import type { ReadingQuestion } from '../../../../types'
import { rhymeRoutesPoemDefinitions } from './poems'
import {
  RHYME_ROUTES_CONTENT_VERSION,
  RHYME_ROUTES_LESSON_KEYS,
  RHYME_ROUTES_PACK_ID,
  RHYME_ROUTES_POEM_KEYS,
  poetryLineId,
  poetryQuestionId,
} from './ids'
import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from './questionFactories'

const common = {
  benchmarkReference: 'ELA.2.R.1.4',
  skillIdentifier: 'g2-poetry-planet-poetry',
  reportingCategory: 'Reading Prose and Poetry',
  genre: 'literary',
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2',
  contentVersion: RHYME_ROUTES_CONTENT_VERSION,
  reviewStatus: 'DRAFT' as const,
}

const lessonAId = `${RHYME_ROUTES_PACK_ID}-lesson-${RHYME_ROUTES_LESSON_KEYS.buildingBlockA}`
const lessonBId = `${RHYME_ROUTES_PACK_ID}-lesson-${RHYME_ROUTES_LESSON_KEYS.buildingBlockB}`

const poemA = rhymeRoutesPoemDefinitions.find((poem) => poem.key === RHYME_ROUTES_POEM_KEYS.kiteDay)!
const poemB = rhymeRoutesPoemDefinitions.find((poem) => poem.key === RHYME_ROUTES_POEM_KEYS.gardenCare)!

const mc = (spec: Parameters<typeof createMultipleChoiceQuestion>[0]) => createMultipleChoiceQuestion(spec)
const ms = (spec: Parameters<typeof createMultiselectQuestion>[0]) => createMultiselectQuestion(spec)
const ht = (spec: Parameters<typeof createHotTextQuestion>[0]) => createHotTextQuestion(spec)
const tm = (spec: Parameters<typeof createTableMatchQuestion>[0]) => createTableMatchQuestion(spec)

export const rhymeRoutesBuildingBlockQuestions: ReadingQuestion[] = [
  mc({
    ...common,
    difficulty: 0,
    passageIdentifier: poemA.passageId,
    lessonIdentifier: lessonAId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.buildingBlockA, 'mc-1'),
    prompt: 'Which pair of end words rhymes?',
    explanation: 'day and play rhyme because their ending sounds match.',
    evidenceReference: 'rhyme-pair',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.kiteDay, 1), poetryLineId(RHYME_ROUTES_POEM_KEYS.kiteDay, 2)],
    targetVocabulary: ['day', 'play', 'rhyme'],
    soundOutChunks: ['d-ay', 'pl-ay', 'rhyme'],
    tags: ['rhyme-scheme-identification', 'line-end-word-identification', 'end-rhyme-identification', 'rhyme-by-sound'],
    choices: [
      { id: 'choice-a', text: 'day and hand' },
      { id: 'choice-b', text: 'day and land' },
      { id: 'choice-c', text: 'play and hand' },
      { id: 'choice-d', text: 'day and play' },
    ],
    correctChoiceIds: ['choice-d'],
  }),
  mc({
    ...common,
    difficulty: 0,
    passageIdentifier: poemA.passageId,
    lessonIdentifier: lessonAId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.buildingBlockA, 'mc-2'),
    prompt: 'Which line should share the letter A with line 1?',
    explanation: 'Line 2 ends with play, which rhymes with day.',
    evidenceReference: 'same-letter',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.kiteDay, 1), poetryLineId(RHYME_ROUTES_POEM_KEYS.kiteDay, 2)],
    targetVocabulary: ['letter', 'same', 'rhymes'],
    soundOutChunks: ['let-ter', 'same', 'rhymes'],
    tags: ['rhyme-scheme-notation', 'same-rhyme-same-letter'],
    choices: [
      { id: 'choice-a', text: 'line 3' },
      { id: 'choice-b', text: 'line 4' },
      { id: 'choice-c', text: 'line 2' },
      { id: 'choice-d', text: 'line 1' },
    ],
    correctChoiceIds: ['choice-c'],
  }),
  ms({
    ...common,
    difficulty: 0,
    passageIdentifier: poemA.passageId,
    lessonIdentifier: lessonAId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.buildingBlockA, 'ms-1'),
    prompt: 'Choose both lines that rhyme with hand.',
    explanation: 'Lines 3 and 4 end with hand and land, which rhyme together.',
    evidenceReference: 'rhyme-family',
    evidenceReferenceIds: [
      poetryLineId(RHYME_ROUTES_POEM_KEYS.kiteDay, 3),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.kiteDay, 4),
    ],
    targetVocabulary: ['hand', 'land', 'rhyme'],
    soundOutChunks: ['hand', 'land', 'rhyme'],
    tags: ['end-rhyme-identification', 'rhyme-by-sound', 'same-rhyme-same-letter'],
    choices: [
      { id: 'choice-a', text: 'I tied the kite for the day.' },
      { id: 'choice-b', text: 'Then I sent it up to play.' },
      { id: 'choice-c', text: 'I held the string in my hand.' },
      { id: 'choice-d', text: 'The kite danced high over the land.' },
    ],
    correctChoiceIds: ['choice-c', 'choice-d'],
  }),
  ht({
    ...common,
    difficulty: 0,
    passageIdentifier: poemA.passageId,
    lessonIdentifier: lessonAId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.buildingBlockA, 'ht-1'),
    prompt: 'Select the line that rhymes with line 1.',
    explanation: 'Line 2 ends with play, which rhymes with day.',
    evidenceReference: 'matching-line',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.kiteDay, 1), poetryLineId(RHYME_ROUTES_POEM_KEYS.kiteDay, 2)],
    targetVocabulary: ['day', 'play', 'line'],
    soundOutChunks: ['d-ay', 'pl-ay', 'line'],
    tags: ['line-end-word-identification', 'end-rhyme-identification'],
    selectableSegments: [
      { id: 'segment-1', text: 'I held the string in my hand.' },
      { id: 'segment-2', text: 'Then I sent it up to play.' },
      { id: 'segment-3', text: 'The kite danced high over the land.' },
    ],
    correctSegmentIds: ['segment-2'],
  }),
  tm({
    ...common,
    difficulty: 0,
    passageIdentifier: poemA.passageId,
    lessonIdentifier: lessonAId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.buildingBlockA, 'tm-1'),
    prompt: 'Match each line number to its rhyme letter.',
    explanation: 'The first two lines rhyme and get A. The last two lines rhyme and get B.',
    evidenceReference: 'line-to-letter',
    evidenceReferenceIds: [
      poetryLineId(RHYME_ROUTES_POEM_KEYS.kiteDay, 1),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.kiteDay, 2),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.kiteDay, 3),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.kiteDay, 4),
    ],
    targetVocabulary: ['letter', 'rhyme', 'scheme'],
    soundOutChunks: ['let-ter', 'rhyme', 'scheme'],
    tags: ['rhyme-scheme-notation', 'whole-poem-scheme'],
    rows: [
      {
        id: 'row-1',
        prompt: 'Line 1',
        correctChoiceId: 'letter-a',
        options: [
          { id: 'letter-a', text: 'A' },
          { id: 'letter-b', text: 'B' },
          { id: 'letter-c', text: 'C' },
          { id: 'letter-d', text: 'D' },
        ],
      },
      {
        id: 'row-2',
        prompt: 'Line 2',
        correctChoiceId: 'letter-a-2',
        options: [
          { id: 'letter-a-2', text: 'A' },
          { id: 'letter-b-2', text: 'B' },
          { id: 'letter-c-2', text: 'C' },
          { id: 'letter-d-2', text: 'D' },
        ],
      },
      {
        id: 'row-3',
        prompt: 'Line 3',
        correctChoiceId: 'letter-b-3',
        options: [
          { id: 'letter-a-3', text: 'A' },
          { id: 'letter-b-3', text: 'B' },
          { id: 'letter-c-3', text: 'C' },
          { id: 'letter-d-3', text: 'D' },
        ],
      },
      {
        id: 'row-4',
        prompt: 'Line 4',
        correctChoiceId: 'letter-b-4',
        options: [
          { id: 'letter-a-4', text: 'A' },
          { id: 'letter-b-4', text: 'B' },
          { id: 'letter-c-4', text: 'C' },
          { id: 'letter-d-4', text: 'D' },
        ],
      },
    ],
  }),
  mc({
    ...common,
    difficulty: 0,
    passageIdentifier: poemB.passageId,
    lessonIdentifier: lessonBId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.buildingBlockB, 'mc-1'),
    prompt: 'Which line gets the first new letter C?',
    explanation: 'Line 5 ends with near, which starts a new rhyme family after the B lines.',
    evidenceReference: 'new-letter',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.gardenCare, 5)],
    targetVocabulary: ['new', 'letter', 'family'],
    soundOutChunks: ['new', 'let-ter', 'fam-i-ly'],
    tags: ['rhyme-scheme-notation', 'new-rhyme-next-letter'],
    choices: [
      { id: 'choice-a', text: 'line 1' },
      { id: 'choice-b', text: 'line 3' },
      { id: 'choice-c', text: 'line 5' },
      { id: 'choice-d', text: 'line 6' },
    ],
    correctChoiceIds: ['choice-c'],
  }),
  mc({
    ...common,
    difficulty: 0,
    passageIdentifier: poemB.passageId,
    lessonIdentifier: lessonBId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.buildingBlockB, 'mc-2'),
    prompt: 'Which pair shows the same rhyme sound?',
    explanation: 'bare and care sound alike at the end, so they get the same letter.',
    evidenceReference: 'same-sound',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.gardenCare, 1), poetryLineId(RHYME_ROUTES_POEM_KEYS.gardenCare, 2)],
    targetVocabulary: ['bare', 'care', 'sound'],
    soundOutChunks: ['bare', 'care', 'sound'],
    tags: ['line-end-word-identification', 'end-rhyme-identification', 'rhyme-by-sound'],
    choices: [
      { id: 'choice-a', text: 'bare and care' },
      { id: 'choice-b', text: 'dirt and near' },
      { id: 'choice-c', text: 'hurt and clear' },
      { id: 'choice-d', text: 'bare and near' },
    ],
    correctChoiceIds: ['choice-a'],
  }),
  ms({
    ...common,
    difficulty: 0,
    passageIdentifier: poemB.passageId,
    lessonIdentifier: lessonBId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.buildingBlockB, 'ms-1'),
    prompt: 'Choose both lines that rhyme with dirt.',
    explanation: 'Lines 3 and 4 end with dirt and hurt, which rhyme together.',
    evidenceReference: 'b-family',
    evidenceReferenceIds: [
      poetryLineId(RHYME_ROUTES_POEM_KEYS.gardenCare, 3),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.gardenCare, 4),
    ],
    targetVocabulary: ['dirt', 'hurt', 'rhyme'],
    soundOutChunks: ['dirt', 'hurt', 'rhyme'],
    tags: ['same-rhyme-same-letter', 'end-rhyme-identification'],
    choices: [
      { id: 'choice-a', text: 'At dawn, the garden looked bare.' },
      { id: 'choice-b', text: 'Nia planted seeds with careful care.' },
      { id: 'choice-c', text: 'She pressed each seed into the dirt.' },
      { id: 'choice-d', text: 'Then she watered gently, not to hurt.' },
    ],
    correctChoiceIds: ['choice-c', 'choice-d'],
  }),
  ht({
    ...common,
    difficulty: 0,
    passageIdentifier: poemB.passageId,
    lessonIdentifier: lessonBId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.buildingBlockB, 'ht-1'),
    prompt: 'Select the line that ends with clear.',
    explanation: 'Line 6 ends with clear, which rhymes with near.',
    evidenceReference: 'last-line',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.gardenCare, 6)],
    targetVocabulary: ['clear', 'near', 'line'],
    soundOutChunks: ['cl-ear', 'n-ear', 'line'],
    tags: ['line-end-word-identification', 'end-rhyme-identification'],
    selectableSegments: [
      { id: 'segment-1', text: 'At dawn, the garden looked bare.' },
      { id: 'segment-2', text: 'By noon, a small green sprout stood near.' },
      { id: 'segment-3', text: 'Nia smiled because the sign was clear.' },
    ],
    correctSegmentIds: ['segment-3'],
  }),
  tm({
    ...common,
    difficulty: 0,
    passageIdentifier: poemB.passageId,
    lessonIdentifier: lessonBId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.buildingBlockB, 'tm-1'),
    prompt: 'Match each line number to its rhyme letter.',
    explanation: 'Lines 1 and 2 get A, lines 3 and 4 get B, and lines 5 and 6 get C.',
    evidenceReference: 'letter-map',
    evidenceReferenceIds: [
      poetryLineId(RHYME_ROUTES_POEM_KEYS.gardenCare, 1),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.gardenCare, 2),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.gardenCare, 3),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.gardenCare, 4),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.gardenCare, 5),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.gardenCare, 6),
    ],
    targetVocabulary: ['letter', 'scheme', 'rhyme'],
    soundOutChunks: ['let-ter', 'scheme', 'rhyme'],
    tags: ['rhyme-scheme-notation', 'whole-poem-scheme'],
    rows: [
      {
        id: 'row-1',
        prompt: 'Line 1',
        correctChoiceId: 'letter-a',
        options: [
          { id: 'letter-a', text: 'A' },
          { id: 'letter-b', text: 'B' },
          { id: 'letter-c', text: 'C' },
        ],
      },
      {
        id: 'row-2',
        prompt: 'Line 2',
        correctChoiceId: 'letter-a-2',
        options: [
          { id: 'letter-a-2', text: 'A' },
          { id: 'letter-b-2', text: 'B' },
          { id: 'letter-c-2', text: 'C' },
        ],
      },
      {
        id: 'row-3',
        prompt: 'Line 3',
        correctChoiceId: 'letter-b-3',
        options: [
          { id: 'letter-a-3', text: 'A' },
          { id: 'letter-b-3', text: 'B' },
          { id: 'letter-c-3', text: 'C' },
        ],
      },
      {
        id: 'row-4',
        prompt: 'Line 4',
        correctChoiceId: 'letter-b-4',
        options: [
          { id: 'letter-a-4', text: 'A' },
          { id: 'letter-b-4', text: 'B' },
          { id: 'letter-c-4', text: 'C' },
        ],
      },
      {
        id: 'row-5',
        prompt: 'Line 5',
        correctChoiceId: 'letter-c-5',
        options: [
          { id: 'letter-a-5', text: 'A' },
          { id: 'letter-b-5', text: 'B' },
          { id: 'letter-c-5', text: 'C' },
        ],
      },
      {
        id: 'row-6',
        prompt: 'Line 6',
        correctChoiceId: 'letter-c-6',
        options: [
          { id: 'letter-a-6', text: 'A' },
          { id: 'letter-b-6', text: 'B' },
          { id: 'letter-c-6', text: 'C' },
        ],
      },
    ],
  }),
]
