import type { ReadingQuestion } from '../../../../types'
import { rhymeRoutesPoemDefinitions } from './poems'
import {
  RHYME_ROUTES_CONTENT_VERSION,
  RHYME_ROUTES_LESSON_KEYS,
  RHYME_ROUTES_PACK_ID,
  RHYME_ROUTES_POEM_KEYS,
  poetryLineId,
  poetryQuestionId,
} from './ids'
import {
  createEvidencePairQuestion,
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from './questionFactories'

const common = {
  benchmarkReference: 'ELA.2.R.1.4',
  skillIdentifier: 'g2-poetry-planet-poetry',
  reportingCategory: 'Reading Prose and Poetry',
  genre: 'literary',
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2',
  contentVersion: RHYME_ROUTES_CONTENT_VERSION,
  reviewStatus: 'DRAFT' as const,
}

const lessonAId = `${RHYME_ROUTES_PACK_ID}-lesson-${RHYME_ROUTES_LESSON_KEYS.checkpointA}`
const lessonBId = `${RHYME_ROUTES_PACK_ID}-lesson-${RHYME_ROUTES_LESSON_KEYS.checkpointB}`
const lessonCId = `${RHYME_ROUTES_PACK_ID}-lesson-${RHYME_ROUTES_LESSON_KEYS.checkpointC}`

const poemA = rhymeRoutesPoemDefinitions.find((poem) => poem.key === RHYME_ROUTES_POEM_KEYS.helpGate)!
const poemB = rhymeRoutesPoemDefinitions.find((poem) => poem.key === RHYME_ROUTES_POEM_KEYS.weatherNotes)!
const poemC = rhymeRoutesPoemDefinitions.find((poem) => poem.key === RHYME_ROUTES_POEM_KEYS.stagePage)!

const mc = (spec: Parameters<typeof createMultipleChoiceQuestion>[0]) => createMultipleChoiceQuestion(spec)
const ms = (spec: Parameters<typeof createMultiselectQuestion>[0]) => createMultiselectQuestion(spec)
const ht = (spec: Parameters<typeof createHotTextQuestion>[0]) => createHotTextQuestion(spec)
const tm = (spec: Parameters<typeof createTableMatchQuestion>[0]) => createTableMatchQuestion(spec)
const ep = (spec: Parameters<typeof createEvidencePairQuestion>[0]) => createEvidencePairQuestion(spec)

export const rhymeRoutesCheckpointQuestions: ReadingQuestion[] = [
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: poemA.passageId,
    lessonIdentifier: lessonAId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointA, 'mc-1'),
    prompt: 'What rhyme scheme is best supported by the poem?',
    explanation: 'The poem uses AABB because the first two lines rhyme and the last two lines rhyme.',
    evidenceReference: 'scheme',
    evidenceReferenceIds: [
      poetryLineId(RHYME_ROUTES_POEM_KEYS.helpGate, 1),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.helpGate, 2),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.helpGate, 3),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.helpGate, 4),
    ],
    targetVocabulary: ['scheme', 'letter', 'rhyme'],
    soundOutChunks: ['scheme', 'let-ter', 'rhyme'],
    tags: ['rhyme-scheme-identification', 'rhyme-scheme-notation', 'whole-poem-scheme', 'notation-starts-with-a'],
    choices: [
      { id: 'choice-a', text: 'ABAB' },
      { id: 'choice-b', text: 'AABBCC' },
      { id: 'choice-c', text: 'ABCB' },
      { id: 'choice-d', text: 'AABB' },
    ],
    correctChoiceIds: ['choice-d'],
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: poemA.passageId,
    lessonIdentifier: lessonAId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointA, 'mc-2'),
    prompt: 'Which line should get letter B?',
    explanation: 'Line 3 starts the new rhyme family with rope, so it gets B.',
    evidenceReference: 'new-letter',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.helpGate, 3)],
    targetVocabulary: ['letter', 'new', 'rhyme'],
    soundOutChunks: ['let-ter', 'new', 'rhyme'],
    tags: ['rhyme-scheme-notation', 'new-rhyme-next-letter'],
    choices: [
      { id: 'choice-a', text: 'line 1' },
      { id: 'choice-b', text: 'line 2' },
      { id: 'choice-c', text: 'line 3' },
      { id: 'choice-d', text: 'line 4' },
    ],
    correctChoiceIds: ['choice-c'],
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: poemA.passageId,
    lessonIdentifier: lessonAId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointA, 'mc-3'),
    prompt: 'Which pair of end words shows the A rhyme?',
    explanation: 'gate and wait sound alike at the end, so they share A.',
    evidenceReference: 'a-pair',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.helpGate, 1), poetryLineId(RHYME_ROUTES_POEM_KEYS.helpGate, 2)],
    targetVocabulary: ['gate', 'wait', 'rhyme'],
    soundOutChunks: ['gate', 'wait', 'rhyme'],
    tags: ['line-end-word-identification', 'end-rhyme-identification', 'rhyme-by-sound'],
    choices: [
      { id: 'choice-a', text: 'gate and wait' },
      { id: 'choice-b', text: 'rope and hope' },
      { id: 'choice-c', text: 'gate and hope' },
      { id: 'choice-d', text: 'wait and rope' },
    ],
    correctChoiceIds: ['choice-a'],
  }),
  ms({
    ...common,
    difficulty: 1,
    passageIdentifier: poemA.passageId,
    lessonIdentifier: lessonAId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointA, 'ms-1'),
    prompt: 'Choose all lines that should get letter A.',
    explanation: 'Lines 1 and 2 rhyme with each other, so they both get A.',
    evidenceReference: 'a-lines',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.helpGate, 1), poetryLineId(RHYME_ROUTES_POEM_KEYS.helpGate, 2)],
    targetVocabulary: ['letter', 'same', 'rhyme'],
    soundOutChunks: ['let-ter', 'same', 'rhyme'],
    tags: ['same-rhyme-same-letter', 'whole-poem-scheme'],
    choices: [
      { id: 'choice-a', text: 'Ari forgot the map by the gate.' },
      { id: 'choice-b', text: 'So Bea came back to help him wait.' },
      { id: 'choice-c', text: 'They found the sign and fixed the rope.' },
      { id: 'choice-d', text: 'Then both kids smiled with fresh new hope.' },
    ],
    correctChoiceIds: ['choice-a', 'choice-b'],
  }),
  ht({
    ...common,
    difficulty: 1,
    passageIdentifier: poemA.passageId,
    lessonIdentifier: lessonAId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointA, 'ht-1'),
    prompt: 'Select the line that rhymes with line 3.',
    explanation: 'Line 4 ends with hope, which rhymes with rope.',
    evidenceReference: 'matching-line',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.helpGate, 3), poetryLineId(RHYME_ROUTES_POEM_KEYS.helpGate, 4)],
    targetVocabulary: ['rope', 'hope', 'line'],
    soundOutChunks: ['rope', 'hope', 'line'],
    tags: ['line-end-word-identification', 'end-rhyme-identification'],
    selectableSegments: [
      { id: 'segment-1', text: 'Ari forgot the map by the gate.' },
      { id: 'segment-2', text: 'So Bea came back to help him wait.' },
      { id: 'segment-3', text: 'Then both kids smiled with fresh new hope.' },
    ],
    correctSegmentIds: ['segment-3'],
  }),
  tm({
    ...common,
    difficulty: 1,
    passageIdentifier: poemA.passageId,
    lessonIdentifier: lessonAId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointA, 'tm-1'),
    prompt: 'Match each line number to its rhyme letter.',
    explanation: 'The first two lines get A and the last two lines get B.',
    evidenceReference: 'scheme-map',
    evidenceReferenceIds: [
      poetryLineId(RHYME_ROUTES_POEM_KEYS.helpGate, 1),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.helpGate, 2),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.helpGate, 3),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.helpGate, 4),
    ],
    targetVocabulary: ['letter', 'scheme', 'rhyme'],
    soundOutChunks: ['let-ter', 'scheme', 'rhyme'],
    tags: ['rhyme-scheme-notation', 'whole-poem-scheme', 'uppercase-rhyme-labels'],
    rows: [
      {
        id: 'row-1',
        prompt: 'Line 1',
        correctChoiceId: 'letter-a',
        options: [
          { id: 'letter-a', text: 'A' },
          { id: 'letter-b', text: 'B' },
        ],
      },
      {
        id: 'row-2',
        prompt: 'Line 2',
        correctChoiceId: 'letter-a-2',
        options: [
          { id: 'letter-a-2', text: 'A' },
          { id: 'letter-b-2', text: 'B' },
        ],
      },
      {
        id: 'row-3',
        prompt: 'Line 3',
        correctChoiceId: 'letter-b-3',
        options: [
          { id: 'letter-a-3', text: 'A' },
          { id: 'letter-b-3', text: 'B' },
        ],
      },
      {
        id: 'row-4',
        prompt: 'Line 4',
        correctChoiceId: 'letter-b-4',
        options: [
          { id: 'letter-a-4', text: 'A' },
          { id: 'letter-b-4', text: 'B' },
        ],
      },
    ],
  }),
  ep({
    ...common,
    difficulty: 1,
    passageIdentifier: poemA.passageId,
    lessonIdentifier: lessonAId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointA, 'ep-1'),
    prompt: 'Which rhyme scheme is best supported by the story?',
    explanation: 'The poem uses AABB because the first two lines rhyme and the last two lines rhyme.',
    evidenceReference: 'best-supported-scheme',
    evidenceReferenceIds: [
      poetryLineId(RHYME_ROUTES_POEM_KEYS.helpGate, 1),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.helpGate, 2),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.helpGate, 3),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.helpGate, 4),
    ],
    targetVocabulary: ['scheme', 'line-end', 'rhyme'],
    soundOutChunks: ['scheme', 'line-end', 'rhyme'],
    tags: ['rhyme-scheme-identification', 'rhyme-scheme-notation', 'scheme-supported-by-end-words'],
    partAChoices: [
      { id: 'part-a-1', text: 'AABB' },
      { id: 'part-a-2', text: 'ABAB' },
      { id: 'part-a-3', text: 'ABCB' },
      { id: 'part-a-4', text: 'AABBCC' },
    ],
    partACorrectChoiceId: 'part-a-1',
    partBChoices: [
      { id: 'part-b-1', text: 'gate and wait' },
      { id: 'part-b-2', text: 'rope and hope' },
      { id: 'part-b-3', text: 'gate and hope' },
      { id: 'part-b-4', text: 'wait and rope' },
    ],
    partBCorrectChoiceId: 'part-b-1',
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: poemB.passageId,
    lessonIdentifier: lessonBId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointB, 'mc-1'),
    prompt: 'What rhyme scheme is best supported by the poem?',
    explanation: 'The poem uses ABABCDCD because the first and third lines rhyme, the second and fourth lines rhyme, the fifth and seventh lines rhyme, and the sixth and eighth lines rhyme.',
    evidenceReference: 'scheme',
    evidenceReferenceIds: [
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 1),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 2),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 3),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 4),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 5),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 6),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 7),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 8),
    ],
    targetVocabulary: ['scheme', 'letters', 'rhyme'],
    soundOutChunks: ['scheme', 'let-ters', 'rhyme'],
    tags: ['rhyme-scheme-identification', 'rhyme-scheme-notation', 'whole-poem-scheme'],
    choices: [
      { id: 'choice-a', text: 'AABBCCDD' },
      { id: 'choice-b', text: 'AABB' },
      { id: 'choice-c', text: 'ABCB' },
      { id: 'choice-d', text: 'ABABCDCD' },
    ],
    correctChoiceIds: ['choice-d'],
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: poemB.passageId,
    lessonIdentifier: lessonBId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointB, 'mc-2'),
    prompt: 'Which line should share the letter A with line 1?',
    explanation: 'Line 3 ends with blow, which rhymes with row.',
    evidenceReference: 'same-letter',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 1), poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 3)],
    targetVocabulary: ['same', 'letter', 'rhyme'],
    soundOutChunks: ['same', 'let-ter', 'rhyme'],
    tags: ['same-rhyme-same-letter', 'line-end-word-identification'],
    choices: [
      { id: 'choice-a', text: 'line 2' },
      { id: 'choice-b', text: 'line 3' },
      { id: 'choice-c', text: 'line 4' },
      { id: 'choice-d', text: 'line 5' },
    ],
    correctChoiceIds: ['choice-b'],
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: poemB.passageId,
    lessonIdentifier: lessonBId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointB, 'mc-3'),
    prompt: 'Which line should get the same letter as line 6?',
    explanation: 'Line 8 ends with night, which rhymes with light.',
    evidenceReference: 'new-letter',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 6), poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 8)],
    targetVocabulary: ['letter', 'new', 'rhyme'],
    soundOutChunks: ['let-ter', 'new', 'rhyme'],
    tags: ['new-rhyme-next-letter', 'same-rhyme-same-letter'],
    choices: [
      { id: 'choice-a', text: 'line 1' },
      { id: 'choice-b', text: 'line 4' },
      { id: 'choice-c', text: 'line 7' },
      { id: 'choice-d', text: 'line 8' },
    ],
    correctChoiceIds: ['choice-d'],
  }),
  ms({
    ...common,
    difficulty: 1,
    passageIdentifier: poemB.passageId,
    lessonIdentifier: lessonBId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointB, 'ms-1'),
    prompt: 'Choose all lines that rhyme with slow.',
    explanation: 'Lines 2 and 4 end with slow, so they get the same B letter.',
    evidenceReference: 'b-lines',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 2), poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 4)],
    targetVocabulary: ['slow', 'rhyme', 'letter'],
    soundOutChunks: ['slow', 'rhyme', 'let-ter'],
    tags: ['end-rhyme-identification', 'same-rhyme-same-letter'],
    choices: [
      { id: 'choice-a', text: 'Lena set the cups in a row.' },
      { id: 'choice-b', text: 'She watched the cotton clouds move slow.' },
      { id: 'choice-c', text: 'They saw the clouds move across the sky.' },
      { id: 'choice-d', text: 'She nodded when the pieces stayed slow.' },
    ],
    correctChoiceIds: ['choice-b', 'choice-d'],
  }),
  ht({
    ...common,
    difficulty: 1,
    passageIdentifier: poemB.passageId,
    lessonIdentifier: lessonBId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointB, 'ht-1'),
    prompt: 'Select the line that rhymes with line 5.',
    explanation: 'Line 7 ends with sky, which rhymes with high.',
    evidenceReference: 'matching-line',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 5), poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 7)],
    targetVocabulary: ['high', 'sky', 'line'],
    soundOutChunks: ['high', 'sky', 'line'],
    tags: ['line-end-word-identification', 'end-rhyme-identification'],
    selectableSegments: [
      { id: 'segment-1', text: 'Then Omar held the chart up high.' },
      { id: 'segment-2', text: 'He pointed to the bright red light.' },
      { id: 'segment-3', text: 'They saw the clouds move across the sky.' },
    ],
    correctSegmentIds: ['segment-3'],
  }),
  tm({
    ...common,
    difficulty: 1,
    passageIdentifier: poemB.passageId,
    lessonIdentifier: lessonBId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointB, 'tm-1'),
    prompt: 'Match each line number to its rhyme letter.',
    explanation: 'The poem follows ABABCDCD.',
    evidenceReference: 'scheme-map',
    evidenceReferenceIds: [
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 1),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 2),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 3),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 4),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 5),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 6),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 7),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 8),
    ],
    targetVocabulary: ['letter', 'scheme', 'rhyme'],
    soundOutChunks: ['let-ter', 'scheme', 'rhyme'],
    tags: ['rhyme-scheme-notation', 'whole-poem-scheme'],
    rows: [
      { id: 'row-1', prompt: 'Line 1', correctChoiceId: 'letter-a', options: [{ id: 'letter-a', text: 'A' }, { id: 'letter-b', text: 'B' }, { id: 'letter-c', text: 'C' }, { id: 'letter-d', text: 'D' }] },
      { id: 'row-2', prompt: 'Line 2', correctChoiceId: 'letter-b-2', options: [{ id: 'letter-a-2', text: 'A' }, { id: 'letter-b-2', text: 'B' }, { id: 'letter-c-2', text: 'C' }, { id: 'letter-d-2', text: 'D' }] },
      { id: 'row-3', prompt: 'Line 3', correctChoiceId: 'letter-a-3', options: [{ id: 'letter-a-3', text: 'A' }, { id: 'letter-b-3', text: 'B' }, { id: 'letter-c-3', text: 'C' }, { id: 'letter-d-3', text: 'D' }] },
      { id: 'row-4', prompt: 'Line 4', correctChoiceId: 'letter-b-4', options: [{ id: 'letter-a-4', text: 'A' }, { id: 'letter-b-4', text: 'B' }, { id: 'letter-c-4', text: 'C' }, { id: 'letter-d-4', text: 'D' }] },
      { id: 'row-5', prompt: 'Line 5', correctChoiceId: 'letter-c-5', options: [{ id: 'letter-a-5', text: 'A' }, { id: 'letter-b-5', text: 'B' }, { id: 'letter-c-5', text: 'C' }, { id: 'letter-d-5', text: 'D' }] },
      { id: 'row-6', prompt: 'Line 6', correctChoiceId: 'letter-d-6', options: [{ id: 'letter-a-6', text: 'A' }, { id: 'letter-b-6', text: 'B' }, { id: 'letter-c-6', text: 'C' }, { id: 'letter-d-6', text: 'D' }] },
      { id: 'row-7', prompt: 'Line 7', correctChoiceId: 'letter-c-7', options: [{ id: 'letter-a-7', text: 'A' }, { id: 'letter-b-7', text: 'B' }, { id: 'letter-c-7', text: 'C' }, { id: 'letter-d-7', text: 'D' }] },
      { id: 'row-8', prompt: 'Line 8', correctChoiceId: 'letter-d-8', options: [{ id: 'letter-a-8', text: 'A' }, { id: 'letter-b-8', text: 'B' }, { id: 'letter-c-8', text: 'C' }, { id: 'letter-d-8', text: 'D' }] },
    ],
  }),
  ep({
    ...common,
    difficulty: 1,
    passageIdentifier: poemB.passageId,
    lessonIdentifier: lessonBId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointB, 'ep-1'),
    prompt: 'Which rhyme scheme is best supported by the story?',
    explanation: 'The poem uses ABABCDCD, and the matching end words show each letter pattern.',
    evidenceReference: 'best-supported-scheme',
    evidenceReferenceIds: [
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 1),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 2),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 3),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 4),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 5),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 6),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 7),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.weatherNotes, 8),
    ],
    targetVocabulary: ['scheme', 'line-end', 'rhyme'],
    soundOutChunks: ['scheme', 'line-end', 'rhyme'],
    tags: ['rhyme-scheme-identification', 'rhyme-scheme-notation', 'scheme-supported-by-end-words'],
    partAChoices: [
      { id: 'part-a-1', text: 'ABABCDCD' },
      { id: 'part-a-2', text: 'AABBCC' },
      { id: 'part-a-3', text: 'ABCB' },
      { id: 'part-a-4', text: 'AABB' },
    ],
    partACorrectChoiceId: 'part-a-1',
    partBChoices: [
      { id: 'part-b-1', text: 'high and sky' },
      { id: 'part-b-2', text: 'light and night' },
      { id: 'part-b-3', text: 'row and slow' },
      { id: 'part-b-4', text: 'sky and night' },
    ],
    partBCorrectChoiceId: 'part-b-1',
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: poemC.passageId,
    lessonIdentifier: lessonCId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointC, 'mc-1'),
    prompt: 'What rhyme scheme is best supported by the poem?',
    explanation: 'The poem uses ABCB because the second and fourth lines rhyme, while the third line has a new sound.',
    evidenceReference: 'scheme',
    evidenceReferenceIds: [
      poetryLineId(RHYME_ROUTES_POEM_KEYS.stagePage, 1),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.stagePage, 2),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.stagePage, 3),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.stagePage, 4),
    ],
    targetVocabulary: ['scheme', 'letters', 'rhyme'],
    soundOutChunks: ['scheme', 'let-ters', 'rhyme'],
    tags: ['rhyme-scheme-identification', 'rhyme-scheme-notation', 'whole-poem-scheme'],
    choices: [
      { id: 'choice-a', text: 'ABCB' },
      { id: 'choice-b', text: 'ABAB' },
      { id: 'choice-c', text: 'AABB' },
      { id: 'choice-d', text: 'AABBCC' },
    ],
    correctChoiceIds: ['choice-a'],
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: poemC.passageId,
    lessonIdentifier: lessonCId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointC, 'mc-2'),
    prompt: 'Which line should get the new letter C?',
    explanation: 'Line 3 ends with door, which has a new rhyme sound.',
    evidenceReference: 'new-letter',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.stagePage, 3)],
    targetVocabulary: ['new', 'letter', 'rhyme'],
    soundOutChunks: ['new', 'let-ter', 'rhyme'],
    tags: ['new-rhyme-next-letter', 'line-end-word-identification'],
    choices: [
      { id: 'choice-a', text: 'line 1' },
      { id: 'choice-b', text: 'line 2' },
      { id: 'choice-c', text: 'line 4' },
      { id: 'choice-d', text: 'line 3' },
    ],
    correctChoiceIds: ['choice-d'],
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: poemC.passageId,
    lessonIdentifier: lessonCId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointC, 'mc-3'),
    prompt: 'Which line shares line 2’s rhyme sound?',
    explanation: 'Line 4 ends with page, just like line 2.',
    evidenceReference: 'same-letter',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.stagePage, 2), poetryLineId(RHYME_ROUTES_POEM_KEYS.stagePage, 4)],
    targetVocabulary: ['same', 'letter', 'rhyme'],
    soundOutChunks: ['same', 'let-ter', 'rhyme'],
    tags: ['same-rhyme-same-letter', 'end-rhyme-identification'],
    choices: [
      { id: 'choice-a', text: 'line 1' },
      { id: 'choice-b', text: 'line 3' },
      { id: 'choice-c', text: 'line 2' },
      { id: 'choice-d', text: 'line 4' },
    ],
    correctChoiceIds: ['choice-d'],
  }),
  ms({
    ...common,
    difficulty: 1,
    passageIdentifier: poemC.passageId,
    lessonIdentifier: lessonCId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointC, 'ms-1'),
    prompt: 'Choose all lines that get letter B.',
    explanation: 'Lines 2 and 4 both end with page, so they share B.',
    evidenceReference: 'b-lines',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.stagePage, 2), poetryLineId(RHYME_ROUTES_POEM_KEYS.stagePage, 4)],
    targetVocabulary: ['page', 'letter', 'rhyme'],
    soundOutChunks: ['page', 'let-ter', 'rhyme'],
    tags: ['same-rhyme-same-letter', 'whole-poem-scheme'],
    choices: [
      { id: 'choice-a', text: 'Noah carried props to the stage.' },
      { id: 'choice-b', text: 'Iris read the plan on a page.' },
      { id: 'choice-c', text: 'She lined the costumes by the door.' },
      { id: 'choice-d', text: 'Then Noah checked the props once more on the page.' },
    ],
    correctChoiceIds: ['choice-b', 'choice-d'],
  }),
  ht({
    ...common,
    difficulty: 1,
    passageIdentifier: poemC.passageId,
    lessonIdentifier: lessonCId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointC, 'ht-1'),
    prompt: 'Select the line that rhymes with line 2.',
    explanation: 'Line 4 ends with page, which rhymes with line 2.',
    evidenceReference: 'matching-line',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.stagePage, 2), poetryLineId(RHYME_ROUTES_POEM_KEYS.stagePage, 4)],
    targetVocabulary: ['page', 'line', 'rhyme'],
    soundOutChunks: ['page', 'line', 'rhyme'],
    tags: ['line-end-word-identification', 'end-rhyme-identification'],
    selectableSegments: [
      { id: 'segment-1', text: 'Noah carried props to the stage.' },
      { id: 'segment-2', text: 'She lined the costumes by the door.' },
      { id: 'segment-3', text: 'Then Noah checked the props once more on the page.' },
    ],
    correctSegmentIds: ['segment-3'],
  }),
  tm({
    ...common,
    difficulty: 1,
    passageIdentifier: poemC.passageId,
    lessonIdentifier: lessonCId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointC, 'tm-1'),
    prompt: 'Match each line number to its rhyme letter.',
    explanation: 'The poem follows ABCB.',
    evidenceReference: 'scheme-map',
    evidenceReferenceIds: [
      poetryLineId(RHYME_ROUTES_POEM_KEYS.stagePage, 1),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.stagePage, 2),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.stagePage, 3),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.stagePage, 4),
    ],
    targetVocabulary: ['letter', 'scheme', 'rhyme'],
    soundOutChunks: ['let-ter', 'scheme', 'rhyme'],
    tags: ['rhyme-scheme-notation', 'whole-poem-scheme'],
    rows: [
      { id: 'row-1', prompt: 'Line 1', correctChoiceId: 'letter-a', options: [{ id: 'letter-a', text: 'A' }, { id: 'letter-b', text: 'B' }, { id: 'letter-c', text: 'C' }] },
      { id: 'row-2', prompt: 'Line 2', correctChoiceId: 'letter-b-2', options: [{ id: 'letter-a-2', text: 'A' }, { id: 'letter-b-2', text: 'B' }, { id: 'letter-c-2', text: 'C' }] },
      { id: 'row-3', prompt: 'Line 3', correctChoiceId: 'letter-c-3', options: [{ id: 'letter-a-3', text: 'A' }, { id: 'letter-b-3', text: 'B' }, { id: 'letter-c-3', text: 'C' }] },
      { id: 'row-4', prompt: 'Line 4', correctChoiceId: 'letter-b-4', options: [{ id: 'letter-a-4', text: 'A' }, { id: 'letter-b-4', text: 'B' }, { id: 'letter-c-4', text: 'C' }] },
    ],
  }),
  ep({
    ...common,
    difficulty: 1,
    passageIdentifier: poemC.passageId,
    lessonIdentifier: lessonCId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.checkpointC, 'ep-1'),
    prompt: 'Which rhyme scheme is best supported by the story?',
    explanation: 'The poem uses ABCB, and the repeated page sound supports the B rhyme.',
    evidenceReference: 'best-supported-scheme',
    evidenceReferenceIds: [
      poetryLineId(RHYME_ROUTES_POEM_KEYS.stagePage, 1),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.stagePage, 2),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.stagePage, 3),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.stagePage, 4),
    ],
    targetVocabulary: ['scheme', 'line-end', 'rhyme'],
    soundOutChunks: ['scheme', 'line-end', 'rhyme'],
    tags: ['rhyme-scheme-identification', 'rhyme-scheme-notation', 'scheme-supported-by-end-words'],
    partAChoices: [
      { id: 'part-a-1', text: 'ABCB' },
      { id: 'part-a-2', text: 'ABAB' },
      { id: 'part-a-3', text: 'AABB' },
      { id: 'part-a-4', text: 'AABBCC' },
    ],
    partACorrectChoiceId: 'part-a-1',
    partBChoices: [
      { id: 'part-b-1', text: 'page and page' },
      { id: 'part-b-2', text: 'stage and door' },
      { id: 'part-b-3', text: 'page and door' },
      { id: 'part-b-4', text: 'stage and page' },
    ],
    partBCorrectChoiceId: 'part-b-1',
  }),
]
