import type { ReadingQuestion } from '../../../../types'
import { rhymeRoutesPoemDefinitions } from './poems'
import {
  RHYME_ROUTES_CONTENT_VERSION,
  RHYME_ROUTES_LESSON_KEYS,
  RHYME_ROUTES_PACK_ID,
  RHYME_ROUTES_POEM_KEYS,
  poetryLineId,
  poetryQuestionId,
} from './ids'
import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from './questionFactories'

const common = {
  benchmarkReference: 'ELA.2.R.1.4',
  skillIdentifier: 'g2-poetry-planet-poetry',
  reportingCategory: 'Reading Prose and Poetry',
  genre: 'literary',
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2',
  contentVersion: RHYME_ROUTES_CONTENT_VERSION,
  reviewStatus: 'DRAFT' as const,
}

const lessonAId = `${RHYME_ROUTES_PACK_ID}-lesson-${RHYME_ROUTES_LESSON_KEYS.guidedA}`
const lessonBId = `${RHYME_ROUTES_PACK_ID}-lesson-${RHYME_ROUTES_LESSON_KEYS.guidedB}`

const poemA = rhymeRoutesPoemDefinitions.find((poem) => poem.key === RHYME_ROUTES_POEM_KEYS.recycleSpin)!
const poemB = rhymeRoutesPoemDefinitions.find((poem) => poem.key === RHYME_ROUTES_POEM_KEYS.bridgeTool)!

const mc = (spec: Parameters<typeof createMultipleChoiceQuestion>[0]) => createMultipleChoiceQuestion(spec)
const ms = (spec: Parameters<typeof createMultiselectQuestion>[0]) => createMultiselectQuestion(spec)
const ht = (spec: Parameters<typeof createHotTextQuestion>[0]) => createHotTextQuestion(spec)
const tm = (spec: Parameters<typeof createTableMatchQuestion>[0]) => createTableMatchQuestion(spec)

export const rhymeRoutesGuidedQuestions: ReadingQuestion[] = [
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: poemA.passageId,
    lessonIdentifier: lessonAId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.guidedA, 'mc-1'),
    prompt: 'What rhyme scheme does the poem use?',
    explanation: 'The poem uses ABAB because the first and third lines rhyme, and the second and fourth lines rhyme.',
    evidenceReference: 'scheme',
    evidenceReferenceIds: [
      poetryLineId(RHYME_ROUTES_POEM_KEYS.recycleSpin, 1),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.recycleSpin, 2),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.recycleSpin, 3),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.recycleSpin, 4),
    ],
    targetVocabulary: ['scheme', 'letters', 'rhyme'],
    soundOutChunks: ['scheme', 'let-ters', 'rhyme'],
    tags: ['rhyme-scheme-identification', 'rhyme-scheme-notation', 'whole-poem-scheme'],
    choices: [
      { id: 'choice-a', text: 'AABB' },
      { id: 'choice-b', text: 'ABAB' },
      { id: 'choice-c', text: 'ABCB' },
      { id: 'choice-d', text: 'AABBCC' },
    ],
    correctChoiceIds: ['choice-b'],
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: poemA.passageId,
    lessonIdentifier: lessonAId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.guidedA, 'mc-2'),
    prompt: 'Which line should get the same letter as line 1?',
    explanation: 'Line 3 ends with tin, which rhymes with bin.',
    evidenceReference: 'same-letter',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.recycleSpin, 1), poetryLineId(RHYME_ROUTES_POEM_KEYS.recycleSpin, 3)],
    targetVocabulary: ['same', 'letter', 'rhymes'],
    soundOutChunks: ['same', 'let-ter', 'rhymes'],
    tags: ['same-rhyme-same-letter', 'line-end-word-identification'],
    choices: [
      { id: 'choice-a', text: 'line 2' },
      { id: 'choice-b', text: 'line 3' },
      { id: 'choice-c', text: 'line 4' },
      { id: 'choice-d', text: 'line 1' },
    ],
    correctChoiceIds: ['choice-b'],
  }),
  ms({
    ...common,
    difficulty: 1,
    passageIdentifier: poemA.passageId,
    lessonIdentifier: lessonAId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.guidedA, 'ms-1'),
    prompt: 'Choose both lines that rhyme with bin.',
    explanation: 'Lines 1 and 3 end with bin and tin, so they share the A rhyme sound.',
    evidenceReference: 'a-family',
    evidenceReferenceIds: [
      poetryLineId(RHYME_ROUTES_POEM_KEYS.recycleSpin, 1),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.recycleSpin, 3),
    ],
    targetVocabulary: ['bin', 'tin', 'rhyme'],
    soundOutChunks: ['bin', 'tin', 'rhyme'],
    tags: ['end-rhyme-identification', 'rhyme-by-sound', 'same-rhyme-same-letter'],
    choices: [
      { id: 'choice-a', text: 'Mara set the cans beside the bin.' },
      { id: 'choice-b', text: 'With a grin, she checked each label on the side.' },
      { id: 'choice-c', text: 'She stacked the jars beside the tin.' },
      { id: 'choice-d', text: 'With a spin, the cart rolled on a gentle ride.' },
    ],
    correctChoiceIds: ['choice-a', 'choice-c'],
  }),
  ht({
    ...common,
    difficulty: 1,
    passageIdentifier: poemA.passageId,
    lessonIdentifier: lessonAId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.guidedA, 'ht-1'),
    prompt: 'Select the line that rhymes with line 1.',
    explanation: 'Line 3 ends with tin, which rhymes with bin.',
    evidenceReference: 'matching-line',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.recycleSpin, 1), poetryLineId(RHYME_ROUTES_POEM_KEYS.recycleSpin, 3)],
    targetVocabulary: ['bin', 'tin', 'line'],
    soundOutChunks: ['bin', 'tin', 'line'],
    tags: ['line-end-word-identification', 'end-rhyme-identification'],
    selectableSegments: [
      { id: 'segment-1', text: 'With a grin, she checked each label on the side.' },
      { id: 'segment-2', text: 'She stacked the jars beside the tin.' },
      { id: 'segment-3', text: 'With a spin, the cart rolled on a gentle ride.' },
    ],
    correctSegmentIds: ['segment-2'],
  }),
  tm({
    ...common,
    difficulty: 1,
    passageIdentifier: poemA.passageId,
    lessonIdentifier: lessonAId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.guidedA, 'tm-1'),
    prompt: 'Match each line number to its rhyme letter.',
    explanation: 'Lines 1 and 3 get A, and lines 2 and 4 get B.',
    evidenceReference: 'scheme-map',
    evidenceReferenceIds: [
      poetryLineId(RHYME_ROUTES_POEM_KEYS.recycleSpin, 1),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.recycleSpin, 2),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.recycleSpin, 3),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.recycleSpin, 4),
    ],
    targetVocabulary: ['letter', 'scheme', 'rhyme'],
    soundOutChunks: ['let-ter', 'scheme', 'rhyme'],
    tags: ['rhyme-scheme-notation', 'whole-poem-scheme'],
    rows: [
      {
        id: 'row-1',
        prompt: 'Line 1',
        correctChoiceId: 'letter-a',
        options: [
          { id: 'letter-a', text: 'A' },
          { id: 'letter-b', text: 'B' },
        ],
      },
      {
        id: 'row-2',
        prompt: 'Line 2',
        correctChoiceId: 'letter-b-2',
        options: [
          { id: 'letter-a-2', text: 'A' },
          { id: 'letter-b-2', text: 'B' },
        ],
      },
      {
        id: 'row-3',
        prompt: 'Line 3',
        correctChoiceId: 'letter-a-3',
        options: [
          { id: 'letter-a-3', text: 'A' },
          { id: 'letter-b-3', text: 'B' },
        ],
      },
      {
        id: 'row-4',
        prompt: 'Line 4',
        correctChoiceId: 'letter-b-4',
        options: [
          { id: 'letter-a-4', text: 'A' },
          { id: 'letter-b-4', text: 'B' },
        ],
      },
    ],
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: poemB.passageId,
    lessonIdentifier: lessonBId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.guidedB, 'mc-1'),
    prompt: 'What rhyme scheme does the poem use?',
    explanation: 'The poem uses ABCB because the second and fourth lines rhyme, while the third line has a new sound.',
    evidenceReference: 'scheme',
    evidenceReferenceIds: [
      poetryLineId(RHYME_ROUTES_POEM_KEYS.bridgeTool, 1),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.bridgeTool, 2),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.bridgeTool, 3),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.bridgeTool, 4),
    ],
    targetVocabulary: ['scheme', 'letters', 'rhyme'],
    soundOutChunks: ['scheme', 'let-ters', 'rhyme'],
    tags: ['rhyme-scheme-identification', 'rhyme-scheme-notation', 'whole-poem-scheme'],
    choices: [
      { id: 'choice-a', text: 'AABB' },
      { id: 'choice-b', text: 'ABAB' },
      { id: 'choice-c', text: 'ABCB' },
      { id: 'choice-d', text: 'AABBCC' },
    ],
    correctChoiceIds: ['choice-c'],
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: poemB.passageId,
    lessonIdentifier: lessonBId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.guidedB, 'mc-2'),
    prompt: 'Which line has the new middle rhyme?',
    explanation: 'Line 3 ends with row, which is a new rhyme sound in the poem.',
    evidenceReference: 'middle-rhyme',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.bridgeTool, 3)],
    targetVocabulary: ['new', 'middle', 'rhyme'],
    soundOutChunks: ['new', 'mid-dle', 'rhyme'],
    tags: ['new-rhyme-next-letter', 'line-end-word-identification'],
    choices: [
      { id: 'choice-a', text: 'line 1' },
      { id: 'choice-b', text: 'line 4' },
      { id: 'choice-c', text: 'line 3' },
      { id: 'choice-d', text: 'line 2' },
    ],
    correctChoiceIds: ['choice-c'],
  }),
  ms({
    ...common,
    difficulty: 1,
    passageIdentifier: poemB.passageId,
    lessonIdentifier: lessonBId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.guidedB, 'ms-1'),
    prompt: 'Choose both lines that rhyme with tool.',
    explanation: 'Lines 2 and 4 end with tool, so they share the B rhyme sound.',
    evidenceReference: 'b-family',
    evidenceReferenceIds: [
      poetryLineId(RHYME_ROUTES_POEM_KEYS.bridgeTool, 2),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.bridgeTool, 4),
    ],
    targetVocabulary: ['tool', 'rhyme', 'sound'],
    soundOutChunks: ['tool', 'rhyme', 'sound'],
    tags: ['same-rhyme-same-letter', 'end-rhyme-identification'],
    choices: [
      { id: 'choice-a', text: 'The bridge crew brought bright boards from school to the site.' },
      { id: 'choice-b', text: 'Tess checked each plank with a careful tool.' },
      { id: 'choice-c', text: 'She marked the safe spots in a neat row.' },
      { id: 'choice-d', text: 'Then Tess set the hammer beside a stool.' },
    ],
    correctChoiceIds: ['choice-b', 'choice-d'],
  }),
  ht({
    ...common,
    difficulty: 1,
    passageIdentifier: poemB.passageId,
    lessonIdentifier: lessonBId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.guidedB, 'ht-1'),
    prompt: 'Select the line that rhymes with line 2.',
    explanation: 'Line 4 ends with tool, which rhymes with line 2.',
    evidenceReference: 'matching-line',
    evidenceReferenceIds: [poetryLineId(RHYME_ROUTES_POEM_KEYS.bridgeTool, 2), poetryLineId(RHYME_ROUTES_POEM_KEYS.bridgeTool, 4)],
    targetVocabulary: ['tool', 'line', 'rhymes'],
    soundOutChunks: ['tool', 'line', 'rhymes'],
    tags: ['line-end-word-identification', 'end-rhyme-identification'],
    selectableSegments: [
      { id: 'segment-1', text: 'The bridge crew brought bright boards from school to the site.' },
      { id: 'segment-2', text: 'She marked the safe spots in a neat row.' },
      { id: 'segment-3', text: 'Then Tess set the hammer beside a stool.' },
    ],
    correctSegmentIds: ['segment-3'],
  }),
  tm({
    ...common,
    difficulty: 1,
    passageIdentifier: poemB.passageId,
    lessonIdentifier: lessonBId,
    questionIdentifier: poetryQuestionId(RHYME_ROUTES_LESSON_KEYS.guidedB, 'tm-1'),
    prompt: 'Match each line number to its rhyme letter.',
    explanation: 'Line 1 gets A, line 2 gets B, line 3 gets C, and line 4 gets B again.',
    evidenceReference: 'scheme-map',
    evidenceReferenceIds: [
      poetryLineId(RHYME_ROUTES_POEM_KEYS.bridgeTool, 1),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.bridgeTool, 2),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.bridgeTool, 3),
      poetryLineId(RHYME_ROUTES_POEM_KEYS.bridgeTool, 4),
    ],
    targetVocabulary: ['letter', 'scheme', 'rhyme'],
    soundOutChunks: ['let-ter', 'scheme', 'rhyme'],
    tags: ['rhyme-scheme-notation', 'whole-poem-scheme'],
    rows: [
      {
        id: 'row-1',
        prompt: 'Line 1',
        correctChoiceId: 'letter-a',
        options: [
          { id: 'letter-a', text: 'A' },
          { id: 'letter-b', text: 'B' },
          { id: 'letter-c', text: 'C' },
        ],
      },
      {
        id: 'row-2',
        prompt: 'Line 2',
        correctChoiceId: 'letter-b-2',
        options: [
          { id: 'letter-a-2', text: 'A' },
          { id: 'letter-b-2', text: 'B' },
          { id: 'letter-c-2', text: 'C' },
        ],
      },
      {
        id: 'row-3',
        prompt: 'Line 3',
        correctChoiceId: 'letter-c-3',
        options: [
          { id: 'letter-a-3', text: 'A' },
          { id: 'letter-b-3', text: 'B' },
          { id: 'letter-c-3', text: 'C' },
        ],
      },
      {
        id: 'row-4',
        prompt: 'Line 4',
        correctChoiceId: 'letter-b-4',
        options: [
          { id: 'letter-a-4', text: 'A' },
          { id: 'letter-b-4', text: 'B' },
          { id: 'letter-c-4', text: 'C' },
        ],
      },
    ],
  }),
]
