import type { Passage } from '../../../../types'
import type { ThemeDevelopmentGuide } from '../../../contentPackTypes'
import { THEME_DEVELOPMENT_PASSAGE_IDS, THEME_DEVELOPMENT_VERSION } from './ids'

interface SupportSpec {
  targetId: string
  word: string
  sentenceId: string
  focus: string
  chunks: Array<{ displayText: string; speechText: string }>
}

export interface ThemeDevelopmentStoryRecord {
  passageId: string
  title: string
  difficulty: number
  themeFamily: string
  topicLabel: string
  supportedTheme: string
  summaryChoice: string
  unsupportedThemeChoice: string
  unsupportedReason: string
  sentences: Array<{ sentenceId: string; text: string }>
  support: SupportSpec[]
  beginningEvidenceId: string
  middleEvidenceId: string
  turningEvidenceId: string
  endingEvidenceId: string
  minorEvidenceId: string
  beginningEvidenceChoice: string
  middleEvidenceChoice: string
  endingEvidenceChoice: string
  minorEvidenceChoice: string
  characterConnectionStatement: string
  conflictConnectionStatement: string
  developmentSummary: string
}

export const themeDevelopmentStories: ThemeDevelopmentStoryRecord[] = [
  {
    passageId: THEME_DEVELOPMENT_PASSAGE_IDS[0],
    title: 'The Two Bridge Models',
    difficulty: 1,
    themeFamily: 'cooperation',
    topicLabel: 'teamwork',
    supportedTheme: 'Combining different ideas can create a stronger solution than working alone.',
    summaryChoice: 'Lina and Eli build two bridge models and then join their useful parts.',
    unsupportedThemeChoice: 'Friendly competition helps people discover which person has the best idea.',
    unsupportedReason: 'The story resolves the problem by combining ideas, not by choosing a winner.',
    sentences: [
      { sentenceId: 'tdt-p1-s1', text: 'At the camp maker table, Lina and Eli received materials for one model bridge.' },
      { sentenceId: 'tdt-p1-s2', text: 'Lina wanted a tall arch and said, "I can finish faster if I build it myself."' },
      { sentenceId: 'tdt-p1-s3', text: 'Eli suggested a wide base, but Lina moved to a separate corner of the table.' },
      { sentenceId: 'tdt-p1-s4', text: 'Eli quietly built his base while Lina stacked craft sticks into a high curve.' },
      { sentenceId: 'tdt-p1-s5', text: 'During the first test, Lina placed a toy truck on her bridge, and the unsteady sides leaned outward.' },
      { sentenceId: 'tdt-p1-s6', text: 'Eli held the arch before it fell and pointed out that his base had stayed level.' },
      { sentenceId: 'tdt-p1-s7', text: 'Lina studied both models and said, "Your base could support my arch if we join them."' },
      { sentenceId: 'tdt-p1-s8', text: 'They combined the wide base, the curved top, and two braces they designed together.' },
      { sentenceId: 'tdt-p1-s9', text: 'The rebuilt bridge held three trucks without bending.' },
      { sentenceId: 'tdt-p1-s10', text: 'For the next challenge, Lina asked Eli for his idea before either of them picked up a stick.' },
    ],
    support: [
      { targetId: 'tdt-support-1', word: 'materials', sentenceId: 'tdt-p1-s1', focus: 'mater', chunks: [{ displayText: 'ma', speechText: 'muh' }, { displayText: 'te', speechText: 'teer' }, { displayText: 'ri', speechText: 'ree' }, { displayText: 'als', speechText: 'ulz' }] },
      { targetId: 'tdt-support-2', word: 'separate', sentenceId: 'tdt-p1-s3', focus: 'sep', chunks: [{ displayText: 'sep', speechText: 'sep' }, { displayText: 'a', speechText: 'uh' }, { displayText: 'rate', speechText: 'rut' }] },
      { targetId: 'tdt-support-3', word: 'unsteady', sentenceId: 'tdt-p1-s5', focus: 'un', chunks: [{ displayText: 'un', speechText: 'un' }, { displayText: 'stead', speechText: 'sted' }, { displayText: 'y', speechText: 'ee' }] },
      { targetId: 'tdt-support-4', word: 'combined', sentenceId: 'tdt-p1-s8', focus: 'combine', chunks: [{ displayText: 'com', speechText: 'kum' }, { displayText: 'bined', speechText: 'bind' }] },
    ],
    beginningEvidenceId: 'tdt-p1-s2',
    middleEvidenceId: 'tdt-p1-s5',
    turningEvidenceId: 'tdt-p1-s7',
    endingEvidenceId: 'tdt-p1-s10',
    minorEvidenceId: 'tdt-p1-s4',
    beginningEvidenceChoice: 'Lina decides she will work faster by building alone.',
    middleEvidenceChoice: 'Lina\'s tall bridge leans while Eli\'s wide base stays level.',
    endingEvidenceChoice: 'Lina asks for Eli\'s idea before starting the next challenge.',
    minorEvidenceChoice: 'Eli builds in a corner of the maker table.',
    characterConnectionStatement: 'Lina changes from rejecting Eli\'s plan to inviting his ideas after their combined design succeeds.',
    conflictConnectionStatement: 'The failed bridge makes the limits of working separately visible.',
    developmentSummary: 'At the beginning, Lina chooses to work alone. In the middle, her bridge fails while Eli\'s base holds. By the end, their combined bridge succeeds and Lina asks for his idea first.',
  },
  {
    passageId: THEME_DEVELOPMENT_PASSAGE_IDS[1],
    title: 'The Heron Sketch',
    difficulty: 1,
    themeFamily: 'patience',
    topicLabel: 'patience',
    supportedTheme: 'Careful observation and patience can prevent mistakes that rushing may cause.',
    summaryChoice: 'Asha scares away a heron, waits quietly, and later completes her sketch.',
    unsupportedThemeChoice: 'Taking immediate action is usually the best way to reach a goal.',
    unsupportedReason: 'Asha reaches her goal only after she stops rushing and waits quietly.',
    sentences: [
      { sentenceId: 'tdt-p2-s1', text: 'Asha opened her nature journal beside the pond and began an observation sketch.' },
      { sentenceId: 'tdt-p2-s2', text: 'She hurried toward a blue heron because she wanted to finish before lunch.' },
      { sentenceId: 'tdt-p2-s3', text: 'A dry branch cracked under her shoe, and the bird lifted above the reeds.' },
      { sentenceId: 'tdt-p2-s4', text: 'The heron disappeared across the water before Asha had drawn even one feather.' },
      { sentenceId: 'tdt-p2-s5', text: 'Asha sighed, but her guide pointed to a bench partly hidden by tall grass.' },
      { sentenceId: 'tdt-p2-s6', text: '"Watch from there for a while," the guide suggested. "The pond may become calm again."' },
      { sentenceId: 'tdt-p2-s7', text: 'Asha sat motionless and noticed ripples, frog calls, and the shadow of wings returning.' },
      { sentenceId: 'tdt-p2-s8', text: 'The heron landed near the same reeds and slowly stretched its neck.' },
      { sentenceId: 'tdt-p2-s9', text: 'This time Asha stayed on the bench and drew the long legs, pointed bill, and folded wings.' },
      { sentenceId: 'tdt-p2-s10', text: 'Her finished page held more detail than the quick outline she had planned.' },
    ],
    support: [
      { targetId: 'tdt-support-5', word: 'observation', sentenceId: 'tdt-p2-s1', focus: 'tion', chunks: [{ displayText: 'ob', speechText: 'ob' }, { displayText: 'ser', speechText: 'zur' }, { displayText: 'va', speechText: 'vay' }, { displayText: 'tion', speechText: 'shun' }] },
      { targetId: 'tdt-support-6', word: 'hurried', sentenceId: 'tdt-p2-s2', focus: 'hurry', chunks: [{ displayText: 'hur', speechText: 'hur' }, { displayText: 'ried', speechText: 'reed' }] },
      { targetId: 'tdt-support-7', word: 'disappeared', sentenceId: 'tdt-p2-s4', focus: 'dis', chunks: [{ displayText: 'dis', speechText: 'dis' }, { displayText: 'ap', speechText: 'uh' }, { displayText: 'peared', speechText: 'peerd' }] },
      { targetId: 'tdt-support-8', word: 'motionless', sentenceId: 'tdt-p2-s7', focus: 'less', chunks: [{ displayText: 'mo', speechText: 'moh' }, { displayText: 'tion', speechText: 'shun' }, { displayText: 'less', speechText: 'lus' }] },
    ],
    beginningEvidenceId: 'tdt-p2-s2',
    middleEvidenceId: 'tdt-p2-s3',
    turningEvidenceId: 'tdt-p2-s6',
    endingEvidenceId: 'tdt-p2-s10',
    minorEvidenceId: 'tdt-p2-s5',
    beginningEvidenceChoice: 'Asha hurries toward the heron so she can finish quickly.',
    middleEvidenceChoice: 'A branch cracks, and the heron flies away before Asha can draw it.',
    endingEvidenceChoice: 'After waiting quietly, Asha finishes a page with careful details.',
    minorEvidenceChoice: 'The guide points toward a bench near tall grass.',
    characterConnectionStatement: 'Asha changes her approach after rushing costs her the first chance to observe the bird.',
    conflictConnectionStatement: 'The frightened heron creates a consequence that makes waiting and careful observation necessary.',
    developmentSummary: 'At the beginning, Asha rushes toward the bird. In the middle, the heron flies away and the guide suggests waiting. By the end, patient observation lets Asha create a detailed sketch.',
  },
  {
    passageId: THEME_DEVELOPMENT_PASSAGE_IDS[2],
    title: 'The Missing Blue Tile',
    difficulty: 2,
    themeFamily: 'honesty',
    topicLabel: 'honesty',
    supportedTheme: 'Admitting a mistake can rebuild trust and help a group repair a problem.',
    summaryChoice: 'Dev moves a tile tray, admits what happened, and helps restore the mosaic.',
    unsupportedThemeChoice: 'Keeping a problem private protects a team from unnecessary worry.',
    unsupportedReason: 'Dev\'s silence wastes time, while his honest explanation helps the team solve the problem.',
    sentences: [
      { sentenceId: 'tdt-p3-s1', text: 'Dev\'s art club was assembling a river mosaic for the library wall.' },
      { sentenceId: 'tdt-p3-s2', text: 'While reaching for glue, Dev moved a tray of blue tiles without asking whose section it held.' },
      { sentenceId: 'tdt-p3-s3', text: 'The tray tilted, and several small pieces scattered beneath a supply cart.' },
      { sentenceId: 'tdt-p3-s4', text: 'Dev quickly returned the tray to the table, hoping nobody had noticed.' },
      { sentenceId: 'tdt-p3-s5', text: 'Minutes later, Nessa searched for the dark blue pieces needed to complete the deepest part of the river.' },
      { sentenceId: 'tdt-p3-s6', text: 'The club checked boxes, pockets, and the floor near the mosaic, but the pieces stayed hidden.' },
      { sentenceId: 'tdt-p3-s7', text: 'Dev suggested that the tiles might have arrived in the wrong package, although he remembered the tilted tray.' },
      { sentenceId: 'tdt-p3-s8', text: 'As everyone began removing finished sections, a streak of blue dust glimmered on Dev\'s sleeve.' },
      { sentenceId: 'tdt-p3-s9', text: 'He imagined the club taking apart an hour of careful work because he had stayed quiet.' },
      { sentenceId: 'tdt-p3-s10', text: '"I moved the tray, and some tiles slid under the cart," Dev admitted. "I should have told you right away."' },
      { sentenceId: 'tdt-p3-s11', text: 'Nessa looked under the cart, found every missing piece, and thanked Dev for finally explaining the clue.' },
      { sentenceId: 'tdt-p3-s12', text: 'Dev helped restore the loosened sections and labeled each tray before the club continued.' },
      { sentenceId: 'tdt-p3-s13', text: 'When he later spilled three green tiles, he called for a dustpan before anyone began searching.' },
    ],
    support: [
      { targetId: 'tdt-support-9', word: 'mosaic', sentenceId: 'tdt-p3-s1', focus: 'mo', chunks: [{ displayText: 'mo', speechText: 'moh' }, { displayText: 'sa', speechText: 'zay' }, { displayText: 'ic', speechText: 'ik' }] },
      { targetId: 'tdt-support-10', word: 'scattered', sentenceId: 'tdt-p3-s3', focus: 'scatter', chunks: [{ displayText: 'scat', speechText: 'skat' }, { displayText: 'tered', speechText: 'urd' }] },
      { targetId: 'tdt-support-11', word: 'glimmered', sentenceId: 'tdt-p3-s8', focus: 'glim', chunks: [{ displayText: 'glim', speechText: 'glim' }, { displayText: 'mered', speechText: 'urd' }] },
      { targetId: 'tdt-support-12', word: 'restore', sentenceId: 'tdt-p3-s12', focus: 're', chunks: [{ displayText: 're', speechText: 'ree' }, { displayText: 'store', speechText: 'stor' }] },
    ],
    beginningEvidenceId: 'tdt-p3-s4',
    middleEvidenceId: 'tdt-p3-s7',
    turningEvidenceId: 'tdt-p3-s10',
    endingEvidenceId: 'tdt-p3-s13',
    minorEvidenceId: 'tdt-p3-s1',
    beginningEvidenceChoice: 'Dev hides the spill and hopes nobody noticed the moved tray.',
    middleEvidenceChoice: 'Dev gives another explanation even though he remembers the tray tilting.',
    endingEvidenceChoice: 'After a later spill, Dev immediately asks for help cleaning it up.',
    minorEvidenceChoice: 'The club is making a river mosaic for the library.',
    characterConnectionStatement: 'Dev sees that hiding his mistake creates more work, then chooses to speak honestly the next time.',
    conflictConnectionStatement: 'The missing tiles and unnecessary search reveal the cost of Dev\'s silence.',
    developmentSummary: 'At the beginning, Dev hides his mistake. In the middle, his silence leads the group toward unnecessary work until he admits what happened. By the end, he reports a new spill immediately.',
  },
  {
    passageId: THEME_DEVELOPMENT_PASSAGE_IDS[3],
    title: 'The Windy Market Banner',
    difficulty: 2,
    themeFamily: 'flexibility',
    topicLabel: 'flexibility',
    supportedTheme: 'Changing a plan when new information appears can help people reach the same goal.',
    summaryChoice: 'Noor changes one long festival banner into shorter panels after the wind damages it.',
    unsupportedThemeChoice: 'The first plan is usually the fairest choice because it rewards preparation.',
    unsupportedReason: 'The prepared first plan fails in the weather, and adapting it preserves the display goal.',
    sentences: [
      { sentenceId: 'tdt-p4-s1', text: 'Noor designed one long banner for the neighborhood night market.' },
      { sentenceId: 'tdt-p4-s2', text: 'Her arrangement placed every painted lantern in a single bright row above the entrance.' },
      { sentenceId: 'tdt-p4-s3', text: 'On setup afternoon, short gusts snapped the loose end against a fence.' },
      { sentenceId: 'tdt-p4-s4', text: 'Ari suggested cutting the banner into smaller sections, but Noor worried that changing it would ruin the pattern.' },
      { sentenceId: 'tdt-p4-s5', text: 'She tied the long banner tighter and insisted that the original plan would work.' },
      { sentenceId: 'tdt-p4-s6', text: 'The next gust pulled one corner free and tore a painted lantern nearly in half.' },
      { sentenceId: 'tdt-p4-s7', text: 'The weather forecast showed stronger wind arriving before the market opened.' },
      { sentenceId: 'tdt-p4-s8', text: 'Noor looked at the torn corner, then tested one small paper panel between two posts.' },
      { sentenceId: 'tdt-p4-s9', text: 'The panel moved gently but did not whip against either post.' },
      { sentenceId: 'tdt-p4-s10', text: '"We can keep the lantern pattern and change the shape," Noor told Ari.' },
      { sentenceId: 'tdt-p4-s11', text: 'Together they trimmed the banner into four sections and left safe gaps for the wind.' },
      { sentenceId: 'tdt-p4-s12', text: 'That evening, the four glowing panels marked the same entrance without tearing.' },
      { sentenceId: 'tdt-p4-s13', text: 'Noor saved the new measurements beside her original sketch for future outdoor displays.' },
    ],
    support: [
      { targetId: 'tdt-support-13', word: 'arrangement', sentenceId: 'tdt-p4-s2', focus: 'ment', chunks: [{ displayText: 'ar', speechText: 'uh' }, { displayText: 'range', speechText: 'raynj' }, { displayText: 'ment', speechText: 'ment' }] },
      { targetId: 'tdt-support-14', word: 'original', sentenceId: 'tdt-p4-s5', focus: 'origin', chunks: [{ displayText: 'o', speechText: 'uh' }, { displayText: 'rig', speechText: 'rij' }, { displayText: 'i', speechText: 'uh' }, { displayText: 'nal', speechText: 'nul' }] },
      { targetId: 'tdt-support-15', word: 'forecast', sentenceId: 'tdt-p4-s7', focus: 'fore', chunks: [{ displayText: 'fore', speechText: 'for' }, { displayText: 'cast', speechText: 'kast' }] },
      { targetId: 'tdt-support-16', word: 'sections', sentenceId: 'tdt-p4-s11', focus: 'tion', chunks: [{ displayText: 'sec', speechText: 'sek' }, { displayText: 'tions', speechText: 'shunz' }] },
    ],
    beginningEvidenceId: 'tdt-p4-s5',
    middleEvidenceId: 'tdt-p4-s6',
    turningEvidenceId: 'tdt-p4-s8',
    endingEvidenceId: 'tdt-p4-s13',
    minorEvidenceId: 'tdt-p4-s1',
    beginningEvidenceChoice: 'Noor insists that the original long-banner plan will work.',
    middleEvidenceChoice: 'A gust tears the banner, and the forecast warns of stronger wind.',
    endingEvidenceChoice: 'Noor saves the successful new measurements for future displays.',
    minorEvidenceChoice: 'The banner is for a neighborhood night market.',
    characterConnectionStatement: 'Noor learns that adapting the shape does not require giving up the purpose of her design.',
    conflictConnectionStatement: 'Wind damage and the forecast make the original form unsafe and ineffective.',
    developmentSummary: 'At the beginning, Noor refuses to alter her long banner. In the middle, wind tears it and a small-panel test works. By the end, the adapted panels meet the same goal and Noor keeps the new plan.',
  },
  {
    passageId: THEME_DEVELOPMENT_PASSAGE_IDS[4],
    title: 'The Clockwork Cart',
    difficulty: 2,
    themeFamily: 'perseverance',
    topicLabel: 'perseverance',
    supportedTheme: 'Small adjustments and repeated effort can turn a setback into steady progress.',
    summaryChoice: 'Ren tests a model cart several times and fixes its wobbling wheel.',
    unsupportedThemeChoice: 'Natural talent matters more than practice when a project becomes difficult.',
    unsupportedReason: 'Ren succeeds through measured tests and revisions rather than instant talent.',
    sentences: [
      { sentenceId: 'tdt-p5-s1', text: 'Ren carried a clockwork cart into the school invention room for the final practice day.' },
      { sentenceId: 'tdt-p5-s2', text: 'Its wooden body was polished, but the left wheel shook whenever the mechanism began turning.' },
      { sentenceId: 'tdt-p5-s3', text: 'During the first test, the cart rolled in a circle and bumped a stack of empty boxes.' },
      { sentenceId: 'tdt-p5-s4', text: 'Ren stared at the crooked path and wondered whether he should replace the whole cart with an older project.' },
      { sentenceId: 'tdt-p5-s5', text: 'His teammate June reminded him that the wheel had traveled farther than it did during yesterday\'s test.' },
      { sentenceId: 'tdt-p5-s6', text: 'Ren measured the axle and found one thin gap between the wheel and its wooden brace.' },
      { sentenceId: 'tdt-p5-s7', text: 'He slid in a paper washer, recorded the adjustment, and wound the spring again.' },
      { sentenceId: 'tdt-p5-s8', text: 'The cart moved straight for half the table before the wheel began to wobble.' },
      { sentenceId: 'tdt-p5-s9', text: 'Instead of pushing it aside, Ren compared both wheels and noticed that one brace sat slightly higher.' },
      { sentenceId: 'tdt-p5-s10', text: 'He sanded the high edge, tested the cart, and marked the new distance in his notebook.' },
      { sentenceId: 'tdt-p5-s11', text: 'On the fourth run, the cart crossed the entire table and stopped inside the chalk finish box.' },
      { sentenceId: 'tdt-p5-s12', text: 'Ren did not call the first failed circle a waste anymore; it had shown him where to look.' },
      { sentenceId: 'tdt-p5-s13', text: 'At the invention share, he displayed the successful cart beside his notes from every imperfect test.' },
      { sentenceId: 'tdt-p5-s14', text: 'When a visitor asked which page mattered most, Ren opened the notebook to the first wobble.' },
    ],
    support: [
      { targetId: 'tdt-support-17', word: 'mechanism', sentenceId: 'tdt-p5-s2', focus: 'mech', chunks: [{ displayText: 'mech', speechText: 'mek' }, { displayText: 'a', speechText: 'uh' }, { displayText: 'nism', speechText: 'nizum' }] },
      { targetId: 'tdt-support-18', word: 'measured', sentenceId: 'tdt-p5-s6', focus: 'meas', chunks: [{ displayText: 'meas', speechText: 'mezh' }, { displayText: 'ured', speechText: 'urd' }] },
      { targetId: 'tdt-support-19', word: 'adjustment', sentenceId: 'tdt-p5-s7', focus: 'ment', chunks: [{ displayText: 'ad', speechText: 'uhd' }, { displayText: 'just', speechText: 'just' }, { displayText: 'ment', speechText: 'ment' }] },
      { targetId: 'tdt-support-20', word: 'successful', sentenceId: 'tdt-p5-s13', focus: 'ful', chunks: [{ displayText: 'suc', speechText: 'suk' }, { displayText: 'cess', speechText: 'ses' }, { displayText: 'ful', speechText: 'ful' }] },
    ],
    beginningEvidenceId: 'tdt-p5-s4',
    middleEvidenceId: 'tdt-p5-s8',
    turningEvidenceId: 'tdt-p5-s9',
    endingEvidenceId: 'tdt-p5-s14',
    minorEvidenceId: 'tdt-p5-s1',
    beginningEvidenceChoice: 'Ren considers replacing the cart after its first failed test.',
    middleEvidenceChoice: 'A small fix improves the distance, but the wheel still wobbles.',
    endingEvidenceChoice: 'Ren values the first wobble because it helped guide later improvements.',
    minorEvidenceChoice: 'Ren carries the cart into the invention room.',
    characterConnectionStatement: 'Ren moves from treating a failed test as a reason to quit to using each result as information for the next attempt.',
    conflictConnectionStatement: 'The repeating wheel problem requires several different adjustments rather than one instant repair.',
    developmentSummary: 'At the beginning, Ren considers replacing the cart after a failed run. In the middle, partial improvement encourages another careful adjustment. By the end, the cart succeeds and Ren values the first failure as useful evidence.',
  },
  {
    passageId: THEME_DEVELOPMENT_PASSAGE_IDS[5],
    title: 'The Garden Signs',
    difficulty: 2,
    themeFamily: 'asking for help',
    topicLabel: 'asking for help',
    supportedTheme: 'Asking for help can turn confusion into a chance to learn and contribute.',
    summaryChoice: 'Imani asks how to read a diagram and then repairs the garden signs.',
    unsupportedThemeChoice: 'Working alone is the surest way to prove that a person is independent.',
    unsupportedReason: 'Imani\'s private guessing creates confusion, while asking a clear question lets her learn and help.',
    sentences: [
      { sentenceId: 'tdt-p6-s1', text: 'Imani volunteered to place direction signs along the community garden paths.' },
      { sentenceId: 'tdt-p6-s2', text: 'The instructions included a diagram filled with dotted lines, arrows, and unfamiliar symbols.' },
      { sentenceId: 'tdt-p6-s3', text: 'Imani understood the first two marks, but she could not tell whether a triangle meant a gate or a tool shed.' },
      { sentenceId: 'tdt-p6-s4', text: 'She wanted to look capable, so she guessed and pointed the berry-path arrow toward the compost bins.' },
      { sentenceId: 'tdt-p6-s5', text: 'She placed three more signs by copying the same guessed symbol.' },
      { sentenceId: 'tdt-p6-s6', text: 'During a practice walk, two volunteers followed the arrows and ended beside a wheelbarrow instead of the berry beds.' },
      { sentenceId: 'tdt-p6-s7', text: 'Imani felt her face grow warm as she realized that silent guessing had repeated the mistake.' },
      { sentenceId: 'tdt-p6-s8', text: 'She carried the diagram to Mr. Chen and said, "I understand the arrows, but will you show me how this triangle works?"' },
      { sentenceId: 'tdt-p6-s9', text: 'Mr. Chen uncovered a small legend at the bottom of the page and explained that the triangle marked each tool station.' },
      { sentenceId: 'tdt-p6-s10', text: 'Imani traced one route with her finger, checked it with him, and then turned the misplaced signs.' },
      { sentenceId: 'tdt-p6-s11', text: 'On the second walk, every volunteer reached the berry beds without a wrong turn.' },
      { sentenceId: 'tdt-p6-s12', text: 'Later, a younger helper frowned at the watering symbol instead of placing his sign.' },
      { sentenceId: 'tdt-p6-s13', text: 'Imani showed him the legend and said, "Questions helped me understand this map too."' },
      { sentenceId: 'tdt-p6-s14', text: 'Together they finished the last route, and Imani added the corrected signs to her contribution list.' },
    ],
    support: [
      { targetId: 'tdt-support-21', word: 'instructions', sentenceId: 'tdt-p6-s2', focus: 'tion', chunks: [{ displayText: 'in', speechText: 'in' }, { displayText: 'struc', speechText: 'struk' }, { displayText: 'tions', speechText: 'shunz' }] },
      { targetId: 'tdt-support-22', word: 'diagram', sentenceId: 'tdt-p6-s2', focus: 'dia', chunks: [{ displayText: 'di', speechText: 'die' }, { displayText: 'a', speechText: 'uh' }, { displayText: 'gram', speechText: 'gram' }] },
      { targetId: 'tdt-support-23', word: 'symbol', sentenceId: 'tdt-p6-s5', focus: 'sym', chunks: [{ displayText: 'sym', speechText: 'sim' }, { displayText: 'bol', speechText: 'bul' }] },
      { targetId: 'tdt-support-24', word: 'contribution', sentenceId: 'tdt-p6-s14', focus: 'tion', chunks: [{ displayText: 'con', speechText: 'kon' }, { displayText: 'tri', speechText: 'truh' }, { displayText: 'bu', speechText: 'byoo' }, { displayText: 'tion', speechText: 'shun' }] },
    ],
    beginningEvidenceId: 'tdt-p6-s4',
    middleEvidenceId: 'tdt-p6-s6',
    turningEvidenceId: 'tdt-p6-s8',
    endingEvidenceId: 'tdt-p6-s13',
    minorEvidenceId: 'tdt-p6-s1',
    beginningEvidenceChoice: 'Imani guesses at the symbol because she wants to look capable.',
    middleEvidenceChoice: 'Her repeated guess sends volunteers away from the berry beds.',
    endingEvidenceChoice: 'Imani helps another learner use the legend and explains that questions helped her.',
    minorEvidenceChoice: 'Imani volunteers at a community garden.',
    characterConnectionStatement: 'Imani stops hiding her confusion, asks a focused question, and later helps someone else do the same.',
    conflictConnectionStatement: 'The misplaced signs show that silent guessing prevents both accurate work and learning.',
    developmentSummary: 'At the beginning, Imani hides her confusion and guesses. In the middle, the wrong route reveals the result and she asks for help. By the end, she uses what she learned to support another helper.',
  },
  {
    passageId: THEME_DEVELOPMENT_PASSAGE_IDS[6],
    title: 'The Shared Rain Shelter',
    difficulty: 2,
    themeFamily: 'considering others',
    topicLabel: 'fairness',
    supportedTheme: 'Considering how a choice affects others can lead to a fairer shared solution.',
    summaryChoice: 'Caleb moves a planned rain shelter after learning how several groups use the courtyard.',
    unsupportedThemeChoice: 'The person who speaks most confidently should make decisions for a group.',
    unsupportedReason: 'Caleb\'s confident first choice overlooks others, while gathered information leads to the useful solution.',
    sentences: [
      { sentenceId: 'tdt-p7-s1', text: 'The student council received one temporary rain shelter for the school courtyard.' },
      { sentenceId: 'tdt-p7-s2', text: 'Caleb immediately proposed placing it beside the basketball bench where he and his friends met.' },
      { sentenceId: 'tdt-p7-s3', text: 'Leila noted that younger students waited near the library doors and the art club carried paper across the opposite side.' },
      { sentenceId: 'tdt-p7-s4', text: 'Caleb replied that the bench was already popular, so his location would help the most people.' },
      { sentenceId: 'tdt-p7-s5', text: 'The council marked his proposal with chalk and raised a small practice canopy there.' },
      { sentenceId: 'tdt-p7-s6', text: 'During a light rain, the basketball group stayed dry, but water dripped onto children lined up at the library doors.' },
      { sentenceId: 'tdt-p7-s7', text: 'Two art students also hurried around the canopy because its ropes blocked their accessible path.' },
      { sentenceId: 'tdt-p7-s8', text: 'Caleb watched one student protect a cardboard model under her jacket and realized his count had included only the group he usually noticed.' },
      { sentenceId: 'tdt-p7-s9', text: 'He asked Leila to help him record where people walked and waited during the next break.' },
      { sentenceId: 'tdt-p7-s10', text: 'Their notes showed that the center walkway served the library line, the art path, and students heading toward the bench.' },
      { sentenceId: 'tdt-p7-s11', text: 'Caleb proposed turning the shelter sideways along that walkway, with one rope moved away from the ramp.' },
      { sentenceId: 'tdt-p7-s12', text: 'The council tested the new position while each group followed its usual route.' },
      { sentenceId: 'tdt-p7-s13', text: 'Everyone could pass, and students from all three areas found cover without crowding one another.' },
      { sentenceId: 'tdt-p7-s14', text: 'Caleb added the route notes to the final decision instead of listing only the number of basketball players.' },
      { sentenceId: 'tdt-p7-s15', text: 'Before planning the next courtyard change, he asked which people had not yet been heard.' },
    ],
    support: [
      { targetId: 'tdt-support-25', word: 'temporary', sentenceId: 'tdt-p7-s1', focus: 'tempor', chunks: [{ displayText: 'tem', speechText: 'tem' }, { displayText: 'po', speechText: 'puh' }, { displayText: 'rar', speechText: 'rair' }, { displayText: 'y', speechText: 'ee' }] },
      { targetId: 'tdt-support-26', word: 'proposal', sentenceId: 'tdt-p7-s5', focus: 'pro', chunks: [{ displayText: 'pro', speechText: 'pruh' }, { displayText: 'pos', speechText: 'pohz' }, { displayText: 'al', speechText: 'ul' }] },
      { targetId: 'tdt-support-27', word: 'accessible', sentenceId: 'tdt-p7-s7', focus: 'access', chunks: [{ displayText: 'ac', speechText: 'ak' }, { displayText: 'ces', speechText: 'ses' }, { displayText: 'si', speechText: 'suh' }, { displayText: 'ble', speechText: 'bul' }] },
      { targetId: 'tdt-support-28', word: 'decision', sentenceId: 'tdt-p7-s14', focus: 'sion', chunks: [{ displayText: 'de', speechText: 'duh' }, { displayText: 'ci', speechText: 'sizh' }, { displayText: 'sion', speechText: 'un' }] },
    ],
    beginningEvidenceId: 'tdt-p7-s4',
    middleEvidenceId: 'tdt-p7-s7',
    turningEvidenceId: 'tdt-p7-s8',
    endingEvidenceId: 'tdt-p7-s15',
    minorEvidenceId: 'tdt-p7-s1',
    beginningEvidenceChoice: 'Caleb supports the place used by his own group and assumes it helps the most people.',
    middleEvidenceChoice: 'The test reveals that the location leaves one line wet and blocks an accessible path.',
    endingEvidenceChoice: 'Caleb asks whose needs have not yet been heard before another decision.',
    minorEvidenceChoice: 'The shelter is temporary and stands in the school courtyard.',
    characterConnectionStatement: 'Caleb replaces an assumption based on his own group with a habit of gathering information about everyone affected.',
    conflictConnectionStatement: 'The rainy test makes the overlooked effects of the first location visible.',
    developmentSummary: 'At the beginning, Caleb considers mainly his own group. In the middle, the test reveals problems for other students and he gathers route evidence. By the end, the shared location works and Caleb asks who still needs a voice.',
  },
]

export const themeDevelopmentPassages: Passage[] = themeDevelopmentStories.map((story) => ({
  passageIdentifier: story.passageId,
  title: story.title,
  passageText: story.sentences.map((sentence) => sentence.text).join(' '),
  readingContext: story.title,
  sentences: story.sentences,
  genre: 'literary',
  gradeBand: 3,
  reviewStatus: 'DRAFT',
  contentVersion: THEME_DEVELOPMENT_VERSION,
  wordSupportTargets: story.support.map((target) => ({
    targetId: target.targetId,
    passageId: story.passageId,
    sentenceId: target.sentenceId,
    surfaceWord: target.word,
    focusParts: buildFocusParts(target.word, target.focus),
    displayChunks: target.chunks,
    spokenChunks: target.chunks,
    blendSpeechText: target.word,
    wholeWordSpeechText: target.word,
    sentenceSpeechText: story.sentences.find((sentence) => sentence.sentenceId === target.sentenceId)?.text ?? '',
    reviewStatus: 'DRAFT',
    contentVersion: THEME_DEVELOPMENT_VERSION,
  })),
}))

export const themeDevelopmentGuides: ThemeDevelopmentGuide[] = themeDevelopmentStories.map((story, index) => ({
  passageId: story.passageId,
  topicLabel: story.topicLabel,
  supportedTheme: {
    themeId: `tdt-p${index + 1}-theme-supported`,
    statement: story.supportedTheme,
    candidateKind: 'theme',
    supported: true,
    supportReason: story.developmentSummary,
  },
  plausibleDistractorThemes: [
    { themeId: `tdt-p${index + 1}-theme-topic`, statement: story.topicLabel, candidateKind: 'topic', supported: false, supportReason: 'This names the broad topic but does not express a complete message.' },
    { themeId: `tdt-p${index + 1}-theme-summary`, statement: story.summaryChoice, candidateKind: 'summary', supported: false, supportReason: 'This retells important events but does not state the story\'s broader message.' },
    { themeId: `tdt-p${index + 1}-theme-unsupported`, statement: story.unsupportedThemeChoice, candidateKind: 'unsupported-theme', supported: false, supportReason: story.unsupportedReason },
  ],
  stages: [
    { stageId: `tdt-p${index + 1}-stage-beginning`, stage: 'beginning', evidenceIds: [story.beginningEvidenceId], developmentStatement: `The beginning introduces the conflict around ${story.topicLabel}.` },
    { stageId: `tdt-p${index + 1}-stage-middle`, stage: 'middle', evidenceIds: [story.middleEvidenceId, story.turningEvidenceId], developmentStatement: 'The consequence and turning point test the important idea and make its value clearer.' },
    { stageId: `tdt-p${index + 1}-stage-end`, stage: 'end', evidenceIds: [story.endingEvidenceId], developmentStatement: 'The ending response shows the idea guiding a later choice.' },
  ],
  turningPointEvidenceIds: [story.turningEvidenceId],
  characterConnectionStatement: story.characterConnectionStatement,
  conflictConnectionStatement: story.conflictConnectionStatement,
  developmentSummary: story.developmentSummary,
  reviewStatus: 'DRAFT',
  contentVersion: THEME_DEVELOPMENT_VERSION,
}))

export const themeDevelopmentCoveragePatterns = [
  'theme',
  'theme-development',
  'supporting-details',
  'plot-theme-connection',
] as const

function buildFocusParts(word: string, focus: string) {
  const index = word.toLowerCase().indexOf(focus.toLowerCase())
  if (index < 0) return [{ text: word, emphasis: true }]
  return [
    { text: word.slice(0, index), emphasis: false },
    { text: word.slice(index, index + focus.length), emphasis: true },
    { text: word.slice(index + focus.length), emphasis: false },
  ].filter((part) => part.text.length > 0)
}
