import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
  lessonChoice as choice,
} from './questionFactories'
import {
  opinionEvidenceDeskContentVersion,
  opinionEvidenceDeskFeatureIds,
  opinionEvidenceDeskLessonIds,
  opinionEvidenceDeskPassageIds,
  opinionEvidenceDeskQuestionIds,
  opinionEvidenceDeskSentenceIds,
} from './ids'

const base = {
  benchmarkReference: 'ELA.2.R.2.4' as const,
  skillIdentifier: 'g2-information-detectives-reading' as const,
  reportingCategory: 'Reading Informational Text' as const,
  genre: 'informational' as const,
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2' as const,
  contentVersion: opinionEvidenceDeskContentVersion,
  reviewStatus: 'DRAFT' as const,
}

const mc = (spec: Parameters<typeof createMultipleChoiceQuestion>[0]) => createMultipleChoiceQuestion(spec)
const ms = (spec: Parameters<typeof createMultiselectQuestion>[0]) => createMultiselectQuestion(spec)
const ht = (spec: Parameters<typeof createHotTextQuestion>[0]) => createHotTextQuestion(spec)
const tm = (spec: Parameters<typeof createTableMatchQuestion>[0]) => createTableMatchQuestion(spec)

export const opinionEvidenceDeskPrerequisiteQuestions = [
  mc({
    ...base,
    difficulty: 3,
    passageIdentifier: opinionEvidenceDeskPassageIds.shadedRestSpots.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.prereqFactOpinionTopic,
    questionIdentifier: opinionEvidenceDeskQuestionIds.prereqFactOpinionTopic[0],
    prompt: 'What is the topic of this passage?',
    explanation: 'The topic is the short phrase that names what the passage is about.',
    evidenceReference: opinionEvidenceDeskFeatureIds.shadedRestSpots.title,
    evidenceReferenceIds: [opinionEvidenceDeskFeatureIds.shadedRestSpots.title],
    targetVocabulary: ['topic'],
    soundOutChunks: ['top', 'ic'],
    tags: ['opinion', 'opinion-vs-topic'],
    choices: [
      choice('shaded-topic', 'shaded rest spots'),
      choice('shaded-fact', 'The class measured the shaded bench at three degrees cooler at noon.'),
      choice('shaded-opinion', 'The nature center should add more shaded rest spots.'),
      choice('shaded-detail', 'Visitors stayed longer at the shaded bench because it felt more comfortable.'),
    ],
    correctChoiceIds: ['shaded-topic'],
  }),
  mc({
    ...base,
    difficulty: 3,
    passageIdentifier: opinionEvidenceDeskPassageIds.shadedRestSpots.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.prereqFactOpinionTopic,
    questionIdentifier: opinionEvidenceDeskQuestionIds.prereqFactOpinionTopic[1],
    prompt: 'Which sentence is a fact from the passage?',
    explanation: 'A fact can be checked in the passage.',
    evidenceReference: opinionEvidenceDeskSentenceIds.shadedRestSpots[2],
    evidenceReferenceIds: [opinionEvidenceDeskSentenceIds.shadedRestSpots[2]],
    targetVocabulary: ['fact', 'opinion'],
    soundOutChunks: ['fact'],
    tags: ['opinion', 'fact-vs-opinion'],
    choices: [
      choice('shaded-fact', 'The class measured the shaded bench at three degrees cooler at noon.'),
      choice('shaded-opinion', 'The nature center should add more shaded rest spots.'),
      choice('shaded-topic', 'shaded rest spots'),
      choice('shaded-false', 'Visitors stayed longer at the sunny bench because it felt more comfortable.'),
    ],
    correctChoiceIds: ['shaded-fact'],
  }),
  ms({
    ...base,
    difficulty: 3,
    passageIdentifier: opinionEvidenceDeskPassageIds.shadedRestSpots.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.prereqFactOpinionTopic,
    questionIdentifier: opinionEvidenceDeskQuestionIds.prereqFactOpinionTopic[2],
    prompt: 'Choose two details that help explain why the author wants more shaded rest spots.',
    explanation: 'These details show why the shaded bench is a good place to stop.',
    evidenceReference: opinionEvidenceDeskSentenceIds.shadedRestSpots[3],
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.shadedRestSpots[2],
      opinionEvidenceDeskSentenceIds.shadedRestSpots[3],
    ],
    targetVocabulary: ['detail', 'evidence'],
    soundOutChunks: ['de', 'tail'],
    tags: ['opinion', 'supporting-evidence', 'supporting-evidence-identification', 'strongest-supporting-evidence'],
    choices: [
      choice('shaded-detail-1', 'The class measured the shaded bench at three degrees cooler at noon.'),
      choice('shaded-detail-2', 'Visitors stayed longer at the shaded bench because it felt more comfortable.'),
      choice('shaded-detail-3', 'The nature center has two benches near the trail.'),
      choice('shaded-detail-4', 'The ranger said families often rest there after the steep hill.'),
    ],
    correctChoiceIds: ['shaded-detail-1', 'shaded-detail-2'],
  }),
  ht({
    ...base,
    difficulty: 3,
    passageIdentifier: opinionEvidenceDeskPassageIds.shadedRestSpots.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.prereqFactOpinionTopic,
    questionIdentifier: opinionEvidenceDeskQuestionIds.prereqFactOpinionTopic[3],
    prompt: 'Select the sentence that states the author opinion.',
    explanation: 'The opinion tells what the author thinks should happen.',
    evidenceReference: opinionEvidenceDeskSentenceIds.shadedRestSpots[5],
    evidenceReferenceIds: [opinionEvidenceDeskSentenceIds.shadedRestSpots[5]],
    targetVocabulary: ['opinion'],
    soundOutChunks: ['op', 'in', 'ion'],
    tags: ['opinion', 'author-opinion-identification', 'opinion-vs-topic'],
    selectableSegments: [
      { id: opinionEvidenceDeskSentenceIds.shadedRestSpots[0], text: 'The nature center has two benches near the trail.' },
      { id: opinionEvidenceDeskSentenceIds.shadedRestSpots[2], text: 'The class measured the shaded bench at three degrees cooler at noon.' },
      { id: opinionEvidenceDeskSentenceIds.shadedRestSpots[5], text: 'The nature center should add more shaded rest spots.' },
      { id: opinionEvidenceDeskSentenceIds.shadedRestSpots[7], text: 'That cooler spot helps people pause before they keep walking.' },
    ],
    correctSegmentIds: [opinionEvidenceDeskSentenceIds.shadedRestSpots[5]],
  }),
  tm({
    ...base,
    difficulty: 3,
    passageIdentifier: opinionEvidenceDeskPassageIds.shadedRestSpots.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.prereqFactOpinionTopic,
    questionIdentifier: opinionEvidenceDeskQuestionIds.prereqFactOpinionTopic[4],
    prompt: 'Match each statement to the best answer.',
    explanation: 'Each row names an idea the reader can identify in the passage.',
    evidenceReference: opinionEvidenceDeskFeatureIds.shadedRestSpots.visual,
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.shadedRestSpots[2],
      opinionEvidenceDeskSentenceIds.shadedRestSpots[3],
      opinionEvidenceDeskSentenceIds.shadedRestSpots[4],
    ],
    targetVocabulary: ['topic', 'opinion', 'fact', 'detail'],
    soundOutChunks: ['mat', 'ch'],
    tags: ['opinion', 'fact-vs-opinion', 'opinion-vs-topic', 'supporting-evidence'],
    rows: [
      {
        id: 'shaded-topic-row',
        prompt: 'What is the topic?',
        correctChoiceId: 'shaded-topic-answer',
        options: [
          choice('shaded-topic-answer', 'shaded rest spots'),
          choice('shaded-topic-opinion', 'The nature center should add more shaded rest spots.'),
          choice('shaded-topic-fact', 'The class measured the shaded bench at three degrees cooler at noon.'),
        ],
      },
      {
        id: 'shaded-opinion-row',
        prompt: 'Which sentence is the opinion?',
        correctChoiceId: 'shaded-opinion-answer',
        options: [
          choice('shaded-opinion-answer', 'The nature center should add more shaded rest spots.'),
          choice('shaded-opinion-fact', 'The class measured the shaded bench at three degrees cooler at noon.'),
          choice('shaded-opinion-detail', 'The ranger said families often rest there after the steep hill.'),
        ],
      },
      {
        id: 'shaded-fact-row',
        prompt: 'Which sentence is a fact?',
        correctChoiceId: 'shaded-fact-answer',
        options: [
          choice('shaded-fact-answer', 'The class measured the shaded bench at three degrees cooler at noon.'),
          choice('shaded-fact-opinion', 'The nature center should add more shaded rest spots.'),
          choice('shaded-fact-topic', 'shaded rest spots'),
        ],
      },
      {
        id: 'shaded-detail-row',
        prompt: 'Which sentence is another true detail?',
        correctChoiceId: 'shaded-detail-answer',
        options: [
          choice('shaded-detail-answer', 'The ranger said families often rest there after the steep hill.'),
          choice('shaded-detail-opinion', 'The nature center should add more shaded rest spots.'),
          choice('shaded-detail-fact', 'The class measured the shaded bench at three degrees cooler at noon.'),
        ],
      },
    ],
  }),
  mc({
    ...base,
    difficulty: 3,
    passageIdentifier: opinionEvidenceDeskPassageIds.nativeFlowerBeds.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.prereqMatchEvidence,
    questionIdentifier: opinionEvidenceDeskQuestionIds.prereqMatchEvidence[0],
    prompt: 'Which sentence is the author opinion about the flowers?',
    explanation: 'The opinion tells what the author thinks should happen in the garden.',
    evidenceReference: opinionEvidenceDeskSentenceIds.nativeFlowerBeds[4],
    evidenceReferenceIds: [opinionEvidenceDeskSentenceIds.nativeFlowerBeds[4]],
    targetVocabulary: ['opinion', 'flowers'],
    soundOutChunks: ['fl', 'ow', 'ers'],
    tags: ['opinion', 'author-opinion-identification', 'multiple-author-opinions'],
    choices: [
      choice('flowers-opinion', 'The garden should include more native flowers.'),
      choice('flowers-fact', 'Bees visited the native flowers more often than the nonnative flowers.'),
      choice('flowers-topic', 'native flowers'),
      choice('flowers-detail', 'A small illustration shows bees near the native flower row.'),
    ],
    correctChoiceIds: ['flowers-opinion'],
  }),
  mc({
    ...base,
    difficulty: 3,
    passageIdentifier: opinionEvidenceDeskPassageIds.nativeFlowerBeds.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.prereqMatchEvidence,
    questionIdentifier: opinionEvidenceDeskQuestionIds.prereqMatchEvidence[1],
    prompt: 'Which detail best supports the opinion that the garden should include more native flowers?',
    explanation: 'This detail shows that the native flowers already bring in bees.',
    evidenceReference: opinionEvidenceDeskSentenceIds.nativeFlowerBeds[1],
    evidenceReferenceIds: [opinionEvidenceDeskSentenceIds.nativeFlowerBeds[1]],
    targetVocabulary: ['support', 'detail'],
    soundOutChunks: ['de', 'tail'],
    tags: ['supporting-evidence', 'strongest-supporting-evidence', 'opinion'],
    choices: [
      choice('flowers-support-1', 'Bees visited the native flowers more often than the nonnative flowers.'),
      choice('flowers-support-2', 'The school garden has a sunny bed and a shady bed.'),
      choice('flowers-support-3', 'The shady bed held fewer blooms but more leaves.'),
      choice('flowers-support-4', 'The taller plants should stay at the back so the shorter plants get sun.'),
    ],
    correctChoiceIds: ['flowers-support-1'],
  }),
  ms({
    ...base,
    difficulty: 3,
    passageIdentifier: opinionEvidenceDeskPassageIds.nativeFlowerBeds.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.prereqMatchEvidence,
    questionIdentifier: opinionEvidenceDeskQuestionIds.prereqMatchEvidence[2],
    prompt: 'Choose two details that help explain the opinion about plant placement.',
    explanation: 'These details show why the taller plants belong in the back.',
    evidenceReference: opinionEvidenceDeskSentenceIds.nativeFlowerBeds[3],
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.nativeFlowerBeds[3],
      opinionEvidenceDeskSentenceIds.nativeFlowerBeds[7],
    ],
    targetVocabulary: ['detail', 'placement'],
    soundOutChunks: ['place', 'ment'],
    tags: ['opinion', 'supporting-evidence', 'multiple-author-opinions', 'supporting-evidence-identification'],
    choices: [
      choice('flowers-layout-1', 'A few taller plants cast shadows on the back row.'),
      choice('flowers-layout-2', 'The shady bed held fewer blooms but more leaves.'),
      choice('flowers-layout-3', 'A small illustration shows bees near the native flower row.'),
      choice('flowers-layout-4', 'The school garden has a sunny bed and a shady bed.'),
    ],
    correctChoiceIds: ['flowers-layout-1', 'flowers-layout-2'],
  }),
  ht({
    ...base,
    difficulty: 3,
    passageIdentifier: opinionEvidenceDeskPassageIds.nativeFlowerBeds.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.prereqMatchEvidence,
    questionIdentifier: opinionEvidenceDeskQuestionIds.prereqMatchEvidence[3],
    prompt: 'Select the sentence that gives a strong clue about why the author wants more native flowers.',
    explanation: 'The bee visits show that native flowers matter to the garden.',
    evidenceReference: opinionEvidenceDeskSentenceIds.nativeFlowerBeds[1],
    evidenceReferenceIds: [opinionEvidenceDeskSentenceIds.nativeFlowerBeds[1]],
    targetVocabulary: ['clue', 'native'],
    soundOutChunks: ['na', 'tive'],
    tags: ['supporting-evidence', 'supporting-evidence-identification', 'opinion'],
    selectableSegments: [
      { id: opinionEvidenceDeskSentenceIds.nativeFlowerBeds[0], text: 'The school garden has a sunny bed and a shady bed.' },
      { id: opinionEvidenceDeskSentenceIds.nativeFlowerBeds[1], text: 'Bees visited the native flowers more often than the nonnative flowers.' },
      { id: opinionEvidenceDeskSentenceIds.nativeFlowerBeds[5], text: 'The taller plants should stay at the back so the shorter plants get sun.' },
      { id: opinionEvidenceDeskSentenceIds.nativeFlowerBeds[7], text: 'The shady bed held fewer blooms but more leaves.' },
    ],
    correctSegmentIds: [opinionEvidenceDeskSentenceIds.nativeFlowerBeds[1]],
  }),
  tm({
    ...base,
    difficulty: 3,
    passageIdentifier: opinionEvidenceDeskPassageIds.nativeFlowerBeds.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.prereqMatchEvidence,
    questionIdentifier: opinionEvidenceDeskQuestionIds.prereqMatchEvidence[4],
    prompt: 'Match each statement to the best answer.',
    explanation: 'Each row names an idea the reader can identify in the passage.',
    evidenceReference: opinionEvidenceDeskFeatureIds.nativeFlowerBeds.visual,
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.nativeFlowerBeds[1],
      opinionEvidenceDeskSentenceIds.nativeFlowerBeds[3],
      opinionEvidenceDeskSentenceIds.nativeFlowerBeds[7],
    ],
    targetVocabulary: ['topic', 'central idea', 'opinion', 'detail'],
    soundOutChunks: ['mat', 'ch'],
    tags: ['opinion', 'multiple-author-opinions', 'opinion-vs-central-idea', 'supporting-evidence'],
    rows: [
      {
        id: 'flowers-topic-row',
        prompt: 'What is the topic?',
        correctChoiceId: 'flowers-topic-answer',
        options: [
          choice('flowers-topic-answer', 'native flowers'),
          choice('flowers-topic-opinion', 'The garden should include more native flowers.'),
          choice('flowers-topic-detail', 'Bees visited the native flowers more often than the nonnative flowers.'),
        ],
      },
      {
        id: 'flowers-central-row',
        prompt: 'What is the central idea?',
        correctChoiceId: 'flowers-central-answer',
        options: [
          choice('flowers-central-answer', 'Native flowers and plant placement can help the garden work well for bees and sunlight.'),
          choice('flowers-central-opinion', 'The garden should include more native flowers.'),
          choice('flowers-central-detail', 'A few taller plants cast shadows on the back row.'),
        ],
      },
      {
        id: 'flowers-opinion-row',
        prompt: 'Which sentence is the opinion about flowers?',
        correctChoiceId: 'flowers-opinion-answer',
        options: [
          choice('flowers-opinion-answer', 'The garden should include more native flowers.'),
          choice('flowers-opinion-central', 'Native flowers and plant placement can help the garden work well for bees and sunlight.'),
          choice('flowers-opinion-detail', 'The shady bed held fewer blooms but more leaves.'),
        ],
      },
      {
        id: 'flowers-detail-row',
        prompt: 'Which sentence is another true detail?',
        correctChoiceId: 'flowers-detail-answer',
        options: [
          choice('flowers-detail-answer', 'The shady bed held fewer blooms but more leaves.'),
          choice('flowers-detail-opinion', 'The taller plants should stay at the back so the shorter plants get sun.'),
          choice('flowers-detail-central', 'Native flowers and plant placement can help the garden work well for bees and sunlight.'),
        ],
      },
    ],
  }),
]
