import {
  createEvidencePairQuestion,
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
  lessonChoice as choice,
} from './questionFactories'
import {
  opinionEvidenceDeskContentVersion,
  opinionEvidenceDeskFeatureIds,
  opinionEvidenceDeskLessonIds,
  opinionEvidenceDeskPassageIds,
  opinionEvidenceDeskQuestionIds,
  opinionEvidenceDeskSentenceIds,
} from './ids'

const base = {
  benchmarkReference: 'ELA.2.R.2.4' as const,
  skillIdentifier: 'g2-information-detectives-reading' as const,
  reportingCategory: 'Reading Informational Text' as const,
  genre: 'informational' as const,
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2' as const,
  contentVersion: opinionEvidenceDeskContentVersion,
  reviewStatus: 'DRAFT' as const,
}

const mc = (spec: Parameters<typeof createMultipleChoiceQuestion>[0]) => createMultipleChoiceQuestion(spec)
const ms = (spec: Parameters<typeof createMultiselectQuestion>[0]) => createMultiselectQuestion(spec)
const ht = (spec: Parameters<typeof createHotTextQuestion>[0]) => createHotTextQuestion(spec)
const tm = (spec: Parameters<typeof createTableMatchQuestion>[0]) => createTableMatchQuestion(spec)
const ep = (spec: Parameters<typeof createEvidencePairQuestion>[0]) => createEvidencePairQuestion(spec)

export const opinionEvidenceDeskCheckpointQuestions = [
  mc({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.birdFriendlyPlants.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointA,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointA[0],
    prompt: 'Which choice is the author opinion rather than the author purpose?',
    explanation: 'The opinion says what the author wants to happen, while the purpose explains why the text was written.',
    evidenceReference: opinionEvidenceDeskSentenceIds.birdFriendlyPlants[3],
    evidenceReferenceIds: [opinionEvidenceDeskSentenceIds.birdFriendlyPlants[3], opinionEvidenceDeskSentenceIds.birdFriendlyPlants[4]],
    targetVocabulary: ['opinion', 'purpose'],
    soundOutChunks: ['pur', 'pose'],
    tags: ['opinion', 'opinion-vs-author-purpose', 'author-opinion-identification'],
    choices: [
      choice('bird-opinion-shrubs', 'The observation area should include more berry shrubs.'),
      choice('bird-purpose', 'To explain how berry shrubs and a water dish help birds.'),
      choice('bird-topic', 'bird-friendly plants'),
      choice('bird-fact', 'The class counted more bird visits near the shrubs than near the fence.'),
    ],
    correctChoiceIds: ['bird-opinion-shrubs'],
  }),
  mc({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.birdFriendlyPlants.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointA,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointA[1],
    prompt: 'Which choice is the author opinion rather than the central idea?',
    explanation: 'The central idea is broader than the opinion.',
    evidenceReference: opinionEvidenceDeskSentenceIds.birdFriendlyPlants[7],
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.birdFriendlyPlants[1],
      opinionEvidenceDeskSentenceIds.birdFriendlyPlants[7],
    ],
    targetVocabulary: ['central idea', 'opinion'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['opinion', 'opinion-vs-central-idea'],
    choices: [
      choice('bird-central', 'Bird-friendly plants can give birds food, shelter, and water.'),
      choice('bird-opinion-shrubs', 'The observation area should include more berry shrubs.'),
      choice('bird-fact', 'The wind felt strong in the open part of the yard.'),
      choice('bird-purpose', 'To explain how berry shrubs and a water dish help birds.'),
    ],
    correctChoiceIds: ['bird-opinion-shrubs'],
  }),
  mc({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.birdFriendlyPlants.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointA,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointA[2],
    prompt: 'Which sentence is a fact rather than an opinion?',
    explanation: 'A fact can be checked in the passage.',
    evidenceReference: opinionEvidenceDeskSentenceIds.birdFriendlyPlants[6],
    evidenceReferenceIds: [opinionEvidenceDeskSentenceIds.birdFriendlyPlants[6]],
    targetVocabulary: ['fact', 'opinion'],
    soundOutChunks: ['fact'],
    tags: ['opinion', 'fact-vs-opinion'],
    choices: [
      choice('bird-fact', 'The class counted more bird visits near the shrubs than near the fence.'),
      choice('bird-opinion-shrubs', 'The observation area should include more berry shrubs.'),
      choice('bird-opinion-water', 'The area should also place one water dish under the tree.'),
      choice('bird-purpose', 'To explain how berry shrubs and a water dish help birds.'),
    ],
    correctChoiceIds: ['bird-fact'],
  }),
  ms({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.birdFriendlyPlants.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointA,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointA[3],
    prompt: 'Choose two details that support the opinion about a water dish under the tree.',
    explanation: 'These details show the tree and the open space around it.',
    evidenceReference: opinionEvidenceDeskSentenceIds.birdFriendlyPlants[0],
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.birdFriendlyPlants[0],
      opinionEvidenceDeskSentenceIds.birdFriendlyPlants[2],
    ],
    targetVocabulary: ['detail', 'support'],
    soundOutChunks: ['sup', 'port'],
    tags: ['opinion', 'supporting-evidence', 'supporting-evidence-identification', 'evidence-across-sections'],
    choices: [
      choice('bird-detail-1', 'The observation area has a low fence, a path, and a small tree.'),
      choice('bird-detail-2', 'The wind felt strong in the open part of the yard.'),
      choice('bird-detail-3', 'A graph showed birds resting in the leaves.'),
      choice('bird-detail-4', 'The berry shrubs sat nearest the middle path.'),
    ],
    correctChoiceIds: ['bird-detail-1', 'bird-detail-2'],
  }),
  ht({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.birdFriendlyPlants.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointA,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointA[4],
    prompt: 'Select the sentence that gives a strong clue about the opinion about berry shrubs.',
    explanation: 'The bird count shows that the shrubs are already a useful part of the area.',
    evidenceReference: opinionEvidenceDeskSentenceIds.birdFriendlyPlants[6],
    evidenceReferenceIds: [opinionEvidenceDeskSentenceIds.birdFriendlyPlants[6]],
    targetVocabulary: ['clue', 'shrubs'],
    soundOutChunks: ['shr', 'ubs'],
    tags: ['opinion', 'supporting-evidence', 'strongest-supporting-evidence'],
    selectableSegments: [
      { id: opinionEvidenceDeskSentenceIds.birdFriendlyPlants[1], text: 'Birds landed on the tree branches and ate the berries.' },
      { id: opinionEvidenceDeskSentenceIds.birdFriendlyPlants[3], text: 'The observation area should include more berry shrubs.' },
      { id: opinionEvidenceDeskSentenceIds.birdFriendlyPlants[6], text: 'The class counted more bird visits near the shrubs than near the fence.' },
      { id: opinionEvidenceDeskSentenceIds.birdFriendlyPlants[9], text: 'The berry shrubs sat nearest the middle path.' },
    ],
    correctSegmentIds: [opinionEvidenceDeskSentenceIds.birdFriendlyPlants[6]],
  }),
  tm({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.birdFriendlyPlants.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointA,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointA[5],
    prompt: 'Match each statement to the best answer.',
    explanation: 'Each row names an idea the reader can identify in the passage.',
    evidenceReference: opinionEvidenceDeskFeatureIds.birdFriendlyPlants.visual,
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.birdFriendlyPlants[1],
      opinionEvidenceDeskSentenceIds.birdFriendlyPlants[6],
      opinionEvidenceDeskSentenceIds.birdFriendlyPlants[8],
    ],
    targetVocabulary: ['topic', 'opinion', 'fact', 'detail'],
    soundOutChunks: ['mat', 'ch'],
    tags: ['opinion', 'multiple-author-opinions', 'opinion-vs-topic', 'opinion-vs-central-idea', 'supporting-evidence'],
    rows: [
      {
        id: 'bird-topic-row',
        prompt: 'What is the topic?',
        correctChoiceId: 'bird-topic-answer',
        options: [
          choice('bird-topic-answer', 'bird-friendly plants'),
          choice('bird-topic-opinion', 'The observation area should include more berry shrubs.'),
          choice('bird-topic-purpose', 'To explain how berry shrubs and a water dish help birds.'),
        ],
      },
      {
        id: 'bird-opinion-row',
        prompt: 'Which sentence is the opinion about shrubs?',
        correctChoiceId: 'bird-opinion-answer',
        options: [
          choice('bird-opinion-answer', 'The observation area should include more berry shrubs.'),
          choice('bird-opinion-fact', 'The class counted more bird visits near the shrubs than near the fence.'),
          choice('bird-opinion-detail', 'The shrubs gave the birds food and a place to hide.'),
        ],
      },
      {
        id: 'bird-other-opinion-row',
        prompt: 'Which sentence is the other opinion?',
        correctChoiceId: 'bird-other-opinion-answer',
        options: [
          choice('bird-other-opinion-answer', 'The area should also place one water dish under the tree.'),
          choice('bird-other-opinion-fact', 'The wind felt strong in the open part of the yard.'),
          choice('bird-other-opinion-purpose', 'To explain how berry shrubs and a water dish help birds.'),
        ],
      },
      {
        id: 'bird-fact-row',
        prompt: 'Which sentence is a fact?',
        correctChoiceId: 'bird-fact-answer',
        options: [
          choice('bird-fact-answer', 'The class counted more bird visits near the shrubs than near the fence.'),
          choice('bird-fact-opinion', 'The observation area should include more berry shrubs.'),
          choice('bird-fact-purpose', 'To explain how berry shrubs and a water dish help birds.'),
        ],
      },
    ],
  }),
  ep({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.birdFriendlyPlants.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointA,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointA[6],
    prompt: 'Choose the best answer for Part A and Part B.',
    explanation: 'The opinion fits because the bird visits and shelter details show why berry shrubs matter.',
    evidenceReference: opinionEvidenceDeskSentenceIds.birdFriendlyPlants[6],
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.birdFriendlyPlants[1],
      opinionEvidenceDeskSentenceIds.birdFriendlyPlants[6],
      opinionEvidenceDeskSentenceIds.birdFriendlyPlants[7],
    ],
    targetVocabulary: ['opinion', 'evidence'],
    soundOutChunks: ['e', 'vi', 'dence'],
    tags: ['opinion', 'multiple-author-opinions', 'opinion-evidence-matching', 'evidence-connection', 'evidence-across-sections'],
    partAPrompt: 'What is the author opinion about the shrubs?',
    partAChoices: [
      choice('bird-part-a-1', 'The observation area should include more berry shrubs.'),
      choice('bird-part-a-2', 'The area should also place one water dish under the tree.'),
      choice('bird-part-a-3', 'bird-friendly plants'),
    ],
    partACorrectChoiceId: 'bird-part-a-1',
    partBPrompt: 'Which detail best supports that opinion?',
    partBChoices: [
      choice('bird-part-b-1', 'The class counted more bird visits near the shrubs than near the fence.'),
      choice('bird-part-b-2', 'The observation area has a low fence, a path, and a small tree.'),
      choice('bird-part-b-3', 'The wind felt strong in the open part of the yard.'),
    ],
    partBCorrectChoiceId: 'bird-part-b-1',
  }),

  mc({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.compostSortingSigns.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointB,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointB[0],
    prompt: 'Which choice is the author opinion rather than the topic?',
    explanation: 'The opinion says what the author thinks the class should do.',
    evidenceReference: opinionEvidenceDeskSentenceIds.compostSortingSigns[6],
    evidenceReferenceIds: [opinionEvidenceDeskSentenceIds.compostSortingSigns[6]],
    targetVocabulary: ['opinion', 'topic'],
    soundOutChunks: ['top', 'ic'],
    tags: ['opinion', 'opinion-vs-topic', 'author-opinion-identification'],
    choices: [
      choice('compost-opinion', 'The class should keep the sorting signs near the bin.'),
      choice('compost-topic', 'compost sorting signs'),
      choice('compost-fact', 'The class added clear sorting signs with pictures and words.'),
      choice('compost-purpose', 'To explain how clear signs help students sort compost.'),
    ],
    correctChoiceIds: ['compost-opinion'],
  }),
  mc({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.compostSortingSigns.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointB,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointB[1],
    prompt: 'Which choice is the author opinion rather than the central idea?',
    explanation: 'The central idea is broader than the opinion about where the signs should stay.',
    evidenceReference: opinionEvidenceDeskSentenceIds.compostSortingSigns[4],
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.compostSortingSigns[3],
      opinionEvidenceDeskSentenceIds.compostSortingSigns[4],
    ],
    targetVocabulary: ['central idea', 'opinion'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['opinion', 'opinion-vs-central-idea'],
    choices: [
      choice('compost-central', 'Clear sorting signs help students sort compost more easily.'),
      choice('compost-opinion', 'The class should keep the sorting signs near the bin.'),
      choice('compost-fact', 'One sign used a picture of an apple core and a leaf.'),
      choice('compost-purpose', 'To explain how clear signs help students sort compost.'),
    ],
    correctChoiceIds: ['compost-opinion'],
  }),
  mc({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.compostSortingSigns.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointB,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointB[2],
    prompt: 'Which detail is the strongest evidence for the opinion?',
    explanation: 'This detail shows that the signs helped the class make fewer mistakes.',
    evidenceReference: opinionEvidenceDeskSentenceIds.compostSortingSigns[7],
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.compostSortingSigns[1],
      opinionEvidenceDeskSentenceIds.compostSortingSigns[4],
      opinionEvidenceDeskSentenceIds.compostSortingSigns[7],
    ],
    targetVocabulary: ['evidence', 'strongest'],
    soundOutChunks: ['e', 'vi', 'dence'],
    tags: ['opinion', 'supporting-evidence', 'fact-vs-opinion', 'strongest-supporting-evidence'],
    choices: [
      choice('compost-evidence-1', 'After the signs went up, the wrong items showed up less often.'),
      choice('compost-evidence-2', 'The compost bin used to collect apple cores, leaves, and napkins.'),
      choice('compost-evidence-3', 'The guide paper beside the bin listed three good compost items.'),
      choice('compost-evidence-4', 'The class added clear sorting signs with pictures and words.'),
    ],
    correctChoiceIds: ['compost-evidence-1'],
  }),
  ms({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.compostSortingSigns.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointB,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointB[3],
    prompt: 'Choose two details that support the opinion.',
    explanation: 'These details show how the signs helped the class sort compost.',
    evidenceReference: opinionEvidenceDeskSentenceIds.compostSortingSigns[4],
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.compostSortingSigns[1],
      opinionEvidenceDeskSentenceIds.compostSortingSigns[4],
    ],
    targetVocabulary: ['detail', 'support'],
    soundOutChunks: ['sup', 'port'],
    tags: ['opinion', 'supporting-evidence', 'supporting-evidence-identification', 'evidence-across-sections'],
    choices: [
      choice('compost-detail-1', 'Some students put plastic wrappers in the bin by mistake.'),
      choice('compost-detail-2', 'After the signs went up, the wrong items showed up less often.'),
      choice('compost-detail-3', 'The compost pile stayed cleaner and easier to turn.'),
      choice('compost-detail-4', 'One sign used a picture of an apple core and a leaf.'),
    ],
    correctChoiceIds: ['compost-detail-1', 'compost-detail-2'],
  }),
  ht({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.compostSortingSigns.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointB,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointB[4],
    prompt: 'Select the sentence that gives a strong clue about the opinion.',
    explanation: 'The fewer mistakes show that the signs helped the class sort better.',
    evidenceReference: opinionEvidenceDeskSentenceIds.compostSortingSigns[7],
    evidenceReferenceIds: [opinionEvidenceDeskSentenceIds.compostSortingSigns[7]],
    targetVocabulary: ['clue', 'signs'],
    soundOutChunks: ['signs'],
    tags: ['opinion', 'supporting-evidence', 'strongest-supporting-evidence'],
    selectableSegments: [
      { id: opinionEvidenceDeskSentenceIds.compostSortingSigns[2], text: 'The class added clear sorting signs with pictures and words.' },
      { id: opinionEvidenceDeskSentenceIds.compostSortingSigns[4], text: 'After the signs went up, the wrong items showed up less often.' },
      { id: opinionEvidenceDeskSentenceIds.compostSortingSigns[6], text: 'The class should keep the sorting signs near the bin.' },
      { id: opinionEvidenceDeskSentenceIds.compostSortingSigns[9], text: 'The guide paper beside the bin listed three good compost items.' },
    ],
    correctSegmentIds: [opinionEvidenceDeskSentenceIds.compostSortingSigns[4]],
  }),
  tm({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.compostSortingSigns.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointB,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointB[5],
    prompt: 'Match each statement to the best answer.',
    explanation: 'Each row names an idea the reader can identify in the passage.',
    evidenceReference: opinionEvidenceDeskFeatureIds.compostSortingSigns.visual,
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.compostSortingSigns[1],
      opinionEvidenceDeskSentenceIds.compostSortingSigns[4],
      opinionEvidenceDeskSentenceIds.compostSortingSigns[9],
    ],
    targetVocabulary: ['topic', 'opinion', 'purpose', 'fact'],
    soundOutChunks: ['mat', 'ch'],
    tags: ['opinion', 'opinion-vs-author-purpose', 'multiple-author-opinions', 'supporting-evidence'],
    rows: [
      {
        id: 'compost-topic-row',
        prompt: 'What is the topic?',
        correctChoiceId: 'compost-topic-answer',
        options: [
          choice('compost-topic-answer', 'compost sorting signs'),
          choice('compost-topic-opinion', 'The class should keep the sorting signs near the bin.'),
          choice('compost-topic-purpose', 'To explain how clear signs help students sort compost.'),
        ],
      },
      {
        id: 'compost-opinion-row',
        prompt: 'Which sentence is the opinion?',
        correctChoiceId: 'compost-opinion-answer',
        options: [
          choice('compost-opinion-answer', 'The class should keep the sorting signs near the bin.'),
          choice('compost-opinion-purpose', 'To explain how clear signs help students sort compost.'),
          choice('compost-opinion-fact', 'After the signs went up, the wrong items showed up less often.'),
        ],
      },
      {
        id: 'compost-purpose-row',
        prompt: 'Which sentence is the purpose?',
        correctChoiceId: 'compost-purpose-answer',
        options: [
          choice('compost-purpose-answer', 'To explain how clear signs help students sort compost.'),
          choice('compost-purpose-opinion', 'The class should keep the sorting signs near the bin.'),
          choice('compost-purpose-fact', 'One sign used a picture of an apple core and a leaf.'),
        ],
      },
      {
        id: 'compost-fact-row',
        prompt: 'Which sentence is a fact?',
        correctChoiceId: 'compost-fact-answer',
        options: [
          choice('compost-fact-answer', 'After the signs went up, the wrong items showed up less often.'),
          choice('compost-fact-opinion', 'The class should keep the sorting signs near the bin.'),
          choice('compost-fact-purpose', 'To explain how clear signs help students sort compost.'),
        ],
      },
    ],
  }),
  ep({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.compostSortingSigns.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointB,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointB[6],
    prompt: 'Choose the best answer for Part A and Part B.',
    explanation: 'The opinion fits because the mistake count and sign details show the signs help the bin.',
    evidenceReference: opinionEvidenceDeskSentenceIds.compostSortingSigns[4],
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.compostSortingSigns[1],
      opinionEvidenceDeskSentenceIds.compostSortingSigns[4],
      opinionEvidenceDeskSentenceIds.compostSortingSigns[7],
    ],
    targetVocabulary: ['opinion', 'evidence'],
    soundOutChunks: ['e', 'vi', 'dence'],
    tags: ['opinion', 'opinion-evidence-matching', 'multiple-author-opinions', 'evidence-connection', 'evidence-across-sections'],
    partAPrompt: 'What is the author opinion?',
    partAChoices: [
      choice('compost-part-a-1', 'The class should keep the sorting signs near the bin.'),
      choice('compost-part-a-2', 'To explain how clear signs help students sort compost.'),
      choice('compost-part-a-3', 'compost sorting signs'),
    ],
    partACorrectChoiceId: 'compost-part-a-1',
    partBPrompt: 'Which detail best supports that opinion?',
    partBChoices: [
      choice('compost-part-b-1', 'After the signs went up, the wrong items showed up less often.'),
      choice('compost-part-b-2', 'The guide paper beside the bin listed three good compost items.'),
      choice('compost-part-b-3', 'One sign used a picture of an apple core and a leaf.'),
    ],
    partBCorrectChoiceId: 'compost-part-b-1',
  }),

  mc({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.rainBarrelPlan.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointC,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointC[0],
    prompt: 'Which choice is the author opinion rather than the topic?',
    explanation: 'The opinion says what the gardeners should do.',
    evidenceReference: opinionEvidenceDeskSentenceIds.rainBarrelPlan[3],
    evidenceReferenceIds: [opinionEvidenceDeskSentenceIds.rainBarrelPlan[3]],
    targetVocabulary: ['opinion', 'topic'],
    soundOutChunks: ['top', 'ic'],
    tags: ['opinion', 'opinion-vs-topic', 'author-opinion-identification'],
    choices: [
      choice('rain-opinion', 'The gardeners should add a rain barrel by the shed.'),
      choice('rain-topic', 'rain barrels'),
      choice('rain-fact', 'The class measured more dry soil on the days without rain.'),
      choice('rain-purpose', 'To explain why a rain barrel would help the garden beds.'),
    ],
    correctChoiceIds: ['rain-opinion'],
  }),
  mc({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.rainBarrelPlan.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointC,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointC[1],
    prompt: 'Which choice is the author opinion rather than the central idea?',
    explanation: 'The central idea is broader than the opinion about the shed and barrel.',
    evidenceReference: opinionEvidenceDeskSentenceIds.rainBarrelPlan[4],
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.rainBarrelPlan[1],
      opinionEvidenceDeskSentenceIds.rainBarrelPlan[4],
    ],
    targetVocabulary: ['central idea', 'opinion'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['opinion', 'opinion-vs-central-idea'],
    choices: [
      choice('rain-central', 'Rain barrels can help the garden save water when the beds dry out.'),
      choice('rain-opinion', 'The gardeners should add a rain barrel by the shed.'),
      choice('rain-fact', 'A map showed the shed, the beds, and the gutter line.'),
      choice('rain-purpose', 'To explain why a rain barrel would help the garden beds.'),
    ],
    correctChoiceIds: ['rain-opinion'],
  }),
  mc({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.rainBarrelPlan.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointC,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointC[2],
    prompt: 'Which detail is the strongest evidence for the opinion?',
    explanation: 'This detail shows how the barrel would help the garden use water well.',
    evidenceReference: opinionEvidenceDeskSentenceIds.rainBarrelPlan[4],
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.rainBarrelPlan[1],
      opinionEvidenceDeskSentenceIds.rainBarrelPlan[2],
      opinionEvidenceDeskSentenceIds.rainBarrelPlan[4],
    ],
    targetVocabulary: ['evidence', 'strongest'],
    soundOutChunks: ['stron', 'gest'],
    tags: ['opinion', 'supporting-evidence', 'fact-vs-opinion', 'strongest-supporting-evidence'],
    choices: [
      choice('rain-evidence-1', 'The barrel could help the class water plants without using the hose as much.'),
      choice('rain-evidence-2', 'The community garden sat near a roof that sent rainwater into a gutter.'),
      choice('rain-evidence-3', 'The compost pile sat beside the shed.'),
      choice('rain-evidence-4', 'The gardeners should add a rain barrel by the shed.'),
    ],
    correctChoiceIds: ['rain-evidence-1'],
  }),
  ms({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.rainBarrelPlan.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointC,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointC[3],
    prompt: 'Choose two details that support the opinion.',
    explanation: 'These details show why the rain barrel would help the garden.',
    evidenceReference: opinionEvidenceDeskSentenceIds.rainBarrelPlan[2],
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.rainBarrelPlan[2],
      opinionEvidenceDeskSentenceIds.rainBarrelPlan[4],
    ],
    targetVocabulary: ['detail', 'support'],
    soundOutChunks: ['sup', 'port'],
    tags: ['opinion', 'supporting-evidence', 'supporting-evidence-identification', 'evidence-across-sections'],
    choices: [
      choice('rain-detail-1', 'A rain barrel could catch that water before it ran into the dirt path.'),
      choice('rain-detail-2', 'The garden beds dried out quickly on hot afternoons.'),
      choice('rain-detail-3', 'The compost pile sat beside the shed.'),
      choice('rain-detail-4', 'The barrel could help the class water plants without using the hose as much.'),
    ],
    correctChoiceIds: ['rain-detail-2', 'rain-detail-4'],
  }),
  ht({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.rainBarrelPlan.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointC,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointC[4],
    prompt: 'Select the sentence that gives a strong clue about the opinion.',
    explanation: 'The dry soil and water-use ideas show why the barrel would help.',
    evidenceReference: opinionEvidenceDeskSentenceIds.rainBarrelPlan[2],
    evidenceReferenceIds: [opinionEvidenceDeskSentenceIds.rainBarrelPlan[2]],
    targetVocabulary: ['clue', 'water'],
    soundOutChunks: ['wa', 'ter'],
    tags: ['opinion', 'supporting-evidence', 'strongest-supporting-evidence'],
    selectableSegments: [
      { id: opinionEvidenceDeskSentenceIds.rainBarrelPlan[1], text: 'A rain barrel could catch that water before it ran into the dirt path.' },
      { id: opinionEvidenceDeskSentenceIds.rainBarrelPlan[2], text: 'The garden beds dried out quickly on hot afternoons.' },
      { id: opinionEvidenceDeskSentenceIds.rainBarrelPlan[4], text: 'The barrel could help the class water plants without using the hose as much.' },
      { id: opinionEvidenceDeskSentenceIds.rainBarrelPlan[6], text: 'The class measured more dry soil on the days without rain.' },
    ],
    correctSegmentIds: [opinionEvidenceDeskSentenceIds.rainBarrelPlan[2]],
  }),
  tm({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.rainBarrelPlan.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointC,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointC[5],
    prompt: 'Match each statement to the best answer.',
    explanation: 'Each row names an idea the reader can identify in the passage.',
    evidenceReference: opinionEvidenceDeskFeatureIds.rainBarrelPlan.visual,
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.rainBarrelPlan[1],
      opinionEvidenceDeskSentenceIds.rainBarrelPlan[2],
      opinionEvidenceDeskSentenceIds.rainBarrelPlan[4],
    ],
    targetVocabulary: ['topic', 'opinion', 'purpose', 'fact'],
    soundOutChunks: ['mat', 'ch'],
    tags: ['opinion', 'opinion-vs-author-purpose', 'multiple-author-opinions', 'supporting-evidence'],
    rows: [
      {
        id: 'rain-topic-row',
        prompt: 'What is the topic?',
        correctChoiceId: 'rain-topic-answer',
        options: [
          choice('rain-topic-answer', 'rain barrels'),
          choice('rain-topic-opinion', 'The gardeners should add a rain barrel by the shed.'),
          choice('rain-topic-purpose', 'To explain why a rain barrel would help the garden beds.'),
        ],
      },
      {
        id: 'rain-opinion-row',
        prompt: 'Which sentence is the opinion?',
        correctChoiceId: 'rain-opinion-answer',
        options: [
          choice('rain-opinion-answer', 'The gardeners should add a rain barrel by the shed.'),
          choice('rain-opinion-purpose', 'To explain why a rain barrel would help the garden beds.'),
          choice('rain-opinion-fact', 'The garden beds dried out quickly on hot afternoons.'),
        ],
      },
      {
        id: 'rain-purpose-row',
        prompt: 'Which sentence is the purpose?',
        correctChoiceId: 'rain-purpose-answer',
        options: [
          choice('rain-purpose-answer', 'To explain why a rain barrel would help the garden beds.'),
          choice('rain-purpose-opinion', 'The gardeners should add a rain barrel by the shed.'),
          choice('rain-purpose-fact', 'The class measured more dry soil on the days without rain.'),
        ],
      },
      {
        id: 'rain-fact-row',
        prompt: 'Which sentence is a fact?',
        correctChoiceId: 'rain-fact-answer',
        options: [
          choice('rain-fact-answer', 'The garden beds dried out quickly on hot afternoons.'),
          choice('rain-fact-opinion', 'The gardeners should add a rain barrel by the shed.'),
          choice('rain-fact-purpose', 'To explain why a rain barrel would help the garden beds.'),
        ],
      },
    ],
  }),
  ep({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.rainBarrelPlan.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.checkpointC,
    questionIdentifier: opinionEvidenceDeskQuestionIds.checkpointC[6],
    prompt: 'Choose the best answer for Part A and Part B.',
    explanation: 'The opinion fits because the rainwater and dry-soil details show why the barrel would help.',
    evidenceReference: opinionEvidenceDeskSentenceIds.rainBarrelPlan[4],
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.rainBarrelPlan[1],
      opinionEvidenceDeskSentenceIds.rainBarrelPlan[2],
      opinionEvidenceDeskSentenceIds.rainBarrelPlan[4],
    ],
    targetVocabulary: ['opinion', 'evidence'],
    soundOutChunks: ['e', 'vi', 'dence'],
    tags: ['opinion', 'opinion-evidence-matching', 'multiple-author-opinions', 'evidence-connection', 'evidence-across-sections'],
    partAPrompt: 'What is the author opinion?',
    partAChoices: [
      choice('rain-part-a-1', 'The gardeners should add a rain barrel by the shed.'),
      choice('rain-part-a-2', 'To explain why a rain barrel would help the garden beds.'),
      choice('rain-part-a-3', 'rain barrels'),
    ],
    partACorrectChoiceId: 'rain-part-a-1',
    partBPrompt: 'Which detail best supports that opinion?',
    partBChoices: [
      choice('rain-part-b-1', 'The barrel could help the class water plants without using the hose as much.'),
      choice('rain-part-b-2', 'The garden beds dried out quickly on hot afternoons.'),
      choice('rain-part-b-3', 'The compost pile sat beside the shed.'),
    ],
    partBCorrectChoiceId: 'rain-part-b-1',
  }),
]
