import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
  lessonChoice as choice,
} from './questionFactories'
import {
  opinionEvidenceDeskContentVersion,
  opinionEvidenceDeskFeatureIds,
  opinionEvidenceDeskLessonIds,
  opinionEvidenceDeskPassageIds,
  opinionEvidenceDeskQuestionIds,
  opinionEvidenceDeskSentenceIds,
} from './ids'

const base = {
  benchmarkReference: 'ELA.2.R.2.4' as const,
  skillIdentifier: 'g2-information-detectives-reading' as const,
  reportingCategory: 'Reading Informational Text' as const,
  genre: 'informational' as const,
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2' as const,
  contentVersion: opinionEvidenceDeskContentVersion,
  reviewStatus: 'DRAFT' as const,
}

const mc = (spec: Parameters<typeof createMultipleChoiceQuestion>[0]) => createMultipleChoiceQuestion(spec)
const ms = (spec: Parameters<typeof createMultiselectQuestion>[0]) => createMultiselectQuestion(spec)
const ht = (spec: Parameters<typeof createHotTextQuestion>[0]) => createHotTextQuestion(spec)
const tm = (spec: Parameters<typeof createTableMatchQuestion>[0]) => createTableMatchQuestion(spec)

export const opinionEvidenceDeskGuidedQuestions = [
  mc({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.clearTrailSymbols.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.guidedFindOpinion,
    questionIdentifier: opinionEvidenceDeskQuestionIds.guidedFindOpinion[0],
    prompt: 'Which choice is the author opinion rather than the topic?',
    explanation: 'The opinion says what the author thinks should happen, not just what the text is about.',
    evidenceReference: opinionEvidenceDeskFeatureIds.clearTrailSymbols.title,
    evidenceReferenceIds: [opinionEvidenceDeskFeatureIds.clearTrailSymbols.title],
    targetVocabulary: ['opinion', 'topic'],
    soundOutChunks: ['op', 'in', 'ion'],
    tags: ['opinion', 'opinion-vs-topic', 'author-opinion-identification'],
    choices: [
      choice('trail-opinion', 'The trail map should use clearer symbols so visitors can find places quickly.'),
      choice('trail-topic', 'trail map symbols'),
      choice('trail-fact', 'The key shows that the star means the overlook and the drop means water.'),
      choice('trail-purpose', 'To explain how map symbols and a legend help visitors find places quickly.'),
    ],
    correctChoiceIds: ['trail-opinion'],
  }),
  mc({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.clearTrailSymbols.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.guidedFindOpinion,
    questionIdentifier: opinionEvidenceDeskQuestionIds.guidedFindOpinion[1],
    prompt: 'Which choice is the author opinion rather than the central idea?',
    explanation: 'The central idea is broader, while the opinion says what the author thinks should happen.',
    evidenceReference: opinionEvidenceDeskSentenceIds.clearTrailSymbols[5],
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.clearTrailSymbols[1],
      opinionEvidenceDeskSentenceIds.clearTrailSymbols[3],
    ],
    targetVocabulary: ['central idea', 'opinion'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['opinion', 'opinion-vs-central-idea'],
    choices: [
      choice('trail-central', 'Clear symbols help visitors keep moving without getting turned around.'),
      choice('trail-opinion', 'The trail map should use clearer symbols so visitors can find places quickly.'),
      choice('trail-fact', 'A map legend lists the symbols and what they mean.'),
      choice('trail-purpose', 'To explain how map symbols and a legend help visitors find places quickly.'),
    ],
    correctChoiceIds: ['trail-opinion'],
  }),
  ms({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.clearTrailSymbols.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.guidedFindOpinion,
    questionIdentifier: opinionEvidenceDeskQuestionIds.guidedFindOpinion[2],
    prompt: 'Choose two details that help explain why the author wants clearer symbols.',
    explanation: 'These details show the problem and the clue that fixes it.',
    evidenceReference: opinionEvidenceDeskSentenceIds.clearTrailSymbols[1],
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.clearTrailSymbols[1],
      opinionEvidenceDeskSentenceIds.clearTrailSymbols[6],
    ],
    targetVocabulary: ['detail', 'evidence'],
    soundOutChunks: ['de', 'tail'],
    tags: ['opinion', 'supporting-evidence', 'supporting-evidence-identification', 'evidence-across-sections'],
    choices: [
      choice('trail-detail-1', 'A family paused because they could not tell which symbol meant the rest stop.'),
      choice('trail-detail-2', 'The ranger added a small key near the top of the map.'),
      choice('trail-detail-3', 'The path marker at the river bends to the left.'),
      choice('trail-detail-4', 'A map legend lists the symbols and what they mean.'),
    ],
    correctChoiceIds: ['trail-detail-1', 'trail-detail-4'],
  }),
  ht({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.clearTrailSymbols.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.guidedFindOpinion,
    questionIdentifier: opinionEvidenceDeskQuestionIds.guidedFindOpinion[3],
    prompt: 'Select the sentence that gives a strong clue about the opinion.',
    explanation: 'The family pause shows that the map symbols were hard to understand.',
    evidenceReference: opinionEvidenceDeskSentenceIds.clearTrailSymbols[1],
    evidenceReferenceIds: [opinionEvidenceDeskSentenceIds.clearTrailSymbols[1]],
    targetVocabulary: ['clue', 'symbols'],
    soundOutChunks: ['sym', 'bols'],
    tags: ['supporting-evidence', 'strongest-supporting-evidence'],
    selectableSegments: [
      { id: opinionEvidenceDeskSentenceIds.clearTrailSymbols[0], text: 'The trail map uses arrows, stars, and water-drop symbols.' },
      { id: opinionEvidenceDeskSentenceIds.clearTrailSymbols[1], text: 'A family paused because they could not tell which symbol meant the rest stop.' },
      { id: opinionEvidenceDeskSentenceIds.clearTrailSymbols[3], text: 'The key shows that the star means the overlook and the drop means water.' },
      { id: opinionEvidenceDeskSentenceIds.clearTrailSymbols[7], text: 'Clear symbols help visitors keep moving without getting turned around.' },
    ],
    correctSegmentIds: [opinionEvidenceDeskSentenceIds.clearTrailSymbols[1]],
  }),
  tm({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.clearTrailSymbols.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.guidedFindOpinion,
    questionIdentifier: opinionEvidenceDeskQuestionIds.guidedFindOpinion[4],
    prompt: 'Match each statement to the best answer.',
    explanation: 'Each row matches a statement to the idea it names.',
    evidenceReference: opinionEvidenceDeskFeatureIds.clearTrailSymbols.visual,
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.clearTrailSymbols[1],
      opinionEvidenceDeskSentenceIds.clearTrailSymbols[3],
      opinionEvidenceDeskSentenceIds.clearTrailSymbols[7],
    ],
    targetVocabulary: ['topic', 'opinion', 'purpose', 'detail'],
    soundOutChunks: ['mat', 'ch'],
    tags: ['opinion', 'opinion-vs-author-purpose', 'supporting-evidence'],
    rows: [
      {
        id: 'trail-topic-row',
        prompt: 'What is the topic?',
        correctChoiceId: 'trail-topic-answer',
        options: [
          choice('trail-topic-answer', 'trail map symbols'),
          choice('trail-topic-opinion', 'The trail map should use clearer symbols so visitors can find places quickly.'),
          choice('trail-topic-purpose', 'To explain how map symbols and a legend help visitors find places quickly.'),
        ],
      },
      {
        id: 'trail-opinion-row',
        prompt: 'Which sentence is the opinion?',
        correctChoiceId: 'trail-opinion-answer',
        options: [
          choice('trail-opinion-answer', 'The trail map should use clearer symbols so visitors can find places quickly.'),
          choice('trail-opinion-purpose', 'To explain how map symbols and a legend help visitors find places quickly.'),
          choice('trail-opinion-detail', 'The path marker at the river bends to the left.'),
        ],
      },
      {
        id: 'trail-purpose-row',
        prompt: 'Which sentence is the purpose?',
        correctChoiceId: 'trail-purpose-answer',
        options: [
          choice('trail-purpose-answer', 'To explain how map symbols and a legend help visitors find places quickly.'),
          choice('trail-purpose-opinion', 'The trail map should use clearer symbols so visitors can find places quickly.'),
          choice('trail-purpose-fact', 'A map legend lists the symbols and what they mean.'),
        ],
      },
      {
        id: 'trail-detail-row',
        prompt: 'Which sentence is another true detail?',
        correctChoiceId: 'trail-detail-answer',
        options: [
          choice('trail-detail-answer', 'The path marker at the river bends to the left.'),
          choice('trail-detail-opinion', 'The trail map should use clearer symbols so visitors can find places quickly.'),
          choice('trail-detail-purpose', 'To explain how map symbols and a legend help visitors find places quickly.'),
        ],
      },
    ],
  }),
  mc({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.reusableContainers.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.guidedChooseStrongestEvidence,
    questionIdentifier: opinionEvidenceDeskQuestionIds.guidedChooseStrongestEvidence[0],
    prompt: 'Which choice is the author opinion rather than the topic?',
    explanation: 'The opinion says what the author thinks the class should do.',
    evidenceReference: opinionEvidenceDeskFeatureIds.reusableContainers.title,
    evidenceReferenceIds: [opinionEvidenceDeskFeatureIds.reusableContainers.title],
    targetVocabulary: ['opinion', 'containers'],
    soundOutChunks: ['con', 'tain', 'ers'],
    tags: ['opinion', 'opinion-vs-topic', 'author-opinion-identification'],
    choices: [
      choice('container-opinion', 'The class should use reusable containers for the school event.'),
      choice('container-topic', 'reusable containers'),
      choice('container-fact', 'Each box could be washed and used again.'),
      choice('container-purpose', 'To explain why reusable containers help at the school event.'),
    ],
    correctChoiceIds: ['container-opinion'],
  }),
  mc({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.reusableContainers.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.guidedChooseStrongestEvidence,
    questionIdentifier: opinionEvidenceDeskQuestionIds.guidedChooseStrongestEvidence[1],
    prompt: 'Which explanation best shows how the evidence supports the opinion?',
    explanation: 'The explanation tells how the detail connects to the opinion.',
    evidenceReference: opinionEvidenceDeskSentenceIds.reusableContainers[1],
    evidenceReferenceIds: [opinionEvidenceDeskSentenceIds.reusableContainers[1], opinionEvidenceDeskSentenceIds.reusableContainers[2]],
    targetVocabulary: ['evidence', 'supports'],
    soundOutChunks: ['sup', 'port'],
    tags: ['opinion', 'supporting-evidence', 'evidence-connection', 'strongest-supporting-evidence'],
    choices: [
      choice('container-explain-1', 'The boxes could be washed and used again, so the class would not need new trays every time.'),
      choice('container-explain-2', 'The class packed fruit and crackers in sturdy plastic boxes.'),
      choice('container-explain-3', 'Reusable means something can be used again after it is cleaned.'),
      choice('container-explain-4', 'To explain how boxes are packed for the event.'),
    ],
    correctChoiceIds: ['container-explain-1'],
  }),
  ms({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.reusableContainers.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.guidedChooseStrongestEvidence,
    questionIdentifier: opinionEvidenceDeskQuestionIds.guidedChooseStrongestEvidence[2],
    prompt: 'Choose two details that help explain why reusable containers are a good choice.',
    explanation: 'These details show that the boxes can be used again and help cut wrappers.',
    evidenceReference: opinionEvidenceDeskSentenceIds.reusableContainers[1],
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.reusableContainers[1],
      opinionEvidenceDeskSentenceIds.reusableContainers[2],
    ],
    targetVocabulary: ['detail', 'reusable'],
    soundOutChunks: ['re', 'use'],
    tags: ['opinion', 'supporting-evidence', 'supporting-evidence-identification', 'evidence-across-sections'],
    choices: [
      choice('container-detail-1', 'Each box could be washed and used again.'),
      choice('container-detail-2', 'The trash can held fewer wrappers when the class used the boxes.'),
      choice('container-detail-3', 'The return bin near the door kept the empty boxes together.'),
      choice('container-detail-4', 'Reusable means something can be used again after it is cleaned.'),
    ],
    correctChoiceIds: ['container-detail-1', 'container-detail-2'],
  }),
  ht({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.reusableContainers.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.guidedChooseStrongestEvidence,
    questionIdentifier: opinionEvidenceDeskQuestionIds.guidedChooseStrongestEvidence[3],
    prompt: 'Select the sentence that gives a strong clue about the opinion.',
    explanation: 'The sentence shows the boxes can be used again, which helps the opinion fit.',
    evidenceReference: opinionEvidenceDeskSentenceIds.reusableContainers[1],
    evidenceReferenceIds: [opinionEvidenceDeskSentenceIds.reusableContainers[1]],
    targetVocabulary: ['clue', 'boxes'],
    soundOutChunks: ['box', 'es'],
    tags: ['supporting-evidence', 'strongest-supporting-evidence'],
    selectableSegments: [
      { id: opinionEvidenceDeskSentenceIds.reusableContainers[0], text: 'The class packed fruit and crackers in sturdy plastic boxes.' },
      { id: opinionEvidenceDeskSentenceIds.reusableContainers[1], text: 'Each box could be washed and used again.' },
      { id: opinionEvidenceDeskSentenceIds.reusableContainers[4], text: 'The return bin near the door kept the empty boxes together.' },
      { id: opinionEvidenceDeskSentenceIds.reusableContainers[6], text: 'The boxes cost less than buying new paper trays every time.' },
    ],
    correctSegmentIds: [opinionEvidenceDeskSentenceIds.reusableContainers[1]],
  }),
  tm({
    ...base,
    difficulty: 4,
    passageIdentifier: opinionEvidenceDeskPassageIds.reusableContainers.passageId,
    lessonIdentifier: opinionEvidenceDeskLessonIds.guidedChooseStrongestEvidence,
    questionIdentifier: opinionEvidenceDeskQuestionIds.guidedChooseStrongestEvidence[4],
    prompt: 'Match each statement to the best answer.',
    explanation: 'Each row names an idea the reader can identify in the passage.',
    evidenceReference: opinionEvidenceDeskFeatureIds.reusableContainers.visual,
    evidenceReferenceIds: [
      opinionEvidenceDeskSentenceIds.reusableContainers[1],
      opinionEvidenceDeskSentenceIds.reusableContainers[2],
      opinionEvidenceDeskSentenceIds.reusableContainers[6],
    ],
    targetVocabulary: ['topic', 'opinion', 'purpose', 'fact'],
    soundOutChunks: ['mat', 'ch'],
    tags: ['opinion', 'opinion-vs-author-purpose', 'supporting-evidence'],
    rows: [
      {
        id: 'container-topic-row',
        prompt: 'What is the topic?',
        correctChoiceId: 'container-topic-answer',
        options: [
          choice('container-topic-answer', 'reusable containers'),
          choice('container-topic-opinion', 'The class should use reusable containers for the school event.'),
          choice('container-topic-purpose', 'To explain why reusable containers help at the school event.'),
        ],
      },
      {
        id: 'container-opinion-row',
        prompt: 'Which sentence is the opinion?',
        correctChoiceId: 'container-opinion-answer',
        options: [
          choice('container-opinion-answer', 'The class should use reusable containers for the school event.'),
          choice('container-opinion-purpose', 'To explain why reusable containers help at the school event.'),
          choice('container-opinion-fact', 'Each box could be washed and used again.'),
        ],
      },
      {
        id: 'container-purpose-row',
        prompt: 'Which sentence is the purpose?',
        correctChoiceId: 'container-purpose-answer',
        options: [
          choice('container-purpose-answer', 'To explain why reusable containers help at the school event.'),
          choice('container-purpose-opinion', 'The class should use reusable containers for the school event.'),
          choice('container-purpose-fact', 'The trash can held fewer wrappers when the class used the boxes.'),
        ],
      },
      {
        id: 'container-fact-row',
        prompt: 'Which sentence is a fact?',
        correctChoiceId: 'container-fact-answer',
        options: [
          choice('container-fact-answer', 'Each box could be washed and used again.'),
          choice('container-fact-opinion', 'The class should use reusable containers for the school event.'),
          choice('container-fact-purpose', 'To explain why reusable containers help at the school event.'),
        ],
      },
    ],
  }),
]
