import { createHotTextQuestion, createMultipleChoiceQuestion, createMultiselectQuestion, createTableMatchQuestion } from '../variableVowelsOoEa/questionFactories'
import { TWO_SYLLABLE_OPEN_CLOSED_CONTENT_VERSION, TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS, TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS, TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS } from './ids'

const shortCommon = {
  benchmarkReference: 'ELA.2.F.1.3b',
  skillIdentifier: 'g2-word-forge-word-practice',
  prerequisiteSkillIdentifiers: [],
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'word-lab',
  estimatedReadingLevel: 'grade-2-bridge',
  reviewStatus: 'DRAFT' as const,
  contentVersion: TWO_SYLLABLE_OPEN_CLOSED_CONTENT_VERSION,
  tags: ['grade-2', 'bridge', 'word-forge', 'two-syllable-short-vowels', 'guided-practice'],
}

const longCommon = {
  benchmarkReference: 'ELA.2.F.1.3b',
  skillIdentifier: 'g2-word-forge-word-practice',
  prerequisiteSkillIdentifiers: [],
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'word-lab',
  estimatedReadingLevel: 'grade-2-bridge',
  reviewStatus: 'DRAFT' as const,
  contentVersion: TWO_SYLLABLE_OPEN_CLOSED_CONTENT_VERSION,
  tags: ['grade-2', 'bridge', 'word-forge', 'two-syllable-long-vowels', 'guided-practice'],
}

export const guidedQuestions = [
  createMultipleChoiceQuestion({
    ...shortCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.picnicPlanning,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedShort,
    activityIdentifier: 'activity-word-forge-syllable-summit-guided-short-vowels-1',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedShort[0],
    prompt: 'Which word has two short vowels like picnic?',
    explanation: 'Picnic has two short vowel sounds in its authored chunks.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['picnic-choice'],
    targetVocabulary: ['picnic', 'sunset'],
    soundOutChunks: ['pic', 'nic'],
    choices: [
      { id: 'picnic-choice', text: 'picnic' },
      { id: 'robot-choice', text: 'robot' },
      { id: 'music-choice', text: 'music' },
      { id: 'photo-choice', text: 'photo' },
    ],
    correctChoiceIds: ['picnic-choice'],
  }),
  createMultipleChoiceQuestion({
    ...shortCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.picnicPlanning,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedShort,
    activityIdentifier: 'activity-word-forge-syllable-summit-guided-short-vowels-2',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedShort[1],
    prompt: 'Which word has two short vowels like sunset?',
    explanation: 'Sunset has two short vowel sounds in its authored chunks.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['sunset-choice'],
    targetVocabulary: ['sunset', 'magnet'],
    soundOutChunks: ['sun', 'set'],
    choices: [
      { id: 'sunset-choice', text: 'sunset' },
      { id: 'pilot-choice', text: 'pilot' },
      { id: 'tulip-choice', text: 'tulip' },
      { id: 'solo-choice', text: 'solo' },
    ],
    correctChoiceIds: ['sunset-choice'],
  }),
  createMultiselectQuestion({
    ...shortCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.picnicPlanning,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedShort,
    activityIdentifier: 'activity-word-forge-syllable-summit-guided-short-vowels-3',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedShort[2],
    prompt: 'Choose all the words with short-vowel two-syllable chunks in the picnic passage.',
    explanation: 'Picnic and sunset use short-vowel chunks in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['picnic-choice', 'sunset-choice'],
    targetVocabulary: ['picnic', 'sunset'],
    soundOutChunks: ['short two-syllable words'],
    choices: [
      { id: 'picnic-choice', text: 'picnic' },
      { id: 'sunset-choice', text: 'sunset' },
      { id: 'robot-choice', text: 'robot' },
      { id: 'music-choice', text: 'music' },
    ],
    correctChoiceIds: ['picnic-choice', 'sunset-choice'],
  }),
  createHotTextQuestion({
    ...shortCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.picnicPlanning,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedShort,
    activityIdentifier: 'activity-word-forge-syllable-summit-guided-short-vowels-4',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedShort[3],
    prompt: 'Select the sentence that says they packed a basket, a napkin, and a magnet chart.',
    explanation: 'The second sentence gives the basket, napkin, and magnet clue.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['picnic-planning-2'],
    targetVocabulary: ['basket', 'napkin', 'magnet'],
    soundOutChunks: ['picnic'],
    selectableSegments: [
      { id: 'picnic-planning-1', text: 'The picnic team spread a blanket by the sunset tree.' },
      { id: 'picnic-planning-2', text: 'They packed a basket, a napkin, and a magnet chart.' },
      { id: 'picnic-planning-3', text: 'A kitten watched the lunch plan from a chair.' },
    ],
    correctSegmentIds: ['picnic-planning-2'],
  }),
  createTableMatchQuestion({
    ...shortCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.picnicPlanning,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedShort,
    activityIdentifier: 'activity-word-forge-syllable-summit-guided-short-vowels-5',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedShort[4],
    prompt: 'Match each word to its short-vowel chunking.',
    explanation: 'Each word is split with a short-vowel chunk in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['picnic-pic-nic', 'magnet-mag-net'],
    targetVocabulary: ['picnic', 'magnet'],
    soundOutChunks: ['short two-syllable words'],
    rows: [
      {
        id: 'picnic-row',
        prompt: 'picnic',
        correctChoiceId: 'picnic-pic-nic',
        options: [
          { id: 'picnic-pic-nic', text: 'pic / nic' },
          { id: 'picnic-ro-bot', text: 'ro / bot' },
          { id: 'picnic-tu-lip', text: 'tu / lip' },
        ],
      },
      {
        id: 'magnet-row',
        prompt: 'magnet',
        correctChoiceId: 'magnet-mag-net',
        options: [
          { id: 'magnet-mag-net', text: 'mag / net' },
          { id: 'magnet-so-lo', text: 'so / lo' },
          { id: 'magnet-pho-to', text: 'pho / to' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...longCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.musicRoom,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedLong,
    activityIdentifier: 'activity-word-forge-syllable-summit-guided-long-vowels-1',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedLong[0],
    prompt: 'Which word has a long-vowel two-syllable pattern like robot?',
    explanation: 'Robot begins with an open syllable and a long vowel sound.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['robot-choice'],
    targetVocabulary: ['robot', 'photo'],
    soundOutChunks: ['ro', 'bot'],
    choices: [
      { id: 'robot-choice', text: 'robot' },
      { id: 'basket-choice', text: 'basket' },
      { id: 'kitten-choice', text: 'kitten' },
      { id: 'helmet-choice', text: 'helmet' },
    ],
    correctChoiceIds: ['robot-choice'],
  }),
  createMultipleChoiceQuestion({
    ...longCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.musicRoom,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedLong,
    activityIdentifier: 'activity-word-forge-syllable-summit-guided-long-vowels-2',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedLong[1],
    prompt: 'Which word has a long-vowel two-syllable pattern like music?',
    explanation: 'Music begins with an open syllable and a long vowel sound.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['music-choice'],
    targetVocabulary: ['music', 'tulip'],
    soundOutChunks: ['mu', 'sic'],
    choices: [
      { id: 'music-choice', text: 'music' },
      { id: 'sunset-choice', text: 'sunset' },
      { id: 'magnet-choice', text: 'magnet' },
      { id: 'napkin-choice', text: 'napkin' },
    ],
    correctChoiceIds: ['music-choice'],
  }),
  createMultiselectQuestion({
    ...longCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.musicRoom,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedLong,
    activityIdentifier: 'activity-word-forge-syllable-summit-guided-long-vowels-3',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedLong[2],
    prompt: 'Choose all the words with long-vowel two-syllable chunks in the music passage.',
    explanation: 'Music, tulip, solo, and photo each use open syllables in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['music-choice', 'tulip-choice', 'solo-choice', 'photo-choice'],
    targetVocabulary: ['music', 'tulip', 'solo', 'photo'],
    soundOutChunks: ['long two-syllable words'],
    choices: [
      { id: 'music-choice', text: 'music' },
      { id: 'tulip-choice', text: 'tulip' },
      { id: 'solo-choice', text: 'solo' },
      { id: 'photo-choice', text: 'photo' },
    ],
    correctChoiceIds: ['music-choice', 'tulip-choice', 'solo-choice', 'photo-choice'],
  }),
  createHotTextQuestion({
    ...longCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.musicRoom,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedLong,
    activityIdentifier: 'activity-word-forge-syllable-summit-guided-long-vowels-4',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedLong[3],
    prompt: 'Select the sentence that says a photo of the zero sign stayed on the wall.',
    explanation: 'The third sentence gives the photo and zero clue.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['music-room-3'],
    targetVocabulary: ['photo', 'zero', 'wall'],
    soundOutChunks: ['photo'],
    selectableSegments: [
      { id: 'music-room-1', text: 'In the music room, the robot kept a steady beat.' },
      { id: 'music-room-2', text: 'The tulip poster hung near a solo chair.' },
      { id: 'music-room-3', text: 'A photo of the zero sign stayed on the wall.' },
    ],
    correctSegmentIds: ['music-room-3'],
  }),
  createTableMatchQuestion({
    ...longCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.musicRoom,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedLong,
    activityIdentifier: 'activity-word-forge-syllable-summit-guided-long-vowels-5',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedLong[4],
    prompt: 'Match each word to its long-vowel chunking.',
    explanation: 'The chunks show the open syllables clearly.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['music-mu-sic', 'photo-pho-to'],
    targetVocabulary: ['music', 'photo'],
    soundOutChunks: ['long two-syllable words'],
    rows: [
      {
        id: 'music-row',
        prompt: 'music',
        correctChoiceId: 'music-mu-sic',
        options: [
          { id: 'music-mu-sic', text: 'mu / sic' },
          { id: 'music-pic-nic', text: 'pic / nic' },
          { id: 'music-rab-bit', text: 'rab / bit' },
        ],
      },
      {
        id: 'photo-row',
        prompt: 'photo',
        correctChoiceId: 'photo-pho-to',
        options: [
          { id: 'photo-pho-to', text: 'pho / to' },
          { id: 'photo-sun-set', text: 'sun / set' },
          { id: 'photo-mag-net', text: 'mag / net' },
        ],
      },
    ],
  }),
]
