import { createHotTextQuestion, createMultipleChoiceQuestion, createMultiselectQuestion, createTableMatchQuestion } from '../variableVowelsOoEa/questionFactories'
import { TWO_SYLLABLE_OPEN_CLOSED_CONTENT_VERSION, TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS, TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS, TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS } from './ids'

const shortCommon = {
  benchmarkReference: 'ELA.2.F.1.3b',
  skillIdentifier: 'g2-word-forge-word-practice',
  prerequisiteSkillIdentifiers: [],
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'word-lab',
  estimatedReadingLevel: 'grade-2-bridge',
  reviewStatus: 'DRAFT' as const,
  contentVersion: TWO_SYLLABLE_OPEN_CLOSED_CONTENT_VERSION,
  tags: ['grade-2', 'bridge', 'word-forge', 'two-syllable-short-vowels', 'checkpoint'],
}

const longCommon = {
  benchmarkReference: 'ELA.2.F.1.3b',
  skillIdentifier: 'g2-word-forge-word-practice',
  prerequisiteSkillIdentifiers: [],
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'word-lab',
  estimatedReadingLevel: 'grade-2-bridge',
  reviewStatus: 'DRAFT' as const,
  contentVersion: TWO_SYLLABLE_OPEN_CLOSED_CONTENT_VERSION,
  tags: ['grade-2', 'bridge', 'word-forge', 'two-syllable-long-vowels', 'checkpoint'],
}

const openCommon = {
  benchmarkReference: 'ELA.2.F.1.3c',
  skillIdentifier: 'g2-word-forge-word-practice',
  prerequisiteSkillIdentifiers: [],
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'word-lab',
  estimatedReadingLevel: 'grade-2-bridge',
  reviewStatus: 'DRAFT' as const,
  contentVersion: TWO_SYLLABLE_OPEN_CLOSED_CONTENT_VERSION,
  tags: ['grade-2', 'bridge', 'word-forge', 'open-syllable', 'checkpoint'],
}

const closedCommon = {
  benchmarkReference: 'ELA.2.F.1.3c',
  skillIdentifier: 'g2-word-forge-word-practice',
  prerequisiteSkillIdentifiers: [],
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'word-lab',
  estimatedReadingLevel: 'grade-2-bridge',
  reviewStatus: 'DRAFT' as const,
  contentVersion: TWO_SYLLABLE_OPEN_CLOSED_CONTENT_VERSION,
  tags: ['grade-2', 'bridge', 'word-forge', 'closed-syllable', 'checkpoint'],
}

export const checkpointQuestions = [
  createMultipleChoiceQuestion({
    ...shortCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.rabbitHabitat,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-a-1',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointA[0],
    prompt: 'Which word has two short vowels like picnic?',
    explanation: 'Picnic uses two short vowels in its authored chunks.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['picnic-choice'],
    targetVocabulary: ['picnic', 'sunset'],
    soundOutChunks: ['pic', 'nic'],
    choices: [
      { id: 'picnic-choice', text: 'picnic' },
      { id: 'robot-choice', text: 'robot' },
      { id: 'music-choice', text: 'music' },
      { id: 'photo-choice', text: 'photo' },
    ],
    correctChoiceIds: ['picnic-choice'],
  }),
  createMultipleChoiceQuestion({
    ...longCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.robotExhibit,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-a-2',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointA[1],
    prompt: 'Which word has two long vowels like music?',
    explanation: 'Music begins with an open syllable and a long vowel sound.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['music-choice'],
    targetVocabulary: ['music', 'robot'],
    soundOutChunks: ['mu', 'sic'],
    choices: [
      { id: 'music-choice', text: 'music' },
      { id: 'sunset-choice', text: 'sunset' },
      { id: 'napkin-choice', text: 'napkin' },
      { id: 'helmet-choice', text: 'helmet' },
    ],
    correctChoiceIds: ['music-choice'],
  }),
  createMultiselectQuestion({
    ...shortCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.picnicPlanning,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-a-3',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointA[2],
    prompt: 'Choose all the short-vowel two-syllable words in these passages.',
    explanation: 'Rabbit, picnic, and sunset use short-vowel chunks in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['rabbit-choice', 'picnic-choice', 'sunset-choice'],
    targetVocabulary: ['rabbit', 'picnic', 'sunset', 'music'],
    soundOutChunks: ['short two-syllable words'],
    choices: [
      { id: 'rabbit-choice', text: 'rabbit' },
      { id: 'picnic-choice', text: 'picnic' },
      { id: 'sunset-choice', text: 'sunset' },
      { id: 'robot-choice', text: 'robot' },
    ],
    correctChoiceIds: ['rabbit-choice', 'picnic-choice', 'sunset-choice'],
  }),
  createHotTextQuestion({
    ...longCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.robotExhibit,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-a-4',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointA[3],
    prompt: 'Select the sentence that says a pilot played music while the model spun.',
    explanation: 'The second sentence gives the music clue.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['robot-exhibit-2'],
    targetVocabulary: ['pilot', 'music', 'model'],
    soundOutChunks: ['music'],
    selectableSegments: [
      { id: 'robot-exhibit-1', text: 'The robot stood on an open stage at the exhibit.' },
      { id: 'robot-exhibit-2', text: 'A pilot played music while the model spun.' },
      { id: 'robot-exhibit-3', text: 'The photo card showed a zero beside a solar unit.' },
    ],
    correctSegmentIds: ['robot-exhibit-2'],
  }),
  createTableMatchQuestion({
    ...longCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.robotExhibit,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-a-5',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointA[4],
    prompt: 'Match each word to its two-syllable chunks.',
    explanation: 'The chunks show the long-vowel two-syllable words clearly.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['robot-ro-bot', 'photo-pho-to'],
    targetVocabulary: ['robot', 'photo'],
    soundOutChunks: ['two-syllable words'],
    rows: [
      {
        id: 'robot-row',
        prompt: 'robot',
        correctChoiceId: 'robot-ro-bot',
        options: [
          { id: 'robot-ro-bot', text: 'ro / bot' },
          { id: 'robot-pic-nic', text: 'pic / nic' },
          { id: 'robot-sun-set', text: 'sun / set' },
        ],
      },
      {
        id: 'photo-row',
        prompt: 'photo',
        correctChoiceId: 'photo-pho-to',
        options: [
          { id: 'photo-pho-to', text: 'pho / to' },
          { id: 'photo-rab-bit', text: 'rab / bit' },
          { id: 'photo-mag-net', text: 'mag / net' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...openCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.robotExhibit,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-a-6',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointA[5],
    prompt: 'Which word has an open syllable like robot?',
    explanation: 'Robot begins with an open syllable that says its long vowel sound.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['robot-choice'],
    targetVocabulary: ['robot', 'pilot'],
    soundOutChunks: ['open syllable'],
    choices: [
      { id: 'robot-choice', text: 'robot' },
      { id: 'basket-choice', text: 'basket' },
      { id: 'kitten-choice', text: 'kitten' },
      { id: 'napkin-choice', text: 'napkin' },
    ],
    correctChoiceIds: ['robot-choice'],
  }),
  createMultipleChoiceQuestion({
    ...closedCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.rabbitHabitat,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-a-7',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointA[6],
    prompt: 'Which word has a closed syllable like rabbit?',
    explanation: 'Rabbit begins with a closed syllable that ends with a consonant.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['rabbit-choice'],
    targetVocabulary: ['rabbit', 'basket'],
    soundOutChunks: ['closed syllable'],
    choices: [
      { id: 'rabbit-choice', text: 'rabbit' },
      { id: 'robot-choice', text: 'robot' },
      { id: 'music-choice', text: 'music' },
      { id: 'photo-choice', text: 'photo' },
    ],
    correctChoiceIds: ['rabbit-choice'],
  }),
  createMultipleChoiceQuestion({
    ...shortCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.musicRoom,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-b-1',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointB[0],
    prompt: 'Which word has two short vowels like magnet?',
    explanation: 'Magnet uses two short vowel sounds in its authored chunks.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['magnet-choice'],
    targetVocabulary: ['magnet', 'sunset'],
    soundOutChunks: ['mag', 'net'],
    choices: [
      { id: 'magnet-choice', text: 'magnet' },
      { id: 'photo-choice', text: 'photo' },
      { id: 'robot-choice', text: 'robot' },
      { id: 'music-choice', text: 'music' },
    ],
    correctChoiceIds: ['magnet-choice'],
  }),
  createMultipleChoiceQuestion({
    ...longCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.musicRoom,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-b-2',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointB[1],
    prompt: 'Which word has two long vowels like tulip?',
    explanation: 'Tulip begins with an open syllable that says a long vowel sound.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['tulip-choice'],
    targetVocabulary: ['tulip', 'photo'],
    soundOutChunks: ['tu', 'lip'],
    choices: [
      { id: 'tulip-choice', text: 'tulip' },
      { id: 'sunset-choice', text: 'sunset' },
      { id: 'basket-choice', text: 'basket' },
      { id: 'helmet-choice', text: 'helmet' },
    ],
    correctChoiceIds: ['tulip-choice'],
  }),
  createMultiselectQuestion({
    ...longCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.musicRoom,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-b-3',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointB[2],
    prompt: 'Choose all the long-vowel two-syllable words in these passages.',
    explanation: 'Music, tulip, solo, and photo use long-vowel chunks in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['music-choice', 'tulip-choice', 'solo-choice', 'photo-choice'],
    targetVocabulary: ['music', 'tulip', 'solo', 'photo'],
    soundOutChunks: ['long two-syllable words'],
    choices: [
      { id: 'music-choice', text: 'music' },
      { id: 'tulip-choice', text: 'tulip' },
      { id: 'solo-choice', text: 'solo' },
      { id: 'photo-choice', text: 'photo' },
    ],
    correctChoiceIds: ['music-choice', 'tulip-choice', 'solo-choice', 'photo-choice'],
  }),
  createHotTextQuestion({
    ...longCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.musicRoom,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-b-4',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointB[3],
    prompt: 'Select the sentence that says a photo of the zero sign stayed on the wall.',
    explanation: 'The third sentence gives the photo clue.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['music-room-3'],
    targetVocabulary: ['photo', 'zero', 'wall'],
    soundOutChunks: ['photo'],
    selectableSegments: [
      { id: 'music-room-1', text: 'In the music room, the robot kept a steady beat.' },
      { id: 'music-room-2', text: 'The tulip poster hung near a solo chair.' },
      { id: 'music-room-3', text: 'A photo of the zero sign stayed on the wall.' },
    ],
    correctSegmentIds: ['music-room-3'],
  }),
  createTableMatchQuestion({
    ...longCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.tulipGarden,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-b-5',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointB[4],
    prompt: 'Match each word to its long-vowel chunking.',
    explanation: 'The chunks show the open syllables clearly.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['pilot-pi-lot', 'photo-pho-to'],
    targetVocabulary: ['pilot', 'photo'],
    soundOutChunks: ['long two-syllable words'],
    rows: [
      {
        id: 'pilot-row',
        prompt: 'pilot',
        correctChoiceId: 'pilot-pi-lot',
        options: [
          { id: 'pilot-pi-lot', text: 'pi / lot' },
          { id: 'pilot-rab-bit', text: 'rab / bit' },
          { id: 'pilot-sun-set', text: 'sun / set' },
        ],
      },
      {
        id: 'photo-row',
        prompt: 'photo',
        correctChoiceId: 'photo-pho-to',
        options: [
          { id: 'photo-pho-to', text: 'pho / to' },
          { id: 'photo-mag-net', text: 'mag / net' },
          { id: 'photo-kit-ten', text: 'kit / ten' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...openCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.tulipGarden,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-b-6',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointB[5],
    prompt: 'Which word has an open syllable like solo?',
    explanation: 'Solo begins with an open syllable that says its long vowel sound.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['solo-choice'],
    targetVocabulary: ['solo', 'robot'],
    soundOutChunks: ['open syllable'],
    choices: [
      { id: 'solo-choice', text: 'solo' },
      { id: 'basket-choice', text: 'basket' },
      { id: 'picnic-choice', text: 'picnic' },
      { id: 'helmet-choice', text: 'helmet' },
    ],
    correctChoiceIds: ['solo-choice'],
  }),
  createMultipleChoiceQuestion({
    ...closedCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.tulipGarden,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-b-7',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointB[6],
    prompt: 'Which word has a closed syllable like basket?',
    explanation: 'Basket begins with a closed syllable that ends with a consonant.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['basket-choice'],
    targetVocabulary: ['basket', 'magnet'],
    soundOutChunks: ['closed syllable'],
    choices: [
      { id: 'basket-choice', text: 'basket' },
      { id: 'robot-choice', text: 'robot' },
      { id: 'music-choice', text: 'music' },
      { id: 'photo-choice', text: 'photo' },
    ],
    correctChoiceIds: ['basket-choice'],
  }),
  createMultipleChoiceQuestion({
    ...shortCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.pilotWeatherLog,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-c-1',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointC[0],
    prompt: 'Which word has two short vowels like napkin?',
    explanation: 'Napkin uses two short vowel sounds in its authored chunks.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['napkin-choice'],
    targetVocabulary: ['napkin', 'basket'],
    soundOutChunks: ['nap', 'kin'],
    choices: [
      { id: 'napkin-choice', text: 'napkin' },
      { id: 'photo-choice', text: 'photo' },
      { id: 'robot-choice', text: 'robot' },
      { id: 'solo-choice', text: 'solo' },
    ],
    correctChoiceIds: ['napkin-choice'],
  }),
  createMultipleChoiceQuestion({
    ...longCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.pilotWeatherLog,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-c-2',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointC[1],
    prompt: 'Which word has two long vowels like photo?',
    explanation: 'Photo begins with an open syllable that says its long vowel sound.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['photo-choice'],
    targetVocabulary: ['photo', 'robot'],
    soundOutChunks: ['pho', 'to'],
    choices: [
      { id: 'photo-choice', text: 'photo' },
      { id: 'sunset-choice', text: 'sunset' },
      { id: 'magnet-choice', text: 'magnet' },
      { id: 'kitten-choice', text: 'kitten' },
    ],
    correctChoiceIds: ['photo-choice'],
  }),
  createMultiselectQuestion({
    ...shortCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.photoDisplay,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-c-3',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointC[2],
    prompt: 'Choose all the short-vowel two-syllable words in these passages.',
    explanation: 'Rabbit, napkin, basket, and helmet use short-vowel chunks in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['rabbit-choice', 'napkin-choice', 'basket-choice', 'helmet-choice'],
    targetVocabulary: ['rabbit', 'napkin', 'basket', 'helmet'],
    soundOutChunks: ['short two-syllable words'],
    choices: [
      { id: 'rabbit-choice', text: 'rabbit' },
      { id: 'napkin-choice', text: 'napkin' },
      { id: 'basket-choice', text: 'basket' },
      { id: 'helmet-choice', text: 'helmet' },
    ],
    correctChoiceIds: ['rabbit-choice', 'napkin-choice', 'basket-choice', 'helmet-choice'],
  }),
  createHotTextQuestion({
    ...longCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.photoDisplay,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-c-4',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointC[3],
    prompt: 'Select the sentence that says the photo display opened beside the music room.',
    explanation: 'The first sentence gives the photo display clue.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['photo-display-1'],
    targetVocabulary: ['photo', 'music', 'display'],
    soundOutChunks: ['photo'],
    selectableSegments: [
      { id: 'photo-display-1', text: 'The photo display opened beside the music room.' },
      { id: 'photo-display-2', text: 'A robot and a tulip shared the stage.' },
      { id: 'photo-display-3', text: 'The rabbit and the basket stayed by the wall.' },
    ],
    correctSegmentIds: ['photo-display-1'],
  }),
  createTableMatchQuestion({
    ...longCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.photoDisplay,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-c-5',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointC[4],
    prompt: 'Match each word to its long-vowel chunking.',
    explanation: 'The chunks show the open syllables clearly.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['photo-pho-to', 'robot-ro-bot'],
    targetVocabulary: ['photo', 'robot'],
    soundOutChunks: ['long two-syllable words'],
    rows: [
      {
        id: 'photo-row',
        prompt: 'photo',
        correctChoiceId: 'photo-pho-to',
        options: [
          { id: 'photo-pho-to', text: 'pho / to' },
          { id: 'photo-rab-bit', text: 'rab / bit' },
          { id: 'photo-mag-net', text: 'mag / net' },
        ],
      },
      {
        id: 'robot-row',
        prompt: 'robot',
        correctChoiceId: 'robot-ro-bot',
        options: [
          { id: 'robot-ro-bot', text: 'ro / bot' },
          { id: 'robot-pic-nic', text: 'pic / nic' },
          { id: 'robot-sun-set', text: 'sun / set' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...openCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.photoDisplay,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-c-6',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointC[5],
    prompt: 'Which word has an open syllable like robot?',
    explanation: 'Robot begins with an open syllable that says its long vowel sound.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['robot-choice'],
    targetVocabulary: ['robot', 'solo'],
    soundOutChunks: ['open syllable'],
    choices: [
      { id: 'robot-choice', text: 'robot' },
      { id: 'basket-choice', text: 'basket' },
      { id: 'kitten-choice', text: 'kitten' },
      { id: 'napkin-choice', text: 'napkin' },
    ],
    correctChoiceIds: ['robot-choice'],
  }),
  createMultipleChoiceQuestion({
    ...closedCommon,
    difficulty: 3,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.photoDisplay,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-syllable-summit-checkpoint-c-7',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.checkpointC[6],
    prompt: 'Which word has a closed syllable like helmet?',
    explanation: 'Helmet begins with a closed syllable that ends with a consonant.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['helmet-choice'],
    targetVocabulary: ['helmet', 'rabbit'],
    soundOutChunks: ['closed syllable'],
    choices: [
      { id: 'helmet-choice', text: 'helmet' },
      { id: 'robot-choice', text: 'robot' },
      { id: 'photo-choice', text: 'photo' },
      { id: 'solo-choice', text: 'solo' },
    ],
    correctChoiceIds: ['helmet-choice'],
  }),
]
