import { createHotTextQuestion, createMultipleChoiceQuestion, createMultiselectQuestion, createTableMatchQuestion } from '../variableVowelsOoEa/questionFactories'
import { TWO_SYLLABLE_OPEN_CLOSED_CONTENT_VERSION, TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS, TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS, TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS } from './ids'

const closedCommon = {
  benchmarkReference: 'ELA.2.F.1.3c',
  skillIdentifier: 'g2-word-forge-word-practice',
  prerequisiteSkillIdentifiers: [],
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'word-lab',
  estimatedReadingLevel: 'grade-2-bridge',
  reviewStatus: 'DRAFT' as const,
  contentVersion: TWO_SYLLABLE_OPEN_CLOSED_CONTENT_VERSION,
  tags: ['grade-2', 'bridge', 'word-forge', 'closed-syllable', 'building-block'],
}

const openCommon = {
  benchmarkReference: 'ELA.2.F.1.3c',
  skillIdentifier: 'g2-word-forge-word-practice',
  prerequisiteSkillIdentifiers: [],
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'word-lab',
  estimatedReadingLevel: 'grade-2-bridge',
  reviewStatus: 'DRAFT' as const,
  contentVersion: TWO_SYLLABLE_OPEN_CLOSED_CONTENT_VERSION,
  tags: ['grade-2', 'bridge', 'word-forge', 'open-syllable', 'building-block'],
}

export const buildingBlockQuestions = [
  createMultipleChoiceQuestion({
    ...closedCommon,
    difficulty: 2,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.rabbitHabitat,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedClosed,
    activityIdentifier: 'activity-word-forge-syllable-summit-building-block-closed-1',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedClosed[0],
    prompt: 'Which word has a closed first syllable like rabbit?',
    explanation: 'Rabbit has a closed first syllable with a short vowel sound.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['rabbit-choice'],
    targetVocabulary: ['rabbit', 'kitten'],
    soundOutChunks: ['rab', 'bit'],
    choices: [
      { id: 'rabbit-choice', text: 'rabbit' },
      { id: 'robot-choice', text: 'robot' },
      { id: 'music-choice', text: 'music' },
      { id: 'photo-choice', text: 'photo' },
    ],
    correctChoiceIds: ['rabbit-choice'],
  }),
  createMultipleChoiceQuestion({
    ...closedCommon,
    difficulty: 2,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.rabbitHabitat,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedClosed,
    activityIdentifier: 'activity-word-forge-syllable-summit-building-block-closed-2',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedClosed[1],
    prompt: 'Which word has a closed first syllable like picnic?',
    explanation: 'Picnic begins with a closed syllable that uses a short vowel sound.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['picnic-choice'],
    targetVocabulary: ['picnic', 'basket'],
    soundOutChunks: ['pic', 'nic'],
    choices: [
      { id: 'picnic-choice', text: 'picnic' },
      { id: 'robot-choice', text: 'robot' },
      { id: 'music-choice', text: 'music' },
      { id: 'solo-choice', text: 'solo' },
    ],
    correctChoiceIds: ['picnic-choice'],
  }),
  createMultiselectQuestion({
    ...closedCommon,
    difficulty: 2,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.rabbitHabitat,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedClosed,
    activityIdentifier: 'activity-word-forge-syllable-summit-building-block-closed-3',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedClosed[2],
    prompt: 'Choose all the closed-syllable words from the rabbit passage.',
    explanation: 'Rabbit and basket both have a consonant after the first vowel in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['rabbit-choice', 'basket-choice'],
    targetVocabulary: ['rabbit', 'basket'],
    soundOutChunks: ['closed syllables'],
    choices: [
      { id: 'rabbit-choice', text: 'rabbit' },
      { id: 'basket-choice', text: 'basket' },
      { id: 'robot-choice', text: 'robot' },
      { id: 'music-choice', text: 'music' },
    ],
    correctChoiceIds: ['rabbit-choice', 'basket-choice'],
  }),
  createHotTextQuestion({
    ...closedCommon,
    difficulty: 2,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.rabbitHabitat,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedClosed,
    activityIdentifier: 'activity-word-forge-syllable-summit-building-block-closed-4',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedClosed[3],
    prompt: 'Select the sentence that gives a closed-syllable clue with rabbit and napkin.',
    explanation: 'The second sentence includes both rabbit-path words with closed syllables.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['rabbit-habitat-2'],
    targetVocabulary: ['rabbit', 'napkin'],
    soundOutChunks: ['closed syllables'],
    selectableSegments: [
      { id: 'rabbit-habitat-1', text: 'The rabbit sat in a basket near the cabin.' },
      { id: 'rabbit-habitat-2', text: 'A kitten slept on a napkin by the window.' },
      { id: 'rabbit-habitat-3', text: 'Mia checked a magnet and a helmet before lunch.' },
    ],
    correctSegmentIds: ['rabbit-habitat-2'],
  }),
  createTableMatchQuestion({
    ...closedCommon,
    difficulty: 2,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.rabbitHabitat,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedClosed,
    activityIdentifier: 'activity-word-forge-syllable-summit-building-block-closed-5',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedClosed[4],
    prompt: 'Match each word to its closed-syllable chunks.',
    explanation: 'The chunks show the consonant closing the vowel sound.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['rabbit-rab-bit', 'basket-bas-ket'],
    targetVocabulary: ['rabbit', 'basket'],
    soundOutChunks: ['closed syllables'],
    rows: [
      {
        id: 'rabbit-row',
        prompt: 'rabbit',
        correctChoiceId: 'rabbit-rab-bit',
        options: [
          { id: 'rabbit-rab-bit', text: 'rab / bit' },
          { id: 'rabbit-ro-bot', text: 'ro / bot' },
          { id: 'rabbit-mu-sic', text: 'mu / sic' },
        ],
      },
      {
        id: 'basket-row',
        prompt: 'basket',
        correctChoiceId: 'basket-bas-ket',
        options: [
          { id: 'basket-bas-ket', text: 'bas / ket' },
          { id: 'basket-pho-to', text: 'pho / to' },
          { id: 'basket-tu-lip', text: 'tu / lip' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...openCommon,
    difficulty: 2,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.robotExhibit,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedOpen,
    activityIdentifier: 'activity-word-forge-syllable-summit-building-block-open-1',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedOpen[0],
    prompt: 'Which word has an open first syllable like robot?',
    explanation: 'Robot begins with an open syllable, so the first vowel says its long sound.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['robot-choice'],
    targetVocabulary: ['robot', 'photo'],
    soundOutChunks: ['ro', 'bot'],
    choices: [
      { id: 'robot-choice', text: 'robot' },
      { id: 'rabbit-choice', text: 'rabbit' },
      { id: 'picnic-choice', text: 'picnic' },
      { id: 'basket-choice', text: 'basket' },
    ],
    correctChoiceIds: ['robot-choice'],
  }),
  createMultipleChoiceQuestion({
    ...openCommon,
    difficulty: 2,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.robotExhibit,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedOpen,
    activityIdentifier: 'activity-word-forge-syllable-summit-building-block-open-2',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedOpen[1],
    prompt: 'Which word has an open first syllable like music?',
    explanation: 'Music starts with an open syllable and a long vowel sound.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['music-choice'],
    targetVocabulary: ['music', 'zero'],
    soundOutChunks: ['mu', 'sic'],
    choices: [
      { id: 'music-choice', text: 'music' },
      { id: 'sunset-choice', text: 'sunset' },
      { id: 'napkin-choice', text: 'napkin' },
      { id: 'helmet-choice', text: 'helmet' },
    ],
    correctChoiceIds: ['music-choice'],
  }),
  createMultiselectQuestion({
    ...openCommon,
    difficulty: 2,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.robotExhibit,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedOpen,
    activityIdentifier: 'activity-word-forge-syllable-summit-building-block-open-3',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedOpen[2],
    prompt: 'Choose all the open-syllable words from the robot passage.',
    explanation: 'Robot, music, pilot, and zero all begin with open syllables in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['robot-choice', 'music-choice', 'pilot-choice', 'zero-choice'],
    targetVocabulary: ['robot', 'music', 'pilot', 'zero'],
    soundOutChunks: ['open syllables'],
    choices: [
      { id: 'robot-choice', text: 'robot' },
      { id: 'music-choice', text: 'music' },
      { id: 'pilot-choice', text: 'pilot' },
      { id: 'zero-choice', text: 'zero' },
    ],
    correctChoiceIds: ['robot-choice', 'music-choice', 'pilot-choice', 'zero-choice'],
  }),
  createHotTextQuestion({
    ...openCommon,
    difficulty: 2,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.robotExhibit,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedOpen,
    activityIdentifier: 'activity-word-forge-syllable-summit-building-block-open-4',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedOpen[3],
    prompt: 'Select the sentence that gives an open-syllable clue with robot and music.',
    explanation: 'The second sentence gives the open-syllable words robot and music.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['robot-exhibit-2'],
    targetVocabulary: ['robot', 'music'],
    soundOutChunks: ['open syllables'],
    selectableSegments: [
      { id: 'robot-exhibit-1', text: 'The robot stood on an open stage at the exhibit.' },
      { id: 'robot-exhibit-2', text: 'A pilot played music while the model spun.' },
      { id: 'robot-exhibit-3', text: 'The photo card showed a zero beside a solar unit.' },
    ],
    correctSegmentIds: ['robot-exhibit-2'],
  }),
  createTableMatchQuestion({
    ...openCommon,
    difficulty: 2,
    passageIdentifier: TWO_SYLLABLE_OPEN_CLOSED_PASSAGE_IDS.robotExhibit,
    lessonIdentifier: TWO_SYLLABLE_OPEN_CLOSED_LESSON_IDS.guidedOpen,
    activityIdentifier: 'activity-word-forge-syllable-summit-building-block-open-5',
    questionIdentifier: TWO_SYLLABLE_OPEN_CLOSED_QUESTION_IDS.guidedOpen[4],
    prompt: 'Match each word to its open-syllable chunks.',
    explanation: 'The chunks show the long first syllable clearly.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['robot-ro-bot', 'music-mu-sic'],
    targetVocabulary: ['robot', 'music'],
    soundOutChunks: ['open syllables'],
    rows: [
      {
        id: 'robot-row',
        prompt: 'robot',
        correctChoiceId: 'robot-ro-bot',
        options: [
          { id: 'robot-ro-bot', text: 'ro / bot' },
          { id: 'robot-rab-bit', text: 'rab / bit' },
          { id: 'robot-pic-nic', text: 'pic / nic' },
        ],
      },
      {
        id: 'music-row',
        prompt: 'music',
        correctChoiceId: 'music-mu-sic',
        options: [
          { id: 'music-mu-sic', text: 'mu / sic' },
          { id: 'music-sun-set', text: 'sun / set' },
          { id: 'music-bas-ket', text: 'bas / ket' },
        ],
      },
    ],
  }),
]
