import type { Passage, WordSupportChunk, WordSupportPart, WordSupportTarget } from '../../../../types'
import { CONSONANT_LE_CONTENT_VERSION, CONSONANT_LE_PASSAGE_IDS } from './ids'

const draftStatus = 'DRAFT' as const

function sentence(sentenceId: string, text: string) {
  return { sentenceId, text }
}

function chunk(displayText: string, speechText: string = displayText): WordSupportChunk {
  return { displayText, speechText }
}

function part(text: string, emphasis = false): WordSupportPart {
  return { text, emphasis }
}

function supportTarget(spec: {
  targetId: string
  passageId: string
  sentenceId: string
  surfaceWord: string
  focusParts: WordSupportPart[]
  displayChunks: WordSupportChunk[]
  spokenChunks: WordSupportChunk[]
  blendSpeechText: string
  wholeWordSpeechText: string
  sentenceSpeechText: string
}): WordSupportTarget {
  return {
    ...spec,
    reviewStatus: draftStatus,
    contentVersion: CONSONANT_LE_CONTENT_VERSION,
  }
}

export const grade2WordForgeConsonantLePassages: Passage[] = [
  {
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.orchardTable,
    gradeBand: 2,
    passageText: [
      'At the orchard, the apple cart sat beside a table.',
      'A maple leaf rested near a candle box.',
      'The farmer tied a cable to the sign.',
      'A little child carried a bundle of fruit.',
    ].join(' '),
    sentences: [
      sentence('orchard-table-1', 'At the orchard, the apple cart sat beside a table.'),
      sentence('orchard-table-2', 'A maple leaf rested near a candle box.'),
      sentence('orchard-table-3', 'The farmer tied a cable to the sign.'),
      sentence('orchard-table-4', 'A little child carried a bundle of fruit.'),
    ],
    readingContext: 'Word Forge Trail 4 practice about an orchard stand and a display table.',
    contentVersion: CONSONANT_LE_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-1-apple',
        passageId: CONSONANT_LE_PASSAGE_IDS.orchardTable,
        sentenceId: 'orchard-table-1',
        surfaceWord: 'apple',
        focusParts: [part('ap'), part('ple', true)],
        displayChunks: [chunk('ap'), chunk('ple')],
        spokenChunks: [chunk('ap'), chunk('ple')],
        blendSpeechText: 'apple',
        wholeWordSpeechText: 'apple',
        sentenceSpeechText: 'At the orchard, the apple cart sat beside a table.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-1-table',
        passageId: CONSONANT_LE_PASSAGE_IDS.orchardTable,
        sentenceId: 'orchard-table-1',
        surfaceWord: 'table',
        focusParts: [part('ta'), part('ble', true)],
        displayChunks: [chunk('ta'), chunk('ble')],
        spokenChunks: [chunk('ta'), chunk('ble')],
        blendSpeechText: 'table',
        wholeWordSpeechText: 'table',
        sentenceSpeechText: 'At the orchard, the apple cart sat beside a table.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-1-maple',
        passageId: CONSONANT_LE_PASSAGE_IDS.orchardTable,
        sentenceId: 'orchard-table-2',
        surfaceWord: 'maple',
        focusParts: [part('ma'), part('ple', true)],
        displayChunks: [chunk('ma'), chunk('ple')],
        spokenChunks: [chunk('ma'), chunk('ple')],
        blendSpeechText: 'maple',
        wholeWordSpeechText: 'maple',
        sentenceSpeechText: 'A maple leaf rested near a candle box.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-1-cable',
        passageId: CONSONANT_LE_PASSAGE_IDS.orchardTable,
        sentenceId: 'orchard-table-3',
        surfaceWord: 'cable',
        focusParts: [part('ca'), part('ble', true)],
        displayChunks: [chunk('ca'), chunk('ble')],
        spokenChunks: [chunk('ca'), chunk('ble')],
        blendSpeechText: 'cable',
        wholeWordSpeechText: 'cable',
        sentenceSpeechText: 'The farmer tied a cable to the sign.',
      }),
    ],
  },
  {
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.candleDemo,
    gradeBand: 2,
    passageText: [
      'At the safety demo, a candle sat on a stable table.',
      'A little helper watched the flame.',
      'The bundle of rules stayed near the candle.',
      'The simple sign told each step.',
    ].join(' '),
    sentences: [
      sentence('candle-demo-1', 'At the safety demo, a candle sat on a stable table.'),
      sentence('candle-demo-2', 'A little helper watched the flame.'),
      sentence('candle-demo-3', 'The bundle of rules stayed near the candle.'),
      sentence('candle-demo-4', 'The simple sign told each step.'),
    ],
    readingContext: 'Word Forge Trail 4 practice about careful class safety at a science table.',
    contentVersion: CONSONANT_LE_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-2-candle',
        passageId: CONSONANT_LE_PASSAGE_IDS.candleDemo,
        sentenceId: 'candle-demo-1',
        surfaceWord: 'candle',
        focusParts: [part('can'), part('dle', true)],
        displayChunks: [chunk('can'), chunk('dle')],
        spokenChunks: [chunk('can'), chunk('dle')],
        blendSpeechText: 'candle',
        wholeWordSpeechText: 'candle',
        sentenceSpeechText: 'At the safety demo, a candle sat on a stable table.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-2-stable',
        passageId: CONSONANT_LE_PASSAGE_IDS.candleDemo,
        sentenceId: 'candle-demo-1',
        surfaceWord: 'stable',
        focusParts: [part('sta'), part('ble', true)],
        displayChunks: [chunk('sta'), chunk('ble')],
        spokenChunks: [chunk('sta'), chunk('ble')],
        blendSpeechText: 'stable',
        wholeWordSpeechText: 'stable',
        sentenceSpeechText: 'At the safety demo, a candle sat on a stable table.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-2-little',
        passageId: CONSONANT_LE_PASSAGE_IDS.candleDemo,
        sentenceId: 'candle-demo-2',
        surfaceWord: 'little',
        focusParts: [part('lit'), part('tle', true)],
        displayChunks: [chunk('lit'), chunk('tle')],
        spokenChunks: [chunk('lit'), chunk('tle')],
        blendSpeechText: 'little',
        wholeWordSpeechText: 'little',
        sentenceSpeechText: 'A little helper watched the flame.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-2-simple',
        passageId: CONSONANT_LE_PASSAGE_IDS.candleDemo,
        sentenceId: 'candle-demo-4',
        surfaceWord: 'simple',
        focusParts: [part('sim'), part('ple', true)],
        displayChunks: [chunk('sim'), chunk('ple')],
        spokenChunks: [chunk('sim'), chunk('ple')],
        blendSpeechText: 'simple',
        wholeWordSpeechText: 'simple',
        sentenceSpeechText: 'The simple sign told each step.',
      }),
    ],
  },
  {
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.puzzleClub,
    gradeBand: 2,
    passageText: [
      'The puzzle club built a simple model.',
      'They placed a bottle on a rattle tray.',
      'A pebble held the corner of the note.',
      'The sample card told each step.',
    ].join(' '),
    sentences: [
      sentence('puzzle-club-1', 'The puzzle club built a simple model.'),
      sentence('puzzle-club-2', 'They placed a bottle on a rattle tray.'),
      sentence('puzzle-club-3', 'A pebble held the corner of the note.'),
      sentence('puzzle-club-4', 'The sample card told each step.'),
    ],
    readingContext: 'Word Forge Trail 4 practice about a club project with small model parts.',
    contentVersion: CONSONANT_LE_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-3-puzzle',
        passageId: CONSONANT_LE_PASSAGE_IDS.puzzleClub,
        sentenceId: 'puzzle-club-1',
        surfaceWord: 'puzzle',
        focusParts: [part('puz'), part('zle', true)],
        displayChunks: [chunk('puz'), chunk('zle')],
        spokenChunks: [chunk('puz'), chunk('zle')],
        blendSpeechText: 'puzzle',
        wholeWordSpeechText: 'puzzle',
        sentenceSpeechText: 'The puzzle club built a simple model.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-3-simple',
        passageId: CONSONANT_LE_PASSAGE_IDS.puzzleClub,
        sentenceId: 'puzzle-club-1',
        surfaceWord: 'simple',
        focusParts: [part('sim'), part('ple', true)],
        displayChunks: [chunk('sim'), chunk('ple')],
        spokenChunks: [chunk('sim'), chunk('ple')],
        blendSpeechText: 'simple',
        wholeWordSpeechText: 'simple',
        sentenceSpeechText: 'The puzzle club built a simple model.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-3-bottle',
        passageId: CONSONANT_LE_PASSAGE_IDS.puzzleClub,
        sentenceId: 'puzzle-club-2',
        surfaceWord: 'bottle',
        focusParts: [part('bot'), part('tle', true)],
        displayChunks: [chunk('bot'), chunk('tle')],
        spokenChunks: [chunk('bot'), chunk('tle')],
        blendSpeechText: 'bottle',
        wholeWordSpeechText: 'bottle',
        sentenceSpeechText: 'They placed a bottle on a rattle tray.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-3-sample',
        passageId: CONSONANT_LE_PASSAGE_IDS.puzzleClub,
        sentenceId: 'puzzle-club-4',
        surfaceWord: 'sample',
        focusParts: [part('sam'), part('ple', true)],
        displayChunks: [chunk('sam'), chunk('ple')],
        spokenChunks: [chunk('sam'), chunk('ple')],
        blendSpeechText: 'sample',
        wholeWordSpeechText: 'sample',
        sentenceSpeechText: 'The sample card told each step.',
      }),
    ],
  },
  {
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.machineExhibit,
    gradeBand: 2,
    passageText: [
      'The machine exhibit showed a title card and a handle.',
      'A bubble tube spun beside a stable wheel.',
      'The noble guide nodded at the model.',
      'A bundle of parts rested by the table.',
    ].join(' '),
    sentences: [
      sentence('machine-exhibit-1', 'The machine exhibit showed a title card and a handle.'),
      sentence('machine-exhibit-2', 'A bubble tube spun beside a stable wheel.'),
      sentence('machine-exhibit-3', 'The noble guide nodded at the model.'),
      sentence('machine-exhibit-4', 'A bundle of parts rested by the table.'),
    ],
    readingContext: 'Word Forge Trail 4 practice about a class exhibit with moving parts and labels.',
    contentVersion: CONSONANT_LE_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-4-title',
        passageId: CONSONANT_LE_PASSAGE_IDS.machineExhibit,
        sentenceId: 'machine-exhibit-1',
        surfaceWord: 'title',
        focusParts: [part('ti'), part('tle', true)],
        displayChunks: [chunk('ti'), chunk('tle')],
        spokenChunks: [chunk('ti'), chunk('tle')],
        blendSpeechText: 'title',
        wholeWordSpeechText: 'title',
        sentenceSpeechText: 'The machine exhibit showed a title card and a handle.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-4-handle',
        passageId: CONSONANT_LE_PASSAGE_IDS.machineExhibit,
        sentenceId: 'machine-exhibit-1',
        surfaceWord: 'handle',
        focusParts: [part('han'), part('dle', true)],
        displayChunks: [chunk('han'), chunk('dle')],
        spokenChunks: [chunk('han'), chunk('dle')],
        blendSpeechText: 'handle',
        wholeWordSpeechText: 'handle',
        sentenceSpeechText: 'The machine exhibit showed a title card and a handle.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-4-bubble',
        passageId: CONSONANT_LE_PASSAGE_IDS.machineExhibit,
        sentenceId: 'machine-exhibit-2',
        surfaceWord: 'bubble',
        focusParts: [part('bub'), part('ble', true)],
        displayChunks: [chunk('bub'), chunk('ble')],
        spokenChunks: [chunk('bub'), chunk('ble')],
        blendSpeechText: 'bubble',
        wholeWordSpeechText: 'bubble',
        sentenceSpeechText: 'A bubble tube spun beside a stable wheel.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-4-noble',
        passageId: CONSONANT_LE_PASSAGE_IDS.machineExhibit,
        sentenceId: 'machine-exhibit-3',
        surfaceWord: 'noble',
        focusParts: [part('no'), part('ble', true)],
        displayChunks: [chunk('no'), chunk('ble')],
        spokenChunks: [chunk('no'), chunk('ble')],
        blendSpeechText: 'noble',
        wholeWordSpeechText: 'noble',
        sentenceSpeechText: 'The noble guide nodded at the model.',
      }),
    ],
  },
  {
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.jungleHabitat,
    gradeBand: 2,
    passageText: [
      'The jungle habitat model stood on a table.',
      'A dimple card marked each animal home.',
      'The little monkey crossed a stable bridge.',
      'A candle lantern glowed near the bundle.',
    ].join(' '),
    sentences: [
      sentence('jungle-habitat-1', 'The jungle habitat model stood on a table.'),
      sentence('jungle-habitat-2', 'A dimple card marked each animal home.'),
      sentence('jungle-habitat-3', 'The little monkey crossed a stable bridge.'),
      sentence('jungle-habitat-4', 'A candle lantern glowed near the bundle.'),
    ],
    readingContext: 'Word Forge Trail 4 practice about a classroom habitat model and sturdy pieces.',
    contentVersion: CONSONANT_LE_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-5-jungle',
        passageId: CONSONANT_LE_PASSAGE_IDS.jungleHabitat,
        sentenceId: 'jungle-habitat-1',
        surfaceWord: 'jungle',
        focusParts: [part('jun'), part('gle', true)],
        displayChunks: [chunk('jun'), chunk('gle')],
        spokenChunks: [chunk('jun'), chunk('gle')],
        blendSpeechText: 'jungle',
        wholeWordSpeechText: 'jungle',
        sentenceSpeechText: 'The jungle habitat model stood on a table.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-5-dimple',
        passageId: CONSONANT_LE_PASSAGE_IDS.jungleHabitat,
        sentenceId: 'jungle-habitat-2',
        surfaceWord: 'dimple',
        focusParts: [part('dim'), part('ple', true)],
        displayChunks: [chunk('dim'), chunk('ple')],
        spokenChunks: [chunk('dim'), chunk('ple')],
        blendSpeechText: 'dimple',
        wholeWordSpeechText: 'dimple',
        sentenceSpeechText: 'A dimple card marked each animal home.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-5-stable',
        passageId: CONSONANT_LE_PASSAGE_IDS.jungleHabitat,
        sentenceId: 'jungle-habitat-3',
        surfaceWord: 'stable',
        focusParts: [part('sta'), part('ble', true)],
        displayChunks: [chunk('sta'), chunk('ble')],
        spokenChunks: [chunk('sta'), chunk('ble')],
        blendSpeechText: 'stable',
        wholeWordSpeechText: 'stable',
        sentenceSpeechText: 'The little monkey crossed a stable bridge.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-5-bundle',
        passageId: CONSONANT_LE_PASSAGE_IDS.jungleHabitat,
        sentenceId: 'jungle-habitat-4',
        surfaceWord: 'bundle',
        focusParts: [part('bun'), part('dle', true)],
        displayChunks: [chunk('bun'), chunk('dle')],
        spokenChunks: [chunk('bun'), chunk('dle')],
        blendSpeechText: 'bundle',
        wholeWordSpeechText: 'bundle',
        sentenceSpeechText: 'A candle lantern glowed near the bundle.',
      }),
    ],
  },
  {
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.bottleRecycling,
    gradeBand: 2,
    passageText: [
      'At the recycling bin, children stacked a bottle, a pebble, and a bundle.',
      'A candle label showed the safe rule.',
      'The apple sticker sat on a table.',
      'The handle moved the lid.',
    ].join(' '),
    sentences: [
      sentence('bottle-recycling-1', 'At the recycling bin, children stacked a bottle, a pebble, and a bundle.'),
      sentence('bottle-recycling-2', 'A candle label showed the safe rule.'),
      sentence('bottle-recycling-3', 'The apple sticker sat on a table.'),
      sentence('bottle-recycling-4', 'The handle moved the lid.'),
    ],
    readingContext: 'Word Forge Trail 4 practice about recycling and safe classroom habits.',
    contentVersion: CONSONANT_LE_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-6-bottle',
        passageId: CONSONANT_LE_PASSAGE_IDS.bottleRecycling,
        sentenceId: 'bottle-recycling-1',
        surfaceWord: 'bottle',
        focusParts: [part('bot'), part('tle', true)],
        displayChunks: [chunk('bot'), chunk('tle')],
        spokenChunks: [chunk('bot'), chunk('tle')],
        blendSpeechText: 'bottle',
        wholeWordSpeechText: 'bottle',
        sentenceSpeechText: 'At the recycling bin, children stacked a bottle, a pebble, and a bundle.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-6-pebble',
        passageId: CONSONANT_LE_PASSAGE_IDS.bottleRecycling,
        sentenceId: 'bottle-recycling-1',
        surfaceWord: 'pebble',
        focusParts: [part('peb'), part('ble', true)],
        displayChunks: [chunk('peb'), chunk('ble')],
        spokenChunks: [chunk('peb'), chunk('ble')],
        blendSpeechText: 'pebble',
        wholeWordSpeechText: 'pebble',
        sentenceSpeechText: 'At the recycling bin, children stacked a bottle, a pebble, and a bundle.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-6-candle',
        passageId: CONSONANT_LE_PASSAGE_IDS.bottleRecycling,
        sentenceId: 'bottle-recycling-2',
        surfaceWord: 'candle',
        focusParts: [part('can'), part('dle', true)],
        displayChunks: [chunk('can'), chunk('dle')],
        spokenChunks: [chunk('can'), chunk('dle')],
        blendSpeechText: 'candle',
        wholeWordSpeechText: 'candle',
        sentenceSpeechText: 'A candle label showed the safe rule.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-6-apple',
        passageId: CONSONANT_LE_PASSAGE_IDS.bottleRecycling,
        sentenceId: 'bottle-recycling-3',
        surfaceWord: 'apple',
        focusParts: [part('ap'), part('ple', true)],
        displayChunks: [chunk('ap'), chunk('ple')],
        spokenChunks: [chunk('ap'), chunk('ple')],
        blendSpeechText: 'apple',
        wholeWordSpeechText: 'apple',
        sentenceSpeechText: 'The apple sticker sat on a table.',
      }),
    ],
  },
  {
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.bubbleScience,
    gradeBand: 2,
    passageText: [
      'The bubble jar sat on a table.',
      'A maple leaf floated near the water.',
      'The rattle fan shook a little.',
      'The helper used a cable to hold the tube.',
    ].join(' '),
    sentences: [
      sentence('bubble-science-1', 'The bubble jar sat on a table.'),
      sentence('bubble-science-2', 'A maple leaf floated near the water.'),
      sentence('bubble-science-3', 'The rattle fan shook a little.'),
      sentence('bubble-science-4', 'The helper used a cable to hold the tube.'),
    ],
    readingContext: 'Word Forge Trail 4 practice about bubbles, a jar, and a careful test setup.',
    contentVersion: CONSONANT_LE_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-7-bubble',
        passageId: CONSONANT_LE_PASSAGE_IDS.bubbleScience,
        sentenceId: 'bubble-science-1',
        surfaceWord: 'bubble',
        focusParts: [part('bub'), part('ble', true)],
        displayChunks: [chunk('bub'), chunk('ble')],
        spokenChunks: [chunk('bub'), chunk('ble')],
        blendSpeechText: 'bubble',
        wholeWordSpeechText: 'bubble',
        sentenceSpeechText: 'The bubble jar sat on a table.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-7-table',
        passageId: CONSONANT_LE_PASSAGE_IDS.bubbleScience,
        sentenceId: 'bubble-science-1',
        surfaceWord: 'table',
        focusParts: [part('ta'), part('ble', true)],
        displayChunks: [chunk('ta'), chunk('ble')],
        spokenChunks: [chunk('ta'), chunk('ble')],
        blendSpeechText: 'table',
        wholeWordSpeechText: 'table',
        sentenceSpeechText: 'The bubble jar sat on a table.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-7-maple',
        passageId: CONSONANT_LE_PASSAGE_IDS.bubbleScience,
        sentenceId: 'bubble-science-2',
        surfaceWord: 'maple',
        focusParts: [part('ma'), part('ple', true)],
        displayChunks: [chunk('ma'), chunk('ple')],
        spokenChunks: [chunk('ma'), chunk('ple')],
        blendSpeechText: 'maple',
        wholeWordSpeechText: 'maple',
        sentenceSpeechText: 'A maple leaf floated near the water.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-consonant-le-7-rattle',
        passageId: CONSONANT_LE_PASSAGE_IDS.bubbleScience,
        sentenceId: 'bubble-science-3',
        surfaceWord: 'rattle',
        focusParts: [part('rat'), part('tle', true)],
        displayChunks: [chunk('rat'), chunk('tle')],
        spokenChunks: [chunk('rat'), chunk('tle')],
        blendSpeechText: 'rattle',
        wholeWordSpeechText: 'rattle',
        sentenceSpeechText: 'The rattle fan shook a little.',
      }),
    ],
  },
]
