import type { ReadingQuestion } from '../../../../types'
import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from '../variableVowelsOoEa/questionFactories'
import {
  CONSONANT_LE_CONTENT_VERSION,
  CONSONANT_LE_LESSON_IDS,
  CONSONANT_LE_PASSAGE_IDS,
  CONSONANT_LE_QUESTION_IDS,
} from './ids'

const common = {
  benchmarkReference: 'ELA.2.F.1.3c',
  skillIdentifier: 'g2-word-forge-word-practice',
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'Word Forge',
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2',
  contentVersion: CONSONANT_LE_CONTENT_VERSION,
  reviewStatus: 'DRAFT' as const,
}

export const guidedQuestions: ReadingQuestion[] = [
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.machineExhibit,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedConsonantLePractice,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-practice-1',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedConsonantLePractice[0],
    prompt: 'Which word splits as ti | tle?',
    explanation: 'Title has ti | tle, so the first syllable is open.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['title-choice'],
    targetVocabulary: ['title', 'handle', 'bubble', 'noble'],
    soundOutChunks: ['ti', 'tle'],
    tags: ['consonant-le', 'open-syllable'],
    choices: [
      { id: 'handle-choice', text: 'handle' },
      { id: 'bubble-choice', text: 'bubble' },
      { id: 'noble-choice', text: 'noble' },
      { id: 'title-choice', text: 'title' },
    ],
    correctChoiceIds: ['title-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.machineExhibit,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedConsonantLePractice,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-practice-2',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedConsonantLePractice[1],
    prompt: 'Which word splits as han | dle?',
    explanation: 'Handle has han | dle, so the first syllable is closed.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['handle-choice'],
    targetVocabulary: ['title', 'handle', 'bubble', 'noble'],
    soundOutChunks: ['han', 'dle'],
    tags: ['consonant-le', 'closed-syllable'],
    choices: [
      { id: 'title-choice', text: 'title' },
      { id: 'bubble-choice', text: 'bubble' },
      { id: 'noble-choice', text: 'noble' },
      { id: 'handle-choice', text: 'handle' },
    ],
    correctChoiceIds: ['handle-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.machineExhibit,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedConsonantLePractice,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-practice-3',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedConsonantLePractice[2],
    prompt: 'Choose all the words in the exhibit passage that end with consonant-le.',
    explanation: 'Title, handle, bubble, and noble all end with consonant-le chunks.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['title-choice', 'handle-choice', 'bubble-choice', 'noble-choice'],
    targetVocabulary: ['title', 'handle', 'bubble', 'noble'],
    soundOutChunks: ['ti', 'tle', 'han', 'dle', 'bub', 'ble', 'no', 'ble'],
    tags: ['consonant-le', 'open-syllable', 'closed-syllable'],
    choices: [
      { id: 'title-choice', text: 'title' },
      { id: 'handle-choice', text: 'handle' },
      { id: 'bubble-choice', text: 'bubble' },
      { id: 'noble-choice', text: 'noble' },
    ],
    correctChoiceIds: ['title-choice', 'handle-choice', 'bubble-choice', 'noble-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.machineExhibit,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedConsonantLePractice,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-practice-4',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedConsonantLePractice[3],
    prompt: 'Select the sentence that mentions a bubble tube and a stable wheel.',
    explanation: 'The second sentence gives the clue about the bubble tube and the stable wheel.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['machine-exhibit-2'],
    targetVocabulary: ['bubble', 'stable'],
    soundOutChunks: ['bub', 'ble'],
    tags: ['consonant-le', 'open-syllable', 'closed-syllable'],
    selectableSegments: [
      { id: 'machine-exhibit-1', text: 'The machine exhibit showed a title card and a handle.' },
      { id: 'machine-exhibit-2', text: 'A bubble tube spun beside a stable wheel.' },
      { id: 'machine-exhibit-3', text: 'The noble guide nodded at the model.' },
    ],
    correctSegmentIds: ['machine-exhibit-2'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.machineExhibit,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedConsonantLePractice,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-practice-5',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedConsonantLePractice[4],
    prompt: 'Match each word to its split.',
    explanation: 'Each word matches the authored split in the lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['title-split', 'handle-split', 'bubble-split', 'noble-split'],
    targetVocabulary: ['title', 'handle', 'bubble', 'noble'],
    soundOutChunks: ['ti', 'tle', 'han', 'dle', 'bub', 'ble', 'no', 'ble'],
    tags: ['consonant-le', 'open-syllable', 'closed-syllable'],
    rows: [
      {
        id: 'title-row',
        prompt: 'title',
        correctChoiceId: 'title-split',
        options: [
          { id: 'title-split', text: 'ti | tle' },
          { id: 'title-mis1', text: 'tit | le' },
          { id: 'title-mis2', text: 'ti | t le' },
          { id: 'title-mis3', text: 't | itle' },
        ],
      },
      {
        id: 'handle-row',
        prompt: 'handle',
        correctChoiceId: 'handle-split',
        options: [
          { id: 'handle-mis1', text: 'hand | le' },
          { id: 'handle-split', text: 'han | dle' },
          { id: 'handle-mis2', text: 'ha | ndle' },
          { id: 'handle-mis3', text: 'han | d le' },
        ],
      },
      {
        id: 'bubble-row',
        prompt: 'bubble',
        correctChoiceId: 'bubble-split',
        options: [
          { id: 'bubble-mis1', text: 'bubb | le' },
          { id: 'bubble-mis2', text: 'bu | bble' },
          { id: 'bubble-split', text: 'bub | ble' },
          { id: 'bubble-mis3', text: 'bub | b le' },
        ],
      },
      {
        id: 'noble-row',
        prompt: 'noble',
        correctChoiceId: 'noble-split',
        options: [
          { id: 'noble-split', text: 'no | ble' },
          { id: 'noble-mis1', text: 'nob | le' },
          { id: 'noble-mis2', text: 'no | b le' },
          { id: 'noble-mis3', text: 'n | oble' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.jungleHabitat,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedMixedSyllables,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-mixed-1',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedMixedSyllables[0],
    prompt: 'Which word has an open syllable before consonant-le?',
    explanation: 'Stable has sta | ble, so the first syllable is open.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['stable-choice'],
    targetVocabulary: ['jungle', 'dimple', 'stable', 'bundle'],
    soundOutChunks: ['sta', 'ble'],
    tags: ['consonant-le', 'open-syllable'],
    choices: [
      { id: 'jungle-choice', text: 'jungle' },
      { id: 'bundle-choice', text: 'bundle' },
      { id: 'dimple-choice', text: 'dimple' },
      { id: 'stable-choice', text: 'stable' },
    ],
    correctChoiceIds: ['stable-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.jungleHabitat,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedMixedSyllables,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-mixed-2',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedMixedSyllables[1],
    prompt: 'Which word splits as jun | gle?',
    explanation: 'Jungle has jun | gle, so the first syllable is closed.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['jungle-choice'],
    targetVocabulary: ['jungle', 'dimple', 'stable', 'bundle'],
    soundOutChunks: ['jun', 'gle'],
    tags: ['consonant-le', 'closed-syllable'],
    choices: [
      { id: 'stable-choice', text: 'stable' },
      { id: 'bundle-choice', text: 'bundle' },
      { id: 'dimple-choice', text: 'dimple' },
      { id: 'jungle-choice', text: 'jungle' },
    ],
    correctChoiceIds: ['jungle-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.jungleHabitat,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedMixedSyllables,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-mixed-3',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedMixedSyllables[2],
    prompt: 'Choose all the words with consonant-le endings in the habitat passage.',
    explanation: 'Jungle, dimple, stable, and bundle all end with consonant-le chunks.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['jungle-choice', 'dimple-choice', 'stable-choice', 'bundle-choice'],
    targetVocabulary: ['jungle', 'dimple', 'stable', 'bundle'],
    soundOutChunks: ['jun', 'gle', 'dim', 'ple', 'sta', 'ble', 'bun', 'dle'],
    tags: ['consonant-le', 'open-syllable', 'closed-syllable'],
    choices: [
      { id: 'jungle-choice', text: 'jungle' },
      { id: 'dimple-choice', text: 'dimple' },
      { id: 'stable-choice', text: 'stable' },
      { id: 'bundle-choice', text: 'bundle' },
    ],
    correctChoiceIds: ['jungle-choice', 'dimple-choice', 'stable-choice', 'bundle-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.jungleHabitat,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedMixedSyllables,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-mixed-4',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedMixedSyllables[3],
    prompt: 'Select the sentence that says the little monkey crossed a stable bridge.',
    explanation: 'The third sentence gives the clue about the monkey and the stable bridge.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['jungle-habitat-3'],
    targetVocabulary: ['stable', 'bundle', 'jungle'],
    soundOutChunks: ['sta', 'ble'],
    tags: ['consonant-le', 'open-syllable', 'closed-syllable'],
    selectableSegments: [
      { id: 'jungle-habitat-1', text: 'The jungle habitat model stood on a table.' },
      { id: 'jungle-habitat-2', text: 'A dimple card marked each animal home.' },
      { id: 'jungle-habitat-3', text: 'The little monkey crossed a stable bridge.' },
    ],
    correctSegmentIds: ['jungle-habitat-3'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.jungleHabitat,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedMixedSyllables,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-mixed-5',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedMixedSyllables[4],
    prompt: 'Match each word to its split.',
    explanation: 'Each word matches the authored split in the lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['jungle-split', 'dimple-split', 'stable-split', 'bundle-split'],
    targetVocabulary: ['jungle', 'dimple', 'stable', 'bundle'],
    soundOutChunks: ['jun', 'gle', 'dim', 'ple', 'sta', 'ble', 'bun', 'dle'],
    tags: ['consonant-le', 'open-syllable', 'closed-syllable'],
    rows: [
      {
        id: 'jungle-row',
        prompt: 'jungle',
        correctChoiceId: 'jungle-split',
        options: [
          { id: 'jungle-split', text: 'jun | gle' },
          { id: 'jungle-mis1', text: 'jung | le' },
          { id: 'jungle-mis2', text: 'ju | ngle' },
          { id: 'jungle-mis3', text: 'jun | g le' },
        ],
      },
      {
        id: 'dimple-row',
        prompt: 'dimple',
        correctChoiceId: 'dimple-split',
        options: [
          { id: 'dimple-mis1', text: 'dimp | le' },
          { id: 'dimple-split', text: 'dim | ple' },
          { id: 'dimple-mis2', text: 'di | mple' },
          { id: 'dimple-mis3', text: 'dim | p le' },
        ],
      },
      {
        id: 'stable-row',
        prompt: 'stable',
        correctChoiceId: 'stable-split',
        options: [
          { id: 'stable-split', text: 'sta | ble' },
          { id: 'stable-mis1', text: 'stab | le' },
          { id: 'stable-mis2', text: 'st | able' },
          { id: 'stable-mis3', text: 'sta | b le' },
        ],
      },
      {
        id: 'bundle-row',
        prompt: 'bundle',
        correctChoiceId: 'bundle-split',
        options: [
          { id: 'bundle-mis1', text: 'bund | le' },
          { id: 'bundle-mis2', text: 'bu | ndle' },
          { id: 'bundle-split', text: 'bun | dle' },
          { id: 'bundle-mis3', text: 'bun | d le' },
        ],
      },
    ],
  }),
]
