import type { ReadingQuestion } from '../../../../types'
import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from '../variableVowelsOoEa/questionFactories'
import {
  CONSONANT_LE_CONTENT_VERSION,
  CONSONANT_LE_LESSON_IDS,
  CONSONANT_LE_PASSAGE_IDS,
  CONSONANT_LE_QUESTION_IDS,
} from './ids'

const common = {
  benchmarkReference: 'ELA.2.F.1.3c',
  skillIdentifier: 'g2-word-forge-word-practice',
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'Word Forge',
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2',
  contentVersion: CONSONANT_LE_CONTENT_VERSION,
  reviewStatus: 'DRAFT' as const,
}

export const checkpointQuestions: ReadingQuestion[] = [
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.jungleHabitat,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-a-1',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointA[0],
    prompt: 'Which word splits as jun | gle?',
    explanation: 'Jungle splits as jun | gle and ends with consonant-le.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['jungle-choice'],
    targetVocabulary: ['jungle', 'dimple', 'stable', 'bundle'],
    soundOutChunks: ['jun', 'gle'],
    tags: ['consonant-le'],
    choices: [
      { id: 'table-choice', text: 'table' },
      { id: 'bundle-choice', text: 'bundle' },
      { id: 'dimple-choice', text: 'dimple' },
      { id: 'jungle-choice', text: 'jungle' },
    ],
    correctChoiceIds: ['jungle-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.bottleRecycling,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-a-2',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointA[1],
    prompt: 'Which split matches bottle?',
    explanation: 'Bottle splits as bot | tle in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['bottle-split'],
    targetVocabulary: ['bottle', 'pebble', 'bundle', 'candle'],
    soundOutChunks: ['bot', 'tle'],
    tags: ['consonant-le', 'closed-syllable'],
    choices: [
      { id: 'bottle-mis1', text: 'bott | le' },
      { id: 'bottle-split', text: 'bot | tle' },
      { id: 'bottle-mis2', text: 'bo | ttle' },
      { id: 'bottle-mis3', text: 'bot | t le' },
    ],
    correctChoiceIds: ['bottle-split'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.jungleHabitat,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-a-3',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointA[2],
    prompt: 'Which word has an open syllable before consonant-le?',
    explanation: 'Stable has sta | ble, so the first syllable is open.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['stable-choice'],
    targetVocabulary: ['stable', 'bundle', 'dimple', 'jungle'],
    soundOutChunks: ['sta', 'ble'],
    tags: ['consonant-le', 'open-syllable'],
    choices: [
      { id: 'jungle-choice', text: 'jungle' },
      { id: 'bundle-choice', text: 'bundle' },
      { id: 'dimple-choice', text: 'dimple' },
      { id: 'stable-choice', text: 'stable' },
    ],
    correctChoiceIds: ['stable-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.bottleRecycling,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-a-4',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointA[3],
    prompt: 'Which word splits as peb | ble?',
    explanation: 'Pebble has peb | ble, so the first syllable is closed.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['pebble-choice'],
    targetVocabulary: ['bottle', 'pebble', 'bundle', 'candle'],
    soundOutChunks: ['peb', 'ble'],
    tags: ['consonant-le', 'closed-syllable'],
    choices: [
      { id: 'stable-choice', text: 'stable' },
      { id: 'bundle-choice', text: 'bundle' },
      { id: 'candle-choice', text: 'candle' },
      { id: 'pebble-choice', text: 'pebble' },
    ],
    correctChoiceIds: ['pebble-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.jungleHabitat,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-a-5',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointA[4],
    prompt: 'Choose all the words that show consonant-le in the habitat passage.',
    explanation: 'Jungle, dimple, stable, and bundle all show consonant-le.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['jungle-choice', 'dimple-choice', 'stable-choice', 'bundle-choice'],
    targetVocabulary: ['jungle', 'dimple', 'stable', 'bundle'],
    soundOutChunks: ['jun', 'gle', 'dim', 'ple', 'sta', 'ble', 'bun', 'dle'],
    tags: ['consonant-le', 'open-syllable', 'closed-syllable'],
    choices: [
      { id: 'jungle-choice', text: 'jungle' },
      { id: 'dimple-choice', text: 'dimple' },
      { id: 'stable-choice', text: 'stable' },
      { id: 'bundle-choice', text: 'bundle' },
    ],
    correctChoiceIds: ['jungle-choice', 'dimple-choice', 'stable-choice', 'bundle-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.bubbleScience,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-a-6',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointA[5],
    prompt: 'Select the sentence that says the bubble jar sat on a table.',
    explanation: 'The first sentence gives the clue about the bubble jar and the table.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['bubble-science-1'],
    targetVocabulary: ['bubble', 'table', 'maple'],
    soundOutChunks: ['bub', 'ble'],
    tags: ['consonant-le', 'open-syllable'],
    selectableSegments: [
      { id: 'bubble-science-1', text: 'The bubble jar sat on a table.' },
      { id: 'bubble-science-2', text: 'A maple leaf floated near the water.' },
      { id: 'bubble-science-3', text: 'The rattle fan shook a little.' },
    ],
    correctSegmentIds: ['bubble-science-1'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.bottleRecycling,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-a-7',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointA[6],
    prompt: 'Match each word to its split.',
    explanation: 'Each word matches the authored split in the lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['bottle-split', 'pebble-split', 'candle-split', 'apple-split'],
    targetVocabulary: ['bottle', 'pebble', 'candle', 'apple'],
    soundOutChunks: ['bot', 'tle', 'peb', 'ble', 'can', 'dle', 'ap', 'ple'],
    tags: ['consonant-le', 'open-syllable', 'closed-syllable'],
    rows: [
      {
        id: 'bottle-row',
        prompt: 'bottle',
        correctChoiceId: 'bottle-split',
        options: [
          { id: 'bottle-split', text: 'bot | tle' },
          { id: 'bottle-mis1', text: 'bott | le' },
          { id: 'bottle-mis2', text: 'bo | ttle' },
          { id: 'bottle-mis3', text: 'bot | t le' },
        ],
      },
      {
        id: 'pebble-row',
        prompt: 'pebble',
        correctChoiceId: 'pebble-split',
        options: [
          { id: 'pebble-mis1', text: 'peb | le' },
          { id: 'pebble-split', text: 'peb | ble' },
          { id: 'pebble-mis2', text: 'pe | bble' },
          { id: 'pebble-mis3', text: 'peb | b le' },
        ],
      },
      {
        id: 'candle-row',
        prompt: 'candle',
        correctChoiceId: 'candle-split',
        options: [
          { id: 'candle-mis1', text: 'cand | le' },
          { id: 'candle-split', text: 'can | dle' },
          { id: 'candle-mis2', text: 'ca | ndle' },
          { id: 'candle-mis3', text: 'can | d le' },
        ],
      },
      {
        id: 'apple-row',
        prompt: 'apple',
        correctChoiceId: 'apple-split',
        options: [
          { id: 'apple-mis1', text: 'app | le' },
          { id: 'apple-mis2', text: 'a | pple' },
          { id: 'apple-split', text: 'ap | ple' },
          { id: 'apple-mis3', text: 'ap | p le' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.orchardTable,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-b-1',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointB[0],
    prompt: 'Which word splits as ma | ple?',
    explanation: 'Maple has ma | ple, so the first syllable is open.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['maple-choice'],
    targetVocabulary: ['table', 'maple', 'apple', 'cable'],
    soundOutChunks: ['ma', 'ple'],
    tags: ['consonant-le', 'open-syllable'],
    choices: [
      { id: 'apple-choice', text: 'apple' },
      { id: 'cable-choice', text: 'cable' },
      { id: 'table-choice', text: 'table' },
      { id: 'maple-choice', text: 'maple' },
    ],
    correctChoiceIds: ['maple-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.puzzleClub,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-b-2',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointB[1],
    prompt: 'Which word splits as puz | zle?',
    explanation: 'Puzzle has puz | zle, so the first syllable is closed.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['puzzle-choice'],
    targetVocabulary: ['puzzle', 'simple', 'bottle', 'sample'],
    soundOutChunks: ['puz', 'zle'],
    tags: ['consonant-le', 'closed-syllable'],
    choices: [
      { id: 'sample-choice', text: 'sample' },
      { id: 'simple-choice', text: 'simple' },
      { id: 'bottle-choice', text: 'bottle' },
      { id: 'puzzle-choice', text: 'puzzle' },
    ],
    correctChoiceIds: ['puzzle-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.orchardTable,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-b-3',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointB[2],
    prompt: 'Which word has a closed syllable before consonant-le in the orchard lesson?',
    explanation: 'Apple has ap | ple, so the first syllable is closed.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['apple-choice'],
    targetVocabulary: ['apple', 'table', 'maple', 'cable'],
    soundOutChunks: ['ap', 'ple'],
    tags: ['consonant-le', 'closed-syllable'],
    choices: [
      { id: 'table-choice', text: 'table' },
      { id: 'maple-choice', text: 'maple' },
      { id: 'cable-choice', text: 'cable' },
      { id: 'apple-choice', text: 'apple' },
    ],
    correctChoiceIds: ['apple-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.puzzleClub,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-b-4',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointB[3],
    prompt: 'Which word has an open syllable before consonant-le in the puzzle club lesson?',
    explanation: 'Table has ta | ble, so the first syllable is open.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['table-choice'],
    targetVocabulary: ['puzzle', 'simple', 'bottle', 'table'],
    soundOutChunks: ['ta', 'ble'],
    tags: ['consonant-le', 'open-syllable'],
    choices: [
      { id: 'bottle-choice', text: 'bottle' },
      { id: 'puzzle-choice', text: 'puzzle' },
      { id: 'simple-choice', text: 'simple' },
      { id: 'table-choice', text: 'table' },
    ],
    correctChoiceIds: ['table-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.orchardTable,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-b-5',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointB[4],
    prompt: 'Choose all the words with consonant-le endings in the orchard passage.',
    explanation: 'Apple, table, maple, and cable all end with consonant-le chunks.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['apple-choice', 'table-choice', 'maple-choice', 'cable-choice'],
    targetVocabulary: ['apple', 'table', 'maple', 'cable'],
    soundOutChunks: ['ap', 'ple', 'ta', 'ble', 'ma', 'ple', 'ca', 'ble'],
    tags: ['consonant-le', 'open-syllable', 'closed-syllable'],
    choices: [
      { id: 'apple-choice', text: 'apple' },
      { id: 'table-choice', text: 'table' },
      { id: 'maple-choice', text: 'maple' },
      { id: 'cable-choice', text: 'cable' },
    ],
    correctChoiceIds: ['apple-choice', 'table-choice', 'maple-choice', 'cable-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.puzzleClub,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-b-6',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointB[5],
    prompt: 'Select the sentence that says the puzzle club built a simple model.',
    explanation: 'The first sentence gives the clue about the puzzle club and the model.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['puzzle-club-1'],
    targetVocabulary: ['puzzle', 'simple', 'model'],
    soundOutChunks: ['puz', 'zle'],
    tags: ['consonant-le', 'closed-syllable'],
    selectableSegments: [
      { id: 'puzzle-club-1', text: 'The puzzle club built a simple model.' },
      { id: 'puzzle-club-2', text: 'They placed a bottle on a rattle tray.' },
      { id: 'puzzle-club-3', text: 'A pebble held the corner of the note.' },
    ],
    correctSegmentIds: ['puzzle-club-1'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.puzzleClub,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-b-7',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointB[6],
    prompt: 'Match each word to its split.',
    explanation: 'Each word matches the authored split in the lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['puzzle-split', 'simple-split', 'bottle-split', 'sample-split'],
    targetVocabulary: ['puzzle', 'simple', 'bottle', 'sample'],
    soundOutChunks: ['puz', 'zle', 'sim', 'ple', 'bot', 'tle', 'sam', 'ple'],
    tags: ['consonant-le', 'closed-syllable'],
    rows: [
      {
        id: 'puzzle-row',
        prompt: 'puzzle',
        correctChoiceId: 'puzzle-split',
        options: [
          { id: 'puzzle-split', text: 'puz | zle' },
          { id: 'puzzle-mis1', text: 'puz | le' },
          { id: 'puzzle-mis2', text: 'puz | z le' },
          { id: 'puzzle-mis3', text: 'puzz | le' },
        ],
      },
      {
        id: 'simple-row',
        prompt: 'simple',
        correctChoiceId: 'simple-split',
        options: [
          { id: 'simple-mis1', text: 'simp | le' },
          { id: 'simple-split', text: 'sim | ple' },
          { id: 'simple-mis2', text: 'si | mple' },
          { id: 'simple-mis3', text: 'sim | p le' },
        ],
      },
      {
        id: 'bottle-row',
        prompt: 'bottle',
        correctChoiceId: 'bottle-split',
        options: [
          { id: 'bottle-mis1', text: 'bott | le' },
          { id: 'bottle-split', text: 'bot | tle' },
          { id: 'bottle-mis2', text: 'bo | ttle' },
          { id: 'bottle-mis3', text: 'bot | t le' },
        ],
      },
      {
        id: 'sample-row',
        prompt: 'sample',
        correctChoiceId: 'sample-split',
        options: [
          { id: 'sample-mis1', text: 'sam | p le' },
          { id: 'sample-split', text: 'sam | ple' },
          { id: 'sample-mis2', text: 'sa | mple' },
          { id: 'sample-mis3', text: 'samp | le' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.candleDemo,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-c-1',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointC[0],
    prompt: 'Which word splits as can | dle?',
    explanation: 'Candle has can | dle, so the first syllable is closed.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['candle-choice'],
    targetVocabulary: ['candle', 'stable', 'little', 'simple'],
    soundOutChunks: ['can', 'dle'],
    tags: ['consonant-le', 'closed-syllable'],
    choices: [
      { id: 'stable-choice', text: 'stable' },
      { id: 'little-choice', text: 'little' },
      { id: 'simple-choice', text: 'simple' },
      { id: 'candle-choice', text: 'candle' },
    ],
    correctChoiceIds: ['candle-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.machineExhibit,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-c-2',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointC[1],
    prompt: 'Which word splits as ti | tle?',
    explanation: 'Title has ti | tle, so the first syllable is open.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['title-choice'],
    targetVocabulary: ['title', 'handle', 'bubble', 'noble'],
    soundOutChunks: ['ti', 'tle'],
    tags: ['consonant-le', 'open-syllable'],
    choices: [
      { id: 'handle-choice', text: 'handle' },
      { id: 'bubble-choice', text: 'bubble' },
      { id: 'noble-choice', text: 'noble' },
      { id: 'title-choice', text: 'title' },
    ],
    correctChoiceIds: ['title-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.machineExhibit,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-c-3',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointC[2],
    prompt: 'Which word splits as han | dle?',
    explanation: 'Handle has han | dle, so the first syllable is closed.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['handle-choice'],
    targetVocabulary: ['title', 'handle', 'bubble', 'noble'],
    soundOutChunks: ['han', 'dle'],
    tags: ['consonant-le', 'closed-syllable'],
    choices: [
      { id: 'title-choice', text: 'title' },
      { id: 'bubble-choice', text: 'bubble' },
      { id: 'noble-choice', text: 'noble' },
      { id: 'handle-choice', text: 'handle' },
    ],
    correctChoiceIds: ['handle-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.candleDemo,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-c-4',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointC[3],
    prompt: 'Which word splits as sim | ple?',
    explanation: 'Simple has sim | ple, so the first syllable is closed.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['simple-choice'],
    targetVocabulary: ['candle', 'stable', 'little', 'simple'],
    soundOutChunks: ['sim', 'ple'],
    tags: ['consonant-le', 'closed-syllable'],
    choices: [
      { id: 'candle-choice', text: 'candle' },
      { id: 'stable-choice', text: 'stable' },
      { id: 'little-choice', text: 'little' },
      { id: 'simple-choice', text: 'simple' },
    ],
    correctChoiceIds: ['simple-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.candleDemo,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-c-5',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointC[4],
    prompt: 'Choose all the words with consonant-le endings in the safety demo.',
    explanation: 'Candle, stable, little, and simple all end with consonant-le chunks.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['candle-choice', 'stable-choice', 'little-choice', 'simple-choice'],
    targetVocabulary: ['candle', 'stable', 'little', 'simple'],
    soundOutChunks: ['can', 'dle', 'sta', 'ble', 'lit', 'tle', 'sim', 'ple'],
    tags: ['consonant-le', 'open-syllable', 'closed-syllable'],
    choices: [
      { id: 'candle-choice', text: 'candle' },
      { id: 'stable-choice', text: 'stable' },
      { id: 'little-choice', text: 'little' },
      { id: 'simple-choice', text: 'simple' },
    ],
    correctChoiceIds: ['candle-choice', 'stable-choice', 'little-choice', 'simple-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.machineExhibit,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-c-6',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointC[5],
    prompt: 'Select the sentence that mentions a bubble tube and a stable wheel.',
    explanation: 'The second sentence gives the clue about the bubble tube and the stable wheel.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['machine-exhibit-2'],
    targetVocabulary: ['bubble', 'stable'],
    soundOutChunks: ['bub', 'ble'],
    tags: ['consonant-le', 'open-syllable', 'closed-syllable'],
    selectableSegments: [
      { id: 'machine-exhibit-1', text: 'The machine exhibit showed a title card and a handle.' },
      { id: 'machine-exhibit-2', text: 'A bubble tube spun beside a stable wheel.' },
      { id: 'machine-exhibit-3', text: 'The noble guide nodded at the model.' },
    ],
    correctSegmentIds: ['machine-exhibit-2'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.bottleRecycling,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-consonant-le-checkpoint-c-7',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.checkpointC[6],
    prompt: 'Match each word to its split.',
    explanation: 'Each word matches the authored split in the lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['candle-split', 'title-split', 'handle-split', 'simple-split'],
    targetVocabulary: ['candle', 'title', 'handle', 'simple'],
    soundOutChunks: ['can', 'dle', 'ti', 'tle', 'han', 'dle', 'sim', 'ple'],
    tags: ['consonant-le', 'open-syllable', 'closed-syllable'],
    rows: [
      {
        id: 'candle-row',
        prompt: 'candle',
        correctChoiceId: 'candle-split',
        options: [
          { id: 'candle-split', text: 'can | dle' },
          { id: 'candle-mis1', text: 'cand | le' },
          { id: 'candle-mis2', text: 'ca | ndle' },
          { id: 'candle-mis3', text: 'can | d le' },
        ],
      },
      {
        id: 'title-row',
        prompt: 'title',
        correctChoiceId: 'title-split',
        options: [
          { id: 'title-split', text: 'ti | tle' },
          { id: 'title-mis1', text: 'tit | le' },
          { id: 'title-mis2', text: 'ti | t le' },
          { id: 'title-mis3', text: 't | itle' },
        ],
      },
      {
        id: 'handle-row',
        prompt: 'handle',
        correctChoiceId: 'handle-split',
        options: [
          { id: 'handle-mis1', text: 'hand | le' },
          { id: 'handle-split', text: 'han | dle' },
          { id: 'handle-mis2', text: 'ha | ndle' },
          { id: 'handle-mis3', text: 'han | d le' },
        ],
      },
      {
        id: 'simple-row',
        prompt: 'simple',
        correctChoiceId: 'simple-split',
        options: [
          { id: 'simple-mis1', text: 'simp | le' },
          { id: 'simple-split', text: 'sim | ple' },
          { id: 'simple-mis2', text: 'si | mple' },
          { id: 'simple-mis3', text: 'sim | p le' },
        ],
      },
    ],
  }),
]
