import type { ReadingQuestion } from '../../../../types'
import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from '../variableVowelsOoEa/questionFactories'
import {
  CONSONANT_LE_CONTENT_VERSION,
  CONSONANT_LE_LESSON_IDS,
  CONSONANT_LE_PASSAGE_IDS,
  CONSONANT_LE_QUESTION_IDS,
} from './ids'

const common = {
  benchmarkReference: 'ELA.2.F.1.3c',
  skillIdentifier: 'g2-word-forge-word-practice',
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'Word Forge',
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2',
  contentVersion: CONSONANT_LE_CONTENT_VERSION,
  reviewStatus: 'DRAFT' as const,
}

export const buildingBlockQuestions: ReadingQuestion[] = [
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 3,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.orchardTable,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedFinalBeat,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-final-beat-1',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedFinalBeat[0],
    prompt: 'Which word has an open syllable before consonant-le?',
    explanation: 'Table has an open first syllable, ta, before the consonant-le ending.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['table-choice'],
    targetVocabulary: ['table', 'maple', 'apple', 'cable'],
    soundOutChunks: ['ta', 'ble'],
    tags: ['consonant-le', 'open-syllable'],
    choices: [
      { id: 'table-choice', text: 'table' },
      { id: 'apple-choice', text: 'apple' },
      { id: 'candle-choice', text: 'candle' },
      { id: 'bundle-choice', text: 'bundle' },
    ],
    correctChoiceIds: ['table-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 3,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.orchardTable,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedFinalBeat,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-final-beat-2',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedFinalBeat[1],
    prompt: 'Which word has a closed syllable before consonant-le?',
    explanation: 'Apple has a closed first syllable, ap, before the consonant-le ending.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['apple-choice'],
    targetVocabulary: ['apple', 'table', 'maple', 'cable'],
    soundOutChunks: ['ap', 'ple'],
    tags: ['consonant-le', 'closed-syllable'],
    choices: [
      { id: 'table-choice', text: 'table' },
      { id: 'apple-choice', text: 'apple' },
      { id: 'maple-choice', text: 'maple' },
      { id: 'cable-choice', text: 'cable' },
    ],
    correctChoiceIds: ['apple-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 3,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.orchardTable,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedFinalBeat,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-final-beat-3',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedFinalBeat[2],
    prompt: 'Choose all the words with consonant-le endings in the orchard passage.',
    explanation: 'Apple, table, maple, and cable all end with consonant-le chunks.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['apple-choice', 'table-choice', 'maple-choice', 'cable-choice'],
    targetVocabulary: ['apple', 'table', 'maple', 'cable'],
    soundOutChunks: ['ap', 'ple', 'ta', 'ble', 'ma', 'ple', 'ca', 'ble'],
    tags: ['consonant-le', 'open-syllable', 'closed-syllable'],
    choices: [
      { id: 'apple-choice', text: 'apple' },
      { id: 'table-choice', text: 'table' },
      { id: 'maple-choice', text: 'maple' },
      { id: 'cable-choice', text: 'cable' },
    ],
    correctChoiceIds: ['apple-choice', 'table-choice', 'maple-choice', 'cable-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 3,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.orchardTable,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedFinalBeat,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-final-beat-4',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedFinalBeat[3],
    prompt: 'Select the sentence that says the farmer tied a cable to the sign.',
    explanation: 'The third sentence gives the clue about the cable and the sign.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['orchard-table-3'],
    targetVocabulary: ['cable', 'table', 'maple'],
    soundOutChunks: ['ca', 'ble'],
    tags: ['consonant-le'],
    selectableSegments: [
      { id: 'orchard-table-1', text: 'At the orchard, the apple cart sat beside a table.' },
      { id: 'orchard-table-2', text: 'A maple leaf rested near a candle box.' },
      { id: 'orchard-table-3', text: 'The farmer tied a cable to the sign.' },
    ],
    correctSegmentIds: ['orchard-table-3'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 3,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.orchardTable,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedFinalBeat,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-final-beat-5',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedFinalBeat[4],
    prompt: 'Match each word to its split.',
    explanation: 'Each word is split into the authored chunks shown in the lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['table-split', 'maple-split', 'apple-split', 'cable-split'],
    targetVocabulary: ['table', 'maple', 'apple', 'cable'],
    soundOutChunks: ['ta', 'ble', 'ma', 'ple', 'ap', 'ple', 'ca', 'ble'],
    tags: ['consonant-le', 'open-syllable', 'closed-syllable'],
    rows: [
      {
        id: 'table-row',
        prompt: 'table',
        correctChoiceId: 'table-split',
        options: [
          { id: 'table-split', text: 'ta | ble' },
          { id: 'table-mis1', text: 'tab | le' },
          { id: 'table-mis2', text: 't | able' },
          { id: 'table-mis3', text: 'ta | b le' },
        ],
      },
      {
        id: 'maple-row',
        prompt: 'maple',
        correctChoiceId: 'maple-split',
        options: [
          { id: 'maple-mis1', text: 'map | le' },
          { id: 'maple-split', text: 'ma | ple' },
          { id: 'maple-mis2', text: 'm | aple' },
          { id: 'maple-mis3', text: 'ma | p le' },
        ],
      },
      {
        id: 'apple-row',
        prompt: 'apple',
        correctChoiceId: 'apple-split',
        options: [
          { id: 'apple-mis1', text: 'app | le' },
          { id: 'apple-split', text: 'ap | ple' },
          { id: 'apple-mis2', text: 'a | pple' },
          { id: 'apple-mis3', text: 'ap | p le' },
        ],
      },
      {
        id: 'cable-row',
        prompt: 'cable',
        correctChoiceId: 'cable-split',
        options: [
          { id: 'cable-mis1', text: 'cab | le' },
          { id: 'cable-mis2', text: 'c | able' },
          { id: 'cable-split', text: 'ca | ble' },
          { id: 'cable-mis3', text: 'ca | b le' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 3,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.candleDemo,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedSplitBeforeConsonantLe,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-split-before-1',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedSplitBeforeConsonantLe[0],
    prompt: 'Which split matches candle?',
    explanation: 'The authored split for candle is can | dle.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['candle-split'],
    targetVocabulary: ['candle', 'stable', 'little', 'simple'],
    soundOutChunks: ['can', 'dle'],
    tags: ['consonant-le', 'closed-syllable'],
    choices: [
      { id: 'candle-mis1', text: 'cand | le' },
      { id: 'candle-mis2', text: 'ca | ndle' },
      { id: 'candle-split', text: 'can | dle' },
      { id: 'candle-mis3', text: 'can | del' },
    ],
    correctChoiceIds: ['candle-split'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 3,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.candleDemo,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedSplitBeforeConsonantLe,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-split-before-2',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedSplitBeforeConsonantLe[1],
    prompt: 'Which word has a closed first syllable and a consonant-le ending?',
    explanation: 'Simple has sim | ple, so the first syllable is closed.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['simple-choice'],
    targetVocabulary: ['candle', 'little', 'simple', 'stable'],
    soundOutChunks: ['sim', 'ple'],
    tags: ['consonant-le', 'closed-syllable'],
    choices: [
      { id: 'candle-choice', text: 'candle' },
      { id: 'little-choice', text: 'little' },
      { id: 'stable-choice', text: 'stable' },
      { id: 'simple-choice', text: 'simple' },
    ],
    correctChoiceIds: ['simple-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 3,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.candleDemo,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedSplitBeforeConsonantLe,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-split-before-3',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedSplitBeforeConsonantLe[2],
    prompt: 'Choose all the words with a closed first syllable in the safety demo.',
    explanation: 'Candle, little, and simple all begin with a closed syllable.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['candle-choice', 'little-choice', 'simple-choice'],
    targetVocabulary: ['candle', 'little', 'simple', 'stable'],
    soundOutChunks: ['can', 'dle', 'lit', 'tle', 'sim', 'ple'],
    tags: ['consonant-le', 'closed-syllable'],
    choices: [
      { id: 'candle-choice', text: 'candle' },
      { id: 'little-choice', text: 'little' },
      { id: 'simple-choice', text: 'simple' },
      { id: 'stable-choice', text: 'stable' },
    ],
    correctChoiceIds: ['candle-choice', 'little-choice', 'simple-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 3,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.candleDemo,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedSplitBeforeConsonantLe,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-split-before-4',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedSplitBeforeConsonantLe[3],
    prompt: 'Select the sentence that says a little helper watched the flame.',
    explanation: 'The second sentence gives the clue about the little helper.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['candle-demo-2'],
    targetVocabulary: ['little', 'candle', 'simple'],
    soundOutChunks: ['lit', 'tle'],
    tags: ['consonant-le'],
    selectableSegments: [
      { id: 'candle-demo-1', text: 'At the safety demo, a candle sat on a stable table.' },
      { id: 'candle-demo-2', text: 'A little helper watched the flame.' },
      { id: 'candle-demo-3', text: 'The bundle of rules stayed near the candle.' },
    ],
    correctSegmentIds: ['candle-demo-2'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 3,
    passageIdentifier: CONSONANT_LE_PASSAGE_IDS.candleDemo,
    lessonIdentifier: CONSONANT_LE_LESSON_IDS.guidedSplitBeforeConsonantLe,
    activityIdentifier: 'activity-word-forge-consonant-le-guided-split-before-5',
    questionIdentifier: CONSONANT_LE_QUESTION_IDS.guidedSplitBeforeConsonantLe[4],
    prompt: 'Match each word to its split.',
    explanation: 'Each word matches the authored split in the lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['candle-split', 'little-split', 'simple-split', 'stable-split'],
    targetVocabulary: ['candle', 'little', 'simple', 'stable'],
    soundOutChunks: ['can', 'dle', 'lit', 'tle', 'sim', 'ple', 'sta', 'ble'],
    tags: ['consonant-le', 'closed-syllable', 'open-syllable'],
    rows: [
      {
        id: 'candle-row',
        prompt: 'candle',
        correctChoiceId: 'candle-split',
        options: [
          { id: 'candle-split', text: 'can | dle' },
          { id: 'candle-mis1', text: 'can | del' },
          { id: 'candle-mis2', text: 'cand | le' },
          { id: 'candle-mis3', text: 'ca | ndle' },
        ],
      },
      {
        id: 'little-row',
        prompt: 'little',
        correctChoiceId: 'little-split',
        options: [
          { id: 'little-mis1', text: 'lit | le' },
          { id: 'little-split', text: 'lit | tle' },
          { id: 'little-mis2', text: 'li | ttle' },
          { id: 'little-mis3', text: 'litt | le' },
        ],
      },
      {
        id: 'simple-row',
        prompt: 'simple',
        correctChoiceId: 'simple-split',
        options: [
          { id: 'simple-mis1', text: 'simp | le' },
          { id: 'simple-mis2', text: 'si | mple' },
          { id: 'simple-split', text: 'sim | ple' },
          { id: 'simple-mis3', text: 'sim | p le' },
        ],
      },
      {
        id: 'stable-row',
        prompt: 'stable',
        correctChoiceId: 'stable-split',
        options: [
          { id: 'stable-split', text: 'sta | ble' },
          { id: 'stable-mis1', text: 'stab | le' },
          { id: 'stable-mis2', text: 'st | able' },
          { id: 'stable-mis3', text: 'sta | b le' },
        ],
      },
    ],
  }),
]
