import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
  lessonChoice as choice,
} from './questionFactories'
import { RETELL_HALL_LESSON_IDS, RETELL_HALL_PASSAGE_IDS, RETELL_HALL_QUESTION_IDS } from './ids'
import { getRetellHallPassagePlan } from './passages'
import { buildCommonQuestionFields, joinWords } from './questionsShared'
import { RETELL_HALL_INFORMATIONAL_QUESTION_TAGS, RETELL_HALL_LITERARY_QUESTION_TAGS } from './patterns'

const mural = getRetellHallPassagePlan(RETELL_HALL_PASSAGE_IDS.literaryMuralLabel)
const seedTravel = getRetellHallPassagePlan(RETELL_HALL_PASSAGE_IDS.informationalSeedTravel)

const literaryFields = (questionIdentifier: string, difficulty: 1 | 2, tags: string[]) =>
  buildCommonQuestionFields('literary', tags, difficulty, mural.passageId, RETELL_HALL_LESSON_IDS.prereqStoryPartsInOrder, questionIdentifier)

const informationalFields = (questionIdentifier: string, difficulty: 1 | 2, tags: string[]) =>
  buildCommonQuestionFields('informational', tags, difficulty, seedTravel.passageId, RETELL_HALL_LESSON_IDS.prereqCentralIdeaAndImportantDetails, questionIdentifier)

export const retellHallPrerequisiteQuestions = [
  createMultipleChoiceQuestion({
    ...literaryFields(RETELL_HALL_QUESTION_IDS.prereqStoryPartsInOrder[0], 1, ['literary-retell', 'literary-main-characters', 'literary-setting']),
    passageIdentifier: mural.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.prereqStoryPartsInOrder,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.prereqStoryPartsInOrder[0],
    prompt: 'Which sentence tells the opening of the story?',
    explanation: 'Sentence 1 names Maya and Eli and sets the art-room scene.',
    evidenceReference: mural.sentences[0].sentenceId,
    evidenceReferenceIds: [mural.sentences[0].sentenceId],
    targetVocabulary: ['opening', 'setting'],
    soundOutChunks: joinWords('art room library'),
    choices: [
      choice('p1', mural.sentences[1].text),
      choice('p2', mural.sentences[0].text),
      choice('p3', mural.sentences[4].text),
      choice('p4', mural.sentences[6].text),
    ],
    correctChoiceIds: ['p2'],
  }),
  createMultipleChoiceQuestion({
    ...literaryFields(RETELL_HALL_QUESTION_IDS.prereqStoryPartsInOrder[1], 1, ['literary-retell', 'literary-problem']),
    passageIdentifier: mural.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.prereqStoryPartsInOrder,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.prereqStoryPartsInOrder[1],
    prompt: 'What is the main problem?',
    explanation: 'The mural needs a final label before visitors arrive.',
    evidenceReference: mural.sentences[1].sentenceId,
    evidenceReferenceIds: [mural.sentences[1].sentenceId],
    targetVocabulary: ['problem', 'final'],
    soundOutChunks: joinWords('final label visitors'),
    choices: [
      choice('p1', 'The children moved the paint jars.'),
      choice('p2', 'The mural needed a final label.'),
      choice('p3', 'The art room was beside the library.'),
      choice('p4', 'A red eraser waited on the sill.'),
    ],
    correctChoiceIds: ['p2'],
  }),
  createMultiselectQuestion({
    ...literaryFields(RETELL_HALL_QUESTION_IDS.prereqStoryPartsInOrder[2], 1, ['literary-retell', 'literary-important-events', 'literary-logical-sequence']),
    passageIdentifier: mural.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.prereqStoryPartsInOrder,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.prereqStoryPartsInOrder[2],
    prompt: 'Choose two important events that belong in the retell.',
    explanation: 'The cards and the tape help the children fix the mural label.',
    evidenceReference: mural.sentences[2].sentenceId,
    evidenceReferenceIds: [mural.sentences[2].sentenceId, mural.sentences[4].sentenceId],
    targetVocabulary: ['important', 'event'],
    soundOutChunks: joinWords('cards tape'),
    choices: [
      choice('p1', 'A red eraser waited on the sill.'),
      choice('p2', 'Maya spread the bright cards carefully across the table.'),
      choice('p3', 'The mural needed a final label.'),
      choice('p4', 'They taped the corner flat and checked the picture again.'),
    ],
    correctChoiceIds: ['p2', 'p4'],
  }),
  createHotTextQuestion({
    ...literaryFields(RETELL_HALL_QUESTION_IDS.prereqStoryPartsInOrder[3], 1, ['literary-retell', 'literary-resolution', 'literary-retell-completeness']),
    passageIdentifier: mural.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.prereqStoryPartsInOrder,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.prereqStoryPartsInOrder[3],
    prompt: 'Select the sentence that shows the ending.',
    explanation: 'Sentence 7 shows that the mural is finished and ready for the visitors.',
    evidenceReference: mural.sentences[6].sentenceId,
    evidenceReferenceIds: [mural.sentences[6].sentenceId],
    targetVocabulary: ['ending', 'ready'],
    soundOutChunks: joinWords('ready visitors'),
    selectableSegments: [
      { id: 'h1', text: mural.sentences[1].text },
      { id: 'h2', text: mural.sentences[4].text },
      { id: 'h3', text: mural.sentences[6].text },
      { id: 'h4', text: mural.sentences[7].text },
    ],
    correctSegmentIds: ['h3'],
  }),
  createTableMatchQuestion({
    ...literaryFields(RETELL_HALL_QUESTION_IDS.prereqStoryPartsInOrder[4], 1, [...RETELL_HALL_LITERARY_QUESTION_TAGS]),
    passageIdentifier: mural.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.prereqStoryPartsInOrder,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.prereqStoryPartsInOrder[4],
    prompt: 'Build the retell. Choose one retell piece for each place. Each piece can be used only once. One extra detail does not belong in the retell.',
    explanation: 'The pieces should follow the opening, problem, two important events, and ending. The extra detail stays out.',
    evidenceReference: mural.sentences[0].sentenceId,
    evidenceReferenceIds: mural.sentences.map((sentence) => sentence.sentenceId),
    targetVocabulary: ['opening', 'problem', 'ending'],
    soundOutChunks: joinWords('one extra detail'),
    selectionMode: 'use_each_once',
    rows: [
      {
        id: 'r1',
        prompt: 'Opening',
        correctChoiceId: 'mural-piece-1',
        options: [
          choice('mural-piece-1', 'Maya and Eli work in the art room beside the library to finish the mural label before visitors arrive.'),
          choice('mural-piece-2', 'The problem is that the class mural still needs a final label.'),
          choice('mural-piece-3', 'Maya spreads the bright cards carefully across the table.'),
          choice('mural-piece-4', 'Eli tapes the curled corner flat and the children move the paint jars into an organized line.'),
          choice('mural-piece-5', 'At last, the mural has a neat title and is ready for the visitors.'),
          choice('mural-extra', 'A red eraser waited on the sill.'),
        ],
      },
      {
        id: 'r2',
        prompt: 'Problem',
        correctChoiceId: 'mural-piece-2',
        options: [
          choice('mural-piece-1', 'Maya and Eli work in the art room beside the library to finish the mural label before visitors arrive.'),
          choice('mural-piece-2', 'The problem is that the class mural still needs a final label.'),
          choice('mural-piece-3', 'Maya spreads the bright cards carefully across the table.'),
          choice('mural-piece-4', 'Eli tapes the curled corner flat and the children move the paint jars into an organized line.'),
          choice('mural-piece-5', 'At last, the mural has a neat title and is ready for the visitors.'),
          choice('mural-extra', 'A red eraser waited on the sill.'),
        ],
      },
      {
        id: 'r3',
        prompt: 'Important event 1',
        correctChoiceId: 'mural-piece-3',
        options: [
          choice('mural-piece-1', 'Maya and Eli work in the art room beside the library to finish the mural label before visitors arrive.'),
          choice('mural-piece-2', 'The problem is that the class mural still needs a final label.'),
          choice('mural-piece-3', 'Maya spreads the bright cards carefully across the table.'),
          choice('mural-piece-4', 'Eli tapes the curled corner flat and the children move the paint jars into an organized line.'),
          choice('mural-piece-5', 'At last, the mural has a neat title and is ready for the visitors.'),
          choice('mural-extra', 'A red eraser waited on the sill.'),
        ],
      },
      {
        id: 'r4',
        prompt: 'Important event 2',
        correctChoiceId: 'mural-piece-4',
        options: [
          choice('mural-piece-1', 'Maya and Eli work in the art room beside the library to finish the mural label before visitors arrive.'),
          choice('mural-piece-2', 'The problem is that the class mural still needs a final label.'),
          choice('mural-piece-3', 'Maya spreads the bright cards carefully across the table.'),
          choice('mural-piece-4', 'Eli tapes the curled corner flat and the children move the paint jars into an organized line.'),
          choice('mural-piece-5', 'At last, the mural has a neat title and is ready for the visitors.'),
          choice('mural-extra', 'A red eraser waited on the sill.'),
        ],
      },
      {
        id: 'r5',
        prompt: 'Ending',
        correctChoiceId: 'mural-piece-5',
        options: [
          choice('mural-piece-1', 'Maya and Eli work in the art room beside the library to finish the mural label before visitors arrive.'),
          choice('mural-piece-2', 'The problem is that the class mural still needs a final label.'),
          choice('mural-piece-3', 'Maya spreads the bright cards carefully across the table.'),
          choice('mural-piece-4', 'Eli tapes the curled corner flat and the children move the paint jars into an organized line.'),
          choice('mural-piece-5', 'At last, the mural has a neat title and is ready for the visitors.'),
          choice('mural-extra', 'A red eraser waited on the sill.'),
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...informationalFields(RETELL_HALL_QUESTION_IDS.prereqCentralIdeaAndImportantDetails[0], 1, ['informational-retell', 'informational-central-idea']),
    passageIdentifier: seedTravel.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.prereqCentralIdeaAndImportantDetails,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.prereqCentralIdeaAndImportantDetails[0],
    prompt: 'What is the central idea of this passage?',
    explanation: 'The passage says that seeds travel to new places in several ways.',
    evidenceReference: seedTravel.sentences[0].sentenceId,
    evidenceReferenceIds: [seedTravel.sentences[0].sentenceId],
    targetVocabulary: ['central idea'],
    soundOutChunks: joinWords('seeds travel places'),
    choices: [
      choice('i1', 'Seeds travel to new places in several ways.'),
      choice('i2', 'A gardener keeps a seed packet in a pocket.'),
      choice('i3', 'Animals only help seeds move.'),
      choice('i4', 'Every seed travels on water.'),
    ],
    correctChoiceIds: ['i1'],
  }),
  createMultipleChoiceQuestion({
    ...informationalFields(RETELL_HALL_QUESTION_IDS.prereqCentralIdeaAndImportantDetails[1], 1, ['informational-retell', 'informational-relevant-details']),
    passageIdentifier: seedTravel.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.prereqCentralIdeaAndImportantDetails,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.prereqCentralIdeaAndImportantDetails[1],
    prompt: 'Which detail is most relevant to the central idea?',
    explanation: 'The sentence about wind shows one way seeds travel to new places.',
    evidenceReference: seedTravel.sentences[1].sentenceId,
    evidenceReferenceIds: [seedTravel.sentences[1].sentenceId],
    targetVocabulary: ['relevant', 'detail'],
    soundOutChunks: joinWords('wind float away'),
    choices: [
      choice('i1', 'A gardener may notice a seed packet in a pocket.'),
      choice('i2', 'Tiny hooks cling to animal fur.'),
      choice('i3', 'Water can carry seeds along streams and puddles.'),
      choice('i4', 'Some light seeds ride gently on the wind and float far away.'),
    ],
    correctChoiceIds: ['i4'],
  }),
  createMultiselectQuestion({
    ...informationalFields(RETELL_HALL_QUESTION_IDS.prereqCentralIdeaAndImportantDetails[2], 1, ['informational-retell', 'informational-relevant-details', 'informational-details-across-sections']),
    passageIdentifier: seedTravel.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.prereqCentralIdeaAndImportantDetails,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.prereqCentralIdeaAndImportantDetails[2],
    prompt: 'Choose two details that belong in the retell.',
    explanation: 'The wind and animal-fur details both help explain how seeds travel.',
    evidenceReference: seedTravel.sentences[1].sentenceId,
    evidenceReferenceIds: [seedTravel.sentences[1].sentenceId, seedTravel.sentences[2].sentenceId],
    targetVocabulary: ['travel', 'details'],
    soundOutChunks: joinWords('wind fur'),
    choices: [
      choice('i1', 'A gardener may notice a seed packet in a pocket.'),
      choice('i2', 'Some light seeds ride gently on the wind and float far away.'),
      choice('i3', 'Tiny hooks cling to animal fur.'),
      choice('i4', 'Each move helps a plant begin in a new spot.'),
    ],
    correctChoiceIds: ['i2', 'i3'],
  }),
  createHotTextQuestion({
    ...informationalFields(RETELL_HALL_QUESTION_IDS.prereqCentralIdeaAndImportantDetails[3], 1, ['informational-retell', 'informational-relevant-details']),
    passageIdentifier: seedTravel.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.prereqCentralIdeaAndImportantDetails,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.prereqCentralIdeaAndImportantDetails[3],
    prompt: 'Select the sentence that gives a relevant detail about water.',
    explanation: 'Sentence 4 tells how water can carry seeds.',
    evidenceReference: seedTravel.sentences[3].sentenceId,
    evidenceReferenceIds: [seedTravel.sentences[3].sentenceId],
    targetVocabulary: ['water', 'carry'],
    soundOutChunks: joinWords('water carry seeds'),
    selectableSegments: [
      { id: 'i1', text: seedTravel.sentences[0].text },
      { id: 'i2', text: seedTravel.sentences[2].text },
      { id: 'i3', text: seedTravel.sentences[3].text },
      { id: 'i4', text: seedTravel.sentences[5].text },
    ],
    correctSegmentIds: ['i3'],
  }),
  createTableMatchQuestion({
    ...informationalFields(RETELL_HALL_QUESTION_IDS.prereqCentralIdeaAndImportantDetails[4], 1, [...RETELL_HALL_INFORMATIONAL_QUESTION_TAGS]),
    passageIdentifier: seedTravel.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.prereqCentralIdeaAndImportantDetails,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.prereqCentralIdeaAndImportantDetails[4],
    prompt: 'Build the retell. Choose one retell piece for each place. Each piece can be used only once. One extra detail does not belong in the retell.',
    explanation: 'The retell starts with the central idea, then uses the three important details. The extra detail stays out.',
    evidenceReference: seedTravel.sentences[0].sentenceId,
    evidenceReferenceIds: seedTravel.sentences.map((sentence) => sentence.sentenceId),
    targetVocabulary: ['central idea', 'relevant details'],
    soundOutChunks: joinWords('one extra detail'),
    selectionMode: 'use_each_once',
    rows: [
      {
        id: 'r1',
        prompt: 'Central idea',
        correctChoiceId: 'seed-piece-1',
        options: [
          choice('seed-piece-1', 'Seeds travel to new places in several ways.'),
          choice('seed-piece-2', 'Some light seeds ride gently on the wind and float far away.'),
          choice('seed-piece-3', 'Tiny hooks cling to animal fur.'),
          choice('seed-piece-4', 'Water can carry seeds along streams and puddles.'),
          choice('seed-extra', 'A gardener may notice a seed packet in a pocket.'),
        ],
      },
      {
        id: 'r2',
        prompt: 'Relevant detail 1',
        correctChoiceId: 'seed-piece-2',
        options: [
          choice('seed-piece-1', 'Seeds travel to new places in several ways.'),
          choice('seed-piece-2', 'Some light seeds ride gently on the wind and float far away.'),
          choice('seed-piece-3', 'Tiny hooks cling to animal fur.'),
          choice('seed-piece-4', 'Water can carry seeds along streams and puddles.'),
          choice('seed-extra', 'A gardener may notice a seed packet in a pocket.'),
        ],
      },
      {
        id: 'r3',
        prompt: 'Relevant detail 2',
        correctChoiceId: 'seed-piece-3',
        options: [
          choice('seed-piece-1', 'Seeds travel to new places in several ways.'),
          choice('seed-piece-2', 'Some light seeds ride gently on the wind and float far away.'),
          choice('seed-piece-3', 'Tiny hooks cling to animal fur.'),
          choice('seed-piece-4', 'Water can carry seeds along streams and puddles.'),
          choice('seed-extra', 'A gardener may notice a seed packet in a pocket.'),
        ],
      },
      {
        id: 'r4',
        prompt: 'Relevant detail 3',
        correctChoiceId: 'seed-piece-4',
        options: [
          choice('seed-piece-1', 'Seeds travel to new places in several ways.'),
          choice('seed-piece-2', 'Some light seeds ride gently on the wind and float far away.'),
          choice('seed-piece-3', 'Tiny hooks cling to animal fur.'),
          choice('seed-piece-4', 'Water can carry seeds along streams and puddles.'),
          choice('seed-extra', 'A gardener may notice a seed packet in a pocket.'),
        ],
      },
    ],
  }),
] as const
