import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
  lessonChoice as choice,
} from './questionFactories'
import { RETELL_HALL_LESSON_IDS, RETELL_HALL_PASSAGE_IDS, RETELL_HALL_QUESTION_IDS } from './ids'
import { getRetellHallPassagePlan } from './passages'
import { buildCommonQuestionFields, joinWords } from './questionsShared'
import { RETELL_HALL_INFORMATIONAL_QUESTION_TAGS, RETELL_HALL_LITERARY_QUESTION_TAGS } from './patterns'

const bridgeRepair = getRetellHallPassagePlan(RETELL_HALL_PASSAGE_IDS.literaryBridgeRepair)
const rainGauge = getRetellHallPassagePlan(RETELL_HALL_PASSAGE_IDS.informationalRainGaugeNotes)

const literaryFields = (questionIdentifier: string, difficulty: 1 | 2, tags: string[]) =>
  buildCommonQuestionFields('literary', tags, difficulty, bridgeRepair.passageId, RETELL_HALL_LESSON_IDS.guidedBuildALiteraryRetell, questionIdentifier)

const informationalFields = (questionIdentifier: string, difficulty: 1 | 2, tags: string[]) =>
  buildCommonQuestionFields('informational', tags, difficulty, rainGauge.passageId, RETELL_HALL_LESSON_IDS.guidedBuildAnInformationalRetell, questionIdentifier)

export const retellHallGuidedQuestions = [
  createMultipleChoiceQuestion({
    ...literaryFields(RETELL_HALL_QUESTION_IDS.guidedBuildALiteraryRetell[0], 2, ['literary-retell', 'literary-problem']),
    passageIdentifier: bridgeRepair.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.guidedBuildALiteraryRetell,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.guidedBuildALiteraryRetell[0],
    prompt: 'Which sentence shows the problem?',
    explanation: 'Sentence 2 says the bridge wobbled when the truck rolled across it.',
    evidenceReference: bridgeRepair.sentences[1].sentenceId,
    evidenceReferenceIds: [bridgeRepair.sentences[1].sentenceId],
    targetVocabulary: ['problem', 'wobbled'],
    soundOutChunks: joinWords('bridge wobbled truck'),
    choices: [
      choice('b1', bridgeRepair.sentences[0].text),
      choice('b2', bridgeRepair.sentences[1].text),
      choice('b3', bridgeRepair.sentences[4].text),
      choice('b4', bridgeRepair.sentences[7].text),
    ],
    correctChoiceIds: ['b2'],
  }),
  createMultipleChoiceQuestion({
    ...literaryFields(RETELL_HALL_QUESTION_IDS.guidedBuildALiteraryRetell[1], 2, ['literary-retell', 'literary-important-events']),
    passageIdentifier: bridgeRepair.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.guidedBuildALiteraryRetell,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.guidedBuildALiteraryRetell[1],
    prompt: 'What did Jada add to help the bridge?',
    explanation: 'Jada added a support beam to make the bridge stronger.',
    evidenceReference: bridgeRepair.sentences[2].sentenceId,
    evidenceReferenceIds: [bridgeRepair.sentences[2].sentenceId],
    targetVocabulary: ['support beam'],
    soundOutChunks: joinWords('support beam'),
    choices: [
      choice('b1', 'a blue mat'),
      choice('b2', 'a support beam'),
      choice('b3', 'a pencil'),
      choice('b4', 'a notebook'),
    ],
    correctChoiceIds: ['b2'],
  }),
  createMultiselectQuestion({
    ...literaryFields(RETELL_HALL_QUESTION_IDS.guidedBuildALiteraryRetell[2], 2, ['literary-retell', 'literary-important-events', 'literary-logical-sequence']),
    passageIdentifier: bridgeRepair.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.guidedBuildALiteraryRetell,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.guidedBuildALiteraryRetell[2],
    prompt: 'Choose two details that show the bridge got stronger.',
    explanation: 'The support beam and the connected strip both help the model bridge grow stronger.',
    evidenceReference: bridgeRepair.sentences[4].sentenceId,
    evidenceReferenceIds: [bridgeRepair.sentences[2].sentenceId, bridgeRepair.sentences[4].sentenceId],
    targetVocabulary: ['stronger', 'connected'],
    soundOutChunks: joinWords('support connected'),
    choices: [
      choice('b1', 'The toy truck rolled across it.'),
      choice('b2', 'Jada added a support beam.'),
      choice('b3', 'The bridge grew stronger after they connected the last cardboard strip.'),
      choice('b4', 'A pencil rolled off the table.'),
    ],
    correctChoiceIds: ['b2', 'b3'],
  }),
  createHotTextQuestion({
    ...literaryFields(RETELL_HALL_QUESTION_IDS.guidedBuildALiteraryRetell[3], 2, ['literary-retell', 'literary-resolution', 'literary-retell-completeness']),
    passageIdentifier: bridgeRepair.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.guidedBuildALiteraryRetell,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.guidedBuildALiteraryRetell[3],
    prompt: 'Select the sentence that shows the ending.',
    explanation: 'Sentence 8 shows that the model bridge is ready for the class display.',
    evidenceReference: bridgeRepair.sentences[7].sentenceId,
    evidenceReferenceIds: [bridgeRepair.sentences[7].sentenceId],
    targetVocabulary: ['ending', 'ready'],
    soundOutChunks: joinWords('class display'),
    selectableSegments: [
      { id: 'b1', text: bridgeRepair.sentences[1].text },
      { id: 'b2', text: bridgeRepair.sentences[4].text },
      { id: 'b3', text: bridgeRepair.sentences[6].text },
      { id: 'b4', text: bridgeRepair.sentences[7].text },
    ],
    correctSegmentIds: ['b4'],
  }),
  createTableMatchQuestion({
    ...literaryFields(RETELL_HALL_QUESTION_IDS.guidedBuildALiteraryRetell[4], 2, [...RETELL_HALL_LITERARY_QUESTION_TAGS]),
    passageIdentifier: bridgeRepair.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.guidedBuildALiteraryRetell,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.guidedBuildALiteraryRetell[4],
    prompt: 'Build the retell. Choose one retell piece for each place. Each piece can be used only once. One extra detail does not belong in the retell.',
    explanation: 'The retell begins with the setting and problem, then tells two important events, and ends with the finished bridge.',
    evidenceReference: bridgeRepair.sentences[0].sentenceId,
    evidenceReferenceIds: bridgeRepair.sentences.map((sentence) => sentence.sentenceId),
    targetVocabulary: ['setting', 'problem', 'ending'],
    soundOutChunks: joinWords('one extra detail'),
    selectionMode: 'use_each_once',
    rows: [
      {
        id: 'r1',
        prompt: 'Opening',
        correctChoiceId: 'bridge-piece-1',
        options: [
          choice('bridge-piece-1', 'Jada and Omar test the model bridge in the science corner.'),
          choice('bridge-piece-2', 'The bridge wobbles when the toy truck rolls across it.'),
          choice('bridge-piece-3', 'Jada adds a support beam and Omar holds the pieces steady.'),
          choice('bridge-piece-4', 'The friends work carefully and connect the last cardboard strip.'),
          choice('bridge-piece-5', 'Soon, the truck crosses the bridge without a shake, and the model is ready for the class display.'),
          choice('bridge-extra', 'A pencil rolled off the table.'),
        ],
      },
      {
        id: 'r2',
        prompt: 'Problem',
        correctChoiceId: 'bridge-piece-2',
        options: [
          choice('bridge-piece-1', 'Jada and Omar test the model bridge in the science corner.'),
          choice('bridge-piece-2', 'The bridge wobbles when the toy truck rolls across it.'),
          choice('bridge-piece-3', 'Jada adds a support beam and Omar holds the pieces steady.'),
          choice('bridge-piece-4', 'The friends work carefully and connect the last cardboard strip.'),
          choice('bridge-piece-5', 'Soon, the truck crosses the bridge without a shake, and the model is ready for the class display.'),
          choice('bridge-extra', 'A pencil rolled off the table.'),
        ],
      },
      {
        id: 'r3',
        prompt: 'Important event 1',
        correctChoiceId: 'bridge-piece-3',
        options: [
          choice('bridge-piece-1', 'Jada and Omar test the model bridge in the science corner.'),
          choice('bridge-piece-2', 'The bridge wobbles when the toy truck rolls across it.'),
          choice('bridge-piece-3', 'Jada adds a support beam and Omar holds the pieces steady.'),
          choice('bridge-piece-4', 'The friends work carefully and connect the last cardboard strip.'),
          choice('bridge-piece-5', 'Soon, the truck crosses the bridge without a shake, and the model is ready for the class display.'),
          choice('bridge-extra', 'A pencil rolled off the table.'),
        ],
      },
      {
        id: 'r4',
        prompt: 'Important event 2',
        correctChoiceId: 'bridge-piece-4',
        options: [
          choice('bridge-piece-1', 'Jada and Omar test the model bridge in the science corner.'),
          choice('bridge-piece-2', 'The bridge wobbles when the toy truck rolls across it.'),
          choice('bridge-piece-3', 'Jada adds a support beam and Omar holds the pieces steady.'),
          choice('bridge-piece-4', 'The friends work carefully and connect the last cardboard strip.'),
          choice('bridge-piece-5', 'Soon, the truck crosses the bridge without a shake, and the model is ready for the class display.'),
          choice('bridge-extra', 'A pencil rolled off the table.'),
        ],
      },
      {
        id: 'r5',
        prompt: 'Ending',
        correctChoiceId: 'bridge-piece-5',
        options: [
          choice('bridge-piece-1', 'Jada and Omar test the model bridge in the science corner.'),
          choice('bridge-piece-2', 'The bridge wobbles when the toy truck rolls across it.'),
          choice('bridge-piece-3', 'Jada adds a support beam and Omar holds the pieces steady.'),
          choice('bridge-piece-4', 'The friends work carefully and connect the last cardboard strip.'),
          choice('bridge-piece-5', 'Soon, the truck crosses the bridge without a shake, and the model is ready for the class display.'),
          choice('bridge-extra', 'A pencil rolled off the table.'),
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...informationalFields(RETELL_HALL_QUESTION_IDS.guidedBuildAnInformationalRetell[0], 2, ['informational-retell', 'informational-central-idea']),
    passageIdentifier: rainGauge.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.guidedBuildAnInformationalRetell,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.guidedBuildAnInformationalRetell[0],
    prompt: 'What is the central idea of this passage?',
    explanation: 'The passage explains that a rain gauge helps people measure how much rain falls.',
    evidenceReference: rainGauge.sentences[0].sentenceId,
    evidenceReferenceIds: [rainGauge.sentences[0].sentenceId],
    targetVocabulary: ['central idea', 'measure'],
    soundOutChunks: joinWords('rain gauge measure'),
    choices: [
      choice('r1', 'A rain gauge helps people measure how much rain falls.'),
      choice('r2', 'A flower bed is the best place for a garden.'),
      choice('r3', 'The cup catches drops one after another.'),
      choice('r4', 'Marked lines show the amount.'),
    ],
    correctChoiceIds: ['r1'],
  }),
  createMultipleChoiceQuestion({
    ...informationalFields(RETELL_HALL_QUESTION_IDS.guidedBuildAnInformationalRetell[1], 2, ['informational-retell', 'informational-relevant-details']),
    passageIdentifier: rainGauge.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.guidedBuildAnInformationalRetell,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.guidedBuildAnInformationalRetell[1],
    prompt: 'Which detail is most relevant?',
    explanation: 'The marked lines show the amount of rain that fell, which helps explain how the gauge works.',
    evidenceReference: rainGauge.sentences[2].sentenceId,
    evidenceReferenceIds: [rainGauge.sentences[2].sentenceId],
    targetVocabulary: ['relevant', 'amount'],
    soundOutChunks: joinWords('marked lines amount'),
    choices: [
      choice('r1', 'The gauge may stand beside a flower bed.'),
      choice('r2', 'A notebook records the reading after the storm.'),
      choice('r3', 'Marked lines show the amount.'),
      choice('r4', 'The cup catches drops one after another.'),
    ],
    correctChoiceIds: ['r3'],
  }),
  createMultiselectQuestion({
    ...informationalFields(RETELL_HALL_QUESTION_IDS.guidedBuildAnInformationalRetell[2], 2, ['informational-retell', 'informational-relevant-details', 'informational-details-across-sections']),
    passageIdentifier: rainGauge.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.guidedBuildAnInformationalRetell,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.guidedBuildAnInformationalRetell[2],
    prompt: 'Choose two details that belong in the retell.',
    explanation: 'The cup and the notebook both help explain how the gauge works and why people read it.',
    evidenceReference: rainGauge.sentences[1].sentenceId,
    evidenceReferenceIds: [rainGauge.sentences[1].sentenceId, rainGauge.sentences[3].sentenceId],
    targetVocabulary: ['details', 'read'],
    soundOutChunks: joinWords('cup notebook'),
    choices: [
      choice('r1', 'The gauge may stand beside a flower bed.'),
      choice('r2', 'The cup catches drops one after another.'),
      choice('r3', 'A notebook records the reading after the storm.'),
      choice('r4', 'The number helps people compare one storm with another.'),
    ],
    correctChoiceIds: ['r2', 'r3'],
  }),
  createHotTextQuestion({
    ...informationalFields(RETELL_HALL_QUESTION_IDS.guidedBuildAnInformationalRetell[3], 2, ['informational-retell', 'informational-central-idea', 'informational-relevant-details']),
    passageIdentifier: rainGauge.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.guidedBuildAnInformationalRetell,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.guidedBuildAnInformationalRetell[3],
    prompt: 'Select the sentence that tells what the rain gauge does.',
    explanation: 'Sentence 1 tells that the rain gauge helps people measure rain.',
    evidenceReference: rainGauge.sentences[0].sentenceId,
    evidenceReferenceIds: [rainGauge.sentences[0].sentenceId],
    targetVocabulary: ['measure', 'rain gauge'],
    soundOutChunks: joinWords('rain gauge measure'),
    selectableSegments: [
      { id: 'r1', text: rainGauge.sentences[1].text },
      { id: 'r2', text: rainGauge.sentences[0].text },
      { id: 'r3', text: rainGauge.sentences[4].text },
      { id: 'r4', text: rainGauge.sentences[5].text },
    ],
    correctSegmentIds: ['r2'],
  }),
  createTableMatchQuestion({
    ...informationalFields(RETELL_HALL_QUESTION_IDS.guidedBuildAnInformationalRetell[4], 2, [...RETELL_HALL_INFORMATIONAL_QUESTION_TAGS]),
    passageIdentifier: rainGauge.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.guidedBuildAnInformationalRetell,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.guidedBuildAnInformationalRetell[4],
    prompt: 'Build the retell. Choose one retell piece for each place. Each piece can be used only once. One extra detail does not belong in the retell.',
    explanation: 'The retell starts with the central idea, then uses the three most relevant details. The extra detail stays out.',
    evidenceReference: rainGauge.sentences[0].sentenceId,
    evidenceReferenceIds: rainGauge.sentences.map((sentence) => sentence.sentenceId),
    targetVocabulary: ['central idea', 'relevant details'],
    soundOutChunks: joinWords('one extra detail'),
    selectionMode: 'use_each_once',
    rows: [
      {
        id: 'r1',
        prompt: 'Central idea',
        correctChoiceId: 'rain-piece-1',
        options: [
          choice('rain-piece-1', 'A rain gauge helps people measure how much rain falls.'),
          choice('rain-piece-2', 'The cup catches drops one after another.'),
          choice('rain-piece-3', 'Marked lines show the amount.'),
          choice('rain-piece-4', 'A notebook records the reading after the storm.'),
          choice('rain-extra', 'The gauge may stand beside a flower bed.'),
        ],
      },
      {
        id: 'r2',
        prompt: 'Relevant detail 1',
        correctChoiceId: 'rain-piece-2',
        options: [
          choice('rain-piece-1', 'A rain gauge helps people measure how much rain falls.'),
          choice('rain-piece-2', 'The cup catches drops one after another.'),
          choice('rain-piece-3', 'Marked lines show the amount.'),
          choice('rain-piece-4', 'A notebook records the reading after the storm.'),
          choice('rain-extra', 'The gauge may stand beside a flower bed.'),
        ],
      },
      {
        id: 'r3',
        prompt: 'Relevant detail 2',
        correctChoiceId: 'rain-piece-3',
        options: [
          choice('rain-piece-1', 'A rain gauge helps people measure how much rain falls.'),
          choice('rain-piece-2', 'The cup catches drops one after another.'),
          choice('rain-piece-3', 'Marked lines show the amount.'),
          choice('rain-piece-4', 'A notebook records the reading after the storm.'),
          choice('rain-extra', 'The gauge may stand beside a flower bed.'),
        ],
      },
      {
        id: 'r4',
        prompt: 'Relevant detail 3',
        correctChoiceId: 'rain-piece-4',
        options: [
          choice('rain-piece-1', 'A rain gauge helps people measure how much rain falls.'),
          choice('rain-piece-2', 'The cup catches drops one after another.'),
          choice('rain-piece-3', 'Marked lines show the amount.'),
          choice('rain-piece-4', 'A notebook records the reading after the storm.'),
          choice('rain-extra', 'The gauge may stand beside a flower bed.'),
        ],
      },
    ],
  }),
] as const
