import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
  createTwoPartQuestion,
  lessonChoice as choice,
} from './questionFactories'
import { RETELL_HALL_LESSON_IDS, RETELL_HALL_PASSAGE_IDS, RETELL_HALL_QUESTION_IDS } from './ids'
import { getRetellHallPassagePlan } from './passages'
import { buildCommonQuestionFields, joinWords } from './questionsShared'
import { RETELL_HALL_INFORMATIONAL_QUESTION_TAGS, RETELL_HALL_LITERARY_QUESTION_TAGS } from './patterns'

const RETELL_HALL_CHECKPOINT_TAGS = [
  ...RETELL_HALL_LITERARY_QUESTION_TAGS,
  ...RETELL_HALL_INFORMATIONAL_QUESTION_TAGS,
]

const libraryStoryNight = getRetellHallPassagePlan(RETELL_HALL_PASSAGE_IDS.literaryLibraryStoryNight)
const birdLayers = getRetellHallPassagePlan(RETELL_HALL_PASSAGE_IDS.informationalBirdLayers)
const mapCardSearch = getRetellHallPassagePlan(RETELL_HALL_PASSAGE_IDS.literaryMapCardSearch)

const literaryCheckpointAFields = (questionIdentifier: string, tags: string[]) =>
  buildCommonQuestionFields('literary', [...tags, ...RETELL_HALL_CHECKPOINT_TAGS], 2, libraryStoryNight.passageId, RETELL_HALL_LESSON_IDS.checkpointLiteraryA, questionIdentifier)

const informationalCheckpointFields = (questionIdentifier: string, tags: string[]) =>
  buildCommonQuestionFields('informational', [...tags, ...RETELL_HALL_CHECKPOINT_TAGS], 2, birdLayers.passageId, RETELL_HALL_LESSON_IDS.checkpointInformational, questionIdentifier)

const literaryCheckpointBFields = (questionIdentifier: string, tags: string[]) =>
  buildCommonQuestionFields('literary', [...tags, ...RETELL_HALL_CHECKPOINT_TAGS], 2, mapCardSearch.passageId, RETELL_HALL_LESSON_IDS.checkpointLiteraryB, questionIdentifier)

export const retellHallCheckpointQuestions = [
  createMultipleChoiceQuestion({
    ...literaryCheckpointAFields(RETELL_HALL_QUESTION_IDS.checkpointLiteraryA[0], ['literary-retell', 'literary-main-characters', 'literary-setting']),
    passageIdentifier: libraryStoryNight.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointLiteraryA,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointLiteraryA[0],
    prompt: 'Which sentence tells the setting?',
    explanation: 'Sentence 1 names the library hall where the story-night table is set up.',
    evidenceReference: libraryStoryNight.sentences[0].sentenceId,
    evidenceReferenceIds: [libraryStoryNight.sentences[0].sentenceId],
    targetVocabulary: ['setting', 'hall'],
    soundOutChunks: joinWords('library hall'),
    choices: [
      choice('a1', libraryStoryNight.sentences[4].text),
      choice('a2', libraryStoryNight.sentences[0].text),
      choice('a3', libraryStoryNight.sentences[7].text),
      choice('a4', libraryStoryNight.sentences[5].text),
    ],
    correctChoiceIds: ['a2'],
  }),
  createMultipleChoiceQuestion({
    ...literaryCheckpointAFields(RETELL_HALL_QUESTION_IDS.checkpointLiteraryA[1], ['literary-retell', 'literary-problem']),
    passageIdentifier: libraryStoryNight.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointLiteraryA,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointLiteraryA[1],
    prompt: 'What is the main problem?',
    explanation: 'The poster needs to stay up before the families arrive.',
    evidenceReference: libraryStoryNight.sentences[1].sentenceId,
    evidenceReferenceIds: [libraryStoryNight.sentences[1].sentenceId],
    targetVocabulary: ['problem', 'poster'],
    soundOutChunks: joinWords('stay families arrive'),
    choices: [
      choice('a1', 'The poster needs to stay up before the families arrive.'),
      choice('a2', 'The basket of stickers sat nearby.'),
      choice('a3', 'The story-night sign looked bright.'),
      choice('a4', 'A clock ticked softly above the shelves.'),
    ],
    correctChoiceIds: ['a1'],
  }),
  createMultipleChoiceQuestion({
    ...literaryCheckpointAFields(RETELL_HALL_QUESTION_IDS.checkpointLiteraryA[2], ['literary-retell', 'literary-important-events', 'literary-logical-sequence']),
    passageIdentifier: libraryStoryNight.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointLiteraryA,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointLiteraryA[2],
    prompt: 'Which event happens after the poster curls?',
    explanation: 'After the poster curls, Noa presses it flat and Priya finds the tape roll.',
    evidenceReference: libraryStoryNight.sentences[3].sentenceId,
    evidenceReferenceIds: [libraryStoryNight.sentences[2].sentenceId, libraryStoryNight.sentences[3].sentenceId],
    targetVocabulary: ['event', 'curl'],
    soundOutChunks: joinWords('press tape roll'),
    choices: [
      choice('a1', 'A basket of stickers sat nearby.'),
      choice('a2', 'Noa presses it flat while Priya finds the tape roll.'),
      choice('a3', 'The story-night sign looked bright.'),
      choice('a4', 'The children smiled when the first visitors walked in.'),
    ],
    correctChoiceIds: ['a2'],
  }),
  createMultiselectQuestion({
    ...literaryCheckpointAFields(RETELL_HALL_QUESTION_IDS.checkpointLiteraryA[3], ['literary-retell', 'literary-important-events', 'literary-logical-sequence']),
    passageIdentifier: libraryStoryNight.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointLiteraryA,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointLiteraryA[3],
    prompt: 'Choose two important details that belong in the retell.',
    explanation: 'The lights and the chair backs help the story-night setup move toward the ending.',
    evidenceReference: libraryStoryNight.sentences[6].sentenceId,
    evidenceReferenceIds: [libraryStoryNight.sentences[3].sentenceId, libraryStoryNight.sentences[6].sentenceId],
    targetVocabulary: ['important', 'details'],
    soundOutChunks: joinWords('lights chairs'),
    choices: [
      choice('a1', 'The basket of stickers sat nearby.'),
      choice('a2', 'The friends arranged the name cards in an organized row.'),
      choice('a3', 'They checked the lights and moved the chair backs into a straight line.'),
      choice('a4', 'A clock ticked softly above the shelves.'),
    ],
    correctChoiceIds: ['a2', 'a3'],
  }),
  createHotTextQuestion({
    ...literaryCheckpointAFields(RETELL_HALL_QUESTION_IDS.checkpointLiteraryA[4], ['literary-retell', 'literary-resolution', 'literary-retell-completeness']),
    passageIdentifier: libraryStoryNight.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointLiteraryA,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointLiteraryA[4],
    prompt: 'Select the sentence that shows the ending.',
    explanation: 'Sentence 8 shows the poster finished and hanging neatly.',
    evidenceReference: libraryStoryNight.sentences[7].sentenceId,
    evidenceReferenceIds: [libraryStoryNight.sentences[7].sentenceId],
    targetVocabulary: ['ending', 'visitors'],
    soundOutChunks: joinWords('poster visitors'),
    selectableSegments: [
      { id: 'a1', text: libraryStoryNight.sentences[1].text },
      { id: 'a2', text: libraryStoryNight.sentences[4].text },
      { id: 'a3', text: libraryStoryNight.sentences[7].text },
      { id: 'a4', text: libraryStoryNight.sentences[9].text },
    ],
    correctSegmentIds: ['a3'],
  }),
  createTableMatchQuestion({
    ...literaryCheckpointAFields(RETELL_HALL_QUESTION_IDS.checkpointLiteraryA[5], [...RETELL_HALL_LITERARY_QUESTION_TAGS]),
    passageIdentifier: libraryStoryNight.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointLiteraryA,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointLiteraryA[5],
    prompt: 'Build the retell. Choose one retell piece for each place. Each piece can be used only once. One extra detail does not belong in the retell.',
    explanation: 'The pieces should follow the opening, problem, important events, and ending. The extra detail stays out.',
    evidenceReference: libraryStoryNight.sentences[0].sentenceId,
    evidenceReferenceIds: libraryStoryNight.sentences.map((sentence) => sentence.sentenceId),
    targetVocabulary: ['opening', 'ending'],
    soundOutChunks: joinWords('one extra detail'),
    selectionMode: 'use_each_once',
    rows: [
      {
        id: 'r1',
        prompt: 'Opening',
        correctChoiceId: 'library-piece-1',
        options: [
          choice('library-piece-1', 'Noa and Priya set up the story-night table in the library hall.'),
          choice('library-piece-2', 'The story-night poster needs to stay up before the families arrive.'),
          choice('library-piece-3', 'One corner of the poster curls like a ribbon in a breeze.'),
          choice('library-piece-4', 'Noa presses the poster flat while Priya finds the tape roll and arranges the name cards in an organized row.'),
          choice('library-piece-5', 'At last, the poster hangs neatly, and the story-night sign looks bright when the first visitors walk in.'),
          choice('library-extra', 'A basket of stickers sat nearby.'),
        ],
      },
      {
        id: 'r2',
        prompt: 'Problem',
        correctChoiceId: 'library-piece-2',
        options: [
          choice('library-piece-1', 'Noa and Priya set up the story-night table in the library hall.'),
          choice('library-piece-2', 'The story-night poster needs to stay up before the families arrive.'),
          choice('library-piece-3', 'One corner of the poster curls like a ribbon in a breeze.'),
          choice('library-piece-4', 'Noa presses the poster flat while Priya finds the tape roll and arranges the name cards in an organized row.'),
          choice('library-piece-5', 'At last, the poster hangs neatly, and the story-night sign looks bright when the first visitors walk in.'),
          choice('library-extra', 'A basket of stickers sat nearby.'),
        ],
      },
      {
        id: 'r3',
        prompt: 'Important event 1',
        correctChoiceId: 'library-piece-3',
        options: [
          choice('library-piece-1', 'Noa and Priya set up the story-night table in the library hall.'),
          choice('library-piece-2', 'The story-night poster needs to stay up before the families arrive.'),
          choice('library-piece-3', 'One corner of the poster curls like a ribbon in a breeze.'),
          choice('library-piece-4', 'Noa presses the poster flat while Priya finds the tape roll and arranges the name cards in an organized row.'),
          choice('library-piece-5', 'At last, the poster hangs neatly, and the story-night sign looks bright when the first visitors walk in.'),
          choice('library-extra', 'A basket of stickers sat nearby.'),
        ],
      },
      {
        id: 'r4',
        prompt: 'Important event 2',
        correctChoiceId: 'library-piece-4',
        options: [
          choice('library-piece-1', 'Noa and Priya set up the story-night table in the library hall.'),
          choice('library-piece-2', 'The story-night poster needs to stay up before the families arrive.'),
          choice('library-piece-3', 'One corner of the poster curls like a ribbon in a breeze.'),
          choice('library-piece-4', 'Noa presses the poster flat while Priya finds the tape roll and arranges the name cards in an organized row.'),
          choice('library-piece-5', 'At last, the poster hangs neatly, and the story-night sign looks bright when the first visitors walk in.'),
          choice('library-extra', 'A basket of stickers sat nearby.'),
        ],
      },
      {
        id: 'r5',
        prompt: 'Ending',
        correctChoiceId: 'library-piece-5',
        options: [
          choice('library-piece-1', 'Noa and Priya set up the story-night table in the library hall.'),
          choice('library-piece-2', 'The story-night poster needs to stay up before the families arrive.'),
          choice('library-piece-3', 'One corner of the poster curls like a ribbon in a breeze.'),
          choice('library-piece-4', 'Noa presses the poster flat while Priya finds the tape roll and arranges the name cards in an organized row.'),
          choice('library-piece-5', 'At last, the poster hangs neatly, and the story-night sign looks bright when the first visitors walk in.'),
          choice('library-extra', 'A basket of stickers sat nearby.'),
        ],
      },
    ],
  }),
  createTwoPartQuestion({
    ...literaryCheckpointAFields(RETELL_HALL_QUESTION_IDS.checkpointLiteraryA[6], ['literary-retell', 'retell-important-vs-minor']),
    passageIdentifier: libraryStoryNight.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointLiteraryA,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointLiteraryA[6],
    prompt: 'Which detail is minor and should be left out?',
    explanation: 'The basket of stickers is true, but it does not change the main story of the poster getting ready.',
    evidenceReference: libraryStoryNight.sentences[5].sentenceId,
    evidenceReferenceIds: [libraryStoryNight.sentences[5].sentenceId, libraryStoryNight.sentences[7].sentenceId],
    targetVocabulary: ['minor', 'detail'],
    soundOutChunks: joinWords('basket stickers'),
    partAPrompt: 'Which detail is minor and should be left out?',
    partAChoices: [
      choice('a1', 'The basket of stickers sat nearby.'),
      choice('a2', 'The poster needs to stay up before the families arrive.'),
      choice('a3', 'Noa presses the poster flat.'),
      choice('a4', 'The story-night sign looks bright.'),
    ],
    partACorrectChoiceId: 'a1',
    partBPrompt: 'Why should it be left out?',
    partBChoices: [
      choice('b1', 'It does not change the main story.'),
      choice('b2', 'It is the central idea.'),
      choice('b3', 'It is the first event.'),
      choice('b4', 'It tells the setting.'),
    ],
    partBCorrectChoiceId: 'b1',
  }),
  createMultipleChoiceQuestion({
    ...informationalCheckpointFields(RETELL_HALL_QUESTION_IDS.checkpointInformational[0], ['informational-retell', 'informational-central-idea']),
    passageIdentifier: birdLayers.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointInformational,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointInformational[0],
    prompt: 'What is the central idea?',
    explanation: 'The passage says birds use different layers of a habitat for food and shelter.',
    evidenceReference: birdLayers.sentences[0].sentenceId,
    evidenceReferenceIds: [birdLayers.sentences[0].sentenceId],
    targetVocabulary: ['central idea', 'habitat'],
    soundOutChunks: joinWords('layers habitat shelter'),
    choices: [
      choice('i1', 'Birds only live on the ground.'),
      choice('i2', 'Birds use different layers of a habitat for food and shelter.'),
      choice('i3', 'A path marker stands near the trail.'),
      choice('i4', 'Birds always search for insects in shrubs.'),
    ],
    correctChoiceIds: ['i2'],
  }),
  createMultipleChoiceQuestion({
    ...informationalCheckpointFields(RETELL_HALL_QUESTION_IDS.checkpointInformational[1], ['informational-retell', 'informational-relevant-details']),
    passageIdentifier: birdLayers.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointInformational,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointInformational[1],
    prompt: 'Which detail is most relevant to the central idea?',
    explanation: 'The sentence about the top layer explains one place birds rest for shelter.',
    evidenceReference: birdLayers.sentences[1].sentenceId,
    evidenceReferenceIds: [birdLayers.sentences[1].sentenceId],
    targetVocabulary: ['relevant', 'layer'],
    soundOutChunks: joinWords('top layer branches'),
    choices: [
      choice('i1', 'A path marker stands near the trail.'),
      choice('i2', 'On the ground, some birds search for seeds and crumbs.'),
      choice('i3', 'In the top layer, some birds rest high in the branches.'),
      choice('i4', 'The passage has three sections.'),
    ],
    correctChoiceIds: ['i3'],
  }),
  createMultipleChoiceQuestion({
    ...informationalCheckpointFields(RETELL_HALL_QUESTION_IDS.checkpointInformational[2], ['informational-retell', 'informational-relevant-details', 'informational-details-across-sections']),
    passageIdentifier: birdLayers.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointInformational,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointInformational[2],
    prompt: 'Which sentence is a less relevant true detail?',
    explanation: 'The path marker is true, but it does not tell how birds use the habitat layers.',
    evidenceReference: birdLayers.sentences[4].sentenceId,
    evidenceReferenceIds: [birdLayers.sentences[4].sentenceId],
    targetVocabulary: ['less relevant', 'detail'],
    soundOutChunks: joinWords('path marker trail'),
    choices: [
      choice('i1', 'A path marker stands near the trail, but it is only a small extra detail.'),
      choice('i2', 'Birds use different layers of a habitat for food and shelter.'),
      choice('i3', 'In the middle layer, others hide in shrubs and look for insects.'),
      choice('i4', 'On the ground, some birds search for seeds and crumbs.'),
    ],
    correctChoiceIds: ['i1'],
  }),
  createMultiselectQuestion({
    ...informationalCheckpointFields(RETELL_HALL_QUESTION_IDS.checkpointInformational[3], ['informational-retell', 'informational-relevant-details', 'informational-details-across-sections']),
    passageIdentifier: birdLayers.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointInformational,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointInformational[3],
    prompt: 'Choose three details that belong in the retell.',
    explanation: 'The top layer, middle layer, and ground layer details all belong in the retell.',
    evidenceReference: birdLayers.sentences[0].sentenceId,
    evidenceReferenceIds: [birdLayers.sentences[1].sentenceId, birdLayers.sentences[2].sentenceId, birdLayers.sentences[3].sentenceId],
    targetVocabulary: ['details', 'layers'],
    soundOutChunks: joinWords('top middle ground'),
    choices: [
      choice('i1', 'In the top layer, some birds rest high in the branches.'),
      choice('i2', 'In the middle layer, others hide in shrubs and look for insects.'),
      choice('i3', 'On the ground, some birds search for seeds and crumbs.'),
      choice('i4', 'A path marker stands near the trail.'),
    ],
    correctChoiceIds: ['i1', 'i2', 'i3'],
  }),
  createHotTextQuestion({
    ...informationalCheckpointFields(RETELL_HALL_QUESTION_IDS.checkpointInformational[4], ['informational-retell', 'informational-relevant-details', 'informational-central-idea']),
    passageIdentifier: birdLayers.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointInformational,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointInformational[4],
    prompt: 'Select the sentence that gives a relevant detail from the middle section.',
    explanation: 'Sentence 3 says that some birds hide in shrubs and look for insects.',
    evidenceReference: birdLayers.sentences[2].sentenceId,
    evidenceReferenceIds: [birdLayers.sentences[2].sentenceId],
    targetVocabulary: ['relevant', 'middle'],
    soundOutChunks: joinWords('middle shrubs insects'),
    selectableSegments: [
      { id: 'i1', text: birdLayers.sentences[0].text },
      { id: 'i2', text: birdLayers.sentences[2].text },
      { id: 'i3', text: birdLayers.sentences[4].text },
      { id: 'i4', text: birdLayers.sentences[5].text },
    ],
    correctSegmentIds: ['i2'],
  }),
  createTableMatchQuestion({
    ...informationalCheckpointFields(RETELL_HALL_QUESTION_IDS.checkpointInformational[5], [...RETELL_HALL_INFORMATIONAL_QUESTION_TAGS]),
    passageIdentifier: birdLayers.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointInformational,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointInformational[5],
    prompt: 'Build the retell. Choose one retell piece for each place. Each piece can be used only once. One extra detail does not belong in the retell.',
    explanation: 'The retell starts with the central idea and then uses the three important details from the habitat layers.',
    evidenceReference: birdLayers.sentences[0].sentenceId,
    evidenceReferenceIds: birdLayers.sentences.map((sentence) => sentence.sentenceId),
    targetVocabulary: ['central idea', 'habitat layers'],
    soundOutChunks: joinWords('one extra detail'),
    selectionMode: 'use_each_once',
    rows: [
      {
        id: 'r1',
        prompt: 'Central idea',
        correctChoiceId: 'bird-piece-1',
        options: [
          choice('bird-piece-1', 'Birds use different layers of a habitat for food and shelter.'),
          choice('bird-piece-2', 'In the top layer, some birds rest high in the branches.'),
          choice('bird-piece-3', 'In the middle layer, others hide in shrubs and look for insects.'),
          choice('bird-piece-4', 'On the ground, some birds search for seeds and crumbs.'),
          choice('bird-extra', 'A path marker stands near the trail.'),
        ],
      },
      {
        id: 'r2',
        prompt: 'Relevant detail 1',
        correctChoiceId: 'bird-piece-2',
        options: [
          choice('bird-piece-1', 'Birds use different layers of a habitat for food and shelter.'),
          choice('bird-piece-2', 'In the top layer, some birds rest high in the branches.'),
          choice('bird-piece-3', 'In the middle layer, others hide in shrubs and look for insects.'),
          choice('bird-piece-4', 'On the ground, some birds search for seeds and crumbs.'),
          choice('bird-extra', 'A path marker stands near the trail.'),
        ],
      },
      {
        id: 'r3',
        prompt: 'Relevant detail 2',
        correctChoiceId: 'bird-piece-3',
        options: [
          choice('bird-piece-1', 'Birds use different layers of a habitat for food and shelter.'),
          choice('bird-piece-2', 'In the top layer, some birds rest high in the branches.'),
          choice('bird-piece-3', 'In the middle layer, others hide in shrubs and look for insects.'),
          choice('bird-piece-4', 'On the ground, some birds search for seeds and crumbs.'),
          choice('bird-extra', 'A path marker stands near the trail.'),
        ],
      },
      {
        id: 'r4',
        prompt: 'Relevant detail 3',
        correctChoiceId: 'bird-piece-4',
        options: [
          choice('bird-piece-1', 'Birds use different layers of a habitat for food and shelter.'),
          choice('bird-piece-2', 'In the top layer, some birds rest high in the branches.'),
          choice('bird-piece-3', 'In the middle layer, others hide in shrubs and look for insects.'),
          choice('bird-piece-4', 'On the ground, some birds search for seeds and crumbs.'),
          choice('bird-extra', 'A path marker stands near the trail.'),
        ],
      },
    ],
  }),
  createTwoPartQuestion({
    ...informationalCheckpointFields(RETELL_HALL_QUESTION_IDS.checkpointInformational[6], ['informational-retell', 'informational-central-idea', 'informational-relevant-details']),
    passageIdentifier: birdLayers.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointInformational,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointInformational[6],
    prompt: 'What is the central idea and which detail belongs in the retell?',
    explanation: 'The central idea names the habitat layers, and the top-layer sentence is one of the important details.',
    evidenceReference: birdLayers.sentences[0].sentenceId,
    evidenceReferenceIds: [birdLayers.sentences[0].sentenceId, birdLayers.sentences[1].sentenceId],
    targetVocabulary: ['central idea', 'detail'],
    soundOutChunks: joinWords('layers shelter'),
    partAPrompt: 'Part A: What is the central idea?',
    partAChoices: [
      choice('a1', 'Birds use different layers of a habitat for food and shelter.'),
      choice('a2', 'A path marker stands near the trail.'),
      choice('a3', 'Birds always stay in the top layer.'),
      choice('a4', 'The ground is the only place birds live.'),
    ],
    partACorrectChoiceId: 'a1',
    partBPrompt: 'Part B: Which detail belongs in the retell?',
    partBChoices: [
      choice('b1', 'A path marker stands near the trail.'),
      choice('b2', 'In the top layer, some birds rest high in the branches.'),
      choice('b3', 'The passage has three sections.'),
      choice('b4', 'Birds use the same layer for everything.'),
    ],
    partBCorrectChoiceId: 'b2',
  }),
  createMultipleChoiceQuestion({
    ...literaryCheckpointBFields(RETELL_HALL_QUESTION_IDS.checkpointLiteraryB[0], ['literary-retell', 'literary-main-characters', 'literary-setting']),
    passageIdentifier: mapCardSearch.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointLiteraryB,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointLiteraryB[0],
    prompt: 'Which sentence tells the setting?',
    explanation: 'Sentence 1 tells that the walk takes place in the park behind the school.',
    evidenceReference: mapCardSearch.sentences[0].sentenceId,
    evidenceReferenceIds: [mapCardSearch.sentences[0].sentenceId],
    targetVocabulary: ['setting', 'park'],
    soundOutChunks: joinWords('park behind school'),
    choices: [
      choice('c1', mapCardSearch.sentences[0].text),
      choice('c2', mapCardSearch.sentences[1].text),
      choice('c3', mapCardSearch.sentences[7].text),
      choice('c4', mapCardSearch.sentences[9].text),
    ],
    correctChoiceIds: ['c1'],
  }),
  createMultipleChoiceQuestion({
    ...literaryCheckpointBFields(RETELL_HALL_QUESTION_IDS.checkpointLiteraryB[1], ['literary-retell', 'literary-problem']),
    passageIdentifier: mapCardSearch.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointLiteraryB,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointLiteraryB[1],
    prompt: 'What is the problem?',
    explanation: 'The map card slips from the folder before the group line moves.',
    evidenceReference: mapCardSearch.sentences[1].sentenceId,
    evidenceReferenceIds: [mapCardSearch.sentences[1].sentenceId],
    targetVocabulary: ['problem', 'slips'],
    soundOutChunks: joinWords('map card folder'),
    choices: [
      choice('c1', 'The friends place the card back in the folder.'),
      choice('c2', 'The map card slips from the folder before the group line moves.'),
      choice('c3', 'The leader gives a thankful wave.'),
      choice('c4', 'The trail markers are painted arrows.'),
    ],
    correctChoiceIds: ['c2'],
  }),
  createMultipleChoiceQuestion({
    ...literaryCheckpointBFields(RETELL_HALL_QUESTION_IDS.checkpointLiteraryB[2], ['literary-retell', 'literary-resolution']),
    passageIdentifier: mapCardSearch.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointLiteraryB,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointLiteraryB[2],
    prompt: 'Which sentence shows the resolution?',
    explanation: 'Sentence 9 shows that everyone reaches the garden gate on time.',
    evidenceReference: mapCardSearch.sentences[8].sentenceId,
    evidenceReferenceIds: [mapCardSearch.sentences[8].sentenceId],
    targetVocabulary: ['resolution', 'on time'],
    soundOutChunks: joinWords('garden gate time'),
    choices: [
      choice('c1', 'Their map card slipped from the folder before the group line moved.'),
      choice('c2', 'Luis looked under a bench while Hana checked the path markers.'),
      choice('c3', 'At the end, everyone reached the garden gate on time.'),
      choice('c4', 'A red glove lay near the fountain.'),
    ],
    correctChoiceIds: ['c3'],
  }),
  createMultiselectQuestion({
    ...literaryCheckpointBFields(RETELL_HALL_QUESTION_IDS.checkpointLiteraryB[3], ['literary-retell', 'literary-important-events', 'literary-logical-sequence']),
    passageIdentifier: mapCardSearch.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointLiteraryB,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointLiteraryB[3],
    prompt: 'Choose two important events that belong in the retell.',
    explanation: 'Looking under the bench and following the painted arrows both help the friends find the map card.',
    evidenceReference: mapCardSearch.sentences[2].sentenceId,
    evidenceReferenceIds: [mapCardSearch.sentences[2].sentenceId, mapCardSearch.sentences[3].sentenceId],
    targetVocabulary: ['important', 'events'],
    soundOutChunks: joinWords('bench arrows'),
    choices: [
      choice('c1', 'Luis looked under a bench while Hana checked the path markers.'),
      choice('c2', 'They followed the painted arrows to the information sign.'),
      choice('c3', 'A red glove lay near the fountain.'),
      choice('c4', 'At the end, everyone reached the garden gate on time.'),
    ],
    correctChoiceIds: ['c1', 'c2'],
  }),
  createHotTextQuestion({
    ...literaryCheckpointBFields(RETELL_HALL_QUESTION_IDS.checkpointLiteraryB[4], ['literary-retell', 'literary-resolution', 'literary-retell-completeness']),
    passageIdentifier: mapCardSearch.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointLiteraryB,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointLiteraryB[4],
    prompt: 'Select the sentence that shows the ending.',
    explanation: 'Sentence 9 shows the walkers reaching the garden gate on time.',
    evidenceReference: mapCardSearch.sentences[8].sentenceId,
    evidenceReferenceIds: [mapCardSearch.sentences[8].sentenceId],
    targetVocabulary: ['ending', 'gate'],
    soundOutChunks: joinWords('garden gate'),
    selectableSegments: [
      { id: 'c1', text: mapCardSearch.sentences[1].text },
      { id: 'c2', text: mapCardSearch.sentences[6].text },
      { id: 'c3', text: mapCardSearch.sentences[8].text },
      { id: 'c4', text: mapCardSearch.sentences[9].text },
    ],
    correctSegmentIds: ['c3'],
  }),
  createTableMatchQuestion({
    ...literaryCheckpointBFields(RETELL_HALL_QUESTION_IDS.checkpointLiteraryB[5], [...RETELL_HALL_LITERARY_QUESTION_TAGS]),
    passageIdentifier: mapCardSearch.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointLiteraryB,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointLiteraryB[5],
    prompt: 'Build the retell. Choose one retell piece for each place. Each piece can be used only once. One extra detail does not belong in the retell.',
    explanation: 'The pieces should follow the opening, problem, important events, and ending. The extra detail stays out.',
    evidenceReference: mapCardSearch.sentences[0].sentenceId,
    evidenceReferenceIds: mapCardSearch.sentences.map((sentence) => sentence.sentenceId),
    targetVocabulary: ['sequence', 'ending'],
    soundOutChunks: joinWords('one extra detail'),
    selectionMode: 'use_each_once',
    rows: [
      {
        id: 'r1',
        prompt: 'Opening',
        correctChoiceId: 'map-piece-1',
        options: [
          choice('map-piece-1', 'Luis and Hana start a nature walk in the small park behind the school.'),
          choice('map-piece-2', 'Their map card slips from the folder before the group line moves.'),
          choice('map-piece-3', 'Luis looks under a bench while Hana checks the path markers.'),
          choice('map-piece-4', 'The friends follow the painted arrows, tuck the card beside the sign, and place it back in the folder.'),
          choice('map-piece-5', 'At the end, everyone reaches the garden gate on time.'),
          choice('map-extra', 'A red glove lay near the fountain.'),
        ],
      },
      {
        id: 'r2',
        prompt: 'Problem',
        correctChoiceId: 'map-piece-2',
        options: [
          choice('map-piece-1', 'Luis and Hana start a nature walk in the small park behind the school.'),
          choice('map-piece-2', 'Their map card slips from the folder before the group line moves.'),
          choice('map-piece-3', 'Luis looks under a bench while Hana checks the path markers.'),
          choice('map-piece-4', 'The friends follow the painted arrows, tuck the card beside the sign, and place it back in the folder.'),
          choice('map-piece-5', 'At the end, everyone reaches the garden gate on time.'),
          choice('map-extra', 'A red glove lay near the fountain.'),
        ],
      },
      {
        id: 'r3',
        prompt: 'Important event 1',
        correctChoiceId: 'map-piece-3',
        options: [
          choice('map-piece-1', 'Luis and Hana start a nature walk in the small park behind the school.'),
          choice('map-piece-2', 'Their map card slips from the folder before the group line moves.'),
          choice('map-piece-3', 'Luis looks under a bench while Hana checks the path markers.'),
          choice('map-piece-4', 'The friends follow the painted arrows, tuck the card beside the sign, and place it back in the folder.'),
          choice('map-piece-5', 'At the end, everyone reaches the garden gate on time.'),
          choice('map-extra', 'A red glove lay near the fountain.'),
        ],
      },
      {
        id: 'r4',
        prompt: 'Important event 2',
        correctChoiceId: 'map-piece-4',
        options: [
          choice('map-piece-1', 'Luis and Hana start a nature walk in the small park behind the school.'),
          choice('map-piece-2', 'Their map card slips from the folder before the group line moves.'),
          choice('map-piece-3', 'Luis looks under a bench while Hana checks the path markers.'),
          choice('map-piece-4', 'The friends follow the painted arrows, tuck the card beside the sign, and place it back in the folder.'),
          choice('map-piece-5', 'At the end, everyone reaches the garden gate on time.'),
          choice('map-extra', 'A red glove lay near the fountain.'),
        ],
      },
      {
        id: 'r5',
        prompt: 'Ending',
        correctChoiceId: 'map-piece-5',
        options: [
          choice('map-piece-1', 'Luis and Hana start a nature walk in the small park behind the school.'),
          choice('map-piece-2', 'Their map card slips from the folder before the group line moves.'),
          choice('map-piece-3', 'Luis looks under a bench while Hana checks the path markers.'),
          choice('map-piece-4', 'The friends follow the painted arrows, tuck the card beside the sign, and place it back in the folder.'),
          choice('map-piece-5', 'At the end, everyone reaches the garden gate on time.'),
          choice('map-extra', 'A red glove lay near the fountain.'),
        ],
      },
    ],
  }),
  createTwoPartQuestion({
    ...literaryCheckpointBFields(RETELL_HALL_QUESTION_IDS.checkpointLiteraryB[6], ['literary-retell', 'retell-important-vs-minor']),
    passageIdentifier: mapCardSearch.passageId,
    lessonIdentifier: RETELL_HALL_LESSON_IDS.checkpointLiteraryB,
    questionIdentifier: RETELL_HALL_QUESTION_IDS.checkpointLiteraryB[6],
    prompt: 'Which detail is minor and should be left out?',
    explanation: 'The red glove is true, but it does not change the main events of finding the map card.',
    evidenceReference: mapCardSearch.sentences[5].sentenceId,
    evidenceReferenceIds: [mapCardSearch.sentences[5].sentenceId, mapCardSearch.sentences[8].sentenceId],
    targetVocabulary: ['minor', 'detail'],
    soundOutChunks: joinWords('red glove'),
    partAPrompt: 'Which detail is minor and should be left out?',
    partAChoices: [
      choice('a1', 'A red glove lay near the fountain.'),
      choice('a2', 'The map card slips from the folder.'),
      choice('a3', 'Luis looks under a bench.'),
      choice('a4', 'At the end, everyone reaches the garden gate on time.'),
    ],
    partACorrectChoiceId: 'a1',
    partBPrompt: 'Why should it be left out?',
    partBChoices: [
      choice('b1', 'It does not change the main events.'),
      choice('b2', 'It is the central idea.'),
      choice('b3', 'It is the opening.'),
      choice('b4', 'It is the strongest event.'),
    ],
    partBCorrectChoiceId: 'b1',
  }),
] as const
