import type { RetellGuide } from '../../../contentPackTypes'
import { RETELL_HALL_CONTENT_VERSION, RETELL_HALL_PASSAGE_IDS } from './ids'
import { getRetellHallPassagePlan } from './passages'

const sentenceId = (passageId: string, index: number) => getRetellHallPassagePlan(passageId).sentences[index].sentenceId

export const retellHallRetellGuides: readonly RetellGuide[] = [
  {
    passageId: RETELL_HALL_PASSAGE_IDS.literaryMuralLabel,
    textKind: 'literary',
    mainCharacters: ['Maya', 'Eli'],
    settingStatement: 'The art room beside the library is the setting.',
    problemStatement: 'The class mural needs a final label before visitors arrive.',
    importantEventStatements: [
      'Maya spreads the bright cards carefully across the table.',
      'Eli tapes the curled corner flat.',
      'The children move the paint jars into an organized line.',
    ],
    resolutionStatement: 'At last, the mural has a neat title and is ready for the visitors.',
    retellPieces: [
      {
        pieceId: 'g2-cg-retell-mural-label-piece-1',
        text: 'Maya and Eli work in the art room beside the library to finish the mural label before visitors arrive.',
        sequenceIndex: 1,
        role: 'Opening',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryMuralLabel, 0), sentenceId(RETELL_HALL_PASSAGE_IDS.literaryMuralLabel, 1)],
      },
      {
        pieceId: 'g2-cg-retell-mural-label-piece-2',
        text: 'The problem is that the class mural still needs a final label.',
        sequenceIndex: 2,
        role: 'Problem',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryMuralLabel, 1)],
      },
      {
        pieceId: 'g2-cg-retell-mural-label-piece-3',
        text: 'Maya spreads the bright cards carefully across the table.',
        sequenceIndex: 3,
        role: 'Important event 1',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryMuralLabel, 2)],
      },
      {
        pieceId: 'g2-cg-retell-mural-label-piece-4',
        text: 'Eli tapes the curled corner flat and the children move the paint jars into an organized line.',
        sequenceIndex: 4,
        role: 'Important event 2',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryMuralLabel, 4), sentenceId(RETELL_HALL_PASSAGE_IDS.literaryMuralLabel, 5)],
      },
      {
        pieceId: 'g2-cg-retell-mural-label-piece-5',
        text: 'At last, the mural has a neat title and is ready for the visitors.',
        sequenceIndex: 5,
        role: 'Ending',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryMuralLabel, 6)],
      },
    ],
    minorDetailIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryMuralLabel, 7)],
    reviewStatus: 'DRAFT',
    contentVersion: RETELL_HALL_CONTENT_VERSION,
  },
  {
    passageId: RETELL_HALL_PASSAGE_IDS.literaryBridgeRepair,
    textKind: 'literary',
    mainCharacters: ['Jada', 'Omar'],
    settingStatement: 'The science corner is the setting.',
    problemStatement: 'The model bridge wobbles when the toy truck rolls across it.',
    importantEventStatements: [
      'Jada adds a support beam.',
      'Omar holds the pieces steady.',
      'The friends work carefully and connect the last cardboard strip.',
    ],
    resolutionStatement: 'Soon, the truck crosses the bridge without a shake, and the model is ready for the class display.',
    retellPieces: [
      {
        pieceId: 'g2-cg-retell-bridge-repair-piece-1',
        text: 'Jada and Omar test the model bridge in the science corner.',
        sequenceIndex: 1,
        role: 'Opening',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryBridgeRepair, 0)],
      },
      {
        pieceId: 'g2-cg-retell-bridge-repair-piece-2',
        text: 'The bridge wobbles when the toy truck rolls across it.',
        sequenceIndex: 2,
        role: 'Problem',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryBridgeRepair, 1)],
      },
      {
        pieceId: 'g2-cg-retell-bridge-repair-piece-3',
        text: 'Jada adds a support beam and Omar holds the pieces steady.',
        sequenceIndex: 3,
        role: 'Important event 1',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryBridgeRepair, 2)],
      },
      {
        pieceId: 'g2-cg-retell-bridge-repair-piece-4',
        text: 'The friends work carefully and connect the last cardboard strip.',
        sequenceIndex: 4,
        role: 'Important event 2',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryBridgeRepair, 3), sentenceId(RETELL_HALL_PASSAGE_IDS.literaryBridgeRepair, 4)],
      },
      {
        pieceId: 'g2-cg-retell-bridge-repair-piece-5',
        text: 'Soon, the truck crosses the bridge without a shake, and the model is ready for the class display.',
        sequenceIndex: 5,
        role: 'Ending',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryBridgeRepair, 7)],
      },
    ],
    minorDetailIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryBridgeRepair, 5)],
    reviewStatus: 'DRAFT',
    contentVersion: RETELL_HALL_CONTENT_VERSION,
  },
  {
    passageId: RETELL_HALL_PASSAGE_IDS.literaryLibraryStoryNight,
    textKind: 'literary',
    mainCharacters: ['Noa', 'Priya'],
    settingStatement: 'The library hall is the setting.',
    problemStatement: 'The story-night poster needs to stay up before the families arrive.',
    importantEventStatements: [
      'One corner of the poster curls like a ribbon in a breeze.',
      'Noa presses the poster flat while Priya finds the tape roll.',
      'The friends arrange the name cards in an organized row.',
    ],
    resolutionStatement: 'At last, the poster hangs neatly, and the story-night sign looks bright when the first visitors walk in.',
    retellPieces: [
      {
        pieceId: 'g2-cg-retell-library-story-night-piece-1',
        text: 'Noa and Priya set up the story-night table in the library hall.',
        sequenceIndex: 1,
        role: 'Opening',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryLibraryStoryNight, 0)],
      },
      {
        pieceId: 'g2-cg-retell-library-story-night-piece-2',
        text: 'The story-night poster needs to stay up before the families arrive.',
        sequenceIndex: 2,
        role: 'Problem',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryLibraryStoryNight, 1)],
      },
      {
        pieceId: 'g2-cg-retell-library-story-night-piece-3',
        text: 'One corner of the poster curls like a ribbon in a breeze.',
        sequenceIndex: 3,
        role: 'Important event 1',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryLibraryStoryNight, 2)],
      },
      {
        pieceId: 'g2-cg-retell-library-story-night-piece-4',
        text: 'Noa presses the poster flat while Priya finds the tape roll and arranges the name cards in an organized row.',
        sequenceIndex: 4,
        role: 'Important event 2',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryLibraryStoryNight, 3), sentenceId(RETELL_HALL_PASSAGE_IDS.literaryLibraryStoryNight, 4)],
      },
      {
        pieceId: 'g2-cg-retell-library-story-night-piece-5',
        text: 'At last, the poster hangs neatly, and the story-night sign looks bright when the first visitors walk in.',
        sequenceIndex: 5,
        role: 'Ending',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryLibraryStoryNight, 7), sentenceId(RETELL_HALL_PASSAGE_IDS.literaryLibraryStoryNight, 8)],
      },
    ],
    minorDetailIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryLibraryStoryNight, 9)],
    reviewStatus: 'DRAFT',
    contentVersion: RETELL_HALL_CONTENT_VERSION,
  },
  {
    passageId: RETELL_HALL_PASSAGE_IDS.literaryMapCardSearch,
    textKind: 'literary',
    mainCharacters: ['Luis', 'Hana'],
    settingStatement: 'The small park behind the school is the setting.',
    problemStatement: 'The map card slips from the folder before the group line moves.',
    importantEventStatements: [
      'Luis looks under a bench while Hana checks the path markers.',
      'The friends follow the painted arrows to the information sign.',
      'The map card is tucked beside the sign and then placed back in the folder.',
    ],
    resolutionStatement: 'At the end, everyone reaches the garden gate on time.',
    retellPieces: [
      {
        pieceId: 'g2-cg-retell-map-card-search-piece-1',
        text: 'Luis and Hana start a nature walk in the small park behind the school.',
        sequenceIndex: 1,
        role: 'Opening',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryMapCardSearch, 0)],
      },
      {
        pieceId: 'g2-cg-retell-map-card-search-piece-2',
        text: 'Their map card slips from the folder before the group line moves.',
        sequenceIndex: 2,
        role: 'Problem',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryMapCardSearch, 1)],
      },
      {
        pieceId: 'g2-cg-retell-map-card-search-piece-3',
        text: 'Luis looks under a bench while Hana checks the path markers.',
        sequenceIndex: 3,
        role: 'Important event 1',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryMapCardSearch, 2)],
      },
      {
        pieceId: 'g2-cg-retell-map-card-search-piece-4',
        text: 'The friends follow the painted arrows, tuck the card beside the sign, and place it back in the folder.',
        sequenceIndex: 4,
        role: 'Important event 2',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryMapCardSearch, 3), sentenceId(RETELL_HALL_PASSAGE_IDS.literaryMapCardSearch, 4), sentenceId(RETELL_HALL_PASSAGE_IDS.literaryMapCardSearch, 6)],
      },
      {
        pieceId: 'g2-cg-retell-map-card-search-piece-5',
        text: 'At the end, everyone reaches the garden gate on time.',
        sequenceIndex: 5,
        role: 'Ending',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryMapCardSearch, 8)],
      },
    ],
    minorDetailIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.literaryMapCardSearch, 5)],
    reviewStatus: 'DRAFT',
    contentVersion: RETELL_HALL_CONTENT_VERSION,
  },
  {
    passageId: RETELL_HALL_PASSAGE_IDS.informationalSeedTravel,
    textKind: 'informational',
    topicLabel: 'Seeds on the Move',
    centralIdeaStatement: 'Seeds travel to new places in several ways.',
    relevantDetailStatements: [
      'Some light seeds ride gently on the wind and float far away.',
      'Tiny hooks cling to animal fur.',
      'Water can carry seeds along streams and puddles.',
    ],
    retellPieces: [
      {
        pieceId: 'g2-cg-retell-seed-travel-piece-1',
        text: 'Seeds travel to new places in several ways.',
        sequenceIndex: 1,
        role: 'Central idea',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.informationalSeedTravel, 0)],
      },
      {
        pieceId: 'g2-cg-retell-seed-travel-piece-2',
        text: 'Some light seeds ride gently on the wind and float far away.',
        sequenceIndex: 2,
        role: 'Relevant detail 1',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.informationalSeedTravel, 1)],
      },
      {
        pieceId: 'g2-cg-retell-seed-travel-piece-3',
        text: 'Tiny hooks cling to animal fur.',
        sequenceIndex: 3,
        role: 'Relevant detail 2',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.informationalSeedTravel, 2)],
      },
      {
        pieceId: 'g2-cg-retell-seed-travel-piece-4',
        text: 'Water can carry seeds along streams and puddles.',
        sequenceIndex: 4,
        role: 'Relevant detail 3',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.informationalSeedTravel, 3)],
      },
    ],
    otherTrueDetailIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.informationalSeedTravel, 4)],
    reviewStatus: 'DRAFT',
    contentVersion: RETELL_HALL_CONTENT_VERSION,
  },
  {
    passageId: RETELL_HALL_PASSAGE_IDS.informationalRainGaugeNotes,
    textKind: 'informational',
    topicLabel: 'Rain Gauge Notes',
    centralIdeaStatement: 'A rain gauge helps people measure how much rain falls.',
    relevantDetailStatements: [
      'The cup catches drops one after another.',
      'Marked lines show the amount.',
      'A notebook records the reading after the storm.',
    ],
    retellPieces: [
      {
        pieceId: 'g2-cg-retell-rain-gauge-piece-1',
        text: 'A rain gauge helps people measure how much rain falls.',
        sequenceIndex: 1,
        role: 'Central idea',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.informationalRainGaugeNotes, 0)],
      },
      {
        pieceId: 'g2-cg-retell-rain-gauge-piece-2',
        text: 'The cup catches drops one after another.',
        sequenceIndex: 2,
        role: 'Relevant detail 1',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.informationalRainGaugeNotes, 1)],
      },
      {
        pieceId: 'g2-cg-retell-rain-gauge-piece-3',
        text: 'Marked lines show the amount.',
        sequenceIndex: 3,
        role: 'Relevant detail 2',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.informationalRainGaugeNotes, 2)],
      },
      {
        pieceId: 'g2-cg-retell-rain-gauge-piece-4',
        text: 'A notebook records the reading after the storm.',
        sequenceIndex: 4,
        role: 'Relevant detail 3',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.informationalRainGaugeNotes, 3)],
      },
    ],
    otherTrueDetailIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.informationalRainGaugeNotes, 4)],
    reviewStatus: 'DRAFT',
    contentVersion: RETELL_HALL_CONTENT_VERSION,
  },
  {
    passageId: RETELL_HALL_PASSAGE_IDS.informationalBirdLayers,
    textKind: 'informational',
    topicLabel: 'Birds in a Layered Habitat',
    centralIdeaStatement: 'Birds use different layers of a habitat for food and shelter.',
    relevantDetailStatements: [
      'In the top layer, some birds rest high in the branches.',
      'In the middle layer, others hide in shrubs and look for insects.',
      'On the ground, some birds search for seeds and crumbs.',
    ],
    retellPieces: [
      {
        pieceId: 'g2-cg-retell-bird-layers-piece-1',
        text: 'Birds use different layers of a habitat for food and shelter.',
        sequenceIndex: 1,
        role: 'Central idea',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.informationalBirdLayers, 0)],
      },
      {
        pieceId: 'g2-cg-retell-bird-layers-piece-2',
        text: 'In the top layer, some birds rest high in the branches.',
        sequenceIndex: 2,
        role: 'Relevant detail 1',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.informationalBirdLayers, 1)],
      },
      {
        pieceId: 'g2-cg-retell-bird-layers-piece-3',
        text: 'In the middle layer, others hide in shrubs and look for insects.',
        sequenceIndex: 3,
        role: 'Relevant detail 2',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.informationalBirdLayers, 2)],
      },
      {
        pieceId: 'g2-cg-retell-bird-layers-piece-4',
        text: 'On the ground, some birds search for seeds and crumbs.',
        sequenceIndex: 4,
        role: 'Relevant detail 3',
        evidenceReferenceIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.informationalBirdLayers, 3)],
      },
    ],
    otherTrueDetailIds: [sentenceId(RETELL_HALL_PASSAGE_IDS.informationalBirdLayers, 4)],
    reviewStatus: 'DRAFT',
    contentVersion: RETELL_HALL_CONTENT_VERSION,
  },
] as const
