import type { ReadingQuestion } from '../../../../types'
import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from '../../../grade2/wordForge/variableVowelsOoEa/questionFactories'
import {
  GRADE3_FLUENCY_FLIGHT_CONTENT_VERSION,
  GRADE3_FLUENCY_FLIGHT_LESSON_IDS,
  GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS,
  GRADE3_FLUENCY_FLIGHT_QUESTION_IDS,
  GRADE3_FLUENCY_FLIGHT_SKILL_ID,
} from './ids'

const common = {
  benchmarkReference: 'ELA.3.F.1.4',
  skillIdentifier: GRADE3_FLUENCY_FLIGHT_SKILL_ID,
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'Word Forge',
  gradeBand: 3 as const,
  estimatedReadingLevel: 'Grade 3',
  contentVersion: GRADE3_FLUENCY_FLIGHT_CONTENT_VERSION,
  reviewStatus: 'DRAFT' as const,
  difficulty: 4,
}

const activity = (questionId: string) => `${questionId}-activity`

export const grade3WordForgeFluencyFlightQuestions: ReadingQuestion[] = [
  createMultipleChoiceQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.hilltopSignal,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.guidedPunctuation,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedPunctuation[0]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedPunctuation[0],
    prompt: 'Which mark tells the reader to pause briefly after "Before sunrise"?',
    explanation: 'The comma after "Before sunrise" marks a brief pause before the sentence continues.',
    evidenceReference: 'hilltop-1',
    evidenceReferenceIds: ['hilltop-comma'],
    targetVocabulary: ['comma', 'pause', 'sunrise'],
    soundOutChunks: ['be', 'fore', 'sun', 'rise'],
    tags: ['fluency-practice', 'punctuation-pause', 'accuracy-practice'],
    choices: [
      { id: 'hilltop-period', text: 'period' },
      { id: 'hilltop-comma', text: 'comma' },
      { id: 'hilltop-question', text: 'question mark' },
      { id: 'hilltop-exclamation', text: 'exclamation mark' },
    ],
    correctChoiceIds: ['hilltop-comma'],
  }),
  createHotTextQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.hilltopSignal,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.guidedPunctuation,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedPunctuation[1]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedPunctuation[1],
    prompt: 'Select the sentence that should sound like a question.',
    explanation: '"Is the glider ready?" asks a question, and its question mark gives the voice a clear cue.',
    evidenceReference: 'hilltop-3',
    evidenceReferenceIds: ['hilltop-question-sentence'],
    targetVocabulary: ['glider', 'question', 'ready'],
    soundOutChunks: ['glid', 'er'],
    tags: ['fluency-practice', 'question-cue', 'expression-practice'],
    selectableSegments: [
      { id: 'hilltop-breath-sentence', text: 'She paused beside her uncle, took a steady breath, and watched the eastern horizon.' },
      { id: 'hilltop-question-sentence', text: '"Is the glider ready?" she asked.' },
      { id: 'hilltop-landing-sentence', text: 'The small glider lifted smoothly, crossed the field, and landed near the orange marker.' },
    ],
    correctSegmentIds: ['hilltop-question-sentence'],
  }),
  createMultiselectQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.hilltopSignal,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.guidedPunctuation,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedPunctuation[2]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedPunctuation[2],
    prompt: 'Choose the two quoted lines that should be read with strong energy.',
    explanation: 'Both quoted lines end with exclamation marks, which signal strong energy.',
    evidenceReference: 'hilltop-4 hilltop-5',
    evidenceReferenceIds: ['hilltop-ready-line', 'hilltop-now-line'],
    targetVocabulary: ['launch', 'energy', 'exclamation'],
    soundOutChunks: ['launch', 'en', 'er', 'gy'],
    tags: ['fluency-practice', 'exclamation-cue', 'expression-practice'],
    choices: [
      { id: 'hilltop-ready-line', text: '"Ready for a careful launch!"' },
      { id: 'hilltop-question-line', text: '"Is the glider ready?"' },
      { id: 'hilltop-now-line', text: '"Now!"' },
      { id: 'hilltop-marker-line', text: 'near the orange marker' },
    ],
    correctChoiceIds: ['hilltop-ready-line', 'hilltop-now-line'],
  }),
  createTableMatchQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.hilltopSignal,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.guidedPunctuation,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedPunctuation[3]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedPunctuation[3],
    prompt: 'Match each punctuation mark to the reading cue it gives.',
    explanation: 'Commas mark brief pauses, periods mark full stops, question marks signal questions, and exclamation marks signal strong feeling.',
    evidenceReference: 'hilltop punctuation cues',
    evidenceReferenceIds: ['hilltop-table-comma-correct', 'hilltop-table-period-correct', 'hilltop-table-question-correct', 'hilltop-table-exclamation-correct'],
    targetVocabulary: ['comma', 'period', 'question mark', 'exclamation mark'],
    soundOutChunks: ['pause', 'stop', 'question', 'energy'],
    tags: ['fluency-practice', 'punctuation-cues', 'phrasing-practice'],
    rows: [
      { id: 'hilltop-comma-row', prompt: 'comma', correctChoiceId: 'hilltop-table-comma-correct', options: [
        { id: 'hilltop-table-comma-correct', text: 'pause briefly' },
        { id: 'hilltop-table-comma-stop', text: 'stop for the whole sentence' },
        { id: 'hilltop-table-comma-question', text: 'turn it into a question' },
        { id: 'hilltop-table-comma-energy', text: 'add powerful energy' },
      ] },
      { id: 'hilltop-period-row', prompt: 'period', correctChoiceId: 'hilltop-table-period-correct', options: [
        { id: 'hilltop-table-period-pause', text: 'take a short comma pause' },
        { id: 'hilltop-table-period-correct', text: 'make a full stop' },
        { id: 'hilltop-table-period-question', text: 'use a questioning voice' },
        { id: 'hilltop-table-period-energy', text: 'add excited energy' },
      ] },
      { id: 'hilltop-question-row', prompt: 'question mark', correctChoiceId: 'hilltop-table-question-correct', options: [
        { id: 'hilltop-table-question-pause', text: 'pause as at a comma' },
        { id: 'hilltop-table-question-stop', text: 'finish as at a period' },
        { id: 'hilltop-table-question-correct', text: 'read it as a question' },
        { id: 'hilltop-table-question-energy', text: 'sound excited by the news' },
      ] },
      { id: 'hilltop-exclamation-row', prompt: 'exclamation mark', correctChoiceId: 'hilltop-table-exclamation-correct', options: [
        { id: 'hilltop-table-exclamation-pause', text: 'pause softly at a comma' },
        { id: 'hilltop-table-exclamation-stop', text: 'finish calmly at a period' },
        { id: 'hilltop-table-exclamation-question', text: 'ask with a questioning voice' },
        { id: 'hilltop-table-exclamation-correct', text: 'show strong feeling' },
      ] },
    ],
  }),

  createMultipleChoiceQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.paperGlider,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.guidedPhraseGroups,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedPhraseGroups[0]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedPhraseGroups[0],
    prompt: 'Which words should be read together because they name one complete action?',
    explanation: '"helps create lift" names one connected action and should be read as a phrase.',
    evidenceReference: 'glider-3',
    evidenceReferenceIds: ['glider-lift-phrase'],
    targetVocabulary: ['create', 'lift', 'phrase'],
    soundOutChunks: ['cre', 'ate', 'lift'],
    tags: ['fluency-practice', 'phrase-grouping', 'automaticity-practice'],
    choices: [
      { id: 'glider-shape-fragment', text: "The wing's" },
      { id: 'glider-lift-phrase', text: 'helps create lift' },
      { id: 'glider-floor-fragment', text: 'the floor for' },
      { id: 'glider-time-fragment', text: 'a short' },
    ],
    correctChoiceIds: ['glider-lift-phrase'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.paperGlider,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.guidedPhraseGroups,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedPhraseGroups[1]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedPhraseGroups[1],
    prompt: 'Which grouping keeps the opening idea and the air movement clear?',
    explanation: 'The comma separates the opening phrase from the complete idea about air moving over and under the wing.',
    evidenceReference: 'glider-2',
    evidenceReferenceIds: ['glider-grouping-correct'],
    targetVocabulary: ['travels', 'forward', 'air'],
    soundOutChunks: ['trav', 'els', 'for', 'ward'],
    tags: ['fluency-practice', 'phrase-grouping', 'punctuation-pause'],
    choices: [
      { id: 'glider-grouping-correct', text: 'Pause after forward: As the glider travels forward | air moves over and under each wing' },
      { id: 'glider-grouping-2', text: 'Pause after the: As the | glider travels forward air moves over and under each wing' },
      { id: 'glider-grouping-3', text: 'Pause after glider: As the glider | travels forward air moves over and under each wing' },
      { id: 'glider-grouping-4', text: 'Pause after As: As | the glider travels forward air moves over and under each wing' },
    ],
    correctChoiceIds: ['glider-grouping-correct'],
  }),
  createHotTextQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.paperGlider,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.guidedPhraseGroups,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedPhraseGroups[2]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedPhraseGroups[2],
    prompt: 'Select the sentence with an opening phrase followed by a comma.',
    explanation: '"As the glider travels forward" is an opening phrase, and the comma marks a brief pause after it.',
    evidenceReference: 'glider-2',
    evidenceReferenceIds: ['glider-opening-sentence'],
    targetVocabulary: ['opening phrase', 'comma', 'forward'],
    soundOutChunks: ['o', 'pen', 'ing', 'phrase'],
    tags: ['fluency-practice', 'phrase-grouping', 'punctuation-pause'],
    selectableSegments: [
      { id: 'glider-first-sentence', text: 'A paper glider moves because air pushes around its wings.' },
      { id: 'glider-opening-sentence', text: 'As the glider travels forward, air moves over and under each wing.' },
      { id: 'glider-balanced-sentence', text: 'A balanced glider follows a steadier path.' },
    ],
    correctSegmentIds: ['glider-opening-sentence'],
  }),
  createMultiselectQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.paperGlider,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.guidedPhraseGroups,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedPhraseGroups[3]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedPhraseGroups[3],
    prompt: 'Choose the two words after which the reader makes a full stop in the first two sentences.',
    explanation: 'The periods after "wings" and "wing" mark full stops at the ends of the first two sentences.',
    evidenceReference: 'glider-1 glider-2',
    evidenceReferenceIds: ['glider-wings-stop', 'glider-wing-stop'],
    targetVocabulary: ['period', 'stop', 'sentence'],
    soundOutChunks: ['pe', 'ri', 'od'],
    tags: ['fluency-practice', 'punctuation-stop', 'accuracy-practice'],
    choices: [
      { id: 'glider-wings-stop', text: 'wings.' },
      { id: 'glider-because-middle', text: 'because' },
      { id: 'glider-wing-stop', text: 'wing.' },
      { id: 'glider-forward-comma', text: 'forward,' },
    ],
    correctChoiceIds: ['glider-wings-stop', 'glider-wing-stop'],
  }),

  createMultipleChoiceQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.missingMap,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.guidedDialogue,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedDialogue[0]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedDialogue[0],
    prompt: 'Which quoted line should sound curious because it asks a question?',
    explanation: '"Could the breeze have moved it?" is a question, so the reader should use a curious questioning voice.',
    evidenceReference: 'map-5',
    evidenceReferenceIds: ['map-breeze-question'],
    targetVocabulary: ['breeze', 'curious', 'question'],
    soundOutChunks: ['breeze', 'cu', 'ri', 'ous'],
    tags: ['fluency-practice', 'dialogue-phrasing', 'question-cue'],
    choices: [
      { id: 'map-compass-statement', text: '"I placed it beside the compass."' },
      { id: 'map-not-there-exclaim', text: '"It isn\'t there now!"' },
      { id: 'map-breeze-question', text: '"Could the breeze have moved it?"' },
      { id: 'map-mystery-exclaim', text: '"Yes, and our mystery has landed!"' },
    ],
    correctChoiceIds: ['map-breeze-question'],
  }),
  createHotTextQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.missingMap,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.guidedDialogue,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedDialogue[1]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedDialogue[1],
    prompt: 'Select the line that clearly shows surprise with an exclamation mark.',
    explanation: '"It isn\'t there now!" uses an exclamation mark to show Mateo\'s surprise.',
    evidenceReference: 'map-3',
    evidenceReferenceIds: ['map-surprise-line'],
    targetVocabulary: ['surprise', 'exclamation', 'dialogue'],
    soundOutChunks: ['sur', 'prise'],
    tags: ['fluency-practice', 'dialogue-phrasing', 'exclamation-cue'],
    selectableSegments: [
      { id: 'map-surprise-line', text: '"It isn\'t there now!" Mateo cried.' },
      { id: 'map-quiet-line', text: 'After a quiet moment, Nia noticed a corner of paper under the model runway.' },
      { id: 'map-return-line', text: 'Together, they returned the map to its folder and checked the route.' },
    ],
    correctSegmentIds: ['map-surprise-line'],
  }),
  createMultiselectQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.missingMap,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.guidedDialogue,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedDialogue[2]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedDialogue[2],
    prompt: 'Choose the two quoted lines that should be read as questions.',
    explanation: 'The lines about the missing map and the breeze both end with question marks.',
    evidenceReference: 'map-1 map-5',
    evidenceReferenceIds: ['map-where-question', 'map-could-question'],
    targetVocabulary: ['question mark', 'dialogue', 'voice'],
    soundOutChunks: ['ques', 'tion', 'mark'],
    tags: ['fluency-practice', 'dialogue-phrasing', 'question-cue'],
    choices: [
      { id: 'map-where-question', text: '"Where did the flight map go?"' },
      { id: 'map-placed-statement', text: '"I placed it beside the compass."' },
      { id: 'map-could-question', text: '"Could the breeze have moved it?"' },
      { id: 'map-landed-exclaim', text: '"Yes, and our mystery has landed!"' },
    ],
    correctChoiceIds: ['map-where-question', 'map-could-question'],
  }),
  createTableMatchQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.missingMap,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.guidedDialogue,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedDialogue[3]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedDialogue[3],
    prompt: 'Match each line to the voice cue given by its punctuation and wording.',
    explanation: 'Each dialogue line gives a clear cue for a questioning, surprised, calm, or joyful voice.',
    evidenceReference: 'map dialogue',
    evidenceReferenceIds: ['map-table-question-correct', 'map-table-surprise-correct', 'map-table-calm-correct', 'map-table-joy-correct'],
    targetVocabulary: ['questioning', 'surprised', 'calm', 'joyful'],
    soundOutChunks: ['ques', 'tion', 'sur', 'prised', 'joy', 'ful'],
    tags: ['fluency-practice', 'dialogue-phrasing', 'expression-practice'],
    rows: [
      { id: 'map-table-question-row', prompt: '"Where did the flight map go?"', correctChoiceId: 'map-table-question-correct', options: [
        { id: 'map-table-question-correct', text: 'questioning' },
        { id: 'map-table-question-surprise', text: 'startled by new information' },
        { id: 'map-table-question-calm', text: 'quietly stating a fact' },
        { id: 'map-table-question-joy', text: 'cheering about good news' },
      ] },
      { id: 'map-table-surprise-row', prompt: '"It isn\'t there now!"', correctChoiceId: 'map-table-surprise-correct', options: [
        { id: 'map-table-surprise-question', text: 'asking for missing information' },
        { id: 'map-table-surprise-correct', text: 'surprised' },
        { id: 'map-table-surprise-calm', text: 'stating a calm fact' },
        { id: 'map-table-surprise-joy', text: 'celebrating a success' },
      ] },
      { id: 'map-table-calm-row', prompt: '"I placed it beside the compass."', correctChoiceId: 'map-table-calm-correct', options: [
        { id: 'map-table-calm-question', text: 'asking with curiosity' },
        { id: 'map-table-calm-surprise', text: 'reacting to sudden news' },
        { id: 'map-table-calm-correct', text: 'calmly explaining' },
        { id: 'map-table-calm-joy', text: 'cheering about a success' },
      ] },
      { id: 'map-table-joy-row', prompt: '"Yes, and our mystery has landed!"', correctChoiceId: 'map-table-joy-correct', options: [
        { id: 'map-table-joy-question', text: 'asking for an answer' },
        { id: 'map-table-joy-surprise', text: 'worried and surprised' },
        { id: 'map-table-joy-calm', text: 'sharing a quiet fact' },
        { id: 'map-table-joy-correct', text: 'joyfully celebrating' },
      ] },
    ],
  }),

  createMultipleChoiceQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.paperRotor,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.guidedRereading,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedRereading[0]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedRereading[0],
    prompt: 'Which word signals that the first direction begins the procedure?',
    explanation: '"First" signals the beginning and should be read with the rest of the first direction.',
    evidenceReference: 'rotor-1',
    evidenceReferenceIds: ['rotor-first-word'],
    targetVocabulary: ['first', 'direction', 'procedure'],
    soundOutChunks: ['first', 'di', 'rec', 'tion'],
    tags: ['fluency-practice', 'phrase-grouping', 'accuracy-practice'],
    choices: [
      { id: 'rotor-first-word', text: 'First' },
      { id: 'rotor-strip-word', text: 'strip' },
      { id: 'rotor-paper-word', text: 'paper' },
      { id: 'rotor-half-word', text: 'half' },
    ],
    correctChoiceIds: ['rotor-first-word'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.paperRotor,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.guidedRereading,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedRereading[1]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedRereading[1],
    prompt: 'Which line should be reread in three smooth action groups instead of one word at a time?',
    explanation: 'The commas separate three connected actions: hold the rotor, release it, and watch it spin.',
    evidenceReference: 'rotor-5',
    evidenceReferenceIds: ['rotor-three-actions'],
    targetVocabulary: ['release', 'spin', 'action groups'],
    soundOutChunks: ['re', 'lease', 'ac', 'tion'],
    tags: ['fluency-practice', 'rereading', 'phrase-grouping'],
    choices: [
      { id: 'rotor-fold-line', text: 'First, fold a narrow strip of paper in half.' },
      { id: 'rotor-three-actions', text: 'Hold the rotor above a clear space, release it, and watch it spin.' },
      { id: 'rotor-blades-line', text: 'Fold one blade forward and the other backward.' },
      { id: 'rotor-balance-line', text: 'Then attach a paper clip at the bottom for balance.' },
    ],
    correctChoiceIds: ['rotor-three-actions'],
  }),
  createHotTextQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.paperRotor,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.guidedRereading,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedRereading[2]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedRereading[2],
    prompt: 'Select the direction that tells what to do if the rotor does not spin evenly.',
    explanation: 'The selected direction tells the reader to adjust one blade and try again when the rotation looks uneven.',
    evidenceReference: 'rotor-6',
    evidenceReferenceIds: ['rotor-adjust-direction'],
    targetVocabulary: ['rotation', 'uneven', 'adjust'],
    soundOutChunks: ['ro', 'ta', 'tion', 'un', 'e', 'ven'],
    tags: ['fluency-practice', 'rereading', 'sentence-context-confirmation'],
    selectableSegments: [
      { id: 'rotor-cut-direction', text: 'Next, cut two short lines at the top to make rotor blades.' },
      { id: 'rotor-clip-direction', text: 'Then attach a paper clip at the bottom for balance.' },
      { id: 'rotor-adjust-direction', text: 'If the rotation looks uneven, adjust one blade and try again.' },
    ],
    correctSegmentIds: ['rotor-adjust-direction'],
  }),
  createMultiselectQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.paperRotor,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.guidedRereading,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedRereading[3]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.guidedRereading[3],
    prompt: 'Choose the two commas that divide the three actions in the rotor-release direction.',
    explanation: 'The commas after "space" and "it" divide the direction into three action groups.',
    evidenceReference: 'rotor-5',
    evidenceReferenceIds: ['rotor-space-comma', 'rotor-it-comma'],
    targetVocabulary: ['comma', 'release', 'action'],
    soundOutChunks: ['com', 'ma', 're', 'lease'],
    tags: ['fluency-practice', 'punctuation-pause', 'phrase-grouping'],
    choices: [
      { id: 'rotor-space-comma', text: 'space,' },
      { id: 'rotor-release-word', text: 'release' },
      { id: 'rotor-it-comma', text: 'it,' },
      { id: 'rotor-spin-period', text: 'spin.' },
    ],
    correctChoiceIds: ['rotor-space-comma', 'rotor-it-comma'],
  }),

  createMultipleChoiceQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.morningMarsh,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.independentDescription,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentDescription[0]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentDescription[0],
    prompt: 'Which words name one place and should be read together as a phrase?',
    explanation: '"the observation deck" names one place and should be kept together.',
    evidenceReference: 'marsh-3',
    evidenceReferenceIds: ['marsh-deck-phrase'],
    targetVocabulary: ['observation', 'deck', 'phrase'],
    soundOutChunks: ['ob', 'ser', 'va', 'tion'],
    tags: ['fluency-practice', 'phrase-grouping', 'automaticity-practice'],
    choices: [
      { id: 'marsh-deck-phrase', text: 'the observation deck' },
      { id: 'marsh-from-fragment', text: 'From the' },
      { id: 'marsh-children-fragment', text: 'deck, two' },
      { id: 'marsh-shore-fragment', text: 'searched the' },
    ],
    correctChoiceIds: ['marsh-deck-phrase'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.morningMarsh,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.independentDescription,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentDescription[1]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentDescription[1],
    prompt: 'Which words should be grouped to describe how the heron stood?',
    explanation: '"perfectly still" works together to describe how the heron stood.',
    evidenceReference: 'marsh-4',
    evidenceReferenceIds: ['marsh-still-phrase'],
    targetVocabulary: ['perfectly', 'still', 'heron'],
    soundOutChunks: ['per', 'fect', 'ly'],
    tags: ['fluency-practice', 'phrase-grouping', 'meaningful-emphasis'],
    choices: [
      { id: 'marsh-heron-fragment', text: 'A heron' },
      { id: 'marsh-still-phrase', text: 'perfectly still' },
      { id: 'marsh-beside-fragment', text: 'beside a' },
      { id: 'marsh-reflection-fragment', text: 'silver reflection' },
    ],
    correctChoiceIds: ['marsh-still-phrase'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.morningMarsh,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.independentDescription,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentDescription[2]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentDescription[2],
    prompt: 'Which line should be read with the strongest excitement?',
    explanation: '"What an amazing morning!" ends with an exclamation mark and directly expresses excitement.',
    evidenceReference: 'marsh-6',
    evidenceReferenceIds: ['marsh-amazing-line'],
    targetVocabulary: ['amazing', 'excitement', 'exclamation'],
    soundOutChunks: ['a', 'maz', 'ing'],
    tags: ['fluency-practice', 'exclamation-cue', 'expression-practice'],
    choices: [
      { id: 'marsh-light-line', text: 'Golden light spread across the quiet marsh.' },
      { id: 'marsh-heron-line', text: 'A heron stood perfectly still beside a silver reflection.' },
      { id: 'marsh-amazing-line', text: '"What an amazing morning!"' },
      { id: 'marsh-deck-line', text: 'From the observation deck, two children lifted their binoculars.' },
    ],
    correctChoiceIds: ['marsh-amazing-line'],
  }),
  createTableMatchQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.morningMarsh,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.independentDescription,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentDescription[3]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentDescription[3],
    prompt: 'Match each text cue to the reading choice it clearly supports.',
    explanation: 'The wording and punctuation identify a place phrase, a brief pause, a descriptive phrase, and an excited line.',
    evidenceReference: 'marsh fluency cues',
    evidenceReferenceIds: ['marsh-table-place-correct', 'marsh-table-pause-correct', 'marsh-table-description-correct', 'marsh-table-energy-correct'],
    targetVocabulary: ['phrase', 'pause', 'description', 'energy'],
    soundOutChunks: ['phrase', 'pause', 'en', 'er', 'gy'],
    tags: ['fluency-practice', 'phrase-grouping', 'expression-practice'],
    rows: [
      { id: 'marsh-table-place-row', prompt: 'the observation deck', correctChoiceId: 'marsh-table-place-correct', options: [
        { id: 'marsh-table-place-correct', text: 'read together as one place' },
        { id: 'marsh-table-place-pause', text: 'stop after every word' },
        { id: 'marsh-table-place-question', text: 'read as a question' },
        { id: 'marsh-table-place-energy', text: 'shout with excitement' },
      ] },
      { id: 'marsh-table-pause-row', prompt: 'From the observation deck,', correctChoiceId: 'marsh-table-pause-correct', options: [
        { id: 'marsh-table-pause-place', text: 'stop as if the sentence ended' },
        { id: 'marsh-table-pause-correct', text: 'pause briefly at the comma' },
        { id: 'marsh-table-pause-question', text: 'use a questioning voice' },
        { id: 'marsh-table-pause-energy', text: 'add excited energy' },
      ] },
      { id: 'marsh-table-description-row', prompt: 'perfectly still', correctChoiceId: 'marsh-table-description-correct', options: [
        { id: 'marsh-table-description-place', text: 'name a new place' },
        { id: 'marsh-table-description-pause', text: 'pause between both words' },
        { id: 'marsh-table-description-correct', text: 'read together as one description' },
        { id: 'marsh-table-description-energy', text: 'turn the words into an excited command' },
      ] },
      { id: 'marsh-table-energy-row', prompt: '"What an amazing morning!"', correctChoiceId: 'marsh-table-energy-correct', options: [
        { id: 'marsh-table-energy-place', text: 'read as a place name' },
        { id: 'marsh-table-energy-pause', text: 'break apart every word' },
        { id: 'marsh-table-energy-question', text: 'lift the voice as for a question' },
        { id: 'marsh-table-energy-correct', text: 'read with strong excitement' },
      ] },
    ],
  }),

  createMultipleChoiceQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.firstLaunch,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.independentLiterary,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentLiterary[0]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentLiterary[0],
    prompt: 'Which words should Mira read together as her brother\'s one helpful reminder?',
    explanation: '"Remember the steady pull" is one complete reminder inside the quotation marks.',
    evidenceReference: 'launch-3',
    evidenceReferenceIds: ['launch-reminder-phrase'],
    targetVocabulary: ['remember', 'steady', 'pull'],
    soundOutChunks: ['re', 'mem', 'ber', 'stead', 'y'],
    tags: ['fluency-practice', 'dialogue-phrasing', 'phrase-grouping'],
    choices: [
      { id: 'launch-reminder-phrase', text: 'Remember the steady pull' },
      { id: 'launch-brother-fragment', text: 'her brother said' },
      { id: 'launch-gently-word', text: 'gently' },
      { id: 'launch-quote-fragment', text: 'pull, her' },
    ],
    correctChoiceIds: ['launch-reminder-phrase'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.firstLaunch,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.independentLiterary,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentLiterary[1]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentLiterary[1],
    prompt: 'Which punctuation mark tells the reader that Mira\'s words have strong feeling?',
    explanation: 'The exclamation mark in "I did it!" shows Mira\'s strong joy.',
    evidenceReference: 'launch-6',
    evidenceReferenceIds: ['launch-exclamation-mark'],
    targetVocabulary: ['exclamation mark', 'strong feeling', 'joy'],
    soundOutChunks: ['ex', 'cla', 'ma', 'tion'],
    tags: ['fluency-practice', 'exclamation-cue', 'expression-practice'],
    choices: [
      { id: 'launch-comma-mark', text: 'comma' },
      { id: 'launch-period-mark', text: 'period' },
      { id: 'launch-question-mark', text: 'question mark' },
      { id: 'launch-exclamation-mark', text: 'exclamation mark' },
    ],
    correctChoiceIds: ['launch-exclamation-mark'],
  }),
  createHotTextQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.firstLaunch,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.independentLiterary,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentLiterary[2]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentLiterary[2],
    prompt: 'Select the sentence that should be reread slowly enough to show Mira\'s nervous feeling.',
    explanation: 'The sentence says that Mira practiced but her hands still trembled, which clearly signals nervousness.',
    evidenceReference: 'launch-2',
    evidenceReferenceIds: ['launch-nervous-sentence'],
    targetVocabulary: ['practiced', 'trembled', 'nervous'],
    soundOutChunks: ['prac', 'ticed', 'trem', 'bled'],
    tags: ['fluency-practice', 'rereading', 'meaningful-emphasis'],
    selectableSegments: [
      { id: 'launch-nervous-sentence', text: 'She had practiced every step, but her hands still trembled.' },
      { id: 'launch-kite-sentence', text: 'The red kite climbed past the treetops.' },
      { id: 'launch-circle-sentence', text: 'Her brother grinned, and Mira let the kite sail in a smooth circle.' },
    ],
    correctSegmentIds: ['launch-nervous-sentence'],
  }),
  createMultiselectQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.firstLaunch,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.independentLiterary,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentLiterary[3]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentLiterary[3],
    prompt: 'Choose the two quoted lines that call for clearly different character voices.',
    explanation: 'Her brother gives a gentle reminder, while Mira celebrates with an exclamation.',
    evidenceReference: 'launch-3 launch-6',
    evidenceReferenceIds: ['launch-gentle-line', 'launch-joy-line'],
    targetVocabulary: ['gentle', 'celebrate', 'character voice'],
    soundOutChunks: ['gen', 'tle', 'cel', 'e', 'brate'],
    tags: ['fluency-practice', 'dialogue-phrasing', 'expression-practice'],
    choices: [
      { id: 'launch-gentle-line', text: '"Remember the steady pull," her brother said gently.' },
      { id: 'launch-cloud-line', text: 'clouds hurried above the park' },
      { id: 'launch-joy-line', text: '"I did it!" she shouted.' },
      { id: 'launch-circle-line', text: 'the kite sail in a smooth circle' },
    ],
    correctChoiceIds: ['launch-gentle-line', 'launch-joy-line'],
  }),

  createMultipleChoiceQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.geeseFormation,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.independentInformational,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentInformational[0]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentInformational[0],
    prompt: 'Which two words should be read together because they name the birds being explained?',
    explanation: '"Migrating geese" names the birds that the passage explains.',
    evidenceReference: 'geese-1',
    evidenceReferenceIds: ['geese-subject-phrase'],
    targetVocabulary: ['migrating', 'geese', 'phrase'],
    soundOutChunks: ['mi', 'grat', 'ing', 'geese'],
    tags: ['fluency-practice', 'phrase-grouping', 'automaticity-practice'],
    choices: [
      { id: 'geese-subject-phrase', text: 'Migrating geese' },
      { id: 'geese-often-fragment', text: 'geese often' },
      { id: 'geese-v-fragment', text: 'a V-shaped' },
      { id: 'geese-formation-fragment', text: 'formation.' },
    ],
    correctChoiceIds: ['geese-subject-phrase'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.geeseFormation,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.independentInformational,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentInformational[1]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentInformational[1],
    prompt: 'Where should the reader pause briefly in the sentence about the tired lead goose?',
    explanation: 'The comma after "tired" marks a brief pause before the sentence continues.',
    evidenceReference: 'geese-4',
    evidenceReferenceIds: ['geese-tired-comma'],
    targetVocabulary: ['lead goose', 'tired', 'comma'],
    soundOutChunks: ['tired', 'com', 'ma'],
    tags: ['fluency-practice', 'punctuation-pause', 'accuracy-practice'],
    choices: [
      { id: 'geese-after-when', text: 'after "When"' },
      { id: 'geese-after-lead', text: 'after "lead"' },
      { id: 'geese-tired-comma', text: 'after "tired"' },
      { id: 'geese-after-another', text: 'after "another"' },
    ],
    correctChoiceIds: ['geese-tired-comma'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.geeseFormation,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.independentInformational,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentInformational[2]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentInformational[2],
    prompt: 'Which grouping keeps the two actions in the wing sentence clear?',
    explanation: '"move the air" and "create a helpful current" are the two connected actions joined by "and."',
    evidenceReference: 'geese-2',
    evidenceReferenceIds: ['geese-actions-grouping'],
    targetVocabulary: ['move', 'create', 'current'],
    soundOutChunks: ['move', 'cre', 'ate', 'cur', 'rent'],
    tags: ['fluency-practice', 'phrase-grouping', 'sentence-context-confirmation'],
    choices: [
      { id: 'geese-actions-grouping', text: 'Two complete actions: move the air | and create a helpful current' },
      { id: 'geese-actions-grouping-2', text: 'Break after move: move | the air and create a helpful current' },
      { id: 'geese-actions-grouping-3', text: 'Break after the: move the | air and create a helpful current' },
      { id: 'geese-actions-grouping-4', text: 'Break before helpful: move the air and create a | helpful current' },
    ],
    correctChoiceIds: ['geese-actions-grouping'],
  }),
  createTableMatchQuestion({
    ...common,
    passageIdentifier: GRADE3_FLUENCY_FLIGHT_PASSAGE_IDS.geeseFormation,
    lessonIdentifier: GRADE3_FLUENCY_FLIGHT_LESSON_IDS.independentInformational,
    activityIdentifier: activity(GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentInformational[3]),
    questionIdentifier: GRADE3_FLUENCY_FLIGHT_QUESTION_IDS.independentInformational[3],
    prompt: 'Match each part of the geese passage to the reading choice it supports.',
    explanation: 'The text gives clear cues for a subject phrase, a short comma pause, a complete action phrase, and a full stop.',
    evidenceReference: 'geese fluency cues',
    evidenceReferenceIds: ['geese-table-subject-correct', 'geese-table-pause-correct', 'geese-table-action-correct', 'geese-table-stop-correct'],
    targetVocabulary: ['phrase', 'pause', 'action', 'full stop'],
    soundOutChunks: ['phrase', 'pause', 'ac', 'tion'],
    tags: ['fluency-practice', 'phrase-grouping', 'punctuation-cues'],
    rows: [
      { id: 'geese-table-subject-row', prompt: 'Migrating geese', correctChoiceId: 'geese-table-subject-correct', options: [
        { id: 'geese-table-subject-correct', text: 'read together as the subject' },
        { id: 'geese-table-subject-pause', text: 'pause between the words' },
        { id: 'geese-table-subject-stop', text: 'make a full stop' },
        { id: 'geese-table-subject-question', text: 'read as a question' },
      ] },
      { id: 'geese-table-pause-row', prompt: 'becomes tired,', correctChoiceId: 'geese-table-pause-correct', options: [
        { id: 'geese-table-pause-subject', text: 'read as the sentence subject' },
        { id: 'geese-table-pause-correct', text: 'pause briefly at the comma' },
        { id: 'geese-table-pause-stop', text: 'stop completely at that comma' },
        { id: 'geese-table-pause-question', text: 'ask the phrase as a question' },
      ] },
      { id: 'geese-table-action-row', prompt: 'create a helpful current', correctChoiceId: 'geese-table-action-correct', options: [
        { id: 'geese-table-action-subject', text: 'treat it as the opening subject' },
        { id: 'geese-table-action-pause', text: 'pause after every word' },
        { id: 'geese-table-action-correct', text: 'read together as one action' },
        { id: 'geese-table-action-question', text: 'use a questioning voice' },
      ] },
      { id: 'geese-table-stop-row', prompt: 'during a long journey.', correctChoiceId: 'geese-table-stop-correct', options: [
        { id: 'geese-table-stop-subject', text: 'begin a new subject' },
        { id: 'geese-table-stop-pause', text: 'pause briefly but continue' },
        { id: 'geese-table-stop-correct', text: 'make a full stop at the period' },
        { id: 'geese-table-stop-question', text: 'ask it as a question' },
      ] },
    ],
  }),
]
