import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
  lessonChoice as choice,
} from './questionFactories'
import {
  purposePathContentVersion,
  purposePathFeatureIds,
  purposePathLessonIds,
  purposePathPassageIds,
  purposePathQuestionIds,
  purposePathSentenceIds,
} from './ids'
import { pollinatorPatchSentences, weatherStationSentences } from './passages'

const base = {
  benchmarkReference: 'ELA.2.R.2.3' as const,
  skillIdentifier: 'g2-information-detectives-reading' as const,
  reportingCategory: 'Reading Informational Text' as const,
  genre: 'informational' as const,
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2' as const,
  contentVersion: purposePathContentVersion,
  reviewStatus: 'DRAFT' as const,
}

export const purposePathGuidedQuestions = [
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.beePollenPath.passageId,
    lessonIdentifier: purposePathLessonIds.guidedExplainWhatTryingToExplain,
    questionIdentifier: purposePathQuestionIds.guidedExplainWhatTryingToExplain[0],
    prompt: 'What is the topic of this passage?',
    explanation: 'The topic is a short phrase that names what the passage is about.',
    evidenceReference: purposePathFeatureIds.beePollenPath.title,
    evidenceReferenceIds: [purposePathFeatureIds.beePollenPath.title],
    targetVocabulary: ['topic'],
    soundOutChunks: ['top', 'ic'],
    tags: ['informational-author-purpose', 'purpose-vs-topic'],
    choices: [
      choice('pollinator-topic', 'pollinator patch counts'),
      choice('weather-topic', 'weather tools'),
      choice('seed-topic', 'seed travel routes'),
      choice('compost-topic', 'compost piles'),
    ],
    correctChoiceIds: ['pollinator-topic'],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.beePollenPath.passageId,
    lessonIdentifier: purposePathLessonIds.guidedExplainWhatTryingToExplain,
    questionIdentifier: purposePathQuestionIds.guidedExplainWhatTryingToExplain[1],
    prompt: 'Which sentence is the best author purpose?',
    explanation: 'The author purpose is a complete thought that brings the details together.',
    evidenceReference: purposePathSentenceIds.beePollenPath[7],
    evidenceReferenceIds: [purposePathSentenceIds.beePollenPath[7]],
    targetVocabulary: ['author purpose', 'complete thought'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['informational-author-purpose', 'author-purpose-specific', 'purpose-vs-central-idea', 'purpose-from-multiple-sections'],
    choices: [
      choice('pollinator-detail-1', 'The sunny row had the tallest stems near the path.'),
      choice('pollinator-detail-2', 'The class counted three kinds of blooms in the sunny row.'),
      choice('pollinator-central', 'A pollinator garden gives insects places to find food and rest.'),
      choice('pollinator-detail-3', 'The shady row had fewer blooms but more leaves.'),
    ],
    correctChoiceIds: ['pollinator-central'],
  }),
  createMultiselectQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.beePollenPath.passageId,
    lessonIdentifier: purposePathLessonIds.guidedExplainWhatTryingToExplain,
    questionIdentifier: purposePathQuestionIds.guidedExplainWhatTryingToExplain[2],
    prompt: 'Choose two details that are most relevant to the author purpose.',
    explanation: 'The best details help readers see how the class compares the patch and notices insect visits.',
    evidenceReference: purposePathFeatureIds.beePollenPath.caption,
    evidenceReferenceIds: [
      purposePathSentenceIds.beePollenPath[1],
      purposePathSentenceIds.beePollenPath[2],
    ],
    targetVocabulary: ['relevant detail', 'compare', 'observe'],
    soundOutChunks: ['re', 'le', 'vant'],
    tags: ['purpose-vs-detail', 'purpose-vs-detail'],
    choices: [
      choice('pollinator-blue', 'The graph shows more blue flowers than red ones there.'),
      choice('pollinator-bees', 'Bees visited the sunny row most often on warm mornings.'),
      choice('pollinator-balance', 'The shady row had fewer blooms but more leaves.'),
      choice('pollinator-stems', 'The sunny row also had the tallest stems near the path.'),
    ],
    correctChoiceIds: ['pollinator-blue', 'pollinator-bees'],
  }),
  createHotTextQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.beePollenPath.passageId,
    lessonIdentifier: purposePathLessonIds.guidedExplainWhatTryingToExplain,
    questionIdentifier: purposePathQuestionIds.guidedExplainWhatTryingToExplain[3],
    prompt: 'Tap the sentence that best helps readers understand the author purpose.',
    explanation: 'This sentence puts the passage idea into a complete thought.',
    evidenceReference: purposePathSentenceIds.beePollenPath[7],
    evidenceReferenceIds: [purposePathSentenceIds.beePollenPath[7]],
    targetVocabulary: ['author purpose'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['informational-author-purpose', 'purpose-from-text-clues'],
    selectableSegments: [
      { id: purposePathSentenceIds.beePollenPath[0], text: pollinatorPatchSentences[0].text },
      { id: purposePathSentenceIds.beePollenPath[2], text: pollinatorPatchSentences[2].text },
      { id: purposePathSentenceIds.beePollenPath[6], text: pollinatorPatchSentences[6].text },
      { id: purposePathSentenceIds.beePollenPath[7], text: pollinatorPatchSentences[7].text },
    ],
    correctSegmentIds: [purposePathSentenceIds.beePollenPath[7]],
  }),
  createTableMatchQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.beePollenPath.passageId,
    lessonIdentifier: purposePathLessonIds.guidedExplainWhatTryingToExplain,
    questionIdentifier: purposePathQuestionIds.guidedExplainWhatTryingToExplain[4],
    prompt: 'Match each statement to the best answer.',
    explanation: 'Each row matches a statement to the idea it names.',
    evidenceReference: purposePathFeatureIds.beePollenPath.glossary,
    evidenceReferenceIds: [
      purposePathFeatureIds.beePollenPath.title,
      purposePathSentenceIds.beePollenPath[7],
    ],
    targetVocabulary: ['topic', 'detail', 'author purpose'],
    soundOutChunks: ['stat', 'e', 'ment'],
    tags: ['purpose-supported-by-text', 'purpose-from-multiple-sections'],
    rows: [
      {
        id: 'pollinator-topic',
        prompt: 'What is the topic?',
        correctChoiceId: 'pollinator-topic-answer',
        options: [
          choice('pollinator-topic-answer', 'pollinator patch counts'),
          choice('pollinator-topic-detail', 'Bees visited the sunny row most often on warm mornings.'),
          choice('pollinator-topic-other', 'The shady row had fewer blooms but more leaves.'),
        ],
      },
      {
        id: 'pollinator-central',
        prompt: 'What is the author purpose?',
        correctChoiceId: 'pollinator-central-answer',
        options: [
          choice('pollinator-central-answer', 'A pollinator garden gives insects places to find food and rest.'),
          choice('pollinator-central-other1', 'The graph shows more blue flowers than red ones there.'),
          choice('pollinator-central-other2', 'The sunny row also had the tallest stems near the path.'),
        ],
      },
      {
        id: 'pollinator-other',
        prompt: 'Which is another true detail?',
        correctChoiceId: 'pollinator-other-answer',
        options: [
          choice('pollinator-other-answer', 'The shady row had fewer blooms but more leaves.'),
          choice('pollinator-other-topic', 'pollinator patch counts'),
          choice('pollinator-other-central', 'A pollinator garden gives insects places to find food and rest.'),
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.trailMarkerSystem.passageId,
    lessonIdentifier: purposePathLessonIds.guidedUseWholeTextPurpose,
    questionIdentifier: purposePathQuestionIds.guidedUseWholeTextPurpose[0],
    prompt: 'What is the topic of this passage?',
    explanation: 'The topic is a short phrase that names what the passage is about.',
    evidenceReference: purposePathFeatureIds.trailMarkerSystem.title,
    evidenceReferenceIds: [purposePathFeatureIds.trailMarkerSystem.title],
    targetVocabulary: ['topic'],
    soundOutChunks: ['top', 'ic'],
    tags: ['informational-author-purpose', 'purpose-vs-topic'],
    choices: [
      choice('weather-topic', 'weather station notes'),
      choice('compost-topic', 'compost piles'),
      choice('seed-topic', 'seed travel routes'),
      choice('pollinator-topic', 'pollinator patch counts'),
    ],
    correctChoiceIds: ['weather-topic'],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.trailMarkerSystem.passageId,
    lessonIdentifier: purposePathLessonIds.guidedUseWholeTextPurpose,
    questionIdentifier: purposePathQuestionIds.guidedUseWholeTextPurpose[1],
    prompt: 'Which sentence is the best author purpose?',
    explanation: 'The author purpose is the complete thought that the details point to.',
    evidenceReference: purposePathSentenceIds.trailMarkerSystem[7],
    evidenceReferenceIds: [purposePathSentenceIds.trailMarkerSystem[7]],
    targetVocabulary: ['author purpose', 'observations'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['informational-author-purpose', 'author-purpose-specific', 'purpose-vs-central-idea', 'purpose-from-text-clues'],
    choices: [
      choice('weather-detail-1', 'A wind sock points the direction the wind blows.'),
      choice('weather-central', 'With tools and careful observations, the class learns more about weather.'),
      choice('weather-detail-2', 'A thermometer tells the class if the air feels warmer or cooler.'),
      choice('weather-detail-3', 'A student circles cloudy days on the chart so the group can check them later.'),
    ],
    correctChoiceIds: ['weather-central'],
  }),
  createMultiselectQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.trailMarkerSystem.passageId,
    lessonIdentifier: purposePathLessonIds.guidedUseWholeTextPurpose,
    questionIdentifier: purposePathQuestionIds.guidedUseWholeTextPurpose[2],
    prompt: 'Choose two details that are most relevant to the author purpose.',
    explanation: 'These details show how the class uses tools and records to learn about weather.',
    evidenceReference: purposePathFeatureIds.trailMarkerSystem.caption,
    evidenceReferenceIds: [
      purposePathSentenceIds.trailMarkerSystem[0],
      purposePathSentenceIds.trailMarkerSystem[2],
    ],
    targetVocabulary: ['relevant detail', 'weather', 'chart'],
    soundOutChunks: ['re', 'le', 'vant'],
    tags: ['purpose-vs-detail', 'purpose-vs-detail'],
    choices: [
      choice('weather-thermometer', 'A thermometer tells the class if the air feels warmer or cooler.'),
      choice('weather-chart', 'The class records the numbers in a chart each afternoon.'),
      choice('weather-clouds', 'A student circles cloudy days on the chart so the group can check them later.'),
      choice('weather-wind', 'A wind sock points the direction the wind blows.'),
    ],
    correctChoiceIds: ['weather-thermometer', 'weather-chart'],
  }),
  createHotTextQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.trailMarkerSystem.passageId,
    lessonIdentifier: purposePathLessonIds.guidedUseWholeTextPurpose,
    questionIdentifier: purposePathQuestionIds.guidedUseWholeTextPurpose[3],
    prompt: 'Tap the sentence that best helps readers understand the author purpose.',
    explanation: 'This sentence brings the weather tools and notes together into one idea.',
    evidenceReference: purposePathSentenceIds.trailMarkerSystem[7],
    evidenceReferenceIds: [purposePathSentenceIds.trailMarkerSystem[7]],
    targetVocabulary: ['author purpose'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['informational-author-purpose', 'purpose-from-text-clues'],
    selectableSegments: [
      { id: purposePathSentenceIds.trailMarkerSystem[1], text: weatherStationSentences[1].text },
      { id: purposePathSentenceIds.trailMarkerSystem[4], text: weatherStationSentences[4].text },
      { id: purposePathSentenceIds.trailMarkerSystem[6], text: weatherStationSentences[6].text },
      { id: purposePathSentenceIds.trailMarkerSystem[7], text: weatherStationSentences[7].text },
    ],
    correctSegmentIds: [purposePathSentenceIds.trailMarkerSystem[7]],
  }),
  createTableMatchQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.trailMarkerSystem.passageId,
    lessonIdentifier: purposePathLessonIds.guidedUseWholeTextPurpose,
    questionIdentifier: purposePathQuestionIds.guidedUseWholeTextPurpose[4],
    prompt: 'Match each statement to the best answer.',
    explanation: 'Each row matches a statement to the kind of information it gives.',
    evidenceReference: purposePathFeatureIds.trailMarkerSystem.glossary,
    evidenceReferenceIds: [
      purposePathFeatureIds.trailMarkerSystem.title,
      purposePathSentenceIds.trailMarkerSystem[7],
    ],
    targetVocabulary: ['topic', 'author purpose', 'detail'],
    soundOutChunks: ['stat', 'e', 'ment'],
    tags: ['purpose-supported-by-text', 'purpose-from-multiple-sections'],
    rows: [
      {
        id: 'weather-topic',
        prompt: 'What is the topic?',
        correctChoiceId: 'weather-topic-answer',
        options: [
          choice('weather-topic-answer', 'weather station notes'),
          choice('weather-topic-detail', 'A rain gauge shows how much rain fell overnight.'),
          choice('weather-topic-other', 'A student circles cloudy days on the chart.'),
        ],
      },
      {
        id: 'weather-central',
        prompt: 'What is the author purpose?',
        correctChoiceId: 'weather-central-answer',
        options: [
          choice('weather-central-answer', 'With tools and careful observations, the class learns more about weather.'),
          choice('weather-central-other1', 'A thermometer tells the class if the air feels warmer or cooler.'),
          choice('weather-central-other2', 'The class records the numbers in a chart each afternoon.'),
        ],
      },
      {
        id: 'weather-other',
        prompt: 'Which is another true detail?',
        correctChoiceId: 'weather-other-answer',
        options: [
          choice('weather-other-answer', 'A wind sock points the direction the wind blows.'),
          choice('weather-other-topic', 'weather station notes'),
          choice('weather-other-central', 'With tools and careful observations, the class learns more about weather.'),
        ],
      },
    ],
  }),
] as const







