import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
  lessonChoice as choice,
} from './questionFactories'
import {
  purposePathContentVersion,
  purposePathFeatureIds,
  purposePathLessonIds,
  purposePathPassageIds,
  purposePathQuestionIds,
  purposePathSentenceIds,
} from './ids'
import { quietShelterSentences, rainGardenSentences } from './passages'

const base = {
  benchmarkReference: 'ELA.2.R.2.3' as const,
  skillIdentifier: 'g2-information-detectives-reading' as const,
  reportingCategory: 'Reading Informational Text' as const,
  genre: 'informational' as const,
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2' as const,
  contentVersion: purposePathContentVersion,
  reviewStatus: 'DRAFT' as const,
}

export const purposePathPrerequisiteQuestions = [
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: purposePathPassageIds.rainGaugeReadings.passageId,
    lessonIdentifier: purposePathLessonIds.prereqTopicPurposeDetail,
    questionIdentifier: purposePathQuestionIds.prereqTopicPurposeDetail[0],
    prompt: 'What is the topic of this passage?',
    explanation: 'Rain gardens is a short topic phrase. It tells what the passage is about.',
    evidenceReference: purposePathFeatureIds.rainGaugeReadings.title,
    evidenceReferenceIds: [purposePathFeatureIds.rainGaugeReadings.title],
    targetVocabulary: ['topic'],
    soundOutChunks: ['rain', 'garden'],
    tags: ['informational-author-purpose', 'purpose-vs-topic'],
    choices: [
      choice('rain-gardens', 'rain gardens'),
      choice('water-rushes', 'water that rushes away'),
      choice('flower-blooming', 'flowers in bloom'),
      choice('safe-place', 'a safer place to grow'),
    ],
    correctChoiceIds: ['rain-gardens'],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: purposePathPassageIds.rainGaugeReadings.passageId,
    lessonIdentifier: purposePathLessonIds.prereqTopicPurposeDetail,
    questionIdentifier: purposePathQuestionIds.prereqTopicPurposeDetail[1],
    prompt: 'Which sentence is the best author purpose?',
    explanation: 'The best author purpose is a complete thought about the topic, not just one detail.',
    evidenceReference: purposePathSentenceIds.rainGaugeReadings[7],
    evidenceReferenceIds: [purposePathSentenceIds.rainGaugeReadings[7]],
    targetVocabulary: ['author purpose', 'complete thought'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['informational-author-purpose', 'author-purpose-specific', 'purpose-vs-central-idea', 'purpose-from-text-clues'],
    choices: [
      choice('detail-catch', 'A rain garden is a shallow bed that catches rain.'),
      choice('central-soak', 'A rain garden helps water soak in and gives plants a safer place to grow.'),
      choice('detail-rocks', 'Small rocks keep water from rushing away too fast.'),
      choice('detail-bloom', 'Bees and butterflies can visit the flowers.'),
    ],
    correctChoiceIds: ['central-soak'],
  }),
  createMultiselectQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: purposePathPassageIds.rainGaugeReadings.passageId,
    lessonIdentifier: purposePathLessonIds.prereqTopicPurposeDetail,
    questionIdentifier: purposePathQuestionIds.prereqTopicPurposeDetail[2],
    prompt: 'Choose two details that are most relevant to the author purpose.',
    explanation: 'The most relevant details tell how the rain garden catches water and holds it safely.',
    evidenceReference: purposePathSentenceIds.rainGaugeReadings[1],
    evidenceReferenceIds: [
      purposePathSentenceIds.rainGaugeReadings[0],
      purposePathSentenceIds.rainGaugeReadings[1],
    ],
    targetVocabulary: ['relevant detail', 'water', 'soil'],
    soundOutChunks: ['re', 'le', 'vant', 'de', 'tail'],
    tags: ['purpose-vs-detail', 'purpose-vs-detail'],
    choices: [
      choice('bed-catches-rain', 'The bed catches rain from a roof or walkway.'),
      choice('soil-holds-water', 'The soil holds the water for a little while.'),
      choice('bees-bloom', 'Bees and butterflies can visit the flowers.'),
      choice('children-watch', 'Children can watch how water disappears after a storm.'),
    ],
    correctChoiceIds: ['bed-catches-rain', 'soil-holds-water'],
  }),
  createHotTextQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: purposePathPassageIds.rainGaugeReadings.passageId,
    lessonIdentifier: purposePathLessonIds.prereqTopicPurposeDetail,
    questionIdentifier: purposePathQuestionIds.prereqTopicPurposeDetail[3],
    prompt: 'Tap the sentence that states the author purpose.',
    explanation: 'This sentence says the biggest point the reader should understand.',
    evidenceReference: purposePathSentenceIds.rainGaugeReadings[7],
    evidenceReferenceIds: [purposePathSentenceIds.rainGaugeReadings[7]],
    targetVocabulary: ['author purpose'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['informational-author-purpose', 'purpose-from-text-clues'],
    selectableSegments: [
      { id: purposePathSentenceIds.rainGaugeReadings[0], text: rainGardenSentences[0].text },
      { id: purposePathSentenceIds.rainGaugeReadings[1], text: rainGardenSentences[1].text },
      { id: purposePathSentenceIds.rainGaugeReadings[4], text: rainGardenSentences[4].text },
      { id: purposePathSentenceIds.rainGaugeReadings[7], text: rainGardenSentences[7].text },
    ],
    correctSegmentIds: [purposePathSentenceIds.rainGaugeReadings[7]],
  }),
  createTableMatchQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: purposePathPassageIds.rainGaugeReadings.passageId,
    lessonIdentifier: purposePathLessonIds.prereqTopicPurposeDetail,
    questionIdentifier: purposePathQuestionIds.prereqTopicPurposeDetail[4],
    prompt: 'Match each statement to the best answer.',
    explanation: 'Each row matches a statement to the idea it names.',
    evidenceReference: purposePathFeatureIds.rainGaugeReadings.caption,
    evidenceReferenceIds: [purposePathFeatureIds.rainGaugeReadings.caption, purposePathSentenceIds.rainGaugeReadings[7]],
    targetVocabulary: ['topic', 'detail', 'author purpose'],
    soundOutChunks: ['stat', 'e', 'ment'],
    tags: ['purpose-supported-by-text', 'purpose-vs-topic'],
    rows: [
      {
        id: 'rain-topic',
        prompt: 'What is the topic?',
        correctChoiceId: 'rain-topic-answer',
        options: [
          choice('rain-topic-answer', 'rain gardens'),
          choice('rain-detail-answer', 'The soil holds the water for a little while.'),
          choice('rain-other-answer', 'Bees and butterflies can visit the flowers.'),
        ],
      },
      {
        id: 'rain-central',
        prompt: 'What is the author purpose?',
        correctChoiceId: 'rain-central-answer',
        options: [
          choice('rain-central-answer', 'A rain garden helps water soak in and gives plants a safer place to grow.'),
          choice('rain-other1-answer', 'Small rocks keep the water from rushing away too fast.'),
          choice('rain-other2-answer', 'Children can watch how water disappears after a storm.'),
        ],
      },
      {
        id: 'rain-other',
        prompt: 'Which is another true detail?',
        correctChoiceId: 'rain-other-answer-2',
        options: [
          choice('rain-other-answer-2', 'Bees and butterflies can visit the flowers.'),
          choice('rain-topic-answer-2', 'rain gardens'),
          choice('rain-central-answer-2', 'A rain garden helps water soak in and gives plants a safer place to grow.'),
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: purposePathPassageIds.nestBuilderNotes.passageId,
    lessonIdentifier: purposePathLessonIds.prereqFindAuthorGoal,
    questionIdentifier: purposePathQuestionIds.prereqFindAuthorGoal[0],
    prompt: 'What is the topic of this passage?',
    explanation: 'The topic is a short phrase that names what the passage is about.',
    evidenceReference: purposePathFeatureIds.nestBuilderNotes.title,
    evidenceReferenceIds: [purposePathFeatureIds.nestBuilderNotes.title],
    targetVocabulary: ['topic'],
    soundOutChunks: ['an', 'i', 'mal'],
    tags: ['informational-author-purpose', 'purpose-vs-topic'],
    choices: [
      choice('quiet-shelter-topic', 'animal shelters'),
      choice('soft-beds', 'soft beds'),
      choice('low-lights', 'low lights'),
      choice('one-way-paths', 'one-way paths'),
    ],
    correctChoiceIds: ['quiet-shelter-topic'],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: purposePathPassageIds.nestBuilderNotes.passageId,
    lessonIdentifier: purposePathLessonIds.prereqFindAuthorGoal,
    questionIdentifier: purposePathQuestionIds.prereqFindAuthorGoal[1],
    prompt: 'Which sentence is the best author purpose?',
    explanation: 'The author purpose is the main complete thought about the shelter.',
    evidenceReference: purposePathSentenceIds.nestBuilderNotes[7],
    evidenceReferenceIds: [purposePathSentenceIds.nestBuilderNotes[7]],
    targetVocabulary: ['author purpose', 'safe', 'settle'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['informational-author-purpose', 'author-purpose-specific', 'purpose-vs-central-idea', 'purpose-from-multiple-sections'],
    choices: [
      choice('quiet-detail-1', 'The shelter has soft beds, low lights, and water bowls.'),
      choice('quiet-detail-2', 'Each animal gets a small space where it can rest without much noise.'),
      choice('quiet-central', 'A quiet shelter helps animals feel safe and settle in.'),
      choice('quiet-detail-3', 'Helpers clean the rooms every day and refill the bowls before visitors arrive.'),
    ],
    correctChoiceIds: ['quiet-central'],
  }),
  createMultiselectQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: purposePathPassageIds.nestBuilderNotes.passageId,
    lessonIdentifier: purposePathLessonIds.prereqFindAuthorGoal,
    questionIdentifier: purposePathQuestionIds.prereqFindAuthorGoal[2],
    prompt: 'Choose two details that are most relevant to the author purpose.',
    explanation: 'The best details help readers see how the shelter stays calm and safe.',
    evidenceReference: purposePathSentenceIds.nestBuilderNotes[1],
    evidenceReferenceIds: [
      purposePathSentenceIds.nestBuilderNotes[1],
      purposePathSentenceIds.nestBuilderNotes[3],
    ],
    targetVocabulary: ['relevant detail', 'quiet', 'safe'],
    soundOutChunks: ['re', 'le', 'vant'],
    tags: ['purpose-vs-detail', 'purpose-vs-detail'],
    choices: [
      choice('quiet-rest', 'Each animal gets a small space where it can rest without much noise.'),
      choice('quiet-path', 'Visitors follow one-way paths so the animals do not feel crowded.'),
      choice('quiet-list', 'The front desk keeps a simple list of the animals who need extra rest.'),
      choice('quiet-clean', 'Helpers clean the rooms every day and refill the bowls before visitors arrive.'),
    ],
    correctChoiceIds: ['quiet-rest', 'quiet-path'],
  }),
  createHotTextQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: purposePathPassageIds.nestBuilderNotes.passageId,
    lessonIdentifier: purposePathLessonIds.prereqFindAuthorGoal,
    questionIdentifier: purposePathQuestionIds.prereqFindAuthorGoal[3],
    prompt: 'Tap the sentence that best helps readers understand the author purpose.',
    explanation: 'This sentence gives a detail that shows how the shelter feels calm.',
    evidenceReference: purposePathSentenceIds.nestBuilderNotes[7],
    evidenceReferenceIds: [purposePathSentenceIds.nestBuilderNotes[7]],
    targetVocabulary: ['detail', 'safe'],
    soundOutChunks: ['de', 'tail'],
    tags: ['purpose-vs-detail', 'purpose-from-multiple-sections'],
    selectableSegments: [
      { id: purposePathSentenceIds.nestBuilderNotes[0], text: quietShelterSentences[0].text },
      { id: purposePathSentenceIds.nestBuilderNotes[1], text: quietShelterSentences[1].text },
      { id: purposePathSentenceIds.nestBuilderNotes[3], text: quietShelterSentences[3].text },
      { id: purposePathSentenceIds.nestBuilderNotes[7], text: quietShelterSentences[7].text },
    ],
    correctSegmentIds: [purposePathSentenceIds.nestBuilderNotes[7]],
  }),
  createTableMatchQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: purposePathPassageIds.nestBuilderNotes.passageId,
    lessonIdentifier: purposePathLessonIds.prereqFindAuthorGoal,
    questionIdentifier: purposePathQuestionIds.prereqFindAuthorGoal[4],
    prompt: 'Match each statement to the best answer.',
    explanation: 'Each row matches a statement to the kind of information it gives.',
    evidenceReference: purposePathFeatureIds.nestBuilderNotes.caption,
    evidenceReferenceIds: [purposePathFeatureIds.nestBuilderNotes.caption, purposePathSentenceIds.nestBuilderNotes[7]],
    targetVocabulary: ['topic', 'author purpose', 'detail'],
    soundOutChunks: ['stat', 'e', 'ment'],
    tags: ['purpose-supported-by-text', 'purpose-from-multiple-sections'],
    rows: [
      {
        id: 'quiet-topic',
        prompt: 'What is the topic?',
        correctChoiceId: 'quiet-topic-answer',
        options: [
          choice('quiet-topic-answer', 'animal shelters'),
          choice('quiet-topic-detail', 'one-way paths'),
          choice('quiet-topic-other', 'water bowls'),
        ],
      },
      {
        id: 'quiet-central',
        prompt: 'What is the author purpose?',
        correctChoiceId: 'quiet-central-answer',
        options: [
          choice('quiet-central-answer', 'A quiet shelter helps animals feel safe and settle in.'),
          choice('quiet-central-other1', 'Helpers clean the rooms every day.'),
          choice('quiet-central-other2', 'Visitors follow one-way paths.'),
        ],
      },
      {
        id: 'quiet-other',
        prompt: 'Which is another true detail?',
        correctChoiceId: 'quiet-other-answer',
        options: [
          choice('quiet-other-answer', 'The front desk keeps a simple list of the animals who need extra rest.'),
          choice('quiet-other-topic', 'animal shelters'),
          choice('quiet-other-central', 'A quiet shelter helps animals feel safe and settle in.'),
        ],
      },
    ],
  }),
]







