import {
  createEvidencePairQuestion,
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
  lessonChoice as choice,
} from './questionFactories'
import {
  purposePathContentVersion,
  purposePathFeatureIds,
  purposePathLessonIds,
  purposePathPassageIds,
  purposePathQuestionIds,
  purposePathSentenceIds,
} from './ids'
import { compostChangeSentences, seedTravelSentences, trailMarkerSentences } from './passages'

const base = {
  benchmarkReference: 'ELA.2.R.2.3' as const,
  skillIdentifier: 'g2-information-detectives-reading' as const,
  reportingCategory: 'Reading Informational Text' as const,
  genre: 'informational' as const,
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2' as const,
  contentVersion: purposePathContentVersion,
  reviewStatus: 'DRAFT' as const,
}

export const purposePathCheckpointQuestions = [
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.shadeGardenStudy.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointA,
    questionIdentifier: purposePathQuestionIds.checkpointA[0],
    prompt: 'What is the topic of this passage?',
    explanation: 'The topic is a short phrase that names what the passage is about.',
    evidenceReference: purposePathFeatureIds.shadeGardenStudy.title,
    evidenceReferenceIds: [purposePathFeatureIds.shadeGardenStudy.title],
    targetVocabulary: ['topic'],
    soundOutChunks: ['top', 'ic'],
    tags: ['informational-author-purpose', 'purpose-vs-topic'],
    choices: [
      choice('seed-topic', 'seed travel routes'),
      choice('compost-topic', 'compost piles'),
      choice('trail-topic', 'trail markers'),
      choice('weather-topic', 'weather stations'),
    ],
    correctChoiceIds: ['seed-topic'],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.shadeGardenStudy.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointA,
    questionIdentifier: purposePathQuestionIds.checkpointA[1],
    prompt: 'Why did the author most likely write this passage?',
    explanation: 'The author wrote this passage to explain several ways seeds travel to new places.',
    evidenceReference: purposePathFeatureIds.shadeGardenStudy.headingC,
    evidenceReferenceIds: [purposePathFeatureIds.shadeGardenStudy.headingC],
    targetVocabulary: ['author purpose', 'complete thought'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['informational-author-purpose', 'author-purpose-specific', 'purpose-vs-central-idea', 'purpose-from-multiple-sections'],
    choices: [
      choice('seed-detail-1', 'To tell a made-up story about a traveling seed.'),
      choice('seed-central', 'To explain several ways seeds travel to new places.'),
      choice('seed-detail-2', 'To give directions for planting one seed packet.'),
      choice('seed-detail-3', 'To persuade readers that seeds travel only by wind.'),
    ],
    correctChoiceIds: ['seed-central'],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.shadeGardenStudy.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointA,
    questionIdentifier: purposePathQuestionIds.checkpointA[2],
    prompt: 'Which detail is most relevant to the author purpose?',
    explanation: 'This detail shows one way a seed can travel to a new place.',
    evidenceReference: purposePathFeatureIds.shadeGardenStudy.caption,
    evidenceReferenceIds: [purposePathSentenceIds.shadeGardenStudy[0]],
    targetVocabulary: ['relevant detail', 'travel'],
    soundOutChunks: ['re', 'le', 'vant'],
    tags: ['purpose-vs-detail', 'purpose-vs-detail'],
    choices: [
      choice('seed-water', 'Some float on water after a rain.'),
      choice('seed-room', 'That new spot can give the plant sun, soil, and room to grow.'),
      choice('seed-fur', 'Sticky seeds ride on fur or feathers.'),
      choice('seed-shoes', 'A few seeds even hitch a ride on shoes or socks.'),
    ],
    correctChoiceIds: ['seed-fur'],
  }),
  createMultiselectQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.shadeGardenStudy.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointA,
    questionIdentifier: purposePathQuestionIds.checkpointA[3],
    prompt: 'Choose two details that are most relevant to the author purpose.',
    explanation: 'These details show different ways seeds travel to new places.',
    evidenceReference: purposePathFeatureIds.shadeGardenStudy.glossary,
    evidenceReferenceIds: [
      purposePathSentenceIds.shadeGardenStudy[0],
      purposePathSentenceIds.shadeGardenStudy[3],
    ],
    targetVocabulary: ['relevant detail', 'travel', 'new places'],
    soundOutChunks: ['re', 'le', 'vant'],
    tags: ['purpose-vs-detail', 'purpose-vs-detail'],
    choices: [
      choice('seed-wind', 'Some seeds are light and drift on the wind.'),
      choice('seed-water-detail', 'Some float on water after a rain.'),
      choice('seed-map', 'A classroom map shows where the seeds traveled.'),
      choice('seed-fur-detail', 'Sticky seeds ride on fur or feathers.'),
    ],
    correctChoiceIds: ['seed-wind', 'seed-fur-detail'],
  }),
  createHotTextQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.shadeGardenStudy.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointA,
    questionIdentifier: purposePathQuestionIds.checkpointA[4],
    prompt: 'Tap the sentence that best helps readers understand the author purpose.',
    explanation: 'This sentence puts the seed-travel details together into one idea.',
    evidenceReference: purposePathSentenceIds.shadeGardenStudy[9],
    evidenceReferenceIds: [purposePathSentenceIds.shadeGardenStudy[9]],
    targetVocabulary: ['author purpose'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['informational-author-purpose', 'purpose-from-text-clues'],
    selectableSegments: [
      { id: purposePathSentenceIds.shadeGardenStudy[1], text: seedTravelSentences[1].text },
      { id: purposePathSentenceIds.shadeGardenStudy[4], text: seedTravelSentences[4].text },
      { id: purposePathSentenceIds.shadeGardenStudy[6], text: seedTravelSentences[6].text },
      { id: purposePathSentenceIds.shadeGardenStudy[9], text: seedTravelSentences[9].text },
    ],
    correctSegmentIds: [purposePathSentenceIds.shadeGardenStudy[9]],
  }),
  createTableMatchQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.shadeGardenStudy.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointA,
    questionIdentifier: purposePathQuestionIds.checkpointA[5],
    prompt: 'Match each statement to the best answer.',
    explanation: 'Each row matches a statement to the idea it names.',
    evidenceReference: purposePathFeatureIds.shadeGardenStudy.visual,
    evidenceReferenceIds: [
      purposePathFeatureIds.shadeGardenStudy.caption,
      purposePathFeatureIds.shadeGardenStudy.glossary,
    ],
    targetVocabulary: ['topic', 'author purpose', 'detail'],
    soundOutChunks: ['stat', 'e', 'ment'],
    tags: ['purpose-supported-by-text', 'purpose-from-multiple-sections', 'purpose-from-multiple-sections', 'purpose-from-multiple-sections'],
    rows: [
      {
        id: 'seed-topic',
        prompt: 'What is the topic?',
        correctChoiceId: 'seed-topic-answer',
        options: [
          choice('seed-topic-answer', 'seed travel routes'),
          choice('seed-topic-detail', 'A classroom map shows where the seeds traveled.'),
          choice('seed-topic-other', 'Birds may drop seeds after eating fruit.'),
        ],
      },
      {
        id: 'seed-central',
        prompt: 'What is the author purpose?',
        correctChoiceId: 'seed-central-answer',
        options: [
          choice('seed-central-answer', 'To explain several ways seeds travel to new places.'),
          choice('seed-central-other1', 'Some float on water after a rain.'),
          choice('seed-central-other2', 'Sticky seeds ride on fur or feathers.'),
        ],
      },
      {
        id: 'seed-other',
        prompt: 'Which is another true detail?',
        correctChoiceId: 'seed-other-answer',
        options: [
          choice('seed-other-answer', 'A classroom map shows where the seeds traveled.'),
          choice('seed-other-topic', 'seed travel routes'),
          choice('seed-other-central', 'Different seeds travel in different ways, and those trips help plants grow in new places.'),
        ],
      },
    ],
  }),
  createEvidencePairQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.shadeGardenStudy.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointA,
    questionIdentifier: purposePathQuestionIds.checkpointA[6],
    prompt: 'Choose the best answer for Part A and Part B.',
    explanation: 'The author purpose names the main thought, and the detail shows one way seeds travel.',
    evidenceReference: purposePathSentenceIds.shadeGardenStudy[9],
    evidenceReferenceIds: [
      purposePathSentenceIds.shadeGardenStudy[0],
      purposePathSentenceIds.shadeGardenStudy[3],
      purposePathFeatureIds.shadeGardenStudy.visual,
    ],
    targetVocabulary: ['author purpose', 'detail', 'evidence'],
    soundOutChunks: ['e', 'vi', 'dence'],
    tags: ['purpose-supported-by-text', 'purpose-from-multiple-sections', 'purpose-from-multiple-sections', 'purpose-from-multiple-sections'],
    partAPrompt: 'What is the author purpose of the text?',
    partAChoices: [
      choice('seed-part-a-1', 'To explain several ways seeds travel to new places.'),
      choice('seed-part-a-2', 'A classroom map shows where the seeds traveled.'),
      choice('seed-part-a-3', 'Some seeds are light and drift on the wind.'),
    ],
    partACorrectChoiceId: 'seed-part-a-1',
    partBPrompt: 'Which detail best supports that answer?',
    partBChoices: [
      choice('seed-part-b-1', 'Birds may drop seeds after eating fruit.'),
      choice('seed-part-b-2', 'Some seeds are light and drift on the wind.'),
      choice('seed-part-b-3', 'A classroom map shows where the seeds traveled.'),
    ],
    partBCorrectChoiceId: 'seed-part-b-2',
  }),

  createMultipleChoiceQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.recyclingSortStation.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointB,
    questionIdentifier: purposePathQuestionIds.checkpointB[0],
    prompt: 'What is the topic of this passage?',
    explanation: 'The topic is a short phrase that names what the passage is about.',
    evidenceReference: purposePathFeatureIds.recyclingSortStation.title,
    evidenceReferenceIds: [purposePathFeatureIds.recyclingSortStation.title],
    targetVocabulary: ['topic'],
    soundOutChunks: ['top', 'ic'],
    tags: ['informational-author-purpose', 'purpose-vs-topic'],
    choices: [
      choice('compost-topic', 'compost piles'),
      choice('seed-topic', 'seed travel routes'),
      choice('weather-topic', 'weather station notes'),
      choice('trail-topic', 'trail markers'),
    ],
    correctChoiceIds: ['compost-topic'],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.recyclingSortStation.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointB,
    questionIdentifier: purposePathQuestionIds.checkpointB[1],
    prompt: 'Why did the author most likely write this passage?',
    explanation: 'The author wrote this passage to explain how scraps and leaves change into compost that helps soil.',
    evidenceReference: purposePathSentenceIds.recyclingSortStation[9],
    evidenceReferenceIds: [purposePathSentenceIds.recyclingSortStation[9]],
    targetVocabulary: ['author purpose', 'complete thought'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['informational-author-purpose', 'author-purpose-specific', 'purpose-vs-central-idea', 'purpose-from-text-clues'],
    choices: [
      choice('compost-detail-1', 'To tell a made-up story about a worm.'),
      choice('compost-detail-2', 'To give directions for building one compost bin.'),
      choice('compost-central', 'To explain how scraps and leaves change into compost that helps soil.'),
      choice('compost-detail-3', 'To persuade readers to put all paper into compost.'),
    ],
    correctChoiceIds: ['compost-central'],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.recyclingSortStation.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointB,
    questionIdentifier: purposePathQuestionIds.checkpointB[2],
    prompt: 'Which detail is most relevant to the author purpose?',
    explanation: 'This detail shows how the compost pile changes over time.',
    evidenceReference: purposePathFeatureIds.recyclingSortStation.caption,
    evidenceReferenceIds: [purposePathSentenceIds.recyclingSortStation[7]],
    targetVocabulary: ['relevant detail', 'compost'],
    soundOutChunks: ['re', 'le', 'vant'],
    tags: ['purpose-vs-detail', 'purpose-vs-detail'],
    choices: [
      choice('compost-dark', 'The pile gets darker and crumbly over time.'),
      choice('compost-smell', 'When the pile changes, it smells less like food scraps and more like earth.'),
      choice('compost-scraps', 'Food scraps, leaves, and paper go into the pile.'),
      choice('compost-graph', 'A graph shows the pile warming up and then cooling down.'),
    ],
    correctChoiceIds: ['compost-scraps'],
  }),
  createMultiselectQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.recyclingSortStation.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointB,
    questionIdentifier: purposePathQuestionIds.checkpointB[3],
    prompt: 'Choose two details that are most relevant to the author purpose.',
    explanation: 'These details show how scraps change into compost that helps soil.',
    evidenceReference: purposePathFeatureIds.recyclingSortStation.visual,
    evidenceReferenceIds: [
      purposePathSentenceIds.recyclingSortStation[1],
      purposePathSentenceIds.recyclingSortStation[7],
    ],
    targetVocabulary: ['relevant detail', 'soil', 'change'],
    soundOutChunks: ['re', 'le', 'vant'],
    tags: ['purpose-vs-detail', 'purpose-vs-detail'],
    choices: [
      choice('compost-bugs', 'Tiny bugs and worms help break the pieces apart.'),
      choice('compost-useful', 'The scraps become compost that helps plants grow.'),
      choice('compost-leaf', 'A teacher says the class can still see leaf bits in the pile.'),
      choice('compost-week', 'The class watches the graph each week.'),
    ],
    correctChoiceIds: ['compost-bugs', 'compost-useful'],
  }),
  createHotTextQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.recyclingSortStation.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointB,
    questionIdentifier: purposePathQuestionIds.checkpointB[4],
    prompt: 'Tap the sentence that best helps readers understand the author purpose.',
    explanation: 'This sentence states the big idea about what happens in the pile.',
    evidenceReference: purposePathSentenceIds.recyclingSortStation[9],
    evidenceReferenceIds: [purposePathSentenceIds.recyclingSortStation[9]],
    targetVocabulary: ['author purpose'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['informational-author-purpose', 'purpose-from-text-clues'],
    selectableSegments: [
      { id: purposePathSentenceIds.recyclingSortStation[2], text: compostChangeSentences[2].text },
      { id: purposePathSentenceIds.recyclingSortStation[3], text: compostChangeSentences[3].text },
      { id: purposePathSentenceIds.recyclingSortStation[7], text: compostChangeSentences[7].text },
      { id: purposePathSentenceIds.recyclingSortStation[9], text: compostChangeSentences[9].text },
    ],
    correctSegmentIds: [purposePathSentenceIds.recyclingSortStation[9]],
  }),
  createTableMatchQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.recyclingSortStation.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointB,
    questionIdentifier: purposePathQuestionIds.checkpointB[5],
    prompt: 'Match each statement to the best answer.',
    explanation: 'Each row matches a statement to the idea it names.',
    evidenceReference: purposePathFeatureIds.recyclingSortStation.visual,
    evidenceReferenceIds: [
      purposePathFeatureIds.recyclingSortStation.caption,
      purposePathFeatureIds.recyclingSortStation.visual,
    ],
    targetVocabulary: ['topic', 'author purpose', 'detail'],
    soundOutChunks: ['stat', 'e', 'ment'],
    tags: ['purpose-supported-by-text', 'purpose-from-multiple-sections', 'purpose-from-multiple-sections', 'purpose-from-multiple-sections'],
    rows: [
      {
        id: 'compost-topic',
        prompt: 'What is the topic?',
        correctChoiceId: 'compost-topic-answer',
        options: [
          choice('compost-topic-answer', 'compost piles'),
          choice('compost-topic-detail', 'Tiny bugs and worms help break the pieces apart.'),
          choice('compost-topic-other', 'The class watches the graph each week.'),
        ],
      },
      {
        id: 'compost-central',
        prompt: 'What is the author purpose?',
        correctChoiceId: 'compost-central-answer',
        options: [
          choice('compost-central-answer', 'To explain how scraps and leaves change into compost that helps soil.'),
          choice('compost-central-other1', 'The pile gets darker and crumbly over time.'),
          choice('compost-central-other2', 'The class turns the pile so air can move through it.'),
        ],
      },
      {
        id: 'compost-other',
        prompt: 'Which is another true detail?',
        correctChoiceId: 'compost-other-answer',
        options: [
          choice('compost-other-answer', 'A teacher says the class can still see leaf bits in the pile.'),
          choice('compost-other-topic', 'compost piles'),
          choice('compost-other-central', 'Composting changes scraps and leaves into material that helps soil.'),
        ],
      },
    ],
  }),
  createEvidencePairQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.recyclingSortStation.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointB,
    questionIdentifier: purposePathQuestionIds.checkpointB[6],
    prompt: 'Choose the best answer for Part A and Part B.',
    explanation: 'The author purpose names the main thought, and the detail shows the change in the pile.',
    evidenceReference: purposePathSentenceIds.recyclingSortStation[9],
    evidenceReferenceIds: [
      purposePathSentenceIds.recyclingSortStation[1],
      purposePathSentenceIds.recyclingSortStation[7],
      purposePathFeatureIds.recyclingSortStation.visual,
    ],
    targetVocabulary: ['author purpose', 'detail', 'evidence'],
    soundOutChunks: ['e', 'vi', 'dence'],
    tags: ['purpose-supported-by-text', 'purpose-from-multiple-sections', 'purpose-from-multiple-sections', 'purpose-from-multiple-sections'],
    partAPrompt: 'What is the author purpose of the text?',
    partAChoices: [
      choice('compost-part-a-1', 'To explain how scraps and leaves change into compost that helps soil.'),
      choice('compost-part-a-2', 'A graph shows the pile warming up and then cooling down.'),
      choice('compost-part-a-3', 'Tiny bugs and worms help break the pieces apart.'),
    ],
    partACorrectChoiceId: 'compost-part-a-1',
    partBPrompt: 'Which detail best supports that answer?',
    partBChoices: [
      choice('compost-part-b-1', 'The class turns the pile so air can move through it.'),
      choice('compost-part-b-2', 'Food scraps, leaves, and paper go into the pile.'),
      choice('compost-part-b-3', 'A teacher says the class can still see leaf bits in the pile.'),
    ],
    partBCorrectChoiceId: 'compost-part-b-2',
  }),

  createMultipleChoiceQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.compostChangeNotes.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointC,
    questionIdentifier: purposePathQuestionIds.checkpointC[0],
    prompt: 'What is the topic of this passage?',
    explanation: 'The topic is a short phrase that names what the passage is about.',
    evidenceReference: purposePathFeatureIds.compostChangeNotes.title,
    evidenceReferenceIds: [purposePathFeatureIds.compostChangeNotes.title],
    targetVocabulary: ['topic'],
    soundOutChunks: ['top', 'ic'],
    tags: ['informational-author-purpose', 'purpose-vs-topic'],
    choices: [
      choice('trail-topic', 'trail markers'),
      choice('seed-topic', 'seed travel routes'),
      choice('weather-topic', 'weather station notes'),
      choice('compost-topic', 'compost piles'),
    ],
    correctChoiceIds: ['trail-topic'],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.compostChangeNotes.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointC,
    questionIdentifier: purposePathQuestionIds.checkpointC[1],
    prompt: 'Why did the author most likely write this passage?',
    explanation: 'The author wrote this passage to explain how trail markers and maps help visitors follow a path safely.',
    evidenceReference: purposePathSentenceIds.compostChangeNotes[9],
    evidenceReferenceIds: [purposePathSentenceIds.compostChangeNotes[9]],
    targetVocabulary: ['author purpose', 'complete thought'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['informational-author-purpose', 'author-purpose-specific', 'purpose-vs-central-idea', 'purpose-from-multiple-sections'],
    choices: [
      choice('trail-detail-1', 'To tell a made-up story about a lost hiker.'),
      choice('trail-central', 'To explain how trail markers and maps help visitors follow a path safely.'),
      choice('trail-detail-2', 'To give directions for painting one specific trail.'),
      choice('trail-detail-3', 'To persuade readers to choose only steep paths.'),
    ],
    correctChoiceIds: ['trail-central'],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.compostChangeNotes.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointC,
    questionIdentifier: purposePathQuestionIds.checkpointC[2],
    prompt: 'Which detail is most relevant to the author purpose?',
    explanation: 'This detail shows how the markers help visitors know which way to go.',
    evidenceReference: purposePathFeatureIds.compostChangeNotes.caption,
    evidenceReferenceIds: [purposePathSentenceIds.compostChangeNotes[0]],
    targetVocabulary: ['relevant detail', 'trail'],
    soundOutChunks: ['re', 'le', 'vant'],
    tags: ['purpose-vs-detail', 'purpose-vs-detail'],
    choices: [
      choice('trail-map-detail', 'The map tells hikers where to turn and where the loop ends.'),
      choice('trail-safe-detail', 'The guide notices a fallen branch and marks the safe side path.'),
      choice('trail-marker-detail', 'Bright markers show which path to take.'),
      choice('trail-end-detail', 'The end sign shows where the path meets the parking area.'),
    ],
    correctChoiceIds: ['trail-marker-detail'],
  }),
  createMultiselectQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.compostChangeNotes.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointC,
    questionIdentifier: purposePathQuestionIds.checkpointC[3],
    prompt: 'Choose two details that are most relevant to the author purpose.',
    explanation: 'These details show how the trail markers guide visitors safely.',
    evidenceReference: purposePathFeatureIds.compostChangeNotes.visual,
    evidenceReferenceIds: [
      purposePathSentenceIds.compostChangeNotes[1],
      purposePathSentenceIds.compostChangeNotes[7],
    ],
    targetVocabulary: ['relevant detail', 'safely', 'path'],
    soundOutChunks: ['re', 'le', 'vant'],
    tags: ['purpose-vs-detail', 'purpose-vs-detail'],
    choices: [
      choice('trail-turn', 'The map tells hikers where to turn and where the loop ends.'),
      choice('trail-safe', 'The guide notices a fallen branch and marks the safe side path.'),
      choice('trail-loop', 'Families can follow the same color marker all the way around.'),
      choice('trail-lost', 'Markers help walkers avoid getting lost.'),
    ],
    correctChoiceIds: ['trail-safe', 'trail-lost'],
  }),
  createHotTextQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.compostChangeNotes.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointC,
    questionIdentifier: purposePathQuestionIds.checkpointC[4],
    prompt: 'Tap the sentence that best helps readers understand the author purpose.',
    explanation: 'This sentence puts the trail-marker details together into one idea.',
    evidenceReference: purposePathSentenceIds.compostChangeNotes[9],
    evidenceReferenceIds: [purposePathSentenceIds.compostChangeNotes[9]],
    targetVocabulary: ['author purpose'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['informational-author-purpose', 'purpose-from-text-clues'],
    selectableSegments: [
      { id: purposePathSentenceIds.compostChangeNotes[1], text: trailMarkerSentences[1].text },
      { id: purposePathSentenceIds.compostChangeNotes[4], text: trailMarkerSentences[4].text },
      { id: purposePathSentenceIds.compostChangeNotes[7], text: trailMarkerSentences[7].text },
      { id: purposePathSentenceIds.compostChangeNotes[9], text: trailMarkerSentences[9].text },
    ],
    correctSegmentIds: [purposePathSentenceIds.compostChangeNotes[9]],
  }),
  createTableMatchQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.compostChangeNotes.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointC,
    questionIdentifier: purposePathQuestionIds.checkpointC[5],
    prompt: 'Match each statement to the best answer.',
    explanation: 'Each row matches a statement to the idea it names.',
    evidenceReference: purposePathFeatureIds.compostChangeNotes.visual,
    evidenceReferenceIds: [
      purposePathFeatureIds.compostChangeNotes.caption,
      purposePathFeatureIds.compostChangeNotes.visual,
    ],
    targetVocabulary: ['topic', 'author purpose', 'detail'],
    soundOutChunks: ['stat', 'e', 'ment'],
    tags: ['purpose-supported-by-text', 'purpose-from-multiple-sections', 'purpose-from-multiple-sections', 'purpose-from-multiple-sections'],
    rows: [
      {
        id: 'trail-topic',
        prompt: 'What is the topic?',
        correctChoiceId: 'trail-topic-answer',
        options: [
          choice('trail-topic-answer', 'trail markers'),
          choice('trail-topic-detail', 'Bright markers show which path to take.'),
          choice('trail-topic-other', 'The end sign shows where the path meets the parking area.'),
        ],
      },
      {
        id: 'trail-central',
        prompt: 'What is the author purpose?',
        correctChoiceId: 'trail-central-answer',
        options: [
          choice('trail-central-answer', 'To explain how trail markers and maps help visitors follow a path safely.'),
          choice('trail-central-other1', 'The map tells hikers where to turn and where the loop ends.'),
          choice('trail-central-other2', 'Families can follow the same color marker all the way around.'),
        ],
      },
      {
        id: 'trail-other',
        prompt: 'Which is another true detail?',
        correctChoiceId: 'trail-other-answer',
        options: [
          choice('trail-other-answer', 'The end sign shows where the path meets the parking area.'),
          choice('trail-other-topic', 'trail markers'),
          choice('trail-other-central', 'Trail markers help visitors stay on the right path and reach the end safely.'),
        ],
      },
    ],
  }),
  createEvidencePairQuestion({
    ...base,
    difficulty: 3,
    passageIdentifier: purposePathPassageIds.compostChangeNotes.passageId,
    lessonIdentifier: purposePathLessonIds.checkpointC,
    questionIdentifier: purposePathQuestionIds.checkpointC[6],
    prompt: 'Choose the best answer for Part A and Part B.',
    explanation: 'The author purpose names the main thought, and the detail shows how the markers guide walkers.',
    evidenceReference: purposePathSentenceIds.compostChangeNotes[9],
    evidenceReferenceIds: [
      purposePathSentenceIds.compostChangeNotes[1],
      purposePathSentenceIds.compostChangeNotes[7],
      purposePathFeatureIds.compostChangeNotes.visual,
    ],
    targetVocabulary: ['author purpose', 'detail', 'evidence'],
    soundOutChunks: ['e', 'vi', 'dence'],
    tags: ['purpose-supported-by-text', 'purpose-from-multiple-sections'],
    partAPrompt: 'What is the author purpose of the text?',
    partAChoices: [
      choice('trail-part-a-1', 'To explain how trail markers and maps help visitors follow a path safely.'),
      choice('trail-part-a-2', 'The map tells hikers where to turn and where the loop ends.'),
      choice('trail-part-a-3', 'Bright markers show which path to take.'),
    ],
    partACorrectChoiceId: 'trail-part-a-1',
    partBPrompt: 'Which detail best supports that answer?',
    partBChoices: [
      choice('trail-part-b-1', 'The end sign shows where the path meets the parking area.'),
      choice('trail-part-b-2', 'Bright markers show which path to take.'),
      choice('trail-part-b-3', 'Families can follow the same color marker all the way around.'),
    ],
    partBCorrectChoiceId: 'trail-part-b-2',
  }),
] as const






