import { buildWordplayTextArtifact } from './textArtifacts'

const prosePlans = [
  {
    passageId: 'g2-cg-wordplay-kite-parade',
    title: 'Kite Parade Notes',
    readingContext: 'Compare Castle Wordplay Watchtower',
    bodyKind: 'prose' as const,
    lines: [
      { sentenceId: 'g2-cg-wordplay-kite-parade-sentence-1', lineNumber: 1, text: 'At the kite parade, the banner lifted like a bright fish in the wind.' },
      { sentenceId: 'g2-cg-wordplay-kite-parade-sentence-2', lineNumber: 2, text: 'The helpers lend a hand by holding the string and passing tape.' },
      { sentenceId: 'g2-cg-wordplay-kite-parade-sentence-3', lineNumber: 3, text: 'Blue banners bobbed beside the booth.' },
      { sentenceId: 'g2-cg-wordplay-kite-parade-sentence-4', lineNumber: 4, text: 'The kite tail curled as smooth as a ribbon.' },
      { sentenceId: 'g2-cg-wordplay-kite-parade-sentence-5', lineNumber: 5, text: 'A small crowd watched from the curb.' },
      { sentenceId: 'g2-cg-wordplay-kite-parade-sentence-6', lineNumber: 6, text: 'The pilot thanked each helper with a grin.' },
      { sentenceId: 'g2-cg-wordplay-kite-parade-sentence-7', lineNumber: 7, text: 'The last page of the plan showed where to place the pin.' },
    ],
    supportTargets: [
      { sentenceIndex: 0, surfaceWord: 'like a bright fish', split: ['like a ', 'bright fish'] as [string, string] },
      { sentenceIndex: 1, surfaceWord: 'lend a hand', split: ['lend a ', 'hand'] as [string, string] },
      { sentenceIndex: 2, surfaceWord: 'blue banners bobbed', split: ['blue banners ', 'bobbed'] as [string, string] },
      { sentenceIndex: 3, surfaceWord: 'as smooth as a ribbon', split: ['as smooth as ', 'a ribbon'] as [string, string] },
    ],
    targetPlans: [
      {
        targetId: 'g2-cg-wordplay-kite-parade-simile-fish',
        kind: 'simile' as const,
        expressionText: 'like a bright fish',
        sentenceIndex: 0,
        evidenceSentenceIndexes: [0],
        explanationStatement: 'The banner is compared to a bright fish to show how it moved and flashed in the wind.',
        signalWord: 'like' as const,
        comparisonSubject: 'the banner',
        comparisonObject: 'a bright fish',
        sharedQuality: 'both move and flash in the wind',
        figurativeComparison: true as const,
      },
      {
        targetId: 'g2-cg-wordplay-kite-parade-idiom-lend-a-hand',
        kind: 'idiom' as const,
        expressionText: 'lend a hand',
        sentenceIndex: 1,
        evidenceSentenceIndexes: [1, 5],
        explanationStatement: 'Lend a hand means help someone.',
        intendedMeaning: 'help someone',
        literalReading: 'to give someone your hand',
        contextEvidenceSentenceIndexes: [1, 5],
        nonliteral: true as const,
      },
      {
        targetId: 'g2-cg-wordplay-kite-parade-alliteration-blue-banners',
        kind: 'alliteration' as const,
        expressionText: 'blue banners bobbed',
        sentenceIndex: 2,
        evidenceSentenceIndexes: [2],
        explanationStatement: 'Blue banners bobbed uses alliteration because the words begin with the /b/ sound.',
        alliterativeWords: [
          { word: 'blue', initialSound: 'b' },
          { word: 'banners', initialSound: 'b' },
          { word: 'bobbed', initialSound: 'b' },
        ],
        repeatedInitialSound: 'b',
        soundExplanation: 'The /b/ sound repeats at the start of the three words.',
      },
      {
        targetId: 'g2-cg-wordplay-kite-parade-simile-ribbon',
        kind: 'simile' as const,
        expressionText: 'as smooth as a ribbon',
        sentenceIndex: 3,
        evidenceSentenceIndexes: [3],
        explanationStatement: 'The kite tail is compared to ribbon to show that it curled in a smooth way.',
        signalWord: 'as' as const,
        comparisonSubject: 'the kite tail',
        comparisonObject: 'a ribbon',
        sharedQuality: 'both are smooth and flowing',
        figurativeComparison: true as const,
      },
    ],
  },
  {
    passageId: 'g2-cg-wordplay-library-helpers',
    title: 'Library Helpers',
    readingContext: 'Compare Castle Wordplay Watchtower',
    bodyKind: 'prose' as const,
    lines: [
      { sentenceId: 'g2-cg-wordplay-library-helpers-sentence-1', lineNumber: 1, text: 'The hall was as quiet as a cloud after the bell.' },
      { sentenceId: 'g2-cg-wordplay-library-helpers-sentence-2', lineNumber: 2, text: 'The readers were on the same page about the book club plan.' },
      { sentenceId: 'g2-cg-wordplay-library-helpers-sentence-3', lineNumber: 3, text: 'Careful cats carried cards down the center aisle.' },
      { sentenceId: 'g2-cg-wordplay-library-helpers-sentence-4', lineNumber: 4, text: 'The helpers keep an eye on the returns shelf.' },
      { sentenceId: 'g2-cg-wordplay-library-helpers-sentence-5', lineNumber: 5, text: 'Two students sorted story cards into neat boxes.' },
      { sentenceId: 'g2-cg-wordplay-library-helpers-sentence-6', lineNumber: 6, text: 'The checkout table stayed bright and calm.' },
      { sentenceId: 'g2-cg-wordplay-library-helpers-sentence-7', lineNumber: 7, text: 'Their neat notes showed the plan for tomorrow.' },
    ],
    supportTargets: [
      { sentenceIndex: 0, surfaceWord: 'as quiet as a cloud', split: ['as quiet as ', 'a cloud'] as [string, string] },
      { sentenceIndex: 1, surfaceWord: 'on the same page', split: ['on the same ', 'page'] as [string, string] },
      { sentenceIndex: 2, surfaceWord: 'careful cats carried', split: ['careful cats ', 'carried'] as [string, string] },
      { sentenceIndex: 3, surfaceWord: 'keep an eye on', split: ['keep an ', 'eye on'] as [string, string] },
    ],
    targetPlans: [
      {
        targetId: 'g2-cg-wordplay-library-helpers-simile-cloud',
        kind: 'simile' as const,
        expressionText: 'as quiet as a cloud',
        sentenceIndex: 0,
        evidenceSentenceIndexes: [0],
        explanationStatement: 'The hall is compared to a cloud to show how very quiet it felt.',
        signalWord: 'as' as const,
        comparisonSubject: 'the hall',
        comparisonObject: 'a cloud',
        sharedQuality: 'both are quiet and soft-looking',
        figurativeComparison: true as const,
      },
      {
        targetId: 'g2-cg-wordplay-library-helpers-idiom-page',
        kind: 'idiom' as const,
        expressionText: 'on the same page',
        sentenceIndex: 1,
        evidenceSentenceIndexes: [1],
        explanationStatement: 'On the same page means the readers agree about the plan.',
        intendedMeaning: 'agreeing about the same plan',
        literalReading: 'standing on the same page of a book',
        contextEvidenceSentenceIndexes: [1],
        nonliteral: true as const,
      },
      {
        targetId: 'g2-cg-wordplay-library-helpers-alliteration-cats',
        kind: 'alliteration' as const,
        expressionText: 'careful cats carried',
        sentenceIndex: 2,
        evidenceSentenceIndexes: [2],
        explanationStatement: 'Careful cats carried uses alliteration because the words begin with the /c/ sound.',
        alliterativeWords: [
          { word: 'careful', initialSound: 'c' },
          { word: 'cats', initialSound: 'c' },
          { word: 'carried', initialSound: 'c' },
        ],
        repeatedInitialSound: 'c',
        soundExplanation: 'The /c/ sound repeats at the start of the three words.',
      },
      {
        targetId: 'g2-cg-wordplay-library-helpers-idiom-eye',
        kind: 'idiom' as const,
        expressionText: 'keep an eye on',
        sentenceIndex: 3,
        evidenceSentenceIndexes: [3],
        explanationStatement: 'Keep an eye on means watch something carefully.',
        intendedMeaning: 'watch something carefully',
        literalReading: 'hold an eye on something',
        contextEvidenceSentenceIndexes: [3],
        nonliteral: true as const,
      },
    ],
  },
  {
    passageId: 'g2-cg-wordplay-garden-display',
    title: 'Garden Display',
    readingContext: 'Compare Castle Wordplay Watchtower',
    bodyKind: 'prose' as const,
    lines: [
      { sentenceId: 'g2-cg-wordplay-garden-display-sentence-1', lineNumber: 1, text: 'The seed tray rested like a tiny boat on the table.' },
      { sentenceId: 'g2-cg-wordplay-garden-display-sentence-2', lineNumber: 2, text: 'Maya helped get the ball rolling by watering the sprouts first.' },
      { sentenceId: 'g2-cg-wordplay-garden-display-sentence-3', lineNumber: 3, text: 'Merry markers made tall labels for each pot.' },
      { sentenceId: 'g2-cg-wordplay-garden-display-sentence-4', lineNumber: 4, text: 'Paper petals pushed past the plain plant sticks.' },
      { sentenceId: 'g2-cg-wordplay-garden-display-sentence-5', lineNumber: 5, text: 'The class lined up the pots by size.' },
      { sentenceId: 'g2-cg-wordplay-garden-display-sentence-6', lineNumber: 6, text: 'Each leaf looked new and neat.' },
      { sentenceId: 'g2-cg-wordplay-garden-display-sentence-7', lineNumber: 7, text: 'The display stood ready for visitors.' },
    ],
    supportTargets: [
      { sentenceIndex: 0, surfaceWord: 'like a tiny boat', split: ['like a ', 'tiny boat'] as [string, string] },
      { sentenceIndex: 1, surfaceWord: 'get the ball rolling', split: ['get the ball ', 'rolling'] as [string, string] },
      { sentenceIndex: 2, surfaceWord: 'merry markers made', split: ['merry markers ', 'made'] as [string, string] },
      { sentenceIndex: 3, surfaceWord: 'paper petals pushed', split: ['paper petals ', 'pushed'] as [string, string] },
    ],
    targetPlans: [
      {
        targetId: 'g2-cg-wordplay-garden-display-simile-boat',
        kind: 'simile' as const,
        expressionText: 'like a tiny boat',
        sentenceIndex: 0,
        evidenceSentenceIndexes: [0],
        explanationStatement: 'The seed tray is compared to a tiny boat to show its small shape and how it rested on the table.',
        signalWord: 'like' as const,
        comparisonSubject: 'the seed tray',
        comparisonObject: 'a tiny boat',
        sharedQuality: 'both are small and boat-shaped',
        figurativeComparison: true as const,
      },
      {
        targetId: 'g2-cg-wordplay-garden-display-idiom-ball',
        kind: 'idiom' as const,
        expressionText: 'get the ball rolling',
        sentenceIndex: 1,
        evidenceSentenceIndexes: [1],
        explanationStatement: 'Get the ball rolling means start the work.',
        intendedMeaning: 'start the work',
        literalReading: 'roll a ball',
        contextEvidenceSentenceIndexes: [1],
        nonliteral: true as const,
      },
      {
        targetId: 'g2-cg-wordplay-garden-display-alliteration-markers',
        kind: 'alliteration' as const,
        expressionText: 'merry markers made',
        sentenceIndex: 2,
        evidenceSentenceIndexes: [2],
        explanationStatement: 'Merry markers made uses alliteration because the words begin with the /m/ sound.',
        alliterativeWords: [
          { word: 'merry', initialSound: 'm' },
          { word: 'markers', initialSound: 'm' },
          { word: 'made', initialSound: 'm' },
        ],
        repeatedInitialSound: 'm',
        soundExplanation: 'The /m/ sound repeats at the start of the three words.',
      } as const,
      {
        targetId: 'g2-cg-wordplay-garden-display-alliteration-petals',
        kind: 'alliteration' as const,
        expressionText: 'paper petals pushed',
        sentenceIndex: 3,
        evidenceSentenceIndexes: [3],
        explanationStatement: 'Paper petals pushed uses alliteration because the words begin with the /p/ sound.',
        alliterativeWords: [
          { word: 'paper', initialSound: 'p' },
          { word: 'petals', initialSound: 'p' },
          { word: 'pushed', initialSound: 'p' },
        ],
        repeatedInitialSound: 'p',
        soundExplanation: 'The /p/ sound repeats at the start of the three words.',
      },
    ],
  },
  {
    passageId: 'g2-cg-wordplay-bridge-model',
    title: 'Bridge Model Day',
    readingContext: 'Compare Castle Wordplay Watchtower',
    bodyKind: 'prose' as const,
    lines: [
      { sentenceId: 'g2-cg-wordplay-bridge-model-sentence-1', lineNumber: 1, text: 'The bridge model stood like a narrow smile across the desk.' },
      { sentenceId: 'g2-cg-wordplay-bridge-model-sentence-2', lineNumber: 2, text: 'The class was in the same boat when the glue tipped over.' },
      { sentenceId: 'g2-cg-wordplay-bridge-model-sentence-3', lineNumber: 3, text: 'Brave builders balanced bolts by the beam.' },
      { sentenceId: 'g2-cg-wordplay-bridge-model-sentence-4', lineNumber: 4, text: 'When the bell rang, we called it a day and cleaned up.' },
      { sentenceId: 'g2-cg-wordplay-bridge-model-sentence-5', lineNumber: 5, text: 'The paper tower stayed tall beside the sand tray.' },
      { sentenceId: 'g2-cg-wordplay-bridge-model-sentence-6', lineNumber: 6, text: 'A red marker rested near the ruler.' },
      { sentenceId: 'g2-cg-wordplay-bridge-model-sentence-7', lineNumber: 7, text: 'The last test showed our bridge could hold a toy car.' },
    ],
    supportTargets: [
      { sentenceIndex: 0, surfaceWord: 'like a narrow smile', split: ['like a narrow ', 'smile'] as [string, string] },
      { sentenceIndex: 1, surfaceWord: 'in the same boat', split: ['in the same ', 'boat'] as [string, string] },
      { sentenceIndex: 2, surfaceWord: 'brave builders balanced', split: ['brave builders ', 'balanced'] as [string, string] },
      { sentenceIndex: 3, surfaceWord: 'called it a day', split: ['called it a ', 'day'] as [string, string] },
    ],
    targetPlans: [
      {
        targetId: 'g2-cg-wordplay-bridge-model-simile-smile',
        kind: 'simile' as const,
        expressionText: 'like a narrow smile',
        sentenceIndex: 0,
        evidenceSentenceIndexes: [0],
        explanationStatement: 'The bridge model is compared to a narrow smile to show its curved shape.',
        signalWord: 'like' as const,
        comparisonSubject: 'the bridge model',
        comparisonObject: 'a narrow smile',
        sharedQuality: 'both curve across a space',
        figurativeComparison: true as const,
      },
      {
        targetId: 'g2-cg-wordplay-bridge-model-idiom-boat',
        kind: 'idiom' as const,
        expressionText: 'in the same boat',
        sentenceIndex: 1,
        evidenceSentenceIndexes: [1],
        explanationStatement: 'In the same boat means the class shared the same problem.',
        intendedMeaning: 'sharing the same problem',
        literalReading: 'sitting in the same boat',
        contextEvidenceSentenceIndexes: [1],
        nonliteral: true as const,
      },
      {
        targetId: 'g2-cg-wordplay-bridge-model-alliteration-builders',
        kind: 'alliteration' as const,
        expressionText: 'brave builders balanced',
        sentenceIndex: 2,
        evidenceSentenceIndexes: [2],
        explanationStatement: 'Brave builders balanced uses alliteration because the words begin with the /b/ sound.',
        alliterativeWords: [
          { word: 'brave', initialSound: 'b' },
          { word: 'builders', initialSound: 'b' },
          { word: 'balanced', initialSound: 'b' },
        ],
        repeatedInitialSound: 'b',
        soundExplanation: 'The /b/ sound repeats at the start of the three words.',
      },
      {
        targetId: 'g2-cg-wordplay-bridge-model-idiom-day',
        kind: 'idiom' as const,
        expressionText: 'called it a day',
        sentenceIndex: 3,
        evidenceSentenceIndexes: [3],
        explanationStatement: 'Called it a day means stop working for now.',
        intendedMeaning: 'stop working for now',
        literalReading: 'say the day is called',
        contextEvidenceSentenceIndexes: [3],
        nonliteral: true as const,
      },
    ],
  },
  {
    passageId: 'g2-cg-wordplay-trail-map',
    title: 'Trail Map Day',
    readingContext: 'Compare Castle Wordplay Watchtower',
    bodyKind: 'prose' as const,
    lines: [
      { sentenceId: 'g2-cg-wordplay-trail-map-sentence-1', lineNumber: 1, text: 'The trail sign looked like a friendly arrow.' },
      { sentenceId: 'g2-cg-wordplay-trail-map-sentence-2', lineNumber: 2, text: 'Our group was as calm as a pond after the rain.' },
      { sentenceId: 'g2-cg-wordplay-trail-map-sentence-3', lineNumber: 3, text: 'Path markers pointed past pine trees.' },
      { sentenceId: 'g2-cg-wordplay-trail-map-sentence-4', lineNumber: 4, text: 'The guide said to keep an eye on the mud patch.' },
      { sentenceId: 'g2-cg-wordplay-trail-map-sentence-5', lineNumber: 5, text: 'We stepped over roots and small stones.' },
      { sentenceId: 'g2-cg-wordplay-trail-map-sentence-6', lineNumber: 6, text: 'The map stayed folded in my pocket.' },
      { sentenceId: 'g2-cg-wordplay-trail-map-sentence-7', lineNumber: 7, text: 'The last bend led us back to the bus.' },
    ],
    supportTargets: [
      { sentenceIndex: 0, surfaceWord: 'like a friendly arrow', split: ['like a friendly ', 'arrow'] as [string, string] },
      { sentenceIndex: 1, surfaceWord: 'as calm as a pond', split: ['as calm as a ', 'pond'] as [string, string] },
      { sentenceIndex: 2, surfaceWord: 'path markers pointed', split: ['path markers ', 'pointed'] as [string, string] },
      { sentenceIndex: 3, surfaceWord: 'keep an eye on', split: ['keep an ', 'eye on'] as [string, string] },
    ],
    targetPlans: [
      {
        targetId: 'g2-cg-wordplay-trail-map-simile-arrow',
        kind: 'simile' as const,
        expressionText: 'like a friendly arrow',
        sentenceIndex: 0,
        evidenceSentenceIndexes: [0],
        explanationStatement: 'The trail sign is compared to a friendly arrow to show that it points the way.',
        signalWord: 'like' as const,
        comparisonSubject: 'the trail sign',
        comparisonObject: 'a friendly arrow',
        sharedQuality: 'both point the way clearly',
        figurativeComparison: true as const,
      },
      {
        targetId: 'g2-cg-wordplay-trail-map-simile-pond',
        kind: 'simile' as const,
        expressionText: 'as calm as a pond',
        sentenceIndex: 1,
        evidenceSentenceIndexes: [1],
        explanationStatement: 'The group is compared to a pond to show how calm everyone was.',
        signalWord: 'as' as const,
        comparisonSubject: 'our group',
        comparisonObject: 'a pond',
        sharedQuality: 'both are calm and still',
        figurativeComparison: true as const,
      },
      {
        targetId: 'g2-cg-wordplay-trail-map-alliteration-markers',
        kind: 'alliteration' as const,
        expressionText: 'path markers pointed',
        sentenceIndex: 2,
        evidenceSentenceIndexes: [2],
        explanationStatement: 'Path markers pointed uses alliteration because the words begin with the /p/ sound.',
        alliterativeWords: [
          { word: 'path', initialSound: 'p' },
          { word: 'markers', initialSound: 'p' },
          { word: 'pointed', initialSound: 'p' },
        ],
        repeatedInitialSound: 'p',
        soundExplanation: 'The /p/ sound repeats at the start of the three words.',
      },
      {
        targetId: 'g2-cg-wordplay-trail-map-idiom-eye',
        kind: 'idiom' as const,
        expressionText: 'keep an eye on',
        sentenceIndex: 3,
        evidenceSentenceIndexes: [3],
        explanationStatement: 'Keep an eye on means watch something carefully.',
        intendedMeaning: 'watch something carefully',
        literalReading: 'hold an eye on something',
        contextEvidenceSentenceIndexes: [3],
        nonliteral: true as const,
      },
    ],
  },
]

export const wordplayWatchtowerProseArtifacts = prosePlans.map((plan) => buildWordplayTextArtifact(plan))
