import { buildWordplayTextArtifact } from './textArtifacts'

const poemPlans = [
  {
    passageId: 'g2-cg-wordplay-rooftop-poem',
    title: 'Rooftop Practice',
    readingContext: 'Compare Castle Wordplay Watchtower',
    bodyKind: 'poem' as const,
    lines: [
      { sentenceId: 'g2-cg-wordplay-rooftop-poem-line-1', lineNumber: 1, stanzaId: 'g2-cg-wordplay-rooftop-poem-stanza-1', text: 'The flags climbed like orange kites above the roof.' },
      { sentenceId: 'g2-cg-wordplay-rooftop-poem-line-2', lineNumber: 2, stanzaId: 'g2-cg-wordplay-rooftop-poem-stanza-1', text: 'We put on our thinking caps before the game.' },
      { sentenceId: 'g2-cg-wordplay-rooftop-poem-line-3', lineNumber: 3, stanzaId: 'g2-cg-wordplay-rooftop-poem-stanza-1', text: 'Tiny tools tapped the tin table.' },
      { sentenceId: 'g2-cg-wordplay-rooftop-poem-line-4', lineNumber: 4, stanzaId: 'g2-cg-wordplay-rooftop-poem-stanza-1', text: 'The ropes stretched as straight as chalk lines.' },
      { sentenceId: 'g2-cg-wordplay-rooftop-poem-line-5', lineNumber: 5, stanzaId: 'g2-cg-wordplay-rooftop-poem-stanza-2', text: 'The wind moved softly through the warm air.' },
      { sentenceId: 'g2-cg-wordplay-rooftop-poem-line-6', lineNumber: 6, stanzaId: 'g2-cg-wordplay-rooftop-poem-stanza-2', text: 'We checked each knot and smiled.' },
      { sentenceId: 'g2-cg-wordplay-rooftop-poem-line-7', lineNumber: 7, stanzaId: 'g2-cg-wordplay-rooftop-poem-stanza-2', text: 'A red drum kept the beat near the wall.' },
      { sentenceId: 'g2-cg-wordplay-rooftop-poem-line-8', lineNumber: 8, stanzaId: 'g2-cg-wordplay-rooftop-poem-stanza-2', text: 'The rooftop stayed steady through the night.' },
    ],
    stanzas: [
      { stanzaId: 'g2-cg-wordplay-rooftop-poem-stanza-1', lineNumbers: [1, 2, 3, 4] },
      { stanzaId: 'g2-cg-wordplay-rooftop-poem-stanza-2', lineNumbers: [5, 6, 7, 8] },
    ],
    supportTargets: [
      { sentenceIndex: 0, surfaceWord: 'like orange kites', split: ['like orange ', 'kites'] as [string, string] },
      { sentenceIndex: 1, surfaceWord: 'put on our thinking caps', split: ['put on our ', 'thinking caps'] as [string, string] },
      { sentenceIndex: 2, surfaceWord: 'tiny tools tapped', split: ['tiny tools ', 'tapped'] as [string, string] },
      { sentenceIndex: 3, surfaceWord: 'as straight as chalk lines', split: ['as straight as ', 'chalk lines'] as [string, string] },
    ],
    targetPlans: [
      {
        targetId: 'g2-cg-wordplay-rooftop-poem-simile-kites',
        kind: 'simile' as const,
        expressionText: 'like orange kites',
        sentenceIndex: 0,
        evidenceSentenceIndexes: [0],
        explanationStatement: 'The flags are compared to orange kites to show how they moved in the wind.',
        signalWord: 'like' as const,
        comparisonSubject: 'the flags',
        comparisonObject: 'orange kites',
        sharedQuality: 'both float and climb in the wind',
        figurativeComparison: true as const,
      },
      {
        targetId: 'g2-cg-wordplay-rooftop-poem-idiom-thinking-caps',
        kind: 'idiom' as const,
        expressionText: 'put on our thinking caps',
        sentenceIndex: 1,
        evidenceSentenceIndexes: [1],
        explanationStatement: 'Put on our thinking caps means start thinking carefully.',
        intendedMeaning: 'start thinking carefully',
        literalReading: 'wear caps on our heads',
        contextEvidenceSentenceIndexes: [1],
        nonliteral: true as const,
      },
      {
        targetId: 'g2-cg-wordplay-rooftop-poem-alliteration-tools',
        kind: 'alliteration' as const,
        expressionText: 'tiny tools tapped',
        sentenceIndex: 2,
        evidenceSentenceIndexes: [2],
        explanationStatement: 'Tiny tools tapped uses alliteration because the words begin with the /t/ sound.',
        alliterativeWords: [
          { word: 'tiny', initialSound: 't' },
          { word: 'tools', initialSound: 't' },
          { word: 'tapped', initialSound: 't' },
        ],
        repeatedInitialSound: 't',
        soundExplanation: 'The /t/ sound repeats at the start of the three words.',
      },
      {
        targetId: 'g2-cg-wordplay-rooftop-poem-simile-lines',
        kind: 'simile' as const,
        expressionText: 'as straight as chalk lines',
        sentenceIndex: 3,
        evidenceSentenceIndexes: [3],
        explanationStatement: 'The ropes are compared to chalk lines to show that they stretched in a straight way.',
        signalWord: 'as' as const,
        comparisonSubject: 'the ropes',
        comparisonObject: 'chalk lines',
        sharedQuality: 'both are straight and long',
        figurativeComparison: true as const,
      },
    ],
  },
  {
    passageId: 'g2-cg-wordplay-seed-song',
    title: 'Seed Song',
    readingContext: 'Compare Castle Wordplay Watchtower',
    bodyKind: 'poem' as const,
    lines: [
      { sentenceId: 'g2-cg-wordplay-seed-song-line-1', lineNumber: 1, stanzaId: 'g2-cg-wordplay-seed-song-stanza-1', text: 'The seed moved as soft as snow through the soil.' },
      { sentenceId: 'g2-cg-wordplay-seed-song-line-2', lineNumber: 2, stanzaId: 'g2-cg-wordplay-seed-song-stanza-1', text: 'I had to hold your horses while the rain drum rolled.' },
      { sentenceId: 'g2-cg-wordplay-seed-song-line-3', lineNumber: 3, stanzaId: 'g2-cg-wordplay-seed-song-stanza-1', text: 'Spry sprouts swayed in the sun.' },
      { sentenceId: 'g2-cg-wordplay-seed-song-line-4', lineNumber: 4, stanzaId: 'g2-cg-wordplay-seed-song-stanza-1', text: 'Green gates guarded the garden.' },
      { sentenceId: 'g2-cg-wordplay-seed-song-line-5', lineNumber: 5, stanzaId: 'g2-cg-wordplay-seed-song-stanza-2', text: 'Little leaves lifted their heads.' },
      { sentenceId: 'g2-cg-wordplay-seed-song-line-6', lineNumber: 6, stanzaId: 'g2-cg-wordplay-seed-song-stanza-2', text: 'A cool cup of water waited nearby.' },
      { sentenceId: 'g2-cg-wordplay-seed-song-line-7', lineNumber: 7, stanzaId: 'g2-cg-wordplay-seed-song-stanza-2', text: 'The rows stood neat as notebook lines.' },
      { sentenceId: 'g2-cg-wordplay-seed-song-line-8', lineNumber: 8, stanzaId: 'g2-cg-wordplay-seed-song-stanza-2', text: 'The garden woke with a quiet sigh.' },
    ],
    stanzas: [
      { stanzaId: 'g2-cg-wordplay-seed-song-stanza-1', lineNumbers: [1, 2, 3, 4] },
      { stanzaId: 'g2-cg-wordplay-seed-song-stanza-2', lineNumbers: [5, 6, 7, 8] },
    ],
    supportTargets: [
      { sentenceIndex: 0, surfaceWord: 'as soft as snow', split: ['as soft as ', 'snow'] as [string, string] },
      { sentenceIndex: 1, surfaceWord: 'hold your horses', split: ['hold your ', 'horses'] as [string, string] },
      { sentenceIndex: 2, surfaceWord: 'spry sprouts swayed', split: ['spry sprouts ', 'swayed'] as [string, string] },
      { sentenceIndex: 3, surfaceWord: 'green gates guarded', split: ['green gates ', 'guarded'] as [string, string] },
    ],
    targetPlans: [
      {
        targetId: 'g2-cg-wordplay-seed-song-simile-snow',
        kind: 'simile' as const,
        expressionText: 'as soft as snow',
        sentenceIndex: 0,
        evidenceSentenceIndexes: [0],
        explanationStatement: 'The seed is compared to snow to show how gently it moved through the soil.',
        signalWord: 'as' as const,
        comparisonSubject: 'the seed',
        comparisonObject: 'snow',
        sharedQuality: 'both move softly',
        figurativeComparison: true as const,
      },
      {
        targetId: 'g2-cg-wordplay-seed-song-idiom-horses',
        kind: 'idiom' as const,
        expressionText: 'hold your horses',
        sentenceIndex: 1,
        evidenceSentenceIndexes: [1],
        explanationStatement: 'Hold your horses means wait patiently.',
        intendedMeaning: 'wait patiently',
        literalReading: 'hold horses with your hands',
        contextEvidenceSentenceIndexes: [1],
        nonliteral: true as const,
      },
      {
        targetId: 'g2-cg-wordplay-seed-song-alliteration-spry',
        kind: 'alliteration' as const,
        expressionText: 'spry sprouts swayed',
        sentenceIndex: 2,
        evidenceSentenceIndexes: [2],
        explanationStatement: 'Spry sprouts swayed uses alliteration because the words begin with the /s/ sound.',
        alliterativeWords: [
          { word: 'spry', initialSound: 's' },
          { word: 'sprouts', initialSound: 's' },
          { word: 'swayed', initialSound: 's' },
        ],
        repeatedInitialSound: 's',
        soundExplanation: 'The /s/ sound repeats at the start of the three words.',
      },
      {
        targetId: 'g2-cg-wordplay-seed-song-alliteration-gates',
        kind: 'alliteration' as const,
        expressionText: 'green gates guarded',
        sentenceIndex: 3,
        evidenceSentenceIndexes: [3],
        explanationStatement: 'Green gates guarded uses alliteration because the words begin with the /g/ sound.',
        alliterativeWords: [
          { word: 'green', initialSound: 'g' },
          { word: 'gates', initialSound: 'g' },
          { word: 'guarded', initialSound: 'g' },
        ],
        repeatedInitialSound: 'g',
        soundExplanation: 'The /g/ sound repeats at the start of the three words.',
      },
    ],
  },
] as const

export const wordplayWatchtowerPoemArtifacts = poemPlans.map((plan) => buildWordplayTextArtifact(plan))
