import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
  lessonChoice as choice,
} from './questionFactories'
import { WORDPLAY_WATCHTOWER_CONTENT_VERSION, WORDPLAY_WATCHTOWER_LESSON_IDS, WORDPLAY_WATCHTOWER_QUESTION_IDS } from './ids'
import { wordplayWatchtowerProseArtifacts } from './passages'
import { wordplayWatchtowerPoemArtifacts } from './poems'
import { WORDPLAY_WATCHTOWER_QUESTION_TAGS } from './patterns'

const commonQuestionFields = {
  benchmarkReference: 'ELA.2.R.3.1' as const,
  skillIdentifier: 'g2-across-genres-reading' as const,
  reportingCategory: 'Reading Across Genres and Vocabulary' as const,
  genre: 'literary' as const,
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2' as const,
  reviewStatus: 'DRAFT' as const,
  contentVersion: WORDPLAY_WATCHTOWER_CONTENT_VERSION,
  targetVocabulary: [] as string[],
  soundOutChunks: [] as string[],
  tags: [...WORDPLAY_WATCHTOWER_QUESTION_TAGS],
}

const joinWords = (text: string) => text.split(/\s+/).filter(Boolean)

const gardenDisplay = wordplayWatchtowerProseArtifacts[2]
const rooftopPoem = wordplayWatchtowerPoemArtifacts[0]

export const wordplayWatchtowerGuidedQuestions = [
  createMultipleChoiceQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: gardenDisplay.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.guidedSimilesAndIdiomsInContext,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.guidedSimilesAndIdiomsInContext[0],
    prompt: 'Which phrase is a simile?',
    explanation: 'Like a tiny boat compares the seed tray to a boat, so it is a simile.',
    evidenceReference: gardenDisplay.passage.sentences?.[0]?.sentenceId ?? gardenDisplay.passage.passageIdentifier,
    evidenceReferenceIds: [gardenDisplay.passage.sentences?.[0]?.sentenceId ?? gardenDisplay.passage.passageIdentifier],
    targetVocabulary: ['simile'],
    soundOutChunks: joinWords('like a tiny boat'),
    choices: [
      choice('c1', 'The seed tray rested'),
      choice('c2', 'like a tiny boat'),
      choice('c3', 'watering the sprouts'),
      choice('c4', 'made tall labels'),
    ],
    correctChoiceIds: ['c2'],
  }),
  createMultipleChoiceQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: gardenDisplay.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.guidedSimilesAndIdiomsInContext,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.guidedSimilesAndIdiomsInContext[1],
    prompt: 'What does get the ball rolling mean?',
    explanation: 'Get the ball rolling means start the work.',
    evidenceReference: gardenDisplay.passage.sentences?.[1]?.sentenceId ?? gardenDisplay.passage.passageIdentifier,
    evidenceReferenceIds: [gardenDisplay.passage.sentences?.[1]?.sentenceId ?? gardenDisplay.passage.passageIdentifier],
    targetVocabulary: ['get the ball rolling'],
    soundOutChunks: joinWords('get the ball rolling'),
    choices: [
      choice('c1', 'roll a ball'),
      choice('c2', 'decorate the display'),
      choice('c3', 'start the work'),
      choice('c4', 'fix the tray'),
    ],
    correctChoiceIds: ['c3'],
  }),
  createMultiselectQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: gardenDisplay.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.guidedSimilesAndIdiomsInContext,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.guidedSimilesAndIdiomsInContext[2],
    prompt: 'Choose two things the simile compares.',
    explanation: 'The sentence compares the seed tray and a tiny boat.',
    evidenceReference: gardenDisplay.passage.sentences?.[0]?.sentenceId ?? gardenDisplay.passage.passageIdentifier,
    evidenceReferenceIds: [gardenDisplay.passage.sentences?.[0]?.sentenceId ?? gardenDisplay.passage.passageIdentifier],
    targetVocabulary: ['seed tray', 'tiny boat'],
    soundOutChunks: joinWords('seed tray tiny boat'),
    choices: [
      choice('c1', 'the class'),
      choice('c2', 'the seed tray'),
      choice('c3', 'the tiny boat'),
      choice('c4', 'the tall labels'),
    ],
    correctChoiceIds: ['c2', 'c3'],
  }),
  createHotTextQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: gardenDisplay.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.guidedSimilesAndIdiomsInContext,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.guidedSimilesAndIdiomsInContext[3],
    prompt: 'Select the phrase that uses alliteration.',
    explanation: 'Paper petals pushed uses alliteration because the words begin with the /p/ sound.',
    evidenceReference: gardenDisplay.passage.sentences?.[3]?.sentenceId ?? gardenDisplay.passage.passageIdentifier,
    evidenceReferenceIds: [gardenDisplay.passage.sentences?.[3]?.sentenceId ?? gardenDisplay.passage.passageIdentifier],
    targetVocabulary: ['alliteration'],
    soundOutChunks: joinWords('paper petals pushed'),
    selectableSegments: [
      { id: 'h1', text: 'The seed tray rested' },
      { id: 'h2', text: 'Maya got the ball rolling' },
      { id: 'h3', text: 'paper petals pushed' },
      { id: 'h4', text: 'The display stood ready' },
    ],
    correctSegmentIds: ['h3'],
  }),
  createTableMatchQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: gardenDisplay.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.guidedSimilesAndIdiomsInContext,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.guidedSimilesAndIdiomsInContext[4],
    prompt: 'Match each expression to what it shows.',
    explanation: 'Each row matches the expression to the right wordplay type.',
    evidenceReference: gardenDisplay.passage.sentences?.[0]?.sentenceId ?? gardenDisplay.passage.passageIdentifier,
    evidenceReferenceIds: [
      gardenDisplay.passage.sentences?.[0]?.sentenceId ?? gardenDisplay.passage.passageIdentifier,
      gardenDisplay.passage.sentences?.[1]?.sentenceId ?? gardenDisplay.passage.passageIdentifier,
      gardenDisplay.passage.sentences?.[2]?.sentenceId ?? gardenDisplay.passage.passageIdentifier,
      gardenDisplay.passage.sentences?.[3]?.sentenceId ?? gardenDisplay.passage.passageIdentifier,
    ],
    targetVocabulary: ['simile', 'idiom', 'alliteration'],
    soundOutChunks: joinWords('wordplay type'),
    rows: [
      {
        id: 'r1',
        prompt: 'like a tiny boat',
        correctChoiceId: 'simile',
        options: [
          choice('idiom', 'idiom'),
          choice('alliteration', 'alliteration'),
          choice('simile', 'simile'),
        ],
      },
      {
        id: 'r2',
        prompt: 'get the ball rolling',
        correctChoiceId: 'idiom',
        options: [
          choice('simile', 'simile'),
          choice('idiom', 'idiom'),
          choice('alliteration', 'alliteration'),
        ],
      },
      {
        id: 'r3',
        prompt: 'merry markers made',
        correctChoiceId: 'alliteration',
        options: [
          choice('alliteration', 'alliteration'),
          choice('simile', 'simile'),
          choice('idiom', 'idiom'),
        ],
      },
      {
        id: 'r4',
        prompt: 'paper petals pushed',
        correctChoiceId: 'alliteration',
        options: [
          choice('idiom', 'idiom'),
          choice('alliteration', 'alliteration'),
          choice('simile', 'simile'),
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: rooftopPoem.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.guidedSoundPatternsInAPoem,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.guidedSoundPatternsInAPoem[0],
    prompt: 'Which line contains the simile that compares the flags to kites?',
    explanation: 'Line 1 compares the flags to orange kites, so it contains the simile.',
    evidenceReference: rooftopPoem.passage.sentences?.[0]?.sentenceId ?? rooftopPoem.passage.passageIdentifier,
    evidenceReferenceIds: [rooftopPoem.passage.sentences?.[0]?.sentenceId ?? rooftopPoem.passage.passageIdentifier],
    targetVocabulary: ['simile'],
    soundOutChunks: joinWords('like orange kites'),
    choices: [
      choice('c1', 'Line 4'),
      choice('c2', 'Line 2'),
      choice('c3', 'Line 1'),
      choice('c4', 'Line 3'),
    ],
    correctChoiceIds: ['c3'],
  }),
  createMultipleChoiceQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: rooftopPoem.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.guidedSoundPatternsInAPoem,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.guidedSoundPatternsInAPoem[1],
    prompt: 'What does put on our thinking caps mean?',
    explanation: 'Put on our thinking caps means start thinking carefully.',
    evidenceReference: rooftopPoem.passage.sentences?.[1]?.sentenceId ?? rooftopPoem.passage.passageIdentifier,
    evidenceReferenceIds: [rooftopPoem.passage.sentences?.[1]?.sentenceId ?? rooftopPoem.passage.passageIdentifier],
    targetVocabulary: ['put on our thinking caps'],
    soundOutChunks: joinWords('put on our thinking caps'),
    choices: [
      choice('c1', 'wear hats for the game'),
      choice('c2', 'start thinking carefully'),
      choice('c3', 'draw the game'),
      choice('c4', 'carry the ropes'),
    ],
    correctChoiceIds: ['c2'],
  }),
  createMultiselectQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: rooftopPoem.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.guidedSoundPatternsInAPoem,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.guidedSoundPatternsInAPoem[2],
    prompt: 'Choose two things the simile compares.',
    explanation: 'The poem compares the flags and orange kites.',
    evidenceReference: rooftopPoem.passage.sentences?.[0]?.sentenceId ?? rooftopPoem.passage.passageIdentifier,
    evidenceReferenceIds: [rooftopPoem.passage.sentences?.[0]?.sentenceId ?? rooftopPoem.passage.passageIdentifier],
    targetVocabulary: ['flags', 'orange kites'],
    soundOutChunks: joinWords('flags orange kites'),
    choices: [
      choice('c1', 'the roof'),
      choice('c2', 'the flags'),
      choice('c3', 'the orange kites'),
      choice('c4', 'the game'),
    ],
    correctChoiceIds: ['c2', 'c3'],
  }),
  createHotTextQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: rooftopPoem.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.guidedSoundPatternsInAPoem,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.guidedSoundPatternsInAPoem[3],
    prompt: 'Select the phrase that uses alliteration.',
    explanation: 'Tiny tools tapped uses alliteration because the words begin with the /t/ sound.',
    evidenceReference: rooftopPoem.passage.sentences?.[2]?.sentenceId ?? rooftopPoem.passage.passageIdentifier,
    evidenceReferenceIds: [rooftopPoem.passage.sentences?.[2]?.sentenceId ?? rooftopPoem.passage.passageIdentifier],
    targetVocabulary: ['alliteration'],
    soundOutChunks: joinWords('tiny tools tapped'),
    selectableSegments: [
      { id: 'h1', text: 'The flags climbed' },
      { id: 'h2', text: 'We put on our thinking caps' },
      { id: 'h3', text: 'Tiny tools tapped' },
      { id: 'h4', text: 'The rooftop stayed steady' },
    ],
    correctSegmentIds: ['h3'],
  }),
  createTableMatchQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: rooftopPoem.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.guidedSoundPatternsInAPoem,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.guidedSoundPatternsInAPoem[4],
    prompt: 'Match each expression to what it shows.',
    explanation: 'Each row matches the expression to the right wordplay type.',
    evidenceReference: rooftopPoem.passage.sentences?.[0]?.sentenceId ?? rooftopPoem.passage.passageIdentifier,
    evidenceReferenceIds: [
      rooftopPoem.passage.sentences?.[0]?.sentenceId ?? rooftopPoem.passage.passageIdentifier,
      rooftopPoem.passage.sentences?.[1]?.sentenceId ?? rooftopPoem.passage.passageIdentifier,
      rooftopPoem.passage.sentences?.[2]?.sentenceId ?? rooftopPoem.passage.passageIdentifier,
      rooftopPoem.passage.sentences?.[3]?.sentenceId ?? rooftopPoem.passage.passageIdentifier,
    ],
    targetVocabulary: ['simile', 'idiom', 'alliteration'],
    soundOutChunks: joinWords('wordplay type'),
    rows: [
      {
        id: 'r1',
        prompt: 'like orange kites',
        correctChoiceId: 'simile',
        options: [
          choice('simile', 'simile'),
          choice('idiom', 'idiom'),
          choice('alliteration', 'alliteration'),
        ],
      },
      {
        id: 'r2',
        prompt: 'put on our thinking caps',
        correctChoiceId: 'idiom',
        options: [
          choice('idiom', 'idiom'),
          choice('alliteration', 'alliteration'),
          choice('simile', 'simile'),
        ],
      },
      {
        id: 'r3',
        prompt: 'tiny tools tapped',
        correctChoiceId: 'alliteration',
        options: [
          choice('alliteration', 'alliteration'),
          choice('simile', 'simile'),
          choice('idiom', 'idiom'),
        ],
      },
      {
        id: 'r4',
        prompt: 'as straight as chalk lines',
        correctChoiceId: 'simile',
        options: [
          choice('idiom', 'idiom'),
          choice('simile', 'simile'),
          choice('alliteration', 'alliteration'),
        ],
      },
    ],
  }),
] as const

export const wordplayWatchtowerGuidedLessonQuestions = {
  guidedSimilesAndIdiomsInContext: wordplayWatchtowerGuidedQuestions.slice(0, 5),
  guidedSoundPatternsInAPoem: wordplayWatchtowerGuidedQuestions.slice(5, 10),
} as const
