import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
  createTwoPartQuestion,
  lessonChoice as choice,
} from './questionFactories'
import { WORDPLAY_WATCHTOWER_CONTENT_VERSION, WORDPLAY_WATCHTOWER_LESSON_IDS, WORDPLAY_WATCHTOWER_QUESTION_IDS } from './ids'
import { wordplayWatchtowerPoemArtifacts } from './poems'
import { wordplayWatchtowerProseArtifacts } from './passages'
import { WORDPLAY_WATCHTOWER_QUESTION_TAGS } from './patterns'

const commonQuestionFields = {
  benchmarkReference: 'ELA.2.R.3.1' as const,
  skillIdentifier: 'g2-across-genres-reading' as const,
  reportingCategory: 'Reading Across Genres and Vocabulary' as const,
  genre: 'literary' as const,
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2' as const,
  reviewStatus: 'DRAFT' as const,
  contentVersion: WORDPLAY_WATCHTOWER_CONTENT_VERSION,
  targetVocabulary: [] as string[],
  soundOutChunks: [] as string[],
  tags: [...WORDPLAY_WATCHTOWER_QUESTION_TAGS],
}

const joinWords = (text: string) => text.split(/\s+/).filter(Boolean)

const bridgeModel = wordplayWatchtowerProseArtifacts[3]
const trailMap = wordplayWatchtowerProseArtifacts[4]
const rooftopPoem = wordplayWatchtowerPoemArtifacts[0]
const seedSong = wordplayWatchtowerPoemArtifacts[1]

export const wordplayWatchtowerCheckpointQuestions = [
  createMultipleChoiceQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: bridgeModel.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointA,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointA[0],
    prompt: 'Which phrase is a simile?',
    explanation: 'Like a narrow smile compares the bridge model to a smile, so it is a simile.',
    evidenceReference: bridgeModel.passage.sentences?.[0]?.sentenceId ?? bridgeModel.passage.passageIdentifier,
    evidenceReferenceIds: [bridgeModel.passage.sentences?.[0]?.sentenceId ?? bridgeModel.passage.passageIdentifier],
    targetVocabulary: ['simile'],
    soundOutChunks: joinWords('like a narrow smile'),
    choices: [
      choice('c1', 'The bridge model stood'),
      choice('c2', 'like a narrow smile'),
      choice('c3', 'the class worked'),
      choice('c4', 'called it a day'),
    ],
    correctChoiceIds: ['c2'],
  }),
  createMultipleChoiceQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: bridgeModel.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointA,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointA[1],
    prompt: 'What does in the same boat mean?',
    explanation: 'In the same boat means sharing the same problem.',
    evidenceReference: bridgeModel.passage.sentences?.[1]?.sentenceId ?? bridgeModel.passage.passageIdentifier,
    evidenceReferenceIds: [bridgeModel.passage.sentences?.[1]?.sentenceId ?? bridgeModel.passage.passageIdentifier],
    targetVocabulary: ['in the same boat'],
    soundOutChunks: joinWords('in the same boat'),
    choices: [
      choice('c1', 'share the same problem'),
      choice('c2', 'row a boat'),
      choice('c3', 'build a bridge'),
      choice('c4', 'hold a rope'),
    ],
    correctChoiceIds: ['c1'],
  }),
  createMultipleChoiceQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: bridgeModel.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointA,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointA[2],
    prompt: 'Which phrase uses alliteration?',
    explanation: 'Brave builders balanced uses alliteration because the words begin with the /b/ sound.',
    evidenceReference: bridgeModel.passage.sentences?.[2]?.sentenceId ?? bridgeModel.passage.passageIdentifier,
    evidenceReferenceIds: [bridgeModel.passage.sentences?.[2]?.sentenceId ?? bridgeModel.passage.passageIdentifier],
    targetVocabulary: ['alliteration'],
    soundOutChunks: joinWords('brave builders balanced'),
    choices: [
      choice('c1', 'in the same boat'),
      choice('c2', 'Brave builders balanced'),
      choice('c3', 'The paper tower stayed tall'),
      choice('c4', 'The last test showed'),
    ],
    correctChoiceIds: ['c2'],
  }),
  createMultiselectQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: bridgeModel.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointA,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointA[3],
    prompt: 'Choose two clues that help explain called it a day.',
    explanation: 'The bell rang and the class cleaned up, so the work stopped.',
    evidenceReference: bridgeModel.passage.sentences?.[3]?.sentenceId ?? bridgeModel.passage.passageIdentifier,
    evidenceReferenceIds: [
      bridgeModel.passage.sentences?.[3]?.sentenceId ?? bridgeModel.passage.passageIdentifier,
      bridgeModel.passage.sentences?.[6]?.sentenceId ?? bridgeModel.passage.passageIdentifier,
    ],
    targetVocabulary: ['called it a day'],
    soundOutChunks: joinWords('bell rang cleaned up'),
    choices: [
      choice('c1', 'when the bell rang'),
      choice('c2', 'the sand tray'),
      choice('c3', 'we cleaned up'),
      choice('c4', 'the toy car'),
    ],
    correctChoiceIds: ['c1', 'c3'],
  }),
  createHotTextQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: rooftopPoem.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointA,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointA[4],
    prompt: 'Select the phrase that uses alliteration.',
    explanation: 'Tiny tools tapped uses alliteration because the words begin with the /t/ sound.',
    evidenceReference: rooftopPoem.passage.sentences?.[2]?.sentenceId ?? rooftopPoem.passage.passageIdentifier,
    evidenceReferenceIds: [rooftopPoem.passage.sentences?.[2]?.sentenceId ?? rooftopPoem.passage.passageIdentifier],
    targetVocabulary: ['alliteration'],
    soundOutChunks: joinWords('tiny tools tapped'),
    selectableSegments: [
      { id: 'h1', text: 'The flags climbed' },
      { id: 'h2', text: 'We put on our thinking caps' },
      { id: 'h3', text: 'Tiny tools tapped' },
      { id: 'h4', text: 'The rooftop stayed steady' },
    ],
    correctSegmentIds: ['h3'],
  }),
  createTableMatchQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: bridgeModel.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointA,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointA[5],
    prompt: 'Match each expression to what it shows.',
    explanation: 'Each row matches the expression to the right wordplay type.',
    evidenceReference: bridgeModel.passage.sentences?.[0]?.sentenceId ?? bridgeModel.passage.passageIdentifier,
    evidenceReferenceIds: [
      bridgeModel.passage.sentences?.[0]?.sentenceId ?? bridgeModel.passage.passageIdentifier,
      bridgeModel.passage.sentences?.[1]?.sentenceId ?? bridgeModel.passage.passageIdentifier,
      bridgeModel.passage.sentences?.[2]?.sentenceId ?? bridgeModel.passage.passageIdentifier,
      bridgeModel.passage.sentences?.[3]?.sentenceId ?? bridgeModel.passage.passageIdentifier,
    ],
    targetVocabulary: ['simile', 'idiom', 'alliteration'],
    soundOutChunks: joinWords('wordplay type'),
    rows: [
      {
        id: 'r1',
        prompt: 'like a narrow smile',
        correctChoiceId: 'simile',
        options: [
          choice('alliteration', 'alliteration'),
          choice('idiom', 'idiom'),
          choice('simile', 'simile'),
        ],
      },
      {
        id: 'r2',
        prompt: 'in the same boat',
        correctChoiceId: 'idiom',
        options: [
          choice('simile', 'simile'),
          choice('idiom', 'idiom'),
          choice('alliteration', 'alliteration'),
        ],
      },
      {
        id: 'r3',
        prompt: 'brave builders balanced',
        correctChoiceId: 'alliteration',
        options: [
          choice('alliteration', 'alliteration'),
          choice('simile', 'simile'),
          choice('idiom', 'idiom'),
        ],
      },
      {
        id: 'r4',
        prompt: 'call it a day',
        correctChoiceId: 'idiom',
        options: [
          choice('idiom', 'idiom'),
          choice('alliteration', 'alliteration'),
          choice('simile', 'simile'),
        ],
      },
    ],
  }),
  createTwoPartQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: bridgeModel.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointA,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointA[6],
    prompt: 'What does called it a day mean?',
    explanation: 'Called it a day means stop working for now, and the sentence about cleaning up confirms it.',
    evidenceReference: bridgeModel.passage.sentences?.[3]?.sentenceId ?? bridgeModel.passage.passageIdentifier,
    evidenceReferenceIds: [
      bridgeModel.passage.sentences?.[3]?.sentenceId ?? bridgeModel.passage.passageIdentifier,
      bridgeModel.passage.sentences?.[6]?.sentenceId ?? bridgeModel.passage.passageIdentifier,
    ],
    targetVocabulary: ['called it a day'],
    soundOutChunks: joinWords('called it a day'),
    partAPrompt: 'What does the phrase mean?',
    partAChoices: [
      choice('a1', 'stop working for now'),
      choice('a2', 'start the bridge'),
      choice('a3', 'carry the toy car'),
    ],
    partACorrectChoiceId: 'a1',
    partBPrompt: 'Which detail supports that meaning?',
    partBChoices: [
      choice('b1', 'The last test showed our bridge could hold a toy car.'),
      choice('b2', 'When the bell rang, we called it a day and cleaned up.'),
      choice('b3', 'The paper tower stayed tall beside the sand tray.'),
    ],
    partBCorrectChoiceId: 'b2',
  }),

  createMultipleChoiceQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: trailMap.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointB,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointB[0],
    prompt: 'Which phrase is a simile?',
    explanation: 'As calm as a pond compares the group to a pond, so it is a simile.',
    evidenceReference: trailMap.passage.sentences?.[1]?.sentenceId ?? trailMap.passage.passageIdentifier,
    evidenceReferenceIds: [trailMap.passage.sentences?.[1]?.sentenceId ?? trailMap.passage.passageIdentifier],
    targetVocabulary: ['simile'],
    soundOutChunks: joinWords('as calm as a pond'),
    choices: [
      choice('c1', 'The trail sign looked'),
      choice('c2', 'as calm as a pond'),
      choice('c3', 'keep an eye on'),
      choice('c4', 'The map stayed folded'),
    ],
    correctChoiceIds: ['c2'],
  }),
  createMultipleChoiceQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: trailMap.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointB,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointB[1],
    prompt: 'How do the clues explain keep an eye on?',
    explanation: 'Keep an eye on means watch something carefully.',
    evidenceReference: trailMap.passage.sentences?.[3]?.sentenceId ?? trailMap.passage.passageIdentifier,
    evidenceReferenceIds: [trailMap.passage.sentences?.[3]?.sentenceId ?? trailMap.passage.passageIdentifier],
    targetVocabulary: ['keep an eye on'],
    soundOutChunks: joinWords('keep an eye on'),
    choices: [
      choice('c1', 'ignore the mud patch'),
      choice('c2', 'watch something carefully'),
      choice('c3', 'look for a pond'),
      choice('c4', 'fold the map'),
    ],
    correctChoiceIds: ['c2'],
  }),
  createMultipleChoiceQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: trailMap.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointB,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointB[2],
    prompt: 'Which phrase uses alliteration?',
    explanation: 'Path markers pointed uses alliteration because the words begin with the /p/ sound.',
    evidenceReference: trailMap.passage.sentences?.[2]?.sentenceId ?? trailMap.passage.passageIdentifier,
    evidenceReferenceIds: [trailMap.passage.sentences?.[2]?.sentenceId ?? trailMap.passage.passageIdentifier],
    targetVocabulary: ['alliteration'],
    soundOutChunks: joinWords('path markers pointed'),
    choices: [
      choice('c1', 'as calm as a pond'),
      choice('c2', 'keep an eye on'),
      choice('c3', 'path markers pointed'),
      choice('c4', 'The map stayed folded'),
    ],
    correctChoiceIds: ['c3'],
  }),
  createMultiselectQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: trailMap.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointB,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointB[3],
    prompt: 'Choose two things the simile compares.',
    explanation: 'The sentence compares the group to a pond.',
    evidenceReference: trailMap.passage.sentences?.[1]?.sentenceId ?? trailMap.passage.passageIdentifier,
    evidenceReferenceIds: [trailMap.passage.sentences?.[1]?.sentenceId ?? trailMap.passage.passageIdentifier],
    targetVocabulary: ['our group', 'a pond'],
    soundOutChunks: joinWords('our group a pond'),
    choices: [
      choice('c1', 'our group'),
      choice('c2', 'the trail sign'),
      choice('c3', 'a pond'),
      choice('c4', 'the mud patch'),
    ],
    correctChoiceIds: ['c1', 'c3'],
  }),
  createHotTextQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: seedSong.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointB,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointB[4],
    prompt: 'Select the phrase that uses alliteration.',
    explanation: 'Green gates guarded uses alliteration because the words begin with the /g/ sound.',
    evidenceReference: seedSong.passage.sentences?.[3]?.sentenceId ?? seedSong.passage.passageIdentifier,
    evidenceReferenceIds: [seedSong.passage.sentences?.[3]?.sentenceId ?? seedSong.passage.passageIdentifier],
    targetVocabulary: ['alliteration'],
    soundOutChunks: joinWords('green gates guarded'),
    selectableSegments: [
      { id: 'h1', text: 'The seed moved' },
      { id: 'h2', text: 'I had to hold your horses' },
      { id: 'h3', text: 'Green gates guarded' },
      { id: 'h4', text: 'The garden woke' },
    ],
    correctSegmentIds: ['h3'],
  }),
  createTableMatchQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: trailMap.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointB,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointB[5],
    prompt: 'Match each expression to what it shows.',
    explanation: 'Each row matches the expression to the right wordplay type.',
    evidenceReference: trailMap.passage.sentences?.[0]?.sentenceId ?? trailMap.passage.passageIdentifier,
    evidenceReferenceIds: [
      trailMap.passage.sentences?.[0]?.sentenceId ?? trailMap.passage.passageIdentifier,
      trailMap.passage.sentences?.[1]?.sentenceId ?? trailMap.passage.passageIdentifier,
      trailMap.passage.sentences?.[2]?.sentenceId ?? trailMap.passage.passageIdentifier,
      trailMap.passage.sentences?.[3]?.sentenceId ?? trailMap.passage.passageIdentifier,
    ],
    targetVocabulary: ['simile', 'idiom', 'alliteration'],
    soundOutChunks: joinWords('wordplay type'),
    rows: [
      {
        id: 'r1',
        prompt: 'as calm as a pond',
        correctChoiceId: 'simile',
        options: [
          choice('simile', 'simile'),
          choice('idiom', 'idiom'),
          choice('alliteration', 'alliteration'),
        ],
      },
      {
        id: 'r2',
        prompt: 'keep an eye on',
        correctChoiceId: 'idiom',
        options: [
          choice('alliteration', 'alliteration'),
          choice('idiom', 'idiom'),
          choice('simile', 'simile'),
        ],
      },
      {
        id: 'r3',
        prompt: 'path markers pointed',
        correctChoiceId: 'alliteration',
        options: [
          choice('idiom', 'idiom'),
          choice('alliteration', 'alliteration'),
          choice('simile', 'simile'),
        ],
      },
      {
        id: 'r4',
        prompt: 'green gates guarded',
        correctChoiceId: 'alliteration',
        options: [
          choice('simile', 'simile'),
          choice('alliteration', 'alliteration'),
          choice('idiom', 'idiom'),
        ],
      },
    ],
  }),
  createTwoPartQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: trailMap.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointB,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointB[6],
    prompt: 'What does keep an eye on mean?',
    explanation: 'Keep an eye on means watch something carefully, and the sentence about the mud patch shows that meaning.',
    evidenceReference: trailMap.passage.sentences?.[3]?.sentenceId ?? trailMap.passage.passageIdentifier,
    evidenceReferenceIds: [
      trailMap.passage.sentences?.[3]?.sentenceId ?? trailMap.passage.passageIdentifier,
      trailMap.passage.sentences?.[1]?.sentenceId ?? trailMap.passage.passageIdentifier,
    ],
    targetVocabulary: ['keep an eye on'],
    soundOutChunks: joinWords('keep an eye on'),
    partAPrompt: 'What does the phrase mean?',
    partAChoices: [
      choice('a1', 'watch something carefully'),
      choice('a2', 'keep an eye still'),
      choice('a3', 'walk on the trail'),
    ],
    partACorrectChoiceId: 'a1',
    partBPrompt: 'Which detail supports that meaning?',
    partBChoices: [
      choice('b1', 'The map stayed folded in my pocket.'),
      choice('b2', 'The guide said to keep an eye on the mud patch.'),
      choice('b3', 'The last bend led us back to the bus.'),
    ],
    partBCorrectChoiceId: 'b2',
  }),

  createMultipleChoiceQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: seedSong.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointC,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointC[0],
    prompt: 'Which line contains the simile?',
    explanation: 'Line 1 compares the seed to snow, so it contains the simile.',
    evidenceReference: seedSong.passage.sentences?.[0]?.sentenceId ?? seedSong.passage.passageIdentifier,
    evidenceReferenceIds: [seedSong.passage.sentences?.[0]?.sentenceId ?? seedSong.passage.passageIdentifier],
    targetVocabulary: ['simile'],
    soundOutChunks: joinWords('as soft as snow'),
    choices: [
      choice('c1', 'Line 4'),
      choice('c2', 'Line 1'),
      choice('c3', 'Line 3'),
      choice('c4', 'Line 2'),
    ],
    correctChoiceIds: ['c2'],
  }),
  createMultipleChoiceQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: seedSong.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointC,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointC[1],
    prompt: 'What does hold your horses mean?',
    explanation: 'Hold your horses means wait patiently.',
    evidenceReference: seedSong.passage.sentences?.[1]?.sentenceId ?? seedSong.passage.passageIdentifier,
    evidenceReferenceIds: [seedSong.passage.sentences?.[1]?.sentenceId ?? seedSong.passage.passageIdentifier],
    targetVocabulary: ['hold your horses'],
    soundOutChunks: joinWords('hold your horses'),
    choices: [
      choice('c1', 'wait patiently'),
      choice('c2', 'run faster'),
      choice('c3', 'carry water'),
      choice('c4', 'dig the soil'),
    ],
    correctChoiceIds: ['c1'],
  }),
  createMultipleChoiceQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: seedSong.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointC,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointC[2],
    prompt: 'Which phrase uses alliteration?',
    explanation: 'Spry sprouts swayed uses alliteration because the words begin with the /s/ sound.',
    evidenceReference: seedSong.passage.sentences?.[2]?.sentenceId ?? seedSong.passage.passageIdentifier,
    evidenceReferenceIds: [seedSong.passage.sentences?.[2]?.sentenceId ?? seedSong.passage.passageIdentifier],
    targetVocabulary: ['alliteration'],
    soundOutChunks: joinWords('spry sprouts swayed'),
    choices: [
      choice('c1', 'The garden woke'),
      choice('c2', 'spry sprouts swayed'),
      choice('c3', 'as soft as snow'),
      choice('c4', 'hold your horses'),
    ],
    correctChoiceIds: ['c2'],
  }),
  createMultiselectQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: seedSong.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointC,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointC[3],
    prompt: 'Choose two clues that help explain hold your horses.',
    explanation: 'The line says the speaker had to wait while the rain drum rolled, so the idiom means wait patiently.',
    evidenceReference: seedSong.passage.sentences?.[1]?.sentenceId ?? seedSong.passage.passageIdentifier,
    evidenceReferenceIds: [seedSong.passage.sentences?.[1]?.sentenceId ?? seedSong.passage.passageIdentifier],
    targetVocabulary: ['hold your horses'],
    soundOutChunks: joinWords('wait patiently'),
    choices: [
      choice('c1', 'had to'),
      choice('c2', 'spry sprouts swayed'),
      choice('c3', 'while the rain drum rolled'),
      choice('c4', 'the garden woke'),
    ],
    correctChoiceIds: ['c1', 'c3'],
  }),
  createHotTextQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: seedSong.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointC,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointC[4],
    prompt: 'Select the phrase that uses alliteration.',
    explanation: 'Green gates guarded uses alliteration because the words begin with the /g/ sound.',
    evidenceReference: seedSong.passage.sentences?.[3]?.sentenceId ?? seedSong.passage.passageIdentifier,
    evidenceReferenceIds: [seedSong.passage.sentences?.[3]?.sentenceId ?? seedSong.passage.passageIdentifier],
    targetVocabulary: ['alliteration'],
    soundOutChunks: joinWords('green gates guarded'),
    selectableSegments: [
      { id: 'h1', text: 'The seed moved' },
      { id: 'h2', text: 'I had to hold your horses' },
      { id: 'h3', text: 'Green gates guarded' },
      { id: 'h4', text: 'The garden woke' },
    ],
    correctSegmentIds: ['h3'],
  }),
  createTableMatchQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: seedSong.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointC,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointC[5],
    prompt: 'Match each expression to what it shows.',
    explanation: 'Each row matches the expression to the right wordplay type.',
    evidenceReference: seedSong.passage.sentences?.[0]?.sentenceId ?? seedSong.passage.passageIdentifier,
    evidenceReferenceIds: [
      seedSong.passage.sentences?.[0]?.sentenceId ?? seedSong.passage.passageIdentifier,
      seedSong.passage.sentences?.[1]?.sentenceId ?? seedSong.passage.passageIdentifier,
      seedSong.passage.sentences?.[2]?.sentenceId ?? seedSong.passage.passageIdentifier,
      seedSong.passage.sentences?.[3]?.sentenceId ?? seedSong.passage.passageIdentifier,
    ],
    targetVocabulary: ['simile', 'idiom', 'alliteration'],
    soundOutChunks: joinWords('wordplay type'),
    rows: [
      {
        id: 'r1',
        prompt: 'as soft as snow',
        correctChoiceId: 'simile',
        options: [
          choice('idiom', 'idiom'),
          choice('simile', 'simile'),
          choice('alliteration', 'alliteration'),
        ],
      },
      {
        id: 'r2',
        prompt: 'hold your horses',
        correctChoiceId: 'idiom',
        options: [
          choice('simile', 'simile'),
          choice('idiom', 'idiom'),
          choice('alliteration', 'alliteration'),
        ],
      },
      {
        id: 'r3',
        prompt: 'spry sprouts swayed',
        correctChoiceId: 'alliteration',
        options: [
          choice('alliteration', 'alliteration'),
          choice('simile', 'simile'),
          choice('idiom', 'idiom'),
        ],
      },
      {
        id: 'r4',
        prompt: 'green gates guarded',
        correctChoiceId: 'alliteration',
        options: [
          choice('simile', 'simile'),
          choice('alliteration', 'alliteration'),
          choice('idiom', 'idiom'),
        ],
      },
    ],
  }),
  createTwoPartQuestion({
    ...commonQuestionFields,
    difficulty: 1,
    passageIdentifier: seedSong.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.checkpointC,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.checkpointC[6],
    prompt: 'What does as soft as snow mean?',
    explanation: 'As soft as snow means the seed moved gently, and the sentence about the soil supports that meaning.',
    evidenceReference: seedSong.passage.sentences?.[0]?.sentenceId ?? seedSong.passage.passageIdentifier,
    evidenceReferenceIds: [
      seedSong.passage.sentences?.[0]?.sentenceId ?? seedSong.passage.passageIdentifier,
      seedSong.passage.sentences?.[7]?.sentenceId ?? seedSong.passage.passageIdentifier,
    ],
    targetVocabulary: ['as soft as snow'],
    soundOutChunks: joinWords('as soft as snow'),
    partAPrompt: 'What does the phrase mean?',
    partAChoices: [
      choice('a1', 'moved gently'),
      choice('a2', 'grew taller'),
      choice('a3', 'waited on the bench'),
    ],
    partACorrectChoiceId: 'a1',
    partBPrompt: 'Which detail supports that meaning?',
    partBChoices: [
      choice('b1', 'The garden woke with a quiet sigh.'),
      choice('b2', 'The seed moved as soft as snow through the soil.'),
      choice('b3', 'Green gates guarded the garden.'),
    ],
    partBCorrectChoiceId: 'b2',
  }),
] as const

export const wordplayWatchtowerCheckpointLessonQuestions = {
  checkpointA: wordplayWatchtowerCheckpointQuestions.slice(0, 7),
  checkpointB: wordplayWatchtowerCheckpointQuestions.slice(7, 14),
  checkpointC: wordplayWatchtowerCheckpointQuestions.slice(14, 21),
} as const
