import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
  lessonChoice as choice,
} from './questionFactories'
import { WORDPLAY_WATCHTOWER_CONTENT_VERSION, WORDPLAY_WATCHTOWER_LESSON_IDS, WORDPLAY_WATCHTOWER_QUESTION_IDS } from './ids'
import { wordplayWatchtowerProseArtifacts } from './passages'
import { WORDPLAY_WATCHTOWER_QUESTION_TAGS } from './patterns'

const commonQuestionFields = {
  benchmarkReference: 'ELA.2.R.3.1' as const,
  skillIdentifier: 'g2-across-genres-reading' as const,
  reportingCategory: 'Reading Across Genres and Vocabulary' as const,
  genre: 'literary' as const,
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2' as const,
  reviewStatus: 'DRAFT' as const,
  contentVersion: WORDPLAY_WATCHTOWER_CONTENT_VERSION,
  targetVocabulary: [] as string[],
  soundOutChunks: [] as string[],
  tags: [...WORDPLAY_WATCHTOWER_QUESTION_TAGS],
}

const joinWords = (text: string) => text.split(/\s+/).filter(Boolean)

const kiteParade = wordplayWatchtowerProseArtifacts[0]
const libraryHelpers = wordplayWatchtowerProseArtifacts[1]

export const wordplayWatchtowerPrerequisiteQuestions = [
  createMultipleChoiceQuestion({
    ...commonQuestionFields,
    difficulty: 0,
    passageIdentifier: kiteParade.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.prereqSpotTheComparison,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.prereqSpotTheComparison[0],
    prompt: 'Which sentence contains the simile?',
    explanation: 'Sentence 1 compares the banner to a bright fish, so it contains the simile.',
    evidenceReference: kiteParade.passage.sentences?.[0]?.sentenceId ?? kiteParade.passage.passageIdentifier,
    evidenceReferenceIds: [kiteParade.passage.sentences?.[0]?.sentenceId ?? kiteParade.passage.passageIdentifier],
    targetVocabulary: ['simile'],
    soundOutChunks: joinWords('like a bright fish'),
    choices: [
      choice('s1', kiteParade.passage.sentences?.[1]?.text ?? ''),
      choice('s2', kiteParade.passage.sentences?.[0]?.text ?? ''),
      choice('s3', kiteParade.passage.sentences?.[2]?.text ?? ''),
      choice('s4', kiteParade.passage.sentences?.[3]?.text ?? ''),
    ],
    correctChoiceIds: ['s2'],
  }),
  createMultipleChoiceQuestion({
    ...commonQuestionFields,
    difficulty: 0,
    passageIdentifier: kiteParade.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.prereqSpotTheComparison,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.prereqSpotTheComparison[1],
    prompt: 'What does lend a hand mean?',
    explanation: 'Lend a hand means help someone.',
    evidenceReference: kiteParade.passage.sentences?.[1]?.sentenceId ?? kiteParade.passage.passageIdentifier,
    evidenceReferenceIds: [kiteParade.passage.sentences?.[1]?.sentenceId ?? kiteParade.passage.passageIdentifier],
    targetVocabulary: ['lend a hand'],
    soundOutChunks: joinWords('lend a hand'),
    choices: [
      choice('h1', 'carry the string'),
      choice('h2', 'help someone'),
      choice('h3', 'watch the booth'),
      choice('h4', 'paint the banner'),
    ],
    correctChoiceIds: ['h2'],
  }),
  createMultiselectQuestion({
    ...commonQuestionFields,
    difficulty: 0,
    passageIdentifier: kiteParade.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.prereqSpotTheComparison,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.prereqSpotTheComparison[2],
    prompt: 'Choose two clues that help explain lend a hand.',
    explanation: 'The helpers are already helping by holding the string and passing tape.',
    evidenceReference: kiteParade.passage.sentences?.[1]?.sentenceId ?? kiteParade.passage.passageIdentifier,
    evidenceReferenceIds: [
      kiteParade.passage.sentences?.[1]?.sentenceId ?? kiteParade.passage.passageIdentifier,
      kiteParade.passage.sentences?.[5]?.sentenceId ?? kiteParade.passage.passageIdentifier,
    ],
    targetVocabulary: ['lend a hand', 'helpers'],
    soundOutChunks: joinWords('helpers holding'),
    choices: [
      choice('c1', 'a bright fish'),
      choice('c2', 'helpers'),
      choice('c3', 'holding the string'),
      choice('c4', 'the last page of the plan'),
    ],
    correctChoiceIds: ['c2', 'c3'],
  }),
  createHotTextQuestion({
    ...commonQuestionFields,
    difficulty: 0,
    passageIdentifier: kiteParade.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.prereqSpotTheComparison,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.prereqSpotTheComparison[3],
    prompt: 'Select the phrase that uses alliteration.',
    explanation: 'Blue banners bobbed uses alliteration because the words begin with the /b/ sound.',
    evidenceReference: kiteParade.passage.sentences?.[2]?.sentenceId ?? kiteParade.passage.passageIdentifier,
    evidenceReferenceIds: [kiteParade.passage.sentences?.[2]?.sentenceId ?? kiteParade.passage.passageIdentifier],
    targetVocabulary: ['alliteration'],
    soundOutChunks: joinWords('blue banners bobbed'),
    selectableSegments: [
      { id: 'h1', text: 'At the kite parade' },
      { id: 'h2', text: 'Blue banners bobbed' },
      { id: 'h3', text: 'beside the booth' },
      { id: 'h4', text: 'The kite tail curled' },
    ],
    correctSegmentIds: ['h2'],
  }),
  createTableMatchQuestion({
    ...commonQuestionFields,
    difficulty: 0,
    passageIdentifier: kiteParade.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.prereqSpotTheComparison,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.prereqSpotTheComparison[4],
    prompt: 'Match each expression to what it shows.',
    explanation: 'Each row matches the expression to the right wordplay type.',
    evidenceReference: kiteParade.passage.sentences?.[0]?.sentenceId ?? kiteParade.passage.passageIdentifier,
    evidenceReferenceIds: [
      kiteParade.passage.sentences?.[0]?.sentenceId ?? kiteParade.passage.passageIdentifier,
      kiteParade.passage.sentences?.[1]?.sentenceId ?? kiteParade.passage.passageIdentifier,
      kiteParade.passage.sentences?.[2]?.sentenceId ?? kiteParade.passage.passageIdentifier,
      kiteParade.passage.sentences?.[3]?.sentenceId ?? kiteParade.passage.passageIdentifier,
    ],
    targetVocabulary: ['simile', 'idiom', 'alliteration'],
    soundOutChunks: joinWords('wordplay type'),
    rows: [
      {
        id: 'r1',
        prompt: 'like a bright fish',
        correctChoiceId: 'simile',
        options: [
          choice('alliteration', 'alliteration'),
          choice('idiom', 'idiom'),
          choice('simile', 'simile'),
        ],
      },
      {
        id: 'r2',
        prompt: 'lend a hand',
        correctChoiceId: 'idiom',
        options: [
          choice('simile', 'simile'),
          choice('idiom', 'idiom'),
          choice('alliteration', 'alliteration'),
        ],
      },
      {
        id: 'r3',
        prompt: 'blue banners bobbed',
        correctChoiceId: 'alliteration',
        options: [
          choice('alliteration', 'alliteration'),
          choice('simile', 'simile'),
          choice('idiom', 'idiom'),
        ],
      },
      {
        id: 'r4',
        prompt: 'as smooth as a ribbon',
        correctChoiceId: 'simile',
        options: [
          choice('idiom', 'idiom'),
          choice('simile', 'simile'),
          choice('alliteration', 'alliteration'),
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...commonQuestionFields,
    difficulty: 0,
    passageIdentifier: libraryHelpers.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.prereqMeaningBeyondWords,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.prereqMeaningBeyondWords[0],
    prompt: 'Which sentence contains the simile?',
    explanation: 'Sentence 1 compares the hall to a cloud, so it contains the simile.',
    evidenceReference: libraryHelpers.passage.sentences?.[0]?.sentenceId ?? libraryHelpers.passage.passageIdentifier,
    evidenceReferenceIds: [libraryHelpers.passage.sentences?.[0]?.sentenceId ?? libraryHelpers.passage.passageIdentifier],
    targetVocabulary: ['simile'],
    soundOutChunks: joinWords('as quiet as a cloud'),
    choices: [
      choice('s1', libraryHelpers.passage.sentences?.[2]?.text ?? ''),
      choice('s2', libraryHelpers.passage.sentences?.[0]?.text ?? ''),
      choice('s3', libraryHelpers.passage.sentences?.[1]?.text ?? ''),
      choice('s4', libraryHelpers.passage.sentences?.[3]?.text ?? ''),
    ],
    correctChoiceIds: ['s2'],
  }),
  createMultipleChoiceQuestion({
    ...commonQuestionFields,
    difficulty: 0,
    passageIdentifier: libraryHelpers.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.prereqMeaningBeyondWords,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.prereqMeaningBeyondWords[1],
    prompt: 'What does on the same page mean?',
    explanation: 'On the same page means the readers agree about the plan.',
    evidenceReference: libraryHelpers.passage.sentences?.[1]?.sentenceId ?? libraryHelpers.passage.passageIdentifier,
    evidenceReferenceIds: [libraryHelpers.passage.sentences?.[1]?.sentenceId ?? libraryHelpers.passage.passageIdentifier],
    targetVocabulary: ['on the same page'],
    soundOutChunks: joinWords('on the same page'),
    choices: [
      choice('m1', 'turn the page in a book'),
      choice('m2', 'agree about the plan'),
      choice('m3', 'watch the shelf'),
      choice('m4', 'move the chairs'),
    ],
    correctChoiceIds: ['m2'],
  }),
  createMultiselectQuestion({
    ...commonQuestionFields,
    difficulty: 0,
    passageIdentifier: libraryHelpers.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.prereqMeaningBeyondWords,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.prereqMeaningBeyondWords[2],
    prompt: 'Choose two details that show the readers agreed about the plan.',
    explanation: 'The readers and the book club plan show that everyone was on the same page.',
    evidenceReference: libraryHelpers.passage.sentences?.[1]?.sentenceId ?? libraryHelpers.passage.passageIdentifier,
    evidenceReferenceIds: [libraryHelpers.passage.sentences?.[1]?.sentenceId ?? libraryHelpers.passage.passageIdentifier],
    targetVocabulary: ['readers', 'book club plan'],
    soundOutChunks: joinWords('readers book club'),
    choices: [
      choice('c1', 'the quiet hall'),
      choice('c2', 'The readers'),
      choice('c3', 'the returns shelf'),
      choice('c4', 'the book club plan'),
    ],
    correctChoiceIds: ['c2', 'c4'],
  }),
  createHotTextQuestion({
    ...commonQuestionFields,
    difficulty: 0,
    passageIdentifier: libraryHelpers.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.prereqMeaningBeyondWords,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.prereqMeaningBeyondWords[3],
    prompt: 'Select the phrase that uses alliteration.',
    explanation: 'Careful cats carried uses alliteration because the words begin with the /c/ sound.',
    evidenceReference: libraryHelpers.passage.sentences?.[2]?.sentenceId ?? libraryHelpers.passage.passageIdentifier,
    evidenceReferenceIds: [libraryHelpers.passage.sentences?.[2]?.sentenceId ?? libraryHelpers.passage.passageIdentifier],
    targetVocabulary: ['alliteration'],
    soundOutChunks: joinWords('careful cats carried'),
    selectableSegments: [
      { id: 'h1', text: 'The hall was' },
      { id: 'h2', text: 'careful cats carried' },
      { id: 'h3', text: 'down the center aisle' },
      { id: 'h4', text: 'The helpers kept an eye' },
    ],
    correctSegmentIds: ['h2'],
  }),
  createTableMatchQuestion({
    ...commonQuestionFields,
    difficulty: 0,
    passageIdentifier: libraryHelpers.passage.passageIdentifier,
    lessonIdentifier: WORDPLAY_WATCHTOWER_LESSON_IDS.prereqMeaningBeyondWords,
    questionIdentifier: WORDPLAY_WATCHTOWER_QUESTION_IDS.prereqMeaningBeyondWords[4],
    prompt: 'Match each expression to what it shows.',
    explanation: 'Each row matches the expression to the right wordplay type.',
    evidenceReference: libraryHelpers.passage.sentences?.[0]?.sentenceId ?? libraryHelpers.passage.passageIdentifier,
    evidenceReferenceIds: [
      libraryHelpers.passage.sentences?.[0]?.sentenceId ?? libraryHelpers.passage.passageIdentifier,
      libraryHelpers.passage.sentences?.[1]?.sentenceId ?? libraryHelpers.passage.passageIdentifier,
      libraryHelpers.passage.sentences?.[2]?.sentenceId ?? libraryHelpers.passage.passageIdentifier,
      libraryHelpers.passage.sentences?.[3]?.sentenceId ?? libraryHelpers.passage.passageIdentifier,
    ],
    targetVocabulary: ['simile', 'idiom', 'alliteration'],
    soundOutChunks: joinWords('wordplay type'),
    rows: [
      {
        id: 'r1',
        prompt: 'as quiet as a cloud',
        correctChoiceId: 'simile',
        options: [
          choice('simile', 'simile'),
          choice('idiom', 'idiom'),
          choice('alliteration', 'alliteration'),
        ],
      },
      {
        id: 'r2',
        prompt: 'on the same page',
        correctChoiceId: 'idiom',
        options: [
          choice('alliteration', 'alliteration'),
          choice('idiom', 'idiom'),
          choice('simile', 'simile'),
        ],
      },
      {
        id: 'r3',
        prompt: 'careful cats carried',
        correctChoiceId: 'alliteration',
        options: [
          choice('idiom', 'idiom'),
          choice('alliteration', 'alliteration'),
          choice('simile', 'simile'),
        ],
      },
      {
        id: 'r4',
        prompt: 'keep an eye on',
        correctChoiceId: 'idiom',
        options: [
          choice('simile', 'simile'),
          choice('idiom', 'idiom'),
          choice('alliteration', 'alliteration'),
        ],
      },
    ],
  }),
] as const

export const wordplayWatchtowerPrerequisiteLessonQuestions = {
  prereqSpotTheComparison: wordplayWatchtowerPrerequisiteQuestions.slice(0, 5),
  prereqMeaningBeyondWords: wordplayWatchtowerPrerequisiteQuestions.slice(5, 10),
} as const
