import type { ContentSample } from './types'

export const sampleContent: ContentSample = {
  passages: [
    {
      passageIdentifier: 'passage-word-forge-bridge-a',
      gradeBand: 2,
      passageText:
        'Nora packed her small kite bag, tied the string around her wrist, and checked the wind before walking outside. '
        + 'She asked her brother to hold the spool and to call out each count slowly. '
        + 'On the first jump, the kite dipped low, then lifted high and stayed steady in the sky.',
      readingContext: 'Short sentence set for short-vowel decoding.',
      contentVersion: 'r0.1.0',
    },
    {
      passageIdentifier: 'passage-word-forge-bridge-b',
      gradeBand: 2,
      passageText:
        'After school, Nora and Maya planted seeds in three little cups. '
        + 'Nora measured one cup of soil and then one cup of water for each. '
        + 'She covered each cup with earth and smiled when each cup had a tiny label saying Day 1, Day 2, and Day 3.',
      readingContext: 'Short sentence set for multisyllabic pattern review.',
      contentVersion: 'r0.1.0',
    },
  ],
  questions: [
    {
      gradeBand: 2,
      benchmarkReference: 'RR-G2-WF-01',
      skillIdentifier: 'g2-word-forge-word-practice',
      prerequisiteSkillIdentifiers: [],
      reportingCategory: 'Word Forge',
      genre: 'sentence',
      difficulty: 1,
      passageIdentifier: 'passage-word-forge-bridge-a',
      lessonIdentifier: 'lesson-word-forge-vowel-voyage',
      activityIdentifier: 'act-word-forge-vowel-voyage-a-1',
      questionIdentifier: 'q-word-forge-vowel-voyage-a-1',
      questionType: 'multiple_choice',
      prompt: 'Which action shows planning before flight?',
      answerChoices: ['step-pack', 'step-jump', 'step-slow', 'step-call'],
      correctAnswers: ['step-pack'],
      explanation:
        'She packed her kite bag and checked the wind before she went outside, which shows planning.',
      evidenceReference: 'evidence-passages',
      evidenceReferenceIds: ['step-pack'],
      targetVocabulary: ['pack', 'wind', 'check'],
      soundOutChunks: ['c', 'a', 't'],
      estimatedReadingLevel: 'grade-2-placeholder',
      reviewStatus: 'DRAFT',
      contentVersion: 'r0.1.0',
      tags: ['bridge', 'multiple-choice', 'g2'],
      questionContent: {
        type: 'multiple_choice',
        choices: [
          { id: 'step-pack', text: 'Packing her kite bag and checking the wind' },
          { id: 'step-jump', text: 'Jumping twice into the air' },
          { id: 'step-slow', text: 'Holding the spool too tightly' },
          { id: 'step-call', text: 'Waving to her brother' },
        ],
        correctChoiceIds: ['step-pack'],
      },
    },
    {
      gradeBand: 2,
      benchmarkReference: 'RR-G2-WF-01',
      skillIdentifier: 'g2-word-forge-word-practice',
      prerequisiteSkillIdentifiers: [],
      reportingCategory: 'Word Forge',
      genre: 'sentence',
      difficulty: 1,
      passageIdentifier: 'passage-word-forge-bridge-a',
      lessonIdentifier: 'lesson-word-forge-vowel-voyage',
      activityIdentifier: 'act-word-forge-vowel-voyage-a-2',
      questionIdentifier: 'q-word-forge-vowel-voyage-a-2',
      questionType: 'multiple_choice',
      prompt: 'Which choice best shows a sentence about keeping the kite steady?',
      answerChoices: ['choice-wind', 'choice-soft', 'choice-run', 'choice-pack'],
      correctAnswers: ['choice-wind'],
      explanation: 'She checked the wind before using the kite and then kept the launch steady.',
      evidenceReference: 'evidence-passages',
      evidenceReferenceIds: ['choice-wind'],
      targetVocabulary: ['wind', 'steady'],
      soundOutChunks: ['r', 'o', 'll'],
      estimatedReadingLevel: 'grade-2-placeholder',
      reviewStatus: 'DRAFT',
      contentVersion: 'r0.1.0',
      tags: ['bridge', 'multiple-choice', 'g2'],
      questionContent: {
        type: 'multiple_choice',
        choices: [
          { id: 'choice-wind', text: 'Checking the wind and then stepping outside' },
          { id: 'choice-soft', text: 'Holding the spool too hard' },
          { id: 'choice-run', text: 'Running across the yard' },
          { id: 'choice-pack', text: 'Skipping the checks' },
        ],
        correctChoiceIds: ['choice-wind'],
      },
    },
    {
      gradeBand: 2,
      benchmarkReference: 'RR-G2-WF-01',
      skillIdentifier: 'g2-word-forge-word-practice',
      prerequisiteSkillIdentifiers: [],
      reportingCategory: 'Word Forge',
      genre: 'sentence',
      difficulty: 1,
      passageIdentifier: 'passage-word-forge-bridge-a',
      lessonIdentifier: 'lesson-word-forge-vowel-voyage',
      activityIdentifier: 'act-word-forge-vowel-voyage-a-3',
      questionIdentifier: 'q-word-forge-vowel-voyage-a-3',
      questionType: 'multi_select',
      prompt: 'Choose all the clues that show teamwork.',
      answerChoices: ['clue-brother', 'clue-count', 'clue-sky', 'clue-laugh'],
      correctAnswers: ['clue-brother', 'clue-count'],
      explanation: 'Nora works with her brother and asks him to count out loud together.',
      evidenceReference: 'evidence-passages',
      evidenceReferenceIds: ['clue-brother', 'clue-count'],
      targetVocabulary: ['brother', 'count'],
      soundOutChunks: ['p', 'l', 'a', 'n'],
      estimatedReadingLevel: 'grade-2-placeholder',
      reviewStatus: 'DRAFT',
      contentVersion: 'r0.1.0',
      tags: ['bridge', 'multiselect', 'g2'],
      questionContent: {
        type: 'multi_select',
        choices: [
          { id: 'clue-brother', text: 'She asked her brother to hold the spool.' },
          { id: 'clue-count', text: 'He called out each number slowly.' },
          { id: 'clue-sky', text: 'The sky looked blue in the first line.' },
          { id: 'clue-laugh', text: 'Nora smiled and laughed.' },
        ],
        correctChoiceIds: ['clue-brother', 'clue-count'],
      },
    },
    {
      gradeBand: 2,
      benchmarkReference: 'RR-G2-WF-01',
      skillIdentifier: 'g2-word-forge-word-practice',
      prerequisiteSkillIdentifiers: [],
      reportingCategory: 'Word Forge',
      genre: 'sentence',
      difficulty: 0,
      passageIdentifier: 'passage-word-forge-bridge-b',
      lessonIdentifier: 'lesson-word-forge-vowel-voyage',
      activityIdentifier: 'act-word-forge-vowel-voyage-b-1',
      questionIdentifier: 'q-word-forge-vowel-voyage-b-1',
      questionType: 'hot_text',
      prompt: 'Select the sentence that shows careful seed care.',
      answerChoices: [],
      correctAnswers: [],
      explanation:
        'Nora measured soil and water and then covered each cup, which is careful seed care.',
      evidenceReference: 'evidence-passages',
      evidenceReferenceIds: ['seed-2', 'seed-3'],
      targetVocabulary: ['soil', 'water'],
      soundOutChunks: [],
      estimatedReadingLevel: 'grade-2-placeholder',
      reviewStatus: 'DRAFT',
      contentVersion: 'r0.1.0',
      tags: ['bridge', 'hot-text', 'g2'],
      questionContent: {
        type: 'hot_text',
        selectableSegments: [
          {
            id: 'seed-1',
            text: 'After school, Nora and Maya planted seeds in three little cups.',
          },
          {
            id: 'seed-2',
            text: 'Nora measured one cup of soil and then one cup of water for each.',
          },
          {
            id: 'seed-3',
            text: 'She covered each cup with earth and smiled when each cup had a tiny label.',
          },
        ],
        correctSegmentIds: ['seed-2', 'seed-3'],
      },
    },
    {
      gradeBand: 2,
      benchmarkReference: 'RR-G2-WF-01',
      skillIdentifier: 'g2-word-forge-word-practice',
      prerequisiteSkillIdentifiers: [],
      reportingCategory: 'Word Forge',
      genre: 'sentence',
      difficulty: 1,
      passageIdentifier: 'passage-word-forge-bridge-b',
      lessonIdentifier: 'lesson-word-forge-vowel-voyage',
      activityIdentifier: 'act-word-forge-vowel-voyage-b-2',
      questionIdentifier: 'q-word-forge-vowel-voyage-b-2',
      questionType: 'hot_text',
      prompt: 'Select all details about the growth labels.',
      answerChoices: [],
      correctAnswers: [],
      explanation:
        'Nora labeled each cup with Day 1, Day 2, and Day 3 to keep labels for comparison.',
      evidenceReference: 'evidence-passages',
      evidenceReferenceIds: ['seed-6', 'seed-7'],
      targetVocabulary: ['label', 'day'],
      soundOutChunks: [],
      estimatedReadingLevel: 'grade-2-placeholder',
      reviewStatus: 'DRAFT',
      contentVersion: 'r0.1.0',
      tags: ['bridge', 'hot-text', 'g2'],
      questionContent: {
        type: 'hot_text',
        selectableSegments: [
          {
            id: 'seed-4',
            text: 'Nora and Maya planted seeds in three little cups.',
          },
          {
            id: 'seed-5',
            text: 'Nora measured one cup of soil and then one cup of water for each.',
          },
          {
            id: 'seed-6',
            text: 'She covered each cup with earth and smiled when each cup had a tiny label.',
          },
          {
            id: 'seed-7',
            text: 'She wrote Day 1, Day 2, and Day 3 on the labels.',
          },
        ],
        correctSegmentIds: ['seed-6', 'seed-7'],
      },
    },
    {
      gradeBand: 2,
      benchmarkReference: 'RR-G2-WF-01',
      skillIdentifier: 'g2-word-forge-word-practice',
      prerequisiteSkillIdentifiers: [],
      reportingCategory: 'Word Forge',
      genre: 'sentence',
      difficulty: 1,
      passageIdentifier: 'passage-word-forge-bridge-a',
      lessonIdentifier: 'lesson-word-forge-vowel-voyage',
      activityIdentifier: 'act-word-forge-vowel-voyage-a-4',
      questionIdentifier: 'q-word-forge-vowel-voyage-a-4',
      questionType: 'two_part',
      prompt: 'Choose what Nora was trying to practice and the supporting sentence.',
      answerChoices: [],
      correctAnswers: [],
      explanation:
        'She practiced keeping the kite controlled, and the sentence about calling numbers slowly supports that teamwork.',
      evidenceReference: 'evidence-passages',
      evidenceReferenceIds: ['lesson-A'],
      targetVocabulary: ['count', 'steady'],
      soundOutChunks: ['j', 'u', 'm'],
      estimatedReadingLevel: 'grade-2-placeholder',
      reviewStatus: 'DRAFT',
      contentVersion: 'r0.1.0',
      tags: ['bridge', 'evidence', 'g2'],
      questionContent: {
        type: 'two_part',
        partAPrompt: 'What was the main lesson in this scene?',
        partAChoices: [
          { id: 'lesson-A', text: 'Work safely with a team.' },
          { id: 'lesson-B', text: 'Ignore the wind checks.' },
        ],
        partACorrectChoiceId: 'lesson-A',
        partBPrompt: 'Which sentence best supports that lesson?',
        partBChoices: [
          { id: 'seg-a1', text: 'Nora packed her small kite bag, tied the string around her wrist, and checked the wind.' },
          { id: 'seg-a2', text: 'She asked her brother to hold the spool and to call out each count slowly.' },
          { id: 'seg-a3', text: 'On the first jump, the kite dipped low, then lifted high and stayed steady in the sky.' },
        ],
        partBCorrectChoiceId: 'seg-a2',
      },
    },
    {
      gradeBand: 2,
      benchmarkReference: 'RR-G2-WF-01',
      skillIdentifier: 'g2-word-forge-word-practice',
      prerequisiteSkillIdentifiers: [],
      reportingCategory: 'Word Forge',
      genre: 'sentence',
      difficulty: 1,
      passageIdentifier: 'passage-word-forge-bridge-b',
      lessonIdentifier: 'lesson-word-forge-vowel-voyage',
      activityIdentifier: 'act-word-forge-vowel-voyage-b-4',
      questionIdentifier: 'q-word-forge-vowel-voyage-b-4',
      questionType: 'table_match',
      prompt: 'Match each learner action to the science habit.',
      answerChoices: [],
      correctAnswers: [],
      explanation:
        'Labeling each cup and measuring carefully are planning habits; covering with earth helps protect growth.',
      evidenceReference: 'evidence-passages',
      evidenceReferenceIds: ['habit-planned', 'habit-tracked', 'habit-safe'],
      targetVocabulary: ['measure', 'cover'],
      soundOutChunks: [],
      estimatedReadingLevel: 'grade-2-placeholder',
      reviewStatus: 'DRAFT',
      contentVersion: 'r0.1.0',
      tags: ['bridge', 'table-match', 'g2'],
      questionContent: {
        type: 'table_match',
        rows: [
          {
            id: 'row-1',
            prompt: 'Measured cups for each seed',
            correctChoiceId: 'habit-planned',
            options: [
              { id: 'habit-planned', text: 'Planned and measured carefully' },
              { id: 'habit-observed', text: 'Observed changes and reacted' },
              { id: 'habit-random', text: 'Acted without a plan' },
            ],
          },
          {
            id: 'row-2',
            prompt: 'Wrote tiny labels for each cup',
            correctChoiceId: 'habit-tracked',
            options: [
              { id: 'habit-tracked', text: 'Tracked each trial clearly' },
              { id: 'habit-skipped', text: 'Skipped checks' },
              { id: 'habit-forgot', text: 'Forgot details' },
            ],
          },
          {
            id: 'row-3',
            prompt: 'Covered cups with earth',
            correctChoiceId: 'habit-safe',
            options: [
              { id: 'habit-safe', text: 'Protected each seed' },
              { id: 'habit-rush', text: 'Rushed setup' },
              { id: 'habit-hastily', text: 'Ignored safety details' },
            ],
          },
        ],
      },
    },
    {
      gradeBand: 2,
      benchmarkReference: 'RR-G2-WF-01',
      skillIdentifier: 'g2-word-forge-word-practice',
      prerequisiteSkillIdentifiers: [],
      reportingCategory: 'Word Forge',
      genre: 'sentence',
      difficulty: 1,
      passageIdentifier: 'passage-word-forge-bridge-b',
      lessonIdentifier: 'lesson-word-forge-vowel-voyage',
      activityIdentifier: 'act-word-forge-vowel-voyage-b-5',
      questionIdentifier: 'q-word-forge-vowel-voyage-b-5',
      questionType: 'multi_select',
      prompt: 'Choose all details that show Nora compared progress safely.',
      answerChoices: ['evidence-order', 'evidence-label', 'evidence-speed', 'evidence-soil'],
      correctAnswers: ['evidence-order', 'evidence-label'],
      explanation:
        'Day labels and careful sequence of steps keep progress safe and easy to compare.',
      evidenceReference: 'evidence-passages',
      evidenceReferenceIds: ['evidence-order', 'evidence-label'],
      targetVocabulary: ['sequence', 'label'],
      soundOutChunks: ['m', 'o', 'n'],
      estimatedReadingLevel: 'grade-2-placeholder',
      reviewStatus: 'DRAFT',
      contentVersion: 'r0.1.0',
      tags: ['bridge', 'multiselect', 'g2'],
      questionContent: {
        type: 'multi_select',
        choices: [
          { id: 'evidence-order', text: 'She planted three cups, not one.' },
          { id: 'evidence-label', text: 'She wrote Day 1, Day 2, and Day 3.' },
          { id: 'evidence-speed', text: 'She ran quickly to class.' },
          { id: 'evidence-soil', text: 'She measured water and soil.' },
        ],
        correctChoiceIds: ['evidence-order', 'evidence-label'],
      },
    },
    {
      gradeBand: 2,
      benchmarkReference: 'RR-G2-WF-01',
      skillIdentifier: 'g2-word-forge-word-practice',
      prerequisiteSkillIdentifiers: [],
      reportingCategory: 'Word Forge',
      genre: 'sentence',
      difficulty: 1,
      passageIdentifier: 'passage-word-forge-bridge-a',
      lessonIdentifier: 'lesson-word-forge-vowel-voyage',
      activityIdentifier: 'act-word-forge-vowel-voyage-a-5',
      questionIdentifier: 'q-word-forge-vowel-voyage-a-5',
      questionType: 'multiple_choice',
      prompt: 'What happened to the kite after the first jump?',
      answerChoices: ['jump-high', 'jump-dipped', 'jump-broke', 'jump-lost'],
      correctAnswers: ['jump-dipped'],
      explanation: 'The passage says the kite dipped low, then lifted high and stayed steady.',
      evidenceReference: 'evidence-passages',
      evidenceReferenceIds: ['jump-dipped'],
      targetVocabulary: ['dip', 'steady'],
      soundOutChunks: ['j', 'u', 'm'],
      estimatedReadingLevel: 'grade-2-placeholder',
      reviewStatus: 'DRAFT',
      contentVersion: 'r0.1.0',
      tags: ['bridge', 'vowel', 'pattern', 'g2'],
      questionContent: {
        type: 'multiple_choice',
        choices: [
          { id: 'jump-high', text: 'The kite lifted high right away and fell.' },
          { id: 'jump-dipped', text: 'The kite dipped first, then lifted high and stayed steady.' },
          { id: 'jump-broke', text: 'The kite broke into two pieces.' },
          { id: 'jump-lost', text: 'The kite disappeared instantly.' },
        ],
        correctChoiceIds: ['jump-dipped'],
      },
    },
    {
      gradeBand: 2,
      benchmarkReference: 'RR-G2-WF-01',
      skillIdentifier: 'g2-word-forge-word-practice',
      prerequisiteSkillIdentifiers: [],
      reportingCategory: 'Word Forge',
      genre: 'sentence',
      difficulty: 1,
      passageIdentifier: 'passage-word-forge-bridge-a',
      lessonIdentifier: 'lesson-word-forge-vowel-voyage',
      activityIdentifier: 'act-word-forge-vowel-voyage-a-6',
      questionIdentifier: 'q-word-forge-vowel-voyage-a-6',
      questionType: 'two_part',
      prompt: 'Choose a lesson and proof from the passage.',
      answerChoices: [],
      correctAnswers: [],
      explanation:
        'Nora prepared and then flew with her brother as a team; the line about asking her brother for counts proves it.',
      evidenceReference: 'evidence-passages',
      evidenceReferenceIds: ['team-plan'],
      targetVocabulary: ['team', 'proof'],
      soundOutChunks: ['t', 'e', 'a', 'm'],
      estimatedReadingLevel: 'grade-2-placeholder',
      reviewStatus: 'DRAFT',
      contentVersion: 'r0.1.0',
      tags: ['bridge', 'evidence', 'g2'],
      questionContent: {
        type: 'two_part',
        partAPrompt: 'What did the team do together?',
        partAChoices: [
          { id: 'team-plan', text: 'Plan the launch and count the steps together.' },
          { id: 'team-alone', text: 'Work only one at a time.' },
        ],
        partACorrectChoiceId: 'team-plan',
        partBPrompt: 'Where is the clearest evidence of that teamwork?',
        partBChoices: [
          { id: 'seed-4', text: 'She and Maya planted seeds in three little cups.' },
          { id: 'seg-a2', text: 'She asked her brother to hold the spool and call out each count slowly.' },
          { id: 'seg-a3', text: 'On the first jump, the kite dipped low, then lifted high and stayed steady in the sky.' },
        ],
        partBCorrectChoiceId: 'seg-a2',
      },
    },
  ],
}
