import type { ContentSample } from './types'

export const sampleContent: ContentSample = {
  passages: [
    {
      passageIdentifier: 'passage-word-forge-bridge-a',
      gradeBand: 2,
      passageText:
        'The tiny cat sat on the mat and tapped at the window.',
      readingContext: 'Short sentence set for short-vowel decoding.',
      contentVersion: 'r0.1.0',
    },
    {
      passageIdentifier: 'passage-word-forge-bridge-b',
      gradeBand: 2,
      passageText:
        'The rover rolled over the red rug by the barn.',
      readingContext: 'Short sentence set for multisyllabic pattern review.',
      contentVersion: 'r0.1.0',
    },
    {
      passageIdentifier: 'passage-word-forge-bridge-c',
      gradeBand: 2,
      passageText:
        'Nina made a tiny map to track her class robot path.',
      readingContext: 'Short text for vowel-pattern practice.',
      contentVersion: 'r0.1.0',
    },
  ],
  questions: [
    {
      gradeBand: 2,
      benchmarkReference: 'RR-G2-WF-01',
      skillIdentifier: 'g2-word-forge-vowel-patterns',
      prerequisiteSkillIdentifiers: ['g2-word-forge-phoneme-readiness'],
      reportingCategory: 'Word Forge',
      genre: 'sentence',
      difficulty: 1,
      passageIdentifier: 'passage-word-forge-bridge-a',
      activityIdentifier: 'act-word-forge-bridge-a-1',
      questionIdentifier: 'q-word-forge-bridge-a-1',
      questionType: 'multiple_choice',
      prompt: 'Choose the word with the same short "a" sound as "cat".',
      answerChoices: ['man', 'cat', 'moon', 'dog'],
      correctAnswers: ['cat'],
      explanation: 'Both words use the short a sound.',
      evidenceReference: 'target sound pattern in sentence',
      targetVocabulary: ['cat', 'man'],
      soundOutChunks: ['c', 'a', 't'],
      estimatedReadingLevel: 'grade-2-placeholder',
      reviewStatus: 'DRAFT',
      contentVersion: 'r0.1.0',
      tags: ['bridge', 'vowel', 'pattern', 'g2'],
    },
    {
      gradeBand: 2,
      benchmarkReference: 'RR-G2-WF-01',
      skillIdentifier: 'g2-word-forge-vowel-patterns',
      prerequisiteSkillIdentifiers: ['g2-word-forge-phoneme-readiness'],
      reportingCategory: 'Word Forge',
      genre: 'sentence',
      difficulty: 1,
      passageIdentifier: 'passage-word-forge-bridge-b',
      activityIdentifier: 'act-word-forge-bridge-b-1',
      questionIdentifier: 'q-word-forge-bridge-b-1',
      questionType: 'multiple_choice',
      prompt: 'Pick the word that matches the short "o" pattern.',
      answerChoices: ['roll', 'robe', 'blue', 'time'],
      correctAnswers: ['roll'],
      explanation: 'The word "roll" has the short o vowel sound.',
      evidenceReference: 'word pattern focus',
      targetVocabulary: ['roll', 'rover'],
      soundOutChunks: ['r', 'o', 'll'],
      estimatedReadingLevel: 'grade-2-placeholder',
      reviewStatus: 'DRAFT',
      contentVersion: 'r0.1.0',
      tags: ['bridge', 'vowel', 'pattern', 'g2'],
    },
    {
      gradeBand: 2,
      benchmarkReference: 'RR-G2-WF-01',
      skillIdentifier: 'g2-word-forge-vowel-patterns',
      prerequisiteSkillIdentifiers: ['g2-word-forge-phoneme-readiness'],
      reportingCategory: 'Word Forge',
      genre: 'sentence',
      difficulty: 1,
      passageIdentifier: 'passage-word-forge-bridge-c',
      activityIdentifier: 'act-word-forge-bridge-c-1',
      questionIdentifier: 'q-word-forge-bridge-c-1',
      questionType: 'multiple_choice',
      prompt: 'Choose the word with the short "i" pattern.',
      answerChoices: ['nail', 'bike', 'pin', 'line'],
      correctAnswers: ['pin'],
      explanation: 'The word "pin" uses a short i sound.',
      evidenceReference: 'sound decoding target',
      targetVocabulary: ['pin', 'nina'],
      soundOutChunks: ['p', 'i', 'n'],
      estimatedReadingLevel: 'grade-2-placeholder',
      reviewStatus: 'DRAFT',
      contentVersion: 'r0.1.0',
      tags: ['bridge', 'vowel', 'pattern', 'g2'],
    },
    {
      gradeBand: 2,
      benchmarkReference: 'RR-G2-WF-00',
      skillIdentifier: 'g2-word-forge-phoneme-readiness',
      prerequisiteSkillIdentifiers: [],
      reportingCategory: 'Word Forge',
      genre: 'sentence',
      difficulty: 0,
      passageIdentifier: 'passage-word-forge-bridge-a',
      activityIdentifier: 'act-word-forge-prereq-readiness-1',
      questionIdentifier: 'q-word-forge-prereq-readiness-1',
      questionType: 'multiple_choice',
      prompt: 'Pick the word that starts with /m/.',
      answerChoices: ['cat', 'moon', 'mat', 'top'],
      correctAnswers: ['mat'],
      explanation: 'The starting sound /m/ is in "mat".',
      evidenceReference: 'phoneme readiness',
      targetVocabulary: ['cat', 'mat'],
      soundOutChunks: ['m', 'a', 't'],
      estimatedReadingLevel: 'grade-2-placeholder',
      reviewStatus: 'DRAFT',
      contentVersion: 'r0.1.0',
      tags: ['bridge', 'phoneme', 'g2'],
    },
  ],
}
