import type { ContentPackLesson, ContentPackManifest } from '../../../contentPackTypes'
import {
  COMPARE_KEEP_BENCHMARK,
  COMPARE_KEEP_CONTENT_VERSION,
  COMPARE_KEEP_LESSON_IDS,
  COMPARE_KEEP_PACK_ID,
  COMPARE_KEEP_PACK_TITLE,
  COMPARE_KEEP_PAIR_IDS,
  COMPARE_KEEP_PASSAGE_IDS,
  COMPARE_KEEP_PRIMARY_SKILL_ID,
  COMPARE_KEEP_QUESTION_IDS,
  COMPARE_KEEP_WORLD_ID,
  COMPARE_KEEP_UNIT_ID,
} from './ids'

const buildTeachingBlock = (
  title: string,
  explanation: string,
  examples: string[],
  contrast: string,
  learnerCue: string,
) => ({
  title,
  explanation,
  examples,
  contrast,
  learnerCue,
})

export const compareKeepManifest: ContentPackManifest = {
  packId: COMPARE_KEEP_PACK_ID,
  packTitle: COMPARE_KEEP_PACK_TITLE,
  gradeBand: 2,
  worldId: COMPARE_KEEP_WORLD_ID,
  unitId: COMPARE_KEEP_UNIT_ID,
  primarySkillId: COMPARE_KEEP_PRIMARY_SKILL_ID,
  benchmarkReferences: [COMPARE_KEEP_BENCHMARK],
  coverageKind: 'benchmark',
  partialBenchmarkCoverage: 'structured authored selected-response compare and contrast for two texts',
  difficultyRange: [2, 3],
  contentVersion: COMPARE_KEEP_CONTENT_VERSION,
  reviewStatus: 'DRAFT',
  coveredPatterns: [
    'compare-contrast-important-details',
    'same-topic-or-theme',
    'paired-text-reading',
    'text-1-text-2-evidence',
    'important-detail-identification',
    'important-vs-minor-detail',
    'similarity-identification',
    'difference-identification',
    'comparison-evidence',
    'same-topic-pair',
    'same-theme-pair',
    'same-format-pair',
    'different-format-pair',
    'literary-character-comparison',
    'literary-setting-comparison',
    'literary-event-sequence-comparison',
    'informational-central-idea-comparison',
    'informational-detail-comparison',
    'informational-process-comparison',
    'structured-compare-contrast',
  ],
  passageIds: [
    COMPARE_KEEP_PASSAGE_IDS.literaryProseA,
    COMPARE_KEEP_PASSAGE_IDS.literaryProseB,
    COMPARE_KEEP_PASSAGE_IDS.literaryProseC,
    COMPARE_KEEP_PASSAGE_IDS.literaryProseD,
    COMPARE_KEEP_PASSAGE_IDS.literaryProseE,
    COMPARE_KEEP_PASSAGE_IDS.literaryProseF,
    COMPARE_KEEP_PASSAGE_IDS.literaryPoemA,
    COMPARE_KEEP_PASSAGE_IDS.literaryPoemB,
    COMPARE_KEEP_PASSAGE_IDS.informationalA,
    COMPARE_KEEP_PASSAGE_IDS.informationalB,
    COMPARE_KEEP_PASSAGE_IDS.informationalC,
    COMPARE_KEEP_PASSAGE_IDS.informationalD,
    COMPARE_KEEP_PASSAGE_IDS.informationalE,
    COMPARE_KEEP_PASSAGE_IDS.informationalF,
  ],
  questionIds: [
    ...COMPARE_KEEP_QUESTION_IDS.prereqFindWhatBothTextsShare,
    ...COMPARE_KEEP_QUESTION_IDS.prereqFindWhatEachTextAdds,
    ...COMPARE_KEEP_QUESTION_IDS.guidedCompareCharactersAndEvents,
    ...COMPARE_KEEP_QUESTION_IDS.guidedCompareImportantFacts,
    ...COMPARE_KEEP_QUESTION_IDS.checkpointLiteraryA,
    ...COMPARE_KEEP_QUESTION_IDS.checkpointInformational,
    ...COMPARE_KEEP_QUESTION_IDS.checkpointLiteraryB,
  ],
  lessonIds: [...Object.values(COMPARE_KEEP_LESSON_IDS)],
}

export const compareKeepLessons: ContentPackLesson[] = [
  {
    lessonId: COMPARE_KEEP_LESSON_IDS.prereqFindWhatBothTextsShare,
    worldId: COMPARE_KEEP_WORLD_ID,
    unitId: COMPARE_KEEP_UNIT_ID,
    activityId: 'activity-compare-castle-compare-keep-prereq-find-what-both-texts-share',
    difficulty: 2,
    passageIdentifiers: [
      COMPARE_KEEP_PASSAGE_IDS.literaryProseA,
      COMPARE_KEEP_PASSAGE_IDS.literaryProseB,
    ],
    pairedTextSetId: COMPARE_KEEP_PAIR_IDS.literaryProseA,
    questionIdentifiers: [...COMPARE_KEEP_QUESTION_IDS.prereqFindWhatBothTextsShare],
    lessonTitle: 'Find What Both Texts Share',
    lessonObjective: 'Read two literary texts and name the important ways they are alike.',
    lessonRole: 'GUIDED_PRACTICE',
    selectionStatus: 'active',
    teachingBlock: buildTeachingBlock(
      'Read Both Texts',
      'Compare Keep lessons ask learners to read two texts and look for one important similarity and one important difference.',
      ['two helpers work carefully', 'a ready space at the end', 'a calm plan that solves a problem'],
      'A minor detail does not make the best comparison.',
      'Find the detail that helps explain both texts best.',
    ),
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    eligiblePurposes: ['remediation', 'review'],
  },
  {
    lessonId: COMPARE_KEEP_LESSON_IDS.prereqFindWhatEachTextAdds,
    worldId: COMPARE_KEEP_WORLD_ID,
    unitId: COMPARE_KEEP_UNIT_ID,
    activityId: 'activity-compare-castle-compare-keep-prereq-find-what-each-text-adds',
    difficulty: 2,
    passageIdentifiers: [
      COMPARE_KEEP_PASSAGE_IDS.informationalA,
      COMPARE_KEEP_PASSAGE_IDS.informationalB,
    ],
    pairedTextSetId: COMPARE_KEEP_PAIR_IDS.informationalA,
    questionIdentifiers: [...COMPARE_KEEP_QUESTION_IDS.prereqFindWhatEachTextAdds],
    lessonTitle: 'Find What Each Text Adds',
    lessonObjective: 'Read two informational texts and notice what each text adds to the topic.',
    lessonRole: 'GUIDED_PRACTICE',
    selectionStatus: 'active',
    teachingBlock: buildTeachingBlock(
      'Look for Useful Facts',
      'Informational comparison asks learners to find the central idea and the details that matter most for the topic.',
      ['seeds travel in more than one way', 'wind and water move seeds', 'fresh soil helps plants spread'],
      'A true detail can still be less important than the central idea.',
      'Choose the detail that best explains the topic.',
    ),
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    eligiblePurposes: ['remediation', 'review'],
  },
  {
    lessonId: COMPARE_KEEP_LESSON_IDS.guidedCompareCharactersAndEvents,
    worldId: COMPARE_KEEP_WORLD_ID,
    unitId: COMPARE_KEEP_UNIT_ID,
    activityId: 'activity-compare-castle-compare-keep-guided-compare-characters-and-events',
    difficulty: 3,
    passageIdentifiers: [
      COMPARE_KEEP_PASSAGE_IDS.literaryProseC,
      COMPARE_KEEP_PASSAGE_IDS.literaryPoemA,
    ],
    pairedTextSetId: COMPARE_KEEP_PAIR_IDS.literaryPoemA,
    questionIdentifiers: [...COMPARE_KEEP_QUESTION_IDS.guidedCompareCharactersAndEvents],
    lessonTitle: 'Compare Characters and Events',
    lessonObjective: 'Compare a story and a poem by looking at the characters and the event sequence.',
    lessonRole: 'GUIDED_PRACTICE',
    selectionStatus: 'active',
    teachingBlock: buildTeachingBlock(
      'Compare the Wind Texts',
      'A comparison can show how two texts share a theme while using different formats.',
      ['a kite rises in the wind', 'the leaves move in the breeze', 'the ending stays calm'],
      'The poem may describe the same idea without using a story structure.',
      'Read both texts and match the important details.',
    ),
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    eligiblePurposes: ['remediation', 'review'],
  },
  {
    lessonId: COMPARE_KEEP_LESSON_IDS.guidedCompareImportantFacts,
    worldId: COMPARE_KEEP_WORLD_ID,
    unitId: COMPARE_KEEP_UNIT_ID,
    activityId: 'activity-compare-castle-compare-keep-guided-compare-important-facts',
    difficulty: 3,
    passageIdentifiers: [
      COMPARE_KEEP_PASSAGE_IDS.informationalC,
      COMPARE_KEEP_PASSAGE_IDS.informationalD,
    ],
    pairedTextSetId: COMPARE_KEEP_PAIR_IDS.informationalB,
    questionIdentifiers: [...COMPARE_KEEP_QUESTION_IDS.guidedCompareImportantFacts],
    lessonTitle: 'Compare Important Facts',
    lessonObjective: 'Compare two informational texts by noticing important facts and the process each one explains.',
    lessonRole: 'GUIDED_PRACTICE',
    selectionStatus: 'active',
    teachingBlock: buildTeachingBlock(
      'Sort the Facts',
      'The best comparison details explain the central idea, the process, or another important fact.',
      ['rain gauges measure rain', 'weather shelters protect tools', 'students compare observations'],
      'A less important detail should not take the main comparison spot.',
      'Choose the fact that helps the reader learn the topic.',
    ),
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    eligiblePurposes: ['remediation', 'review'],
  },
  {
    lessonId: COMPARE_KEEP_LESSON_IDS.checkpointLiteraryA,
    worldId: COMPARE_KEEP_WORLD_ID,
    unitId: COMPARE_KEEP_UNIT_ID,
    activityId: 'activity-compare-castle-compare-keep-checkpoint-literary-a',
    difficulty: 3,
    passageIdentifiers: [
      COMPARE_KEEP_PASSAGE_IDS.literaryProseD,
      COMPARE_KEEP_PASSAGE_IDS.literaryProseE,
    ],
    pairedTextSetId: COMPARE_KEEP_PAIR_IDS.literaryProseB,
    questionIdentifiers: [...COMPARE_KEEP_QUESTION_IDS.checkpointLiteraryA],
    lessonTitle: 'Literary Same-Theme Checkpoint',
    lessonObjective: 'Compare two prose texts by identifying the important character, event, and ending details.',
    lessonRole: 'CHECKPOINT',
    selectionStatus: 'active',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    eligiblePurposes: ['progression', 'verification', 'review'],
  },
  {
    lessonId: COMPARE_KEEP_LESSON_IDS.checkpointInformational,
    worldId: COMPARE_KEEP_WORLD_ID,
    unitId: COMPARE_KEEP_UNIT_ID,
    activityId: 'activity-compare-castle-compare-keep-checkpoint-informational',
    difficulty: 3,
    passageIdentifiers: [
      COMPARE_KEEP_PASSAGE_IDS.informationalE,
      COMPARE_KEEP_PASSAGE_IDS.informationalF,
    ],
    pairedTextSetId: COMPARE_KEEP_PAIR_IDS.informationalC,
    questionIdentifiers: [...COMPARE_KEEP_QUESTION_IDS.checkpointInformational],
    lessonTitle: 'Informational Same-Topic Checkpoint',
    lessonObjective: 'Compare two informational texts by using central idea, facts, and process details.',
    lessonRole: 'CHECKPOINT',
    selectionStatus: 'active',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    eligiblePurposes: ['progression', 'verification', 'review'],
  },
  {
    lessonId: COMPARE_KEEP_LESSON_IDS.checkpointLiteraryB,
    worldId: COMPARE_KEEP_WORLD_ID,
    unitId: COMPARE_KEEP_UNIT_ID,
    activityId: 'activity-compare-castle-compare-keep-checkpoint-literary-b',
    difficulty: 3,
    passageIdentifiers: [
      COMPARE_KEEP_PASSAGE_IDS.literaryProseF,
      COMPARE_KEEP_PASSAGE_IDS.literaryPoemB,
    ],
    pairedTextSetId: COMPARE_KEEP_PAIR_IDS.literaryPoemB,
    questionIdentifiers: [...COMPARE_KEEP_QUESTION_IDS.checkpointLiteraryB],
    lessonTitle: 'Literary Same-Theme Checkpoint',
    lessonObjective: 'Compare a prose story and a poem by finding important similarities and differences.',
    lessonRole: 'CHECKPOINT',
    selectionStatus: 'active',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    eligiblePurposes: ['progression', 'verification', 'review'],
  },
]
