import type { ReadingQuestion } from '../../../../types'
import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from './questionFactories'
import { createScopedEvidenceReference } from '../../../../evidence'
import {
  COMPARE_KEEP_BENCHMARK,
  COMPARE_KEEP_CONTENT_VERSION,
  COMPARE_KEEP_LESSON_IDS,
  COMPARE_KEEP_PASSAGE_IDS,
  COMPARE_KEEP_QUESTION_IDS,
} from './ids'

const reportingCategory = 'Reading Across Genres and Vocabulary'
const skillIdentifier = 'g2-across-genres-reading'
const genre = 'paired_text'

function choice(id: string, text: string) {
  return { id, text }
}

const proseWind = COMPARE_KEEP_PASSAGE_IDS.literaryProseC
const poemWind = COMPARE_KEEP_PASSAGE_IDS.literaryPoemA
const rain1 = COMPARE_KEEP_PASSAGE_IDS.informationalC
const rain2 = COMPARE_KEEP_PASSAGE_IDS.informationalD

export const compareKeepGuidedQuestions: ReadingQuestion[] = [
  createMultipleChoiceQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: proseWind,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.guidedCompareCharactersAndEvents,
    activityIdentifier: 'activity-compare-castle-compare-keep-guided-compare-characters-and-events',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.guidedCompareCharactersAndEvents[0],
    prompt: 'Which detail do both wind texts share?',
    explanation: 'Both texts show the wind changing what happens outdoors.',
    evidenceReference: createScopedEvidenceReference(proseWind, 'ck-lit-prose-3-s1'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(proseWind, 'ck-lit-prose-3-s1'),
      createScopedEvidenceReference(poemWind, 'ck-lit-poem-1-s1'),
    ],
    targetVocabulary: ['similar'],
    soundOutChunks: ['sim', 'i', 'lar'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'different-format'],
    choices: [
      choice('wind-change', 'The wind changes the outdoor scene.'),
      choice('rain-cups', 'The texts are about rain cups only.'),
      choice('music-room', 'The texts happen in a music room.'),
      choice('snow-day', 'The texts are about a snow day.'),
    ],
    correctChoiceIds: ['wind-change'],
  }),
  createMultipleChoiceQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: proseWind,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.guidedCompareCharactersAndEvents,
    activityIdentifier: 'activity-compare-castle-compare-keep-guided-compare-characters-and-events',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.guidedCompareCharactersAndEvents[1],
    prompt: 'How are the two wind texts different?',
    explanation: 'Text 1 is a story about a kite walk, and Text 2 is a poem about the wind and leaves.',
    evidenceReference: createScopedEvidenceReference(proseWind, 'ck-lit-prose-3-s4'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(proseWind, 'ck-lit-prose-3-s4'),
      createScopedEvidenceReference(poemWind, 'ck-lit-poem-1-s2'),
    ],
    targetVocabulary: ['different', 'compare'],
    soundOutChunks: ['dif', 'fer', 'ent'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'different-format'],
    choices: [
      choice('story-vs-poem', 'Text 1 is a story and Text 2 is a poem.'),
      choice('same-map', 'Both texts use a map.'),
      choice('same-rain', 'Both texts are about rain gauges.'),
      choice('same-parade', 'Both texts are about a parade.'),
    ],
    correctChoiceIds: ['story-vs-poem'],
  }),
  createMultiselectQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: proseWind,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.guidedCompareCharactersAndEvents,
    activityIdentifier: 'activity-compare-castle-compare-keep-guided-compare-characters-and-events',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.guidedCompareCharactersAndEvents[2],
    prompt: 'Choose two details that help compare the wind texts.',
    explanation: 'The best details show the wind, the kite, and the calm ending.',
    evidenceReference: createScopedEvidenceReference(proseWind, 'ck-lit-prose-3-s6'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(proseWind, 'ck-lit-prose-3-s6'),
      createScopedEvidenceReference(poemWind, 'ck-lit-poem-1-s5'),
    ],
    targetVocabulary: ['important', 'event'],
    soundOutChunks: ['im', 'por', 'tant'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'different-format'],
    choices: [
      choice('kite-rises', 'The kite rises when the wind changes.'),
      choice('wind-calms', 'The wind becomes calmer at the end.'),
      choice('pizza', 'The texts talk about pizza night.'),
      choice('tape', 'The texts are about sticky tape only.'),
    ],
    correctChoiceIds: ['kite-rises', 'wind-calms'],
  }),
  createHotTextQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: proseWind,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.guidedCompareCharactersAndEvents,
    activityIdentifier: 'activity-compare-castle-compare-keep-guided-compare-characters-and-events',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.guidedCompareCharactersAndEvents[3],
    prompt: 'Select the sentence in Text 1 that shows the kite rising.',
    explanation: 'The sentence about the kite rising shows the important event in Text 1.',
    evidenceReference: createScopedEvidenceReference(proseWind, 'ck-lit-prose-3-s4'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(proseWind, 'ck-lit-prose-3-s4'),
    ],
    targetVocabulary: ['carefully'],
    soundOutChunks: ['care', 'fully'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'different-format'],
    selectableSegments: [
      choice('seg-1', 'Quinn kept the string carefully loose, then carefully tight, until the kite rose.'),
      choice('seg-2', 'The grass bent low and whispered under the gust.'),
      choice('seg-3', 'Clouds drifted by in a soft gray line.'),
    ],
    correctSegmentIds: ['seg-1'],
  }),
  createTableMatchQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: proseWind,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.guidedCompareCharactersAndEvents,
    activityIdentifier: 'activity-compare-castle-compare-keep-guided-compare-characters-and-events',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.guidedCompareCharactersAndEvents[4],
    prompt: 'Build the comparison table for the wind texts.',
    explanation: 'The table helps sort the details that belong to Text 1, Text 2, or both texts.',
    evidenceReference: createScopedEvidenceReference(proseWind, 'ck-lit-prose-3-s1'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(proseWind, 'ck-lit-prose-3-s1'),
      createScopedEvidenceReference(poemWind, 'ck-lit-poem-1-s1'),
    ],
    targetVocabulary: ['compare', 'event'],
    soundOutChunks: ['ev', 'ent'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'different-format'],
    rows: [
      {
        id: 'row-a',
        prompt: 'The wind changes the scene outdoors.',
        correctChoiceId: 'both',
        options: [
          choice('text1', 'Text 1 only'),
          choice('text2', 'Text 2 only'),
          choice('both', 'Both texts'),
        ],
      },
      {
        id: 'row-b',
        prompt: 'A kite rises when the wind helps.',
        correctChoiceId: 'text1',
        options: [
          choice('both', 'Both texts'),
          choice('text1', 'Text 1 only'),
          choice('text2', 'Text 2 only'),
        ],
      },
      {
        id: 'row-c',
        prompt: 'Leaves lift and spin in the breeze.',
        correctChoiceId: 'text2',
        options: [
          choice('text1', 'Text 1 only'),
          choice('both', 'Both texts'),
          choice('text2', 'Text 2 only'),
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: rain1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.guidedCompareImportantFacts,
    activityIdentifier: 'activity-compare-castle-compare-keep-guided-compare-important-facts',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.guidedCompareImportantFacts[0],
    prompt: 'What is both weather-tool texts mostly about?',
    explanation: 'Both texts explain tools that help a class observe the weather.',
    evidenceReference: createScopedEvidenceReference(rain1, 'ck-info-3-s1'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(rain1, 'ck-info-3-s1'),
      createScopedEvidenceReference(rain2, 'ck-info-4-s1'),
    ],
    targetVocabulary: ['observe', 'weather'],
    soundOutChunks: ['ob', 'serve'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-topic'],
    choices: [
      choice('weather-tools', 'Tools help a class observe the weather.'),
      choice('music-tools', 'Tools help a band play music.'),
      choice('math-tools', 'Tools help solve math riddles.'),
      choice('food-tools', 'Tools help make snack food.'),
    ],
    correctChoiceIds: ['weather-tools'],
  }),
  createMultipleChoiceQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: rain1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.guidedCompareImportantFacts,
    activityIdentifier: 'activity-compare-castle-compare-keep-guided-compare-important-facts',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.guidedCompareImportantFacts[1],
    prompt: 'Which detail belongs only in Text 2?',
    explanation: 'Text 2 explains the weather shelter and the wind sock.',
    evidenceReference: createScopedEvidenceReference(rain2, 'ck-info-4-s3'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(rain2, 'ck-info-4-s2'),
      createScopedEvidenceReference(rain2, 'ck-info-4-s3'),
    ],
    targetVocabulary: ['shelter', 'wind'],
    soundOutChunks: ['shel', 'ter'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-topic'],
    choices: [
      choice('wind-sock', 'A wind sock hangs near the shelter.'),
      choice('rain-gauge', 'A clear cup measures the rain amount.'),
      choice('plants', 'The text is about plant roots only.'),
      choice('ballet', 'The text is about a ballet show.'),
    ],
    correctChoiceIds: ['wind-sock'],
  }),
  createMultiselectQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: rain1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.guidedCompareImportantFacts,
    activityIdentifier: 'activity-compare-castle-compare-keep-guided-compare-important-facts',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.guidedCompareImportantFacts[2],
    prompt: 'Choose two details that help compare the weather-tool texts.',
    explanation: 'The best details show what the tools measure and how students use them.',
    evidenceReference: createScopedEvidenceReference(rain1, 'ck-info-3-s5'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(rain1, 'ck-info-3-s5'),
      createScopedEvidenceReference(rain2, 'ck-info-4-s5'),
    ],
    targetVocabulary: ['important', 'careful'],
    soundOutChunks: ['care', 'ful'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-topic'],
    choices: [
      choice('notes', 'The class gathered careful notes.'),
      choice('compare-days', 'The notes help the students compare one day with the next.'),
      choice('bikes', 'The texts are about bike races.'),
      choice('paint', 'The texts are about paint colors.'),
    ],
    correctChoiceIds: ['notes', 'compare-days'],
  }),
  createHotTextQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: rain1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.guidedCompareImportantFacts,
    activityIdentifier: 'activity-compare-castle-compare-keep-guided-compare-important-facts',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.guidedCompareImportantFacts[3],
    prompt: 'Select the sentence in Text 1 that shows the main measurement tool.',
    explanation: 'The sentence about the rain gauge tells what the tool does.',
    evidenceReference: createScopedEvidenceReference(rain1, 'ck-info-3-s1'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(rain1, 'ck-info-3-s1'),
    ],
    targetVocabulary: ['measure'],
    soundOutChunks: ['mea', 'sure'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-topic'],
    selectableSegments: [
      choice('seg-1', 'A rain gauge is a clear cup that helps people measure how much rain falls.'),
      choice('seg-2', 'The water line shows whether the day had a little rain or a lot of rain.'),
      choice('seg-3', 'The cup must stay on level ground so the reading stays fair.'),
    ],
    correctSegmentIds: ['seg-1'],
  }),
  createTableMatchQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: rain1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.guidedCompareImportantFacts,
    activityIdentifier: 'activity-compare-castle-compare-keep-guided-compare-important-facts',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.guidedCompareImportantFacts[4],
    prompt: 'Sort each weather detail into the right box.',
    explanation: 'The table helps sort what belongs to Text 1, Text 2, or both texts.',
    evidenceReference: createScopedEvidenceReference(rain1, 'ck-info-3-s1'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(rain1, 'ck-info-3-s1'),
      createScopedEvidenceReference(rain2, 'ck-info-4-s1'),
    ],
    targetVocabulary: ['compare', 'detail'],
    soundOutChunks: ['de', 'tail'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-topic'],
    rows: [
      {
        id: 'row-a',
        prompt: 'Students use tools to observe the weather.',
        correctChoiceId: 'both',
        options: [
          choice('text1', 'Text 1 only'),
          choice('both', 'Both texts'),
          choice('text2', 'Text 2 only'),
        ],
      },
      {
        id: 'row-b',
        prompt: 'A rain gauge measures how much rain falls.',
        correctChoiceId: 'text1',
        options: [
          choice('text2', 'Text 2 only'),
          choice('text1', 'Text 1 only'),
          choice('both', 'Both texts'),
        ],
      },
      {
        id: 'row-c',
        prompt: 'A wind sock shows the breeze moving.',
        correctChoiceId: 'text2',
        options: [
          choice('both', 'Both texts'),
          choice('text2', 'Text 2 only'),
          choice('text1', 'Text 1 only'),
        ],
      },
    ],
  }),
]
