import type { ReadingQuestion } from '../../../../types'
import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
  createTwoPartQuestion,
} from './questionFactories'
import { createScopedEvidenceReference } from '../../../../evidence'
import {
  COMPARE_KEEP_BENCHMARK,
  COMPARE_KEEP_CONTENT_VERSION,
  COMPARE_KEEP_LESSON_IDS,
  COMPARE_KEEP_PASSAGE_IDS,
  COMPARE_KEEP_QUESTION_IDS,
} from './ids'

const reportingCategory = 'Reading Across Genres and Vocabulary'
const skillIdentifier = 'g2-across-genres-reading'
const genre = 'paired_text'

function choice(id: string, text: string) {
  return { id, text }
}

const literaryA1 = COMPARE_KEEP_PASSAGE_IDS.literaryProseD
const literaryA2 = COMPARE_KEEP_PASSAGE_IDS.literaryProseE
const informational1 = COMPARE_KEEP_PASSAGE_IDS.informationalE
const informational2 = COMPARE_KEEP_PASSAGE_IDS.informationalF
const literaryB1 = COMPARE_KEEP_PASSAGE_IDS.literaryProseF
const literaryB2 = COMPARE_KEEP_PASSAGE_IDS.literaryPoemB

const compareKeepCheckpointPatternTags = [
  'compare-contrast-important-details',
  'same-topic-or-theme',
  'paired-text-reading',
  'text-1-text-2-evidence',
  'important-detail-identification',
  'important-vs-minor-detail',
  'similarity-identification',
  'difference-identification',
  'comparison-evidence',
  'same-topic-pair',
  'same-theme-pair',
  'same-format-pair',
  'different-format-pair',
  'literary-character-comparison',
  'literary-setting-comparison',
  'literary-event-sequence-comparison',
  'informational-central-idea-comparison',
  'informational-detail-comparison',
  'informational-process-comparison',
  'structured-compare-contrast',
] as const

export const compareKeepCheckpointQuestions: ReadingQuestion[] = [
  createMultipleChoiceQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: literaryA1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointLiteraryA,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-literary-a',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointLiteraryA[0],
    prompt: 'How are the two literary texts alike?',
    explanation: 'Both texts show careful helpers working through a plan until the space is ready.',
    evidenceReference: createScopedEvidenceReference(literaryA1, 'ck-lit-prose-4-s4'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(literaryA1, 'ck-lit-prose-4-s4'),
      createScopedEvidenceReference(literaryA2, 'ck-lit-prose-5-s4'),
    ],
    targetVocabulary: ['similar', 'compare'],
    soundOutChunks: ['sim', 'i', 'lar'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-theme', 'literary-character-comparison', ...compareKeepCheckpointPatternTags],
    choices: [
      choice('careful-help', 'Both texts show careful helpers working through a plan.'),
      choice('weather-tools', 'Both texts are about weather tools.'),
      choice('seed-trip', 'Both texts explain how seeds travel.'),
      choice('camp-lights', 'Both texts are about camp lanterns only.'),
    ],
    correctChoiceIds: ['careful-help'],
  }),
  createMultipleChoiceQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: literaryA1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointLiteraryA,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-literary-a',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointLiteraryA[1],
    prompt: 'Which detail belongs only in Text 2?',
    explanation: 'Text 2 is the parade story, so the map spread across chairs belongs there only.',
    evidenceReference: createScopedEvidenceReference(literaryA2, 'ck-lit-prose-5-s1'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(literaryA1, 'ck-lit-prose-4-s1'),
      createScopedEvidenceReference(literaryA2, 'ck-lit-prose-5-s1'),
    ],
    targetVocabulary: ['different', 'important'],
    soundOutChunks: ['dif', 'fer', 'ent'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-theme', 'difference-identification'],
    choices: [
      choice('trail-card', 'The class finds a missing trail card.'),
      choice('map-chairs', 'The parade team spreads a map across two folding chairs.'),
      choice('start-on-time', 'The class can start on time.'),
      choice('careful-plan', 'Both groups stay calm and follow a plan.'),
    ],
    correctChoiceIds: ['map-chairs'],
  }),
  createMultipleChoiceQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: literaryA1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointLiteraryA,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-literary-a',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointLiteraryA[2],
    prompt: 'Which detail is less important for the comparison?',
    explanation: 'The balloons are true, but they do not help the reader compare the two texts as well.',
    evidenceReference: createScopedEvidenceReference(literaryA2, 'ck-lit-prose-5-s5'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(literaryA1, 'ck-lit-prose-4-s4'),
      createScopedEvidenceReference(literaryA2, 'ck-lit-prose-5-s5'),
    ],
    targetVocabulary: ['minor', 'important'],
    soundOutChunks: ['mi', 'nor'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-theme', 'important-vs-minor-detail'],
    choices: [
      choice('trail-card', 'Eli found the trail card in his backpack.'),
      choice('map-plan', 'The leaders checked the sequence again so no group would miss a turn.'),
      choice('balloons', 'A few balloons bumped together in the breeze.'),
      choice('start-order', 'The parade moved in the right order from start to finish.'),
    ],
    correctChoiceIds: ['balloons'],
  }),
  createMultiselectQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: literaryA1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointLiteraryA,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-literary-a',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointLiteraryA[3],
    prompt: 'Choose two details that belong in the literary comparison.',
    explanation: 'The best details show the important actions that help each group finish the plan.',
    evidenceReference: createScopedEvidenceReference(literaryA1, 'ck-lit-prose-4-s5'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(literaryA1, 'ck-lit-prose-4-s5'),
      createScopedEvidenceReference(literaryA2, 'ck-lit-prose-5-s6'),
    ],
    targetVocabulary: ['sequence', 'compare'],
    soundOutChunks: ['se', 'quence'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-theme', 'event-sequence-comparison'],
    choices: [
      choice('start-on-time', 'The class can start on time because the route card is found.'),
      choice('right-order', 'The parade moves in the right order from start to finish.'),
      choice('purple-sky', 'The sky turns purple at camp.'),
      choice('notebook-slip', 'The card slipped behind the notebook during line-up.'),
    ],
    correctChoiceIds: ['start-on-time', 'right-order'],
  }),
  createHotTextQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: literaryA1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointLiteraryA,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-literary-a',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointLiteraryA[4],
    prompt: 'Select the sentence in Text 1 that shows the resolution.',
    explanation: 'The sentence about the class starting on time shows the ending clearly.',
    evidenceReference: createScopedEvidenceReference(literaryA1, 'ck-lit-prose-4-s5'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(literaryA1, 'ck-lit-prose-4-s5'),
    ],
    targetVocabulary: ['resolution'],
    soundOutChunks: ['re', 'so', 'lu', 'tion'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-theme', 'literary-event-sequence-comparison'],
    selectableSegments: [
      choice('seg-1', 'The class could start on time because he had found the one card that set the route.'),
      choice('seg-2', 'The card had slipped behind his notebook during morning line-up.'),
      choice('seg-3', 'A few balloons bumped together in the breeze, but the map kept the plan calm.'),
    ],
    correctSegmentIds: ['seg-1'],
  }),
  createTableMatchQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: literaryA1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointLiteraryA,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-literary-a',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointLiteraryA[5],
    prompt: 'Sort each detail into the right column.',
    explanation: 'The table shows which details belong to Text 1, both texts, or Text 2.',
    evidenceReference: createScopedEvidenceReference(literaryA1, 'ck-lit-prose-4-s1'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(literaryA1, 'ck-lit-prose-4-s1'),
      createScopedEvidenceReference(literaryA2, 'ck-lit-prose-5-s1'),
    ],
    targetVocabulary: ['detail', 'compare'],
    soundOutChunks: ['de', 'tail'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-theme', 'comparison-evidence'],
    rows: [
      {
        id: 'row-a',
        prompt: 'A helper finds a missing route card before the walk.',
        correctChoiceId: 'text1',
        options: [
          choice('both', 'Both texts'),
          choice('text1', 'Text 1 only'),
          choice('text2', 'Text 2 only'),
        ],
      },
      {
        id: 'row-b',
        prompt: 'Both texts end with the group ready to move forward.',
        correctChoiceId: 'both',
        options: [
          choice('text1', 'Text 1 only'),
          choice('text2', 'Text 2 only'),
          choice('both', 'Both texts'),
        ],
      },
      {
        id: 'row-c',
        prompt: 'The parade team spreads a map across chairs.',
        correctChoiceId: 'text2',
        options: [
          choice('text2', 'Text 2 only'),
          choice('both', 'Both texts'),
          choice('text1', 'Text 1 only'),
        ],
      },
    ],
  }),
  createTwoPartQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: literaryA1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointLiteraryA,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-literary-a',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointLiteraryA[6],
    prompt: 'Part A and Part B: compare the literary texts.',
    explanation: 'The best answer names the different jobs and then points to evidence from both texts.',
    evidenceReference: createScopedEvidenceReference(literaryA1, 'ck-lit-prose-4-s5'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(literaryA1, 'ck-lit-prose-4-s5'),
      createScopedEvidenceReference(literaryA2, 'ck-lit-prose-5-s6'),
    ],
    targetVocabulary: ['similar', 'difference'],
    soundOutChunks: ['dif', 'fer', 'ence'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-theme', 'structured-compare-contrast'],
    partAPrompt: 'Which important difference do the texts show?',
    partAChoices: [
      choice('help-and-map', 'Text 1 focuses on a lost route card, and Text 2 focuses on a parade map.'),
      choice('weather-tools', 'Both texts are about weather tools.'),
      choice('seed-travel', 'Both texts explain how seeds travel.'),
    ],
    partACorrectChoiceId: 'help-and-map',
    partBPrompt: 'Which evidence best supports that difference?',
    partBChoices: [
      choice('route-card', 'Eli found the one card that set the route. / The parade team spread a map across chairs.'),
      choice('wind-sock', 'A wind sock hangs near the shelter. / A rain gauge measures rain.'),
      choice('pond-roots', 'The pond has shelter for animals. / Roots hold the soil in place.'),
    ],
    partBCorrectChoiceId: 'route-card',
  }),

  createMultipleChoiceQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: informational1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointInformational,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-informational',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointInformational[0],
    prompt: 'What are both informational texts mostly about?',
    explanation: 'Both texts explain how roots support plants and help soil stay in place.',
    evidenceReference: createScopedEvidenceReference(informational1, 'ck-info-5-s6'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(informational1, 'ck-info-5-s6'),
      createScopedEvidenceReference(informational2, 'ck-info-6-s6'),
    ],
    targetVocabulary: ['central', 'idea'],
    soundOutChunks: ['cen', 'tral'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-topic', 'informational-central-idea-comparison', ...compareKeepCheckpointPatternTags],
    choices: [
      choice('living-places', 'How roots support plants and soil.'),
      choice('music-show', 'How a music show gets ready.'),
      choice('kite-wind', 'How a kite flies in the wind.'),
      choice('garden-sign', 'How to fix a garden sign.'),
    ],
    correctChoiceIds: ['living-places'],
  }),
  createMultipleChoiceQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: informational1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointInformational,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-informational',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointInformational[1],
    prompt: 'Which detail belongs only in Text 1?',
    explanation: 'Only Text 1 explains that pond-edge plants shelter small animals.',
    evidenceReference: createScopedEvidenceReference(informational1, 'ck-info-5-s1'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(informational1, 'ck-info-5-s1'),
      createScopedEvidenceReference(informational2, 'ck-info-6-s1'),
    ],
    targetVocabulary: ['different', 'important'],
    soundOutChunks: ['dif', 'fer', 'ent'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-topic', 'informational-detail-comparison'],
    choices: [
      choice('pond-layers', 'Pond-edge plants give shelter to small animals.'),
      choice('soil-strong', 'Roots help soil stay in place.'),
      choice('both-support', 'Both texts explain how roots support soil.'),
      choice('notes', 'The class gathered careful notes after each observation.'),
    ],
    correctChoiceIds: ['pond-layers'],
  }),
  createMultipleChoiceQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: informational1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointInformational,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-informational',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointInformational[2],
    prompt: 'Which detail is less important for the comparison?',
    explanation: 'The shallow pond edge is true, but the strongest comparison focuses on what roots do.',
    evidenceReference: createScopedEvidenceReference(informational1, 'ck-info-5-s6'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(informational1, 'ck-info-5-s6'),
      createScopedEvidenceReference(informational2, 'ck-info-6-s6'),
    ],
    targetVocabulary: ['minor', 'important'],
    soundOutChunks: ['mi', 'nor'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-topic', 'important-vs-minor-detail'],
    choices: [
      choice('small-shower', 'The pond edge is shallow.'),
      choice('root-grip', 'Roots help soil stay in place.'),
      choice('fresh-soil', 'Both texts explain how roots support plants and soil.'),
      choice('protect-tools', 'Text 1 explains that roots work near moving pond water.'),
    ],
    correctChoiceIds: ['small-shower'],
  }),
  createMultiselectQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: informational1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointInformational,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-informational',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointInformational[3],
    prompt: 'Choose two details that help compare the informational texts.',
    explanation: 'The best details show roots holding muddy pond soil and garden soil in place.',
    evidenceReference: createScopedEvidenceReference(informational1, 'ck-info-5-s5'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(informational1, 'ck-info-5-s5'),
      createScopedEvidenceReference(informational2, 'ck-info-6-s3'),
    ],
    targetVocabulary: ['important', 'detail'],
    soundOutChunks: ['im', 'por', 'tant'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-topic', 'comparison-evidence'],
    choices: [
      choice('pond-support', 'Pond-edge roots help muddy soil stay in place when water moves.'),
      choice('roots-hold', 'Garden roots help soil stay in place after heavy rain.'),
      choice('sports-day', 'The texts are about sports day.'),
      choice('marker-color', 'The texts compare marker colors.'),
    ],
    correctChoiceIds: ['pond-support', 'roots-hold'],
  }),
  createHotTextQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: informational1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointInformational,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-informational',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointInformational[4],
    prompt: 'Select the sentence in Text 2 that shows the main idea.',
    explanation: 'The final sentence states that garden roots support both the plant and the soil.',
    evidenceReference: createScopedEvidenceReference(informational2, 'ck-info-6-s6'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(informational1, 'ck-info-5-s1'),
      createScopedEvidenceReference(informational2, 'ck-info-6-s6'),
    ],
    targetVocabulary: ['main', 'idea'],
    soundOutChunks: ['mai', 'n'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-topic', 'informational-central-idea-comparison', ...compareKeepCheckpointPatternTags],
    selectableSegments: [
      choice('seg-1', 'Plant roots push into soil and spread in many directions.'),
      choice('seg-2', 'The roots gather water and hold the plant steady.'),
      choice('seg-3', 'Garden roots help both the plant and the soil stay steady.'),
    ],
    correctSegmentIds: ['seg-3'],
  }),
  createTableMatchQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: informational1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointInformational,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-informational',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointInformational[5],
    prompt: 'Sort each fact into the right column.',
    explanation: 'The table shows whether a fact belongs to Text 1, Text 2, or both texts.',
    evidenceReference: createScopedEvidenceReference(informational1, 'ck-info-5-s1'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(informational1, 'ck-info-5-s1'),
      createScopedEvidenceReference(informational2, 'ck-info-6-s1'),
    ],
    targetVocabulary: ['compare', 'fact'],
    soundOutChunks: ['fac', 't'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-topic', 'structured-compare-contrast'],
    rows: [
      {
        id: 'row-a',
        prompt: 'Pond-edge plants give shelter to small animals.',
        correctChoiceId: 'text1',
        options: [
          choice('text1', 'Text 1 only'),
          choice('both', 'Both texts'),
          choice('text2', 'Text 2 only'),
        ],
      },
      {
        id: 'row-b',
        prompt: 'Garden roots hold the plant upright.',
        correctChoiceId: 'text2',
        options: [
          choice('text2', 'Text 2 only'),
          choice('both', 'Both texts'),
          choice('text1', 'Text 1 only'),
        ],
      },
      {
        id: 'row-c',
        prompt: 'Roots help soil stay in place.',
        correctChoiceId: 'both',
        options: [
          choice('both', 'Both texts'),
          choice('text1', 'Text 1 only'),
          choice('text2', 'Text 2 only'),
        ],
      },
    ],
  }),
  createTwoPartQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: informational1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointInformational,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-informational',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointInformational[6],
    prompt: 'Part A and Part B: compare the informational texts.',
    explanation: 'The strongest answer names the shared idea and then points to evidence from both texts.',
    evidenceReference: createScopedEvidenceReference(informational1, 'ck-info-5-s6'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(informational1, 'ck-info-5-s6'),
      createScopedEvidenceReference(informational2, 'ck-info-6-s6'),
    ],
    targetVocabulary: ['central', 'compare'],
    soundOutChunks: ['com', 'pare'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-topic', 'structured-compare-contrast'],
    partAPrompt: 'Which important similarity do the texts share?',
    partAChoices: [
      choice('support-place', 'Both texts explain how roots support plants and soil.'),
      choice('story-kite', 'Both texts are about a kite in the park.'),
      choice('stage-show', 'Both texts are about a stage show.'),
    ],
    partACorrectChoiceId: 'support-place',
    partBPrompt: 'Which evidence best supports that similarity?',
    partBChoices: [
      choice('pond-roots', 'Pond-edge roots hold muddy soil. / Garden roots help soil stay in place after heavy rain.'),
      choice('trail-map', 'The class finds a trail card. / The parade team uses a map.'),
      choice('wind-kite', 'The kite rises in the wind. / Leaves spin in the breeze.'),
    ],
    partBCorrectChoiceId: 'pond-roots',
  }),

  createMultipleChoiceQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: literaryB1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointLiteraryB,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-literary-b',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointLiteraryB[0],
    prompt: 'How are the two literary texts alike?',
    explanation: 'Both texts show helpers getting ready for a shared event with care.',
    evidenceReference: createScopedEvidenceReference(literaryB1, 'ck-lit-prose-6-s4'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(literaryB1, 'ck-lit-prose-6-s4'),
      createScopedEvidenceReference(literaryB2, 'ck-lit-poem-2-s2'),
    ],
    targetVocabulary: ['similar', 'careful'],
    soundOutChunks: ['sim', 'i', 'lar'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-theme', 'literary-character-comparison', ...compareKeepCheckpointPatternTags],
    choices: [
      choice('careful-help', 'Both texts show helpers getting ready with care.'),
      choice('ponds', 'Both texts are about pond layers.'),
      choice('seeds', 'Both texts explain seed travel.'),
      choice('weather', 'Both texts are about weather tools.'),
    ],
    correctChoiceIds: ['careful-help'],
  }),
  createMultipleChoiceQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: literaryB1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointLiteraryB,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-literary-b',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointLiteraryB[1],
    prompt: 'Which detail belongs only in Text 2?',
    explanation: 'Text 2 is the poem about the show, so the spotlight line belongs there only.',
    evidenceReference: createScopedEvidenceReference(literaryB2, 'ck-lit-poem-2-s6'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(literaryB1, 'ck-lit-prose-6-s1'),
      createScopedEvidenceReference(literaryB2, 'ck-lit-poem-2-s6'),
    ],
    targetVocabulary: ['different', 'detail'],
    soundOutChunks: ['dif', 'fer', 'ent'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'different-format', 'difference-identification'],
    choices: [
      choice('spotlight', 'A spotlight warmed the stage like morning toast.'),
      choice('camp-lanterns', 'Rosa and Leo sorted lanterns, cups, and blankets onto one long picnic table.'),
      choice('careful-work', 'Both texts show helpers working carefully.'),
      choice('ready-calm', 'Both texts move from getting ready to feeling calm.'),
    ],
    correctChoiceIds: ['spotlight'],
  }),
  createMultipleChoiceQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: literaryB1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointLiteraryB,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-literary-b',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointLiteraryB[2],
    prompt: 'Which detail is less important for the comparison?',
    explanation: 'The room buzzes quietly, but that detail is not the strongest way to compare the texts.',
    evidenceReference: createScopedEvidenceReference(literaryB2, 'ck-lit-poem-2-s1'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(literaryB1, 'ck-lit-prose-6-s4'),
      createScopedEvidenceReference(literaryB2, 'ck-lit-poem-2-s1'),
    ],
    targetVocabulary: ['minor', 'important'],
    soundOutChunks: ['mi', 'nor'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'different-format', 'important-vs-minor-detail'],
    choices: [
      choice('quiet-buzz', 'Before the show, the room held a quiet, shining buzz.'),
      choice('careful-help', 'Helpers work carefully before the event begins.'),
      choice('stage-lines', 'The audience listens while the lines find their place.'),
      choice('ready-ending', 'The helpers bow under the soft lights.'),
    ],
    correctChoiceIds: ['quiet-buzz'],
  }),
  createMultiselectQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: literaryB1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointLiteraryB,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-literary-b',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointLiteraryB[3],
    prompt: 'Choose two details that help compare the literary texts.',
    explanation: 'The best details show how both texts move from preparation to a ready ending.',
    evidenceReference: createScopedEvidenceReference(literaryB1, 'ck-lit-prose-6-s2'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(literaryB1, 'ck-lit-prose-6-s2'),
      createScopedEvidenceReference(literaryB2, 'ck-lit-poem-2-s5'),
    ],
    targetVocabulary: ['sequence', 'compare'],
    soundOutChunks: ['se', 'quence'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'different-format', 'event-sequence-comparison'],
    choices: [
      choice('prep-to-ready', 'Both texts move from getting ready to feeling ready.'),
      choice('helpers-together', 'Helpers work together before the event begins.'),
      choice('music-rain', 'The texts are about music and rain.'),
      choice('bike-race', 'The texts are about a bike race.'),
    ],
    correctChoiceIds: ['prep-to-ready', 'helpers-together'],
  }),
  createHotTextQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: literaryB1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointLiteraryB,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-literary-b',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointLiteraryB[4],
    prompt: 'Select the line in Text 1 that shows the preparation.',
    explanation: 'The line about gathering materials shows the careful preparation step.',
    evidenceReference: createScopedEvidenceReference(literaryB1, 'ck-lit-prose-6-s2'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(literaryB1, 'ck-lit-prose-6-s2'),
    ],
    targetVocabulary: ['preparation'],
    soundOutChunks: ['prep', 'ar', 'a', 'tion'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'different-format', 'literary-event-sequence-comparison'],
    selectableSegments: [
      choice('seg-1', 'They gathered the materials before the sky turned purple.'),
      choice('seg-2', 'A helper brought an extra lantern, and the table plan grew even better.'),
      choice('seg-3', 'The room held a quiet, shining buzz.'),
    ],
    correctSegmentIds: ['seg-1'],
  }),
  createTableMatchQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: literaryB1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointLiteraryB,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-literary-b',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointLiteraryB[5],
    prompt: 'Sort each detail into the right column.',
    explanation: 'The table helps sort which details belong to Text 1, both texts, or Text 2.',
    evidenceReference: createScopedEvidenceReference(literaryB1, 'ck-lit-prose-6-s1'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(literaryB1, 'ck-lit-prose-6-s1'),
      createScopedEvidenceReference(literaryB2, 'ck-lit-poem-2-s1'),
    ],
    targetVocabulary: ['detail', 'compare'],
    soundOutChunks: ['com', 'pare'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'different-format', 'comparison-evidence'],
    rows: [
      {
        id: 'row-a',
        prompt: 'Helpers sort lanterns, cups, and blankets onto one table.',
        correctChoiceId: 'text1',
        options: [
          choice('both', 'Both texts'),
          choice('text1', 'Text 1 only'),
          choice('text2', 'Text 2 only'),
        ],
      },
      {
        id: 'row-b',
        prompt: 'Both texts show a calm, ready feeling before the event starts.',
        correctChoiceId: 'both',
        options: [
          choice('text2', 'Text 2 only'),
          choice('both', 'Both texts'),
          choice('text1', 'Text 1 only'),
        ],
      },
      {
        id: 'row-c',
        prompt: 'A spotlight warms the stage during the show.',
        correctChoiceId: 'text2',
        options: [
          choice('text1', 'Text 1 only'),
          choice('text2', 'Text 2 only'),
          choice('both', 'Both texts'),
        ],
      },
    ],
  }),
  createTwoPartQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 3,
    passageIdentifier: literaryB1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.checkpointLiteraryB,
    activityIdentifier: 'activity-compare-castle-compare-keep-checkpoint-literary-b',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.checkpointLiteraryB[6],
    prompt: 'Part A and Part B: compare the literary texts.',
    explanation: 'The strongest answer names the shared preparation and then points to evidence from both texts.',
    evidenceReference: createScopedEvidenceReference(literaryB1, 'ck-lit-prose-6-s4'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(literaryB1, 'ck-lit-prose-6-s4'),
      createScopedEvidenceReference(literaryB2, 'ck-lit-poem-2-s2'),
    ],
    targetVocabulary: ['similar', 'difference'],
    soundOutChunks: ['dif', 'fer', 'ence'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'different-format', 'structured-compare-contrast'],
    partAPrompt: 'Which important similarity do the texts share?',
    partAChoices: [
      choice('ready-before-event', 'Both texts show helpers getting ready before a shared event.'),
      choice('seed-travel', 'Both texts explain how seeds move.'),
      choice('weather-tools', 'Both texts are about weather tools.'),
    ],
    partACorrectChoiceId: 'ready-before-event',
    partBPrompt: 'Which evidence best supports that similarity?',
    partBChoices: [
      choice('prep-lines', 'They gathered the materials before the sky turned purple. / Before the show, the room held a quiet, shining buzz.'),
      choice('pond-roots', 'Pond layers give food and shelter. / Roots help soil stay in place.'),
      choice('trail-map', 'The trail card sets the route. / The parade team spreads a map across chairs.'),
    ],
    partBCorrectChoiceId: 'prep-lines',
  }),
]
