import type { ReadingQuestion } from '../../../../types'
import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from './questionFactories'
import { createScopedEvidenceReference } from '../../../../evidence'
import {
  COMPARE_KEEP_BENCHMARK,
  COMPARE_KEEP_CONTENT_VERSION,
  COMPARE_KEEP_LESSON_IDS,
  COMPARE_KEEP_PASSAGE_IDS,
  COMPARE_KEEP_QUESTION_IDS,
} from './ids'

const reportingCategory = 'Reading Across Genres and Vocabulary'
const skillIdentifier = 'g2-across-genres-reading'
const genre = 'paired_text'

function choice(id: string, text: string) {
  return { id, text }
}

const text1 = COMPARE_KEEP_PASSAGE_IDS.literaryProseA
const seedText1 = COMPARE_KEEP_PASSAGE_IDS.informationalA

export const compareKeepPrerequisiteQuestions: ReadingQuestion[] = [
  createMultipleChoiceQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 2,
    passageIdentifier: text1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.prereqFindWhatBothTextsShare,
    activityIdentifier: 'activity-compare-castle-compare-keep-prereq-find-what-both-texts-share',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.prereqFindWhatBothTextsShare[0],
    prompt: 'Which idea best tells what both texts show?',
    explanation: 'Both texts show helpers working together to move a shared space forward.',
    evidenceReference: createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.literaryProseA, 'ck-lit-prose-1-s1'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.literaryProseA, 'ck-lit-prose-1-s1'),
      createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.literaryProseB, 'ck-lit-prose-2-s1'),
    ],
    targetVocabulary: ['compare', 'similar'],
    soundOutChunks: ['com', 'pare'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-theme'],
    choices: [
      choice('both-help', 'Helpers work together to fix a shared space.'),
      choice('both-rain', 'Both texts are about rain and puddles.'),
      choice('both-games', 'Both texts are about playground games.'),
      choice('both-dogs', 'Both texts are about dogs on a walk.'),
    ],
    correctChoiceIds: ['both-help'],
  }),
  createMultipleChoiceQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 2,
    passageIdentifier: text1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.prereqFindWhatBothTextsShare,
    activityIdentifier: 'activity-compare-castle-compare-keep-prereq-find-what-both-texts-share',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.prereqFindWhatBothTextsShare[1],
    prompt: 'Which detail belongs in both stories?',
    explanation: 'Each story starts with a problem that needs careful help.',
    evidenceReference: createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.literaryProseA, 'ck-lit-prose-1-s1'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.literaryProseA, 'ck-lit-prose-1-s1'),
      createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.literaryProseB, 'ck-lit-prose-2-s1'),
    ],
    targetVocabulary: ['important', 'problem'],
    soundOutChunks: ['im', 'por', 'tant'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-theme'],
    choices: [
      choice('problem-first', 'The text starts with a problem that needs help.'),
      choice('ocean-shore', 'The text starts at the ocean shore.'),
      choice('birthday-cake', 'The text starts with a birthday cake.'),
      choice('train-station', 'The text starts at a train station.'),
    ],
    correctChoiceIds: ['problem-first'],
  }),
  createMultiselectQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 2,
    passageIdentifier: text1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.prereqFindWhatBothTextsShare,
    activityIdentifier: 'activity-compare-castle-compare-keep-prereq-find-what-both-texts-share',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.prereqFindWhatBothTextsShare[2],
    prompt: 'Choose two details that belong in a comparison of these texts.',
    explanation: 'The best details are the ones that show teamwork and a ready ending.',
    evidenceReference: createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.literaryProseA, 'ck-lit-prose-1-s4'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.literaryProseA, 'ck-lit-prose-1-s4'),
      createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.literaryProseB, 'ck-lit-prose-2-s4'),
    ],
    targetVocabulary: ['carefully', 'together'],
    soundOutChunks: ['care', 'fully'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-theme'],
    choices: [
      choice('careful-work', 'The helpers work carefully.'),
      choice('ready-ending', 'The space ends up ready to use.'),
      choice('icy-road', 'The story takes place on an icy road.'),
      choice('big-storm', 'The texts are about a big storm.'),
    ],
    correctChoiceIds: ['careful-work', 'ready-ending'],
  }),
  createHotTextQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 2,
    passageIdentifier: text1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.prereqFindWhatBothTextsShare,
    activityIdentifier: 'activity-compare-castle-compare-keep-prereq-find-what-both-texts-share',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.prereqFindWhatBothTextsShare[3],
    prompt: 'Select the sentence that shows careful work in Text 1.',
    explanation: 'The sentence about working carefully shows the helpful action clearly.',
    evidenceReference: createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.literaryProseA, 'ck-lit-prose-1-s4'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.literaryProseA, 'ck-lit-prose-1-s4'),
    ],
    targetVocabulary: ['carefully'],
    soundOutChunks: ['care', 'fully'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-theme'],
    selectableSegments: [
      choice('seg-1', 'They worked carefully so the carrots would still have room to grow.'),
      choice('seg-2', 'The sign bent like a sleepy spoon beside the bean patch.'),
      choice('seg-3', 'By the end of lunch, the garden looked neat.'),
    ],
    correctSegmentIds: ['seg-1'],
  }),
  createTableMatchQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 2,
    passageIdentifier: text1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.prereqFindWhatBothTextsShare,
    activityIdentifier: 'activity-compare-castle-compare-keep-prereq-find-what-both-texts-share',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.prereqFindWhatBothTextsShare[4],
    prompt: 'Build the comparison by sorting each detail.',
    explanation: 'The table shows which details belong to Text 1, Text 2, or both texts.',
    evidenceReference: createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.literaryProseA, 'ck-lit-prose-1-s1'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.literaryProseA, 'ck-lit-prose-1-s1'),
      createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.literaryProseB, 'ck-lit-prose-2-s1'),
    ],
    targetVocabulary: ['compare', 'important'],
    soundOutChunks: ['im', 'por', 'tant'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-theme'],
    rows: [
      {
        id: 'row-a',
        prompt: 'Two helpers work together to fix a shared space.',
        correctChoiceId: 'both',
        options: [
          choice('text1', 'Text 1 only'),
          choice('both', 'Both texts'),
          choice('text2', 'Text 2 only'),
        ],
      },
      {
        id: 'row-b',
        prompt: 'A garden sign stands straight again.',
        correctChoiceId: 'text1',
        options: [
          choice('text2', 'Text 2 only'),
          choice('text1', 'Text 1 only'),
          choice('both', 'Both texts'),
        ],
      },
      {
        id: 'row-c',
        prompt: 'Paper stars and a banner string help decorate the hall.',
        correctChoiceId: 'text2',
        options: [
          choice('both', 'Both texts'),
          choice('text2', 'Text 2 only'),
          choice('text1', 'Text 1 only'),
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 2,
    passageIdentifier: seedText1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.prereqFindWhatEachTextAdds,
    activityIdentifier: 'activity-compare-castle-compare-keep-prereq-find-what-each-text-adds',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.prereqFindWhatEachTextAdds[0],
    prompt: 'What is both informational texts mostly about?',
    explanation: 'Both texts explain ways seeds travel to new places.',
    evidenceReference: createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.informationalA, 'ck-info-1-s1'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.informationalA, 'ck-info-1-s1'),
      createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.informationalB, 'ck-info-2-s1'),
    ],
    targetVocabulary: ['travel', 'spread'],
    soundOutChunks: ['trav', 'el'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-topic'],
    choices: [
      choice('seed-travel', 'How seeds travel to new places.'),
      choice('weather', 'How weather changes every hour.'),
      choice('animals', 'How animals build homes.'),
      choice('music', 'How a band makes music.'),
    ],
    correctChoiceIds: ['seed-travel'],
  }),
  createMultipleChoiceQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 2,
    passageIdentifier: seedText1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.prereqFindWhatEachTextAdds,
    activityIdentifier: 'activity-compare-castle-compare-keep-prereq-find-what-each-text-adds',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.prereqFindWhatEachTextAdds[1],
    prompt: 'Which detail belongs in Text 2 only?',
    explanation: 'Text 2 explains wind and water moving seeds.',
    evidenceReference: createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.informationalB, 'ck-info-2-s2'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.informationalB, 'ck-info-2-s2'),
    ],
    targetVocabulary: ['wind', 'water'],
    soundOutChunks: ['wind'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-topic'],
    choices: [
      choice('fur', 'Seeds cling to fur or clothes.'),
      choice('wind', 'A breeze carries light seeds.'),
      choice('fresh', 'Seeds reach fresh soil.'),
      choice('parent', 'Seeds stay beside the parent plant.'),
    ],
    correctChoiceIds: ['wind'],
  }),
  createMultiselectQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 2,
    passageIdentifier: seedText1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.prereqFindWhatEachTextAdds,
    activityIdentifier: 'activity-compare-castle-compare-keep-prereq-find-what-each-text-adds',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.prereqFindWhatEachTextAdds[2],
    prompt: 'Choose two details that belong in the informational comparison.',
    explanation: 'The best details are the ones that show how seeds travel and spread.',
    evidenceReference: createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.informationalA, 'ck-info-1-s5'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.informationalA, 'ck-info-1-s5'),
      createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.informationalB, 'ck-info-2-s5'),
    ],
    targetVocabulary: ['important', 'fresh'],
    soundOutChunks: ['im', 'por', 'tant'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-topic'],
    choices: [
      choice('spread-plants', 'The texts explain how plants spread.'),
      choice('fresh-soil', 'The seeds reach fresh soil.'),
      choice('ballet', 'The texts are about a ballet show.'),
      choice('desk', 'The texts are about a classroom desk.'),
    ],
    correctChoiceIds: ['spread-plants', 'fresh-soil'],
  }),
  createHotTextQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 2,
    passageIdentifier: seedText1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.prereqFindWhatEachTextAdds,
    activityIdentifier: 'activity-compare-castle-compare-keep-prereq-find-what-each-text-adds',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.prereqFindWhatEachTextAdds[3],
    prompt: 'Select the sentence in Text 1 that explains how seeds spread.',
    explanation: 'The sentence about the seed moving to new soil shows the important process.',
    evidenceReference: createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.informationalA, 'ck-info-1-s4'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.informationalA, 'ck-info-1-s4'),
    ],
    targetVocabulary: ['process'],
    soundOutChunks: ['pro', 'cess'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-topic'],
    selectableSegments: [
      choice('seg-1', 'Later, the seed rubs off near soil and starts a new plant home.'),
      choice('seg-2', 'Their hooks or sticky coats catch on a walking animal.'),
      choice('seg-3', 'A single seed can make a long trip without using wind or water.'),
    ],
    correctSegmentIds: ['seg-1'],
  }),
  createTableMatchQuestion({
    benchmarkReference: COMPARE_KEEP_BENCHMARK,
    skillIdentifier,
    reportingCategory,
    genre,
    difficulty: 2,
    passageIdentifier: seedText1,
    lessonIdentifier: COMPARE_KEEP_LESSON_IDS.prereqFindWhatEachTextAdds,
    activityIdentifier: 'activity-compare-castle-compare-keep-prereq-find-what-each-text-adds',
    questionIdentifier: COMPARE_KEEP_QUESTION_IDS.prereqFindWhatEachTextAdds[4],
    prompt: 'Sort each seed detail into the right column.',
    explanation: 'The table shows whether a detail belongs to Text 1, Text 2, or both texts.',
    evidenceReference: createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.informationalA, 'ck-info-1-s1'),
    evidenceReferenceIds: [
      createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.informationalA, 'ck-info-1-s1'),
      createScopedEvidenceReference(COMPARE_KEEP_PASSAGE_IDS.informationalB, 'ck-info-2-s1'),
    ],
    targetVocabulary: ['compare', 'detail'],
    soundOutChunks: ['de', 'tail'],
    estimatedReadingLevel: 'Grade 2',
    contentVersion: COMPARE_KEEP_CONTENT_VERSION,
    tags: ['paired-text', 'same-topic'],
    rows: [
      {
        id: 'row-a',
        prompt: 'Seeds can travel away from the parent plant.',
        correctChoiceId: 'both',
        options: [
          choice('text1', 'Text 1 only'),
          choice('both', 'Both texts'),
          choice('text2', 'Text 2 only'),
        ],
      },
      {
        id: 'row-b',
        prompt: 'Seeds cling to fur or clothes.',
        correctChoiceId: 'text1',
        options: [
          choice('text2', 'Text 2 only'),
          choice('both', 'Both texts'),
          choice('text1', 'Text 1 only'),
        ],
      },
      {
        id: 'row-c',
        prompt: 'Wind or water can move seeds.',
        correctChoiceId: 'text2',
        options: [
          choice('both', 'Both texts'),
          choice('text1', 'Text 1 only'),
          choice('text2', 'Text 2 only'),
        ],
      },
    ],
  }),
]
