import type { ReadingQuestion } from '../../../../types'
import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from '../variableVowelsOoEa/questionFactories'
import {
  COMMON_SUFFIX_CONTENT_VERSION,
  COMMON_SUFFIX_LESSON_IDS,
  COMMON_SUFFIX_PASSAGE_IDS,
  COMMON_SUFFIX_QUESTION_IDS,
} from './ids'

const common = {
  benchmarkReference: 'ELA.2.F.1.3d',
  skillIdentifier: 'g2-word-forge-word-practice',
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'Word Forge',
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2',
  contentVersion: COMMON_SUFFIX_CONTENT_VERSION,
  reviewStatus: 'DRAFT' as const,
}

export const guidedQuestions: ReadingQuestion[] = [
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.trailCleanup,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedActionEndings,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-action-endings-1',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedActionEndings[0],
    prompt: 'Which word has the suffix -ing and shows the action is happening now?',
    explanation: 'Helping ends with -ing, and help is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['helping-choice'],
    targetVocabulary: ['helping', 'quickly', 'faster', 'smallest'],
    soundOutChunks: ['help', 'ing'],
    tags: ['common-suffixes', 'suffix-ing', 'base-word'],
    choices: [
      { id: 'faster-choice', text: 'faster' },
      { id: 'quickly-choice', text: 'quickly' },
      { id: 'smallest-choice', text: 'smallest' },
      { id: 'helping-choice', text: 'helping' },
    ],
    correctChoiceIds: ['helping-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.trailCleanup,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedActionEndings,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-action-endings-2',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedActionEndings[1],
    prompt: 'Which word has the suffix -er and compares two things?',
    explanation: 'Faster ends with -er, and fast is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['faster-choice'],
    targetVocabulary: ['helping', 'quickly', 'faster', 'smallest'],
    soundOutChunks: ['fast', 'er'],
    tags: ['common-suffixes', 'suffix-er-est', 'base-word'],
    choices: [
      { id: 'helping-choice', text: 'helping' },
      { id: 'smallest-choice', text: 'smallest' },
      { id: 'quickly-choice', text: 'quickly' },
      { id: 'faster-choice', text: 'faster' },
    ],
    correctChoiceIds: ['faster-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.trailCleanup,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedActionEndings,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-action-endings-3',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedActionEndings[2],
    prompt: 'Choose all the words in the trail passage that have suffixes.',
    explanation: 'Helping, quickly, faster, and smallest all have suffixes you can see.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['helping-choice', 'quickly-choice', 'faster-choice', 'smallest-choice'],
    targetVocabulary: ['helping', 'quickly', 'faster', 'smallest'],
    soundOutChunks: ['help', 'ing', 'quick', 'ly', 'fast', 'er', 'small', 'est'],
    tags: ['common-suffixes', 'suffix-ing', 'suffix-ly', 'suffix-er-est', 'base-word'],
    choices: [
      { id: 'helping-choice', text: 'helping' },
      { id: 'quickly-choice', text: 'quickly' },
      { id: 'faster-choice', text: 'faster' },
      { id: 'smallest-choice', text: 'smallest' },
      { id: 'careful-choice', text: 'careful' },
    ],
    correctChoiceIds: ['helping-choice', 'quickly-choice', 'faster-choice', 'smallest-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.trailCleanup,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedActionEndings,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-action-endings-4',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedActionEndings[3],
    prompt: 'Select the sentence that tells about the smallest sticks.',
    explanation: 'The second sentence says the team sorted the smallest sticks.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['suffix-trail-2'],
    targetVocabulary: ['smallest', 'faster'],
    soundOutChunks: ['small', 'est'],
    tags: ['common-suffixes', 'suffix-er-est'],
    selectableSegments: [
      { id: 'suffix-trail-1', text: 'On the trail cleanup, the children were helping quickly.' },
      { id: 'suffix-trail-2', text: 'They moved faster than before and sorted the smallest sticks.' },
      { id: 'suffix-trail-3', text: 'The team felt careful and calm.' },
    ],
    correctSegmentIds: ['suffix-trail-2'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.trailCleanup,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedActionEndings,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-action-endings-5',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedActionEndings[4],
    prompt: 'Match each word to its split.',
    explanation: 'Each word matches the base word plus the suffix at the end.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['helping-split', 'quickly-split', 'faster-split', 'smallest-split'],
    targetVocabulary: ['helping', 'quickly', 'faster', 'smallest'],
    soundOutChunks: ['help', 'ing', 'quick', 'ly', 'fast', 'er', 'small', 'est'],
    tags: ['common-suffixes', 'suffix-ing', 'suffix-ly', 'suffix-er-est', 'base-word'],
    rows: [
      {
        id: 'helping-row',
        prompt: 'helping',
        correctChoiceId: 'helping-split',
        options: [
          { id: 'helping-split', text: 'help | ing' },
          { id: 'quickly-split', text: 'quick | ly' },
          { id: 'faster-split', text: 'fast | er' },
          { id: 'smallest-split', text: 'small | est' },
        ],
      },
      {
        id: 'quickly-row',
        prompt: 'quickly',
        correctChoiceId: 'quickly-split',
        options: [
          { id: 'faster-split-2', text: 'fast | er' },
          { id: 'quickly-split', text: 'quick | ly' },
          { id: 'smallest-split-2', text: 'small | est' },
          { id: 'helping-split-2', text: 'help | ing' },
        ],
      },
      {
        id: 'faster-row',
        prompt: 'faster',
        correctChoiceId: 'faster-split',
        options: [
          { id: 'smallest-split-3', text: 'small | est' },
          { id: 'faster-split', text: 'fast | er' },
          { id: 'helping-split-3', text: 'help | ing' },
          { id: 'quickly-split-2', text: 'quick | ly' },
        ],
      },
      {
        id: 'smallest-row',
        prompt: 'smallest',
        correctChoiceId: 'smallest-split',
        options: [
          { id: 'helping-split-4', text: 'help | ing' },
          { id: 'smallest-split', text: 'small | est' },
          { id: 'quickly-split-3', text: 'quick | ly' },
          { id: 'faster-split-3', text: 'fast | er' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.weatherWatch,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedMeaningEndings,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-meaning-endings-1',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedMeaningEndings[0],
    prompt: 'Which word has the suffix -est and compares three or more things?',
    explanation: 'Calmest ends with -est, and calm is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['calmest-choice'],
    targetVocabulary: ['calmest', 'kindly', 'hopeful', 'warmer'],
    soundOutChunks: ['calm', 'est'],
    tags: ['common-suffixes', 'suffix-er-est', 'base-word'],
    choices: [
      { id: 'warmer-choice', text: 'warmer' },
      { id: 'hopeful-choice', text: 'hopeful' },
      { id: 'kindly-choice', text: 'kindly' },
      { id: 'calmest-choice', text: 'calmest' },
    ],
    correctChoiceIds: ['calmest-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.weatherWatch,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedMeaningEndings,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-meaning-endings-2',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedMeaningEndings[1],
    prompt: 'Which word has the suffix -ful and means full of hope?',
    explanation: 'Hopeful ends with -ful, and hope is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['hopeful-choice'],
    targetVocabulary: ['calmest', 'kindly', 'hopeful', 'warmer'],
    soundOutChunks: ['hope', 'ful'],
    tags: ['common-suffixes', 'suffix-ful-less', 'base-word'],
    choices: [
      { id: 'kindly-choice', text: 'kindly' },
      { id: 'warmer-choice', text: 'warmer' },
      { id: 'calmest-choice', text: 'calmest' },
      { id: 'hopeful-choice', text: 'hopeful' },
    ],
    correctChoiceIds: ['hopeful-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.weatherWatch,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedMeaningEndings,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-meaning-endings-3',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedMeaningEndings[2],
    prompt: 'Choose all the words in the weather passage that have visible suffixes.',
    explanation: 'Calmer, kindly, hopeful, and warmer all have suffixes you can see.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['calmer-choice', 'kindly-choice', 'hopeful-choice', 'warmer-choice'],
    targetVocabulary: ['calmer', 'kindly', 'hopeful', 'warmer'],
    soundOutChunks: ['calm', 'er', 'kind', 'ly', 'hope', 'ful', 'warm', 'er'],
    tags: ['common-suffixes', 'suffix-er-est', 'suffix-ful-less', 'suffix-ly', 'base-word'],
    choices: [
      { id: 'calmer-choice', text: 'calmer' },
      { id: 'kindly-choice', text: 'kindly' },
      { id: 'hopeful-choice', text: 'hopeful' },
      { id: 'warmer-choice', text: 'warmer' },
      { id: 'clear-choice', text: 'clear' },
    ],
    correctChoiceIds: ['calmer-choice', 'kindly-choice', 'hopeful-choice', 'warmer-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.weatherWatch,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedMeaningEndings,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-meaning-endings-4',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedMeaningEndings[3],
    prompt: 'Select the sentence that tells about the warmer wind.',
    explanation: 'The third sentence says the warmer wind passed.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['suffix-weather-3'],
    targetVocabulary: ['calmer', 'kindly', 'hopeful', 'warmer'],
    soundOutChunks: ['warm', 'er'],
    tags: ['common-suffixes', 'suffix-er-est'],
    selectableSegments: [
      { id: 'suffix-weather-1', text: 'During the weather watch, the sky stayed clear.' },
      { id: 'suffix-weather-2', text: 'The reporter wrote the calmer note and the children listened kindly.' },
      { id: 'suffix-weather-3', text: 'A hopeful sign appeared when the warmer wind passed.' },
    ],
    correctSegmentIds: ['suffix-weather-3'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.weatherWatch,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedMeaningEndings,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-meaning-endings-5',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedMeaningEndings[4],
    prompt: 'Match each word to its split.',
    explanation: 'Each word matches the base word plus the suffix at the end.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['calmer-split', 'kindly-split', 'hopeful-split', 'warmer-split'],
    targetVocabulary: ['calmer', 'kindly', 'hopeful', 'warmer'],
    soundOutChunks: ['calm', 'er', 'kind', 'ly', 'hope', 'ful', 'warm', 'er'],
    tags: ['common-suffixes', 'suffix-er-est', 'suffix-ful-less', 'suffix-ly', 'base-word'],
    rows: [
      {
        id: 'calmer-row',
        prompt: 'calmer',
        correctChoiceId: 'calmer-split',
        options: [
          { id: 'hopeful-split', text: 'hope | ful' },
          { id: 'kindly-split', text: 'kind | ly' },
          { id: 'warmer-split', text: 'warm | er' },
          { id: 'calmer-split', text: 'calm | er' },
        ],
      },
      {
        id: 'kindly-row',
        prompt: 'kindly',
        correctChoiceId: 'kindly-split',
        options: [
          { id: 'calmer-split-2', text: 'calm | er' },
          { id: 'warmer-split-2', text: 'warm | er' },
          { id: 'hopeful-split-2', text: 'hope | ful' },
          { id: 'kindly-split', text: 'kind | ly' },
        ],
      },
      {
        id: 'hopeful-row',
        prompt: 'hopeful',
        correctChoiceId: 'hopeful-split',
        options: [
          { id: 'warmer-split-3', text: 'warm | er' },
          { id: 'hopeful-split', text: 'hope | ful' },
          { id: 'kindly-split-2', text: 'kind | ly' },
          { id: 'calmer-split-3', text: 'calm | er' },
        ],
      },
      {
        id: 'warmer-row',
        prompt: 'warmer',
        correctChoiceId: 'warmer-split',
        options: [
          { id: 'kindly-split-3', text: 'kind | ly' },
          { id: 'warmer-split', text: 'warm | er' },
          { id: 'hopeful-split-3', text: 'hope | ful' },
          { id: 'calmer-split-4', text: 'calm | er' },
        ],
      },
    ],
  }),
]

