import type { ReadingQuestion } from '../../../../types'
import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from '../variableVowelsOoEa/questionFactories'
import {
  COMMON_SUFFIX_CONTENT_VERSION,
  COMMON_SUFFIX_LESSON_IDS,
  COMMON_SUFFIX_PASSAGE_IDS,
  COMMON_SUFFIX_QUESTION_IDS,
} from './ids'

const common = {
  benchmarkReference: 'ELA.2.F.1.3d',
  skillIdentifier: 'g2-word-forge-word-practice',
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'Word Forge',
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2',
  contentVersion: COMMON_SUFFIX_CONTENT_VERSION,
  reviewStatus: 'DRAFT' as const,
}

export const buildingBlockQuestions: ReadingQuestion[] = [
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.gardenBed,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedBaseAndEnding,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-base-and-ending-1',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedBaseAndEnding[0],
    prompt: 'Which word has the suffix -ed and tells about something that already happened?',
    explanation: 'Planted ends with -ed, and plant is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['planted-choice'],
    targetVocabulary: ['planted', 'watered', 'helped', 'helpful'],
    soundOutChunks: ['plant', 'ed'],
    tags: ['common-suffixes', 'suffix-ed', 'base-word'],
    choices: [
      { id: 'helpful-choice', text: 'helpful' },
      { id: 'watered-choice', text: 'watered' },
      { id: 'plants-choice', text: 'plants' },
      { id: 'planted-choice', text: 'planted' },
    ],
    correctChoiceIds: ['planted-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.gardenBed,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedBaseAndEnding,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-base-and-ending-2',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedBaseAndEnding[1],
    prompt: 'Which word has the suffix -ful and means full of help?',
    explanation: 'Helpful ends with -ful, and help is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['helpful-choice'],
    targetVocabulary: ['planted', 'watered', 'helped', 'helpful'],
    soundOutChunks: ['help', 'ful'],
    tags: ['common-suffixes', 'suffix-ful-less', 'base-word'],
    choices: [
      { id: 'planted-choice', text: 'planted' },
      { id: 'careful-choice', text: 'careful' },
      { id: 'helpful-choice', text: 'helpful' },
      { id: 'boxes-choice', text: 'boxes' },
    ],
    correctChoiceIds: ['helpful-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.gardenBed,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedBaseAndEnding,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-base-and-ending-3',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedBaseAndEnding[2],
    prompt: 'Choose all the words in the garden passage that have suffixes.',
    explanation: 'Plants, planted, watered, helped, and helpful all have suffixes you can see.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['plants-choice', 'planted-choice', 'watered-choice', 'helped-choice', 'helpful-choice'],
    targetVocabulary: ['plants', 'planted', 'watered', 'helped', 'helpful'],
    soundOutChunks: ['plant', 's', 'plant', 'ed', 'water', 'ed', 'help', 'ed', 'help', 'ful'],
    tags: ['common-suffixes', 'suffix-s-es', 'suffix-ed', 'suffix-ful-less', 'base-word'],
    choices: [
      { id: 'plants-choice', text: 'plants' },
      { id: 'planted-choice', text: 'planted' },
      { id: 'watered-choice', text: 'watered' },
      { id: 'helped-choice', text: 'helped' },
      { id: 'helpful-choice', text: 'helpful' },
    ],
    correctChoiceIds: ['plants-choice', 'planted-choice', 'watered-choice', 'helped-choice', 'helpful-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.gardenBed,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedBaseAndEnding,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-base-and-ending-4',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedBaseAndEnding[3],
    prompt: 'Select the sentence that tells about the team working carefully.',
    explanation: 'The third sentence says the team worked carefully.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['suffix-garden-3'],
    targetVocabulary: ['carefully', 'helpful'],
    soundOutChunks: ['care', 'ful', 'ly'],
    tags: ['common-suffixes', 'suffix-ly'],
    selectableSegments: [
      { id: 'suffix-garden-1', text: 'At the garden, the class planted seeds and watered plants.' },
      { id: 'suffix-garden-2', text: 'A helpful helper carried boxes of tools and cleaned the table.' },
      { id: 'suffix-garden-3', text: 'The team worked carefully.' },
    ],
    correctSegmentIds: ['suffix-garden-3'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.gardenBed,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedBaseAndEnding,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-base-and-ending-5',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedBaseAndEnding[4],
    prompt: 'Match each word to its base word.',
    explanation: 'Each word matches the base word before the suffix is added.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['plant-base', 'water-base-2', 'help-base-3', 'help-base-4'],
    targetVocabulary: ['planted', 'watered', 'helped', 'helpful'],
    soundOutChunks: ['plant', 'ed', 'water', 'ed', 'help', 'ed', 'help', 'ful'],
    tags: ['common-suffixes', 'suffix-ed', 'suffix-ful-less', 'base-word'],
    rows: [
      {
        id: 'planted-row',
        prompt: 'planted',
        correctChoiceId: 'plant-base',
        options: [
          { id: 'helpful-base', text: 'help' },
          { id: 'water-base', text: 'water' },
          { id: 'plant-base', text: 'plant' },
          { id: 'care-base', text: 'care' },
        ],
      },
      {
        id: 'watered-row',
        prompt: 'watered',
        correctChoiceId: 'water-base-2',
        options: [
          { id: 'water-base-2', text: 'water' },
          { id: 'help-base-2', text: 'help' },
          { id: 'paint-base', text: 'paint' },
          { id: 'care-base-2', text: 'care' },
        ],
      },
      {
        id: 'helped-row',
        prompt: 'helped',
        correctChoiceId: 'help-base-3',
        options: [
          { id: 'help-base-3', text: 'help' },
          { id: 'box-base', text: 'box' },
          { id: 'water-base-3', text: 'water' },
          { id: 'sign-base', text: 'sign' },
        ],
      },
      {
        id: 'helpful-row',
        prompt: 'helpful',
        correctChoiceId: 'help-base-4',
        options: [
          { id: 'help-base-4', text: 'help' },
          { id: 'care-base-3', text: 'care' },
          { id: 'plant-base-2', text: 'plant' },
          { id: 'wish-base', text: 'wish' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.shelterCare,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedEndingSound,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-ending-sound-1',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedEndingSound[0],
    prompt: 'Which word ends with -es and means more than one box?',
    explanation: 'Boxes ends with -es, and box is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['boxes-choice'],
    targetVocabulary: ['boxes', 'dishes', 'softly', 'fearless'],
    soundOutChunks: ['box', 'es'],
    tags: ['common-suffixes', 'suffix-s-es', 'base-word'],
    choices: [
      { id: 'fearless-choice', text: 'fearless' },
      { id: 'softly-choice', text: 'softly' },
      { id: 'dishes-choice', text: 'dishes' },
      { id: 'boxes-choice', text: 'boxes' },
    ],
    correctChoiceIds: ['boxes-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.shelterCare,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedEndingSound,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-ending-sound-2',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedEndingSound[1],
    prompt: 'Which word has the suffix -less and means without fear?',
    explanation: 'Fearless ends with -less, and fear is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['fearless-choice'],
    targetVocabulary: ['boxes', 'dishes', 'softly', 'fearless'],
    soundOutChunks: ['fear', 'less'],
    tags: ['common-suffixes', 'suffix-ful-less', 'base-word'],
    choices: [
      { id: 'softly-choice', text: 'softly' },
      { id: 'boxes-choice', text: 'boxes' },
      { id: 'dishes-choice', text: 'dishes' },
      { id: 'fearless-choice', text: 'fearless' },
    ],
    correctChoiceIds: ['fearless-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.shelterCare,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedEndingSound,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-ending-sound-3',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedEndingSound[2],
    prompt: 'Choose all the words in the shelter passage that have visible suffixes.',
    explanation: 'Boxes, dishes, softly, and fearless all have suffixes you can see.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['boxes-choice', 'dishes-choice', 'softly-choice', 'fearless-choice'],
    targetVocabulary: ['boxes', 'dishes', 'softly', 'fearless'],
    soundOutChunks: ['box', 'es', 'dish', 'es', 'soft', 'ly', 'fear', 'less'],
    tags: ['common-suffixes', 'suffix-s-es', 'suffix-ly', 'suffix-ful-less', 'base-word'],
    choices: [
      { id: 'boxes-choice', text: 'boxes' },
      { id: 'dishes-choice', text: 'dishes' },
      { id: 'softly-choice', text: 'softly' },
      { id: 'fearless-choice', text: 'fearless' },
      { id: 'kind-choice', text: 'kind' },
    ],
    correctChoiceIds: ['boxes-choice', 'dishes-choice', 'softly-choice', 'fearless-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.shelterCare,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedEndingSound,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-ending-sound-4',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedEndingSound[3],
    prompt: 'Select the sentence that tells how the volunteer moved.',
    explanation: 'The second sentence says the volunteer walked softly.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['suffix-shelter-2'],
    targetVocabulary: ['softly', 'fearless'],
    soundOutChunks: ['soft', 'ly'],
    tags: ['common-suffixes', 'suffix-ly'],
    selectableSegments: [
      { id: 'suffix-shelter-1', text: 'At the shelter, boxes of blankets lined the table.' },
      { id: 'suffix-shelter-2', text: 'The kind volunteer carried dishes, cleaned bowls, and walked softly.' },
      { id: 'suffix-shelter-3', text: 'The dogs looked fearless and happy.' },
    ],
    correctSegmentIds: ['suffix-shelter-2'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.shelterCare,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.guidedEndingSound,
    activityIdentifier: 'activity-word-forge-common-suffixes-guided-ending-sound-5',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.guidedEndingSound[4],
    prompt: 'Match each word to its split.',
    explanation: 'Each word matches the base word plus the suffix at the end.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['boxes-split', 'dishes-split', 'softly-split', 'fearless-split'],
    targetVocabulary: ['boxes', 'dishes', 'softly', 'fearless'],
    soundOutChunks: ['box', 'es', 'dish', 'es', 'soft', 'ly', 'fear', 'less'],
    tags: ['common-suffixes', 'suffix-s-es', 'suffix-ly', 'suffix-ful-less', 'base-word'],
    rows: [
      {
        id: 'boxes-row',
        prompt: 'boxes',
        correctChoiceId: 'boxes-split',
        options: [
          { id: 'fearless-split', text: 'fear | less' },
          { id: 'softly-split', text: 'soft | ly' },
          { id: 'dishes-split', text: 'dish | es' },
          { id: 'boxes-split', text: 'box | es' },
        ],
      },
      {
        id: 'dishes-row',
        prompt: 'dishes',
        correctChoiceId: 'dishes-split',
        options: [
          { id: 'dishes-split', text: 'dish | es' },
          { id: 'boxes-split-2', text: 'box | es' },
          { id: 'softly-split-2', text: 'soft | ly' },
          { id: 'fearless-split-2', text: 'fear | less' },
        ],
      },
      {
        id: 'softly-row',
        prompt: 'softly',
        correctChoiceId: 'softly-split',
        options: [
          { id: 'boxes-split-3', text: 'box | es' },
          { id: 'softly-split', text: 'soft | ly' },
          { id: 'fearless-split-3', text: 'fear | less' },
          { id: 'dishes-split-2', text: 'dish | es' },
        ],
      },
      {
        id: 'fearless-row',
        prompt: 'fearless',
        correctChoiceId: 'fearless-split',
        options: [
          { id: 'fearless-split', text: 'fear | less' },
          { id: 'softly-split-3', text: 'soft | ly' },
          { id: 'boxes-split-4', text: 'box | es' },
          { id: 'dishes-split-3', text: 'dish | es' },
        ],
      },
    ],
  }),
]
