import type { ReadingQuestion } from '../../../../types'
import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from '../variableVowelsOoEa/questionFactories'
import {
  COMMON_SUFFIX_CONTENT_VERSION,
  COMMON_SUFFIX_LESSON_IDS,
  COMMON_SUFFIX_PASSAGE_IDS,
  COMMON_SUFFIX_QUESTION_IDS,
} from './ids'

const common = {
  benchmarkReference: 'ELA.2.F.1.3d',
  skillIdentifier: 'g2-word-forge-word-practice',
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'Word Forge',
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2',
  contentVersion: COMMON_SUFFIX_CONTENT_VERSION,
  reviewStatus: 'DRAFT' as const,
}

export const checkpointQuestions: ReadingQuestion[] = [
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.signPainting,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-a-1',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointA[0],
    prompt: 'Which word has the suffix -s or -es?',
    explanation: 'Signs ends with -s, and sign is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['signs-choice'],
    targetVocabulary: ['signs', 'painted', 'jumping', 'careless'],
    soundOutChunks: ['sign', 's'],
    tags: ['common-suffixes', 'suffix-s-es', 'base-word'],
    choices: [
      { id: 'painted-choice', text: 'painted' },
      { id: 'careless-choice', text: 'careless' },
      { id: 'jumping-choice', text: 'jumping' },
      { id: 'signs-choice', text: 'signs' },
    ],
    correctChoiceIds: ['signs-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.signPainting,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-a-2',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointA[1],
    prompt: 'Which word has the suffix -ed?',
    explanation: 'Painted ends with -ed, and paint is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['painted-choice'],
    targetVocabulary: ['signs', 'painted', 'jumping', 'careless'],
    soundOutChunks: ['paint', 'ed'],
    tags: ['common-suffixes', 'suffix-ed', 'base-word'],
    choices: [
      { id: 'careless-choice', text: 'careless' },
      { id: 'signs-choice', text: 'signs' },
      { id: 'jumping-choice', text: 'jumping' },
      { id: 'painted-choice', text: 'painted' },
    ],
    correctChoiceIds: ['painted-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.scienceTools,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-a-3',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointA[2],
    prompt: 'Which word has the suffix -ing?',
    explanation: 'Jumping ends with -ing, and jump is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['jumping-choice'],
    targetVocabulary: ['wanted', 'jumping', 'cleanest', 'kinder'],
    soundOutChunks: ['jump', 'ing'],
    tags: ['common-suffixes', 'suffix-ing', 'base-word'],
    choices: [
      { id: 'cleanest-choice', text: 'cleanest' },
      { id: 'kinder-choice', text: 'kinder' },
      { id: 'wanted-choice', text: 'wanted' },
      { id: 'jumping-choice', text: 'jumping' },
    ],
    correctChoiceIds: ['jumping-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.pantryHelp,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-a-4',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointA[3],
    prompt: 'Which word has the suffix -ful or -less?',
    explanation: 'Careless ends with -less, and care is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['careless-choice'],
    targetVocabulary: ['wishes', 'cleaned', 'fastest', 'careful'],
    soundOutChunks: ['care', 'less'],
    tags: ['common-suffixes', 'suffix-ful-less', 'base-word'],
    choices: [
      { id: 'wishes-choice', text: 'wishes' },
      { id: 'careful-choice', text: 'careful' },
      { id: 'cleaned-choice', text: 'cleaned' },
      { id: 'careless-choice', text: 'careless' },
    ],
    correctChoiceIds: ['careless-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.pantryHelp,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-a-5',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointA[4],
    prompt: 'Choose all the words in the checkpoint passages that compare two or more things.',
    explanation: 'Smaller, kinder, fastest, and cleanest all compare or describe an end point.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['smaller-choice', 'kinder-choice', 'fastest-choice', 'cleanest-choice'],
    targetVocabulary: ['smaller', 'kinder', 'fastest', 'cleanest'],
    soundOutChunks: ['small', 'er', 'kind', 'er', 'fast', 'est', 'clean', 'est'],
    tags: ['common-suffixes', 'suffix-er-est', 'base-word'],
    choices: [
      { id: 'smaller-choice', text: 'smaller' },
      { id: 'kinder-choice', text: 'kinder' },
      { id: 'fastest-choice', text: 'fastest' },
      { id: 'cleanest-choice', text: 'cleanest' },
      { id: 'careful-choice', text: 'careful' },
    ],
    correctChoiceIds: ['smaller-choice', 'kinder-choice', 'fastest-choice', 'cleanest-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.pantryHelp,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-a-6',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointA[5],
    prompt: 'Select the sentence that tells about something being done quickly.',
    explanation: 'The third sentence says the spill was wiped quickly.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['suffix-pantry-3'],
    targetVocabulary: ['quickly', 'fastest'],
    soundOutChunks: ['quick', 'ly'],
    tags: ['common-suffixes', 'suffix-ly'],
    selectableSegments: [
      { id: 'suffix-pantry-1', text: 'At the pantry, the children carried careful bags and cleaned the shelves.' },
      { id: 'suffix-pantry-2', text: 'The fastest cart rolled past the hopeful signs, and the family made wishes for a full shelf.' },
      { id: 'suffix-pantry-3', text: 'A careless spill was wiped quickly.' },
    ],
    correctSegmentIds: ['suffix-pantry-3'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.signPainting,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-a-7',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointA[6],
    prompt: 'Match each word to its base word.',
    explanation: 'Each word matches the base word after the suffix is removed.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['sign-base', 'paint-base', 'jump-base', 'help-base'],
    targetVocabulary: ['signs', 'painted', 'jumping', 'helpful'],
    soundOutChunks: ['sign', 's', 'paint', 'ed', 'jump', 'ing', 'help', 'ful'],
    tags: ['common-suffixes', 'suffix-s-es', 'suffix-ed', 'suffix-ing', 'suffix-ful-less', 'base-word'],
    rows: [
      {
        id: 'signs-row',
        prompt: 'signs',
        correctChoiceId: 'sign-base',
        options: [
          { id: 'help-base', text: 'help' },
          { id: 'sign-base', text: 'sign' },
          { id: 'paint-base', text: 'paint' },
          { id: 'jump-base', text: 'jump' },
        ],
      },
      {
        id: 'painted-row',
        prompt: 'painted',
        correctChoiceId: 'paint-base',
        options: [
          { id: 'paint-base', text: 'paint' },
          { id: 'jump-base-2', text: 'jump' },
          { id: 'sign-base-2', text: 'sign' },
          { id: 'help-base-2', text: 'help' },
        ],
      },
      {
        id: 'jumping-row',
        prompt: 'jumping',
        correctChoiceId: 'jump-base',
        options: [
          { id: 'jump-base', text: 'jump' },
          { id: 'help-base-3', text: 'help' },
          { id: 'sign-base-3', text: 'sign' },
          { id: 'paint-base-3', text: 'paint' },
        ],
      },
      {
        id: 'helpful-row',
        prompt: 'helpful',
        correctChoiceId: 'help-base-4',
        options: [
          { id: 'help-base-4', text: 'help' },
          { id: 'paint-base-4', text: 'paint' },
          { id: 'jump-base-4', text: 'jump' },
          { id: 'sign-base-4', text: 'sign' },
        ],
      },
    ],
  }),

  createMultipleChoiceQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.scienceTools,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-b-1',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointB[0],
    prompt: 'Which word has the suffix -s or -es?',
    explanation: 'Wishes ends with -es, and wish is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['wishes-choice'],
    targetVocabulary: ['wishes', 'wanted', 'jumping', 'cleanest'],
    soundOutChunks: ['wish', 'es'],
    tags: ['common-suffixes', 'suffix-s-es', 'base-word'],
    choices: [
      { id: 'cleanest-choice', text: 'cleanest' },
      { id: 'jumping-choice', text: 'jumping' },
      { id: 'wanted-choice', text: 'wanted' },
      { id: 'wishes-choice', text: 'wishes' },
    ],
    correctChoiceIds: ['wishes-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.scienceTools,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-b-2',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointB[1],
    prompt: 'Which word has the suffix -ed?',
    explanation: 'Wanted ends with -ed, and want is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['wanted-choice'],
    targetVocabulary: ['wishes', 'wanted', 'jumping', 'cleanest'],
    soundOutChunks: ['want', 'ed'],
    tags: ['common-suffixes', 'suffix-ed', 'base-word'],
    choices: [
      { id: 'jumping-choice', text: 'jumping' },
      { id: 'cleanest-choice', text: 'cleanest' },
      { id: 'wishes-choice', text: 'wishes' },
      { id: 'wanted-choice', text: 'wanted' },
    ],
    correctChoiceIds: ['wanted-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.scienceTools,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-b-3',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointB[2],
    prompt: 'Which word has the suffix -ing?',
    explanation: 'Jumping ends with -ing, and jump is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['jumping-choice'],
    targetVocabulary: ['wishes', 'wanted', 'jumping', 'cleanest'],
    soundOutChunks: ['jump', 'ing'],
    tags: ['common-suffixes', 'suffix-ing', 'base-word'],
    choices: [
      { id: 'wanted-choice', text: 'wanted' },
      { id: 'cleanest-choice', text: 'cleanest' },
      { id: 'wishes-choice', text: 'wishes' },
      { id: 'jumping-choice', text: 'jumping' },
    ],
    correctChoiceIds: ['jumping-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.pantryHelp,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-b-4',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointB[3],
    prompt: 'Which word has the suffix -ful or -less?',
    explanation: 'Careful ends with -ful, and care is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['careful-choice'],
    targetVocabulary: ['careful', 'cleaned', 'fastest', 'wishes'],
    soundOutChunks: ['care', 'ful'],
    tags: ['common-suffixes', 'suffix-ful-less', 'base-word'],
    choices: [
      { id: 'wishes-choice', text: 'wishes' },
      { id: 'fastest-choice', text: 'fastest' },
      { id: 'cleaned-choice', text: 'cleaned' },
      { id: 'careful-choice', text: 'careful' },
    ],
    correctChoiceIds: ['careful-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.pantryHelp,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-b-5',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointB[4],
    prompt: 'Choose all the words in the checkpoint passages that compare two or more things.',
    explanation: 'Kinder, fastest, cleanest, and warmer all compare or describe degrees.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['kinder-choice', 'fastest-choice', 'cleanest-choice', 'warmer-choice'],
    targetVocabulary: ['kinder', 'fastest', 'cleanest', 'warmer'],
    soundOutChunks: ['kind', 'er', 'fast', 'est', 'clean', 'est', 'warm', 'er'],
    tags: ['common-suffixes', 'suffix-er-est', 'base-word'],
    choices: [
      { id: 'kinder-choice', text: 'kinder' },
      { id: 'fastest-choice', text: 'fastest' },
      { id: 'cleanest-choice', text: 'cleanest' },
      { id: 'warmer-choice', text: 'warmer' },
      { id: 'careful-choice', text: 'careful' },
    ],
    correctChoiceIds: ['kinder-choice', 'fastest-choice', 'cleanest-choice', 'warmer-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.pantryHelp,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-b-6',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointB[5],
    prompt: 'Select the sentence that tells about something being done quickly.',
    explanation: 'The third sentence says the spill was wiped quickly.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['suffix-pantry-3'],
    targetVocabulary: ['quickly', 'fastest'],
    soundOutChunks: ['quick', 'ly'],
    tags: ['common-suffixes', 'suffix-ly'],
    selectableSegments: [
      { id: 'suffix-pantry-1', text: 'At the pantry, the children carried careful bags and cleaned the shelves.' },
      { id: 'suffix-pantry-2', text: 'The fastest cart rolled past the hopeful signs, and the family made wishes for a full shelf.' },
      { id: 'suffix-pantry-3', text: 'A careless spill was wiped quickly.' },
    ],
    correctSegmentIds: ['suffix-pantry-3'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.scienceTools,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-b-7',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointB[6],
    prompt: 'Match each word to its base word.',
    explanation: 'Each word matches the base word after the suffix is removed.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['wishes-base', 'wanted-base', 'jumping-base', 'cleanest-base'],
    targetVocabulary: ['wishes', 'wanted', 'jumping', 'cleanest'],
    soundOutChunks: ['wish', 'es', 'want', 'ed', 'jump', 'ing', 'clean', 'est'],
    tags: ['common-suffixes', 'suffix-s-es', 'suffix-ed', 'suffix-ing', 'suffix-er-est', 'base-word'],
    rows: [
      {
        id: 'wishes-row',
        prompt: 'wishes',
        correctChoiceId: 'wishes-base',
        options: [
          { id: 'cleanest-base', text: 'clean' },
          { id: 'jumping-base', text: 'jump' },
          { id: 'wishes-base', text: 'wish' },
          { id: 'wanted-base', text: 'want' },
        ],
      },
      {
        id: 'wanted-row',
        prompt: 'wanted',
        correctChoiceId: 'want-base',
        options: [
          { id: 'jumping-base-2', text: 'jump' },
          { id: 'want-base', text: 'want' },
          { id: 'cleanest-base-2', text: 'clean' },
          { id: 'wish-base-2', text: 'wish' },
        ],
      },
      {
        id: 'jumping-row',
        prompt: 'jumping',
        correctChoiceId: 'jump-base',
        options: [
          { id: 'wish-base-3', text: 'wish' },
          { id: 'cleanest-base-3', text: 'clean' },
          { id: 'jump-base', text: 'jump' },
          { id: 'want-base-2', text: 'want' },
        ],
      },
      {
        id: 'cleanest-row',
        prompt: 'cleanest',
        correctChoiceId: 'clean-base',
        options: [
          { id: 'clean-base', text: 'clean' },
          { id: 'wish-base-4', text: 'wish' },
          { id: 'jump-base-2', text: 'jump' },
          { id: 'want-base-3', text: 'want' },
        ],
      },
    ],
  }),

  createMultipleChoiceQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.signPainting,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-c-1',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointC[0],
    prompt: 'Which word has the suffix -s or -es?',
    explanation: 'Wishes ends with -es, and wish is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['wishes-choice'],
    targetVocabulary: ['wishes', 'cleaned', 'fastest', 'careless'],
    soundOutChunks: ['wish', 'es'],
    tags: ['common-suffixes', 'suffix-s-es', 'base-word'],
    choices: [
      { id: 'fastest-choice', text: 'fastest' },
      { id: 'careless-choice', text: 'careless' },
      { id: 'cleaned-choice', text: 'cleaned' },
      { id: 'wishes-choice', text: 'wishes' },
    ],
    correctChoiceIds: ['wishes-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.signPainting,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-c-2',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointC[1],
    prompt: 'Which word has the suffix -ed?',
    explanation: 'Cleaned ends with -ed, and clean is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['cleaned-choice'],
    targetVocabulary: ['wishes', 'cleaned', 'fastest', 'careless'],
    soundOutChunks: ['clean', 'ed'],
    tags: ['common-suffixes', 'suffix-ed', 'base-word'],
    choices: [
      { id: 'careless-choice', text: 'careless' },
      { id: 'wishes-choice', text: 'wishes' },
      { id: 'fastest-choice', text: 'fastest' },
      { id: 'cleaned-choice', text: 'cleaned' },
    ],
    correctChoiceIds: ['cleaned-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.signPainting,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-c-3',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointC[2],
    prompt: 'Which word has the suffix -ing?',
    explanation: 'Jumping ends with -ing, and jump is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['jumping-choice'],
    targetVocabulary: ['jumping', 'smaller', 'hopeful', 'careless'],
    soundOutChunks: ['jump', 'ing'],
    tags: ['common-suffixes', 'suffix-ing', 'base-word'],
    choices: [
      { id: 'smaller-choice', text: 'smaller' },
      { id: 'hopeful-choice', text: 'hopeful' },
      { id: 'careless-choice', text: 'careless' },
      { id: 'jumping-choice', text: 'jumping' },
    ],
    correctChoiceIds: ['jumping-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.signPainting,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-c-4',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointC[3],
    prompt: 'Which word has the suffix -ful or -less?',
    explanation: 'Careless ends with -less, and care is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['careless-choice'],
    targetVocabulary: ['jumping', 'smaller', 'hopeful', 'careless'],
    soundOutChunks: ['care', 'less'],
    tags: ['common-suffixes', 'suffix-ful-less', 'base-word'],
    choices: [
      { id: 'hopeful-choice', text: 'hopeful' },
      { id: 'smaller-choice', text: 'smaller' },
      { id: 'jumping-choice', text: 'jumping' },
      { id: 'careless-choice', text: 'careless' },
    ],
    correctChoiceIds: ['careless-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.pantryHelp,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-c-5',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointC[4],
    prompt: 'Choose all the words in the checkpoint passages that compare two or more things.',
    explanation: 'Smaller, faster, cleanest, and kinder all compare or describe degrees.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['smaller-choice', 'fastest-choice', 'cleanest-choice', 'kinder-choice'],
    targetVocabulary: ['smaller', 'fastest', 'cleanest', 'kinder'],
    soundOutChunks: ['small', 'er', 'fast', 'est', 'clean', 'est', 'kind', 'er'],
    tags: ['common-suffixes', 'suffix-er-est', 'base-word'],
    choices: [
      { id: 'smaller-choice', text: 'smaller' },
      { id: 'fastest-choice', text: 'fastest' },
      { id: 'cleanest-choice', text: 'cleanest' },
      { id: 'kinder-choice', text: 'kinder' },
      { id: 'careful-choice', text: 'careful' },
    ],
    correctChoiceIds: ['smaller-choice', 'fastest-choice', 'cleanest-choice', 'kinder-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.pantryHelp,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-c-6',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointC[5],
    prompt: 'Select the sentence that tells about something being done quickly.',
    explanation: 'The third sentence says the spill was wiped quickly.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['suffix-pantry-3'],
    targetVocabulary: ['quickly', 'fastest'],
    soundOutChunks: ['quick', 'ly'],
    tags: ['common-suffixes', 'suffix-ly'],
    selectableSegments: [
      { id: 'suffix-pantry-1', text: 'At the pantry, the children carried careful bags and cleaned the shelves.' },
      { id: 'suffix-pantry-2', text: 'The fastest cart rolled past the hopeful signs, and the family made wishes for a full shelf.' },
      { id: 'suffix-pantry-3', text: 'A careless spill was wiped quickly.' },
    ],
    correctSegmentIds: ['suffix-pantry-3'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 6,
    passageIdentifier: COMMON_SUFFIX_PASSAGE_IDS.pantryHelp,
    lessonIdentifier: COMMON_SUFFIX_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-common-suffixes-checkpoint-c-7',
    questionIdentifier: COMMON_SUFFIX_QUESTION_IDS.checkpointC[6],
    prompt: 'Match each word to its base word.',
    explanation: 'Each word matches the base word after the suffix is removed.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['wish-base', 'clean-base-2', 'fast-base', 'care-base'],
    targetVocabulary: ['wishes', 'cleaned', 'fastest', 'careful'],
    soundOutChunks: ['wish', 'es', 'clean', 'ed', 'fast', 'est', 'care', 'ful'],
    tags: ['common-suffixes', 'suffix-s-es', 'suffix-ed', 'suffix-er-est', 'suffix-ful-less', 'base-word'],
    rows: [
      {
        id: 'wishes-row',
        prompt: 'wishes',
        correctChoiceId: 'wish-base',
        options: [
          { id: 'clean-base', text: 'clean' },
          { id: 'care-base', text: 'care' },
          { id: 'wish-base', text: 'wish' },
          { id: 'fast-base', text: 'fast' },
        ],
      },
      {
        id: 'cleaned-row',
        prompt: 'cleaned',
        correctChoiceId: 'clean-base-2',
        options: [
          { id: 'care-base-2', text: 'care' },
          { id: 'clean-base-2', text: 'clean' },
          { id: 'wish-base-2', text: 'wish' },
          { id: 'fast-base-2', text: 'fast' },
        ],
      },
      {
        id: 'fastest-row',
        prompt: 'fastest',
        correctChoiceId: 'fast-base',
        options: [
          { id: 'wish-base-3', text: 'wish' },
          { id: 'care-base-3', text: 'care' },
          { id: 'fast-base', text: 'fast' },
          { id: 'clean-base-3', text: 'clean' },
        ],
      },
      {
        id: 'careful-row',
        prompt: 'careful',
        correctChoiceId: 'care-base',
        options: [
          { id: 'fast-base-3', text: 'fast' },
          { id: 'wish-base-4', text: 'wish' },
          { id: 'clean-base-4', text: 'clean' },
          { id: 'care-base', text: 'care' },
        ],
      },
    ],
  }),
]
