import type { Passage, WordSupportTarget } from '../../../../types'
import {
  FLUENCY_PRACTICE_CONTENT_VERSION,
  FLUENCY_PRACTICE_PASSAGE_IDS,
  FLUENCY_PRACTICE_TARGET_IDS,
} from './ids'

function supportTarget(spec: {
  targetId: string
  passageId: string
  sentenceId: string
  surfaceWord: string
  displayChunks: string[]
  spokenChunks: string[]
  focusIndices: number[]
  blendSpeechText: string
  wholeWordSpeechText: string
  sentenceSpeechText: string
}): WordSupportTarget {
  return {
    targetId: spec.targetId,
    passageId: spec.passageId,
    sentenceId: spec.sentenceId,
    surfaceWord: spec.surfaceWord,
    focusParts: spec.displayChunks.map((chunk, index) => ({
      text: chunk,
      emphasis: spec.focusIndices.includes(index),
    })),
    displayChunks: spec.displayChunks.map((chunk) => ({ displayText: chunk, speechText: chunk })),
    spokenChunks: spec.spokenChunks.map((chunk) => ({ displayText: chunk, speechText: chunk })),
    blendSpeechText: spec.blendSpeechText,
    wholeWordSpeechText: spec.wholeWordSpeechText,
    sentenceSpeechText: spec.sentenceSpeechText,
    reviewStatus: 'DRAFT',
    contentVersion: FLUENCY_PRACTICE_CONTENT_VERSION,
  }
}

const weatherPassageText = [
  'At the weather table, the host smiled and said, "Clouds are moving in, but the morning is calm."',
  'She pointed to the chart, then read the note again.',
  '"Will the wind stay gentle?" she asked.',
  'The class watched the map quietly.',
  'One student said, "Let\'s reread the page before we leave!"',
].join(' ')

const trailPassageText = [
  'On the nature trail, the group unpacked a small lunch and a helpful map.',
  'They sat near a stable bench and listened for birds.',
  'A ranger said, "Read the sign carefully, then look for the blue feather."',
  'The children smiled, checked the path, and moved on together.',
].join(' ')

const gardenPassageText = [
  'At the community garden, the leader gave three steps: water, weed, and wait.',
  'The children carried a bundle of gloves and moved carefully between the rows.',
  '"Can you find the tiny sprouts?" she asked.',
  'The team smiled and worked quickly.',
  'Soon the table near the gate held fresh herbs and a sign that said, "Please share!"',
].join(' ')

const museumPassageText = [
  'At the museum, the guide said, "This room has a knight\'s helmet, a brass comb, and a map of an island."',
  'A child asked, "Is the ghost story real?"',
  'The guide laughed softly and said, "It is only a story card, but it still makes readers curious!"',
  'The group moved from one case to the next and stopped to look closely.',
].join(' ')

const animalCarePassageText = [
  'At the animal-care center, the helper lit a candle in a safe jar so the room stayed warm.',
  'She showed how to hold a bottle with both hands and move slowly.',
  '"Did the pup drink?" asked one child.',
  '"Yes," said the helper, "and the pup feels safe and calm."',
  'The team checked the stable crate and smiled.',
].join(' ')

const sciencePassageText = [
  'During the science demonstration, the teacher said, "Preheat the lamp board, then watch what changes."',
  'The class used a question card, wrote one careful note, and compared the results.',
  '"That is exciting!" one student shouted.',
  'Another student replied, "Let\'s review the steps and help each other."',
].join(' ')

const libraryPassageText = [
  'At the library event, a librarian said, "Read the flyer, then join the bubble parade!"',
  'The children lined up near a quiet table and picked a book that could be read again.',
  'One child whispered, "I may misspell this title, so I will check it."',
  'The librarian nodded and said, "That is a helpful plan."',
].join(' ')

export const grade2WordForgeFluencyPracticePassages: Passage[] = [
  {
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.weatherAnnouncement,
    gradeBand: 2,
    passageText: weatherPassageText,
    sentences: [
      { sentenceId: 'weather-1', text: 'At the weather table, the host smiled and said, "Clouds are moving in, but the morning is calm."' },
      { sentenceId: 'weather-2', text: 'She pointed to the chart, then read the note again.' },
      { sentenceId: 'weather-3', text: '"Will the wind move gently?" she asked.' },
      { sentenceId: 'weather-4', text: 'The class watched the map quietly.' },
      { sentenceId: 'weather-5', text: 'One student said, "Let\'s reread the page before we leave!"' },
    ],
    readingContext: 'Weather announcement practice with commas, questions, and an exclamation.',
    contentVersion: FLUENCY_PRACTICE_CONTENT_VERSION,
    reviewStatus: 'DRAFT',
    wordSupportTargets: [
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.weatherTable,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.weatherAnnouncement,
        sentenceId: 'weather-1',
        surfaceWord: 'table',
        displayChunks: ['ta', 'ble'],
        spokenChunks: ['ta', 'ble'],
        focusIndices: [1],
        blendSpeechText: 'table',
        wholeWordSpeechText: 'table',
        sentenceSpeechText: weatherPassageText,
      }),
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.weatherGently,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.weatherAnnouncement,
        sentenceId: 'weather-3',
        surfaceWord: 'gently',
        displayChunks: ['gent', 'ly'],
        spokenChunks: ['gent', 'ly'],
        focusIndices: [1],
        blendSpeechText: 'gently',
        wholeWordSpeechText: 'gently',
        sentenceSpeechText: weatherPassageText,
      }),
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.weatherReread,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.weatherAnnouncement,
        sentenceId: 'weather-5',
        surfaceWord: 'reread',
        displayChunks: ['re', 'read'],
        spokenChunks: ['re', 'read'],
        focusIndices: [0],
        blendSpeechText: 'reread',
        wholeWordSpeechText: 'reread',
        sentenceSpeechText: weatherPassageText,
      }),
    ],
  },
  {
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.natureTrailReport,
    gradeBand: 2,
    passageText: trailPassageText,
    sentences: [
      { sentenceId: 'trail-1', text: 'On the nature trail, the group unpacked a small lunch and a helpful map.' },
      { sentenceId: 'trail-2', text: 'They sat near a stable bench and listened for birds.' },
      { sentenceId: 'trail-3', text: 'A ranger said, "Read the sign carefully, then look for the blue feather."' },
      { sentenceId: 'trail-4', text: 'The children smiled, checked the path, and moved on together.' },
    ],
    readingContext: 'Nature trail practice with clear phrase groups and helpful support words.',
    contentVersion: FLUENCY_PRACTICE_CONTENT_VERSION,
    reviewStatus: 'DRAFT',
    wordSupportTargets: [
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.trailUnpack,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.natureTrailReport,
        sentenceId: 'trail-1',
        surfaceWord: 'unpacked',
        displayChunks: ['un', 'packed'],
        spokenChunks: ['un', 'packed'],
        focusIndices: [0],
        blendSpeechText: 'unpacked',
        wholeWordSpeechText: 'unpacked',
        sentenceSpeechText: trailPassageText,
      }),
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.trailHelpful,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.natureTrailReport,
        sentenceId: 'trail-1',
        surfaceWord: 'helpful',
        displayChunks: ['help', 'ful'],
        spokenChunks: ['help', 'ful'],
        focusIndices: [1],
        blendSpeechText: 'helpful',
        wholeWordSpeechText: 'helpful',
        sentenceSpeechText: trailPassageText,
      }),
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.trailCarefully,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.natureTrailReport,
        sentenceId: 'trail-3',
        surfaceWord: 'carefully',
        displayChunks: ['care', 'ful', 'ly'],
        spokenChunks: ['care', 'ful', 'ly'],
        focusIndices: [1, 2],
        blendSpeechText: 'carefully',
        wholeWordSpeechText: 'carefully',
        sentenceSpeechText: trailPassageText,
      }),
    ],
  },
  {
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.gardenInstructions,
    gradeBand: 2,
    passageText: gardenPassageText,
    sentences: [
      { sentenceId: 'garden-1', text: 'At the community garden, the leader gave three steps: water, weed, and wait.' },
      { sentenceId: 'garden-2', text: 'The children carried a bundle of gloves and moved carefully between the rows.' },
      { sentenceId: 'garden-3', text: '"Can you find the tiny sprouts?" she asked.' },
      { sentenceId: 'garden-4', text: 'The team smiled and worked quickly.' },
      { sentenceId: 'garden-5', text: 'Soon the table near the gate held fresh herbs and a sign that said, "Please share!"' },
    ],
    readingContext: 'Garden directions with list phrasing and a quick response.',
    contentVersion: FLUENCY_PRACTICE_CONTENT_VERSION,
    reviewStatus: 'DRAFT',
    wordSupportTargets: [
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.gardenBundle,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.gardenInstructions,
        sentenceId: 'garden-2',
        surfaceWord: 'bundle',
        displayChunks: ['bun', 'dle'],
        spokenChunks: ['bun', 'dle'],
        focusIndices: [1],
        blendSpeechText: 'bundle',
        wholeWordSpeechText: 'bundle',
        sentenceSpeechText: gardenPassageText,
      }),
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.gardenQuickly,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.gardenInstructions,
        sentenceId: 'garden-4',
        surfaceWord: 'quickly',
        displayChunks: ['quick', 'ly'],
        spokenChunks: ['quick', 'ly'],
        focusIndices: [1],
        blendSpeechText: 'quickly',
        wholeWordSpeechText: 'quickly',
        sentenceSpeechText: gardenPassageText,
      }),
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.gardenTable,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.gardenInstructions,
        sentenceId: 'garden-5',
        surfaceWord: 'table',
        displayChunks: ['ta', 'ble'],
        spokenChunks: ['ta', 'ble'],
        focusIndices: [1],
        blendSpeechText: 'table',
        wholeWordSpeechText: 'table',
        sentenceSpeechText: gardenPassageText,
      }),
    ],
  },
  {
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.museumDialogue,
    gradeBand: 2,
    passageText: museumPassageText,
    sentences: [
      { sentenceId: 'museum-1', text: 'At the museum, the guide said, "This room has a knight\'s helmet, a brass comb, and a map of an island."' },
      { sentenceId: 'museum-2', text: 'A child asked, "Is the ghost story real?"' },
      { sentenceId: 'museum-3', text: 'The guide laughed softly and said, "It is only a story card, but it still makes readers curious!"' },
      { sentenceId: 'museum-4', text: 'The group moved from one case to the next and stopped to look closely.' },
    ],
    readingContext: 'Museum dialogue with character voice and a careful look at quiet-letter words.',
    contentVersion: FLUENCY_PRACTICE_CONTENT_VERSION,
    reviewStatus: 'DRAFT',
    wordSupportTargets: [
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.museumComb,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.museumDialogue,
        sentenceId: 'museum-1',
        surfaceWord: 'comb',
        displayChunks: ['co', 'mb'],
        spokenChunks: ['comb'],
        focusIndices: [1],
        blendSpeechText: 'comb',
        wholeWordSpeechText: 'comb',
        sentenceSpeechText: museumPassageText,
      }),
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.museumIsland,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.museumDialogue,
        sentenceId: 'museum-1',
        surfaceWord: 'island',
        displayChunks: ['is', 'land'],
        spokenChunks: ['island'],
        focusIndices: [1],
        blendSpeechText: 'island',
        wholeWordSpeechText: 'island',
        sentenceSpeechText: museumPassageText,
      }),
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.museumGhost,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.museumDialogue,
        sentenceId: 'museum-2',
        surfaceWord: 'ghost',
        displayChunks: ['gh', 'ost'],
        spokenChunks: ['ghost'],
        focusIndices: [0],
        blendSpeechText: 'ghost',
        wholeWordSpeechText: 'ghost',
        sentenceSpeechText: museumPassageText,
      }),
    ],
  },
  {
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.animalCareDemo,
    gradeBand: 2,
    passageText: animalCarePassageText,
    sentences: [
      { sentenceId: 'animal-1', text: 'At the animal-care center, the helper lit a candle in a safe jar so the room stayed warm.' },
      { sentenceId: 'animal-2', text: 'She showed how to hold a bottle with both hands and move slowly.' },
      { sentenceId: 'animal-3', text: '"Did the pup drink?" asked one child.' },
      { sentenceId: 'animal-4', text: '"Yes," said the helper, "and the pup feels safe and calm."' },
      { sentenceId: 'animal-5', text: 'The team checked the stable crate and smiled.' },
    ],
    readingContext: 'Animal-care demonstration with calm instructions and careful movement.',
    contentVersion: FLUENCY_PRACTICE_CONTENT_VERSION,
    reviewStatus: 'DRAFT',
    wordSupportTargets: [
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.animalCandle,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.animalCareDemo,
        sentenceId: 'animal-1',
        surfaceWord: 'candle',
        displayChunks: ['can', 'dle'],
        spokenChunks: ['can', 'dle'],
        focusIndices: [1],
        blendSpeechText: 'candle',
        wholeWordSpeechText: 'candle',
        sentenceSpeechText: animalCarePassageText,
      }),
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.animalBottle,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.animalCareDemo,
        sentenceId: 'animal-2',
        surfaceWord: 'bottle',
        displayChunks: ['bot', 'tle'],
        spokenChunks: ['bot', 'tle'],
        focusIndices: [1],
        blendSpeechText: 'bottle',
        wholeWordSpeechText: 'bottle',
        sentenceSpeechText: animalCarePassageText,
      }),
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.animalStable,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.animalCareDemo,
        sentenceId: 'animal-5',
        surfaceWord: 'stable',
        displayChunks: ['sta', 'ble'],
        spokenChunks: ['sta', 'ble'],
        focusIndices: [1],
        blendSpeechText: 'stable',
        wholeWordSpeechText: 'stable',
        sentenceSpeechText: animalCarePassageText,
      }),
    ],
  },
  {
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.scienceDemo,
    gradeBand: 2,
    passageText: sciencePassageText,
    sentences: [
      { sentenceId: 'science-1', text: 'During the science demonstration, the teacher said, "Preheat the lamp board, then watch what changes."' },
      { sentenceId: 'science-2', text: 'The class used a question card, wrote one careful note, and compared the results.' },
      { sentenceId: 'science-3', text: '"That is exciting!" one student shouted.' },
      { sentenceId: 'science-4', text: 'Another student helped the class review the steps.' },
    ],
    readingContext: 'Science demonstration with a clear question, a strong exclamation, and careful notes.',
    contentVersion: FLUENCY_PRACTICE_CONTENT_VERSION,
    reviewStatus: 'DRAFT',
    wordSupportTargets: [
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.sciencePreheat,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.scienceDemo,
        sentenceId: 'science-1',
        surfaceWord: 'preheat',
        displayChunks: ['pre', 'heat'],
        spokenChunks: ['pre', 'heat'],
        focusIndices: [0],
        blendSpeechText: 'preheat',
        wholeWordSpeechText: 'preheat',
        sentenceSpeechText: sciencePassageText,
      }),
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.scienceReview,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.scienceDemo,
        sentenceId: 'science-4',
        surfaceWord: 'review',
        displayChunks: ['re', 'view'],
        spokenChunks: ['re', 'view'],
        focusIndices: [0],
        blendSpeechText: 'review',
        wholeWordSpeechText: 'review',
        sentenceSpeechText: sciencePassageText,
      }),
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.scienceHelped,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.scienceDemo,
        sentenceId: 'science-4',
        surfaceWord: 'helped',
        displayChunks: ['help', 'ed'],
        spokenChunks: ['help', 'ed'],
        focusIndices: [1],
        blendSpeechText: 'helped',
        wholeWordSpeechText: 'helped',
        sentenceSpeechText: sciencePassageText,
      }),
    ],
  },
  {
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.libraryAnnouncement,
    gradeBand: 2,
    passageText: libraryPassageText,
    sentences: [
      { sentenceId: 'library-1', text: 'At the library event, a librarian said, "Read the flyer, then join the bubble parade!"' },
      { sentenceId: 'library-2', text: 'The children lined up near a quiet table and picked a book that could be read again.' },
      { sentenceId: 'library-3', text: 'One child whispered, "I may misspell this title, so I will check it."' },
      { sentenceId: 'library-4', text: 'The librarian nodded and said, "That is a helpful plan."' },
    ],
    readingContext: 'Library announcement with repeated reading, self-monitoring, and cheerful support.',
    contentVersion: FLUENCY_PRACTICE_CONTENT_VERSION,
    reviewStatus: 'DRAFT',
    wordSupportTargets: [
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.libraryBubble,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.libraryAnnouncement,
        sentenceId: 'library-1',
        surfaceWord: 'bubble',
        displayChunks: ['bub', 'ble'],
        spokenChunks: ['bub', 'ble'],
        focusIndices: [1],
        blendSpeechText: 'bubble',
        wholeWordSpeechText: 'bubble',
        sentenceSpeechText: libraryPassageText,
      }),
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.libraryMisspell,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.libraryAnnouncement,
        sentenceId: 'library-3',
        surfaceWord: 'misspell',
        displayChunks: ['mis', 'spell'],
        spokenChunks: ['mis', 'spell'],
        focusIndices: [0],
        blendSpeechText: 'misspell',
        wholeWordSpeechText: 'misspell',
        sentenceSpeechText: libraryPassageText,
      }),
      supportTarget({
        targetId: FLUENCY_PRACTICE_TARGET_IDS.libraryHelpful,
        passageId: FLUENCY_PRACTICE_PASSAGE_IDS.libraryAnnouncement,
        sentenceId: 'library-4',
        surfaceWord: 'helpful',
        displayChunks: ['help', 'ful'],
        spokenChunks: ['help', 'ful'],
        focusIndices: [1],
        blendSpeechText: 'helpful',
        wholeWordSpeechText: 'helpful',
        sentenceSpeechText: libraryPassageText,
      }),
    ],
  },
]
