import type { ReadingQuestion } from '../../../../types'
import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from '../variableVowelsOoEa/questionFactories'
import {
  FLUENCY_PRACTICE_CONTENT_VERSION,
  FLUENCY_PRACTICE_LESSON_IDS,
  FLUENCY_PRACTICE_PASSAGE_IDS,
  FLUENCY_PRACTICE_QUESTION_IDS,
} from './ids'

const common = {
  benchmarkReference: 'RR-G2-FLUENCY-PRACTICE',
  skillIdentifier: 'g2-word-forge-word-practice',
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'Word Forge',
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2',
  contentVersion: FLUENCY_PRACTICE_CONTENT_VERSION,
  reviewStatus: 'DRAFT' as const,
}

export const grade2WordForgeFluencyPracticeQuestions: ReadingQuestion[] = [
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.weatherAnnouncement,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.guidedPunctuationPauses,
    activityIdentifier: 'activity-word-forge-fluency-practice-punctuation-pauses-1',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.guidedPunctuationPauses[0],
    prompt: 'Which mark tells the reader to pause gently in the weather passage?',
    explanation: 'A comma usually tells the reader to pause gently.',
    evidenceReference: 'pause-cue',
    evidenceReferenceIds: ['comma-choice'],
    targetVocabulary: ['comma', 'period', 'question mark', 'exclamation mark'],
    soundOutChunks: ['pause', 'gently'],
    tags: ['fluency-practice', 'punctuation-pauses', 'comma-pause'],
    choices: [
      { id: 'period-choice', text: 'period' },
      { id: 'comma-choice', text: 'comma' },
      { id: 'question-choice', text: 'question mark' },
      { id: 'exclamation-choice', text: 'exclamation mark' },
    ],
    correctChoiceIds: ['comma-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.weatherAnnouncement,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.guidedPunctuationPauses,
    activityIdentifier: 'activity-word-forge-fluency-practice-punctuation-pauses-2',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.guidedPunctuationPauses[1],
    prompt: 'Select the sentence that should be read with a pause after the comma.',
    explanation: 'The sentence with the comma asks for a short pause in the middle.',
    evidenceReference: 'pause-cue',
    evidenceReferenceIds: ['weather-pause-sentence'],
    targetVocabulary: ['comma', 'pause'],
    soundOutChunks: ['pause', 'gently'],
    tags: ['fluency-practice', 'punctuation-pauses', 'comma-pause'],
    selectableSegments: [
      { id: 'weather-fast-sentence', text: 'The class watched the map quietly.' },
      { id: 'weather-exclaim-sentence', text: 'Let\'s reread the page before we leave!' },
      { id: 'weather-pause-sentence', text: 'She pointed to the chart, then read the note again.' },
    ],
    correctSegmentIds: ['weather-pause-sentence'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.weatherAnnouncement,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.guidedPunctuationPauses,
    activityIdentifier: 'activity-word-forge-fluency-practice-punctuation-pauses-3',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.guidedPunctuationPauses[2],
    prompt: 'Choose all the words or marks that help the reader slow down in the weather passage.',
    explanation: 'The comma and the phrase gentle help the reader slow down and notice the meaning.',
    evidenceReference: 'pause-cue',
    evidenceReferenceIds: ['weather-comma', 'weather-gentle-choice'],
    targetVocabulary: ['comma', 'gentle', 'reread'],
    soundOutChunks: ['comma', 'gentle'],
    tags: ['fluency-practice', 'punctuation-pauses', 'self-monitoring'],
    choices: [
      { id: 'weather-comma', text: 'comma' },
      { id: 'weather-gentle-choice', text: 'gentle' },
      { id: 'weather-clouds-choice', text: 'clouds' },
      { id: 'weather-map-choice', text: 'map' },
    ],
    correctChoiceIds: ['weather-comma', 'weather-gentle-choice'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.weatherAnnouncement,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.guidedPunctuationPauses,
    activityIdentifier: 'activity-word-forge-fluency-practice-punctuation-pauses-4',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.guidedPunctuationPauses[3],
    prompt: 'Match each punctuation mark to the way it helps reading.',
    explanation: 'Each mark gives a reader a different cue.',
    evidenceReference: 'pause-cue',
    evidenceReferenceIds: ['comma-cue', 'period-cue', 'question-cue', 'exclamation-cue'],
    targetVocabulary: ['comma', 'period', 'question mark', 'exclamation mark'],
    soundOutChunks: ['pause', 'stop', 'rise', 'excited'],
    tags: ['fluency-practice', 'punctuation-pauses', 'expression-cues'],
    rows: [
      {
        id: 'comma-row',
        prompt: 'comma',
        correctChoiceId: 'comma-cue',
        options: [
          { id: 'period-cue', text: 'stop the sentence' },
          { id: 'comma-cue', text: 'pause gently' },
          { id: 'question-cue', text: 'ask a question' },
          { id: 'exclamation-cue', text: 'show excitement' },
        ],
      },
      {
        id: 'period-row',
        prompt: 'period',
        correctChoiceId: 'period-cue',
        options: [
          { id: 'comma-cue-2', text: 'take a small pause' },
          { id: 'question-cue-2', text: 'ask a question aloud' },
          { id: 'period-cue', text: 'stop at the end' },
          { id: 'exclamation-cue-2', text: 'speak with bright energy' },
        ],
      },
      {
        id: 'question-row',
        prompt: 'question mark',
        correctChoiceId: 'question-cue',
        options: [
          { id: 'question-cue', text: 'let the voice rise' },
          { id: 'comma-cue-3', text: 'pause gently at a comma' },
          { id: 'period-cue-3', text: 'finish with a full stop' },
          { id: 'exclamation-cue-3', text: 'read with bright energy' },
        ],
      },
      {
        id: 'exclamation-row',
        prompt: 'exclamation mark',
        correctChoiceId: 'exclamation-cue',
        options: [
          { id: 'period-cue-4', text: 'finish the sentence' },
          { id: 'comma-cue-4', text: 'pause softly' },
          { id: 'exclamation-cue', text: 'read with excitement' },
          { id: 'question-cue-4', text: 'let the voice rise again' },
        ],
      },
    ],
  }),

  createMultipleChoiceQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.natureTrailReport,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.guidedPhraseGroups,
    activityIdentifier: 'activity-word-forge-fluency-practice-phrase-groups-1',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.guidedPhraseGroups[0],
    prompt: 'Which phrase group should be read together in the trail passage?',
    explanation: 'The phrase "unpacked a small lunch" keeps the action together.',
    evidenceReference: 'phrase-group',
    evidenceReferenceIds: ['trail-lunch-choice'],
    targetVocabulary: ['unpacked', 'helpful', 'carefully'],
    soundOutChunks: ['un', 'packed'],
    tags: ['fluency-practice', 'phrase-groups', 'prefix-un'],
    choices: [
      { id: 'trail-map-choice', text: 'a helpful map' },
      { id: 'trail-birds-choice', text: 'listened for birds' },
      { id: 'trail-lunch-choice', text: 'unpacked a small lunch' },
      { id: 'trail-bench-choice', text: 'stable bench' },
    ],
    correctChoiceIds: ['trail-lunch-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.natureTrailReport,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.guidedPhraseGroups,
    activityIdentifier: 'activity-word-forge-fluency-practice-phrase-groups-2',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.guidedPhraseGroups[1],
    prompt: 'Which choice shows a phrase that should stay together while reading?',
    explanation: 'The phrase "a stable bench" should be read as one unit.',
    evidenceReference: 'phrase-group',
    evidenceReferenceIds: ['trail-stable-choice'],
    targetVocabulary: ['stable', 'carefully', 'helpful'],
    soundOutChunks: ['sta', 'ble'],
    tags: ['fluency-practice', 'phrase-groups', 'consonant-le'],
    choices: [
      { id: 'trail-helpful-choice', text: 'helpful map' },
      { id: 'trail-birds-choice-2', text: 'listened for birds' },
      { id: 'trail-stable-choice', text: 'a stable bench' },
      { id: 'trail-blue-choice', text: 'blue feather' },
    ],
    correctChoiceIds: ['trail-stable-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.natureTrailReport,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.guidedPhraseGroups,
    activityIdentifier: 'activity-word-forge-fluency-practice-phrase-groups-3',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.guidedPhraseGroups[2],
    prompt: 'Select the phrase that shows the sentence should be read calmly.',
    explanation: 'The ranger sentence is calm and steady, which helps the reader slow down.',
    evidenceReference: 'phrase-group',
    evidenceReferenceIds: ['trail-ranger-sentence'],
    targetVocabulary: ['carefully', 'stable', 'helpful'],
    soundOutChunks: ['care', 'ful'],
    tags: ['fluency-practice', 'phrase-groups', 'calm-tone'],
    selectableSegments: [
      { id: 'trail-ranger-sentence', text: 'A ranger said, "Read the sign carefully, then look for the blue feather."' },
      { id: 'trail-group-sentence', text: 'The group unpacked a small lunch and a helpful map.' },
      { id: 'trail-ending-sentence', text: 'The children smiled, checked the path, and moved on together.' },
    ],
    correctSegmentIds: ['trail-ranger-sentence'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.natureTrailReport,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.guidedPhraseGroups,
    activityIdentifier: 'activity-word-forge-fluency-practice-phrase-groups-4',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.guidedPhraseGroups[3],
    prompt: 'Match the phrase to the reading cue it suggests.',
    explanation: 'Each phrase helps the reader notice how to group the words.',
    evidenceReference: 'phrase-group',
    evidenceReferenceIds: ['phrase-unpack-cue', 'phrase-sign-cue', 'phrase-path-cue', 'phrase-lunch-cue'],
    targetVocabulary: ['unpacked', 'carefully', 'stable', 'helpful'],
    soundOutChunks: ['un', 'packed', 'care', 'ful'],
    tags: ['fluency-practice', 'phrase-groups', 'self-monitoring'],
    rows: [
      {
        id: 'phrase-unpack-row',
        prompt: 'unpacked a small lunch',
        correctChoiceId: 'phrase-unpack-cue',
        options: [
          { id: 'phrase-unpack-cue', text: 'one action phrase' },
          { id: 'phrase-sign-cue', text: 'a question cue' },
          { id: 'phrase-path-cue', text: 'an exclamation cue' },
          { id: 'phrase-lunch-cue', text: 'a list cue' },
        ],
      },
      {
        id: 'phrase-sign-row',
        prompt: 'Read the sign carefully',
        correctChoiceId: 'phrase-sign-cue',
        options: [
          { id: 'phrase-sign-cue', text: 'one calm instruction' },
          { id: 'phrase-unpack-cue-2', text: 'a quiet trail cue' },
          { id: 'phrase-path-cue-2', text: 'a bright trail cue' },
          { id: 'phrase-lunch-cue-2', text: 'a map cue' },
        ],
      },
      {
        id: 'phrase-path-row',
        prompt: 'checked the path',
        correctChoiceId: 'phrase-path-cue',
        options: [
          { id: 'phrase-lunch-cue-3', text: 'a gentle pace cue' },
          { id: 'phrase-path-cue', text: 'one smooth action phrase' },
          { id: 'phrase-sign-cue-2', text: 'a pause cue' },
          { id: 'phrase-unpack-cue-3', text: 'a curious question cue' },
        ],
      },
      {
        id: 'phrase-lunch-row',
        prompt: 'a helpful map',
        correctChoiceId: 'phrase-lunch-cue',
        options: [
          { id: 'phrase-sign-cue-3', text: 'a helpful detail cue' },
          { id: 'phrase-path-cue-3', text: 'an energy cue' },
          { id: 'phrase-lunch-cue', text: 'a descriptive phrase' },
          { id: 'phrase-unpack-cue-4', text: 'a careful stop cue' },
        ],
      },
    ],
  }),

  createMultipleChoiceQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.scienceDemo,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.guidedQuestionsAndExclamations,
    activityIdentifier: 'activity-word-forge-fluency-practice-questions-and-exclamations-1',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.guidedQuestionsAndExclamations[0],
    prompt: 'Which sentence should sound like a question?',
    explanation: 'The sentence that asks something should rise at the end.',
    evidenceReference: 'question-cue',
    evidenceReferenceIds: ['science-question-choice'],
    targetVocabulary: ['question', 'exciting', 'review'],
    soundOutChunks: ['question'],
    tags: ['fluency-practice', 'questions-and-exclamations', 'question-cue'],
    choices: [
      { id: 'science-exclaim-choice', text: '"That is exciting!" one student shouted.' },
      { id: 'science-review-choice', text: 'Another student replied, "Let\'s review the steps and help each other."' },
      { id: 'science-card-choice', text: 'The class used a question card, wrote one careful note, and compared the results.' },
      { id: 'science-question-choice', text: '"Did the plan work?"' },
    ],
    correctChoiceIds: ['science-question-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.scienceDemo,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.guidedQuestionsAndExclamations,
    activityIdentifier: 'activity-word-forge-fluency-practice-questions-and-exclamations-2',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.guidedQuestionsAndExclamations[1],
    prompt: 'Select the sentence that should be read with excitement.',
    explanation: 'The exclamation sentence shows strong feeling.',
    evidenceReference: 'exclamation-cue',
    evidenceReferenceIds: ['science-exclaim-sentence'],
    targetVocabulary: ['exciting', 'question'],
    soundOutChunks: ['excite', 'ing'],
    tags: ['fluency-practice', 'questions-and-exclamations', 'exclamation-cue'],
    selectableSegments: [
      { id: 'science-question-sentence', text: 'The class used a question card, wrote one careful note, and compared the results.' },
      { id: 'science-exclaim-sentence', text: '"That is exciting!" one student shouted.' },
      { id: 'science-review-sentence', text: 'Another student replied, "Let\'s review the steps and help each other."' },
    ],
    correctSegmentIds: ['science-exclaim-sentence'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.scienceDemo,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.guidedQuestionsAndExclamations,
    activityIdentifier: 'activity-word-forge-fluency-practice-questions-and-exclamations-3',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.guidedQuestionsAndExclamations[2],
    prompt: 'Which choice should be read with an excited voice?',
    explanation: 'That is exciting should sound lively and bright.',
    evidenceReference: 'voice-cue',
    evidenceReferenceIds: ['science-exclaim-choice'],
    targetVocabulary: ['exciting', 'voice', 'tone'],
    soundOutChunks: ['excite', 'ing'],
    tags: ['fluency-practice', 'questions-and-exclamations', 'voice-cues'],
    choices: [
      { id: 'science-question-choice', text: 'question card' },
      { id: 'science-exclaim-choice', text: 'that is exciting' },
      { id: 'science-review-choice', text: 'let us review the steps' },
      { id: 'science-note-choice', text: 'one careful note' },
    ],
    correctChoiceIds: ['science-exclaim-choice'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.scienceDemo,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.guidedQuestionsAndExclamations,
    activityIdentifier: 'activity-word-forge-fluency-practice-questions-and-exclamations-4',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.guidedQuestionsAndExclamations[3],
    prompt: 'Match each mark to the way the reader should sound.',
    explanation: 'Each punctuation mark gives a different reading cue.',
    evidenceReference: 'voice-cue',
    evidenceReferenceIds: ['question-cue-row', 'exclamation-cue-row', 'comma-cue-row', 'period-cue-row'],
    targetVocabulary: ['question', 'exclamation', 'comma', 'period'],
    soundOutChunks: ['rise', 'excited', 'pause', 'stop'],
    tags: ['fluency-practice', 'questions-and-exclamations', 'expression-cues'],
    rows: [
      {
        id: 'question-mark-row',
        prompt: 'question mark',
        correctChoiceId: 'question-cue-row',
        options: [
          { id: 'question-cue-row', text: 'let the voice rise' },
          { id: 'comma-cue-row', text: 'pause softly at a comma' },
          { id: 'period-cue-row', text: 'stop the sentence' },
          { id: 'exclamation-cue-row', text: 'sound curious' },
        ],
      },
      {
        id: 'exclamation-mark-row',
        prompt: 'exclamation mark',
        correctChoiceId: 'exclamation-cue-row',
        options: [
          { id: 'period-cue-row-2', text: 'finish the sentence' },
          { id: 'question-cue-row-2', text: 'ask a question' },
          { id: 'exclamation-cue-row', text: 'read with excitement' },
          { id: 'comma-cue-row-2', text: 'pause at a comma' },
        ],
      },
      {
        id: 'comma-mark-row',
        prompt: 'comma',
        correctChoiceId: 'comma-cue-row',
        options: [
          { id: 'comma-cue-row', text: 'pause gently at the mark' },
          { id: 'period-cue-row-3', text: 'use a full stop' },
          { id: 'question-cue-row-3', text: 'lift the tone a little' },
          { id: 'exclamation-cue-row-2', text: 'read with bright energy' },
        ],
      },
      {
        id: 'period-mark-row',
        prompt: 'period',
        correctChoiceId: 'period-cue-row',
        options: [
          { id: 'exclamation-cue-row-3', text: 'show excitement clearly' },
          { id: 'question-cue-row-4', text: 'let the voice rise again' },
          { id: 'comma-cue-row-3', text: 'pause softly for a beat' },
          { id: 'period-cue-row', text: 'stop at the end' },
        ],
      },
    ],
  }),

  createMultipleChoiceQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.museumDialogue,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.guidedDialogueVoice,
    activityIdentifier: 'activity-word-forge-fluency-practice-dialogue-and-character-voice-1',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.guidedDialogueVoice[0],
    prompt: 'Which part of the museum passage is dialogue?',
    explanation: 'Dialogue is the words that a character says aloud.',
    evidenceReference: 'dialogue-cue',
    evidenceReferenceIds: ['museum-dialogue-choice'],
    targetVocabulary: ['dialogue', 'voice', 'character'],
    soundOutChunks: ['dia', 'logue'],
    tags: ['fluency-practice', 'dialogue-and-character-voice', 'dialogue-cue'],
    choices: [
      { id: 'museum-description-choice', text: 'The group moved from one case to the next and stopped to look closely.' },
      { id: 'museum-dialogue-choice', text: '"Is the ghost story real?"' },
      { id: 'museum-setting-choice', text: 'At the museum, the guide said' },
      { id: 'museum-heard-choice', text: 'The guide laughed softly' },
    ],
    correctChoiceIds: ['museum-dialogue-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.museumDialogue,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.guidedDialogueVoice,
    activityIdentifier: 'activity-word-forge-fluency-practice-dialogue-and-character-voice-2',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.guidedDialogueVoice[1],
    prompt: 'Select the sentence that should sound curious.',
    explanation: 'The child asks a question, so the voice should sound curious.',
    evidenceReference: 'dialogue-cue',
    evidenceReferenceIds: ['museum-question-sentence'],
    targetVocabulary: ['ghost', 'curious', 'dialogue'],
    soundOutChunks: ['curious'],
    tags: ['fluency-practice', 'dialogue-and-character-voice', 'question-cue'],
    selectableSegments: [
      { id: 'museum-question-sentence', text: 'A child asked, "Is the ghost story real?"' },
      { id: 'museum-guide-sentence', text: 'The guide laughed softly and said, "It is only a story card, but it still makes readers curious!"' },
      { id: 'museum-move-sentence', text: 'The group moved from one case to the next and stopped to look closely.' },
    ],
    correctSegmentIds: ['museum-question-sentence'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.museumDialogue,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.guidedDialogueVoice,
    activityIdentifier: 'activity-word-forge-fluency-practice-dialogue-and-character-voice-3',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.guidedDialogueVoice[2],
    prompt: 'Choose all the words that help the reader notice who is speaking.',
    explanation: 'Quotation marks and speech verbs help the reader notice the speakers.',
    evidenceReference: 'dialogue-cue',
    evidenceReferenceIds: ['museum-guide-choice', 'museum-child-choice', 'museum-quotes-choice'],
    targetVocabulary: ['guide', 'asked', 'said'],
    soundOutChunks: ['speaker', 'voice'],
    tags: ['fluency-practice', 'dialogue-and-character-voice', 'speech-verbs'],
    choices: [
      { id: 'museum-guide-choice', text: 'the guide said' },
      { id: 'museum-child-choice', text: 'a child asked' },
      { id: 'museum-quotes-choice', text: 'quotation marks' },
      { id: 'museum-card-choice', text: 'story card' },
    ],
    correctChoiceIds: ['museum-guide-choice', 'museum-child-choice', 'museum-quotes-choice'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.museumDialogue,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.guidedDialogueVoice,
    activityIdentifier: 'activity-word-forge-fluency-practice-dialogue-and-character-voice-4',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.guidedDialogueVoice[3],
    prompt: 'Match the sentence part to the voice it suggests.',
    explanation: 'Each line gives a different clue about how to sound when reading.',
    evidenceReference: 'dialogue-cue',
    evidenceReferenceIds: ['museum-curious-cue', 'museum-soft-cue', 'museum-story-cue', 'museum-close-cue'],
    targetVocabulary: ['curious', 'softly', 'story', 'closely'],
    soundOutChunks: ['curious', 'soft', 'story', 'close'],
    tags: ['fluency-practice', 'dialogue-and-character-voice', 'expression-cues'],
    rows: [
      {
        id: 'curious-row',
        prompt: '"Is the ghost story real?"',
        correctChoiceId: 'museum-curious-cue',
        options: [
          { id: 'museum-soft-cue', text: 'soft and calm at the end' },
          { id: 'museum-curious-cue', text: 'curious and questioning' },
          { id: 'museum-story-cue', text: 'flat and still like a fact' },
          { id: 'museum-close-cue', text: 'fast and rushed like a chase' },
        ],
      },
      {
        id: 'soft-row',
        prompt: 'The guide laughed softly',
        correctChoiceId: 'museum-soft-cue',
        options: [
          { id: 'museum-soft-cue', text: 'soft and calm' },
          { id: 'museum-curious-cue-2', text: 'curious and questioning in a whisper' },
          { id: 'museum-story-cue-2', text: 'flat and still for a statement' },
          { id: 'museum-close-cue-2', text: 'fast and rushed like a race' },
        ],
      },
      {
        id: 'story-row',
        prompt: 'It is only a story card',
        correctChoiceId: 'museum-story-cue',
        options: [
          { id: 'museum-close-cue-3', text: 'fast and rushed through the facts' },
          { id: 'museum-curious-cue-3', text: 'curious and questioning about the story' },
          { id: 'museum-story-cue', text: 'informational and calm' },
          { id: 'museum-soft-cue-3', text: 'soft and calm in a museum voice' },
        ],
      },
      {
        id: 'close-row',
        prompt: 'The group moved from one case to the next',
        correctChoiceId: 'museum-close-cue',
        options: [
          { id: 'museum-story-cue-4', text: 'informational and calm in the room' },
          { id: 'museum-soft-cue-4', text: 'soft and calm beside the display' },
          { id: 'museum-curious-cue-4', text: 'curious and questioning at the case' },
          { id: 'museum-close-cue', text: 'steady and careful' },
        ],
      },
    ],
  }),

  createMultipleChoiceQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.animalCareDemo,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.independentNatureReport,
    activityIdentifier: 'activity-word-forge-fluency-practice-nature-report-1',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.independentNatureReport[0],
    prompt: 'Which choice names the item that should be read as a consonant-le word?',
    explanation: 'Bottle ends with the consonant-le pattern.',
    evidenceReference: 'support-word',
    evidenceReferenceIds: ['animal-bottle-choice'],
    targetVocabulary: ['bottle', 'candle', 'stable'],
    soundOutChunks: ['bot', 'tle'],
    tags: ['fluency-practice', 'supportive-reading', 'consonant-le'],
    choices: [
      { id: 'animal-candle-choice', text: 'candle' },
      { id: 'animal-stable-choice', text: 'stable' },
      { id: 'animal-bottle-choice', text: 'bottle' },
      { id: 'animal-slowly-choice', text: 'slowly' },
    ],
    correctChoiceIds: ['animal-bottle-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.animalCareDemo,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.independentNatureReport,
    activityIdentifier: 'activity-word-forge-fluency-practice-nature-report-2',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.independentNatureReport[1],
    prompt: 'Which sentence best shows careful reading of the animal-care passage?',
    explanation: 'The sentence about the stable crate fits the calm, careful tone.',
    evidenceReference: 'meaning-check',
    evidenceReferenceIds: ['animal-stable-choice-2'],
    targetVocabulary: ['stable', 'careful', 'slowly'],
    soundOutChunks: ['sta', 'ble'],
    tags: ['fluency-practice', 'supportive-reading', 'meaning-check'],
    choices: [
      { id: 'animal-drink-choice', text: 'Did the pup drink?' },
      { id: 'animal-warm-choice', text: 'The room stayed warm.' },
      { id: 'animal-stable-choice-2', text: 'The team checked the stable crate and smiled.' },
      { id: 'animal-calm-choice', text: 'She showed how to hold a bottle with both hands and move slowly.' },
    ],
    correctChoiceIds: ['animal-stable-choice-2'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.animalCareDemo,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.independentNatureReport,
    activityIdentifier: 'activity-word-forge-fluency-practice-nature-report-3',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.independentNatureReport[2],
    prompt: 'Choose all the words that help the reader slow down and stay calm.',
    explanation: 'Candle, bottle, and slowly all help the reader notice the calm pace.',
    evidenceReference: 'meaning-check',
    evidenceReferenceIds: ['animal-candle-choice', 'animal-bottle-choice-3', 'animal-slowly-choice-2'],
    targetVocabulary: ['candle', 'bottle', 'slowly'],
    soundOutChunks: ['can', 'dle', 'bot', 'tle'],
    tags: ['fluency-practice', 'supportive-reading', 'calm-tone'],
    choices: [
      { id: 'animal-candle-choice', text: 'candle' },
      { id: 'animal-bottle-choice-3', text: 'bottle' },
      { id: 'animal-slowly-choice-2', text: 'slowly' },
      { id: 'animal-drink-choice-2', text: 'drink' },
    ],
    correctChoiceIds: ['animal-candle-choice', 'animal-bottle-choice-3', 'animal-slowly-choice-2'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.animalCareDemo,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.independentNatureReport,
    activityIdentifier: 'activity-word-forge-fluency-practice-nature-report-4',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.independentNatureReport[3],
    prompt: 'Which sentence should be read with a smooth, careful voice?',
    explanation: 'The sentence about holding the bottle and moving slowly is calm and careful.',
    evidenceReference: 'meaning-check',
    evidenceReferenceIds: ['animal-slow-sentence'],
    targetVocabulary: ['bottle', 'slowly', 'stable'],
    soundOutChunks: ['bot', 'tle'],
    tags: ['fluency-practice', 'supportive-reading', 'self-monitoring'],
    choices: [
      { id: 'animal-slow-sentence', text: 'She showed how to hold a bottle with both hands and move slowly.' },
      { id: 'animal-safe-sentence', text: 'The room stayed warm.' },
      { id: 'animal-pup-sentence', text: '"Did the pup drink?" asked one child.' },
      { id: 'animal-stable-sentence', text: 'The team checked the stable crate and smiled.' },
    ],
    correctChoiceIds: ['animal-slow-sentence'],
  }),

  createMultipleChoiceQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.gardenInstructions,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.independentCommunityAnnouncement,
    activityIdentifier: 'activity-word-forge-fluency-practice-community-announcement-1',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.independentCommunityAnnouncement[0],
    prompt: 'Which choice shows the phrase that gives a strong voice cue?',
    explanation: 'The exclamation phrase should be read with energy.',
    evidenceReference: 'list-cue',
    evidenceReferenceIds: ['garden-share-choice'],
    targetVocabulary: ['share', 'quickly', 'bundle'],
    soundOutChunks: ['please', 'share'],
    tags: ['fluency-practice', 'supportive-reading', 'exclamation-cue'],
    choices: [
      { id: 'garden-steps-choice', text: 'water, weed, and wait' },
      { id: 'garden-share-choice', text: '"Please share!"' },
      { id: 'garden-bundle-choice', text: 'a bundle of gloves' },
      { id: 'garden-table-choice', text: 'the table near the gate' },
    ],
    correctChoiceIds: ['garden-share-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.gardenInstructions,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.independentCommunityAnnouncement,
    activityIdentifier: 'activity-word-forge-fluency-practice-community-announcement-2',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.independentCommunityAnnouncement[1],
    prompt: 'Select the sentence that should be read as a list of steps.',
    explanation: 'The first sentence lists the steps for the garden work.',
    evidenceReference: 'list-cue',
    evidenceReferenceIds: ['garden-list-sentence'],
    targetVocabulary: ['water', 'weed', 'wait'],
    soundOutChunks: ['water', 'weed', 'wait'],
    tags: ['fluency-practice', 'supportive-reading', 'list-phrasing'],
    selectableSegments: [
      { id: 'garden-list-sentence', text: 'At the community garden, the leader gave three steps: water, weed, and wait.' },
      { id: 'garden-question-sentence', text: '"Can you find the tiny sprouts?" she asked.' },
      { id: 'garden-speed-sentence', text: 'The team smiled and worked quickly.' },
    ],
    correctSegmentIds: ['garden-list-sentence'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.gardenInstructions,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.independentCommunityAnnouncement,
    activityIdentifier: 'activity-word-forge-fluency-practice-community-announcement-3',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.independentCommunityAnnouncement[2],
    prompt: 'Choose all the words that help the reader keep the passage moving smoothly.',
    explanation: 'Bundle, carefully, and quickly all help the reader keep the pace steady.',
    evidenceReference: 'list-cue',
    evidenceReferenceIds: ['garden-bundle-choice', 'garden-carefully-choice', 'garden-quickly-choice'],
    targetVocabulary: ['bundle', 'carefully', 'quickly'],
    soundOutChunks: ['bun', 'dle', 'care', 'ful', 'ly'],
    tags: ['fluency-practice', 'supportive-reading', 'self-monitoring'],
    choices: [
      { id: 'garden-bundle-choice', text: 'bundle' },
      { id: 'garden-carefully-choice', text: 'carefully' },
      { id: 'garden-quickly-choice', text: 'quickly' },
      { id: 'garden-table-choice-2', text: 'table' },
    ],
    correctChoiceIds: ['garden-bundle-choice', 'garden-carefully-choice', 'garden-quickly-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.gardenInstructions,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.independentCommunityAnnouncement,
    activityIdentifier: 'activity-word-forge-fluency-practice-community-announcement-4',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.independentCommunityAnnouncement[3],
    prompt: 'Which phrase should be read with the strongest voice cue?',
    explanation: 'Please share! should be read with excitement.',
    evidenceReference: 'list-cue',
    evidenceReferenceIds: ['garden-share-choice'],
    targetVocabulary: ['share', 'quickly', 'bundle'],
    soundOutChunks: ['please', 'share'],
    tags: ['fluency-practice', 'supportive-reading', 'expression-cues'],
    choices: [
      { id: 'garden-steps-choice', text: 'water, weed, and wait' },
      { id: 'garden-share-choice', text: '"Please share!"' },
      { id: 'garden-bundle-choice', text: 'a bundle of gloves' },
      { id: 'garden-table-choice', text: 'the table near the gate' },
    ],
    correctChoiceIds: ['garden-share-choice'],
  }),

  createMultipleChoiceQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.libraryAnnouncement,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.independentScienceDemonstration,
    activityIdentifier: 'activity-word-forge-fluency-practice-science-demonstration-1',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.independentScienceDemonstration[0],
    prompt: 'Which word helps the reader notice a quiet-letter pattern?',
    explanation: 'Misspell has the prefix mis- and the base word spell.',
    evidenceReference: 'self-monitoring',
    evidenceReferenceIds: ['library-misspell-choice'],
    targetVocabulary: ['misspell', 'bubble', 'helpful'],
    soundOutChunks: ['mis', 'spell'],
    tags: ['fluency-practice', 'supportive-reading', 'self-monitoring'],
    choices: [
      { id: 'library-bubble-choice', text: 'bubble' },
      { id: 'library-helpful-choice', text: 'helpful' },
      { id: 'library-misspell-choice', text: 'misspell' },
      { id: 'library-read-choice', text: 'read' },
    ],
    correctChoiceIds: ['library-misspell-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.libraryAnnouncement,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.independentScienceDemonstration,
    activityIdentifier: 'activity-word-forge-fluency-practice-science-demonstration-2',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.independentScienceDemonstration[1],
    prompt: 'Which sentence should be read again to check the meaning?',
    explanation: 'The sentence about checking the title shows self-monitoring.',
    evidenceReference: 'self-monitoring',
    evidenceReferenceIds: ['library-check-sentence'],
    targetVocabulary: ['misspell', 'helpful', 'again'],
    soundOutChunks: ['check', 'it'],
    tags: ['fluency-practice', 'supportive-reading', 'self-monitoring'],
    choices: [
      { id: 'library-parade-choice', text: 'Read the flyer, then join the bubble parade!' },
      { id: 'library-check-sentence', text: 'I may misspell this title, so I will check it.' },
      { id: 'library-helpful-choice-2', text: 'That is a helpful plan.' },
      { id: 'library-table-choice', text: 'The children lined up near a quiet table.' },
    ],
    correctChoiceIds: ['library-check-sentence'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.libraryAnnouncement,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.independentScienceDemonstration,
    activityIdentifier: 'activity-word-forge-fluency-practice-science-demonstration-3',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.independentScienceDemonstration[2],
    prompt: 'Choose all the words that help the reader stay careful and self-monitor.',
    explanation: 'Bubble, quiet, misspell, and helpful all keep the reader focused on careful reading.',
    evidenceReference: 'self-monitoring',
    evidenceReferenceIds: ['library-bubble-choice-2', 'library-quiet-choice', 'library-misspell-choice-2', 'library-helpful-choice-3'],
    targetVocabulary: ['bubble', 'quiet', 'misspell', 'helpful'],
    soundOutChunks: ['bub', 'ble', 'qui', 'et'],
    tags: ['fluency-practice', 'supportive-reading', 'self-monitoring'],
    choices: [
      { id: 'library-bubble-choice-2', text: 'bubble' },
      { id: 'library-quiet-choice', text: 'quiet' },
      { id: 'library-misspell-choice-2', text: 'misspell' },
      { id: 'library-helpful-choice-3', text: 'helpful' },
    ],
    correctChoiceIds: ['library-bubble-choice-2', 'library-quiet-choice', 'library-misspell-choice-2', 'library-helpful-choice-3'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 8,
    passageIdentifier: FLUENCY_PRACTICE_PASSAGE_IDS.libraryAnnouncement,
    lessonIdentifier: FLUENCY_PRACTICE_LESSON_IDS.independentScienceDemonstration,
    activityIdentifier: 'activity-word-forge-fluency-practice-science-demonstration-4',
    questionIdentifier: FLUENCY_PRACTICE_QUESTION_IDS.independentScienceDemonstration[3],
    prompt: 'Which sentence should feel calm and friendly?',
    explanation: 'The helpful-plan sentence is calm and friendly.',
    evidenceReference: 'self-monitoring',
    evidenceReferenceIds: ['library-helpful-sentence'],
    targetVocabulary: ['helpful', 'quiet', 'bubble'],
    soundOutChunks: ['help', 'ful'],
    tags: ['fluency-practice', 'supportive-reading', 'calm-tone'],
    choices: [
      { id: 'library-bubble-sentence', text: 'Read the flyer, then join the bubble parade!' },
      { id: 'library-check-sentence-2', text: 'I may misspell this title, so I will check it.' },
      { id: 'library-helpful-sentence', text: 'That is a helpful plan.' },
      { id: 'library-quiet-sentence', text: 'The children lined up near a quiet table.' },
    ],
    correctChoiceIds: ['library-helpful-sentence'],
  }),
]
