import type { Passage, WordSupportChunk, WordSupportTarget, WordSupportPart } from '../../../../types'
import { OU_OI_OY_OW_CONTENT_VERSION, OU_OI_OY_OW_PASSAGE_IDS } from './ids'

const draftStatus = 'DRAFT' as const

function sentence(sentenceId: string, text: string) {
  return { sentenceId, text }
}

function chunk(displayText: string, speechText: string = displayText): WordSupportChunk {
  return { displayText, speechText }
}

function part(text: string, emphasis = false): WordSupportPart {
  return { text, emphasis }
}

function supportTarget(spec: {
  targetId: string
  passageId: string
  sentenceId: string
  surfaceWord: string
  focusParts: WordSupportPart[]
  displayChunks: WordSupportChunk[]
  spokenChunks: WordSupportChunk[]
  blendSpeechText: string
  wholeWordSpeechText: string
  sentenceSpeechText: string
}): WordSupportTarget {
  return {
    ...spec,
    reviewStatus: draftStatus,
    contentVersion: OU_OI_OY_OW_CONTENT_VERSION,
  }
}

export const grade2WordForgeVariableVowelsOuOiOyOwPassages: Passage[] = [
  {
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.cloudTownBoard,
    gradeBand: 2,
    passageText: [
      'The town board showed a cloud over the hill.',
      'The snow moved in slowly.',
      'The crowd helped count the cups for the soup drive.',
      'The loud bell rang at noon.',
    ].join(' '),
    sentences: [
      sentence('cloud-board-1', 'The town board showed a cloud over the hill.'),
      sentence('cloud-board-2', 'The snow moved in slowly.'),
      sentence('cloud-board-3', 'The crowd helped count the cups for the soup drive.'),
      sentence('cloud-board-4', 'The loud bell rang at noon.'),
    ],
    readingContext: 'Word Forge Trail 2 practice about a town board and a community drive.',
    contentVersion: OU_OI_OY_OW_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-1-cloud',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.cloudTownBoard,
        sentenceId: 'cloud-board-1',
        surfaceWord: 'cloud',
        focusParts: [part('cl'), part('ou', true), part('d')],
        displayChunks: [chunk('cl'), chunk('ou'), chunk('d')],
        spokenChunks: [chunk('cl'), chunk('ow'), chunk('d')],
        blendSpeechText: 'cloud',
        wholeWordSpeechText: 'cloud',
        sentenceSpeechText: 'The town board showed a cloud over the hill.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-1-snow',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.cloudTownBoard,
        sentenceId: 'cloud-board-2',
        surfaceWord: 'snow',
        focusParts: [part('sn'), part('ow', true)],
        displayChunks: [chunk('sn'), chunk('ow')],
        spokenChunks: [chunk('sn'), chunk('oh')],
        blendSpeechText: 'snow',
        wholeWordSpeechText: 'snow',
        sentenceSpeechText: 'The snow moved in slowly.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-1-count',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.cloudTownBoard,
        sentenceId: 'cloud-board-3',
        surfaceWord: 'count',
        focusParts: [part('c'), part('ou', true), part('nt')],
        displayChunks: [chunk('c'), chunk('ou'), chunk('nt')],
        spokenChunks: [chunk('c'), chunk('ow'), chunk('nt')],
        blendSpeechText: 'count',
        wholeWordSpeechText: 'count',
        sentenceSpeechText: 'The crowd helped count the cups for the soup drive.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-1-loud',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.cloudTownBoard,
        sentenceId: 'cloud-board-4',
        surfaceWord: 'loud',
        focusParts: [part('l'), part('ou', true), part('d')],
        displayChunks: [chunk('l'), chunk('ou'), chunk('d')],
        spokenChunks: [chunk('l'), chunk('ow'), chunk('d')],
        blendSpeechText: 'loud',
        wholeWordSpeechText: 'loud',
        sentenceSpeechText: 'The loud bell rang at noon.',
      }),
    ],
  },
  {
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.toySorting,
    gradeBand: 2,
    passageText: [
      'At the toy box, the team sorted each coin into a bright jar.',
      'A boy and a girl joined the game.',
      'They chose the right voice for each turn.',
      'Joy filled the room.',
    ].join(' '),
    sentences: [
      sentence('toy-sorting-1', 'At the toy box, the team sorted each coin into a bright jar.'),
      sentence('toy-sorting-2', 'A boy and a girl joined the game.'),
      sentence('toy-sorting-3', 'They chose the right voice for each turn.'),
      sentence('toy-sorting-4', 'Joy filled the room.'),
    ],
    readingContext: 'Word Forge Trail 2 practice about sorting toys and coins.',
    contentVersion: OU_OI_OY_OW_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-2-toy',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.toySorting,
        sentenceId: 'toy-sorting-1',
        surfaceWord: 'toy',
        focusParts: [part('t'), part('oy', true)],
        displayChunks: [chunk('t'), chunk('oy')],
        spokenChunks: [chunk('t'), chunk('oy')],
        blendSpeechText: 'toy',
        wholeWordSpeechText: 'toy',
        sentenceSpeechText: 'At the toy box, the team sorted each coin into a bright jar.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-2-coin',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.toySorting,
        sentenceId: 'toy-sorting-1',
        surfaceWord: 'coin',
        focusParts: [part('c'), part('oi', true), part('n')],
        displayChunks: [chunk('c'), chunk('oi'), chunk('n')],
        spokenChunks: [chunk('c'), chunk('oy'), chunk('n')],
        blendSpeechText: 'coin',
        wholeWordSpeechText: 'coin',
        sentenceSpeechText: 'At the toy box, the team sorted each coin into a bright jar.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-2-boy',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.toySorting,
        sentenceId: 'toy-sorting-2',
        surfaceWord: 'boy',
        focusParts: [part('b'), part('oy', true)],
        displayChunks: [chunk('b'), chunk('oy')],
        spokenChunks: [chunk('b'), chunk('oy')],
        blendSpeechText: 'boy',
        wholeWordSpeechText: 'boy',
        sentenceSpeechText: 'A boy and a girl joined the game.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-2-join',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.toySorting,
        sentenceId: 'toy-sorting-2',
        surfaceWord: 'join',
        focusParts: [part('j'), part('oi', true), part('n')],
        displayChunks: [chunk('j'), chunk('oi'), chunk('n')],
        spokenChunks: [chunk('j'), chunk('oy'), chunk('n')],
        blendSpeechText: 'join',
        wholeWordSpeechText: 'join',
        sentenceSpeechText: 'A boy and a girl joined the game.',
      }),
    ],
  },
  {
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.soupWalk,
    gradeBand: 2,
    passageText: [
      'The group carried soup to the house by the pond.',
      'A child tried to touch the warm bowl, but the helper said to wait.',
      'The young owl watched the snow from the window.',
      'The loud crowd counted the cups before the clean-up ended.',
    ].join(' '),
    sentences: [
      sentence('soup-walk-1', 'The group carried soup to the house by the pond.'),
      sentence('soup-walk-2', 'A child tried to touch the warm bowl, but the helper said to wait.'),
      sentence('soup-walk-3', 'The young owl watched the snow from the window.'),
      sentence('soup-walk-4', 'The loud crowd counted the cups before the clean-up ended.'),
    ],
    readingContext: 'Word Forge Trail 2 practice about a family walk and a warm snack.',
    contentVersion: OU_OI_OY_OW_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-3-group',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.soupWalk,
        sentenceId: 'soup-walk-1',
        surfaceWord: 'group',
        focusParts: [part('gr'), part('ou', true), part('p')],
        displayChunks: [chunk('gr'), chunk('ou'), chunk('p')],
        spokenChunks: [chunk('gr'), chunk('oo'), chunk('p')],
        blendSpeechText: 'group',
        wholeWordSpeechText: 'group',
        sentenceSpeechText: 'The group carried soup to the house by the pond.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-3-soup',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.soupWalk,
        sentenceId: 'soup-walk-1',
        surfaceWord: 'soup',
        focusParts: [part('s'), part('ou', true), part('p')],
        displayChunks: [chunk('s'), chunk('ou'), chunk('p')],
        spokenChunks: [chunk('s'), chunk('oo'), chunk('p')],
        blendSpeechText: 'soup',
        wholeWordSpeechText: 'soup',
        sentenceSpeechText: 'The group carried soup to the house by the pond.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-3-touch',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.soupWalk,
        sentenceId: 'soup-walk-2',
        surfaceWord: 'touch',
        focusParts: [part('t'), part('ou', true), part('ch')],
        displayChunks: [chunk('t'), chunk('ou'), chunk('ch')],
        spokenChunks: [chunk('t'), chunk('ouch')],
        blendSpeechText: 'touch',
        wholeWordSpeechText: 'touch',
        sentenceSpeechText: 'A child tried to touch the warm bowl, but the helper said to wait.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-3-snow',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.soupWalk,
        sentenceId: 'soup-walk-3',
        surfaceWord: 'snow',
        focusParts: [part('sn'), part('ow', true)],
        displayChunks: [chunk('sn'), chunk('ow')],
        spokenChunks: [chunk('sn'), chunk('oh')],
        blendSpeechText: 'snow',
        wholeWordSpeechText: 'snow',
        sentenceSpeechText: 'The young owl watched the snow from the window.',
      }),
    ],
  },
  {
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.coinGame,
    gradeBand: 2,
    passageText: [
      'At the market, the coin jar sat beside a shiny toy.',
      'A girl said the choice was hard, but she could join the line.',
      'The voice of the announcer told the story.',
      'The happy boy waved to the crowd.',
    ].join(' '),
    sentences: [
      sentence('coin-game-1', 'At the market, the coin jar sat beside a shiny toy.'),
      sentence('coin-game-2', 'A girl said the choice was hard, but she could join the line.'),
      sentence('coin-game-3', 'The voice of the announcer told the story.'),
      sentence('coin-game-4', 'The happy boy waved to the crowd.'),
    ],
    readingContext: 'Word Forge Trail 2 practice about a market game and careful choices.',
    contentVersion: OU_OI_OY_OW_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-4-coin',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.coinGame,
        sentenceId: 'coin-game-1',
        surfaceWord: 'coin',
        focusParts: [part('c'), part('oi', true), part('n')],
        displayChunks: [chunk('c'), chunk('oi'), chunk('n')],
        spokenChunks: [chunk('c'), chunk('oy'), chunk('n')],
        blendSpeechText: 'coin',
        wholeWordSpeechText: 'coin',
        sentenceSpeechText: 'At the market, the coin jar sat beside a shiny toy.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-4-toy',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.coinGame,
        sentenceId: 'coin-game-1',
        surfaceWord: 'toy',
        focusParts: [part('t'), part('oy', true)],
        displayChunks: [chunk('t'), chunk('oy')],
        spokenChunks: [chunk('t'), chunk('oy')],
        blendSpeechText: 'toy',
        wholeWordSpeechText: 'toy',
        sentenceSpeechText: 'At the market, the coin jar sat beside a shiny toy.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-4-choice',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.coinGame,
        sentenceId: 'coin-game-2',
        surfaceWord: 'choice',
        focusParts: [part('ch'), part('oi', true), part('ce')],
        displayChunks: [chunk('ch'), chunk('oi'), chunk('ce')],
        spokenChunks: [chunk('ch'), chunk('oy'), chunk('ce')],
        blendSpeechText: 'choice',
        wholeWordSpeechText: 'choice',
        sentenceSpeechText: 'A girl said the choice was hard, but she could join the line.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-4-boy',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.coinGame,
        sentenceId: 'coin-game-4',
        surfaceWord: 'boy',
        focusParts: [part('b'), part('oy', true)],
        displayChunks: [chunk('b'), chunk('oy')],
        spokenChunks: [chunk('b'), chunk('oy')],
        blendSpeechText: 'boy',
        wholeWordSpeechText: 'boy',
        sentenceSpeechText: 'The happy boy waved to the crowd.',
      }),
    ],
  },
  {
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.townFair,
    gradeBand: 2,
    passageText: [
      'At the town fair, a cloud of smoke rose from the soup tent.',
      'A coin spun beside a toy wagon while the boy waited.',
      'The crowd could join the line after the snow maker started.',
      'The owl sat on the sign.',
    ].join(' '),
    sentences: [
      sentence('town-fair-1', 'At the town fair, a cloud of smoke rose from the soup tent.'),
      sentence('town-fair-2', 'A coin spun beside a toy wagon while the boy waited.'),
      sentence('town-fair-3', 'The crowd could join the line after the snow maker started.'),
      sentence('town-fair-4', 'The owl sat on the sign.'),
    ],
    readingContext: 'Word Forge Trail 2 checkpoint practice about a community fair.',
    contentVersion: OU_OI_OY_OW_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-5-cloud',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.townFair,
        sentenceId: 'town-fair-1',
        surfaceWord: 'cloud',
        focusParts: [part('cl'), part('ou', true), part('d')],
        displayChunks: [chunk('cl'), chunk('ou'), chunk('d')],
        spokenChunks: [chunk('cl'), chunk('ow'), chunk('d')],
        blendSpeechText: 'cloud',
        wholeWordSpeechText: 'cloud',
        sentenceSpeechText: 'At the town fair, a cloud of smoke rose from the soup tent.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-5-coin',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.townFair,
        sentenceId: 'town-fair-2',
        surfaceWord: 'coin',
        focusParts: [part('c'), part('oi', true), part('n')],
        displayChunks: [chunk('c'), chunk('oi'), chunk('n')],
        spokenChunks: [chunk('c'), chunk('oy'), chunk('n')],
        blendSpeechText: 'coin',
        wholeWordSpeechText: 'coin',
        sentenceSpeechText: 'A coin spun beside a toy wagon while the boy waited.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-5-toy',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.townFair,
        sentenceId: 'town-fair-2',
        surfaceWord: 'toy',
        focusParts: [part('t'), part('oy', true)],
        displayChunks: [chunk('t'), chunk('oy')],
        spokenChunks: [chunk('t'), chunk('oy')],
        blendSpeechText: 'toy',
        wholeWordSpeechText: 'toy',
        sentenceSpeechText: 'A coin spun beside a toy wagon while the boy waited.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-5-snow',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.townFair,
        sentenceId: 'town-fair-3',
        surfaceWord: 'snow',
        focusParts: [part('sn'), part('ow', true)],
        displayChunks: [chunk('sn'), chunk('ow')],
        spokenChunks: [chunk('sn'), chunk('oh')],
        blendSpeechText: 'snow',
        wholeWordSpeechText: 'snow',
        sentenceSpeechText: 'The crowd could join the line after the snow maker started.',
      }),
    ],
  },
  {
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.cleanupMarket,
    gradeBand: 2,
    passageText: [
      'During the cleanup, the team found a round sign and a loud horn.',
      'A girl used a choice card to sort each coin.',
      'Another child carried a toy crow past the window.',
      'The cow watched from the hill.',
    ].join(' '),
    sentences: [
      sentence('cleanup-market-1', 'During the cleanup, the team found a round sign and a loud horn.'),
      sentence('cleanup-market-2', 'A girl used a choice card to sort each coin.'),
      sentence('cleanup-market-3', 'Another child carried a toy crow past the window.'),
      sentence('cleanup-market-4', 'The cow watched from the hill.'),
    ],
    readingContext: 'Word Forge Trail 2 checkpoint practice about cleaning up a market area.',
    contentVersion: OU_OI_OY_OW_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-6-round',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.cleanupMarket,
        sentenceId: 'cleanup-market-1',
        surfaceWord: 'round',
        focusParts: [part('r'), part('ou', true), part('nd')],
        displayChunks: [chunk('r'), chunk('ou'), chunk('nd')],
        spokenChunks: [chunk('r'), chunk('ow'), chunk('nd')],
        blendSpeechText: 'round',
        wholeWordSpeechText: 'round',
        sentenceSpeechText: 'During the cleanup, the team found a round sign and a loud horn.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-6-choice',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.cleanupMarket,
        sentenceId: 'cleanup-market-2',
        surfaceWord: 'choice',
        focusParts: [part('ch'), part('oi', true), part('ce')],
        displayChunks: [chunk('ch'), chunk('oi'), chunk('ce')],
        spokenChunks: [chunk('ch'), chunk('oy'), chunk('ce')],
        blendSpeechText: 'choice',
        wholeWordSpeechText: 'choice',
        sentenceSpeechText: 'A girl used a choice card to sort each coin.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-6-toy',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.cleanupMarket,
        sentenceId: 'cleanup-market-3',
        surfaceWord: 'toy',
        focusParts: [part('t'), part('oy', true)],
        displayChunks: [chunk('t'), chunk('oy')],
        spokenChunks: [chunk('t'), chunk('oy')],
        blendSpeechText: 'toy',
        wholeWordSpeechText: 'toy',
        sentenceSpeechText: 'Another child carried a toy crow past the window.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-6-cow',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.cleanupMarket,
        sentenceId: 'cleanup-market-4',
        surfaceWord: 'cow',
        focusParts: [part('c'), part('ow', true)],
        displayChunks: [chunk('c'), chunk('ow')],
        spokenChunks: [chunk('c'), chunk('ow')],
        blendSpeechText: 'cow',
        wholeWordSpeechText: 'cow',
        sentenceSpeechText: 'The cow watched from the hill.',
      }),
    ],
  },
  {
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.scienceWalk,
    gradeBand: 2,
    passageText: [
      'On the science walk, the cow moved down the brown trail.',
      'The children heard the voice of the guide, and one boy held a cloud chart.',
      'They wrote the weather and the group counted the leaves.',
      'A toy bird sat near the snow fence.',
    ].join(' '),
    sentences: [
      sentence('science-walk-1', 'On the science walk, the cow moved down the brown trail.'),
      sentence('science-walk-2', 'The children heard the voice of the guide, and one boy held a cloud chart.'),
      sentence('science-walk-3', 'They wrote the weather and the group counted the leaves.'),
      sentence('science-walk-4', 'A toy bird sat near the snow fence.'),
    ],
    readingContext: 'Word Forge Trail 2 checkpoint practice on a science walk.',
    contentVersion: OU_OI_OY_OW_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-7-cow',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.scienceWalk,
        sentenceId: 'science-walk-1',
        surfaceWord: 'cow',
        focusParts: [part('c'), part('ow', true)],
        displayChunks: [chunk('c'), chunk('ow')],
        spokenChunks: [chunk('c'), chunk('ow')],
        blendSpeechText: 'cow',
        wholeWordSpeechText: 'cow',
        sentenceSpeechText: 'On the science walk, the cow moved down the brown trail.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-7-voice',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.scienceWalk,
        sentenceId: 'science-walk-2',
        surfaceWord: 'voice',
        focusParts: [part('v'), part('oi', true), part('ce')],
        displayChunks: [chunk('v'), chunk('oi'), chunk('ce')],
        spokenChunks: [chunk('v'), chunk('oy'), chunk('ce')],
        blendSpeechText: 'voice',
        wholeWordSpeechText: 'voice',
        sentenceSpeechText: 'The children heard the voice of the guide, and one boy held a cloud chart.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-7-boy',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.scienceWalk,
        sentenceId: 'science-walk-2',
        surfaceWord: 'boy',
        focusParts: [part('b'), part('oy', true)],
        displayChunks: [chunk('b'), chunk('oy')],
        spokenChunks: [chunk('b'), chunk('oy')],
        blendSpeechText: 'boy',
        wholeWordSpeechText: 'boy',
        sentenceSpeechText: 'The children heard the voice of the guide, and one boy held a cloud chart.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-ou-oi-oy-ow-7-cloud',
        passageId: OU_OI_OY_OW_PASSAGE_IDS.scienceWalk,
        sentenceId: 'science-walk-2',
        surfaceWord: 'cloud',
        focusParts: [part('cl'), part('ou', true), part('d')],
        displayChunks: [chunk('cl'), chunk('ou'), chunk('d')],
        spokenChunks: [chunk('cl'), chunk('ow'), chunk('d')],
        blendSpeechText: 'cloud',
        wholeWordSpeechText: 'cloud',
        sentenceSpeechText: 'The children heard the voice of the guide, and one boy held a cloud chart.',
      }),
    ],
  },
]
