import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from '../variableVowelsOoEa/questionFactories'
import {
  OU_OI_OY_OW_CONTENT_VERSION,
  OU_OI_OY_OW_LESSON_IDS,
  OU_OI_OY_OW_PASSAGE_IDS,
  OU_OI_OY_OW_QUESTION_IDS,
} from './ids'

const common = {
  benchmarkReference: 'ELA.2.F.1.3a',
  skillIdentifier: 'g2-word-forge-word-practice',
  prerequisiteSkillIdentifiers: [],
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'word-lab',
  estimatedReadingLevel: 'grade-2-bridge',
  reviewStatus: 'DRAFT' as const,
  contentVersion: OU_OI_OY_OW_CONTENT_VERSION,
  tags: ['grade-2', 'bridge', 'word-forge', 'ou', 'oi', 'oy', 'ow', 'guided-practice'],
}

const cloudTownSentence3 = 'The crowd helped count the cups for the soup drive.'
const toySortingSentence2 = 'A boy and a girl joined the game.'

export const buildingBlockQuestions = [
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.cloudTownBoard,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOuOwPrereq,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-ou-ow-prereq-1',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOuOwPrereq[0],
    prompt: 'Which word is spelled with ou and has the same vowel sound as loud?',
    explanation: 'Cloud is spelled with ou and has the same vowel sound as loud.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['cloud-choice'],
    targetVocabulary: ['cloud', 'count'],
    soundOutChunks: ['cl', 'ou', 'd'],
    choices: [
      { id: 'cloud-choice', text: 'cloud' },
      { id: 'coin-choice', text: 'coin' },
      { id: 'toy-choice', text: 'toy' },
      { id: 'cow-choice', text: 'cow' },
    ],
    correctChoiceIds: ['cloud-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.cloudTownBoard,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOuOwPrereq,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-ou-ow-prereq-2',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOuOwPrereq[1],
    prompt: 'Which word is spelled with ow and has the same vowel sound as grow?',
    explanation: 'Snow is spelled with ow and has the same vowel sound as grow.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['snow-choice'],
    targetVocabulary: ['snow', 'cloud'],
    soundOutChunks: ['sn', 'ow'],
    choices: [
      { id: 'snow-choice', text: 'snow' },
      { id: 'boy-choice', text: 'boy' },
      { id: 'touch-choice', text: 'touch' },
      { id: 'coin-choice', text: 'coin' },
    ],
    correctChoiceIds: ['snow-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.cloudTownBoard,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOuOwPrereq,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-ou-ow-prereq-3',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOuOwPrereq[2],
    prompt: 'Choose all the words spelled with ou that have the same vowel sound as count.',
    explanation: 'Cloud and count are spelled with ou and have the same vowel sound.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['cloud-choice', 'count-choice'],
    targetVocabulary: ['cloud', 'count', 'snow'],
    soundOutChunks: ['ou'],
    choices: [
      { id: 'cloud-choice', text: 'cloud' },
      { id: 'count-choice', text: 'count' },
      { id: 'toy-choice', text: 'toy' },
      { id: 'boy-choice', text: 'boy' },
    ],
    correctChoiceIds: ['cloud-choice', 'count-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.cloudTownBoard,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOuOwPrereq,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-ou-ow-prereq-4',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOuOwPrereq[3],
    prompt: 'Select the sentence that says the crowd helped count the cups.',
    explanation: 'The third sentence tells about the crowd helping count the cups.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['cloud-board-3'],
    targetVocabulary: ['crowd', 'count', 'cups'],
    soundOutChunks: ['count'],
    selectableSegments: [
      { id: 'cloud-board-1', text: 'The town board showed a cloud over the hill.' },
      { id: 'cloud-board-2', text: 'The snow moved in slowly.' },
      { id: 'cloud-board-3', text: cloudTownSentence3 },
    ],
    correctSegmentIds: ['cloud-board-3'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.cloudTownBoard,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOuOwPrereq,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-ou-ow-prereq-5',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOuOwPrereq[4],
    prompt: 'Which letters spell the vowel sound in loud?',
    explanation: 'The letters ou spell the vowel sound in loud.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['ou-sound'],
    targetVocabulary: ['loud', 'cloud'],
    soundOutChunks: ['l', 'ou', 'd'],
    rows: [
      {
        id: 'loud-row',
        prompt: 'loud',
        correctChoiceId: 'ou-sound',
        options: [
          { id: 'ou-sound', text: 'spelled with ou' },
          { id: 'ow-sound', text: 'spelled with ow' },
          { id: 'oi-sound', text: 'spelled with oi' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.toySorting,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOiOyPrereq,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-oi-oy-prereq-1',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOiOyPrereq[0],
    prompt: 'Which word is spelled with oi and has the same vowel sound as boil?',
    explanation: 'Coin is spelled with oi and has the same vowel sound as boil.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['coin-choice'],
    targetVocabulary: ['coin', 'join'],
    soundOutChunks: ['c', 'oi', 'n'],
    choices: [
      { id: 'toy-choice', text: 'toy' },
      { id: 'coin-choice', text: 'coin' },
      { id: 'boy-choice', text: 'boy' },
      { id: 'snow-choice', text: 'snow' },
    ],
    correctChoiceIds: ['coin-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.toySorting,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOiOyPrereq,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-oi-oy-prereq-2',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOiOyPrereq[1],
    prompt: 'Which word is spelled with oy and has the same vowel sound as joy?',
    explanation: 'Toy is spelled with oy and has the same vowel sound as joy.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['toy-choice'],
    targetVocabulary: ['toy', 'boy'],
    soundOutChunks: ['t', 'oy'],
    choices: [
      { id: 'coin-choice', text: 'coin' },
      { id: 'toy-choice', text: 'toy' },
      { id: 'join-choice', text: 'join' },
      { id: 'touch-choice', text: 'touch' },
    ],
    correctChoiceIds: ['toy-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.toySorting,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOiOyPrereq,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-oi-oy-prereq-3',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOiOyPrereq[2],
    prompt: 'Choose all the words spelled with oi that have the same vowel sound as coin.',
    explanation: 'Coin and join are spelled with oi and have the same vowel sound.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['coin-choice', 'join-choice'],
    targetVocabulary: ['coin', 'join', 'toy'],
    soundOutChunks: ['oi'],
    choices: [
      { id: 'coin-choice', text: 'coin' },
      { id: 'join-choice', text: 'join' },
      { id: 'boy-choice', text: 'boy' },
      { id: 'toy-choice', text: 'toy' },
    ],
    correctChoiceIds: ['coin-choice', 'join-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.toySorting,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOiOyPrereq,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-oi-oy-prereq-4',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOiOyPrereq[3],
    prompt: 'Select the sentence that says a boy and a girl joined the game.',
    explanation: 'The second sentence tells about a boy and a girl joining the game.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['toy-sorting-2'],
    targetVocabulary: ['boy', 'join', 'game'],
    soundOutChunks: ['join'],
    selectableSegments: [
      { id: 'toy-sorting-1', text: 'At the toy box, the team sorted each coin into a bright jar.' },
      { id: 'toy-sorting-2', text: toySortingSentence2 },
      { id: 'toy-sorting-3', text: 'They chose the right voice for each turn.' },
    ],
    correctSegmentIds: ['toy-sorting-2'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.toySorting,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOiOyPrereq,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-oi-oy-prereq-5',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOiOyPrereq[4],
    prompt: 'Which letters spell the vowel sound in toy?',
    explanation: 'The letters oy spell the vowel sound in toy.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['oy-sound'],
    targetVocabulary: ['toy', 'boy'],
    soundOutChunks: ['t', 'oy'],
    rows: [
      {
        id: 'toy-row',
        prompt: 'toy',
        correctChoiceId: 'oy-sound',
        options: [
          { id: 'oi-sound', text: 'spelled with oi' },
          { id: 'oy-sound', text: 'spelled with oy' },
          { id: 'ou-sound', text: 'spelled with ou' },
        ],
      },
    ],
  }),
]
