import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from '../variableVowelsOoEa/questionFactories'
import {
  OU_OI_OY_OW_CONTENT_VERSION,
  OU_OI_OY_OW_LESSON_IDS,
  OU_OI_OY_OW_PASSAGE_IDS,
  OU_OI_OY_OW_QUESTION_IDS,
} from './ids'

const common = {
  benchmarkReference: 'ELA.2.F.1.3a',
  skillIdentifier: 'g2-word-forge-word-practice',
  prerequisiteSkillIdentifiers: [],
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'word-lab',
  estimatedReadingLevel: 'grade-2-bridge',
  reviewStatus: 'DRAFT' as const,
  contentVersion: OU_OI_OY_OW_CONTENT_VERSION,
  tags: ['grade-2', 'bridge', 'word-forge', 'ou', 'oi', 'oy', 'ow', 'guided-practice'],
}

const soupWalkSentence2 = 'A child tried to touch the warm bowl, but the helper said to wait.'
const coinGameSentence3 = 'The voice of the announcer told the story.'

export const guidedQuestions = [
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.soupWalk,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOuOwPractice,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-ou-ow-practice-1',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOuOwPractice[0],
    prompt: 'Which word has the same ou sound as group?',
    explanation: 'Soup has one ou sound group in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['soup-choice'],
    targetVocabulary: ['group', 'soup'],
    soundOutChunks: ['s', 'ou', 'p'],
    choices: [
      { id: 'group-choice', text: 'group' },
      { id: 'soup-choice', text: 'soup' },
      { id: 'snow-choice', text: 'snow' },
      { id: 'toy-choice', text: 'toy' },
    ],
    correctChoiceIds: ['soup-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.soupWalk,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOuOwPractice,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-ou-ow-practice-2',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOuOwPractice[1],
    prompt: 'Which word has the same ow sound as grow?',
    explanation: 'Snow has the ow sound group in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['snow-choice'],
    targetVocabulary: ['snow', 'window'],
    soundOutChunks: ['sn', 'ow'],
    choices: [
      { id: 'touch-choice', text: 'touch' },
      { id: 'cloud-choice', text: 'cloud' },
      { id: 'snow-choice', text: 'snow' },
      { id: 'group-choice', text: 'group' },
    ],
    correctChoiceIds: ['snow-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.soupWalk,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOuOwPractice,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-ou-ow-practice-3',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOuOwPractice[2],
    prompt: 'Choose all the words that have ou like soup.',
    explanation: 'Group and soup show the ou sound group in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['group-choice', 'soup-choice'],
    targetVocabulary: ['group', 'soup', 'touch', 'young'],
    soundOutChunks: ['ou'],
    choices: [
      { id: 'group-choice', text: 'group' },
      { id: 'soup-choice', text: 'soup' },
      { id: 'touch-choice', text: 'touch' },
      { id: 'young-choice', text: 'young' },
    ],
    correctChoiceIds: ['group-choice', 'soup-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.soupWalk,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOuOwPractice,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-ou-ow-practice-4',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOuOwPractice[3],
    prompt: 'Select the sentence that says the child tried to touch the warm bowl.',
    explanation: 'The second sentence tells about the child touching the warm bowl.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['soup-walk-2'],
    targetVocabulary: ['touch', 'bowl', 'wait'],
    soundOutChunks: ['touch'],
    selectableSegments: [
      { id: 'soup-walk-1', text: 'The group carried soup to the house by the pond.' },
      { id: 'soup-walk-2', text: soupWalkSentence2 },
      { id: 'soup-walk-3', text: 'The young owl watched the snow from the window.' },
    ],
    correctSegmentIds: ['soup-walk-2'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.soupWalk,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOuOwPractice,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-ou-ow-practice-5',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOuOwPractice[4],
    prompt: 'Which sound group fits young?',
    explanation: 'Young belongs with the touch-style ou group in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['touch-ou-sound'],
    targetVocabulary: ['young', 'touch'],
    soundOutChunks: ['y', 'ou', 'ng'],
    rows: [
      {
        id: 'young-row',
        prompt: 'young',
        correctChoiceId: 'touch-ou-sound',
        options: [
          { id: 'touch-ou-sound', text: 'touch-style ou' },
          { id: 'ow-sound', text: 'ow sound' },
          { id: 'oi-sound', text: 'oi sound' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.coinGame,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOiOyPractice,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-oi-oy-practice-1',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOiOyPractice[0],
    prompt: 'Which word has the same oi sound as boil?',
    explanation: 'Coin has the oi sound group in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['coin-choice'],
    targetVocabulary: ['coin', 'choice'],
    soundOutChunks: ['c', 'oi', 'n'],
    choices: [
      { id: 'toy-choice', text: 'toy' },
      { id: 'choice-choice', text: 'choice' },
      { id: 'coin-choice', text: 'coin' },
      { id: 'boy-choice', text: 'boy' },
    ],
    correctChoiceIds: ['coin-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.coinGame,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOiOyPractice,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-oi-oy-practice-2',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOiOyPractice[1],
    prompt: 'Which word has the same oy sound as joy?',
    explanation: 'Toy has the oy sound group in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['toy-choice'],
    targetVocabulary: ['toy', 'boy'],
    soundOutChunks: ['t', 'oy'],
    choices: [
      { id: 'coin-choice', text: 'coin' },
      { id: 'toy-choice', text: 'toy' },
      { id: 'join-choice', text: 'join' },
      { id: 'touch-choice', text: 'touch' },
    ],
    correctChoiceIds: ['toy-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.coinGame,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOiOyPractice,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-oi-oy-practice-3',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOiOyPractice[2],
    prompt: 'Choose all the words that have oi like coin.',
    explanation: 'Coin, choice, and voice show the oi sound group in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['coin-choice', 'choice-choice', 'voice-choice'],
    targetVocabulary: ['coin', 'choice', 'voice', 'boy'],
    soundOutChunks: ['oi'],
    choices: [
      { id: 'coin-choice', text: 'coin' },
      { id: 'choice-choice', text: 'choice' },
      { id: 'voice-choice', text: 'voice' },
      { id: 'boy-choice', text: 'boy' },
    ],
    correctChoiceIds: ['coin-choice', 'choice-choice', 'voice-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.coinGame,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOiOyPractice,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-oi-oy-practice-4',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOiOyPractice[3],
    prompt: 'Select the sentence that says the voice of the announcer told the story.',
    explanation: 'The third sentence tells about the voice of the announcer.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['coin-game-3'],
    targetVocabulary: ['voice', 'story', 'announcer'],
    soundOutChunks: ['voice'],
    selectableSegments: [
      { id: 'coin-game-1', text: 'At the market, the coin jar sat beside a shiny toy.' },
      { id: 'coin-game-2', text: 'A girl said the choice was hard, but she could join the line.' },
      { id: 'coin-game-3', text: coinGameSentence3 },
    ],
    correctSegmentIds: ['coin-game-3'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.coinGame,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.guidedOiOyPractice,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-guided-oi-oy-practice-5',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.guidedOiOyPractice[4],
    prompt: 'Which sound group fits boy?',
    explanation: 'Boy belongs with the oy sound group in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['oy-sound'],
    targetVocabulary: ['boy', 'toy'],
    soundOutChunks: ['b', 'oy'],
    rows: [
      {
        id: 'boy-row',
        prompt: 'boy',
        correctChoiceId: 'oy-sound',
        options: [
          { id: 'oi-sound', text: 'oi sound' },
          { id: 'oy-sound', text: 'oy sound' },
          { id: 'ou-sound', text: 'ou sound' },
        ],
      },
    ],
  }),
]
