import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from '../variableVowelsOoEa/questionFactories'
import {
  OU_OI_OY_OW_CONTENT_VERSION,
  OU_OI_OY_OW_LESSON_IDS,
  OU_OI_OY_OW_PASSAGE_IDS,
  OU_OI_OY_OW_QUESTION_IDS,
} from './ids'

const common = {
  benchmarkReference: 'ELA.2.F.1.3a',
  skillIdentifier: 'g2-word-forge-word-practice',
  prerequisiteSkillIdentifiers: [],
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'word-lab',
  estimatedReadingLevel: 'grade-2-bridge',
  reviewStatus: 'DRAFT' as const,
  contentVersion: OU_OI_OY_OW_CONTENT_VERSION,
  tags: ['grade-2', 'bridge', 'word-forge', 'ou', 'oi', 'oy', 'ow', 'checkpoint'],
}

const townFairSentence2 = 'A coin spun beside a toy wagon while the boy waited.'
const cleanupMarketSentence3 = 'Another child carried a toy crow past the window.'
const scienceWalkSentence1 = 'On the science walk, the cow moved down the brown trail.'

export const checkpointQuestions = [
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.townFair,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-a-1',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointA[0],
    prompt: 'Which word has ou like cloud?',
    explanation: 'Cloud has ou like cloud.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['cloud-choice'],
    targetVocabulary: ['cloud', 'snow'],
    soundOutChunks: ['cl', 'ou', 'd'],
    choices: [
      { id: 'coin-choice', text: 'coin' },
      { id: 'cloud-choice', text: 'cloud' },
      { id: 'toy-choice', text: 'toy' },
      { id: 'snow-choice', text: 'snow' },
    ],
    correctChoiceIds: ['cloud-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.townFair,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-a-2',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointA[1],
    prompt: 'Which word has oi like coin?',
    explanation: 'Coin has oi like coin.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['coin-choice'],
    targetVocabulary: ['coin', 'toy'],
    soundOutChunks: ['c', 'oi', 'n'],
    choices: [
      { id: 'cloud-choice', text: 'cloud' },
      { id: 'snow-choice', text: 'snow' },
      { id: 'coin-choice', text: 'coin' },
      { id: 'toy-choice', text: 'toy' },
    ],
    correctChoiceIds: ['coin-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.townFair,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-a-3',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointA[2],
    prompt: 'Which word has oy like toy?',
    explanation: 'Toy has oy like toy.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['toy-choice'],
    targetVocabulary: ['toy', 'boy'],
    soundOutChunks: ['t', 'oy'],
    choices: [
      { id: 'cloud-choice', text: 'cloud' },
      { id: 'snow-choice', text: 'snow' },
      { id: 'boy-choice', text: 'boy' },
      { id: 'toy-choice', text: 'toy' },
    ],
    correctChoiceIds: ['toy-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.townFair,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-a-4',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointA[3],
    prompt: 'Which word has ow like snow?',
    explanation: 'Snow has ow like snow.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['snow-choice'],
    targetVocabulary: ['snow', 'owl'],
    soundOutChunks: ['sn', 'ow'],
    choices: [
      { id: 'snow-choice', text: 'snow' },
      { id: 'cloud-choice', text: 'cloud' },
      { id: 'coin-choice', text: 'coin' },
      { id: 'toy-choice', text: 'toy' },
    ],
    correctChoiceIds: ['snow-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.townFair,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-a-5',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointA[4],
    prompt: 'Choose all the words that show the Trail 2 patterns in this fair passage.',
    explanation: 'Cloud, coin, toy, and snow all show the patterns in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['cloud-choice', 'coin-choice', 'toy-choice', 'snow-choice'],
    targetVocabulary: ['cloud', 'coin', 'toy', 'snow'],
    soundOutChunks: ['ou', 'oi', 'oy', 'ow'],
    choices: [
      { id: 'cloud-choice', text: 'cloud' },
      { id: 'coin-choice', text: 'coin' },
      { id: 'toy-choice', text: 'toy' },
      { id: 'snow-choice', text: 'snow' },
    ],
    correctChoiceIds: ['cloud-choice', 'coin-choice', 'toy-choice', 'snow-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.townFair,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-a-6',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointA[5],
    prompt: 'Select the sentence that says a coin spun beside a toy wagon.',
    explanation: 'The second sentence tells about the coin and toy wagon.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['town-fair-2'],
    targetVocabulary: ['coin', 'toy', 'boy'],
    soundOutChunks: ['coin'],
    selectableSegments: [
      { id: 'town-fair-1', text: 'At the town fair, a cloud of smoke rose from the soup tent.' },
      { id: 'town-fair-2', text: townFairSentence2 },
      { id: 'town-fair-3', text: 'The crowd could join the line after the snow maker started.' },
    ],
    correctSegmentIds: ['town-fair-2'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.townFair,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-a-7',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointA[6],
    prompt: 'Match each word to its sound group.',
    explanation: 'Each word matches the sound group it shows in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['cloud-ou-sound', 'coin-oi-sound', 'toy-oy-sound', 'snow-ow-sound'],
    targetVocabulary: ['cloud', 'coin', 'toy', 'snow'],
    soundOutChunks: ['ou', 'oi', 'oy', 'ow'],
    rows: [
      {
        id: 'cloud-row',
        prompt: 'cloud',
        correctChoiceId: 'cloud-ou-sound',
        options: [
          { id: 'cloud-ou-sound', text: 'ou sound' },
          { id: 'cloud-oi-sound', text: 'oi sound' },
          { id: 'cloud-oy-sound', text: 'oy sound' },
          { id: 'cloud-ow-sound', text: 'ow sound' },
        ],
      },
      {
        id: 'coin-row',
        prompt: 'coin',
        correctChoiceId: 'coin-oi-sound',
        options: [
          { id: 'coin-ou-sound', text: 'ou sound' },
          { id: 'coin-oi-sound', text: 'oi sound' },
          { id: 'coin-oy-sound', text: 'oy sound' },
          { id: 'coin-ow-sound', text: 'ow sound' },
        ],
      },
      {
        id: 'toy-row',
        prompt: 'toy',
        correctChoiceId: 'toy-oy-sound',
        options: [
          { id: 'toy-ou-sound', text: 'ou sound' },
          { id: 'toy-oi-sound', text: 'oi sound' },
          { id: 'toy-oy-sound', text: 'oy sound' },
          { id: 'toy-ow-sound', text: 'ow sound' },
        ],
      },
      {
        id: 'snow-row',
        prompt: 'snow',
        correctChoiceId: 'snow-ow-sound',
        options: [
          { id: 'snow-ou-sound', text: 'ou sound' },
          { id: 'snow-oi-sound', text: 'oi sound' },
          { id: 'snow-oy-sound', text: 'oy sound' },
          { id: 'snow-ow-sound', text: 'ow sound' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.cleanupMarket,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-b-1',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointB[0],
    prompt: 'Which word has ou like round?',
    explanation: 'Round has ou like round.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['round-choice'],
    targetVocabulary: ['round', 'loud'],
    soundOutChunks: ['r', 'ou', 'nd'],
    choices: [
      { id: 'round-choice', text: 'round' },
      { id: 'choice-choice', text: 'choice' },
      { id: 'toy-choice', text: 'toy' },
      { id: 'cow-choice', text: 'cow' },
    ],
    correctChoiceIds: ['round-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.cleanupMarket,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-b-2',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointB[1],
    prompt: 'Which word has oi like choice?',
    explanation: 'Choice has oi like choice.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['choice-choice'],
    targetVocabulary: ['choice', 'coin'],
    soundOutChunks: ['ch', 'oi', 'ce'],
    choices: [
      { id: 'round-choice', text: 'round' },
      { id: 'choice-choice', text: 'choice' },
      { id: 'toy-choice', text: 'toy' },
      { id: 'cow-choice', text: 'cow' },
    ],
    correctChoiceIds: ['choice-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.cleanupMarket,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-b-3',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointB[2],
    prompt: 'Which word has oy like toy?',
    explanation: 'Toy has oy like toy.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['toy-choice'],
    targetVocabulary: ['toy', 'boy'],
    soundOutChunks: ['t', 'oy'],
    choices: [
      { id: 'round-choice', text: 'round' },
      { id: 'choice-choice', text: 'choice' },
      { id: 'toy-choice', text: 'toy' },
      { id: 'cow-choice', text: 'cow' },
    ],
    correctChoiceIds: ['toy-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.cleanupMarket,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-b-4',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointB[3],
    prompt: 'Which word has ow like cow?',
    explanation: 'Cow has ow like cow.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['cow-choice'],
    targetVocabulary: ['cow', 'window'],
    soundOutChunks: ['c', 'ow'],
    choices: [
      { id: 'cow-choice', text: 'cow' },
      { id: 'cloud-choice', text: 'cloud' },
      { id: 'coin-choice', text: 'coin' },
      { id: 'toy-choice', text: 'toy' },
    ],
    correctChoiceIds: ['cow-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.cleanupMarket,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-b-5',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointB[4],
    prompt: 'Choose all the words that show the Trail 2 patterns in the cleanup passage.',
    explanation: 'Round, choice, toy, and cow show the patterns in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['round-choice', 'choice-choice', 'toy-choice', 'cow-choice'],
    targetVocabulary: ['round', 'choice', 'toy', 'cow'],
    soundOutChunks: ['ou', 'oi', 'oy', 'ow'],
    choices: [
      { id: 'round-choice', text: 'round' },
      { id: 'choice-choice', text: 'choice' },
      { id: 'toy-choice', text: 'toy' },
      { id: 'cow-choice', text: 'cow' },
    ],
    correctChoiceIds: ['round-choice', 'choice-choice', 'toy-choice', 'cow-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.cleanupMarket,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-b-6',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointB[5],
    prompt: 'Select the sentence that says another child carried a toy crow past the window.',
    explanation: 'The third sentence tells about the toy crow and the window.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['cleanup-market-3'],
    targetVocabulary: ['toy', 'crow', 'window'],
    soundOutChunks: ['toy'],
    selectableSegments: [
      { id: 'cleanup-market-1', text: 'During the cleanup, the team found a round sign and a loud horn.' },
      { id: 'cleanup-market-2', text: 'A girl used a choice card to sort each coin.' },
      { id: 'cleanup-market-3', text: cleanupMarketSentence3 },
    ],
    correctSegmentIds: ['cleanup-market-3'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.cleanupMarket,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-b-7',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointB[6],
    prompt: 'Match each word to its sound group.',
    explanation: 'Each word matches the sound group it shows in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['round-ou-sound', 'choice-oi-sound', 'toy-oy-sound', 'cow-ow-sound'],
    targetVocabulary: ['round', 'choice', 'toy', 'cow'],
    soundOutChunks: ['ou', 'oi', 'oy', 'ow'],
    rows: [
      {
        id: 'round-row',
        prompt: 'round',
        correctChoiceId: 'round-ou-sound',
        options: [
          { id: 'round-ou-sound', text: 'ou sound' },
          { id: 'round-oi-sound', text: 'oi sound' },
          { id: 'round-oy-sound', text: 'oy sound' },
          { id: 'round-ow-sound', text: 'ow sound' },
        ],
      },
      {
        id: 'choice-row',
        prompt: 'choice',
        correctChoiceId: 'choice-oi-sound',
        options: [
          { id: 'choice-ou-sound', text: 'ou sound' },
          { id: 'choice-oi-sound', text: 'oi sound' },
          { id: 'choice-oy-sound', text: 'oy sound' },
          { id: 'choice-ow-sound', text: 'ow sound' },
        ],
      },
      {
        id: 'toy-row',
        prompt: 'toy',
        correctChoiceId: 'toy-oy-sound',
        options: [
          { id: 'toy-ou-sound', text: 'ou sound' },
          { id: 'toy-oi-sound', text: 'oi sound' },
          { id: 'toy-oy-sound', text: 'oy sound' },
          { id: 'toy-ow-sound', text: 'ow sound' },
        ],
      },
      {
        id: 'cow-row',
        prompt: 'cow',
        correctChoiceId: 'cow-ow-sound',
        options: [
          { id: 'cow-ou-sound', text: 'ou sound' },
          { id: 'cow-oi-sound', text: 'oi sound' },
          { id: 'cow-oy-sound', text: 'oy sound' },
          { id: 'cow-ow-sound', text: 'ow sound' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.scienceWalk,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-c-1',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointC[0],
    prompt: 'Which word has ou like cloud?',
    explanation: 'Cloud has ou like cloud.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['cloud-choice'],
    targetVocabulary: ['cloud', 'count'],
    soundOutChunks: ['cl', 'ou', 'd'],
    choices: [
      { id: 'cloud-choice', text: 'cloud' },
      { id: 'voice-choice', text: 'voice' },
      { id: 'boy-choice', text: 'boy' },
      { id: 'cow-choice', text: 'cow' },
    ],
    correctChoiceIds: ['cloud-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.scienceWalk,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-c-2',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointC[1],
    prompt: 'Which word has oi like voice?',
    explanation: 'Voice has oi like voice.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['voice-choice'],
    targetVocabulary: ['voice', 'boy'],
    soundOutChunks: ['v', 'oi', 'ce'],
    choices: [
      { id: 'cloud-choice', text: 'cloud' },
      { id: 'voice-choice', text: 'voice' },
      { id: 'toy-choice', text: 'toy' },
      { id: 'cow-choice', text: 'cow' },
    ],
    correctChoiceIds: ['voice-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.scienceWalk,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-c-3',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointC[2],
    prompt: 'Which word has oy like boy?',
    explanation: 'Boy has oy like boy.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['boy-choice'],
    targetVocabulary: ['boy', 'toy'],
    soundOutChunks: ['b', 'oy'],
    choices: [
      { id: 'cloud-choice', text: 'cloud' },
      { id: 'voice-choice', text: 'voice' },
      { id: 'boy-choice', text: 'boy' },
      { id: 'cow-choice', text: 'cow' },
    ],
    correctChoiceIds: ['boy-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.scienceWalk,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-c-4',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointC[3],
    prompt: 'Which word has ow like cow?',
    explanation: 'Cow has ow like cow.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['cow-choice'],
    targetVocabulary: ['cow', 'brown'],
    soundOutChunks: ['c', 'ow'],
    choices: [
      { id: 'cloud-choice', text: 'cloud' },
      { id: 'voice-choice', text: 'voice' },
      { id: 'boy-choice', text: 'boy' },
      { id: 'cow-choice', text: 'cow' },
    ],
    correctChoiceIds: ['cow-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.scienceWalk,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-c-5',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointC[4],
    prompt: 'Choose all the words that show the Trail 2 patterns in the science walk.',
    explanation: 'Cloud, voice, boy, and cow show the patterns in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['cloud-choice', 'voice-choice', 'boy-choice', 'cow-choice'],
    targetVocabulary: ['cloud', 'voice', 'boy', 'cow'],
    soundOutChunks: ['ou', 'oi', 'oy', 'ow'],
    choices: [
      { id: 'cloud-choice', text: 'cloud' },
      { id: 'voice-choice', text: 'voice' },
      { id: 'boy-choice', text: 'boy' },
      { id: 'cow-choice', text: 'cow' },
    ],
    correctChoiceIds: ['cloud-choice', 'voice-choice', 'boy-choice', 'cow-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.scienceWalk,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-c-6',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointC[5],
    prompt: 'Select the sentence that says the cow moved down the brown trail.',
    explanation: 'The first sentence tells about the cow on the brown trail.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['science-walk-1'],
    targetVocabulary: ['cow', 'down', 'brown'],
    soundOutChunks: ['cow'],
    selectableSegments: [
      { id: 'science-walk-1', text: scienceWalkSentence1 },
      { id: 'science-walk-2', text: 'The children heard the voice of the guide, and one boy held a cloud chart.' },
      { id: 'science-walk-3', text: 'They wrote the weather and the group counted the leaves.' },
    ],
    correctSegmentIds: ['science-walk-1'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 2,
    passageIdentifier: OU_OI_OY_OW_PASSAGE_IDS.scienceWalk,
    lessonIdentifier: OU_OI_OY_OW_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-ou-oi-oy-ow-checkpoint-c-7',
    questionIdentifier: OU_OI_OY_OW_QUESTION_IDS.checkpointC[6],
    prompt: 'Match each word to its sound group.',
    explanation: 'Each word matches the sound group it shows in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['cloud-ou-sound', 'voice-oi-sound', 'boy-oy-sound', 'cow-ow-sound'],
    targetVocabulary: ['cloud', 'voice', 'boy', 'cow'],
    soundOutChunks: ['ou', 'oi', 'oy', 'ow'],
    rows: [
      {
        id: 'cloud-row',
        prompt: 'cloud',
        correctChoiceId: 'cloud-ou-sound',
        options: [
          { id: 'cloud-ou-sound', text: 'ou sound' },
          { id: 'cloud-oi-sound', text: 'oi sound' },
          { id: 'cloud-oy-sound', text: 'oy sound' },
          { id: 'cloud-ow-sound', text: 'ow sound' },
        ],
      },
      {
        id: 'voice-row',
        prompt: 'voice',
        correctChoiceId: 'voice-oi-sound',
        options: [
          { id: 'voice-ou-sound', text: 'ou sound' },
          { id: 'voice-oi-sound', text: 'oi sound' },
          { id: 'voice-oy-sound', text: 'oy sound' },
          { id: 'voice-ow-sound', text: 'ow sound' },
        ],
      },
      {
        id: 'boy-row',
        prompt: 'boy',
        correctChoiceId: 'boy-oy-sound',
        options: [
          { id: 'boy-ou-sound', text: 'ou sound' },
          { id: 'boy-oi-sound', text: 'oi sound' },
          { id: 'boy-oy-sound', text: 'oy sound' },
          { id: 'boy-ow-sound', text: 'ow sound' },
        ],
      },
      {
        id: 'cow-row',
        prompt: 'cow',
        correctChoiceId: 'cow-ow-sound',
        options: [
          { id: 'cow-ou-sound', text: 'ou sound' },
          { id: 'cow-oi-sound', text: 'oi sound' },
          { id: 'cow-oy-sound', text: 'oy sound' },
          { id: 'cow-ow-sound', text: 'ow sound' },
        ],
      },
    ],
  }),
]
