import type { Passage, WordSupportChunk, WordSupportPart, WordSupportTarget } from '../../../../types'
import { COMMON_PREFIX_CONTENT_VERSION, COMMON_PREFIX_PASSAGE_IDS } from './ids'

const draftStatus = 'DRAFT' as const

function sentence(sentenceId: string, text: string) {
  return { sentenceId, text }
}

function chunk(displayText: string, speechText: string = displayText): WordSupportChunk {
  return { displayText, speechText }
}

function part(text: string, emphasis = false): WordSupportPart {
  return { text, emphasis }
}

function supportTarget(spec: {
  targetId: string
  passageId: string
  sentenceId: string
  surfaceWord: string
  focusParts: WordSupportPart[]
  displayChunks: WordSupportChunk[]
  spokenChunks: WordSupportChunk[]
  blendSpeechText: string
  wholeWordSpeechText: string
  sentenceSpeechText: string
}): WordSupportTarget {
  return {
    ...spec,
    reviewStatus: draftStatus,
    contentVersion: COMMON_PREFIX_CONTENT_VERSION,
  }
}

export const grade2WordForgeCommonPrefixesPassages: Passage[] = [
  {
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.rebuildCorner,
    gradeBand: 2,
    passageText: [
      'At the repair corner, the team could unpack tools and rebuild a shelf.',
      'They chose to reuse paint for the label and checked a preview card.',
      'One helper did miscount screws, so the team counted again.',
      'The kind group finished the job.',
    ].join(' '),
    sentences: [
      sentence('rebuild-corner-1', 'At the repair corner, the team could unpack tools and rebuild a shelf.'),
      sentence('rebuild-corner-2', 'They chose to reuse paint for the label and checked a preview card.'),
      sentence('rebuild-corner-3', 'One helper did miscount screws, so the team counted again.'),
      sentence('rebuild-corner-4', 'The kind group finished the job.'),
    ],
    readingContext: 'Word Forge Trail 5 practice about repairing tools and checking a plan.',
    contentVersion: COMMON_PREFIX_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-1-unpack',
        passageId: COMMON_PREFIX_PASSAGE_IDS.rebuildCorner,
        sentenceId: 'rebuild-corner-1',
        surfaceWord: 'unpack',
        focusParts: [part('un', true), part('pack')],
        displayChunks: [chunk('un'), chunk('pack')],
        spokenChunks: [chunk('un'), chunk('pack')],
        blendSpeechText: 'unpack',
        wholeWordSpeechText: 'unpack',
        sentenceSpeechText: 'At the repair corner, the team could unpack tools and rebuild a shelf.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-1-rebuild',
        passageId: COMMON_PREFIX_PASSAGE_IDS.rebuildCorner,
        sentenceId: 'rebuild-corner-1',
        surfaceWord: 'rebuild',
        focusParts: [part('re', true), part('build')],
        displayChunks: [chunk('re'), chunk('build')],
        spokenChunks: [chunk('re'), chunk('build')],
        blendSpeechText: 'rebuild',
        wholeWordSpeechText: 'rebuild',
        sentenceSpeechText: 'At the repair corner, the team could unpack tools and rebuild a shelf.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-1-reuse',
        passageId: COMMON_PREFIX_PASSAGE_IDS.rebuildCorner,
        sentenceId: 'rebuild-corner-2',
        surfaceWord: 'reuse',
        focusParts: [part('re', true), part('use')],
        displayChunks: [chunk('re'), chunk('use')],
        spokenChunks: [chunk('re'), chunk('use')],
        blendSpeechText: 'reuse',
        wholeWordSpeechText: 'reuse',
        sentenceSpeechText: 'They chose to reuse paint for the label and checked a preview card.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-1-miscount',
        passageId: COMMON_PREFIX_PASSAGE_IDS.rebuildCorner,
        sentenceId: 'rebuild-corner-3',
        surfaceWord: 'miscount',
        focusParts: [part('mis', true), part('count')],
        displayChunks: [chunk('mis'), chunk('count')],
        spokenChunks: [chunk('mis'), chunk('count')],
        blendSpeechText: 'miscount',
        wholeWordSpeechText: 'miscount',
        sentenceSpeechText: 'One helper did miscount screws, so the team counted again.',
      }),
    ],
  },
  {
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.cookingDemo,
    gradeBand: 2,
    passageText: [
      'At the cooking demo, the class had to preheat the oven before it started.',
      'They used a preview card and repainted the sign.',
      'The helper said the tray was unsafe until it cooled.',
      'Everyone waited with calm hands.',
    ].join(' '),
    sentences: [
      sentence('cooking-demo-1', 'At the cooking demo, the class had to preheat the oven before it started.'),
      sentence('cooking-demo-2', 'They used a preview card and repainted the sign.'),
      sentence('cooking-demo-3', 'The helper said the tray was unsafe until it cooled.'),
      sentence('cooking-demo-4', 'Everyone waited with calm hands.'),
    ],
    readingContext: 'Word Forge Trail 5 practice about a cooking lesson and a careful warm-up.',
    contentVersion: COMMON_PREFIX_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-2-preheat',
        passageId: COMMON_PREFIX_PASSAGE_IDS.cookingDemo,
        sentenceId: 'cooking-demo-1',
        surfaceWord: 'preheat',
        focusParts: [part('pre', true), part('heat')],
        displayChunks: [chunk('pre'), chunk('heat')],
        spokenChunks: [chunk('pre'), chunk('heat')],
        blendSpeechText: 'preheat',
        wholeWordSpeechText: 'preheat',
        sentenceSpeechText: 'At the cooking demo, the class had to preheat the oven before it started.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-2-preview',
        passageId: COMMON_PREFIX_PASSAGE_IDS.cookingDemo,
        sentenceId: 'cooking-demo-2',
        surfaceWord: 'preview',
        focusParts: [part('pre', true), part('view')],
        displayChunks: [chunk('pre'), chunk('view')],
        spokenChunks: [chunk('pre'), chunk('view')],
        blendSpeechText: 'preview',
        wholeWordSpeechText: 'preview',
        sentenceSpeechText: 'They used a preview card and repainted the sign.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-2-repaint',
        passageId: COMMON_PREFIX_PASSAGE_IDS.cookingDemo,
        sentenceId: 'cooking-demo-2',
        surfaceWord: 'repaint',
        focusParts: [part('re', true), part('paint')],
        displayChunks: [chunk('re'), chunk('paint')],
        spokenChunks: [chunk('re'), chunk('paint')],
        blendSpeechText: 'repaint',
        wholeWordSpeechText: 'repaint',
        sentenceSpeechText: 'They used a preview card and repainted the sign.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-2-unsafe',
        passageId: COMMON_PREFIX_PASSAGE_IDS.cookingDemo,
        sentenceId: 'cooking-demo-3',
        surfaceWord: 'unsafe',
        focusParts: [part('un', true), part('safe')],
        displayChunks: [chunk('un'), chunk('safe')],
        spokenChunks: [chunk('un'), chunk('safe')],
        blendSpeechText: 'unsafe',
        wholeWordSpeechText: 'unsafe',
        sentenceSpeechText: 'The helper said the tray was unsafe until it cooled.',
      }),
    ],
  },
  {
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.schoolPreview,
    gradeBand: 2,
    passageText: [
      'The school preview let families pretest the art game and hear a welcome song.',
      'A child could unroll a poster while the teacher could retell the plan.',
      'Younger guests smiled near the preschool room.',
      'The door stayed open for each visitor.',
    ].join(' '),
    sentences: [
      sentence('school-preview-1', 'The school preview let families pretest the art game and hear a welcome song.'),
      sentence('school-preview-2', 'A child could unroll a poster while the teacher could retell the plan.'),
      sentence('school-preview-3', 'Younger guests smiled near the preschool room.'),
      sentence('school-preview-4', 'The door stayed open for each visitor.'),
    ],
    readingContext: 'Word Forge Trail 5 practice about a school preview and a welcoming visit.',
    contentVersion: COMMON_PREFIX_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-3-pretest',
        passageId: COMMON_PREFIX_PASSAGE_IDS.schoolPreview,
        sentenceId: 'school-preview-1',
        surfaceWord: 'pretest',
        focusParts: [part('pre', true), part('test')],
        displayChunks: [chunk('pre'), chunk('test')],
        spokenChunks: [chunk('pre'), chunk('test')],
        blendSpeechText: 'pretest',
        wholeWordSpeechText: 'pretest',
        sentenceSpeechText: 'The school preview let families pretest the art game and hear a welcome song.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-3-unroll',
        passageId: COMMON_PREFIX_PASSAGE_IDS.schoolPreview,
        sentenceId: 'school-preview-2',
        surfaceWord: 'unroll',
        focusParts: [part('un', true), part('roll')],
        displayChunks: [chunk('un'), chunk('roll')],
        spokenChunks: [chunk('un'), chunk('roll')],
        blendSpeechText: 'unroll',
        wholeWordSpeechText: 'unroll',
        sentenceSpeechText: 'A child could unroll a poster while the teacher could retell the plan.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-3-retell',
        passageId: COMMON_PREFIX_PASSAGE_IDS.schoolPreview,
        sentenceId: 'school-preview-2',
        surfaceWord: 'retell',
        focusParts: [part('re', true), part('tell')],
        displayChunks: [chunk('re'), chunk('tell')],
        spokenChunks: [chunk('re'), chunk('tell')],
        blendSpeechText: 'retell',
        wholeWordSpeechText: 'retell',
        sentenceSpeechText: 'A child could unroll a poster while the teacher could retell the plan.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-3-preschool',
        passageId: COMMON_PREFIX_PASSAGE_IDS.schoolPreview,
        sentenceId: 'school-preview-3',
        surfaceWord: 'preschool',
        focusParts: [part('pre', true), part('school')],
        displayChunks: [chunk('pre'), chunk('school')],
        spokenChunks: [chunk('pre'), chunk('school')],
        blendSpeechText: 'preschool',
        wholeWordSpeechText: 'preschool',
        sentenceSpeechText: 'Younger guests smiled near the preschool room.',
      }),
    ],
  },
  {
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.scienceNotebook,
    gradeBand: 2,
    passageText: [
      'The science team did not disagree about the magnet test.',
      'One child could misplace the chart, then find it again.',
      'They did not disconnect the cord, and they would not disobey the safety rule.',
      'The notebook stayed neat.',
    ].join(' '),
    sentences: [
      sentence('science-notebook-1', 'The science team did not disagree about the magnet test.'),
      sentence('science-notebook-2', 'One child could misplace the chart, then find it again.'),
      sentence('science-notebook-3', 'They did not disconnect the cord, and they would not disobey the safety rule.'),
      sentence('science-notebook-4', 'The notebook stayed neat.'),
    ],
    readingContext: 'Word Forge Trail 5 practice about a science notebook and a careful lab rule.',
    contentVersion: COMMON_PREFIX_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-4-disagree',
        passageId: COMMON_PREFIX_PASSAGE_IDS.scienceNotebook,
        sentenceId: 'science-notebook-1',
        surfaceWord: 'disagree',
        focusParts: [part('dis', true), part('agree')],
        displayChunks: [chunk('dis'), chunk('agree')],
        spokenChunks: [chunk('dis'), chunk('agree')],
        blendSpeechText: 'disagree',
        wholeWordSpeechText: 'disagree',
        sentenceSpeechText: 'The science team did not disagree about the magnet test.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-4-misplace',
        passageId: COMMON_PREFIX_PASSAGE_IDS.scienceNotebook,
        sentenceId: 'science-notebook-2',
        surfaceWord: 'misplace',
        focusParts: [part('mis', true), part('place')],
        displayChunks: [chunk('mis'), chunk('place')],
        spokenChunks: [chunk('mis'), chunk('place')],
        blendSpeechText: 'misplace',
        wholeWordSpeechText: 'misplace',
        sentenceSpeechText: 'One child could misplace the chart, then find it again.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-4-disconnect',
        passageId: COMMON_PREFIX_PASSAGE_IDS.scienceNotebook,
        sentenceId: 'science-notebook-3',
        surfaceWord: 'disconnect',
        focusParts: [part('dis', true), part('connect')],
        displayChunks: [chunk('dis'), chunk('connect')],
        spokenChunks: [chunk('dis'), chunk('connect')],
        blendSpeechText: 'disconnect',
        wholeWordSpeechText: 'disconnect',
        sentenceSpeechText: 'They did not disconnect the cord, and they would not disobey the safety rule.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-4-disobey',
        passageId: COMMON_PREFIX_PASSAGE_IDS.scienceNotebook,
        sentenceId: 'science-notebook-3',
        surfaceWord: 'disobey',
        focusParts: [part('dis', true), part('obey')],
        displayChunks: [chunk('dis'), chunk('obey')],
        spokenChunks: [chunk('dis'), chunk('obey')],
        blendSpeechText: 'disobey',
        wholeWordSpeechText: 'disobey',
        sentenceSpeechText: 'They did not disconnect the cord, and they would not disobey the safety rule.',
      }),
    ],
  },
  {
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.readingCircle,
    gradeBand: 2,
    passageText: [
      'In reading circle, a child felt unhappy when a page was hard, but a partner helped her unlock a clue.',
      'They could replay the sound and avoid an unkind remark.',
      'The group retold the story.',
      'No one rushed.',
    ].join(' '),
    sentences: [
      sentence('reading-circle-1', 'In reading circle, a child felt unhappy when a page was hard, but a partner helped her unlock a clue.'),
      sentence('reading-circle-2', 'They could replay the sound and avoid an unkind remark.'),
      sentence('reading-circle-3', 'The group retold the story.'),
      sentence('reading-circle-4', 'No one rushed.'),
    ],
    readingContext: 'Word Forge Trail 5 practice about reading help and careful word choices.',
    contentVersion: COMMON_PREFIX_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-5-unhappy',
        passageId: COMMON_PREFIX_PASSAGE_IDS.readingCircle,
        sentenceId: 'reading-circle-1',
        surfaceWord: 'unhappy',
        focusParts: [part('un', true), part('happy')],
        displayChunks: [chunk('un'), chunk('happy')],
        spokenChunks: [chunk('un'), chunk('happy')],
        blendSpeechText: 'unhappy',
        wholeWordSpeechText: 'unhappy',
        sentenceSpeechText: 'In reading circle, a child felt unhappy when a page was hard, but a partner helped her unlock a clue.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-5-unlock',
        passageId: COMMON_PREFIX_PASSAGE_IDS.readingCircle,
        sentenceId: 'reading-circle-1',
        surfaceWord: 'unlock',
        focusParts: [part('un', true), part('lock')],
        displayChunks: [chunk('un'), chunk('lock')],
        spokenChunks: [chunk('un'), chunk('lock')],
        blendSpeechText: 'unlock',
        wholeWordSpeechText: 'unlock',
        sentenceSpeechText: 'In reading circle, a child felt unhappy when a page was hard, but a partner helped her unlock a clue.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-5-replay',
        passageId: COMMON_PREFIX_PASSAGE_IDS.readingCircle,
        sentenceId: 'reading-circle-2',
        surfaceWord: 'replay',
        focusParts: [part('re', true), part('play')],
        displayChunks: [chunk('re'), chunk('play')],
        spokenChunks: [chunk('re'), chunk('play')],
        blendSpeechText: 'replay',
        wholeWordSpeechText: 'replay',
        sentenceSpeechText: 'They could replay the sound and avoid an unkind remark.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-5-unkind',
        passageId: COMMON_PREFIX_PASSAGE_IDS.readingCircle,
        sentenceId: 'reading-circle-2',
        surfaceWord: 'unkind',
        focusParts: [part('un', true), part('kind')],
        displayChunks: [chunk('un'), chunk('kind')],
        spokenChunks: [chunk('un'), chunk('kind')],
        blendSpeechText: 'unkind',
        wholeWordSpeechText: 'unkind',
        sentenceSpeechText: 'They could replay the sound and avoid an unkind remark.',
      }),
    ],
  },
  {
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.supplyCart,
    gradeBand: 2,
    passageText: [
      'At the supply cart, the class did not miscount the crayons.',
      'A helper can misspell the label and notice a misprint on the sign.',
      'Two children unrolled the chart.',
      'The board stayed steady.',
    ].join(' '),
    sentences: [
      sentence('supply-cart-1', 'At the supply cart, the class did not miscount the crayons.'),
      sentence('supply-cart-2', 'A helper can misspell the label and notice a misprint on the sign.'),
      sentence('supply-cart-3', 'Two children unrolled the chart.'),
      sentence('supply-cart-4', 'The board stayed steady.'),
    ],
    readingContext: 'Word Forge Trail 5 practice about a supply cart and careful checking.',
    contentVersion: COMMON_PREFIX_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-6-miscount',
        passageId: COMMON_PREFIX_PASSAGE_IDS.supplyCart,
        sentenceId: 'supply-cart-1',
        surfaceWord: 'miscount',
        focusParts: [part('mis', true), part('count')],
        displayChunks: [chunk('mis'), chunk('count')],
        spokenChunks: [chunk('mis'), chunk('count')],
        blendSpeechText: 'miscount',
        wholeWordSpeechText: 'miscount',
        sentenceSpeechText: 'At the supply cart, the class did not miscount the crayons.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-6-misspell',
        passageId: COMMON_PREFIX_PASSAGE_IDS.supplyCart,
        sentenceId: 'supply-cart-2',
        surfaceWord: 'misspell',
        focusParts: [part('mis', true), part('spell')],
        displayChunks: [chunk('mis'), chunk('spell')],
        spokenChunks: [chunk('mis'), chunk('spell')],
        blendSpeechText: 'misspell',
        wholeWordSpeechText: 'misspell',
        sentenceSpeechText: 'A helper can misspell the label and notice a misprint on the sign.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-6-misprint',
        passageId: COMMON_PREFIX_PASSAGE_IDS.supplyCart,
        sentenceId: 'supply-cart-2',
        surfaceWord: 'misprint',
        focusParts: [part('mis', true), part('print')],
        displayChunks: [chunk('mis'), chunk('print')],
        spokenChunks: [chunk('mis'), chunk('print')],
        blendSpeechText: 'misprint',
        wholeWordSpeechText: 'misprint',
        sentenceSpeechText: 'A helper can misspell the label and notice a misprint on the sign.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-6-unroll',
        passageId: COMMON_PREFIX_PASSAGE_IDS.supplyCart,
        sentenceId: 'supply-cart-3',
        surfaceWord: 'unroll',
        focusParts: [part('un', true), part('roll')],
        displayChunks: [chunk('un'), chunk('roll')],
        spokenChunks: [chunk('un'), chunk('roll')],
        blendSpeechText: 'unroll',
        wholeWordSpeechText: 'unroll',
        sentenceSpeechText: 'Two children unrolled the chart.',
      }),
    ],
  },
  {
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.communityProject,
    gradeBand: 2,
    passageText: [
      'For the community project, children unpack boxes, rebuild a shelf, and preheat soup for the helpers.',
      'They did not dislike the plan or ignore the clean-up chart.',
      'The group retold the steps, then painted a sign.',
      'A leader checked the work.',
    ].join(' '),
    sentences: [
      sentence('community-project-1', 'For the community project, children unpack boxes, rebuild a shelf, and preheat soup for the helpers.'),
      sentence('community-project-2', 'They did not dislike the plan or ignore the clean-up chart.'),
      sentence('community-project-3', 'The group retold the steps, then painted a sign.'),
      sentence('community-project-4', 'A leader checked the work.'),
    ],
    readingContext: 'Word Forge Trail 5 practice about community helpers and a shared project.',
    contentVersion: COMMON_PREFIX_CONTENT_VERSION,
    reviewStatus: draftStatus,
    wordSupportTargets: [
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-7-unpack',
        passageId: COMMON_PREFIX_PASSAGE_IDS.communityProject,
        sentenceId: 'community-project-1',
        surfaceWord: 'unpack',
        focusParts: [part('un', true), part('pack')],
        displayChunks: [chunk('un'), chunk('pack')],
        spokenChunks: [chunk('un'), chunk('pack')],
        blendSpeechText: 'unpack',
        wholeWordSpeechText: 'unpack',
        sentenceSpeechText: 'For the community project, children unpack boxes, rebuild a shelf, and preheat soup for the helpers.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-7-rebuild',
        passageId: COMMON_PREFIX_PASSAGE_IDS.communityProject,
        sentenceId: 'community-project-1',
        surfaceWord: 'rebuild',
        focusParts: [part('re', true), part('build')],
        displayChunks: [chunk('re'), chunk('build')],
        spokenChunks: [chunk('re'), chunk('build')],
        blendSpeechText: 'rebuild',
        wholeWordSpeechText: 'rebuild',
        sentenceSpeechText: 'For the community project, children unpack boxes, rebuild a shelf, and preheat soup for the helpers.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-7-preheat',
        passageId: COMMON_PREFIX_PASSAGE_IDS.communityProject,
        sentenceId: 'community-project-1',
        surfaceWord: 'preheat',
        focusParts: [part('pre', true), part('heat')],
        displayChunks: [chunk('pre'), chunk('heat')],
        spokenChunks: [chunk('pre'), chunk('heat')],
        blendSpeechText: 'preheat',
        wholeWordSpeechText: 'preheat',
        sentenceSpeechText: 'For the community project, children unpack boxes, rebuild a shelf, and preheat soup for the helpers.',
      }),
      supportTarget({
        targetId: 'target-g2-word-forge-common-prefixes-7-dislike',
        passageId: COMMON_PREFIX_PASSAGE_IDS.communityProject,
        sentenceId: 'community-project-2',
        surfaceWord: 'dislike',
        focusParts: [part('dis', true), part('like')],
        displayChunks: [chunk('dis'), chunk('like')],
        spokenChunks: [chunk('dis'), chunk('like')],
        blendSpeechText: 'dislike',
        wholeWordSpeechText: 'dislike',
        sentenceSpeechText: 'They did not dislike the plan or ignore the clean-up chart.',
      }),
    ],
  },
]
