import type { ReadingQuestion } from '../../../../types'
import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from '../variableVowelsOoEa/questionFactories'
import {
  COMMON_PREFIX_CONTENT_VERSION,
  COMMON_PREFIX_LESSON_IDS,
  COMMON_PREFIX_PASSAGE_IDS,
  COMMON_PREFIX_QUESTION_IDS,
} from './ids'

const common = {
  benchmarkReference: 'ELA.2.F.1.3d',
  skillIdentifier: 'g2-word-forge-word-practice',
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'Word Forge',
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2',
  contentVersion: COMMON_PREFIX_CONTENT_VERSION,
  reviewStatus: 'DRAFT' as const,
}

export const checkpointQuestions: ReadingQuestion[] = [
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.readingCircle,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-a-1',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointA[0],
    prompt: 'Which word means not happy?',
    explanation: 'Unhappy begins with un-, and happy is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['unhappy-choice'],
    targetVocabulary: ['unhappy', 'unlock', 'replay', 'unkind'],
    soundOutChunks: ['un', 'happy'],
    tags: ['common-prefixes', 'prefix-un', 'base-word'],
    choices: [
      { id: 'happy-choice', text: 'happy' },
      { id: 'replay-choice', text: 'replay' },
      { id: 'unlock-choice', text: 'unlock' },
      { id: 'unhappy-choice', text: 'unhappy' },
    ],
    correctChoiceIds: ['unhappy-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.readingCircle,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-a-2',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointA[1],
    prompt: 'Which word has the prefix re- and means play again?',
    explanation: 'Replay begins with re-, and play is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['replay-choice'],
    targetVocabulary: ['unhappy', 'unlock', 'replay', 'unkind'],
    soundOutChunks: ['re', 'play'],
    tags: ['common-prefixes', 'prefix-re', 'base-word'],
    choices: [
      { id: 'unlock-choice', text: 'unlock' },
      { id: 'unkind-choice', text: 'unkind' },
      { id: 'happy-choice', text: 'happy' },
      { id: 'replay-choice', text: 'replay' },
    ],
    correctChoiceIds: ['replay-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.communityProject,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-a-3',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointA[2],
    prompt: 'Which word has the prefix pre- and means before heat?',
    explanation: 'Preheat begins with pre-, and heat is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['preheat-choice'],
    targetVocabulary: ['unpack', 'rebuild', 'preheat', 'dislike'],
    soundOutChunks: ['pre', 'heat'],
    tags: ['common-prefixes', 'prefix-pre', 'base-word'],
    choices: [
      { id: 'rebuild-choice', text: 'rebuild' },
      { id: 'dislike-choice', text: 'dislike' },
      { id: 'unpack-choice', text: 'unpack' },
      { id: 'preheat-choice', text: 'preheat' },
    ],
    correctChoiceIds: ['preheat-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.communityProject,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-a-4',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointA[3],
    prompt: 'What is the base word in rebuild?',
    explanation: 'Build is the base word after the re- prefix is removed.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['build-choice'],
    targetVocabulary: ['unpack', 'rebuild', 'preheat', 'dislike'],
    soundOutChunks: ['re', 'build'],
    tags: ['common-prefixes', 'prefix-re', 'base-word'],
    choices: [
      { id: 're-choice', text: 're' },
      { id: 'heat-choice', text: 'heat' },
      { id: 'build-choice', text: 'build' },
      { id: 'pack-choice', text: 'pack' },
    ],
    correctChoiceIds: ['build-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.supplyCart,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-a-5',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointA[4],
    prompt: 'Choose all the words with prefixes in the supply cart passage.',
    explanation: 'Miscount, misspell, misprint, and unroll all begin with common prefixes.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['miscount-choice', 'misspell-choice', 'misprint-choice', 'unroll-choice'],
    targetVocabulary: ['miscount', 'misspell', 'misprint', 'unroll'],
    soundOutChunks: ['mis', 'count', 'mis', 'spell', 'mis', 'print', 'un', 'roll'],
    tags: ['common-prefixes', 'prefix-mis', 'prefix-un', 'base-word'],
    choices: [
      { id: 'miscount-choice', text: 'miscount' },
      { id: 'misspell-choice', text: 'misspell' },
      { id: 'misprint-choice', text: 'misprint' },
      { id: 'unroll-choice', text: 'unroll' },
    ],
    correctChoiceIds: ['miscount-choice', 'misspell-choice', 'misprint-choice', 'unroll-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.communityProject,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-a-6',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointA[5],
    prompt: 'Select the sentence that says children unpack boxes, rebuild a shelf, and preheat soup for the helpers.',
    explanation: 'The first sentence gives the clue about unpack, rebuild, and preheat.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['community-project-1'],
    targetVocabulary: ['unpack', 'rebuild', 'preheat'],
    soundOutChunks: ['un', 'pack'],
    tags: ['common-prefixes', 'prefix-un', 'prefix-re', 'prefix-pre'],
    selectableSegments: [
      { id: 'community-project-1', text: 'For the community project, children unpack boxes, rebuild a shelf, and preheat soup for the helpers.' },
      { id: 'community-project-2', text: 'They did not dislike the plan or ignore the clean-up chart.' },
      { id: 'community-project-3', text: 'The group retold the steps, then painted a sign.' },
    ],
    correctSegmentIds: ['community-project-1'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.communityProject,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-a-7',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointA[6],
    prompt: 'Match each word to its split.',
    explanation: 'Each word matches the authored prefix and base word split in the lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['unpack-split', 'rebuild-split', 'preheat-split', 'dislike-split'],
    targetVocabulary: ['unpack', 'rebuild', 'preheat', 'dislike'],
    soundOutChunks: ['un', 'pack', 're', 'build', 'pre', 'heat', 'dis', 'like'],
    tags: ['common-prefixes', 'prefix-un', 'prefix-re', 'prefix-pre', 'prefix-dis', 'base-word'],
    rows: [
      {
        id: 'unpack-row',
        prompt: 'unpack',
        correctChoiceId: 'unpack-split',
        options: [
          { id: 'unpack-split', text: 'un | pack' },
          { id: 'unpack-mis1', text: 'u | npack' },
          { id: 'unpack-mis2', text: 'unp | ack' },
          { id: 'unpack-mis3', text: 'un | p ack' },
        ],
      },
      {
        id: 'rebuild-row',
        prompt: 'rebuild',
        correctChoiceId: 'rebuild-split',
        options: [
          { id: 'rebuild-mis1', text: 'reb | uild' },
          { id: 'rebuild-split', text: 're | build' },
          { id: 'rebuild-mis2', text: 're | b uild' },
          { id: 'rebuild-mis3', text: 'r | ebuild' },
        ],
      },
      {
        id: 'preheat-row',
        prompt: 'preheat',
        correctChoiceId: 'preheat-split',
        options: [
          { id: 'preheat-split', text: 'pre | heat' },
          { id: 'preheat-mis1', text: 'preh | eat' },
          { id: 'preheat-mis2', text: 'pr | eheat' },
          { id: 'preheat-mis3', text: 'pre | h eat' },
        ],
      },
      {
        id: 'dislike-row',
        prompt: 'dislike',
        correctChoiceId: 'dislike-split',
        options: [
          { id: 'dislike-mis1', text: 'disl | ike' },
          { id: 'dislike-split', text: 'dis | like' },
          { id: 'dislike-mis2', text: 'di | slike' },
          { id: 'dislike-mis3', text: 'dis | l ike' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.cookingDemo,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-b-1',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointB[0],
    prompt: 'Which word means not safe?',
    explanation: 'Unsafe begins with un-, and safe is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['unsafe-choice'],
    targetVocabulary: ['unsafe', 'repaint', 'preheat', 'preview'],
    soundOutChunks: ['un', 'safe'],
    tags: ['common-prefixes', 'prefix-un', 'base-word'],
    choices: [
      { id: 'preview-choice', text: 'preview' },
      { id: 'repaint-choice', text: 'repaint' },
      { id: 'safe-choice', text: 'safe' },
      { id: 'unsafe-choice', text: 'unsafe' },
    ],
    correctChoiceIds: ['unsafe-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.cookingDemo,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-b-2',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointB[1],
    prompt: 'Which word has the prefix re- and means paint again?',
    explanation: 'Repaint begins with re-, and paint is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['repaint-choice'],
    targetVocabulary: ['unsafe', 'repaint', 'preheat', 'preview'],
    soundOutChunks: ['re', 'paint'],
    tags: ['common-prefixes', 'prefix-re', 'base-word'],
    choices: [
      { id: 'preheat-choice', text: 'preheat' },
      { id: 'unsafe-choice', text: 'unsafe' },
      { id: 'preview-choice', text: 'preview' },
      { id: 'repaint-choice', text: 'repaint' },
    ],
    correctChoiceIds: ['repaint-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.scienceNotebook,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-b-3',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointB[2],
    prompt: 'Which word has the prefix mis- and means to put in the wrong place?',
    explanation: 'Misplace begins with mis-, and place is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['misplace-choice'],
    targetVocabulary: ['disagree', 'misplace', 'disconnect', 'disobey'],
    soundOutChunks: ['mis', 'place'],
    tags: ['common-prefixes', 'prefix-mis', 'base-word'],
    choices: [
      { id: 'disconnect-choice', text: 'disconnect' },
      { id: 'disagree-choice', text: 'disagree' },
      { id: 'misplace-choice', text: 'misplace' },
      { id: 'disobey-choice', text: 'disobey' },
    ],
    correctChoiceIds: ['misplace-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.scienceNotebook,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-b-4',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointB[3],
    prompt: 'Choose all the words with prefixes in the science notebook passage.',
    explanation: 'Disagree, misplace, disconnect, and disobey all begin with common prefixes.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['disagree-choice', 'misplace-choice', 'disconnect-choice', 'disobey-choice'],
    targetVocabulary: ['disagree', 'misplace', 'disconnect', 'disobey'],
    soundOutChunks: ['dis', 'agree', 'mis', 'place', 'dis', 'connect', 'dis', 'obey'],
    tags: ['common-prefixes', 'prefix-dis', 'prefix-mis', 'base-word'],
    choices: [
      { id: 'disagree-choice', text: 'disagree' },
      { id: 'misplace-choice', text: 'misplace' },
      { id: 'disconnect-choice', text: 'disconnect' },
      { id: 'disobey-choice', text: 'disobey' },
    ],
    correctChoiceIds: ['disagree-choice', 'misplace-choice', 'disconnect-choice', 'disobey-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.schoolPreview,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-b-5',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointB[4],
    prompt: 'Select the sentence that says the school preview let families pretest the art game and hear a welcome song.',
    explanation: 'The first sentence gives the clue about the school preview and the pretest.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['school-preview-1'],
    targetVocabulary: ['pretest', 'unroll', 'retell'],
    soundOutChunks: ['pre', 'test'],
    tags: ['common-prefixes', 'prefix-pre'],
    selectableSegments: [
      { id: 'school-preview-1', text: 'The school preview let families pretest the art game and hear a welcome song.' },
      { id: 'school-preview-2', text: 'A child could unroll a poster while the teacher could retell the plan.' },
      { id: 'school-preview-3', text: 'Younger guests smiled near the preschool room.' },
    ],
    correctSegmentIds: ['school-preview-1'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.scienceNotebook,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-b-6',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointB[5],
    prompt: 'Choose all the words in the science notebook passage that begin with dis-.',
    explanation: 'Disagree, disconnect, and disobey all begin with the dis- prefix.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['disagree-choice', 'disconnect-choice', 'disobey-choice'],
    targetVocabulary: ['disagree', 'misplace', 'disconnect', 'disobey'],
    soundOutChunks: ['dis', 'agree', 'dis', 'connect', 'dis', 'obey'],
    tags: ['common-prefixes', 'prefix-dis'],
    choices: [
      { id: 'disagree-choice', text: 'disagree' },
      { id: 'misplace-choice', text: 'misplace' },
      { id: 'disconnect-choice', text: 'disconnect' },
      { id: 'disobey-choice', text: 'disobey' },
    ],
    correctChoiceIds: ['disagree-choice', 'disconnect-choice', 'disobey-choice'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.scienceNotebook,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-b-7',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointB[6],
    prompt: 'Match each word to its split.',
    explanation: 'Each word matches the authored prefix and base word split in the lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['disagree-split', 'misplace-split', 'disconnect-split', 'disobey-split'],
    targetVocabulary: ['disagree', 'misplace', 'disconnect', 'disobey'],
    soundOutChunks: ['dis', 'agree', 'mis', 'place', 'dis', 'connect', 'dis', 'obey'],
    tags: ['common-prefixes', 'prefix-dis', 'prefix-mis', 'base-word'],
    rows: [
      {
        id: 'disagree-row',
        prompt: 'disagree',
        correctChoiceId: 'disagree-split',
        options: [
          { id: 'disagree-split', text: 'dis | agree' },
          { id: 'disagree-mis1', text: 'disa | gree' },
          { id: 'disagree-mis2', text: 'dis | ag ree' },
          { id: 'disagree-mis3', text: 'dis | a gree' },
        ],
      },
      {
        id: 'misplace-row',
        prompt: 'misplace',
        correctChoiceId: 'misplace-split',
        options: [
          { id: 'misplace-split', text: 'mis | place' },
          { id: 'misplace-mis1', text: 'misp | lace' },
          { id: 'misplace-mis2', text: 'mis | pl ace' },
          { id: 'misplace-mis3', text: 'mi | splace' },
        ],
      },
      {
        id: 'disconnect-row',
        prompt: 'disconnect',
        correctChoiceId: 'disconnect-split',
        options: [
          { id: 'disconnect-mis1', text: 'disco | nnect' },
          { id: 'disconnect-split', text: 'dis | connect' },
          { id: 'disconnect-mis2', text: 'dis | con nect' },
          { id: 'disconnect-mis3', text: 'd | isconnect' },
        ],
      },
      {
        id: 'disobey-row',
        prompt: 'disobey',
        correctChoiceId: 'disobey-split',
        options: [
          { id: 'disobey-split', text: 'dis | obey' },
          { id: 'disobey-mis1', text: 'diso | bey' },
          { id: 'disobey-mis2', text: 'dis | o bey' },
          { id: 'disobey-mis3', text: 'd | isobey' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.schoolPreview,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-c-1',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointC[0],
    prompt: 'Which word has the prefix pre- and means before test?',
    explanation: 'Pretest begins with pre-, and test is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['pretest-choice'],
    targetVocabulary: ['pretest', 'unroll', 'retell', 'preschool'],
    soundOutChunks: ['pre', 'test'],
    tags: ['common-prefixes', 'prefix-pre', 'base-word'],
    choices: [
      { id: 'retell-choice', text: 'retell' },
      { id: 'preschool-choice', text: 'preschool' },
      { id: 'unroll-choice', text: 'unroll' },
      { id: 'pretest-choice', text: 'pretest' },
    ],
    correctChoiceIds: ['pretest-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.scienceNotebook,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-c-2',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointC[1],
    prompt: 'Which word has the prefix dis- and means not obey?',
    explanation: 'Disobey begins with dis-, and obey is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['disobey-choice'],
    targetVocabulary: ['disagree', 'misplace', 'disconnect', 'disobey'],
    soundOutChunks: ['dis', 'obey'],
    tags: ['common-prefixes', 'prefix-dis', 'base-word'],
    choices: [
      { id: 'misplace-choice', text: 'misplace' },
      { id: 'disconnect-choice', text: 'disconnect' },
      { id: 'disagree-choice', text: 'disagree' },
      { id: 'disobey-choice', text: 'disobey' },
    ],
    correctChoiceIds: ['disobey-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.readingCircle,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-c-3',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointC[2],
    prompt: 'Which word has the prefix un- and means not kind?',
    explanation: 'Unkind begins with un-, and kind is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['unkind-choice'],
    targetVocabulary: ['unhappy', 'unlock', 'replay', 'unkind'],
    soundOutChunks: ['un', 'kind'],
    tags: ['common-prefixes', 'prefix-un', 'base-word'],
    choices: [
      { id: 'replay-choice', text: 'replay' },
      { id: 'unlock-choice', text: 'unlock' },
      { id: 'happy-choice', text: 'happy' },
      { id: 'unkind-choice', text: 'unkind' },
    ],
    correctChoiceIds: ['unkind-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.readingCircle,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-c-4',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointC[3],
    prompt: 'Choose all the words with prefixes in the reading circle passage.',
    explanation: 'Unhappy, unlock, replay, and unkind all begin with common prefixes.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['unhappy-choice', 'unlock-choice', 'replay-choice', 'unkind-choice'],
    targetVocabulary: ['unhappy', 'unlock', 'replay', 'unkind'],
    soundOutChunks: ['un', 'happy', 'un', 'lock', 're', 'play', 'un', 'kind'],
    tags: ['common-prefixes', 'prefix-un', 'prefix-re', 'base-word'],
    choices: [
      { id: 'unhappy-choice', text: 'unhappy' },
      { id: 'unlock-choice', text: 'unlock' },
      { id: 'replay-choice', text: 'replay' },
      { id: 'unkind-choice', text: 'unkind' },
    ],
    correctChoiceIds: ['unhappy-choice', 'unlock-choice', 'replay-choice', 'unkind-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.schoolPreview,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-c-5',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointC[4],
    prompt: 'Select the sentence that says a child could unroll a poster while the teacher retold the plan.',
    explanation: 'The second sentence gives the clue about unroll and retell.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['school-preview-2'],
    targetVocabulary: ['unroll', 'retell', 'preschool'],
    soundOutChunks: ['un', 'roll'],
    tags: ['common-prefixes', 'prefix-un', 'prefix-re'],
    selectableSegments: [
      { id: 'school-preview-1', text: 'The school preview let families pretest the art game and hear a welcome song.' },
      { id: 'school-preview-2', text: 'A child could unroll a poster while the teacher could retell the plan.' },
      { id: 'school-preview-3', text: 'Younger guests smiled near the preschool room.' },
    ],
    correctSegmentIds: ['school-preview-2'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.supplyCart,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-c-6',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointC[5],
    prompt: 'Select the sentence that says a helper can misspell the label and notice a misprint on the sign.',
    explanation: 'The second sentence gives the clue about misspell and misprint.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['supply-cart-2'],
    targetVocabulary: ['miscount', 'misspell', 'misprint', 'unroll'],
    soundOutChunks: ['mis', 'spell'],
    tags: ['common-prefixes', 'prefix-mis', 'prefix-un'],
    selectableSegments: [
      { id: 'supply-cart-1', text: 'At the supply cart, the class did not miscount the crayons.' },
      { id: 'supply-cart-2', text: 'A helper can misspell the label and notice a misprint on the sign.' },
      { id: 'supply-cart-3', text: 'Two children unrolled the chart.' },
    ],
    correctSegmentIds: ['supply-cart-2'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.schoolPreview,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-common-prefixes-checkpoint-c-7',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.checkpointC[6],
    prompt: 'Match each word to its split.',
    explanation: 'Each word matches the authored prefix and base word split in the lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['pretest-split', 'unroll-split', 'retell-split', 'preschool-split'],
    targetVocabulary: ['pretest', 'unroll', 'retell', 'preschool'],
    soundOutChunks: ['pre', 'test', 'un', 'roll', 're', 'tell', 'pre', 'school'],
    tags: ['common-prefixes', 'prefix-pre', 'prefix-un', 'prefix-re', 'base-word'],
    rows: [
      {
        id: 'pretest-row',
        prompt: 'pretest',
        correctChoiceId: 'pretest-split',
        options: [
          { id: 'pretest-split', text: 'pre | test' },
          { id: 'pretest-mis1', text: 'pr | etest' },
          { id: 'pretest-mis2', text: 'pret | est' },
          { id: 'pretest-mis3', text: 'pre | t est' },
        ],
      },
      {
        id: 'unroll-row',
        prompt: 'unroll',
        correctChoiceId: 'unroll-split',
        options: [
          { id: 'unroll-mis1', text: 'unr | oll' },
          { id: 'unroll-split', text: 'un | roll' },
          { id: 'unroll-mis2', text: 'u | nroll' },
          { id: 'unroll-mis3', text: 'un | r oll' },
        ],
      },
      {
        id: 'retell-row',
        prompt: 'retell',
        correctChoiceId: 'retell-split',
        options: [
          { id: 'retell-split', text: 're | tell' },
          { id: 'retell-mis1', text: 'ret | ell' },
          { id: 'retell-mis2', text: 're | t ell' },
          { id: 'retell-mis3', text: 'r | etell' },
        ],
      },
      {
        id: 'preschool-row',
        prompt: 'preschool',
        correctChoiceId: 'preschool-split',
        options: [
          { id: 'preschool-split', text: 'pre | school' },
          { id: 'preschool-mis1', text: 'pres | chool' },
          { id: 'preschool-mis2', text: 'pr | eschool' },
          { id: 'preschool-mis3', text: 'pre | s chool' },
        ],
      },
    ],
  }),
]
