import type { ReadingQuestion } from '../../../../types'
import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from '../variableVowelsOoEa/questionFactories'
import {
  COMMON_PREFIX_CONTENT_VERSION,
  COMMON_PREFIX_LESSON_IDS,
  COMMON_PREFIX_PASSAGE_IDS,
  COMMON_PREFIX_QUESTION_IDS,
} from './ids'

const common = {
  benchmarkReference: 'ELA.2.F.1.3d',
  skillIdentifier: 'g2-word-forge-word-practice',
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'Word Forge',
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2',
  contentVersion: COMMON_PREFIX_CONTENT_VERSION,
  reviewStatus: 'DRAFT' as const,
}

export const guidedQuestions: ReadingQuestion[] = [
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.schoolPreview,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedUnRePre,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-un-re-pre-1',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedUnRePre[0],
    prompt: 'Which word has the prefix pre- and means before test?',
    explanation: 'Pretest begins with pre-, and test is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['pretest-choice'],
    targetVocabulary: ['pretest', 'unroll', 'retell', 'preschool'],
    soundOutChunks: ['pre', 'test'],
    tags: ['common-prefixes', 'prefix-pre', 'base-word'],
    choices: [
      { id: 'retell-choice', text: 'retell' },
      { id: 'preschool-choice', text: 'preschool' },
      { id: 'unroll-choice', text: 'unroll' },
      { id: 'pretest-choice', text: 'pretest' },
    ],
    correctChoiceIds: ['pretest-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.schoolPreview,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedUnRePre,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-un-re-pre-2',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedUnRePre[1],
    prompt: 'Which word has the prefix re- and means tell again?',
    explanation: 'Retell begins with re-, and tell is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['retell-choice'],
    targetVocabulary: ['pretest', 'unroll', 'retell', 'preschool'],
    soundOutChunks: ['re', 'tell'],
    tags: ['common-prefixes', 'prefix-re', 'base-word'],
    choices: [
      { id: 'pretest-choice', text: 'pretest' },
      { id: 'unroll-choice', text: 'unroll' },
      { id: 'preschool-choice', text: 'preschool' },
      { id: 'retell-choice', text: 'retell' },
    ],
    correctChoiceIds: ['retell-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.schoolPreview,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedUnRePre,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-un-re-pre-3',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedUnRePre[2],
    prompt: 'Choose all the words in the preview passage that have a prefix.',
    explanation: 'Pretest, unroll, retell, and preschool all have common prefixes.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['pretest-choice', 'unroll-choice', 'retell-choice', 'preschool-choice'],
    targetVocabulary: ['pretest', 'unroll', 'retell', 'preschool'],
    soundOutChunks: ['pre', 'test', 'un', 'roll', 're', 'tell', 'pre', 'school'],
    tags: ['common-prefixes', 'prefix-pre', 'prefix-un', 'prefix-re', 'base-word'],
    choices: [
      { id: 'pretest-choice', text: 'pretest' },
      { id: 'unroll-choice', text: 'unroll' },
      { id: 'retell-choice', text: 'retell' },
      { id: 'preschool-choice', text: 'preschool' },
    ],
    correctChoiceIds: ['pretest-choice', 'unroll-choice', 'retell-choice', 'preschool-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.schoolPreview,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedUnRePre,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-un-re-pre-4',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedUnRePre[3],
    prompt: 'Select the sentence that says a child could unroll a poster while the teacher retold the plan.',
    explanation: 'The second sentence gives the clue about unroll and retell.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['school-preview-2'],
    targetVocabulary: ['unroll', 'retell', 'preschool'],
    soundOutChunks: ['un', 'roll'],
    tags: ['common-prefixes', 'prefix-un', 'prefix-re'],
    selectableSegments: [
      { id: 'school-preview-1', text: 'The school preview let families pretest the art game and hear a welcome song.' },
      { id: 'school-preview-2', text: 'A child could unroll a poster while the teacher could retell the plan.' },
      { id: 'school-preview-3', text: 'Younger guests smiled near the preschool room.' },
    ],
    correctSegmentIds: ['school-preview-2'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.schoolPreview,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedUnRePre,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-un-re-pre-5',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedUnRePre[4],
    prompt: 'Match each word to its split.',
    explanation: 'Each word matches the authored prefix and base word split in the lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['pretest-split', 'unroll-split', 'retell-split', 'preschool-split'],
    targetVocabulary: ['pretest', 'unroll', 'retell', 'preschool'],
    soundOutChunks: ['pre', 'test', 'un', 'roll', 're', 'tell', 'pre', 'school'],
    tags: ['common-prefixes', 'prefix-pre', 'prefix-un', 'prefix-re', 'base-word'],
    rows: [
      {
        id: 'pretest-row',
        prompt: 'pretest',
        correctChoiceId: 'pretest-split',
        options: [
          { id: 'pretest-split', text: 'pre | test' },
          { id: 'pretest-mis1', text: 'pr | etest' },
          { id: 'pretest-mis2', text: 'pret | est' },
          { id: 'pretest-mis3', text: 'pre | t est' },
        ],
      },
      {
        id: 'unroll-row',
        prompt: 'unroll',
        correctChoiceId: 'unroll-split',
        options: [
          { id: 'unroll-mis1', text: 'unr | oll' },
          { id: 'unroll-split', text: 'un | roll' },
          { id: 'unroll-mis2', text: 'u | nroll' },
          { id: 'unroll-mis3', text: 'un | r oll' },
        ],
      },
      {
        id: 'retell-row',
        prompt: 'retell',
        correctChoiceId: 'retell-split',
        options: [
          { id: 'retell-split', text: 're | tell' },
          { id: 'retell-mis1', text: 'ret | ell' },
          { id: 'retell-mis2', text: 're | t ell' },
          { id: 'retell-mis3', text: 'r | etell' },
        ],
      },
      {
        id: 'preschool-row',
        prompt: 'preschool',
        correctChoiceId: 'preschool-split',
        options: [
          { id: 'preschool-split', text: 'pre | school' },
          { id: 'preschool-mis1', text: 'pres | chool' },
          { id: 'preschool-mis2', text: 'pr | eschool' },
          { id: 'preschool-mis3', text: 'pre | s chool' },
        ],
      },
    ],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.cookingDemo,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedJoinTheParts,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-join-the-parts-5',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedJoinTheParts[4],
    prompt: 'Select the sentence that says the class had to preheat the oven before it started.',
    explanation: 'The first sentence gives the clue about preheat.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['cooking-demo-1'],
    targetVocabulary: ['preheat', 'preview', 'repaint'],
    soundOutChunks: ['pre', 'heat'],
    tags: ['common-prefixes', 'prefix-pre'],
    selectableSegments: [
      { id: 'cooking-demo-1', text: 'At the cooking demo, the class had to preheat the oven before it started.' },
      { id: 'cooking-demo-2', text: 'They used a preview card and repainted the sign.' },
      { id: 'cooking-demo-3', text: 'The helper said the tray was unsafe until it cooled.' },
      { id: 'cooking-demo-4', text: 'Everyone waited with calm hands.' },
    ],
    correctSegmentIds: ['cooking-demo-1'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.scienceNotebook,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedDisMis,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-dis-mis-1',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedDisMis[0],
    prompt: 'Which word has the prefix dis-?',
    explanation: 'Disagree begins with dis-, and agree is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['disagree-choice'],
    targetVocabulary: ['disagree', 'misplace', 'disconnect', 'disobey'],
    soundOutChunks: ['dis', 'agree'],
    tags: ['common-prefixes', 'prefix-dis', 'base-word'],
    choices: [
      { id: 'agree-choice', text: 'agree' },
      { id: 'place-choice', text: 'place' },
      { id: 'disconnect-choice', text: 'disconnect' },
      { id: 'disagree-choice', text: 'disagree' },
    ],
    correctChoiceIds: ['disagree-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.scienceNotebook,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedDisMis,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-dis-mis-2',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedDisMis[1],
    prompt: 'Which word has the prefix mis- and means to put in the wrong place?',
    explanation: 'Misplace begins with mis-, and place is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['misplace-choice'],
    targetVocabulary: ['disagree', 'misplace', 'disconnect', 'disobey'],
    soundOutChunks: ['mis', 'place'],
    tags: ['common-prefixes', 'prefix-mis', 'base-word'],
    choices: [
      { id: 'disagree-choice', text: 'disagree' },
      { id: 'disconnect-choice', text: 'disconnect' },
      { id: 'disobey-choice', text: 'disobey' },
      { id: 'misplace-choice', text: 'misplace' },
    ],
    correctChoiceIds: ['misplace-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.scienceNotebook,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedDisMis,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-dis-mis-3',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedDisMis[2],
    prompt: 'Choose all the words in the science notebook passage that have a prefix.',
    explanation: 'Disagree, misplace, disconnect, and disobey all have common prefixes.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['disagree-choice', 'misplace-choice', 'disconnect-choice', 'disobey-choice'],
    targetVocabulary: ['disagree', 'misplace', 'disconnect', 'disobey'],
    soundOutChunks: ['dis', 'agree', 'mis', 'place', 'dis', 'connect', 'dis', 'obey'],
    tags: ['common-prefixes', 'prefix-dis', 'prefix-mis', 'base-word'],
    choices: [
      { id: 'disagree-choice', text: 'disagree' },
      { id: 'misplace-choice', text: 'misplace' },
      { id: 'disconnect-choice', text: 'disconnect' },
      { id: 'disobey-choice', text: 'disobey' },
    ],
    correctChoiceIds: ['disagree-choice', 'misplace-choice', 'disconnect-choice', 'disobey-choice'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.scienceNotebook,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedDisMis,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-dis-mis-4',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedDisMis[3],
    prompt: 'Match each word to its split.',
    explanation: 'Each word matches the authored prefix and base word split in the lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['disagree-split', 'misplace-split', 'disconnect-split', 'disobey-split'],
    targetVocabulary: ['disagree', 'misplace', 'disconnect', 'disobey'],
    soundOutChunks: ['dis', 'agree', 'mis', 'place', 'dis', 'connect', 'dis', 'obey'],
    tags: ['common-prefixes', 'prefix-dis', 'prefix-mis', 'base-word'],
    rows: [
      {
        id: 'disagree-row',
        prompt: 'disagree',
        correctChoiceId: 'disagree-split',
        options: [
          { id: 'disagree-split', text: 'dis | agree' },
          { id: 'disagree-mis1', text: 'disa | gree' },
          { id: 'disagree-mis2', text: 'dis | ag ree' },
          { id: 'disagree-mis3', text: 'dis | a gree' },
        ],
      },
      {
        id: 'misplace-row',
        prompt: 'misplace',
        correctChoiceId: 'misplace-split',
        options: [
          { id: 'misplace-split', text: 'mis | place' },
          { id: 'misplace-mis1', text: 'misp | lace' },
          { id: 'misplace-mis2', text: 'mis | pl ace' },
          { id: 'misplace-mis3', text: 'mi | splace' },
        ],
      },
      {
        id: 'disconnect-row',
        prompt: 'disconnect',
        correctChoiceId: 'disconnect-split',
        options: [
          { id: 'disconnect-mis1', text: 'disco | nnect' },
          { id: 'disconnect-split', text: 'dis | connect' },
          { id: 'disconnect-mis2', text: 'dis | con nect' },
          { id: 'disconnect-mis3', text: 'd | isconnect' },
        ],
      },
      {
        id: 'disobey-row',
        prompt: 'disobey',
        correctChoiceId: 'disobey-split',
        options: [
          { id: 'disobey-split', text: 'dis | obey' },
          { id: 'disobey-mis1', text: 'diso | bey' },
          { id: 'disobey-mis2', text: 'dis | o bey' },
          { id: 'disobey-mis3', text: 'd | isobey' },
        ],
      },
    ],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 5,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.scienceNotebook,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedDisMis,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-dis-mis-5',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedDisMis[4],
    prompt: 'Match each word to its base word.',
    explanation: 'Each word pairs with the base word after the prefix is removed.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['agree-base', 'place-base', 'connect-base', 'obey-base'],
    targetVocabulary: ['disagree', 'misplace', 'disconnect', 'disobey'],
    soundOutChunks: ['dis', 'agree', 'mis', 'place', 'dis', 'connect', 'dis', 'obey'],
    tags: ['common-prefixes', 'prefix-dis', 'prefix-mis', 'base-word'],
    rows: [
      {
        id: 'disagree-base-row',
        prompt: 'disagree',
        correctChoiceId: 'agree-base',
        options: [
          { id: 'agree-base', text: 'agree' },
          { id: 'connect-base', text: 'connect' },
          { id: 'place-base', text: 'place' },
          { id: 'obey-base', text: 'obey' },
        ],
      },
      {
        id: 'misplace-base-row',
        prompt: 'misplace',
        correctChoiceId: 'place-base',
        options: [
          { id: 'agree-base-2', text: 'agree' },
          { id: 'place-base', text: 'place' },
          { id: 'connect-base-2', text: 'connect' },
          { id: 'obey-base-2', text: 'obey' },
        ],
      },
      {
        id: 'disconnect-base-row',
        prompt: 'disconnect',
        correctChoiceId: 'connect-base',
        options: [
          { id: 'agree-base-3', text: 'agree' },
          { id: 'connect-base', text: 'connect' },
          { id: 'place-base-3', text: 'place' },
          { id: 'obey-base-3', text: 'obey' },
        ],
      },
      {
        id: 'disobey-base-row',
        prompt: 'disobey',
        correctChoiceId: 'obey-base',
        options: [
          { id: 'agree-base-4', text: 'agree' },
          { id: 'connect-base-4', text: 'connect' },
          { id: 'obey-base', text: 'obey' },
          { id: 'place-base-4', text: 'place' },
        ],
      },
    ],
  }),
]
