import type { ReadingQuestion } from '../../../../types'
import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from '../variableVowelsOoEa/questionFactories'
import {
  COMMON_PREFIX_CONTENT_VERSION,
  COMMON_PREFIX_LESSON_IDS,
  COMMON_PREFIX_PASSAGE_IDS,
  COMMON_PREFIX_QUESTION_IDS,
} from './ids'

const common = {
  benchmarkReference: 'ELA.2.F.1.3d',
  skillIdentifier: 'g2-word-forge-word-practice',
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'Word Forge',
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2',
  contentVersion: COMMON_PREFIX_CONTENT_VERSION,
  reviewStatus: 'DRAFT' as const,
}

export const buildingBlockQuestions: ReadingQuestion[] = [
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.rebuildCorner,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedFindTheBase,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-find-the-base-1',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedFindTheBase[0],
    prompt: 'Which word has the prefix un-?',
    explanation: 'Unpack begins with un-, and pack is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['unpack-choice'],
    targetVocabulary: ['unpack', 'rebuild', 'preheat', 'miscount'],
    soundOutChunks: ['un', 'pack'],
    tags: ['common-prefixes', 'prefix-un', 'base-word'],
    choices: [
      { id: 'build-choice', text: 'build' },
      { id: 'heat-choice', text: 'heat' },
      { id: 'pack-choice', text: 'pack' },
      { id: 'unpack-choice', text: 'unpack' },
    ],
    correctChoiceIds: ['unpack-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.rebuildCorner,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedFindTheBase,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-find-the-base-2',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedFindTheBase[1],
    prompt: 'Which word has the prefix re-?',
    explanation: 'Rebuild begins with re-, and build is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['rebuild-choice'],
    targetVocabulary: ['unpack', 'rebuild', 'reuse', 'miscount'],
    soundOutChunks: ['re', 'build'],
    tags: ['common-prefixes', 'prefix-re', 'base-word'],
    choices: [
      { id: 'pack-choice', text: 'pack' },
      { id: 'build-choice', text: 'build' },
      { id: 'rebuild-choice', text: 'rebuild' },
      { id: 'count-choice', text: 'count' },
    ],
    correctChoiceIds: ['rebuild-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.cookingDemo,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedFindTheBase,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-find-the-base-3',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedFindTheBase[2],
    prompt: 'Which word has the prefix pre-?',
    explanation: 'Preheat begins with pre-, and heat is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['preheat-choice'],
    targetVocabulary: ['preheat', 'preview', 'repaint', 'unsafe'],
    soundOutChunks: ['pre', 'heat'],
    tags: ['common-prefixes', 'prefix-pre', 'base-word'],
    choices: [
      { id: 'heat-choice', text: 'heat' },
      { id: 'preview-choice', text: 'preview' },
      { id: 'unsafe-choice', text: 'unsafe' },
      { id: 'preheat-choice', text: 'preheat' },
    ],
    correctChoiceIds: ['preheat-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.rebuildCorner,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedFindTheBase,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-find-the-base-4',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedFindTheBase[3],
    prompt: 'Choose all the words in the repair passage that have a prefix.',
    explanation: 'Unpack, rebuild, reuse, and miscount all begin with common prefixes.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['unpack-choice', 'rebuild-choice', 'reuse-choice', 'miscount-choice'],
    targetVocabulary: ['unpack', 'rebuild', 'reuse', 'miscount'],
    soundOutChunks: ['un', 'pack', 're', 'build', 're', 'use', 'mis', 'count'],
    tags: ['common-prefixes', 'prefix-un', 'prefix-re', 'prefix-mis', 'base-word'],
    choices: [
      { id: 'unpack-choice', text: 'unpack' },
      { id: 'rebuild-choice', text: 'rebuild' },
      { id: 'reuse-choice', text: 'reuse' },
      { id: 'miscount-choice', text: 'miscount' },
    ],
    correctChoiceIds: ['unpack-choice', 'rebuild-choice', 'reuse-choice', 'miscount-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.rebuildCorner,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedFindTheBase,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-find-the-base-5',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedFindTheBase[4],
    prompt: 'Select the sentence that says one helper did miscount screws.',
    explanation: 'The third sentence gives the clue about the helper and the screws.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['rebuild-corner-3'],
    targetVocabulary: ['miscount', 'rebuild', 'reuse'],
    soundOutChunks: ['mis', 'count'],
    tags: ['common-prefixes', 'prefix-mis'],
    selectableSegments: [
      { id: 'rebuild-corner-1', text: 'At the repair corner, the team could unpack tools and rebuild a shelf.' },
      { id: 'rebuild-corner-2', text: 'They chose to reuse paint for the label and checked a preview card.' },
      { id: 'rebuild-corner-3', text: 'One helper did miscount screws, so the team counted again.' },
    ],
    correctSegmentIds: ['rebuild-corner-3'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.cookingDemo,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedJoinTheParts,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-join-the-parts-1',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedJoinTheParts[0],
    prompt: 'Which word has the prefix un- and means not safe?',
    explanation: 'Unsafe begins with un-, and safe is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['unsafe-choice'],
    targetVocabulary: ['unsafe', 'preheat', 'preview', 'repaint'],
    soundOutChunks: ['un', 'safe'],
    tags: ['common-prefixes', 'prefix-un', 'base-word'],
    choices: [
      { id: 'safe-choice', text: 'safe' },
      { id: 'heat-choice', text: 'heat' },
      { id: 'repaint-choice', text: 'repaint' },
      { id: 'unsafe-choice', text: 'unsafe' },
    ],
    correctChoiceIds: ['unsafe-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.cookingDemo,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedJoinTheParts,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-join-the-parts-2',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedJoinTheParts[1],
    prompt: 'Which word has the prefix re- and means paint again?',
    explanation: 'Repaint begins with re-, and paint is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['repaint-choice'],
    targetVocabulary: ['preheat', 'preview', 'repaint', 'unsafe'],
    soundOutChunks: ['re', 'paint'],
    tags: ['common-prefixes', 'prefix-re', 'base-word'],
    choices: [
      { id: 'preview-choice', text: 'preview' },
      { id: 'unsafe-choice', text: 'unsafe' },
      { id: 'paint-choice', text: 'paint' },
      { id: 'repaint-choice', text: 'repaint' },
    ],
    correctChoiceIds: ['repaint-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.cookingDemo,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedJoinTheParts,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-join-the-parts-3',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedJoinTheParts[2],
    prompt: 'Which word has the prefix pre- and means before heat?',
    explanation: 'Preheat begins with pre-, and heat is the base word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['preheat-choice'],
    targetVocabulary: ['preheat', 'preview', 'repaint', 'unsafe'],
    soundOutChunks: ['pre', 'heat'],
    tags: ['common-prefixes', 'prefix-pre', 'base-word'],
    choices: [
      { id: 'preview-choice', text: 'preview' },
      { id: 'unsafe-choice', text: 'unsafe' },
      { id: 'repaint-choice', text: 'repaint' },
      { id: 'preheat-choice', text: 'preheat' },
    ],
    correctChoiceIds: ['preheat-choice'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 4,
    passageIdentifier: COMMON_PREFIX_PASSAGE_IDS.cookingDemo,
    lessonIdentifier: COMMON_PREFIX_LESSON_IDS.guidedJoinTheParts,
    activityIdentifier: 'activity-word-forge-common-prefixes-guided-join-the-parts-4',
    questionIdentifier: COMMON_PREFIX_QUESTION_IDS.guidedJoinTheParts[3],
    prompt: 'Match each word to its split.',
    explanation: 'Each word matches the authored prefix and base word split in the lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['unsafe-split', 'repaint-split', 'preheat-split', 'preview-split'],
    targetVocabulary: ['unsafe', 'repaint', 'preheat', 'preview'],
    soundOutChunks: ['un', 'safe', 're', 'paint', 'pre', 'heat', 'pre', 'view'],
    tags: ['common-prefixes', 'prefix-un', 'prefix-re', 'prefix-pre', 'base-word'],
    rows: [
      {
        id: 'unsafe-row',
        prompt: 'unsafe',
        correctChoiceId: 'unsafe-split',
        options: [
          { id: 'unsafe-split', text: 'un | safe' },
          { id: 'unsafe-mis1', text: 'u | nsafe' },
          { id: 'unsafe-mis2', text: 'uns | afe' },
          { id: 'unsafe-mis3', text: 'un | s afe' },
        ],
      },
      {
        id: 'repaint-row',
        prompt: 'repaint',
        correctChoiceId: 'repaint-split',
        options: [
          { id: 'repaint-mis1', text: 'rep | aint' },
          { id: 'repaint-split', text: 're | paint' },
          { id: 'repaint-mis2', text: 're | pa int' },
          { id: 'repaint-mis3', text: 'r e | paint' },
        ],
      },
      {
        id: 'preheat-row',
        prompt: 'preheat',
        correctChoiceId: 'preheat-split',
        options: [
          { id: 'preheat-split', text: 'pre | heat' },
          { id: 'preheat-mis1', text: 'pr | eheat' },
          { id: 'preheat-mis2', text: 'preh | eat' },
          { id: 'preheat-mis3', text: 'pre | h eat' },
        ],
      },
      {
        id: 'preview-row',
        prompt: 'preview',
        correctChoiceId: 'preview-split',
        options: [
          { id: 'preview-split', text: 'pre | view' },
          { id: 'preview-mis1', text: 'prev | iew' },
          { id: 'preview-mis2', text: 'pre | v iew' },
          { id: 'preview-mis3', text: 'p | review' },
        ],
      },
    ],
  }),
]
