import type { ContentPackManifest, ContentPackLesson } from '../../../contentPackTypes'
import {
  OO_EA_CONTENT_VERSION,
  OO_EA_LESSON_IDS,
  OO_EA_PACK_ID,
  OO_EA_PACK_TITLE,
  OO_EA_PASSAGE_IDS,
  OO_EA_QUESTION_IDS,
} from './ids'

const guidedTeaching = (title: string, explanation: string, examples: string[], contrast: string, learnerCue: string) => ({
  title,
  explanation,
  examples,
  contrast,
  learnerCue,
})

export const grade2WordForgeVariableVowelsOoEaManifest: ContentPackManifest = {
  packId: OO_EA_PACK_ID,
  packTitle: OO_EA_PACK_TITLE,
  gradeBand: 2,
  worldId: 'word-forge',
  unitId: 'wg-unit-1',
  primarySkillId: 'g2-word-forge-word-practice',
  benchmarkReferences: ['ELA.2.F.1.3a'],
  partialBenchmarkCoverage: 'oo and ea only',
  difficultyRange: [0, 1],
  contentVersion: OO_EA_CONTENT_VERSION,
  reviewStatus: 'DRAFT',
  coveredPatterns: ['oo', 'ea'],
  passageIds: [...Object.values(OO_EA_PASSAGE_IDS)],
  questionIds: [
    ...OO_EA_QUESTION_IDS.checkpointA,
    ...OO_EA_QUESTION_IDS.checkpointB,
    ...OO_EA_QUESTION_IDS.checkpointC,
    ...OO_EA_QUESTION_IDS.guidedA,
    ...OO_EA_QUESTION_IDS.guidedB,
    ...OO_EA_QUESTION_IDS.guidedC,
    ...OO_EA_QUESTION_IDS.guidedD,
  ],
  lessonIds: [
    ...Object.values(OO_EA_LESSON_IDS),
  ],
}

export const grade2WordForgeVariableVowelsOoEaLessons: ContentPackLesson[] = [
  {
    lessonId: OO_EA_LESSON_IDS.checkpointA,
    worldId: 'word-forge',
    unitId: 'wg-unit-1',
    activityId: 'activity-word-forge-oo-ea-checkpoint-a',
    difficulty: 1,
    passageIdentifiers: [OO_EA_PASSAGE_IDS.moonRoom],
    questionIdentifiers: [...OO_EA_QUESTION_IDS.checkpointA],
    lessonTitle: 'Vowel Voyage: Moon and Team Quest',
    lessonObjective: 'Read a moon-room scene and prove oo and ea clues with fresh questions.',
    lessonRole: 'CHECKPOINT',
    selectionStatus: 'active',
    contentVersion: OO_EA_CONTENT_VERSION,
    eligiblePurposes: ['progression', 'verification', 'review'],
  },
  {
    lessonId: OO_EA_LESSON_IDS.checkpointB,
    worldId: 'word-forge',
    unitId: 'wg-unit-1',
    activityId: 'activity-word-forge-oo-ea-checkpoint-b',
    difficulty: 1,
    passageIdentifiers: [OO_EA_PASSAGE_IDS.beachCleanup],
    questionIdentifiers: [...OO_EA_QUESTION_IDS.checkpointB],
    lessonTitle: 'Vowel Voyage: Beach and Bread Quest',
    lessonObjective: 'Use beach-cleanup clues to choose the best oo and ea answers.',
    lessonRole: 'CHECKPOINT',
    selectionStatus: 'active',
    contentVersion: OO_EA_CONTENT_VERSION,
    eligiblePurposes: ['progression', 'verification', 'review'],
  },
  {
    lessonId: OO_EA_LESSON_IDS.checkpointC,
    worldId: 'word-forge',
    unitId: 'wg-unit-1',
    activityId: 'activity-word-forge-oo-ea-checkpoint-c',
    difficulty: 1,
    passageIdentifiers: [OO_EA_PASSAGE_IDS.gardenMorning],
    questionIdentifiers: [...OO_EA_QUESTION_IDS.checkpointC],
    lessonTitle: 'Vowel Voyage: Garden and Weather Quest',
    lessonObjective: 'Solve fresh questions about a garden morning with oo and ea clues.',
    lessonRole: 'CHECKPOINT',
    selectionStatus: 'active',
    contentVersion: OO_EA_CONTENT_VERSION,
    eligiblePurposes: ['progression', 'verification', 'review'],
  },
  {
    lessonId: OO_EA_LESSON_IDS.guidedA,
    worldId: 'word-forge',
    unitId: 'wg-unit-1',
    activityId: 'activity-word-forge-oo-ea-guided-a',
    difficulty: 0,
    passageIdentifiers: [OO_EA_PASSAGE_IDS.moonRoom],
    questionIdentifiers: [...OO_EA_QUESTION_IDS.guidedA],
    lessonTitle: 'Guided Practice: Moon Room Clues',
    lessonObjective: 'Sort moon-style and team-style vowel clues with support.',
    lessonRole: 'GUIDED_PRACTICE',
    selectionStatus: 'active',
    teachingBlock: guidedTeaching(
      'Look at the Pattern',
      'The letters oo can make a long sound like moon or a shorter sound like book. The letters ea can make a long sound like team or a softer sound like head. The rest of the word helps us decide.',
      ['moon, spoon, room', 'team, clean, beach', 'book, good, bread'],
      'Not every oo or ea word sounds the same.',
      'Look closely at the word part before you answer.',
    ),
    contentVersion: OO_EA_CONTENT_VERSION,
    eligiblePurposes: ['remediation', 'review'],
  },
  {
    lessonId: OO_EA_LESSON_IDS.guidedB,
    worldId: 'word-forge',
    unitId: 'wg-unit-1',
    activityId: 'activity-word-forge-oo-ea-guided-b',
    difficulty: 0,
    passageIdentifiers: [OO_EA_PASSAGE_IDS.beachCleanup],
    questionIdentifiers: [...OO_EA_QUESTION_IDS.guidedB],
    lessonTitle: 'Guided Practice: Beach Cleanup Clues',
    lessonObjective: 'Use a short beach scene to notice oo and ea word parts.',
    lessonRole: 'GUIDED_PRACTICE',
    selectionStatus: 'active',
    teachingBlock: guidedTeaching(
      'Break It Apart',
      'When we read slowly, the word parts help us decide which sound we hear. Some words keep the sound long, and some use a shorter sound that still makes sense in the sentence.',
      ['beach, clean, leaf', 'boot, spoon, room', 'bread, ready, head'],
      'Read the whole word and think about the sentence clue.',
      'Use the clues before you choose.',
    ),
    contentVersion: OO_EA_CONTENT_VERSION,
    eligiblePurposes: ['remediation', 'review'],
  },
  {
    lessonId: OO_EA_LESSON_IDS.guidedC,
    worldId: 'word-forge',
    unitId: 'wg-unit-1',
    activityId: 'activity-word-forge-oo-ea-guided-c',
    difficulty: 0,
    passageIdentifiers: [OO_EA_PASSAGE_IDS.kitchenBread],
    questionIdentifiers: [...OO_EA_QUESTION_IDS.guidedC],
    lessonTitle: 'Guided Practice: Kitchen Bread Clues',
    lessonObjective: 'Use cooking words to sort oo and ea patterns with support.',
    lessonRole: 'GUIDED_PRACTICE',
    selectionStatus: 'active',
    teachingBlock: guidedTeaching(
      'Hear the Parts',
      'In some words, oo sounds like book or food. In some ea words, the letters sound like team or bread. We can listen, look, and then check the sentence.',
      ['food, good, book', 'team, tea, seat', 'bread, head, ready'],
      'The same letters can make more than one sound.',
      'Try the pattern clue first, then read the whole word.',
    ),
    contentVersion: OO_EA_CONTENT_VERSION,
    eligiblePurposes: ['remediation', 'review'],
  },
  {
    lessonId: OO_EA_LESSON_IDS.guidedD,
    worldId: 'word-forge',
    unitId: 'wg-unit-1',
    activityId: 'activity-word-forge-oo-ea-guided-d',
    difficulty: 0,
    passageIdentifiers: [OO_EA_PASSAGE_IDS.weatherWatch],
    questionIdentifiers: [...OO_EA_QUESTION_IDS.guidedD],
    lessonTitle: 'Guided Practice: Weather Watch Clues',
    lessonObjective: 'Practice oo and ea decoding in a weather scene with support.',
    lessonRole: 'GUIDED_PRACTICE',
    selectionStatus: 'active',
    teachingBlock: guidedTeaching(
      'Blend It',
      'We can blend the parts and listen for the sound that fits the sentence. Use the word part and the story clue together.',
      ['weather, seat, room', 'moon, spoon, pool', 'team, clean, leaf'],
      'The story clue matters as much as the word part.',
      'Blend the parts and check the meaning.',
    ),
    contentVersion: OO_EA_CONTENT_VERSION,
    eligiblePurposes: ['remediation', 'review'],
  },
]
