import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from './questionFactories'
import { OO_EA_CONTENT_VERSION, OO_EA_LESSON_IDS, OO_EA_PASSAGE_IDS, OO_EA_QUESTION_IDS } from './ids'

const common = {
  benchmarkReference: 'ELA.2.F.1.3a',
  skillIdentifier: 'g2-word-forge-word-practice',
  prerequisiteSkillIdentifiers: [],
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'word-lab',
  estimatedReadingLevel: 'grade-2-bridge',
  reviewStatus: 'DRAFT' as const,
  contentVersion: OO_EA_CONTENT_VERSION,
  tags: ['grade-2', 'bridge', 'oo', 'ea', 'checkpoint'],
}

const treeStudySentence1 = 'The leaf study team carried a book and a clean note card into the tree room.'
const treeStudySentence2 = 'They wrote about a dream, a green branch, and a little pond.'
const treeStudySentence3 = 'The leaf stayed on the page while the team talked softly.'

const poolPartySentence1 = 'At the pool party, the team wore a boot and passed a spoon of fruit to each friend.'
const poolPartySentence2 = 'The food tasted good, and the room felt bright.'
const poolPartySentence3 = 'A blue pool card helped the team keep track of each turn.'

const gardenMorningSentence1 = 'At the garden morning, the clean team watched the head gardener water the beds.'
const gardenMorningSentence2 = 'A spoon of soil helped one seed sprout near the beach path.'
const gardenMorningSentence3 = 'Everyone said the new plant looked good by noon.'

export const checkpointQuestions = [
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.treeStudy,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-a-1',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointA[0],
    prompt: 'Which word has ea like clean?',
    explanation: 'Leaf has the ea sound like clean.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['leaf-choice'],
    targetVocabulary: ['leaf', 'clean'],
    soundOutChunks: ['l', 'ea', 'f'],
    choices: [
      { id: 'leaf-choice', text: 'leaf' },
      { id: 'book-choice', text: 'book' },
      { id: 'moon-choice', text: 'moon' },
      { id: 'boot-choice', text: 'boot' },
    ],
    correctChoiceIds: ['leaf-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.treeStudy,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-a-2',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointA[1],
    prompt: 'Which word has oo like moon?',
    explanation: 'Book has the oo sound like moon.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['book-choice'],
    targetVocabulary: ['book', 'room'],
    soundOutChunks: ['b', 'oo', 'k'],
    choices: [
      { id: 'book-choice', text: 'book' },
      { id: 'clean-choice', text: 'clean' },
      { id: 'dream-choice', text: 'dream' },
      { id: 'ready-choice', text: 'ready' },
    ],
    correctChoiceIds: ['book-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.treeStudy,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-a-3',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointA[2],
    prompt: 'Choose all the ea words in the passage.',
    explanation: 'Leaf, clean, dream, and team all show ea sounds in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['leaf-choice', 'clean-choice', 'dream-choice', 'team-choice'],
    targetVocabulary: ['leaf', 'clean', 'dream', 'team'],
    soundOutChunks: ['ea'],
    choices: [
      { id: 'leaf-choice', text: 'leaf' },
      { id: 'clean-choice', text: 'clean' },
      { id: 'dream-choice', text: 'dream' },
      { id: 'team-choice', text: 'team' },
    ],
    correctChoiceIds: ['leaf-choice', 'clean-choice', 'dream-choice', 'team-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.treeStudy,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-a-4',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointA[3],
    prompt: 'Select the sentence that tells about the dream, the green branch, and the little pond.',
    explanation: 'The second sentence tells about the dream, the green branch, and the little pond.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['dream-sentence'],
    targetVocabulary: ['dream', 'branch'],
    soundOutChunks: ['dr', 'ea', 'm'],
    selectableSegments: [
      { id: 'dream-sentence', text: treeStudySentence2 },
      { id: 'work-sentence', text: treeStudySentence1 },
      { id: 'soft-sentence', text: treeStudySentence3 },
    ],
    correctSegmentIds: ['dream-sentence'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.treeStudy,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-a-5',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointA[4],
    prompt: 'Which sound group fits leaf?',
    explanation: 'Leaf belongs with the ea sound group in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['leaf-sound'],
    targetVocabulary: ['leaf', 'clean'],
    soundOutChunks: ['ea'],
    rows: [
      {
        id: 'leaf-row',
        prompt: 'leaf',
        correctChoiceId: 'leaf-sound',
        options: [
          { id: 'leaf-sound', text: 'Ea sound' },
          { id: 'book-sound', text: 'Oo sound' },
          { id: 'blend-sound', text: 'Mixed sound' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.treeStudy,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-a-6',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointA[5],
    prompt: 'Which word has ea like team?',
    explanation: 'Clean has the ea sound like team.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['clean-choice'],
    targetVocabulary: ['clean', 'team'],
    soundOutChunks: ['cl', 'ea', 'n'],
    choices: [
      { id: 'clean-choice', text: 'clean' },
      { id: 'book-choice', text: 'book' },
      { id: 'boot-choice', text: 'boot' },
      { id: 'moon-choice', text: 'moon' },
    ],
    correctChoiceIds: ['clean-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.treeStudy,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-a-7',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointA[6],
    prompt: 'Choose all the oo words in the passage.',
    explanation: 'Book and room both show oo sounds in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['book-choice', 'room-choice'],
    targetVocabulary: ['book', 'room'],
    soundOutChunks: ['oo'],
    choices: [
      { id: 'book-choice', text: 'book' },
      { id: 'room-choice', text: 'room' },
      { id: 'dream-choice', text: 'dream' },
      { id: 'clean-choice', text: 'clean' },
    ],
    correctChoiceIds: ['book-choice', 'room-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.poolParty,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-b-1',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointB[0],
    prompt: 'Which word has oo like moon?',
    explanation: 'Pool has the oo sound like moon.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['pool-choice'],
    targetVocabulary: ['pool', 'boot'],
    soundOutChunks: ['p', 'oo', 'l'],
    choices: [
      { id: 'pool-choice', text: 'pool' },
      { id: 'team-choice', text: 'team' },
      { id: 'seat-choice', text: 'seat' },
      { id: 'head-choice', text: 'head' },
    ],
    correctChoiceIds: ['pool-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.poolParty,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-b-2',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointB[1],
    prompt: 'Which word has ea like leaf?',
    explanation: 'Team has the ea sound like leaf.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['team-choice'],
    targetVocabulary: ['team', 'each'],
    soundOutChunks: ['t', 'ea', 'm'],
    choices: [
      { id: 'team-choice', text: 'team' },
      { id: 'boot-choice', text: 'boot' },
      { id: 'good-choice', text: 'good' },
      { id: 'moon-choice', text: 'moon' },
    ],
    correctChoiceIds: ['team-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.poolParty,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-b-3',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointB[2],
    prompt: 'Choose all the oo words in the passage.',
    explanation: 'Pool, boot, spoon, and good show oo sounds in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['pool-choice', 'boot-choice', 'spoon-choice', 'good-choice'],
    targetVocabulary: ['pool', 'boot', 'spoon', 'good'],
    soundOutChunks: ['oo'],
    choices: [
      { id: 'pool-choice', text: 'pool' },
      { id: 'boot-choice', text: 'boot' },
      { id: 'spoon-choice', text: 'spoon' },
      { id: 'good-choice', text: 'good' },
    ],
    correctChoiceIds: ['pool-choice', 'boot-choice', 'spoon-choice', 'good-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.poolParty,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-b-4',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointB[3],
    prompt: 'Select the sentence that says the food tasted good.',
    explanation: 'The second sentence tells about the food and room.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['food-sentence'],
    targetVocabulary: ['food', 'good'],
    soundOutChunks: ['f', 'oo', 'd'],
    selectableSegments: [
      { id: 'food-sentence', text: poolPartySentence2 },
      { id: 'party-sentence', text: poolPartySentence1 },
      { id: 'card-sentence', text: poolPartySentence3 },
    ],
    correctSegmentIds: ['food-sentence'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.poolParty,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-b-5',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointB[4],
    prompt: 'Which sound group fits boot?',
    explanation: 'Boot belongs with the oo sound group in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['boot-sound'],
    targetVocabulary: ['boot', 'pool'],
    soundOutChunks: ['oo'],
    rows: [
      {
        id: 'boot-row',
        prompt: 'boot',
        correctChoiceId: 'boot-sound',
        options: [
          { id: 'boot-sound', text: 'Oo sound' },
          { id: 'ea-sound', text: 'Ea sound' },
          { id: 'mix-sound', text: 'Mixed sound' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.poolParty,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-b-6',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointB[5],
    prompt: 'Which word has oo like food?',
    explanation: 'Spoon has the oo sound like food.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['spoon-choice'],
    targetVocabulary: ['spoon', 'pool'],
    soundOutChunks: ['sp', 'oo', 'n'],
    choices: [
      { id: 'spoon-choice', text: 'spoon' },
      { id: 'leaf-choice', text: 'leaf' },
      { id: 'head-choice', text: 'head' },
      { id: 'clean-choice', text: 'clean' },
    ],
    correctChoiceIds: ['spoon-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.poolParty,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-b-7',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointB[6],
    prompt: 'Choose all the ea words in the passage.',
    explanation: 'Team and each show ea sounds in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['team-choice', 'each-choice'],
    targetVocabulary: ['team', 'each'],
    soundOutChunks: ['ea'],
    choices: [
      { id: 'team-choice', text: 'team' },
      { id: 'each-choice', text: 'each' },
      { id: 'good-choice', text: 'good' },
      { id: 'boot-choice', text: 'boot' },
    ],
    correctChoiceIds: ['team-choice', 'each-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.gardenMorning,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-c-1',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointC[0],
    prompt: 'Which word has ea like bread?',
    explanation: 'Head has the ea sound like bread.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['head-choice'],
    targetVocabulary: ['head', 'beach'],
    soundOutChunks: ['h', 'ea', 'd'],
    choices: [
      { id: 'head-choice', text: 'head' },
      { id: 'boot-choice', text: 'boot' },
      { id: 'moon-choice', text: 'moon' },
      { id: 'spoon-choice', text: 'spoon' },
    ],
    correctChoiceIds: ['head-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.gardenMorning,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-c-2',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointC[1],
    prompt: 'Which word has oo like moon?',
    explanation: 'Spoon has the oo sound like moon.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['spoon-choice'],
    targetVocabulary: ['spoon', 'good'],
    soundOutChunks: ['sp', 'oo', 'n'],
    choices: [
      { id: 'spoon-choice', text: 'spoon' },
      { id: 'clean-choice', text: 'clean' },
      { id: 'beach-choice', text: 'beach' },
      { id: 'ready-choice', text: 'ready' },
    ],
    correctChoiceIds: ['spoon-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.gardenMorning,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-c-3',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointC[2],
    prompt: 'Choose all the ea words in the passage.',
    explanation: 'Head, clean, beach, and seed show ea sounds in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['head-choice', 'clean-choice', 'beach-choice', 'seed-choice'],
    targetVocabulary: ['head', 'clean', 'beach', 'seed'],
    soundOutChunks: ['ea'],
    choices: [
      { id: 'head-choice', text: 'head' },
      { id: 'clean-choice', text: 'clean' },
      { id: 'beach-choice', text: 'beach' },
      { id: 'seed-choice', text: 'seed' },
    ],
    correctChoiceIds: ['head-choice', 'clean-choice', 'beach-choice', 'seed-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.gardenMorning,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-c-4',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointC[3],
    prompt: 'Select the sentence that mentions the beach path.',
    explanation: 'The second sentence tells about the beach path and the sprouting seed.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['beach-sentence'],
    targetVocabulary: ['beach', 'seed'],
    soundOutChunks: ['b', 'ea', 'ch'],
    selectableSegments: [
      { id: 'beach-sentence', text: gardenMorningSentence2 },
      { id: 'garden-sentence', text: gardenMorningSentence1 },
      { id: 'good-sentence', text: gardenMorningSentence3 },
    ],
    correctSegmentIds: ['beach-sentence'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.gardenMorning,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-c-5',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointC[4],
    prompt: 'Which sound group fits beach?',
    explanation: 'Beach belongs with the ea sound group in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['beach-sound'],
    targetVocabulary: ['beach', 'head'],
    soundOutChunks: ['ea'],
    rows: [
      {
        id: 'beach-row',
        prompt: 'beach',
        correctChoiceId: 'beach-sound',
        options: [
          { id: 'beach-sound', text: 'Ea sound' },
          { id: 'pool-sound', text: 'Oo sound' },
          { id: 'mix-sound', text: 'Mixed sound' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.gardenMorning,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-c-6',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointC[5],
    prompt: 'Which word has oo like book?',
    explanation: 'Good has the oo sound like book.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['good-choice'],
    targetVocabulary: ['good', 'noon'],
    soundOutChunks: ['g', 'oo', 'd'],
    choices: [
      { id: 'good-choice', text: 'good' },
      { id: 'clean-choice', text: 'clean' },
      { id: 'head-choice', text: 'head' },
      { id: 'beach-choice', text: 'beach' },
    ],
    correctChoiceIds: ['good-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.gardenMorning,
    lessonIdentifier: OO_EA_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-word-forge-oo-ea-checkpoint-c-7',
    questionIdentifier: OO_EA_QUESTION_IDS.checkpointC[6],
    prompt: 'Choose all the oo words in the passage.',
    explanation: 'Spoon, good, and noon show oo sounds in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['spoon-choice', 'good-choice', 'noon-choice'],
    targetVocabulary: ['spoon', 'good', 'noon'],
    soundOutChunks: ['oo'],
    choices: [
      { id: 'spoon-choice', text: 'spoon' },
      { id: 'good-choice', text: 'good' },
      { id: 'noon-choice', text: 'noon' },
      { id: 'clean-choice', text: 'clean' },
    ],
    correctChoiceIds: ['spoon-choice', 'good-choice', 'noon-choice'],
  }),
]
