import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from './questionFactories'
import { OO_EA_CONTENT_VERSION, OO_EA_LESSON_IDS, OO_EA_PASSAGE_IDS, OO_EA_QUESTION_IDS } from './ids'

const common = {
  benchmarkReference: 'ELA.2.F.1.3a',
  skillIdentifier: 'g2-word-forge-word-practice',
  prerequisiteSkillIdentifiers: [],
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'word-lab',
  estimatedReadingLevel: 'grade-2-bridge',
  reviewStatus: 'DRAFT' as const,
  contentVersion: OO_EA_CONTENT_VERSION,
  tags: ['grade-2', 'bridge', 'oo', 'ea', 'guided-practice'],
}

const beachCleanupSentence1 = 'The clean team met at the beach before breakfast.'
const beachCleanupSentence2 = 'They wore boots and picked up trash near the blue pool.'
const beachCleanupSentence3 = 'A leaf rested on the sand, and everyone smiled.'

const kitchenBreadSentence1 = 'Mia and her dad baked bread for the team dinner.'
const kitchenBreadSentence2 = 'They measured tea leaves, checked the spoon, and kept the oven clean.'
const kitchenBreadSentence3 = 'The bread looked good and ready on the tray.'

const weatherWatchSentence1 = 'On a cloudy morning, the weather team checked the chart by the room door.'
const weatherWatchSentence2 = 'They found a wood seat, a blue boot, and a neat sign.'
const weatherWatchSentence3 = 'The room stayed calm while the rain tapped the glass.'

export const guidedQuestions = [
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 0,
    passageIdentifier: OO_EA_PASSAGE_IDS.beachCleanup,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedB,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-b-1',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedB[0],
    prompt: 'Which word has ea like team?',
    explanation: 'Beach has the ea sound like team.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['beach-choice'],
    targetVocabulary: ['beach', 'leaf'],
    soundOutChunks: ['b', 'ea', 'ch'],
    choices: [
      { id: 'beach-choice', text: 'beach' },
      { id: 'boots-choice', text: 'boots' },
      { id: 'moon-choice', text: 'moon' },
      { id: 'good-choice', text: 'good' },
    ],
    correctChoiceIds: ['beach-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 0,
    passageIdentifier: OO_EA_PASSAGE_IDS.beachCleanup,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedB,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-b-2',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedB[1],
    prompt: 'Choose all the words that have oo like boots.',
    explanation: 'Boots and pool both have the oo sound in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['boots-choice', 'pool-choice'],
    targetVocabulary: ['boots', 'pool'],
    soundOutChunks: ['oo'],
    choices: [
      { id: 'boots-choice', text: 'boots' },
      { id: 'pool-choice', text: 'pool' },
      { id: 'clean-choice', text: 'clean' },
      { id: 'leaf-choice', text: 'leaf' },
    ],
    correctChoiceIds: ['boots-choice', 'pool-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 0,
    passageIdentifier: OO_EA_PASSAGE_IDS.beachCleanup,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedB,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-b-3',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedB[2],
    prompt: 'Select the sentence that shows the cleanup at the beach.',
    explanation: 'The first sentence tells about the team meeting at the beach.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['cleanup-sentence'],
    targetVocabulary: ['beach', 'clean', 'leaf'],
    soundOutChunks: ['beach'],
    selectableSegments: [
      { id: 'cleanup-sentence', text: beachCleanupSentence1 },
      { id: 'boots-pool-sentence', text: beachCleanupSentence2 },
      { id: 'leaf-sentence', text: beachCleanupSentence3 },
    ],
    correctSegmentIds: ['cleanup-sentence'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 0,
    passageIdentifier: OO_EA_PASSAGE_IDS.beachCleanup,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedB,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-b-4',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedB[3],
    prompt: 'Which sound group fits leaf?',
    explanation: 'Leaf belongs with the ea sound group in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['leaf-sound'],
    targetVocabulary: ['leaf', 'beach'],
    soundOutChunks: ['ea'],
    rows: [
      {
        id: 'leaf-row',
        prompt: 'leaf',
        correctChoiceId: 'leaf-sound',
        options: [
          { id: 'leaf-sound', text: 'Ea sound' },
          { id: 'team-sound', text: 'Oo sound' },
          { id: 'bread-sound', text: 'Bread sound' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 0,
    passageIdentifier: OO_EA_PASSAGE_IDS.beachCleanup,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedB,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-b-5',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedB[4],
    prompt: 'Which word has ea like clean?',
    explanation: 'Leaf has the ea sound like clean.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['leaf-choice'],
    targetVocabulary: ['leaf', 'beach'],
    soundOutChunks: ['l', 'ea', 'f'],
    choices: [
      { id: 'leaf-choice', text: 'leaf' },
      { id: 'boot-choice', text: 'boot' },
      { id: 'moon-choice', text: 'moon' },
      { id: 'bread-choice', text: 'bread' },
    ],
    correctChoiceIds: ['leaf-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.kitchenBread,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedC,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-c-1',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedC[0],
    prompt: 'Which word has ea like head?',
    explanation: 'Bread has the ea sound like head.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['bread-choice'],
    targetVocabulary: ['bread', 'tea'],
    soundOutChunks: ['br', 'ea', 'd'],
    choices: [
      { id: 'bread-choice', text: 'bread' },
      { id: 'spoon-choice', text: 'spoon' },
      { id: 'moon-choice', text: 'moon' },
      { id: 'good-choice', text: 'good' },
    ],
    correctChoiceIds: ['bread-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.kitchenBread,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedC,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-c-2',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedC[1],
    prompt: 'Choose all the words spelled with ea.',
    explanation: 'Tea, bread, and ready are all spelled with ea, even though ea does not make the same sound in every word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['tea-choice', 'bread-choice', 'ready-choice'],
    targetVocabulary: ['tea', 'bread', 'ready'],
    soundOutChunks: ['ea'],
    choices: [
      { id: 'tea-choice', text: 'tea' },
      { id: 'bread-choice', text: 'bread' },
      { id: 'ready-choice', text: 'ready' },
      { id: 'boot-choice', text: 'boot' },
    ],
    correctChoiceIds: ['tea-choice', 'bread-choice', 'ready-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.kitchenBread,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedC,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-c-3',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedC[2],
    prompt: 'Select the sentence that shows the bread on the tray.',
    explanation: 'The third sentence shows the bread looking good and ready on the tray.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['bread-sentence'],
    targetVocabulary: ['bread', 'ready', 'good'],
    soundOutChunks: ['bread'],
    selectableSegments: [
      { id: 'bread-sentence', text: kitchenBreadSentence3 },
      { id: 'tea-sentence', text: kitchenBreadSentence2 },
      { id: 'dad-sentence', text: kitchenBreadSentence1 },
    ],
    correctSegmentIds: ['bread-sentence'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.kitchenBread,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedC,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-c-4',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedC[3],
    prompt: 'Which sound group fits ready?',
    explanation: 'Ready belongs with the ea sound group in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['ready-sound'],
    targetVocabulary: ['ready', 'tea'],
    soundOutChunks: ['ea'],
    rows: [
      {
        id: 'ready-row',
        prompt: 'ready',
        correctChoiceId: 'ready-sound',
        options: [
          { id: 'ready-sound', text: 'Ea sound' },
          { id: 'moo-sound', text: 'Oo sound' },
          { id: 'mix-sound', text: 'Mixed sound' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.kitchenBread,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedC,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-c-5',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedC[4],
    prompt: 'Which word has oo like moon?',
    explanation: 'Spoon has the oo sound like moon.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['spoon-choice'],
    targetVocabulary: ['spoon', 'good'],
    soundOutChunks: ['sp', 'oo', 'n'],
    choices: [
      { id: 'spoon-choice', text: 'spoon' },
      { id: 'tea-choice', text: 'tea' },
      { id: 'bread-choice', text: 'bread' },
      { id: 'leaf-choice', text: 'leaf' },
    ],
    correctChoiceIds: ['spoon-choice'],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.weatherWatch,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedD,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-d-1',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedD[0],
    prompt: 'Which word has ea like bread?',
    explanation: 'Weather has the ea sound like bread.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['weather-choice'],
    targetVocabulary: ['weather', 'seat'],
    soundOutChunks: ['ea'],
    choices: [
      { id: 'weather-choice', text: 'weather' },
      { id: 'boot-choice', text: 'boot' },
      { id: 'moon-choice', text: 'moon' },
      { id: 'good-choice', text: 'good' },
    ],
    correctChoiceIds: ['weather-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.weatherWatch,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedD,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-d-2',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedD[1],
    prompt: 'Choose all the words spelled with oo.',
    explanation: 'Room, wood, and boot are all spelled with oo, even though oo does not make the same sound in every word.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['room-choice', 'wood-choice', 'boot-choice'],
    targetVocabulary: ['room', 'wood', 'boot'],
    soundOutChunks: ['oo'],
    choices: [
      { id: 'room-choice', text: 'room' },
      { id: 'wood-choice', text: 'wood' },
      { id: 'boot-choice', text: 'boot' },
      { id: 'seat-choice', text: 'seat' },
    ],
    correctChoiceIds: ['room-choice', 'wood-choice', 'boot-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.weatherWatch,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedD,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-d-3',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedD[2],
    prompt: 'Select the sentence that shows the weather team.',
    explanation: 'The first sentence names the weather team and the room door.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['weather-sentence'],
    targetVocabulary: ['weather', 'room', 'wood'],
    soundOutChunks: ['weather'],
    selectableSegments: [
      { id: 'weather-sentence', text: weatherWatchSentence1 },
      { id: 'bench-sentence', text: weatherWatchSentence2 },
      { id: 'glass-sentence', text: weatherWatchSentence3 },
    ],
    correctSegmentIds: ['weather-sentence'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.weatherWatch,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedD,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-d-4',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedD[3],
    prompt: 'Which sound group fits seat?',
    explanation: 'Seat belongs with the ea sound group in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['seat-sound'],
    targetVocabulary: ['seat', 'weather'],
    soundOutChunks: ['ea'],
    rows: [
      {
        id: 'seat-row',
        prompt: 'seat',
        correctChoiceId: 'seat-sound',
        options: [
          { id: 'seat-sound', text: 'Ea sound' },
          { id: 'hood-sound', text: 'Oo sound' },
          { id: 'mix-sound', text: 'Mixed sound' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 1,
    passageIdentifier: OO_EA_PASSAGE_IDS.weatherWatch,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedD,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-d-5',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedD[4],
    prompt: 'Which word has oo like good?',
    explanation: 'Wood has the oo sound like good.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['wood-choice'],
    targetVocabulary: ['wood', 'room'],
    soundOutChunks: ['w', 'oo', 'd'],
    choices: [
      { id: 'wood-choice', text: 'wood' },
      { id: 'leaf-choice', text: 'leaf' },
      { id: 'tea-choice', text: 'tea' },
      { id: 'head-choice', text: 'head' },
    ],
    correctChoiceIds: ['wood-choice'],
  }),
]
