import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from './questionFactories'
import { OO_EA_CONTENT_VERSION, OO_EA_LESSON_IDS, OO_EA_PASSAGE_IDS, OO_EA_QUESTION_IDS } from './ids'

const common = {
  benchmarkReference: 'ELA.2.F.1.3a',
  skillIdentifier: 'g2-word-forge-word-practice',
  prerequisiteSkillIdentifiers: [],
  reportingCategory: 'Foundational Skills Bridge',
  genre: 'word-lab',
  estimatedReadingLevel: 'grade-2-bridge',
  reviewStatus: 'DRAFT' as const,
  contentVersion: OO_EA_CONTENT_VERSION,
  tags: ['grade-2', 'bridge', 'oo', 'ea', 'guided-practice'],
}

const moonRoomSentence1 = 'The clean team walked into the moon room at dusk.'
const moonRoomSentence2 = 'Nia carried a spoon and a book for the quiet show.'
const moonRoomSentence3 = 'The room glowed while the moon shone on the wood shelf.'

export const buildingBlockQuestions = [
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 0,
    passageIdentifier: OO_EA_PASSAGE_IDS.moonRoom,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedA,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-a-1',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedA[0],
    prompt: 'Which word has oo like spoon?',
    explanation: 'Moon has the oo sound like spoon.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['moon-choice'],
    targetVocabulary: ['moon', 'book'],
    soundOutChunks: ['m', 'oo', 'n'],
    choices: [
      { id: 'moon-choice', text: 'moon' },
      { id: 'team-choice', text: 'team' },
      { id: 'clean-choice', text: 'clean' },
      { id: 'bread-choice', text: 'bread' },
    ],
    correctChoiceIds: ['moon-choice'],
  }),
  createMultiselectQuestion({
    ...common,
    difficulty: 0,
    passageIdentifier: OO_EA_PASSAGE_IDS.moonRoom,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedA,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-a-2',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedA[1],
    prompt: 'Choose all the words that have oo like moon.',
    explanation: 'Moon and book both have the oo sound in this lesson.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['moon-choice', 'book-choice'],
    targetVocabulary: ['moon', 'book'],
    soundOutChunks: ['oo'],
    choices: [
      { id: 'moon-choice', text: 'moon' },
      { id: 'book-choice', text: 'book' },
      { id: 'team-choice', text: 'team' },
      { id: 'clean-choice', text: 'clean' },
    ],
    correctChoiceIds: ['moon-choice', 'book-choice'],
  }),
  createHotTextQuestion({
    ...common,
    difficulty: 0,
    passageIdentifier: OO_EA_PASSAGE_IDS.moonRoom,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedA,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-a-3',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedA[2],
    prompt: 'Select the sentence that shows the moon room scene.',
    explanation: 'The first sentence names the moon room and the clean team.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['moon-room-sentence'],
    targetVocabulary: ['moon', 'team', 'room'],
    soundOutChunks: ['moon'],
    selectableSegments: [
      { id: 'moon-room-sentence', text: moonRoomSentence1 },
      { id: 'spoon-book-sentence', text: moonRoomSentence2 },
      { id: 'moon-glow-sentence', text: moonRoomSentence3 },
    ],
    correctSegmentIds: ['moon-room-sentence'],
  }),
  createTableMatchQuestion({
    ...common,
    difficulty: 0,
    passageIdentifier: OO_EA_PASSAGE_IDS.moonRoom,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedA,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-a-4',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedA[3],
    prompt: 'Which sound group fits moon?',
    explanation: 'Moon belongs with the moon sound group.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['moon-sound'],
    targetVocabulary: ['moon', 'team'],
    soundOutChunks: ['oo'],
    rows: [
      {
        id: 'moon-row',
        prompt: 'moon',
        correctChoiceId: 'moon-sound',
        options: [
          { id: 'moon-sound', text: 'Moon sound' },
          { id: 'team-sound', text: 'Team sound' },
          { id: 'bread-sound', text: 'Bread sound' },
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...common,
    difficulty: 0,
    passageIdentifier: OO_EA_PASSAGE_IDS.moonRoom,
    lessonIdentifier: OO_EA_LESSON_IDS.guidedA,
    activityIdentifier: 'activity-word-forge-oo-ea-guided-a-5',
    questionIdentifier: OO_EA_QUESTION_IDS.guidedA[4],
    prompt: 'Which word has ea like leaf?',
    explanation: 'Team has the ea sound like leaf.',
    evidenceReference: 'word-pattern',
    evidenceReferenceIds: ['team-choice'],
    targetVocabulary: ['team', 'clean'],
    soundOutChunks: ['t', 'ea', 'm'],
    choices: [
      { id: 'team-choice', text: 'team' },
      { id: 'spoon-choice', text: 'spoon' },
      { id: 'book-choice', text: 'book' },
      { id: 'moon-choice', text: 'moon' },
    ],
    correctChoiceIds: ['team-choice'],
  }),
]
