import type { ContentPack, ContentPackLesson } from '../../../contentPackTypes'
import { rootMeaningArtifacts, rootMeaningGuides, rootMeaningVaultPassages } from './content'
import {
  rootMeaningVaultContentVersion,
  rootMeaningVaultLessonIds,
  rootMeaningVaultPackId,
  rootMeaningVaultPrimarySkillId,
  rootMeaningVaultQuestionIds,
  rootMeaningVaultUnitId,
  rootMeaningVaultWorldId,
} from './ids'
import { rootMeaningVaultQuestions } from './questions'

const guidedPlans = [
  {
    lessonId: rootMeaningVaultLessonIds.prefixClues,
    activityId: 'activity-g3-cc-rmv-prefix-clues',
    difficulty: 1,
    passage: rootMeaningArtifacts.prefixClues.passage,
    questionIds: rootMeaningVaultQuestionIds.prefixClues,
    lessonTitle: 'Root Meaning Vault Power-Up: Prefix Clues',
    lessonObjective: 'Use genuine prefixes and English bases to infer meaning, then confirm the inference in context.',
    teachingBlock: {
      title: 'A prefix changes a base meaning',
      explanation: 'Find a genuine prefix and base, say what each often means, combine the clues, and check the sentence before deciding.',
      examples: ['Preview combines pre, before, with view, look at.', 'Reread combines re, again, with read.', 'Miscount combines mis, wrongly, with count.'],
      contrast: 'A matching string of letters is not a meaning part unless it contributes to this word.',
      learnerCue: 'Build a meaning clue, then ask whether the sentence confirms it.',
    },
  },
  {
    lessonId: rootMeaningVaultLessonIds.suffixClues,
    activityId: 'activity-g3-cc-rmv-suffix-clues',
    difficulty: 1,
    passage: rootMeaningArtifacts.suffixClues.passage,
    questionIds: rootMeaningVaultQuestionIds.suffixClues,
    lessonTitle: 'Root Meaning Vault Power-Up: Suffix Clues',
    lessonObjective: 'Combine an English base with a meaning-bearing suffix and verify the whole-word meaning.',
    teachingBlock: {
      title: 'A suffix can add a meaning clue',
      explanation: 'The base carries a central idea. A suffix such as ful, less, able, or ness adds a clue about having, lacking, possibility, or quality.',
      examples: ['Hopeful means having hope.', 'Careless means without enough care.', 'Washable means able to be washed.'],
      contrast: 'The parts suggest a meaning, but the surrounding details still need to fit that meaning.',
      learnerCue: 'Combine the base and suffix, then check the action or result in the passage.',
    },
  },
  {
    lessonId: rootMeaningVaultLessonIds.greekRoots,
    activityId: 'activity-g3-cc-rmv-greek-roots',
    difficulty: 2,
    passage: rootMeaningArtifacts.greekRoots.passage,
    questionIds: rootMeaningVaultQuestionIds.greekRoots,
    lessonTitle: 'Root Meaning Vault Lab: Greek Roots',
    lessonObjective: 'Use transparent Greek roots and context to build a reasonable unfamiliar-word meaning.',
    teachingBlock: {
      title: 'Greek roots carry meaning across words',
      explanation: 'A Greek root often supplies a useful clue. Combine genuine roots, treat a connector as a connector, and confirm the hypothesis in context.',
      examples: ['Therm often means heat.', 'Poly means many and gon means angle.', 'Mono means one.'],
      contrast: 'Meaning parts are not automatically the same as the chunks used to pronounce a word.',
      learnerCue: 'Ask what the roots suggest and what the model or sentence proves.',
    },
  },
  {
    lessonId: rootMeaningVaultLessonIds.latinRoots,
    activityId: 'activity-g3-cc-rmv-latin-roots',
    difficulty: 2,
    passage: rootMeaningArtifacts.latinRoots.passage,
    questionIds: rootMeaningVaultQuestionIds.latinRoots,
    lessonTitle: 'Root Meaning Vault Lab: Latin Roots',
    lessonObjective: 'Use Latin roots and affixes to infer carrying, saying, and seeing meanings in context.',
    teachingBlock: {
      title: 'A root clue changes with its partners',
      explanation: 'A root can appear with different prefixes or suffixes. Combine all genuine parts, then use the sentence to choose the contextual meaning.',
      examples: ['Port often means carry.', 'Dict often means say.', 'Vis often means see.'],
      contrast: 'A root clue points toward meaning; it does not replace careful reading of the sentence.',
      learnerCue: 'Name each part, combine the clues, and check the surrounding result.',
    },
  },
] as const

const guidedLessons: ContentPackLesson[] = guidedPlans.map((plan) => ({
  lessonId: plan.lessonId,
  worldId: rootMeaningVaultWorldId,
  unitId: rootMeaningVaultUnitId,
  activityId: plan.activityId,
  difficulty: plan.difficulty,
  passageIdentifiers: [plan.passage.passageIdentifier],
  questionIdentifiers: [...plan.questionIds],
  lessonTitle: plan.lessonTitle,
  lessonObjective: plan.lessonObjective,
  lessonRole: 'GUIDED_PRACTICE',
  selectionStatus: 'active',
  teachingBlock: { ...plan.teachingBlock, examples: [...plan.teachingBlock.examples] },
  contentVersion: rootMeaningVaultContentVersion,
  eligiblePurposes: ['remediation', 'review'],
}))

const checkpointLessons: ContentPackLesson[] = [
  {
    lessonId: rootMeaningVaultLessonIds.buildMeaningCheckpoint,
    worldId: rootMeaningVaultWorldId,
    unitId: rootMeaningVaultUnitId,
    activityId: 'activity-g3-cc-rmv-build-meaning-checkpoint',
    difficulty: 2,
    passageIdentifiers: [rootMeaningArtifacts.buildMeaning.passage.passageIdentifier],
    questionIdentifiers: [...rootMeaningVaultQuestionIds.buildMeaningCheckpoint],
    lessonTitle: 'Root Meaning Vault Checkpoint: Build Meaning from Parts',
    lessonObjective: 'Combine English bases and affixes, reject false splits, and confirm inferred meanings in context.',
    lessonRole: 'CHECKPOINT', selectionStatus: 'active', contentVersion: rootMeaningVaultContentVersion,
    eligiblePurposes: ['progression', 'verification', 'review'],
  },
  {
    lessonId: rootMeaningVaultLessonIds.rootsAcrossSubjectsCheckpoint,
    worldId: rootMeaningVaultWorldId,
    unitId: rootMeaningVaultUnitId,
    activityId: 'activity-g3-cc-rmv-roots-across-subjects-checkpoint',
    difficulty: 2,
    passageIdentifiers: [rootMeaningArtifacts.rootsAcrossSubjects.passage.passageIdentifier],
    questionIdentifiers: [...rootMeaningVaultQuestionIds.rootsAcrossSubjectsCheckpoint],
    lessonTitle: 'Root Meaning Vault Checkpoint: Roots Across Subjects',
    lessonObjective: 'Transfer Greek and Latin root analysis across science, communication, and sound contexts.',
    lessonRole: 'CHECKPOINT', selectionStatus: 'active', contentVersion: rootMeaningVaultContentVersion,
    eligiblePurposes: ['progression', 'verification', 'review'],
  },
  {
    lessonId: rootMeaningVaultLessonIds.unfamiliarWordCheckpoint,
    worldId: rootMeaningVaultWorldId,
    unitId: rootMeaningVaultUnitId,
    activityId: 'activity-g3-cc-rmv-unfamiliar-word-checkpoint',
    difficulty: 2,
    passageIdentifiers: [rootMeaningArtifacts.unfamiliarWord.passage.passageIdentifier],
    questionIdentifiers: [...rootMeaningVaultQuestionIds.unfamiliarWordCheckpoint],
    lessonTitle: 'Root Meaning Vault Checkpoint: Unlock the Unfamiliar Word',
    lessonObjective: 'Use roots, bases, suffixes, and context together to determine unfamiliar-word meaning.',
    lessonRole: 'CHECKPOINT', selectionStatus: 'active', contentVersion: rootMeaningVaultContentVersion,
    eligiblePurposes: ['progression', 'verification', 'review'],
  },
]

export const rootMeaningVaultLessons: ContentPackLesson[] = [...guidedLessons, ...checkpointLessons]

export const grade3ContextCavernRootMeaningVaultPack: ContentPack = {
  manifest: {
    packId: rootMeaningVaultPackId,
    packTitle: 'Grade 3 Context Cavern: Root Meaning Vault',
    gradeBand: 3,
    worldId: rootMeaningVaultWorldId,
    unitId: rootMeaningVaultUnitId,
    primarySkillId: rootMeaningVaultPrimarySkillId,
    benchmarkReferences: ['ELA.3.V.1.2'],
    partialBenchmarkCoverage: 'Grade 3 determination of unfamiliar or less-familiar word meaning through transparent Greek roots, Latin roots, English base words, prefixes, and suffixes, with learner-visible context used to confirm or refine the morphemic inference.',
    difficultyRange: [1, 2],
    contentVersion: rootMeaningVaultContentVersion,
    reviewStatus: 'DRAFT',
    coverageKind: 'benchmark',
    lessonIds: rootMeaningVaultLessons.map((lesson) => lesson.lessonId),
    passageIds: rootMeaningVaultPassages.map((passage) => passage.passageIdentifier),
    questionIds: rootMeaningVaultQuestions.map((question) => question.questionIdentifier),
    coveredPatterns: ['greek-roots', 'latin-roots', 'base-words', 'affixes', 'unfamiliar-word-meaning'],
  },
  passages: rootMeaningVaultPassages,
  questions: rootMeaningVaultQuestions,
  lessons: rootMeaningVaultLessons,
  rootMeaningGuides,
}
