import type { ReadingQuestion } from '../../../../types'
import {
  createEvidencePairQuestion,
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from './questionFactories'
import {
  THEME_TRAIL_CONTENT_VERSION,
  THEME_TRAIL_LESSON_IDS,
  THEME_TRAIL_PASSAGE_IDS,
  THEME_TRAIL_QUESTION_TAGS,
  themeTrailQuestionId,
} from './ids'

const common = {
  benchmarkReference: 'ELA.2.R.1.2',
  skillIdentifier: 'g2-story-scouts-prose',
  reportingCategory: 'Reading Prose and Poetry',
  genre: 'literary',
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2',
  contentVersion: THEME_TRAIL_CONTENT_VERSION,
  reviewStatus: 'DRAFT' as const,
}

const lessonAId = THEME_TRAIL_LESSON_IDS.checkpointA
const lessonBId = THEME_TRAIL_LESSON_IDS.checkpointB
const lessonCId = THEME_TRAIL_LESSON_IDS.checkpointC

const lessonATags = ['theme-identification', 'theme-explanation', 'best-supported-theme', 'theme-supported-by-character-actions', 'theme-supported-by-details']
const lessonBTags = ['theme-identification', 'theme-explanation', 'theme-vs-topic', 'theme-supported-by-events', 'theme-supported-by-details']
const lessonCTags = ['theme-identification', 'theme-explanation', 'theme-vs-summary', 'theme-supported-by-outcome', 'theme-supported-by-details']

const mc = (spec: Parameters<typeof createMultipleChoiceQuestion>[0]) =>
  createMultipleChoiceQuestion(spec)

const ms = (spec: Parameters<typeof createMultiselectQuestion>[0]) =>
  createMultiselectQuestion(spec)

const ht = (spec: Parameters<typeof createHotTextQuestion>[0]) =>
  createHotTextQuestion(spec)

const tm = (spec: Parameters<typeof createTableMatchQuestion>[0]) =>
  createTableMatchQuestion(spec)

const ep = (spec: Parameters<typeof createEvidencePairQuestion>[0]) =>
  createEvidencePairQuestion(spec)

export const themeTrailCheckpointQuestions: ReadingQuestion[] = [
  mc({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.modelBridge,
    lessonIdentifier: lessonAId,
    questionIdentifier: themeTrailQuestionId('checkpoint-a', 'mc-1'),
    prompt: 'Which sentence is the best-supported theme?',
    explanation: 'The story shows that working together helped Omar and Jun use different strengths.',
    evidenceReference: 'theme-support',
    evidenceReferenceIds: [
      'g2-story-scouts-theme-trail-passage-model-bridge-sentence-2',
      'g2-story-scouts-theme-trail-passage-model-bridge-sentence-3',
      'g2-story-scouts-theme-trail-passage-model-bridge-sentence-5',
    ],
    targetVocabulary: ['different', 'strengths', 'together'],
    soundOutChunks: ['dif-fer-ent', 'strengths', 'to-geth-er'],
    tags: [...lessonATags],
    choices: [
      { id: 'choice-a', text: 'Working together lets people use different strengths.' },
      { id: 'choice-b', text: 'Omar and Jun built a model bridge from sticks and tape.' },
      { id: 'choice-c', text: 'Their first try sagged in the middle.' },
      { id: 'choice-d', text: 'The story is mostly about science club.' },
    ],
    correctChoiceIds: ['choice-a'],
  }),
  mc({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.modelBridge,
    lessonIdentifier: lessonAId,
    questionIdentifier: themeTrailQuestionId('checkpoint-a', 'mc-2'),
    prompt: 'Which choice is the topic, not the theme?',
    explanation: 'A topic is a short label. "Building a model bridge" names the story subject, but it is not the full message.',
    evidenceReference: 'topic-versus-theme',
    evidenceReferenceIds: ['g2-story-scouts-theme-trail-passage-model-bridge-sentence-1'],
    targetVocabulary: ['topic', 'theme', 'bridge'],
    soundOutChunks: ['top-ic', 'theme', 'bridge'],
    tags: [...lessonATags, 'theme-vs-topic'],
    choices: [
      { id: 'choice-a', text: 'building a model bridge' },
      { id: 'choice-b', text: 'Working together lets people use different strengths.' },
      { id: 'choice-c', text: 'Omar measured the next stick while Jun balanced the supports.' },
      { id: 'choice-d', text: 'The bridge stood up at last.' },
    ],
    correctChoiceIds: ['choice-a'],
  }),
  mc({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.modelBridge,
    lessonIdentifier: lessonAId,
    questionIdentifier: themeTrailQuestionId('checkpoint-a', 'mc-3'),
    prompt: 'Which choice shows a character action that supports the theme?',
    explanation: 'Swapping jobs shows the two friends used their different strengths together.',
    evidenceReference: 'character-action',
    evidenceReferenceIds: ['g2-story-scouts-theme-trail-passage-model-bridge-sentence-3', 'g2-story-scouts-theme-trail-passage-model-bridge-sentence-4'],
    targetVocabulary: ['strengths', 'together', 'swap'],
    soundOutChunks: ['strengths', 'to-geth-er', 'swap'],
    tags: [...lessonATags, 'theme-supported-by-character-actions'],
    choices: [
      { id: 'choice-a', text: 'They talked, swapped jobs, and tried again.' },
      { id: 'choice-b', text: 'The bridge stood up at last.' },
      { id: 'choice-c', text: 'Omar was good at measuring.' },
      { id: 'choice-d', text: 'Jun balanced the supports.' },
    ],
    correctChoiceIds: ['choice-a'],
  }),
  ms({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.modelBridge,
    lessonIdentifier: lessonAId,
    questionIdentifier: themeTrailQuestionId('checkpoint-a', 'ms-1'),
    prompt: 'Choose all the details that support the theme.',
    explanation: 'These details show different strengths, a problem, and a good outcome.',
    evidenceReference: 'supporting-details',
    evidenceReferenceIds: [
      'g2-story-scouts-theme-trail-passage-model-bridge-sentence-2',
      'g2-story-scouts-theme-trail-passage-model-bridge-sentence-3',
      'g2-story-scouts-theme-trail-passage-model-bridge-sentence-4',
      'g2-story-scouts-theme-trail-passage-model-bridge-sentence-5',
    ],
    targetVocabulary: ['different', 'steady', 'together'],
    soundOutChunks: ['dif-fer-ent', 'stead-y', 'to-geth-er'],
    tags: [...THEME_TRAIL_QUESTION_TAGS, 'theme-supported-by-details'],
    choices: [
      { id: 'choice-a', text: 'Omar was good at measuring, and Jun was good at holding tiny pieces steady.' },
      { id: 'choice-b', text: 'Their first try sagged in the middle, so they talked, swapped jobs, and tried again.' },
      { id: 'choice-c', text: 'The bridge stood up at last, and both boys smiled because their different strengths worked together.' },
      { id: 'choice-d', text: 'The science club table was beside the window.' },
    ],
    correctChoiceIds: ['choice-a', 'choice-b', 'choice-c'],
  }),
  ht({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.modelBridge,
    lessonIdentifier: lessonAId,
    questionIdentifier: themeTrailQuestionId('checkpoint-a', 'ht-1'),
    prompt: 'Select the sentence that shows the friends used different strengths.',
    explanation: 'The second sentence tells us one friend measured and the other held the pieces steady.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['g2-story-scouts-theme-trail-passage-model-bridge-sentence-2'],
    targetVocabulary: ['different', 'strengths'],
    soundOutChunks: ['dif-fer-ent', 'strengths'],
    tags: [...lessonATags, 'theme-supported-by-character-actions'],
    selectableSegments: [
      {
        id: 'segment-1',
        text: 'Omar was good at measuring, and Jun was good at holding tiny pieces steady.',
      },
      {
        id: 'segment-2',
        text: 'Their first try sagged in the middle, so they talked, swapped jobs, and tried again.',
      },
      {
        id: 'segment-3',
        text: 'The bridge stood up at last, and both boys smiled because their different strengths worked together.',
      },
    ],
    correctSegmentIds: ['segment-1'],
  }),
  tm({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.modelBridge,
    lessonIdentifier: lessonAId,
    questionIdentifier: themeTrailQuestionId('checkpoint-a', 'tm-1'),
    prompt: 'Match each detail to what it shows.',
    explanation: 'Each detail points to teamwork, different strengths, or the outcome.',
    evidenceReference: 'detail-to-meaning',
    evidenceReferenceIds: [
      'g2-story-scouts-theme-trail-passage-model-bridge-sentence-2',
      'g2-story-scouts-theme-trail-passage-model-bridge-sentence-3',
      'g2-story-scouts-theme-trail-passage-model-bridge-sentence-5',
    ],
    targetVocabulary: ['different', 'together', 'bridge'],
    soundOutChunks: ['dif-fer-ent', 'to-geth-er', 'bridge'],
    tags: [...lessonATags, 'theme-supported-by-events'],
    rows: [
      {
        id: 'row-1',
        prompt: 'What does Omar was good at measuring show?',
        correctChoiceId: 'skill-choice',
        options: [
          { id: 'skill-choice', text: 'one useful strength' },
          { id: 'storm-choice', text: 'a bad weather clue' },
          { id: 'time-choice', text: 'what time it was' },
          { id: 'food-choice', text: 'what they ate' },
        ],
      },
      {
        id: 'row-2',
        prompt: 'What does Their first try sagged in the middle show?',
        correctChoiceId: 'problem-choice',
        options: [
          { id: 'problem-choice', text: 'the first plan had a problem' },
          { id: 'finish-choice', text: 'the work was already finished' },
          { id: 'song-choice', text: 'the club was singing' },
          { id: 'window-choice', text: 'they were near a window' },
        ],
      },
      {
        id: 'row-3',
        prompt: 'What does they talked, swapped jobs, and tried again show?',
        correctChoiceId: 'retry-choice',
        options: [
          { id: 'retry-choice', text: 'they kept trying a new plan' },
          { id: 'quiet-choice', text: 'they stayed silent' },
          { id: 'stop-choice', text: 'they quit for the day' },
          { id: 'book-choice', text: 'they read a book' },
        ],
      },
      {
        id: 'row-4',
        prompt: 'What does their different strengths worked together show?',
        correctChoiceId: 'theme-choice',
        options: [
          { id: 'theme-choice', text: 'working together can use different strengths' },
          { id: 'bridge-choice', text: 'the bridge was made of sticks' },
          { id: 'club-choice', text: 'science club was the setting' },
          { id: 'smile-choice', text: 'the boys were happy' },
        ],
      },
    ],
  }),
  ep({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.modelBridge,
    lessonIdentifier: lessonAId,
    questionIdentifier: themeTrailQuestionId('checkpoint-a', 'ep-1'),
    prompt: 'Which theme is best supported by the story?',
    explanation: 'The story shows that working together helped the boys use their different strengths.',
    evidenceReference: 'best-supported-theme',
    evidenceReferenceIds: [
      'g2-story-scouts-theme-trail-passage-model-bridge-sentence-2',
      'g2-story-scouts-theme-trail-passage-model-bridge-sentence-3',
      'g2-story-scouts-theme-trail-passage-model-bridge-sentence-5',
    ],
    targetVocabulary: ['different', 'together', 'strengths'],
    soundOutChunks: ['dif-fer-ent', 'to-geth-er', 'strengths'],
    tags: [...lessonATags, 'best-supported-theme'],
    partAChoices: [
      { id: 'part-a-1', text: 'Working together lets people use different strengths.' },
      { id: 'part-a-2', text: 'The story is about a model bridge.' },
      { id: 'part-a-3', text: 'Omar and Jun are in science club.' },
      { id: 'part-a-4', text: 'The bridge was made of sticks and tape.' },
    ],
    partACorrectChoiceId: 'part-a-1',
    partBChoices: [
      { id: 'part-b-1', text: 'Their first try sagged in the middle, so they talked, swapped jobs, and tried again.' },
      { id: 'part-b-2', text: 'The science club table was beside the window.' },
      { id: 'part-b-3', text: 'Omar measured the next stick while Jun balanced the supports.' },
      { id: 'part-b-4', text: 'The bridge stood up at last, and both boys smiled because their different strengths worked together.' },
    ],
    partBCorrectChoiceId: 'part-b-4',
  }),
  mc({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.birdhousePlan,
    lessonIdentifier: lessonBId,
    questionIdentifier: themeTrailQuestionId('checkpoint-b', 'mc-1'),
    prompt: 'Which sentence is the best-supported theme?',
    explanation: 'The story shows that trying a new plan helped Ava solve the problem.',
    evidenceReference: 'theme-support',
    evidenceReferenceIds: [
      'g2-story-scouts-theme-trail-passage-birdhouse-plan-sentence-3',
      'g2-story-scouts-theme-trail-passage-birdhouse-plan-sentence-4',
      'g2-story-scouts-theme-trail-passage-birdhouse-plan-sentence-5',
    ],
    targetVocabulary: ['new', 'plan', 'problem'],
    soundOutChunks: ['new', 'plan', 'prob-lem'],
    tags: [...lessonBTags],
    choices: [
      { id: 'choice-a', text: 'Trying a new plan can help when the first plan does not work.' },
      { id: 'choice-b', text: 'Ava tried to hang a birdhouse on the fence by the garden.' },
      { id: 'choice-c', text: 'The birdhouse swung sideways.' },
      { id: 'choice-d', text: 'The story is about a windy afternoon.' },
    ],
    correctChoiceIds: ['choice-a'],
  }),
  mc({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.birdhousePlan,
    lessonIdentifier: lessonBId,
    questionIdentifier: themeTrailQuestionId('checkpoint-b', 'mc-2'),
    prompt: 'Which choice is the topic, not the theme?',
    explanation: 'A topic is a short label. "Hanging a birdhouse" names the story subject, but it is not the full message.',
    evidenceReference: 'topic-versus-theme',
    evidenceReferenceIds: ['g2-story-scouts-theme-trail-passage-birdhouse-plan-sentence-1'],
    targetVocabulary: ['topic', 'theme', 'birdhouse'],
    soundOutChunks: ['top-ic', 'theme', 'bird-house'],
    tags: [...lessonBTags, 'theme-vs-topic'],
    choices: [
      { id: 'choice-a', text: 'hanging a birdhouse' },
      { id: 'choice-b', text: 'Trying a new plan can help when the first plan does not work.' },
      { id: 'choice-c', text: 'The birdhouse stayed steady.' },
      { id: 'choice-d', text: 'Ava chose a new plan.' },
    ],
    correctChoiceIds: ['choice-a'],
  }),
  mc({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.birdhousePlan,
    lessonIdentifier: lessonBId,
    questionIdentifier: themeTrailQuestionId('checkpoint-b', 'mc-3'),
    prompt: 'Which choice shows a character action that supports the theme?',
    explanation: 'Ava chose a new plan when the first knot did not work.',
    evidenceReference: 'character-action',
    evidenceReferenceIds: ['g2-story-scouts-theme-trail-passage-birdhouse-plan-sentence-3', 'g2-story-scouts-theme-trail-passage-birdhouse-plan-sentence-4'],
    targetVocabulary: ['plan', 'instead', 'steady'],
    soundOutChunks: ['plan', 'in-stead', 'stead-y'],
    tags: [...lessonBTags, 'theme-supported-by-character-actions'],
    choices: [
      { id: 'choice-a', text: 'Ava paused, looked at the twine, and chose a new plan.' },
      { id: 'choice-b', text: 'The first knot slipped twice.' },
      { id: 'choice-c', text: 'The birdhouse stayed steady.' },
      { id: 'choice-d', text: 'The fence was by the garden.' },
    ],
    correctChoiceIds: ['choice-a'],
  }),
  ms({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.birdhousePlan,
    lessonIdentifier: lessonBId,
    questionIdentifier: themeTrailQuestionId('checkpoint-b', 'ms-1'),
    prompt: 'Choose all the details that support the theme.',
    explanation: 'These details show the first plan failed, Ava changed plans, and the new plan worked.',
    evidenceReference: 'supporting-details',
    evidenceReferenceIds: [
      'g2-story-scouts-theme-trail-passage-birdhouse-plan-sentence-2',
      'g2-story-scouts-theme-trail-passage-birdhouse-plan-sentence-3',
      'g2-story-scouts-theme-trail-passage-birdhouse-plan-sentence-4',
      'g2-story-scouts-theme-trail-passage-birdhouse-plan-sentence-5',
    ],
    targetVocabulary: ['plan', 'steady', 'instead'],
    soundOutChunks: ['plan', 'stead-y', 'in-stead'],
    tags: [...THEME_TRAIL_QUESTION_TAGS, 'theme-supported-by-details'],
    choices: [
      { id: 'choice-a', text: 'The first knot slipped twice, and the birdhouse swung sideways.' },
      { id: 'choice-b', text: 'Ava paused, looked at the twine, and chose a new plan.' },
      { id: 'choice-c', text: 'She tied the knot around the post instead, then added one more loop to hold it tight.' },
      { id: 'choice-d', text: 'The garden had a fence.' },
    ],
    correctChoiceIds: ['choice-a', 'choice-b', 'choice-c'],
  }),
  ht({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.birdhousePlan,
    lessonIdentifier: lessonBId,
    questionIdentifier: themeTrailQuestionId('checkpoint-b', 'ht-1'),
    prompt: 'Select the sentence that shows Ava chose a new plan.',
    explanation: 'The third sentence says Ava paused, looked, and chose a new plan.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['g2-story-scouts-theme-trail-passage-birdhouse-plan-sentence-3'],
    targetVocabulary: ['plan', 'paused'],
    soundOutChunks: ['plan', 'paus-ed'],
    tags: [...lessonBTags, 'theme-supported-by-character-actions'],
    selectableSegments: [
      {
        id: 'segment-1',
        text: 'The first knot slipped twice, and the birdhouse swung sideways.',
      },
      {
        id: 'segment-2',
        text: 'Ava paused, looked at the twine, and chose a new plan.',
      },
      {
        id: 'segment-3',
        text: 'The birdhouse stayed steady, and Ava felt proud that trying a new plan solved the problem.',
      },
    ],
    correctSegmentIds: ['segment-2'],
  }),
  tm({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.birdhousePlan,
    lessonIdentifier: lessonBId,
    questionIdentifier: themeTrailQuestionId('checkpoint-b', 'tm-1'),
    prompt: 'Match each detail to what it shows.',
    explanation: 'Each detail shows a problem, a new plan, and a good result.',
    evidenceReference: 'detail-to-meaning',
    evidenceReferenceIds: [
      'g2-story-scouts-theme-trail-passage-birdhouse-plan-sentence-2',
      'g2-story-scouts-theme-trail-passage-birdhouse-plan-sentence-3',
      'g2-story-scouts-theme-trail-passage-birdhouse-plan-sentence-4',
      'g2-story-scouts-theme-trail-passage-birdhouse-plan-sentence-5',
    ],
    targetVocabulary: ['plan', 'steady', 'problem'],
    soundOutChunks: ['plan', 'stead-y', 'prob-lem'],
    tags: [...lessonBTags, 'theme-supported-by-events'],
    rows: [
      {
        id: 'row-1',
        prompt: 'What does The first knot slipped twice show?',
        correctChoiceId: 'first-plan-choice',
        options: [
          { id: 'first-plan-choice', text: 'the first plan did not work' },
          { id: 'song-choice', text: 'someone was singing' },
          { id: 'tree-choice', text: 'the garden had a tree' },
          { id: 'bird-choice', text: 'the birdhouse was empty' },
        ],
      },
      {
        id: 'row-2',
        prompt: 'What does Ava paused, looked at the twine, and chose a new plan show?',
        correctChoiceId: 'new-plan-choice',
        options: [
          { id: 'new-plan-choice', text: 'she tried a different plan' },
          { id: 'wind-choice', text: 'the wind stopped' },
          { id: 'fence-choice', text: 'the fence moved' },
          { id: 'garden-choice', text: 'she watered the garden' },
        ],
      },
      {
        id: 'row-3',
        prompt: 'What does she tied the knot around the post instead show?',
        correctChoiceId: 'instead-choice',
        options: [
          { id: 'instead-choice', text: 'she used a new way' },
          { id: 'slip-choice', text: 'the knot slipped again' },
          { id: 'sleep-choice', text: 'she went home' },
          { id: 'rain-choice', text: 'it started to rain' },
        ],
      },
      {
        id: 'row-4',
        prompt: 'What does the birdhouse stayed steady show?',
        correctChoiceId: 'outcome-choice',
        options: [
          { id: 'outcome-choice', text: 'the new plan worked' },
          { id: 'topic-choice', text: 'the story is about a birdhouse' },
          { id: 'problem-choice', text: 'the first knot slipped' },
          { id: 'garden-choice-2', text: 'the garden was sunny' },
        ],
      },
    ],
  }),
  ep({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.birdhousePlan,
    lessonIdentifier: lessonBId,
    questionIdentifier: themeTrailQuestionId('checkpoint-b', 'ep-1'),
    prompt: 'Which theme is best supported by the story?',
    explanation: 'The story shows that trying a new plan helped Ava solve the problem.',
    evidenceReference: 'best-supported-theme',
    evidenceReferenceIds: [
      'g2-story-scouts-theme-trail-passage-birdhouse-plan-sentence-3',
      'g2-story-scouts-theme-trail-passage-birdhouse-plan-sentence-4',
      'g2-story-scouts-theme-trail-passage-birdhouse-plan-sentence-5',
    ],
    targetVocabulary: ['plan', 'problem', 'steady'],
    soundOutChunks: ['plan', 'prob-lem', 'stead-y'],
    tags: [...lessonBTags, 'best-supported-theme'],
    partAChoices: [
      { id: 'part-a-1', text: 'Trying a new plan can help when the first plan does not work.' },
      { id: 'part-a-2', text: 'Ava hung a birdhouse on a windy afternoon.' },
      { id: 'part-a-3', text: 'The first knot slipped twice.' },
      { id: 'part-a-4', text: 'The birdhouse was by the garden fence.' },
    ],
    partACorrectChoiceId: 'part-a-1',
    partBChoices: [
      { id: 'part-b-1', text: 'Ava paused, looked at the twine, and chose a new plan.' },
      { id: 'part-b-2', text: 'She tied the knot around the post instead, then added one more loop to hold it tight.' },
      { id: 'part-b-3', text: 'The birdhouse stayed steady, and Ava felt proud that trying a new plan solved the problem.' },
      { id: 'part-b-4', text: 'The first knot slipped twice, and the birdhouse swung sideways.' },
    ],
    partBCorrectChoiceId: 'part-b-3',
  }),
  mc({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.bookSwapTrust,
    lessonIdentifier: lessonCId,
    questionIdentifier: themeTrailQuestionId('checkpoint-c', 'mc-1'),
    prompt: 'Which sentence is the best-supported theme?',
    explanation: 'The story shows that taking responsibility helped Eli rebuild trust.',
    evidenceReference: 'theme-support',
    evidenceReferenceIds: [
      'g2-story-scouts-theme-trail-passage-book-swap-trust-sentence-3',
      'g2-story-scouts-theme-trail-passage-book-swap-trust-sentence-4',
      'g2-story-scouts-theme-trail-passage-book-swap-trust-sentence-5',
    ],
    targetVocabulary: ['responsibility', 'trust', 'truth'],
    soundOutChunks: ['re-spon-si-bil-i-ty', 'trust', 'truth'],
    tags: [...lessonCTags],
    choices: [
      { id: 'choice-a', text: 'Taking responsibility can help rebuild trust.' },
      { id: 'choice-b', text: 'Eli borrowed a photo book on Friday.' },
      { id: 'choice-c', text: 'He wrote an apology note for the class shelf.' },
      { id: 'choice-d', text: 'The story is about a class book swap.' },
    ],
    correctChoiceIds: ['choice-a'],
  }),
  mc({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.bookSwapTrust,
    lessonIdentifier: lessonCId,
    questionIdentifier: themeTrailQuestionId('checkpoint-c', 'mc-2'),
    prompt: 'Which choice is the topic, not the theme?',
    explanation: 'A topic is a short label. "Returning a library book" names the subject, but it is not the full message.',
    evidenceReference: 'topic-versus-theme',
    evidenceReferenceIds: ['g2-story-scouts-theme-trail-passage-book-swap-trust-sentence-1'],
    targetVocabulary: ['topic', 'theme', 'trust'],
    soundOutChunks: ['top-ic', 'theme', 'trust'],
    tags: [...lessonCTags, 'theme-vs-summary'],
    choices: [
      { id: 'choice-a', text: 'returning a library book' },
      { id: 'choice-b', text: 'Taking responsibility can help rebuild trust.' },
      { id: 'choice-c', text: 'Eli told his teacher the truth.' },
      { id: 'choice-d', text: 'His teacher smiled.' },
    ],
    correctChoiceIds: ['choice-a'],
  }),
  mc({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.bookSwapTrust,
    lessonIdentifier: lessonCId,
    questionIdentifier: themeTrailQuestionId('checkpoint-c', 'mc-3'),
    prompt: 'Which choice shows a character action that supports the theme?',
    explanation: 'Returning the book and writing the apology note show responsibility.',
    evidenceReference: 'character-action',
    evidenceReferenceIds: ['g2-story-scouts-theme-trail-passage-book-swap-trust-sentence-3'],
    targetVocabulary: ['responsibility', 'apology', 'truth'],
    soundOutChunks: ['re-spon-si-bil-i-ty', 'a-pol-o-gy', 'truth'],
    tags: [...lessonCTags, 'theme-supported-by-character-actions'],
    choices: [
      { id: 'choice-a', text: 'Eli told his teacher the truth, returned the book, and wrote an apology note for the class shelf.' },
      { id: 'choice-b', text: 'He forgot the date and left the book in his backpack all weekend.' },
      { id: 'choice-c', text: 'He borrowed a photo book.' },
      { id: 'choice-d', text: 'The class shelf had new books.' },
    ],
    correctChoiceIds: ['choice-a'],
  }),
  ms({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.bookSwapTrust,
    lessonIdentifier: lessonCId,
    questionIdentifier: themeTrailQuestionId('checkpoint-c', 'ms-1'),
    prompt: 'Choose all the details that support the theme.',
    explanation: 'These details show Eli told the truth, made it right, and earned trust again.',
    evidenceReference: 'supporting-details',
    evidenceReferenceIds: [
      'g2-story-scouts-theme-trail-passage-book-swap-trust-sentence-2',
      'g2-story-scouts-theme-trail-passage-book-swap-trust-sentence-3',
      'g2-story-scouts-theme-trail-passage-book-swap-trust-sentence-4',
      'g2-story-scouts-theme-trail-passage-book-swap-trust-sentence-5',
    ],
    targetVocabulary: ['responsibility', 'apology', 'trust'],
    soundOutChunks: ['re-spon-si-bil-i-ty', 'a-pol-o-gy', 'trust'],
    tags: [...THEME_TRAIL_QUESTION_TAGS, 'theme-supported-by-details'],
    choices: [
      { id: 'choice-a', text: 'On Monday, Eli told his teacher the truth, returned the book, and wrote an apology note for the class shelf.' },
      { id: 'choice-b', text: 'He also helped sort the new books before recess.' },
      { id: 'choice-c', text: 'His teacher smiled because Eli took responsibility and showed he could be trusted again.' },
      { id: 'choice-d', text: 'He borrowed a photo book and promised to return it on Friday.' },
    ],
    correctChoiceIds: ['choice-a', 'choice-b', 'choice-c'],
  }),
  ht({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.bookSwapTrust,
    lessonIdentifier: lessonCId,
    questionIdentifier: themeTrailQuestionId('checkpoint-c', 'ht-1'),
    prompt: 'Select the sentence that shows Eli made things right.',
    explanation: 'The third sentence says he told the truth, returned the book, and wrote an apology note.',
    evidenceReference: 'sentence-clue',
    evidenceReferenceIds: ['g2-story-scouts-theme-trail-passage-book-swap-trust-sentence-3'],
    targetVocabulary: ['truth', 'apology', 'responsibility'],
    soundOutChunks: ['truth', 'a-pol-o-gy', 're-spon-si-bil-i-ty'],
    tags: [...lessonCTags, 'theme-supported-by-character-actions'],
    selectableSegments: [
      {
        id: 'segment-1',
        text: 'He forgot the date and left the book in his backpack all weekend.',
      },
      {
        id: 'segment-2',
        text: 'On Monday, Eli told his teacher the truth, returned the book, and wrote an apology note for the class shelf.',
      },
      {
        id: 'segment-3',
        text: 'His teacher smiled because Eli took responsibility and showed he could be trusted again.',
      },
    ],
    correctSegmentIds: ['segment-2'],
  }),
  tm({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.bookSwapTrust,
    lessonIdentifier: lessonCId,
    questionIdentifier: themeTrailQuestionId('checkpoint-c', 'tm-1'),
    prompt: 'Match each detail to what it shows.',
    explanation: 'Each detail shows responsibility, a good choice, or the outcome.',
    evidenceReference: 'detail-to-meaning',
    evidenceReferenceIds: [
      'g2-story-scouts-theme-trail-passage-book-swap-trust-sentence-2',
      'g2-story-scouts-theme-trail-passage-book-swap-trust-sentence-3',
      'g2-story-scouts-theme-trail-passage-book-swap-trust-sentence-4',
      'g2-story-scouts-theme-trail-passage-book-swap-trust-sentence-5',
    ],
    targetVocabulary: ['responsibility', 'trust', 'weekend'],
    soundOutChunks: ['re-spon-si-bil-i-ty', 'trust', 'week-end'],
    tags: [...lessonCTags, 'theme-supported-by-outcome'],
    rows: [
      {
        id: 'row-1',
        prompt: 'What does Eli told his teacher the truth show?',
        correctChoiceId: 'honest-choice',
        options: [
          { id: 'honest-choice', text: 'he made an honest choice' },
          { id: 'book-choice', text: 'he borrowed a book' },
          { id: 'shelf-choice', text: 'the shelf was full' },
          { id: 'week-choice', text: 'it was the weekend' },
        ],
      },
      {
        id: 'row-2',
        prompt: 'What does wrote an apology note show?',
        correctChoiceId: 'fix-choice',
        options: [
          { id: 'fix-choice', text: 'he tried to make it right' },
          { id: 'read-choice', text: 'he wanted to read more' },
          { id: 'wait-choice', text: 'he had to wait' },
          { id: 'class-choice', text: 'the class was busy' },
        ],
      },
      {
        id: 'row-3',
        prompt: 'What does helped sort the new books show?',
        correctChoiceId: 'responsible-choice',
        options: [
          { id: 'responsible-choice', text: 'he was taking responsibility' },
          { id: 'sleep-choice', text: 'he was sleepy' },
          { id: 'borrow-choice', text: 'he borrowed again' },
          { id: 'note-choice', text: 'he wrote another note' },
        ],
      },
      {
        id: 'row-4',
        prompt: 'What does he could be trusted again show?',
        correctChoiceId: 'trust-choice',
        options: [
          { id: 'trust-choice', text: 'the relationship was repaired' },
          { id: 'book-choice-2', text: 'the book was new' },
          { id: 'date-choice', text: 'the date was forgotten' },
          { id: 'backpack-choice', text: 'the backpack was full' },
        ],
      },
    ],
  }),
  ep({
    ...common,
    difficulty: 2,
    passageIdentifier: THEME_TRAIL_PASSAGE_IDS.bookSwapTrust,
    lessonIdentifier: lessonCId,
    questionIdentifier: themeTrailQuestionId('checkpoint-c', 'ep-1'),
    prompt: 'Which theme is best supported by the story?',
    explanation: 'The story shows that taking responsibility helped Eli rebuild trust.',
    evidenceReference: 'best-supported-theme',
    evidenceReferenceIds: [
      'g2-story-scouts-theme-trail-passage-book-swap-trust-sentence-3',
      'g2-story-scouts-theme-trail-passage-book-swap-trust-sentence-4',
      'g2-story-scouts-theme-trail-passage-book-swap-trust-sentence-5',
    ],
    targetVocabulary: ['responsibility', 'trust', 'truth'],
    soundOutChunks: ['re-spon-si-bil-i-ty', 'trust', 'truth'],
    tags: [...lessonCTags, 'best-supported-theme'],
    partAChoices: [
      { id: 'part-a-1', text: 'Taking responsibility can help rebuild trust.' },
      { id: 'part-a-2', text: 'Eli borrowed a photo book.' },
      { id: 'part-a-3', text: 'He forgot the date and left the book in his backpack all weekend.' },
      { id: 'part-a-4', text: 'The class shelf had new books.' },
    ],
    partACorrectChoiceId: 'part-a-1',
    partBChoices: [
      { id: 'part-b-1', text: 'On Monday, Eli told his teacher the truth, returned the book, and wrote an apology note for the class shelf.' },
      { id: 'part-b-2', text: 'He also helped sort the new books before recess.' },
      { id: 'part-b-3', text: 'His teacher smiled because Eli took responsibility and showed he could be trusted again.' },
      { id: 'part-b-4', text: 'He forgot the date and left the book in his backpack all weekend.' },
    ],
    partBCorrectChoiceId: 'part-b-3',
  }),
]
