import type { ReadingQuestion } from '../../../../types'
import { textFeatureHuntPassages } from './passages'
import {
  TEXT_FEATURE_HUNT_CONTENT_VERSION,
  TEXT_FEATURE_HUNT_FEATURE_IDS,
  TEXT_FEATURE_HUNT_LESSON_IDS,
  TEXT_FEATURE_HUNT_PASSAGE_IDS,
  TEXT_FEATURE_HUNT_QUESTION_TAGS,
  textFeatureHuntQuestionId,
  textFeatureHuntSentenceId,
} from './ids'
import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from './questionFactories'

const [feederWatch, gardenGrid] = textFeatureHuntPassages
const feederWatchSentences = feederWatch.sentences ?? []
const gardenGridSentences = gardenGrid.sentences ?? []

const common = {
  benchmarkReference: 'ELA.2.R.2.1' as const,
  skillIdentifier: 'g2-information-detectives-reading' as const,
  reportingCategory: 'Reading Informational Text' as const,
  genre: 'informational' as const,
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2' as const,
  contentVersion: TEXT_FEATURE_HUNT_CONTENT_VERSION,
  reviewStatus: 'DRAFT' as const,
}

const mc = (spec: Parameters<typeof createMultipleChoiceQuestion>[0]) => createMultipleChoiceQuestion(spec)
const ms = (spec: Parameters<typeof createMultiselectQuestion>[0]) => createMultiselectQuestion(spec)
const ht = (spec: Parameters<typeof createHotTextQuestion>[0]) => createHotTextQuestion(spec)
const tm = (spec: Parameters<typeof createTableMatchQuestion>[0]) => createTableMatchQuestion(spec)

const broadTags = [...TEXT_FEATURE_HUNT_QUESTION_TAGS.broad]

export const textFeatureHuntBuildingBlockQuestions: ReadingQuestion[] = [
  mc({
    ...common,
    difficulty: 0,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.feederWatch,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.buildingBlockA,
    questionIdentifier: textFeatureHuntQuestionId('building-block-a', 'mc-1'),
    prompt: 'What does the title Feeder Watch help the reader understand?',
    explanation: 'The title previews that the passage is about watching birds at a feeder.',
    evidenceReference: 'title-contribution',
    evidenceReferenceIds: [TEXT_FEATURE_HUNT_FEATURE_IDS.feederWatch.title],
    targetVocabulary: ['title', 'topic', 'feeder'],
    soundOutChunks: ['ti-tle', 'to-pic'],
    tags: [...broadTags, 'title-contribution'],
    choices: [
      { id: 'choice-a', text: 'The text is about birds visiting a feeder.' },
      { id: 'choice-b', text: 'The text explains how to build a birdhouse.' },
      { id: 'choice-c', text: 'The text is a map of a garden path.' },
      { id: 'choice-d', text: 'The text is about painting animal signs.' },
    ],
    correctChoiceIds: ['choice-a'],
  }),
  mc({
    ...common,
    difficulty: 0,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.feederWatch,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.buildingBlockA,
    questionIdentifier: textFeatureHuntQuestionId('building-block-a', 'mc-2'),
    prompt: 'What does the heading Counting Visitors tell the reader?',
    explanation: 'The heading names the section and tells the reader this part is about counting the birds that visit.',
    evidenceReference: 'heading-contribution',
    evidenceReferenceIds: [TEXT_FEATURE_HUNT_FEATURE_IDS.feederWatch.headingCount],
    targetVocabulary: ['heading', 'section', 'counting'],
    soundOutChunks: ['head-ing', 'sec-tion'],
    tags: [...broadTags, 'heading-contribution'],
    choices: [
      { id: 'choice-a', text: 'This section is about a storm in the sky.' },
      { id: 'choice-b', text: 'This section is about making a flower bed.' },
      { id: 'choice-c', text: 'This section is about a moon graph.' },
      { id: 'choice-d', text: 'This section is about counting bird visitors.' },
    ],
    correctChoiceIds: ['choice-d'],
  }),
  ms({
    ...common,
    difficulty: 0,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.feederWatch,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.buildingBlockA,
    questionIdentifier: textFeatureHuntQuestionId('building-block-a', 'ms-1'),
    prompt: 'Choose the two features that help the reader compare bird visits.',
    explanation: 'The graph organizes the bird counts, and the caption explains what the tallest bar means.',
    evidenceReference: 'feature-meaning',
    evidenceReferenceIds: [
      TEXT_FEATURE_HUNT_FEATURE_IDS.feederWatch.graph,
      TEXT_FEATURE_HUNT_FEATURE_IDS.feederWatch.caption,
    ],
    targetVocabulary: ['graph', 'caption', 'compare'],
    soundOutChunks: ['graph', 'cap-tion'],
    tags: [...broadTags, 'graph-contribution', 'caption-contribution'],
    choices: [
      { id: 'choice-a', text: 'The graph' },
      { id: 'choice-b', text: 'The caption' },
      { id: 'choice-c', text: 'The title' },
      { id: 'choice-d', text: 'The glossary' },
    ],
    correctChoiceIds: ['choice-a', 'choice-b'],
  }),
  ht({
    ...common,
    difficulty: 0,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.feederWatch,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.buildingBlockA,
    questionIdentifier: textFeatureHuntQuestionId('building-block-a', 'ht-1'),
    prompt: 'Select the sentence that tells what the graph helps the reader do.',
    explanation: 'The graph sentence explains that the reader can compare which bird appears most often.',
    evidenceReference: 'graph-meaning',
    evidenceReferenceIds: [textFeatureHuntSentenceId('feeder-watch', 3)],
    targetVocabulary: ['graph', 'compare', 'most'],
    soundOutChunks: ['graph', 'com-pare'],
    tags: [...broadTags, 'graph-contribution', 'feature-body-connection'],
    selectableSegments: feederWatchSentences.map((sentence) => ({ id: sentence.sentenceId, text: sentence.text })),
    correctSegmentIds: [textFeatureHuntSentenceId('feeder-watch', 3)],
  }),
  tm({
    ...common,
    difficulty: 0,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.feederWatch,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.buildingBlockA,
    questionIdentifier: textFeatureHuntQuestionId('building-block-a', 'tm-1'),
    prompt: 'Match each feature to what it does for the reader.',
    explanation: 'Each feature gives a different kind of meaning to the passage.',
    evidenceReference: 'feature-job-match',
    evidenceReferenceIds: [
      TEXT_FEATURE_HUNT_FEATURE_IDS.feederWatch.title,
      TEXT_FEATURE_HUNT_FEATURE_IDS.feederWatch.graph,
      TEXT_FEATURE_HUNT_FEATURE_IDS.feederWatch.caption,
      TEXT_FEATURE_HUNT_FEATURE_IDS.feederWatch.glossary,
    ],
    targetVocabulary: ['feature', 'meaning', 'job'],
    soundOutChunks: ['fea-ture', 'mean-ing'],
    tags: [...broadTags, 'feature-selection-for-purpose', 'feature-body-connection'],
    rows: [
      {
        id: 'row-title',
        prompt: 'Title',
        correctChoiceId: 'option-title',
        options: [
          { id: 'option-title', text: 'Gives a clue about the whole text' },
          { id: 'option-graph', text: 'Compares the bird counts' },
          { id: 'option-caption', text: 'Explains the tall blue bar' },
          { id: 'option-glossary', text: 'Defines a word from the text' },
        ],
      },
      {
        id: 'row-graph',
        prompt: 'Graph',
        correctChoiceId: 'option-graph-2',
        options: [
          { id: 'option-title-2', text: 'Gives a clue about the whole text' },
          { id: 'option-graph-2', text: 'Compares the bird counts' },
          { id: 'option-caption-2', text: 'Explains the tall blue bar' },
          { id: 'option-glossary-2', text: 'Defines a word from the text' },
        ],
      },
      {
        id: 'row-caption',
        prompt: 'Caption',
        correctChoiceId: 'option-caption-3',
        options: [
          { id: 'option-title-3', text: 'Gives a clue about the whole text' },
          { id: 'option-graph-3', text: 'Compares the bird counts' },
          { id: 'option-caption-3', text: 'Explains the tall blue bar' },
          { id: 'option-glossary-3', text: 'Defines a word from the text' },
        ],
      },
      {
        id: 'row-glossary',
        prompt: 'Glossary',
        correctChoiceId: 'option-glossary-4',
        options: [
          { id: 'option-title-4', text: 'Gives a clue about the whole text' },
          { id: 'option-graph-4', text: 'Compares the bird counts' },
          { id: 'option-caption-4', text: 'Explains the tall blue bar' },
          { id: 'option-glossary-4', text: 'Defines a word from the text' },
        ],
      },
    ],
  }),
  mc({
    ...common,
    difficulty: 0,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.gardenGrid,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.buildingBlockB,
    questionIdentifier: textFeatureHuntQuestionId('building-block-b', 'mc-1'),
    prompt: 'What does the title Garden Grid help the reader understand?',
    explanation: 'The title previews that the passage is about a garden and a map grid that helps readers find places.',
    evidenceReference: 'title-contribution',
    evidenceReferenceIds: [TEXT_FEATURE_HUNT_FEATURE_IDS.gardenGrid.title],
    targetVocabulary: ['title', 'garden', 'grid'],
    soundOutChunks: ['ti-tle', 'gar-den'],
    tags: [...broadTags, 'title-contribution'],
    choices: [
      { id: 'choice-a', text: 'The text is about a class graph.' },
      { id: 'choice-b', text: 'The text is about moon notes.' },
      { id: 'choice-c', text: 'The text is about a garden map and plant picture.' },
      { id: 'choice-d', text: 'The text is about making a weather chart.' },
    ],
    correctChoiceIds: ['choice-c'],
  }),
  mc({
    ...common,
    difficulty: 0,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.gardenGrid,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.buildingBlockB,
    questionIdentifier: textFeatureHuntQuestionId('building-block-b', 'mc-2'),
    prompt: 'Which feature helps the reader find the bean bed?',
    explanation: 'The map shows where the bean bed is, so the reader can locate it quickly.',
    evidenceReference: 'feature-selection-for-purpose',
    evidenceReferenceIds: [TEXT_FEATURE_HUNT_FEATURE_IDS.gardenGrid.map],
    targetVocabulary: ['map', 'find', 'locate'],
    soundOutChunks: ['map', 'lo-cate'],
    tags: [...broadTags, 'map-contribution', 'feature-selection-for-purpose'],
    choices: [
      { id: 'choice-a', text: 'The title' },
      { id: 'choice-b', text: 'The map' },
      { id: 'choice-c', text: 'The glossary' },
      { id: 'choice-d', text: 'The caption' },
    ],
    correctChoiceIds: ['choice-b'],
  }),
  ms({
    ...common,
    difficulty: 0,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.gardenGrid,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.buildingBlockB,
    questionIdentifier: textFeatureHuntQuestionId('building-block-b', 'ms-1'),
    prompt: 'Choose the two features that help the reader locate the bean bed.',
    explanation: 'The map shows the places, and the caption points readers to the sunny corner.',
    evidenceReference: 'feature-body-connection',
    evidenceReferenceIds: [
      TEXT_FEATURE_HUNT_FEATURE_IDS.gardenGrid.map,
      TEXT_FEATURE_HUNT_FEATURE_IDS.gardenGrid.caption,
    ],
    targetVocabulary: ['map', 'caption', 'locate'],
    soundOutChunks: ['map', 'cap-tion'],
    tags: [...broadTags, 'map-contribution', 'caption-contribution'],
    choices: [
      { id: 'choice-a', text: 'The map' },
      { id: 'choice-b', text: 'The caption' },
      { id: 'choice-c', text: 'The title' },
      { id: 'choice-d', text: 'The illustration' },
    ],
    correctChoiceIds: ['choice-a', 'choice-b'],
  }),
  ht({
    ...common,
    difficulty: 0,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.gardenGrid,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.buildingBlockB,
    questionIdentifier: textFeatureHuntQuestionId('building-block-b', 'ht-1'),
    prompt: 'Select the sentence that tells what the map helps the reader do.',
    explanation: 'The map sentence explains that the reader can locate each place quickly.',
    evidenceReference: 'map-meaning',
    evidenceReferenceIds: [textFeatureHuntSentenceId('garden-grid', 2)],
    targetVocabulary: ['map', 'locate', 'quickly'],
    soundOutChunks: ['map', 'lo-cate'],
    tags: [...broadTags, 'map-contribution', 'feature-body-connection'],
    selectableSegments: gardenGridSentences.map((sentence) => ({ id: sentence.sentenceId, text: sentence.text })),
    correctSegmentIds: [textFeatureHuntSentenceId('garden-grid', 2)],
  }),
  tm({
    ...common,
    difficulty: 0,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.gardenGrid,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.buildingBlockB,
    questionIdentifier: textFeatureHuntQuestionId('building-block-b', 'tm-1'),
    prompt: 'Match each feature to what it does for the reader.',
    explanation: 'The features help the reader find the places and picture the plant.',
    evidenceReference: 'feature-job-match',
    evidenceReferenceIds: [
      TEXT_FEATURE_HUNT_FEATURE_IDS.gardenGrid.title,
      TEXT_FEATURE_HUNT_FEATURE_IDS.gardenGrid.map,
      TEXT_FEATURE_HUNT_FEATURE_IDS.gardenGrid.caption,
      TEXT_FEATURE_HUNT_FEATURE_IDS.gardenGrid.illustration,
    ],
    targetVocabulary: ['feature', 'meaning', 'picture'],
    soundOutChunks: ['fea-ture', 'mean-ing'],
    tags: [...broadTags, 'feature-selection-for-purpose', 'feature-body-connection'],
    rows: [
      {
        id: 'row-title',
        prompt: 'Title',
        correctChoiceId: 'option-title',
        options: [
          { id: 'option-title', text: 'Gives a clue about the whole text' },
          { id: 'option-map', text: 'Shows where places are' },
          { id: 'option-caption', text: 'Points readers to the sunny corner' },
          { id: 'option-illustration', text: 'Helps readers picture the bean plant' },
        ],
      },
      {
        id: 'row-map',
        prompt: 'Map',
        correctChoiceId: 'option-map-2',
        options: [
          { id: 'option-title-2', text: 'Gives a clue about the whole text' },
          { id: 'option-map-2', text: 'Shows where places are' },
          { id: 'option-caption-2', text: 'Points readers to the sunny corner' },
          { id: 'option-illustration-2', text: 'Helps readers picture the bean plant' },
        ],
      },
      {
        id: 'row-caption',
        prompt: 'Caption',
        correctChoiceId: 'option-caption-3',
        options: [
          { id: 'option-title-3', text: 'Gives a clue about the whole text' },
          { id: 'option-map-3', text: 'Shows where places are' },
          { id: 'option-caption-3', text: 'Points readers to the sunny corner' },
          { id: 'option-illustration-3', text: 'Helps readers picture the bean plant' },
        ],
      },
      {
        id: 'row-illustration',
        prompt: 'Illustration',
        correctChoiceId: 'option-illustration-4',
        options: [
          { id: 'option-title-4', text: 'Gives a clue about the whole text' },
          { id: 'option-map-4', text: 'Shows where places are' },
          { id: 'option-caption-4', text: 'Points readers to the sunny corner' },
          { id: 'option-illustration-4', text: 'Helps readers picture the bean plant' },
        ],
      },
    ],
  }),
]
