import type { ReadingQuestion } from '../../../../types'
import { textFeatureHuntPassages } from './passages'
import {
  TEXT_FEATURE_HUNT_CONTENT_VERSION,
  TEXT_FEATURE_HUNT_FEATURE_IDS,
  TEXT_FEATURE_HUNT_LESSON_IDS,
  TEXT_FEATURE_HUNT_PASSAGE_IDS,
  TEXT_FEATURE_HUNT_PASSAGE_KEYS,
  TEXT_FEATURE_HUNT_QUESTION_TAGS,
  textFeatureHuntQuestionId,
  textFeatureHuntSentenceId,
} from './ids'
import {
  createEvidencePairQuestion,
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from './questionFactories'

const [, , , , moonNotes, recycleSort, compostChange] = textFeatureHuntPassages
const moonNotesSentences = moonNotes.sentences ?? []
const recycleSortSentences = recycleSort.sentences ?? []
const compostChangeSentences = compostChange.sentences ?? []

const common = {
  benchmarkReference: 'ELA.2.R.2.1' as const,
  skillIdentifier: 'g2-information-detectives-reading' as const,
  reportingCategory: 'Reading Informational Text' as const,
  genre: 'informational' as const,
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2' as const,
  contentVersion: TEXT_FEATURE_HUNT_CONTENT_VERSION,
  reviewStatus: 'DRAFT' as const,
}

const mc = (spec: Parameters<typeof createMultipleChoiceQuestion>[0]) => createMultipleChoiceQuestion(spec)
const ms = (spec: Parameters<typeof createMultiselectQuestion>[0]) => createMultiselectQuestion(spec)
const ht = (spec: Parameters<typeof createHotTextQuestion>[0]) => createHotTextQuestion(spec)
const tm = (spec: Parameters<typeof createTableMatchQuestion>[0]) => createTableMatchQuestion(spec)
const ep = (spec: Parameters<typeof createEvidencePairQuestion>[0]) => createEvidencePairQuestion(spec)

const broadTags = [...TEXT_FEATURE_HUNT_QUESTION_TAGS.broad]

export const textFeatureHuntCheckpointQuestions: ReadingQuestion[] = [
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.moonNotes,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointA,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-a', 'mc-1'),
    prompt: 'What does the title Moon Notes help the reader understand?',
    explanation: 'The title previews that the passage is about moon notes and a class log of moon shapes.',
    evidenceReference: 'title-contribution',
    evidenceReferenceIds: [TEXT_FEATURE_HUNT_FEATURE_IDS.moonNotes.title],
    targetVocabulary: ['title', 'moon', 'notes'],
    soundOutChunks: ['ti-tle', 'moon'],
    tags: [...broadTags, 'title-contribution'],
    choices: [
      { id: 'choice-a', text: 'The text is about a garden map.' },
      { id: 'choice-b', text: 'The text is about moon shapes in a class log.' },
      { id: 'choice-c', text: 'The text is about recycling bins.' },
      { id: 'choice-d', text: 'The text is about a trail sign.' },
    ],
    correctChoiceIds: ['choice-b'],
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.moonNotes,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointA,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-a', 'mc-2'),
    prompt: 'What does the heading Night by Night tell the reader?',
    explanation: 'The heading names the section and tells the reader that the class is looking at the moon over several nights.',
    evidenceReference: 'heading-contribution',
    evidenceReferenceIds: [TEXT_FEATURE_HUNT_FEATURE_IDS.moonNotes.headingGraph],
    targetVocabulary: ['heading', 'night', 'moon'],
    soundOutChunks: ['head-ing', 'night'],
    tags: [...broadTags, 'heading-contribution'],
    choices: [
      { id: 'choice-a', text: 'This section is about counting birds.' },
      { id: 'choice-b', text: 'This section is about a map of a trail.' },
      { id: 'choice-c', text: 'This section is about the moon over several nights.' },
      { id: 'choice-d', text: 'This section is about compost changes.' },
    ],
    correctChoiceIds: ['choice-c'],
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.moonNotes,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointA,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-a', 'mc-3'),
    prompt: 'What does the graph help the reader do?',
    explanation: 'The graph organizes the moon shapes so the reader can compare the changes across the week.',
    evidenceReference: 'graph-contribution',
    evidenceReferenceIds: [TEXT_FEATURE_HUNT_FEATURE_IDS.moonNotes.graph],
    targetVocabulary: ['graph', 'compare', 'changes'],
    soundOutChunks: ['graph', 'com-pare'],
    tags: [...broadTags, 'graph-contribution', 'feature-selection-for-purpose'],
    choices: [
      { id: 'choice-a', text: 'Compare the moon changes across the week.' },
      { id: 'choice-b', text: 'Learn the meaning of route.' },
      { id: 'choice-c', text: 'Find the bean bed on a map.' },
      { id: 'choice-d', text: 'Picture the recycling gloves.' },
    ],
    correctChoiceIds: ['choice-a'],
  }),
  ms({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.moonNotes,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointA,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-a', 'ms-1'),
    prompt: 'Choose the two details that help explain the graph.',
    explanation: 'The graph sentence and the caption sentence tell readers how to understand the moon changes.',
    evidenceReference: 'feature-body-connection',
    evidenceReferenceIds: [
      textFeatureHuntSentenceId(TEXT_FEATURE_HUNT_PASSAGE_KEYS.moonNotes, 2),
      textFeatureHuntSentenceId(TEXT_FEATURE_HUNT_PASSAGE_KEYS.moonNotes, 3),
    ],
    targetVocabulary: ['graph', 'caption', 'moon'],
    soundOutChunks: ['graph', 'cap-tion'],
    tags: [...broadTags, 'graph-contribution', 'caption-contribution'],
    choices: [
      { id: 'choice-a', text: moonNotesSentences[1]!.text },
      { id: 'choice-b', text: moonNotesSentences[2]!.text },
      { id: 'choice-c', text: moonNotesSentences[0]!.text },
      { id: 'choice-d', text: moonNotesSentences[3]!.text },
    ],
    correctChoiceIds: ['choice-a', 'choice-b'],
  }),
  ht({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.moonNotes,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointA,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-a', 'ht-1'),
    prompt: 'Select the sentence that tells what the glossary means.',
    explanation: 'The glossary sentence explains that observe means to watch carefully over time.',
    evidenceReference: 'glossary-contribution',
    evidenceReferenceIds: [textFeatureHuntSentenceId(TEXT_FEATURE_HUNT_PASSAGE_KEYS.moonNotes, 4)],
    targetVocabulary: ['glossary', 'observe', 'watch'],
    soundOutChunks: ['glos-sar-y', 'ob-serve'],
    tags: [...broadTags, 'glossary-contribution', 'feature-body-connection'],
    selectableSegments: moonNotesSentences.map((sentence) => ({ id: sentence.sentenceId, text: sentence.text })),
    correctSegmentIds: [textFeatureHuntSentenceId(TEXT_FEATURE_HUNT_PASSAGE_KEYS.moonNotes, 4)],
  }),
  tm({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.moonNotes,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointA,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-a', 'tm-1'),
    prompt: 'Match each feature to what it does for the reader.',
    explanation: 'The features work together to help the reader understand the moon notes and the graph.',
    evidenceReference: 'feature-job-match',
    evidenceReferenceIds: [
      TEXT_FEATURE_HUNT_FEATURE_IDS.moonNotes.title,
      TEXT_FEATURE_HUNT_FEATURE_IDS.moonNotes.graph,
      TEXT_FEATURE_HUNT_FEATURE_IDS.moonNotes.caption,
      TEXT_FEATURE_HUNT_FEATURE_IDS.moonNotes.glossary,
    ],
    targetVocabulary: ['feature', 'meaning', 'moon'],
    soundOutChunks: ['fea-ture', 'mean-ing'],
    tags: [...broadTags, 'feature-selection-for-purpose', 'feature-body-connection'],
    rows: [
      {
        id: 'row-title',
        prompt: 'Title',
        correctChoiceId: 'option-title',
        options: [
          { id: 'option-title', text: 'Gives a clue about the whole text' },
          { id: 'option-graph', text: 'Compares moon shapes' },
          { id: 'option-caption', text: 'Explains the tallest bar' },
          { id: 'option-glossary', text: 'Defines a special word' },
        ],
      },
      {
        id: 'row-graph',
        prompt: 'Graph',
        correctChoiceId: 'option-graph-2',
        options: [
          { id: 'option-title-2', text: 'Gives a clue about the whole text' },
          { id: 'option-graph-2', text: 'Compares moon shapes' },
          { id: 'option-caption-2', text: 'Explains the tallest bar' },
          { id: 'option-glossary-2', text: 'Defines a special word' },
        ],
      },
      {
        id: 'row-caption',
        prompt: 'Caption',
        correctChoiceId: 'option-caption-3',
        options: [
          { id: 'option-title-3', text: 'Gives a clue about the whole text' },
          { id: 'option-graph-3', text: 'Compares moon shapes' },
          { id: 'option-caption-3', text: 'Explains the tallest bar' },
          { id: 'option-glossary-3', text: 'Defines a special word' },
        ],
      },
      {
        id: 'row-glossary',
        prompt: 'Glossary',
        correctChoiceId: 'option-glossary-4',
        options: [
          { id: 'option-title-4', text: 'Gives a clue about the whole text' },
          { id: 'option-graph-4', text: 'Compares moon shapes' },
          { id: 'option-caption-4', text: 'Explains the tallest bar' },
          { id: 'option-glossary-4', text: 'Defines a special word' },
        ],
      },
    ],
  }),
  ep({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.moonNotes,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointA,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-a', 'ep-1'),
    prompt: 'How does the graph help the reader understand the moon notes?',
    explanation: 'The graph shows which moon shape the class saw each night, and that helps the reader compare the changes across the week.',
    evidenceReference: 'graph-support',
    evidenceReferenceIds: [
      TEXT_FEATURE_HUNT_FEATURE_IDS.moonNotes.graph,
      textFeatureHuntSentenceId(TEXT_FEATURE_HUNT_PASSAGE_KEYS.moonNotes, 2),
    ],
    targetVocabulary: ['graph', 'compare', 'week'],
    soundOutChunks: ['graph', 'com-pare'],
    tags: [...broadTags, 'graph-contribution', 'feature-body-connection'],
    partAPrompt: 'How does the graph help the reader understand the moon notes?',
    partAChoices: [
      { id: 'part-a-1', text: 'It shows which moon shape the class saw each night.' },
      { id: 'part-a-2', text: 'It tells how to locate a bean bed.' },
      { id: 'part-a-3', text: 'It explains the meaning of route.' },
    ],
    partACorrectChoiceId: 'part-a-1',
    partBPrompt: 'Which choice best supports that answer?',
    partBChoices: [
      { id: 'part-b-1', text: 'The graph shows which moon shape the class saw each night.' },
      { id: 'part-b-2', text: 'The glossary says observe means to watch carefully over time.' },
      { id: 'part-b-3', text: 'The caption tells readers that the tallest bar names the shape seen most often.' },
    ],
    partBCorrectChoiceId: 'part-b-1',
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.recycleSort,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointB,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-b', 'mc-1'),
    prompt: 'What does the title Recycling Sort help the reader understand?',
    explanation: 'The title previews that the passage is about sorting items for recycling.',
    evidenceReference: 'title-contribution',
    evidenceReferenceIds: [TEXT_FEATURE_HUNT_FEATURE_IDS.recycleSort.title],
    targetVocabulary: ['title', 'recycling', 'sort'],
    soundOutChunks: ['ti-tle', 'sort'],
    tags: [...broadTags, 'title-contribution'],
    choices: [
      { id: 'choice-a', text: 'The text is about birds at a feeder.' },
      { id: 'choice-b', text: 'The text is about moon notes.' },
      { id: 'choice-c', text: 'The text is about a trail map.' },
      { id: 'choice-d', text: 'The text is about sorting items for recycling.' },
    ],
    correctChoiceIds: ['choice-d'],
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.recycleSort,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointB,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-b', 'mc-2'),
    prompt: 'What does the heading Counting the Bins tell the reader?',
    explanation: 'The heading names the section and tells the reader this part is about counting how full each bin is.',
    evidenceReference: 'heading-contribution',
    evidenceReferenceIds: [TEXT_FEATURE_HUNT_FEATURE_IDS.recycleSort.headingGraph],
    targetVocabulary: ['heading', 'bins', 'counting'],
    soundOutChunks: ['head-ing', 'bins'],
    tags: [...broadTags, 'heading-contribution'],
    choices: [
      { id: 'choice-a', text: 'This section is about the compost bin.' },
      { id: 'choice-b', text: 'This section is about counting the bins.' },
      { id: 'choice-c', text: 'This section is about a weather graph.' },
      { id: 'choice-d', text: 'This section is about the trail sign.' },
    ],
    correctChoiceIds: ['choice-b'],
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.recycleSort,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointB,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-b', 'mc-3'),
    prompt: 'Which feature helps readers picture the sorting station?',
    explanation: 'The illustration labels the bins, arrows, and gloves so readers can picture the station.',
    evidenceReference: 'illustration-contribution',
    evidenceReferenceIds: [TEXT_FEATURE_HUNT_FEATURE_IDS.recycleSort.illustration],
    targetVocabulary: ['illustration', 'picture', 'station'],
    soundOutChunks: ['il-lus-tray-shun', 'pic-ture'],
    tags: [...broadTags, 'illustration-contribution', 'feature-selection-for-purpose'],
    choices: [
      { id: 'choice-a', text: 'The title' },
      { id: 'choice-b', text: 'The caption' },
      { id: 'choice-c', text: 'The graph' },
      { id: 'choice-d', text: 'The illustration' },
    ],
    correctChoiceIds: ['choice-d'],
  }),
  ms({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.recycleSort,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointB,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-b', 'ms-1'),
    prompt: 'Choose the two details that help the reader compare the recycling bins.',
    explanation: 'The graph sentence and the caption sentence help the reader compare which bin filled fastest.',
    evidenceReference: 'feature-body-connection',
    evidenceReferenceIds: [
      textFeatureHuntSentenceId(TEXT_FEATURE_HUNT_PASSAGE_KEYS.recycleSort, 2),
      textFeatureHuntSentenceId(TEXT_FEATURE_HUNT_PASSAGE_KEYS.recycleSort, 3),
    ],
    targetVocabulary: ['graph', 'caption', 'compare'],
    soundOutChunks: ['graph', 'cap-tion'],
    tags: [...broadTags, 'graph-contribution', 'caption-contribution'],
    choices: [
      { id: 'choice-a', text: recycleSortSentences[1]!.text },
      { id: 'choice-b', text: recycleSortSentences[2]!.text },
      { id: 'choice-c', text: recycleSortSentences[0]!.text },
      { id: 'choice-d', text: recycleSortSentences[3]!.text },
    ],
    correctChoiceIds: ['choice-a', 'choice-b'],
  }),
  ht({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.recycleSort,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointB,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-b', 'ht-1'),
    prompt: 'Select the sentence that tells what the illustration shows.',
    explanation: 'The illustration sentence labels the bin lids, arrows, and gloves to show how the class sorts each item.',
    evidenceReference: 'illustration-contribution',
    evidenceReferenceIds: [textFeatureHuntSentenceId(TEXT_FEATURE_HUNT_PASSAGE_KEYS.recycleSort, 4)],
    targetVocabulary: ['illustration', 'labels', 'sorts'],
    soundOutChunks: ['il-lus-tray-shun', 'la-bels'],
    tags: [...broadTags, 'illustration-contribution', 'feature-body-connection'],
    selectableSegments: recycleSortSentences.map((sentence) => ({ id: sentence.sentenceId, text: sentence.text })),
    correctSegmentIds: [textFeatureHuntSentenceId(TEXT_FEATURE_HUNT_PASSAGE_KEYS.recycleSort, 4)],
  }),
  tm({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.recycleSort,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointB,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-b', 'tm-1'),
    prompt: 'Match each feature to what it does for the reader.',
    explanation: 'The features work together to help the reader understand the recycling survey and the sorting station.',
    evidenceReference: 'feature-job-match',
    evidenceReferenceIds: [
      TEXT_FEATURE_HUNT_FEATURE_IDS.recycleSort.title,
      TEXT_FEATURE_HUNT_FEATURE_IDS.recycleSort.graph,
      TEXT_FEATURE_HUNT_FEATURE_IDS.recycleSort.caption,
      TEXT_FEATURE_HUNT_FEATURE_IDS.recycleSort.illustration,
    ],
    targetVocabulary: ['feature', 'meaning', 'recycling'],
    soundOutChunks: ['fea-ture', 'mean-ing'],
    tags: [...broadTags, 'feature-selection-for-purpose', 'feature-body-connection'],
    rows: [
      {
        id: 'row-title',
        prompt: 'Title',
        correctChoiceId: 'option-title',
        options: [
          { id: 'option-title', text: 'Gives a clue about the whole text' },
          { id: 'option-graph', text: 'Compares the bin counts' },
          { id: 'option-caption', text: 'Explains the tallest bar' },
          { id: 'option-illustration', text: 'Shows the sorting station' },
        ],
      },
      {
        id: 'row-graph',
        prompt: 'Graph',
        correctChoiceId: 'option-graph-2',
        options: [
          { id: 'option-title-2', text: 'Gives a clue about the whole text' },
          { id: 'option-graph-2', text: 'Compares the bin counts' },
          { id: 'option-caption-2', text: 'Explains the tallest bar' },
          { id: 'option-illustration-2', text: 'Shows the sorting station' },
        ],
      },
      {
        id: 'row-caption',
        prompt: 'Caption',
        correctChoiceId: 'option-caption-3',
        options: [
          { id: 'option-title-3', text: 'Gives a clue about the whole text' },
          { id: 'option-graph-3', text: 'Compares the bin counts' },
          { id: 'option-caption-3', text: 'Explains the tallest bar' },
          { id: 'option-illustration-3', text: 'Shows the sorting station' },
        ],
      },
      {
        id: 'row-illustration',
        prompt: 'Illustration',
        correctChoiceId: 'option-illustration-4',
        options: [
          { id: 'option-title-4', text: 'Gives a clue about the whole text' },
          { id: 'option-graph-4', text: 'Compares the bin counts' },
          { id: 'option-caption-4', text: 'Explains the tallest bar' },
          { id: 'option-illustration-4', text: 'Shows the sorting station' },
        ],
      },
    ],
  }),
  ep({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.recycleSort,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointB,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-b', 'ep-1'),
    prompt: 'How does the illustration help the reader understand the sorting station?',
    explanation: 'The illustration shows the bin lids, sorting arrows, and gloves, so the reader can picture how the station works.',
    evidenceReference: 'illustration-support',
    evidenceReferenceIds: [
      TEXT_FEATURE_HUNT_FEATURE_IDS.recycleSort.illustration,
      textFeatureHuntSentenceId(TEXT_FEATURE_HUNT_PASSAGE_KEYS.recycleSort, 4),
    ],
    targetVocabulary: ['illustration', 'picture', 'station'],
    soundOutChunks: ['il-lus-tray-shun', 'sta-tion'],
    tags: [...broadTags, 'illustration-contribution', 'feature-body-connection'],
    partAPrompt: 'How does the illustration help the reader understand the sorting station?',
    partAChoices: [
      { id: 'part-a-1', text: 'It shows how the class sorts each item.' },
      { id: 'part-a-2', text: 'It tells where the bean bed is.' },
      { id: 'part-a-3', text: 'It explains the meaning of observe.' },
    ],
    partACorrectChoiceId: 'part-a-1',
    partBPrompt: 'Which choice best supports that answer?',
    partBChoices: [
      { id: 'part-b-1', text: 'An illustration labels the bin lids, the sorting arrows, and the helper gloves.' },
      { id: 'part-b-2', text: 'The title says Recycling Sort.' },
      { id: 'part-b-3', text: 'The graph shows which bin filled fastest.' },
    ],
    partBCorrectChoiceId: 'part-b-1',
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.compostChange,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointC,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-c', 'mc-1'),
    prompt: 'What does the title Compost Change help the reader understand?',
    explanation: 'The title previews that the passage is about how compost changes over time.',
    evidenceReference: 'title-contribution',
    evidenceReferenceIds: [TEXT_FEATURE_HUNT_FEATURE_IDS.compostChange.title],
    targetVocabulary: ['title', 'compost', 'change'],
    soundOutChunks: ['ti-tle', 'compost'],
    tags: [...broadTags, 'title-contribution'],
    choices: [
      { id: 'choice-a', text: 'The text is about a trail map.' },
      { id: 'choice-b', text: 'The text is about moon shapes.' },
      { id: 'choice-c', text: 'The text is about how compost changes over time.' },
      { id: 'choice-d', text: 'The text is about bird visitors.' },
    ],
    correctChoiceIds: ['choice-c'],
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.compostChange,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointC,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-c', 'mc-2'),
    prompt: 'What does the heading Where It Stays tell the reader?',
    explanation: 'The heading names the section and tells the reader this part is about where the compost bin stays.',
    evidenceReference: 'heading-contribution',
    evidenceReferenceIds: [TEXT_FEATURE_HUNT_FEATURE_IDS.compostChange.headingMap],
    targetVocabulary: ['heading', 'stays', 'bin'],
    soundOutChunks: ['head-ing', 'stays'],
    tags: [...broadTags, 'heading-contribution'],
    choices: [
      { id: 'choice-a', text: 'This section is about where the compost bin stays.' },
      { id: 'choice-b', text: 'This section is about how the moon changes.' },
      { id: 'choice-c', text: 'This section is about counting recycling bins.' },
      { id: 'choice-d', text: 'This section is about bird visitors.' },
    ],
    correctChoiceIds: ['choice-a'],
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.compostChange,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointC,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-c', 'mc-3'),
    prompt: 'Which feature tells the reader where the compost bin sits?',
    explanation: 'The map shows where the compost bin sits beside the herb bed and hose hook.',
    evidenceReference: 'map-contribution',
    evidenceReferenceIds: [TEXT_FEATURE_HUNT_FEATURE_IDS.compostChange.map],
    targetVocabulary: ['map', 'compost', 'where'],
    soundOutChunks: ['map', 'where'],
    tags: [...broadTags, 'map-contribution', 'feature-selection-for-purpose'],
    choices: [
      { id: 'choice-a', text: 'The glossary' },
      { id: 'choice-b', text: 'The caption' },
      { id: 'choice-c', text: 'The title' },
      { id: 'choice-d', text: 'The map' },
    ],
    correctChoiceIds: ['choice-d'],
  }),
  ms({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.compostChange,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointC,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-c', 'ms-1'),
    prompt: 'Choose the two details that help the reader understand where the compost bin is.',
    explanation: 'The map and the caption both tell readers where the compost bin sits and why that spot matters.',
    evidenceReference: 'feature-body-connection',
    evidenceReferenceIds: [
      textFeatureHuntSentenceId(TEXT_FEATURE_HUNT_PASSAGE_KEYS.compostChange, 2),
      textFeatureHuntSentenceId(TEXT_FEATURE_HUNT_PASSAGE_KEYS.compostChange, 3),
    ],
    targetVocabulary: ['map', 'caption', 'where'],
    soundOutChunks: ['map', 'cap-tion'],
    tags: [...broadTags, 'map-contribution', 'caption-contribution'],
    choices: [
      { id: 'choice-a', text: compostChangeSentences[1]!.text },
      { id: 'choice-b', text: compostChangeSentences[2]!.text },
      { id: 'choice-c', text: compostChangeSentences[0]!.text },
      { id: 'choice-d', text: compostChangeSentences[3]!.text },
    ],
    correctChoiceIds: ['choice-a', 'choice-b'],
  }),
  ht({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.compostChange,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointC,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-c', 'ht-1'),
    prompt: 'Select the sentence that tells what the glossary means.',
    explanation: 'The glossary sentence explains that compost means plant and food scraps that break down slowly into rich soil.',
    evidenceReference: 'glossary-contribution',
    evidenceReferenceIds: [textFeatureHuntSentenceId(TEXT_FEATURE_HUNT_PASSAGE_KEYS.compostChange, 4)],
    targetVocabulary: ['glossary', 'compost', 'soil'],
    soundOutChunks: ['glos-sar-y', 'compost'],
    tags: [...broadTags, 'glossary-contribution', 'feature-body-connection'],
    selectableSegments: compostChangeSentences.map((sentence) => ({ id: sentence.sentenceId, text: sentence.text })),
    correctSegmentIds: [textFeatureHuntSentenceId(TEXT_FEATURE_HUNT_PASSAGE_KEYS.compostChange, 4)],
  }),
  tm({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.compostChange,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointC,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-c', 'tm-1'),
    prompt: 'Match each feature to what it does for the reader.',
    explanation: 'The features help the reader understand where the compost bin is and what compost means.',
    evidenceReference: 'feature-job-match',
    evidenceReferenceIds: [
      TEXT_FEATURE_HUNT_FEATURE_IDS.compostChange.title,
      TEXT_FEATURE_HUNT_FEATURE_IDS.compostChange.map,
      TEXT_FEATURE_HUNT_FEATURE_IDS.compostChange.caption,
      TEXT_FEATURE_HUNT_FEATURE_IDS.compostChange.glossary,
    ],
    targetVocabulary: ['feature', 'meaning', 'compost'],
    soundOutChunks: ['fea-ture', 'mean-ing'],
    tags: [...broadTags, 'feature-selection-for-purpose', 'feature-body-connection'],
    rows: [
      {
        id: 'row-title',
        prompt: 'Title',
        correctChoiceId: 'option-title',
        options: [
          { id: 'option-title', text: 'Gives a clue about the whole text' },
          { id: 'option-map', text: 'Shows where the compost bin sits' },
          { id: 'option-caption', text: 'Explains the cool shaded spot' },
          { id: 'option-glossary', text: 'Defines compost' },
        ],
      },
      {
        id: 'row-map',
        prompt: 'Map',
        correctChoiceId: 'option-map-2',
        options: [
          { id: 'option-title-2', text: 'Gives a clue about the whole text' },
          { id: 'option-map-2', text: 'Shows where the compost bin sits' },
          { id: 'option-caption-2', text: 'Explains the cool shaded spot' },
          { id: 'option-glossary-2', text: 'Defines compost' },
        ],
      },
      {
        id: 'row-caption',
        prompt: 'Caption',
        correctChoiceId: 'option-caption-3',
        options: [
          { id: 'option-title-3', text: 'Gives a clue about the whole text' },
          { id: 'option-map-3', text: 'Shows where the compost bin sits' },
          { id: 'option-caption-3', text: 'Explains the cool shaded spot' },
          { id: 'option-glossary-3', text: 'Defines compost' },
        ],
      },
      {
        id: 'row-glossary',
        prompt: 'Glossary',
        correctChoiceId: 'option-glossary-4',
        options: [
          { id: 'option-title-4', text: 'Gives a clue about the whole text' },
          { id: 'option-map-4', text: 'Shows where the compost bin sits' },
          { id: 'option-caption-4', text: 'Explains the cool shaded spot' },
          { id: 'option-glossary-4', text: 'Defines compost' },
        ],
      },
    ],
  }),
  ep({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.compostChange,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.checkpointC,
    questionIdentifier: textFeatureHuntQuestionId('checkpoint-c', 'ep-1'),
    prompt: 'How does the map help the reader understand compost corner?',
    explanation: 'The map shows where the compost bin sits beside the herb bed and hose hook, so the reader can picture the place quickly.',
    evidenceReference: 'map-support',
    evidenceReferenceIds: [
      TEXT_FEATURE_HUNT_FEATURE_IDS.compostChange.map,
      textFeatureHuntSentenceId(TEXT_FEATURE_HUNT_PASSAGE_KEYS.compostChange, 2),
    ],
    targetVocabulary: ['map', 'compost', 'corner'],
    soundOutChunks: ['map', 'cor-ner'],
    tags: [...broadTags, 'map-contribution', 'feature-body-connection'],
    partAPrompt: 'How does the map help the reader understand compost corner?',
    partAChoices: [
      { id: 'part-a-1', text: 'It shows where the compost bin sits.' },
      { id: 'part-a-2', text: 'It explains the meaning of observe.' },
      { id: 'part-a-3', text: 'It tells which moon shape is tallest.' },
    ],
    partACorrectChoiceId: 'part-a-1',
    partBPrompt: 'Which choice best supports that answer?',
    partBChoices: [
      { id: 'part-b-1', text: 'The map shows where the compost bin sits beside the herb bed and the hose hook.' },
      { id: 'part-b-2', text: 'The title says Compost Change.' },
      { id: 'part-b-3', text: 'The glossary defines compost as plant and food scraps that break down slowly into rich soil.' },
    ],
    partBCorrectChoiceId: 'part-b-1',
  }),
]
