import type { ReadingQuestion } from '../../../../types'
import { textFeatureHuntPassages } from './passages'
import {
  TEXT_FEATURE_HUNT_CONTENT_VERSION,
  TEXT_FEATURE_HUNT_FEATURE_IDS,
  TEXT_FEATURE_HUNT_LESSON_IDS,
  TEXT_FEATURE_HUNT_PASSAGE_IDS,
  TEXT_FEATURE_HUNT_QUESTION_TAGS,
  textFeatureHuntQuestionId,
  textFeatureHuntSentenceId,
} from './ids'
import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from './questionFactories'

const [, , rainGauge, trailMap] = textFeatureHuntPassages
const rainGaugeSentences = rainGauge.sentences ?? []
const trailMapSentences = trailMap.sentences ?? []

const common = {
  benchmarkReference: 'ELA.2.R.2.1' as const,
  skillIdentifier: 'g2-information-detectives-reading' as const,
  reportingCategory: 'Reading Informational Text' as const,
  genre: 'informational' as const,
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2' as const,
  contentVersion: TEXT_FEATURE_HUNT_CONTENT_VERSION,
  reviewStatus: 'DRAFT' as const,
}

const mc = (spec: Parameters<typeof createMultipleChoiceQuestion>[0]) => createMultipleChoiceQuestion(spec)
const ms = (spec: Parameters<typeof createMultiselectQuestion>[0]) => createMultiselectQuestion(spec)
const ht = (spec: Parameters<typeof createHotTextQuestion>[0]) => createHotTextQuestion(spec)
const tm = (spec: Parameters<typeof createTableMatchQuestion>[0]) => createTableMatchQuestion(spec)

const broadTags = [...TEXT_FEATURE_HUNT_QUESTION_TAGS.broad]

export const textFeatureHuntGuidedQuestions: ReadingQuestion[] = [
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.rainGauge,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.guidedA,
    questionIdentifier: textFeatureHuntQuestionId('guided-a', 'mc-1'),
    prompt: 'What does the title Rain Gauge Notes help the reader understand?',
    explanation: 'The title previews that the passage is about notes from measuring rain after a storm.',
    evidenceReference: 'title-contribution',
    evidenceReferenceIds: [TEXT_FEATURE_HUNT_FEATURE_IDS.rainGauge.title],
    targetVocabulary: ['title', 'rain', 'notes'],
    soundOutChunks: ['ti-tle', 'rain'],
    tags: [...broadTags, 'title-contribution'],
    choices: [
      { id: 'choice-a', text: 'The text is about a moon map.' },
      { id: 'choice-b', text: 'The text is about a garden trail.' },
      { id: 'choice-c', text: 'The text is about recycling bins.' },
      { id: 'choice-d', text: 'The text is about rain notes from a storm.' },
    ],
    correctChoiceIds: ['choice-d'],
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.rainGauge,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.guidedA,
    questionIdentifier: textFeatureHuntQuestionId('guided-a', 'mc-2'),
    prompt: 'What does the heading Measuring the Storm tell the reader?',
    explanation: 'The heading names the section and tells the reader that this part is about measuring rainfall from the storm.',
    evidenceReference: 'heading-contribution',
    evidenceReferenceIds: [TEXT_FEATURE_HUNT_FEATURE_IDS.rainGauge.headingGraph],
    targetVocabulary: ['heading', 'storm', 'measuring'],
    soundOutChunks: ['head-ing', 'storm'],
    tags: [...broadTags, 'heading-contribution'],
    choices: [
      { id: 'choice-a', text: 'This section is about plants in a garden.' },
      { id: 'choice-b', text: 'This section is about measuring rain in the storm.' },
      { id: 'choice-c', text: 'This section is about a trail map.' },
      { id: 'choice-d', text: 'This section is about recycling bins.' },
    ],
    correctChoiceIds: ['choice-b'],
  }),
  ms({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.rainGauge,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.guidedA,
    questionIdentifier: textFeatureHuntQuestionId('guided-a', 'ms-1'),
    prompt: 'Choose the two features that help the reader compare rain amounts.',
    explanation: 'The graph organizes the amounts, and the caption explains what the bars mean.',
    evidenceReference: 'feature-meaning',
    evidenceReferenceIds: [
      TEXT_FEATURE_HUNT_FEATURE_IDS.rainGauge.graph,
      TEXT_FEATURE_HUNT_FEATURE_IDS.rainGauge.caption,
    ],
    targetVocabulary: ['graph', 'caption', 'compare'],
    soundOutChunks: ['graph', 'com-pare'],
    tags: [...broadTags, 'graph-contribution', 'caption-contribution'],
    choices: [
      { id: 'choice-a', text: 'The graph' },
      { id: 'choice-b', text: 'The caption' },
      { id: 'choice-c', text: 'The title' },
      { id: 'choice-d', text: 'The glossary' },
    ],
    correctChoiceIds: ['choice-a', 'choice-b'],
  }),
  ht({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.rainGauge,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.guidedA,
    questionIdentifier: textFeatureHuntQuestionId('guided-a', 'ht-1'),
    prompt: 'Select the sentence that tells what the caption explains.',
    explanation: 'The caption sentence tells readers that taller bars mean more rain on that day.',
    evidenceReference: 'caption-meaning',
    evidenceReferenceIds: [textFeatureHuntSentenceId('rain-gauge', 3)],
    targetVocabulary: ['caption', 'bars', 'rain'],
    soundOutChunks: ['cap-tion', 'bars'],
    tags: [...broadTags, 'caption-contribution', 'feature-body-connection'],
    selectableSegments: rainGaugeSentences.map((sentence) => ({ id: sentence.sentenceId, text: sentence.text })),
    correctSegmentIds: [textFeatureHuntSentenceId('rain-gauge', 3)],
  }),
  tm({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.rainGauge,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.guidedA,
    questionIdentifier: textFeatureHuntQuestionId('guided-a', 'tm-1'),
    prompt: 'Match each feature to what it does for the reader.',
    explanation: 'Each feature helps the reader understand the rain notes in a different way.',
    evidenceReference: 'feature-job-match',
    evidenceReferenceIds: [
      TEXT_FEATURE_HUNT_FEATURE_IDS.rainGauge.title,
      TEXT_FEATURE_HUNT_FEATURE_IDS.rainGauge.graph,
      TEXT_FEATURE_HUNT_FEATURE_IDS.rainGauge.caption,
      TEXT_FEATURE_HUNT_FEATURE_IDS.rainGauge.glossary,
    ],
    targetVocabulary: ['feature', 'meaning', 'rain'],
    soundOutChunks: ['fea-ture', 'mean-ing'],
    tags: [...broadTags, 'feature-selection-for-purpose', 'feature-body-connection'],
    rows: [
      {
        id: 'row-title',
        prompt: 'Title',
        correctChoiceId: 'option-title',
        options: [
          { id: 'option-title', text: 'Gives a clue about the whole text' },
          { id: 'option-graph', text: 'Compares rain amounts' },
          { id: 'option-caption', text: 'Explains the bars on the graph' },
          { id: 'option-glossary', text: 'Defines a special word' },
        ],
      },
      {
        id: 'row-graph',
        prompt: 'Graph',
        correctChoiceId: 'option-graph-2',
        options: [
          { id: 'option-title-2', text: 'Gives a clue about the whole text' },
          { id: 'option-graph-2', text: 'Compares rain amounts' },
          { id: 'option-caption-2', text: 'Explains the bars on the graph' },
          { id: 'option-glossary-2', text: 'Defines a special word' },
        ],
      },
      {
        id: 'row-caption',
        prompt: 'Caption',
        correctChoiceId: 'option-caption-3',
        options: [
          { id: 'option-title-3', text: 'Gives a clue about the whole text' },
          { id: 'option-graph-3', text: 'Compares rain amounts' },
          { id: 'option-caption-3', text: 'Explains the bars on the graph' },
          { id: 'option-glossary-3', text: 'Defines a special word' },
        ],
      },
      {
        id: 'row-glossary',
        prompt: 'Glossary',
        correctChoiceId: 'option-glossary-4',
        options: [
          { id: 'option-title-4', text: 'Gives a clue about the whole text' },
          { id: 'option-graph-4', text: 'Compares rain amounts' },
          { id: 'option-caption-4', text: 'Explains the bars on the graph' },
          { id: 'option-glossary-4', text: 'Defines a special word' },
        ],
      },
    ],
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.trailMap,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.guidedB,
    questionIdentifier: textFeatureHuntQuestionId('guided-b', 'mc-1'),
    prompt: 'What does the title Nature Center Trail help the reader understand?',
    explanation: 'The title previews that the passage is about a trail at a nature center.',
    evidenceReference: 'title-contribution',
    evidenceReferenceIds: [TEXT_FEATURE_HUNT_FEATURE_IDS.trailMap.title],
    targetVocabulary: ['title', 'trail', 'nature'],
    soundOutChunks: ['ti-tle', 'na-ture'],
    tags: [...broadTags, 'title-contribution'],
    choices: [
      { id: 'choice-a', text: 'The text is about bird feeder counts.' },
      { id: 'choice-b', text: 'The text is about a recycling survey.' },
      { id: 'choice-c', text: 'The text is about a nature center trail.' },
      { id: 'choice-d', text: 'The text is about moon shapes.' },
    ],
    correctChoiceIds: ['choice-c'],
  }),
  mc({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.trailMap,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.guidedB,
    questionIdentifier: textFeatureHuntQuestionId('guided-b', 'mc-2'),
    prompt: 'What does the heading Reading the Map tell the reader?',
    explanation: 'The heading names the section and tells the reader this part is about reading the map.',
    evidenceReference: 'heading-contribution',
    evidenceReferenceIds: [TEXT_FEATURE_HUNT_FEATURE_IDS.trailMap.headingMap],
    targetVocabulary: ['heading', 'map', 'reading'],
    soundOutChunks: ['head-ing', 'map'],
    tags: [...broadTags, 'heading-contribution'],
    choices: [
      { id: 'choice-a', text: 'This section is about the trail sign picture.' },
      { id: 'choice-b', text: 'This section is about lunch cleanup.' },
      { id: 'choice-c', text: 'This section is about counting moon shapes.' },
      { id: 'choice-d', text: 'This section is about reading the map.' },
    ],
    correctChoiceIds: ['choice-d'],
  }),
  ms({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.trailMap,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.guidedB,
    questionIdentifier: textFeatureHuntQuestionId('guided-b', 'ms-1'),
    prompt: 'Choose the two features that help the reader follow the trail.',
    explanation: 'The map shows the route, and the caption explains the dashed line that marks the route.',
    evidenceReference: 'feature-selection-for-purpose',
    evidenceReferenceIds: [
      TEXT_FEATURE_HUNT_FEATURE_IDS.trailMap.map,
      TEXT_FEATURE_HUNT_FEATURE_IDS.trailMap.caption,
    ],
    targetVocabulary: ['map', 'caption', 'route'],
    soundOutChunks: ['map', 'cap-tion'],
    tags: [...broadTags, 'map-contribution', 'caption-contribution'],
    choices: [
      { id: 'choice-a', text: 'The map' },
      { id: 'choice-b', text: 'The caption' },
      { id: 'choice-c', text: 'The title' },
      { id: 'choice-d', text: 'The illustration' },
    ],
    correctChoiceIds: ['choice-a', 'choice-b'],
  }),
  ht({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.trailMap,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.guidedB,
    questionIdentifier: textFeatureHuntQuestionId('guided-b', 'ht-1'),
    prompt: 'Select the sentence that tells what the glossary means.',
    explanation: 'The glossary sentence explains that route means a path that people follow.',
    evidenceReference: 'glossary-meaning',
    evidenceReferenceIds: [textFeatureHuntSentenceId('trail-map', 4)],
    targetVocabulary: ['glossary', 'route', 'path'],
    soundOutChunks: ['glos-sar-y', 'route'],
    tags: [...broadTags, 'glossary-contribution', 'feature-body-connection'],
    selectableSegments: trailMapSentences.map((sentence) => ({ id: sentence.sentenceId, text: sentence.text })),
    correctSegmentIds: [textFeatureHuntSentenceId('trail-map', 4)],
  }),
  tm({
    ...common,
    difficulty: 1,
    passageIdentifier: TEXT_FEATURE_HUNT_PASSAGE_IDS.trailMap,
    lessonIdentifier: TEXT_FEATURE_HUNT_LESSON_IDS.guidedB,
    questionIdentifier: textFeatureHuntQuestionId('guided-b', 'tm-1'),
    prompt: 'Match each feature to what it does for the reader.',
    explanation: 'The features help the reader understand the trail and the route.',
    evidenceReference: 'feature-job-match',
    evidenceReferenceIds: [
      TEXT_FEATURE_HUNT_FEATURE_IDS.trailMap.title,
      TEXT_FEATURE_HUNT_FEATURE_IDS.trailMap.map,
      TEXT_FEATURE_HUNT_FEATURE_IDS.trailMap.caption,
      TEXT_FEATURE_HUNT_FEATURE_IDS.trailMap.illustration,
    ],
    targetVocabulary: ['feature', 'meaning', 'route'],
    soundOutChunks: ['fea-ture', 'mean-ing'],
    tags: [...broadTags, 'feature-selection-for-purpose', 'feature-body-connection'],
    rows: [
      {
        id: 'row-title',
        prompt: 'Title',
        correctChoiceId: 'option-title',
        options: [
          { id: 'option-title', text: 'Gives a clue about the whole text' },
          { id: 'option-map', text: 'Shows where places are on the trail' },
          { id: 'option-caption', text: 'Explains the dashed line' },
          { id: 'option-illustration', text: 'Helps readers picture the trail sign' },
        ],
      },
      {
        id: 'row-map',
        prompt: 'Map',
        correctChoiceId: 'option-map-2',
        options: [
          { id: 'option-title-2', text: 'Gives a clue about the whole text' },
          { id: 'option-map-2', text: 'Shows where places are on the trail' },
          { id: 'option-caption-2', text: 'Explains the dashed line' },
          { id: 'option-illustration-2', text: 'Helps readers picture the trail sign' },
        ],
      },
      {
        id: 'row-caption',
        prompt: 'Caption',
        correctChoiceId: 'option-caption-3',
        options: [
          { id: 'option-title-3', text: 'Gives a clue about the whole text' },
          { id: 'option-map-3', text: 'Shows where places are on the trail' },
          { id: 'option-caption-3', text: 'Explains the dashed line' },
          { id: 'option-illustration-3', text: 'Helps readers picture the trail sign' },
        ],
      },
      {
        id: 'row-illustration',
        prompt: 'Illustration',
        correctChoiceId: 'option-illustration-4',
        options: [
          { id: 'option-title-4', text: 'Gives a clue about the whole text' },
          { id: 'option-map-4', text: 'Shows where places are on the trail' },
          { id: 'option-caption-4', text: 'Explains the dashed line' },
          { id: 'option-illustration-4', text: 'Helps readers picture the trail sign' },
        ],
      },
    ],
  }),
]
