import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from './questionFactories'
import {
  STORY_MAP_CHECKPOINT_TAGS,
  STORY_MAP_CONTENT_VERSION,
  STORY_MAP_LESSON_IDS,
  STORY_MAP_PASSAGE_IDS,
  storyMapQuestionId,
  storyMapSentenceId,
} from './ids'
import type { ReadingQuestion } from '../../../../types'

const STORY_MAP_QUESTION_TAGS = [...STORY_MAP_CHECKPOINT_TAGS]
const STORY_MAP_BASE = {
  gradeBand: 2 as const,
  benchmarkReference: 'ELA.2.R.1.1',
  skillIdentifier: 'g2-story-scouts-prose',
  reportingCategory: 'Reading Prose and Poetry',
  genre: 'literary',
  estimatedReadingLevel: 'Grade 2',
  reviewStatus: 'DRAFT' as const,
  contentVersion: STORY_MAP_CONTENT_VERSION,
  prerequisiteSkillIdentifiers: [] as string[],
  targetVocabulary: [] as string[],
  soundOutChunks: [] as string[],
  tags: STORY_MAP_QUESTION_TAGS,
}

export const storyMapGuidedQuestions: ReadingQuestion[] = [
  createMultipleChoiceQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.trailCleanup,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedC,
    activityIdentifier: 'activity-story-map-guided-c',
    questionIdentifier: storyMapQuestionId('guided-c', 'q1'),
    prompt: 'Where does this story happen?',
    explanation: 'The story happens on the nature trail.',
    evidenceReference: 'setting-clue',
    evidenceReferenceIds: [storyMapSentenceId('trail-cleanup', 1)],
    targetVocabulary: ['nature trail'],
    soundOutChunks: ['trail'],
    choices: [
      { id: 'a', text: 'on the nature trail' },
      { id: 'b', text: 'in the library' },
      { id: 'c', text: 'at the bird box' },
      { id: 'd', text: 'inside the classroom' },
    ],
    correctChoiceIds: ['a'],
  }),
  createMultipleChoiceQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.trailCleanup,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedC,
    activityIdentifier: 'activity-story-map-guided-c',
    questionIdentifier: storyMapQuestionId('guided-c', 'q2'),
    prompt: 'What is the main problem in this story?',
    explanation: 'Leaves and wrappers cover the trail.',
    evidenceReference: 'problem-clue',
    evidenceReferenceIds: [storyMapSentenceId('trail-cleanup', 2)],
    targetVocabulary: ['wrappers', 'sign'],
    soundOutChunks: ['wrap', 'pers'],
    choices: [
      { id: 'a', text: 'Leaves and wrappers cover the trail.' },
      { id: 'b', text: 'The bridge model falls apart.' },
      { id: 'c', text: 'The bird box is loose.' },
      { id: 'd', text: 'The library shelf is neat.' },
    ],
    correctChoiceIds: ['a'],
  }),
  createMultiselectQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.trailCleanup,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedC,
    activityIdentifier: 'activity-story-map-guided-c',
    questionIdentifier: storyMapQuestionId('guided-c', 'q3'),
    prompt: 'Which details help you know where and when the story happens?',
    explanation: 'Those details show the place and the time.',
    evidenceReference: 'setting-clue',
    evidenceReferenceIds: [
      storyMapSentenceId('trail-cleanup', 1),
      storyMapSentenceId('trail-cleanup', 5),
    ],
    targetVocabulary: ['Saturday', 'trail'],
    soundOutChunks: ['Sat', 'ur', 'day'],
    choices: [
      { id: 'a', text: 'Saturday morning' },
      { id: 'b', text: 'the nature trail' },
      { id: 'c', text: 'teacher help' },
      { id: 'd', text: 'science fair' },
    ],
    correctChoiceIds: ['a', 'b'],
  }),
  createHotTextQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.trailCleanup,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedC,
    activityIdentifier: 'activity-story-map-guided-c',
    questionIdentifier: storyMapQuestionId('guided-c', 'q4'),
    prompt: 'Which sentence shows how the characters solve the problem?',
    explanation: 'The third sentence shows the cleanup work.',
    evidenceReference: 'resolution-clue',
    evidenceReferenceIds: [storyMapSentenceId('trail-cleanup', 3)],
    targetVocabulary: ['cleaned', 'carefully'],
    soundOutChunks: ['clean', 'ed'],
    selectableSegments: [
      {
        id: storyMapSentenceId('trail-cleanup', 1),
        text: 'On Saturday morning, Nia and Ben walked the nature trail after a windy night.',
      },
      {
        id: storyMapSentenceId('trail-cleanup', 2),
        text: 'Leaves covered the small sign, and wrappers hid near the bench.',
      },
      {
        id: storyMapSentenceId('trail-cleanup', 3),
        text: 'Nia picked up the trash while Ben cleaned the sign carefully with a cloth.',
      },
      {
        id: storyMapSentenceId('trail-cleanup', 4),
        text: 'When they finished, the trail felt calm again, and the hikers smiled as they passed.',
      },
      {
        id: storyMapSentenceId('trail-cleanup', 5),
        text: 'The pair left the bench area tidy for the next group of walkers that afternoon.',
      },
    ],
    correctSegmentIds: [storyMapSentenceId('trail-cleanup', 3)],
  }),
  createTableMatchQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.trailCleanup,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedC,
    activityIdentifier: 'activity-story-map-guided-c',
    questionIdentifier: storyMapQuestionId('guided-c', 'q5'),
    prompt: 'Match each story part to the best detail.',
    explanation: 'The details help us follow the beginning, problem, and end.',
    evidenceReference: 'story-structure',
    evidenceReferenceIds: [
      storyMapSentenceId('trail-cleanup', 1),
      storyMapSentenceId('trail-cleanup', 3),
      storyMapSentenceId('trail-cleanup', 4),
    ],
    targetVocabulary: ['beginning', 'problem', 'end'],
    soundOutChunks: ['be', 'gin', 'ning'],
    rows: [
      {
        id: 'row-beginning',
        prompt: 'Beginning',
        correctChoiceId: 'choice-beginning',
        options: [
          { id: 'choice-beginning', text: 'Nia and Ben walk the nature trail in the morning.' },
          { id: 'choice-middle', text: 'Nia picks up trash and Ben cleans the sign.' },
          { id: 'choice-end', text: 'The trail feels calm again.' },
        ],
      },
      {
        id: 'row-problem',
        prompt: 'Problem',
        correctChoiceId: 'choice-problem',
        options: [
          { id: 'choice-problem', text: 'Leaves and wrappers cover the trail.' },
          { id: 'choice-helper', text: 'The hikers smile as they pass.' },
          { id: 'choice-tidy', text: 'The bench area is tidy.' },
        ],
      },
      {
        id: 'row-resolution',
        prompt: 'Resolution',
        correctChoiceId: 'choice-resolution',
        options: [
          { id: 'choice-night', text: 'A windy night starts the story.' },
          { id: 'choice-resolution', text: 'The trail is cleaned and calm again.' },
          { id: 'choice-wrappers', text: 'Wrappers hide near the bench.' },
        ],
      },
    ],
  }),

  createMultipleChoiceQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.birdBoxStorm,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedD,
    activityIdentifier: 'activity-story-map-guided-d',
    questionIdentifier: storyMapQuestionId('guided-d', 'q1'),
    prompt: 'Where does this story happen?',
    explanation: 'The bird box is by the school yard.',
    evidenceReference: 'setting-clue',
    evidenceReferenceIds: [storyMapSentenceId('bird-box-storm', 1)],
    targetVocabulary: ['school yard'],
    soundOutChunks: ['yard'],
    choices: [
      { id: 'a', text: 'by the school yard' },
      { id: 'b', text: 'in the library' },
      { id: 'c', text: 'on the trail' },
      { id: 'd', text: 'in the kitchen' },
    ],
    correctChoiceIds: ['a'],
  }),
  createMultipleChoiceQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.birdBoxStorm,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedD,
    activityIdentifier: 'activity-story-map-guided-d',
    questionIdentifier: storyMapQuestionId('guided-d', 'q2'),
    prompt: 'What is the main problem in this story?',
    explanation: 'The bird box hangs loose before the storm.',
    evidenceReference: 'problem-clue',
    evidenceReferenceIds: [storyMapSentenceId('bird-box-storm', 1)],
    targetVocabulary: ['bird box'],
    soundOutChunks: ['bird', 'box'],
    choices: [
      { id: 'a', text: 'The bird box hangs loose.' },
      { id: 'b', text: 'The library card is missing.' },
      { id: 'c', text: 'The trail is full of wrappers.' },
      { id: 'd', text: 'The seedlings need water.' },
    ],
    correctChoiceIds: ['a'],
  }),
  createMultiselectQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.birdBoxStorm,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedD,
    activityIdentifier: 'activity-story-map-guided-d',
    questionIdentifier: storyMapQuestionId('guided-d', 'q3'),
    prompt: 'Which details help you know where and when the story happens?',
    explanation: 'Those details show the place and the time.',
    evidenceReference: 'setting-clue',
    evidenceReferenceIds: [
      storyMapSentenceId('bird-box-storm', 1),
      storyMapSentenceId('bird-box-storm', 2),
    ],
    targetVocabulary: ['afternoon', 'storm'],
    soundOutChunks: ['af', 'ter'],
    choices: [
      { id: 'a', text: 'late one afternoon' },
      { id: 'b', text: 'by the school yard' },
      { id: 'c', text: 'before the storm arrived' },
      { id: 'd', text: 'after school in the library' },
    ],
    correctChoiceIds: ['a', 'b', 'c'],
  }),
  createHotTextQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.birdBoxStorm,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedD,
    activityIdentifier: 'activity-story-map-guided-d',
    questionIdentifier: storyMapQuestionId('guided-d', 'q4'),
    prompt: 'Which sentence shows how the characters solve the problem?',
    explanation: 'The third sentence shows the fixing work.',
    evidenceReference: 'resolution-clue',
    evidenceReferenceIds: [storyMapSentenceId('bird-box-storm', 3)],
    targetVocabulary: ['secured', 'tightened'],
    soundOutChunks: ['tighten', 'ed'],
    selectableSegments: [
      {
        id: storyMapSentenceId('bird-box-storm', 1),
        text: 'Late one afternoon, Priya and her brother Malik noticed a bird box hanging loose by the school yard.',
      },
      {
        id: storyMapSentenceId('bird-box-storm', 2),
        text: 'Dark clouds moved in, and the wind made the box sway.',
      },
      {
        id: storyMapSentenceId('bird-box-storm', 3),
        text: 'Priya held the ladder steady while Malik secured the hook and tightened the string.',
      },
      {
        id: storyMapSentenceId('bird-box-storm', 4),
        text: 'Before the storm arrived, the box was safe again, and the siblings grinned with relief.',
      },
      {
        id: storyMapSentenceId('bird-box-storm', 5),
        text: 'A small robin hopped nearby as if it knew the home would hold.',
      },
    ],
    correctSegmentIds: [storyMapSentenceId('bird-box-storm', 3)],
  }),
  createTableMatchQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.birdBoxStorm,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedD,
    activityIdentifier: 'activity-story-map-guided-d',
    questionIdentifier: storyMapQuestionId('guided-d', 'q5'),
    prompt: 'Match each story part to the best detail.',
    explanation: 'The story parts help us follow the problem and the fix.',
    evidenceReference: 'story-structure',
    evidenceReferenceIds: [
      storyMapSentenceId('bird-box-storm', 1),
      storyMapSentenceId('bird-box-storm', 3),
      storyMapSentenceId('bird-box-storm', 4),
    ],
    targetVocabulary: ['beginning', 'middle', 'end'],
    soundOutChunks: ['be', 'gin', 'ning'],
    rows: [
      {
        id: 'row-beginning',
        prompt: 'Beginning',
        correctChoiceId: 'choice-beginning',
        options: [
          { id: 'choice-beginning', text: 'Priya and Malik notice the loose bird box.' },
          { id: 'choice-middle', text: 'Priya holds the ladder steady.' },
          { id: 'choice-end', text: 'The box is safe again before the storm.' },
        ],
      },
      {
        id: 'row-problem',
        prompt: 'Problem',
        correctChoiceId: 'choice-problem',
        options: [
          { id: 'choice-problem', text: 'The bird box hangs loose by the school yard.' },
          { id: 'choice-helper', text: 'The robin hops nearby.' },
          { id: 'choice-storm', text: 'Dark clouds move in.' },
        ],
      },
      {
        id: 'row-resolution',
        prompt: 'Resolution',
        correctChoiceId: 'choice-resolution',
        options: [
          { id: 'choice-late', text: 'It is late one afternoon.' },
          { id: 'choice-resolution', text: 'Malik secures the hook and tightens the string.' },
          { id: 'choice-box', text: 'The box sways in the wind.' },
        ],
      },
    ],
  }),
]
