import {
  createEvidencePairQuestion,
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from './questionFactories'
import {
  STORY_MAP_CHECKPOINT_TAGS,
  STORY_MAP_CONTENT_VERSION,
  STORY_MAP_LESSON_IDS,
  STORY_MAP_PASSAGE_IDS,
  storyMapQuestionId,
  storyMapSentenceId,
} from './ids'
import type { ReadingQuestion } from '../../../../types'

const STORY_MAP_QUESTION_TAGS = [...STORY_MAP_CHECKPOINT_TAGS]
const STORY_MAP_BASE = {
  gradeBand: 2 as const,
  benchmarkReference: 'ELA.2.R.1.1',
  skillIdentifier: 'g2-story-scouts-prose',
  reportingCategory: 'Reading Prose and Poetry',
  genre: 'literary',
  estimatedReadingLevel: 'Grade 2',
  reviewStatus: 'DRAFT' as const,
  contentVersion: STORY_MAP_CONTENT_VERSION,
  prerequisiteSkillIdentifiers: [] as string[],
  targetVocabulary: [] as string[],
  soundOutChunks: [] as string[],
  tags: STORY_MAP_QUESTION_TAGS,
}

export const storyMapCheckpointQuestions: ReadingQuestion[] = [
  createMultipleChoiceQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.neighborhoodCleanup,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-story-map-checkpoint-a',
    questionIdentifier: storyMapQuestionId('checkpoint-a', 'q1'),
    prompt: 'What is the main problem in the story?',
    explanation: 'Wrappers and cans have blown across the sidewalk.',
    evidenceReference: 'problem-clue',
    evidenceReferenceIds: [storyMapSentenceId('neighborhood-cleanup', 2)],
    targetVocabulary: ['wrappers', 'cans'],
    soundOutChunks: ['wrap', 'pers'],
    choices: [
      { id: 'a', text: 'Wrappers and cans cover the sidewalk.' },
      { id: 'b', text: 'The bridge model falls over.' },
      { id: 'c', text: 'The bird box is loose.' },
      { id: 'd', text: 'The seedlings are dry.' },
    ],
    correctChoiceIds: ['a'],
  }),
  createMultipleChoiceQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.bridgeModel,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-story-map-checkpoint-a',
    questionIdentifier: storyMapQuestionId('checkpoint-a', 'q2'),
    prompt: 'Where does this story happen?',
    explanation: 'The bridge story happens in the classroom after lunch.',
    evidenceReference: 'setting-clue',
    evidenceReferenceIds: [storyMapSentenceId('bridge-model', 1)],
    targetVocabulary: ['classroom'],
    soundOutChunks: ['class', 'room'],
    choices: [
      { id: 'a', text: 'in the classroom after lunch' },
      { id: 'b', text: 'on the nature trail' },
      { id: 'c', text: 'by the school yard' },
      { id: 'd', text: 'in the garden at night' },
    ],
    correctChoiceIds: ['a'],
  }),
  createMultipleChoiceQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.seedlingsRain,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-story-map-checkpoint-a',
    questionIdentifier: storyMapQuestionId('checkpoint-a', 'q3'),
    prompt: 'How does Harper behave in the story?',
    explanation: 'Harper acts helpful and careful to protect the seedlings.',
    evidenceReference: 'character-clue',
    evidenceReferenceIds: [storyMapSentenceId('seedlings-rain', 3)],
    targetVocabulary: ['helpful', 'careful'],
    soundOutChunks: ['help', 'ful'],
    choices: [
      { id: 'a', text: 'helpful and careful' },
      { id: 'b', text: 'grumpy and rushed' },
      { id: 'c', text: 'sleepy and bored' },
      { id: 'd', text: 'loud and silly' },
    ],
    correctChoiceIds: ['a'],
  }),
  createMultiselectQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.neighborhoodCleanup,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-story-map-checkpoint-a',
    questionIdentifier: storyMapQuestionId('checkpoint-a', 'q4'),
    prompt: 'Which details help you know where and when the story happens?',
    explanation: 'Those details show the place and the time.',
    evidenceReference: 'setting-clue',
    evidenceReferenceIds: [
      storyMapSentenceId('neighborhood-cleanup', 1),
      storyMapSentenceId('neighborhood-cleanup', 5),
    ],
    targetVocabulary: ['Saturday', 'block'],
    soundOutChunks: ['Sat', 'ur', 'day'],
    choices: [
      { id: 'a', text: 'sunny Saturday morning' },
      { id: 'b', text: 'around the block' },
      { id: 'c', text: 'science fair day' },
      { id: 'd', text: 'after school in the library' },
    ],
    correctChoiceIds: ['a', 'b'],
  }),
  createHotTextQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.bridgeModel,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-story-map-checkpoint-a',
    questionIdentifier: storyMapQuestionId('checkpoint-a', 'q5'),
    prompt: 'Which sentence shows how the characters solve the problem?',
    explanation: 'The third sentence tells how they fix the bridge.',
    evidenceReference: 'resolution-clue',
    evidenceReferenceIds: [storyMapSentenceId('bridge-model', 3)],
    targetVocabulary: ['stronger', 'taped'],
    soundOutChunks: ['strong', 'er'],
    selectableSegments: [
      {
        id: storyMapSentenceId('bridge-model', 1),
        text: 'After lunch in the classroom, Carlos and Emmi studied a model bridge for the science fair.',
      },
      {
        id: storyMapSentenceId('bridge-model', 2),
        text: 'The middle beam sagged, and the paper road dipped low.',
      },
      {
        id: storyMapSentenceId('bridge-model', 3),
        text: 'Carlos added a stronger brace while Emmi taped the sides and checked each corner.',
      },
      {
        id: storyMapSentenceId('bridge-model', 4),
        text: 'When the bridge stood steady, their teacher nodded, and the two friends laughed quietly.',
      },
      {
        id: storyMapSentenceId('bridge-model', 5),
        text: 'They placed the model on a blue tray so the class could see the fix.',
      },
    ],
    correctSegmentIds: [storyMapSentenceId('bridge-model', 3)],
  }),
  createTableMatchQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.seedlingsRain,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-story-map-checkpoint-a',
    questionIdentifier: storyMapQuestionId('checkpoint-a', 'q6'),
    prompt: 'Match each story part to the best detail.',
    explanation: 'The details help us follow the beginning, problem, and end.',
    evidenceReference: 'story-structure',
    evidenceReferenceIds: [
      storyMapSentenceId('seedlings-rain', 1),
      storyMapSentenceId('seedlings-rain', 3),
      storyMapSentenceId('seedlings-rain', 4),
    ],
    targetVocabulary: ['beginning', 'problem', 'end'],
    soundOutChunks: ['be', 'gin', 'ning'],
    rows: [
      {
        id: 'row-beginning',
        prompt: 'Beginning',
        correctChoiceId: 'choice-beginning',
        options: [
          { id: 'choice-beginning', text: 'Harper watches the seedlings in the rainy garden.' },
          { id: 'choice-middle', text: 'Harper moves the tray under the awning.' },
          { id: 'choice-end', text: 'A teacher thanks Harper at the end.' },
        ],
      },
      {
        id: 'row-problem',
        prompt: 'Problem',
        correctChoiceId: 'choice-problem',
        options: [
          { id: 'choice-problem', text: 'The cover slips off and the soil looks too wet.' },
          { id: 'choice-helper', text: 'The seedlings stand safer.' },
          { id: 'choice-storm', text: 'A teacher notices the plants.' },
        ],
      },
      {
        id: 'row-resolution',
        prompt: 'Resolution',
        correctChoiceId: 'choice-resolution',
        options: [
          { id: 'choice-wind', text: 'The wind leans the seedlings.' },
          { id: 'choice-resolution', text: 'Harper fixes the tray and keeps the plants safe.' },
          { id: 'choice-rain', text: 'The afternoon is rainy.' },
        ],
      },
    ],
  }),
  createEvidencePairQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.neighborhoodCleanup,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointA,
    activityIdentifier: 'activity-story-map-checkpoint-a',
    questionIdentifier: storyMapQuestionId('checkpoint-a', 'q7'),
    prompt: 'How does Tia feel at the end of the story?',
    explanation: 'The last sentence shows that the cleanup makes Tia proud.',
    evidenceReference: 'character-clue',
    evidenceReferenceIds: [
      storyMapSentenceId('neighborhood-cleanup', 4),
      storyMapSentenceId('neighborhood-cleanup', 5),
    ],
    targetVocabulary: ['proudly', 'helpful'],
    soundOutChunks: ['proud', 'ly'],
    partAChoices: [
      { id: 'part-a-1', text: 'She feels proud and happy.' },
      { id: 'part-a-2', text: 'She feels sleepy and bored.' },
      { id: 'part-a-3', text: 'She feels nervous and quiet.' },
    ],
    partACorrectChoiceId: 'part-a-1',
    partBChoices: [
      { id: 'part-b-1', text: 'Tia waved proudly at the clean sidewalk.' },
      { id: 'part-b-2', text: 'The bridge model sagged low.' },
      { id: 'part-b-3', text: 'The bird box hung loose.' },
    ],
    partBCorrectChoiceId: 'part-b-1',
  }),

  createMultipleChoiceQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.bridgeModel,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-story-map-checkpoint-b',
    questionIdentifier: storyMapQuestionId('checkpoint-b', 'q1'),
    prompt: 'What is the main problem in the story?',
    explanation: 'The bridge sags and the road dips low.',
    evidenceReference: 'problem-clue',
    evidenceReferenceIds: [storyMapSentenceId('bridge-model', 2)],
    targetVocabulary: ['sagged', 'dipped'],
    soundOutChunks: ['sag', 'ged'],
    choices: [
      { id: 'a', text: 'The middle beam sags.' },
      { id: 'b', text: 'The neighbors clean the street.' },
      { id: 'c', text: 'The bird box sways in the wind.' },
      { id: 'd', text: 'The seedlings lean in the garden.' },
    ],
    correctChoiceIds: ['a'],
  }),
  createMultipleChoiceQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.seedlingsRain,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-story-map-checkpoint-b',
    questionIdentifier: storyMapQuestionId('checkpoint-b', 'q2'),
    prompt: 'Where does this story happen?',
    explanation: 'The story happens in the school garden.',
    evidenceReference: 'setting-clue',
    evidenceReferenceIds: [storyMapSentenceId('seedlings-rain', 1)],
    targetVocabulary: ['school garden'],
    soundOutChunks: ['gar', 'den'],
    choices: [
      { id: 'a', text: 'in the school garden' },
      { id: 'b', text: 'in the library' },
      { id: 'c', text: 'at the picnic table' },
      { id: 'd', text: 'on the city bus' },
    ],
    correctChoiceIds: ['a'],
  }),
  createMultipleChoiceQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.neighborhoodCleanup,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-story-map-checkpoint-b',
    questionIdentifier: storyMapQuestionId('checkpoint-b', 'q3'),
    prompt: 'How does Tia behave in the story?',
    explanation: 'Tia acts like a helpful leader.',
    evidenceReference: 'character-clue',
    evidenceReferenceIds: [storyMapSentenceId('neighborhood-cleanup', 1)],
    targetVocabulary: ['led', 'helpers'],
    soundOutChunks: ['help', 'ful'],
    choices: [
      { id: 'a', text: 'helpful and a good leader' },
      { id: 'b', text: 'careless and hurried' },
      { id: 'c', text: 'sleepy and quiet' },
      { id: 'd', text: 'angry and rude' },
    ],
    correctChoiceIds: ['a'],
  }),
  createMultiselectQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.bridgeModel,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-story-map-checkpoint-b',
    questionIdentifier: storyMapQuestionId('checkpoint-b', 'q4'),
    prompt: 'Which details help you know where and when the story happens?',
    explanation: 'Those details show the classroom and the time after lunch.',
    evidenceReference: 'setting-clue',
    evidenceReferenceIds: [
      storyMapSentenceId('bridge-model', 1),
      storyMapSentenceId('bridge-model', 4),
    ],
    targetVocabulary: ['classroom', 'after lunch'],
    soundOutChunks: ['lunch'],
    choices: [
      { id: 'a', text: 'after lunch' },
      { id: 'b', text: 'in the classroom' },
      { id: 'c', text: 'before the storm' },
      { id: 'd', text: 'at the trail bench' },
    ],
    correctChoiceIds: ['a', 'b'],
  }),
  createHotTextQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.seedlingsRain,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-story-map-checkpoint-b',
    questionIdentifier: storyMapQuestionId('checkpoint-b', 'q5'),
    prompt: 'Which sentence shows how the characters solve the problem?',
    explanation: 'The third sentence tells how Harper fixes the tray.',
    evidenceReference: 'resolution-clue',
    evidenceReferenceIds: [storyMapSentenceId('seedlings-rain', 3)],
    targetVocabulary: ['moved', 'awning'],
    soundOutChunks: ['mov', 'ed'],
    selectableSegments: [
      {
        id: storyMapSentenceId('seedlings-rain', 1),
        text: 'During a rainy afternoon in the school garden, Harper watched the young seedlings lean in the wind.',
      },
      {
        id: storyMapSentenceId('seedlings-rain', 2),
        text: 'A cover had slipped off the tray, and the soil looked too wet.',
      },
      {
        id: storyMapSentenceId('seedlings-rain', 3),
        text: 'Harper lifted the cover, moved the tray under the awning, and patted the leaves dry with a cloth.',
      },
      {
        id: storyMapSentenceId('seedlings-rain', 4),
        text: 'By the end, the seedlings stood safer, and Harper felt calm and helpful.',
      },
      {
        id: storyMapSentenceId('seedlings-rain', 5),
        text: 'A teacher thanked Harper for keeping the plants safe before the next storm.',
      },
    ],
    correctSegmentIds: [storyMapSentenceId('seedlings-rain', 3)],
  }),
  createTableMatchQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.neighborhoodCleanup,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-story-map-checkpoint-b',
    questionIdentifier: storyMapQuestionId('checkpoint-b', 'q6'),
    prompt: 'Match each story part to the best detail.',
    explanation: 'The details help us follow the beginning, problem, and end.',
    evidenceReference: 'story-structure',
    evidenceReferenceIds: [
      storyMapSentenceId('neighborhood-cleanup', 1),
      storyMapSentenceId('neighborhood-cleanup', 3),
      storyMapSentenceId('neighborhood-cleanup', 4),
    ],
    targetVocabulary: ['beginning', 'problem', 'end'],
    soundOutChunks: ['be', 'gin', 'ning'],
    rows: [
      {
        id: 'row-beginning',
        prompt: 'Beginning',
        correctChoiceId: 'choice-beginning',
        options: [
          { id: 'choice-beginning', text: 'Tia leads the neighbors around the block.' },
          { id: 'choice-middle', text: 'The helpers sort the trash.' },
          { id: 'choice-end', text: 'Tia waves proudly at the clean sidewalk.' },
        ],
      },
      {
        id: 'row-problem',
        prompt: 'Problem',
        correctChoiceId: 'choice-problem',
        options: [
          { id: 'choice-problem', text: 'Snack wrappers and cans cover the sidewalk.' },
          { id: 'choice-helper', text: 'The neighbors line up the bags.' },
          { id: 'choice-finish', text: 'The street looks fresh.' },
        ],
      },
      {
        id: 'row-resolution',
        prompt: 'Resolution',
        correctChoiceId: 'choice-resolution',
        options: [
          { id: 'choice-wind', text: 'The wind keeps blowing wrappers.' },
          { id: 'choice-resolution', text: 'The trash is sorted and the block looks fresh.' },
          { id: 'choice-night', text: 'It becomes evening.' },
        ],
      },
    ],
  }),
  createEvidencePairQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.bridgeModel,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointB,
    activityIdentifier: 'activity-story-map-checkpoint-b',
    questionIdentifier: storyMapQuestionId('checkpoint-b', 'q7'),
    prompt: 'What was the main problem in the bridge story?',
    explanation: 'The middle beam sagged and the paper road dipped low.',
    evidenceReference: 'problem-clue',
    evidenceReferenceIds: [
      storyMapSentenceId('bridge-model', 2),
      storyMapSentenceId('bridge-model', 3),
    ],
    targetVocabulary: ['beam', 'sagged'],
    soundOutChunks: ['beam'],
    partAChoices: [
      { id: 'part-a-1', text: 'The middle beam sagged.' },
      { id: 'part-a-2', text: 'The teacher thanked the class.' },
      { id: 'part-a-3', text: 'The bridge stood steady.' },
    ],
    partACorrectChoiceId: 'part-a-1',
    partBChoices: [
      { id: 'part-b-1', text: 'The paper road dipped low.' },
      { id: 'part-b-2', text: 'The friends laughed quietly.' },
      { id: 'part-b-3', text: 'The tray sat on a blue shelf.' },
    ],
    partBCorrectChoiceId: 'part-b-1',
  }),

  createMultipleChoiceQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.seedlingsRain,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-story-map-checkpoint-c',
    questionIdentifier: storyMapQuestionId('checkpoint-c', 'q1'),
    prompt: 'What is the main problem in the story?',
    explanation: 'The cover slips off and the soil gets too wet.',
    evidenceReference: 'problem-clue',
    evidenceReferenceIds: [storyMapSentenceId('seedlings-rain', 2)],
    targetVocabulary: ['cover', 'soil'],
    soundOutChunks: ['soil'],
    choices: [
      { id: 'a', text: 'The cover slips off the tray.' },
      { id: 'b', text: 'The bird box hangs loose.' },
      { id: 'c', text: 'The library shelf looks messy.' },
      { id: 'd', text: 'The sidewalk is full of wrappers.' },
    ],
    correctChoiceIds: ['a'],
  }),
  createMultipleChoiceQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.neighborhoodCleanup,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-story-map-checkpoint-c',
    questionIdentifier: storyMapQuestionId('checkpoint-c', 'q2'),
    prompt: 'Where does this story happen?',
    explanation: 'The neighbors clean the block sidewalk.',
    evidenceReference: 'setting-clue',
    evidenceReferenceIds: [storyMapSentenceId('neighborhood-cleanup', 1)],
    targetVocabulary: ['sidewalk', 'block'],
    soundOutChunks: ['side', 'walk'],
    choices: [
      { id: 'a', text: 'around the block sidewalk' },
      { id: 'b', text: 'in the science room' },
      { id: 'c', text: 'on the trail bench' },
      { id: 'd', text: 'under the bird box' },
    ],
    correctChoiceIds: ['a'],
  }),
  createMultipleChoiceQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.bridgeModel,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-story-map-checkpoint-c',
    questionIdentifier: storyMapQuestionId('checkpoint-c', 'q3'),
    prompt: 'How does the character behave in the story?',
    explanation: 'Carlos acts like a careful helper.',
    evidenceReference: 'character-clue',
    evidenceReferenceIds: [storyMapSentenceId('bridge-model', 3)],
    targetVocabulary: ['careful', 'helper'],
    soundOutChunks: ['care', 'ful'],
    choices: [
      { id: 'a', text: 'careful and helpful' },
      { id: 'b', text: 'sad and sleepy' },
      { id: 'c', text: 'loud and angry' },
      { id: 'd', text: 'late and lost' },
    ],
    correctChoiceIds: ['a'],
  }),
  createMultiselectQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.seedlingsRain,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-story-map-checkpoint-c',
    questionIdentifier: storyMapQuestionId('checkpoint-c', 'q4'),
    prompt: 'Which details help you know where and when the story happens?',
    explanation: 'Those details show the school garden and the rainy afternoon.',
    evidenceReference: 'setting-clue',
    evidenceReferenceIds: [
      storyMapSentenceId('seedlings-rain', 1),
      storyMapSentenceId('seedlings-rain', 5),
    ],
    targetVocabulary: ['afternoon', 'garden'],
    soundOutChunks: ['af', 'ter'],
    choices: [
      { id: 'a', text: 'rainy afternoon' },
      { id: 'b', text: 'school garden' },
      { id: 'c', text: 'blue tray' },
      { id: 'd', text: 'science fair' },
    ],
    correctChoiceIds: ['a', 'b'],
  }),
  createHotTextQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.neighborhoodCleanup,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-story-map-checkpoint-c',
    questionIdentifier: storyMapQuestionId('checkpoint-c', 'q5'),
    prompt: 'Which sentence shows the resolution?',
    explanation: 'The fourth sentence shows the problem is fixed.',
    evidenceReference: 'resolution-clue',
    evidenceReferenceIds: [storyMapSentenceId('neighborhood-cleanup', 4)],
    targetVocabulary: ['proudly', 'fresh'],
    soundOutChunks: ['proud', 'ly'],
    selectableSegments: [
      {
        id: storyMapSentenceId('neighborhood-cleanup', 1),
        text: 'On a sunny Saturday morning, Tia led three neighbors around the block.',
      },
      {
        id: storyMapSentenceId('neighborhood-cleanup', 2),
        text: 'Snack wrappers and cans had blown across the sidewalk after the picnic.',
      },
      {
        id: storyMapSentenceId('neighborhood-cleanup', 3),
        text: 'Tia sorted the trash, and the helpers worked carefully until every bag was full.',
      },
      {
        id: storyMapSentenceId('neighborhood-cleanup', 4),
        text: 'At the end, the street looked fresh, and Tia waved proudly at the clean sidewalk.',
      },
      {
        id: storyMapSentenceId('neighborhood-cleanup', 5),
        text: 'The neighbors lined up the bags near the curb for pickup that evening.',
      },
    ],
    correctSegmentIds: [storyMapSentenceId('neighborhood-cleanup', 4)],
  }),
  createTableMatchQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.bridgeModel,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-story-map-checkpoint-c',
    questionIdentifier: storyMapQuestionId('checkpoint-c', 'q6'),
    prompt: 'Match each story part to the best detail.',
    explanation: 'The beginning, problem, and ending each have a clear clue.',
    evidenceReference: 'story-structure',
    evidenceReferenceIds: [
      storyMapSentenceId('bridge-model', 1),
      storyMapSentenceId('bridge-model', 2),
      storyMapSentenceId('bridge-model', 4),
    ],
    targetVocabulary: ['beginning', 'problem', 'end'],
    soundOutChunks: ['be', 'gin', 'ning'],
    rows: [
      {
        id: 'row-beginning',
        prompt: 'Beginning',
        correctChoiceId: 'choice-beginning',
        options: [
          { id: 'choice-beginning', text: 'Carlos and Emmi study a model bridge after lunch.' },
          { id: 'choice-middle', text: 'Carlos adds a stronger brace.' },
          { id: 'choice-end', text: 'The friends laugh quietly when the bridge stands steady.' },
        ],
      },
      {
        id: 'row-problem',
        prompt: 'Problem',
        correctChoiceId: 'choice-problem',
        options: [
          { id: 'choice-problem', text: 'The middle beam sagged and the road dipped low.' },
          { id: 'choice-helper', text: 'The class sees the fix on a blue tray.' },
          { id: 'choice-lunch', text: 'The story starts after lunch.' },
        ],
      },
      {
        id: 'row-resolution',
        prompt: 'Resolution',
        correctChoiceId: 'choice-resolution',
        options: [
          { id: 'choice-sagged', text: 'The beam keeps sagging.' },
          { id: 'choice-resolution', text: 'The bridge stands steady after the fix.' },
          { id: 'choice-road', text: 'The paper road dips low again.' },
        ],
      },
    ],
  }),
  createEvidencePairQuestion({
    ...STORY_MAP_BASE,
    difficulty: 1,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.seedlingsRain,
    lessonIdentifier: STORY_MAP_LESSON_IDS.checkpointC,
    activityIdentifier: 'activity-story-map-checkpoint-c',
    questionIdentifier: storyMapQuestionId('checkpoint-c', 'q7'),
    prompt: 'How does Harper feel at the end of the story?',
    explanation: 'The ending says Harper feels calm and helpful.',
    evidenceReference: 'character-clue',
    evidenceReferenceIds: [
      storyMapSentenceId('seedlings-rain', 4),
      storyMapSentenceId('seedlings-rain', 5),
    ],
    targetVocabulary: ['calm', 'helpful'],
    soundOutChunks: ['help', 'ful'],
    partAChoices: [
      { id: 'part-a-1', text: 'calm and helpful' },
      { id: 'part-a-2', text: 'angry and loud' },
      { id: 'part-a-3', text: 'sleepy and bored' },
    ],
    partACorrectChoiceId: 'part-a-1',
    partBChoices: [
      { id: 'part-b-1', text: 'Harper felt calm and helpful.' },
      { id: 'part-b-2', text: 'The bridge beam sagged low.' },
      { id: 'part-b-3', text: 'The wrappers blew across the sidewalk.' },
    ],
    partBCorrectChoiceId: 'part-b-1',
  }),
]
