import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
} from './questionFactories'
import {
  STORY_MAP_CHECKPOINT_TAGS,
  STORY_MAP_CONTENT_VERSION,
  STORY_MAP_LESSON_IDS,
  STORY_MAP_PASSAGE_IDS,
  storyMapQuestionId,
  storyMapSentenceId,
} from './ids'
import type { ReadingQuestion } from '../../../../types'

const STORY_MAP_QUESTION_TAGS = [...STORY_MAP_CHECKPOINT_TAGS]
const STORY_MAP_BASE = {
  gradeBand: 2 as const,
  benchmarkReference: 'ELA.2.R.1.1',
  skillIdentifier: 'g2-story-scouts-prose',
  reportingCategory: 'Reading Prose and Poetry',
  genre: 'literary',
  estimatedReadingLevel: 'Grade 2',
  reviewStatus: 'DRAFT' as const,
  contentVersion: STORY_MAP_CONTENT_VERSION,
  prerequisiteSkillIdentifiers: [] as string[],
  targetVocabulary: [] as string[],
  soundOutChunks: [] as string[],
  tags: STORY_MAP_QUESTION_TAGS,
}

export const storyMapBuildingBlockQuestions: ReadingQuestion[] = [
  createMultipleChoiceQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.gardenSign,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedA,
    activityIdentifier: 'activity-story-map-guided-a',
    questionIdentifier: storyMapQuestionId('guided-a', 'q1'),
    prompt: 'Where does this story happen?',
    explanation: 'The story happens at the community garden.',
    evidenceReference: 'setting-clue',
    evidenceReferenceIds: [storyMapSentenceId('garden-sign', 1)],
    targetVocabulary: ['community garden'],
    soundOutChunks: ['gar', 'den'],
    choices: [
      { id: 'a', text: 'at the community garden' },
      { id: 'b', text: 'in the library' },
      { id: 'c', text: 'on the trail' },
      { id: 'd', text: 'inside the classroom' },
    ],
    correctChoiceIds: ['a'],
  }),
  createMultipleChoiceQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.gardenSign,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedA,
    activityIdentifier: 'activity-story-map-guided-a',
    questionIdentifier: storyMapQuestionId('guided-a', 'q2'),
    prompt: 'What is the main problem in the story?',
    explanation: 'The welcome sign is bent and crooked.',
    evidenceReference: 'problem-clue',
    evidenceReferenceIds: [storyMapSentenceId('garden-sign', 2)],
    targetVocabulary: ['welcome sign'],
    soundOutChunks: ['sign'],
    choices: [
      { id: 'a', text: 'The welcome sign is bent.' },
      { id: 'b', text: 'The garden is empty.' },
      { id: 'c', text: 'The visitors are late.' },
      { id: 'd', text: 'Leo loses the tape.' },
    ],
    correctChoiceIds: ['a'],
  }),
  createMultiselectQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.gardenSign,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedA,
    activityIdentifier: 'activity-story-map-guided-a',
    questionIdentifier: storyMapQuestionId('guided-a', 'q3'),
    prompt: 'Which details help you know where and when the story happens?',
    explanation: 'Those details tell us the place and the time.',
    evidenceReference: 'setting-clue',
    evidenceReferenceIds: [
      storyMapSentenceId('garden-sign', 1),
      storyMapSentenceId('garden-sign', 4),
    ],
    targetVocabulary: ['Monday', 'garden'],
    soundOutChunks: ['Mon', 'day'],
    choices: [
      { id: 'a', text: 'bright Monday morning' },
      { id: 'b', text: 'the community garden' },
      { id: 'c', text: 'teacher help' },
      { id: 'd', text: 'picture books' },
    ],
    correctChoiceIds: ['a', 'b'],
  }),
  createHotTextQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.gardenSign,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedA,
    activityIdentifier: 'activity-story-map-guided-a',
    questionIdentifier: storyMapQuestionId('guided-a', 'q4'),
    prompt: 'Which sentence shows the problem?',
    explanation: 'The second sentence tells us the sign is bent.',
    evidenceReference: 'problem-clue',
    evidenceReferenceIds: [storyMapSentenceId('garden-sign', 2)],
    targetVocabulary: ['bent', 'crooked'],
    soundOutChunks: ['crook', 'ed'],
    selectableSegments: [
      {
        id: storyMapSentenceId('garden-sign', 1),
        text: 'On a bright Monday morning, Mia arrived at the community garden before the harvest sign-up table opened.',
      },
      {
        id: storyMapSentenceId('garden-sign', 2),
        text: 'A wind gust had bent the welcome sign, and the letters looked crooked.',
      },
      {
        id: storyMapSentenceId('garden-sign', 3),
        text: 'Mia frowned, then carefully straightened the board with tape and two helping hands from her brother, Leo.',
      },
      {
        id: storyMapSentenceId('garden-sign', 4),
        text: 'By the end, the sign stood tall again, and Mia smiled because the garden looked ready for visitors.',
      },
      {
        id: storyMapSentenceId('garden-sign', 5),
        text: 'The early visitors would see the message clearly, and Mia felt proud of the fix.',
      },
    ],
    correctSegmentIds: [storyMapSentenceId('garden-sign', 2)],
  }),
  createTableMatchQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.gardenSign,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedA,
    activityIdentifier: 'activity-story-map-guided-a',
    questionIdentifier: storyMapQuestionId('guided-a', 'q5'),
    prompt: 'Match each story part to the best detail.',
    explanation: 'The beginning, middle, and end each tell a different part of the story.',
    evidenceReference: 'story-structure',
    evidenceReferenceIds: [
      storyMapSentenceId('garden-sign', 1),
      storyMapSentenceId('garden-sign', 3),
      storyMapSentenceId('garden-sign', 4),
    ],
    targetVocabulary: ['beginning', 'middle', 'end'],
    soundOutChunks: ['be', 'gin', 'ning'],
    rows: [
      {
        id: 'row-beginning',
        prompt: 'Beginning',
        correctChoiceId: 'choice-beginning',
        options: [
          { id: 'choice-beginning', text: 'Mia arrives at the community garden in the morning.' },
          { id: 'choice-middle', text: 'Mia straightens the bent welcome sign.' },
          { id: 'choice-end', text: 'The sign stands tall again for visitors.' },
        ],
      },
      {
        id: 'row-problem',
        prompt: 'Problem',
        correctChoiceId: 'choice-problem',
        options: [
          { id: 'choice-problem', text: 'The welcome sign is bent and crooked.' },
          { id: 'choice-helper', text: 'Leo brings helping hands to the garden.' },
          { id: 'choice-ready', text: 'The garden looks ready for visitors.' },
        ],
      },
      {
        id: 'row-resolution',
        prompt: 'Resolution',
        correctChoiceId: 'choice-resolution',
        options: [
          { id: 'choice-event', text: 'The morning event opens.' },
          { id: 'choice-resolution', text: 'Mia fixes the sign and smiles at the end.' },
          { id: 'choice-delay', text: 'The wind keeps blowing.' },
        ],
      },
    ],
  }),

  createMultipleChoiceQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.libraryCard,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedB,
    activityIdentifier: 'activity-story-map-guided-b',
    questionIdentifier: storyMapQuestionId('guided-b', 'q1'),
    prompt: 'Where does this story happen?',
    explanation: 'The story happens at the library table.',
    evidenceReference: 'setting-clue',
    evidenceReferenceIds: [storyMapSentenceId('library-card', 1)],
    targetVocabulary: ['library'],
    soundOutChunks: ['li', 'bra', 'ry'],
    choices: [
      { id: 'a', text: 'at the library table' },
      { id: 'b', text: 'on the trail' },
      { id: 'c', text: 'in the garden' },
      { id: 'd', text: 'by the bird box' },
    ],
    correctChoiceIds: ['a'],
  }),
  createMultipleChoiceQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.libraryCard,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedB,
    activityIdentifier: 'activity-story-map-guided-b',
    questionIdentifier: storyMapQuestionId('guided-b', 'q2'),
    prompt: 'Who is the main character in this story?',
    explanation: 'Jamal is the character who helps fix the display.',
    evidenceReference: 'character-clue',
    evidenceReferenceIds: [storyMapSentenceId('library-card', 1)],
    targetVocabulary: ['Jamal'],
    soundOutChunks: ['Ja', 'mal'],
    choices: [
      { id: 'a', text: 'Jamal' },
      { id: 'b', text: 'Mia' },
      { id: 'c', text: 'Priya' },
      { id: 'd', text: 'Harper' },
    ],
    correctChoiceIds: ['a'],
  }),
  createMultiselectQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.libraryCard,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedB,
    activityIdentifier: 'activity-story-map-guided-b',
    questionIdentifier: storyMapQuestionId('guided-b', 'q3'),
    prompt: 'Which details tell you when or where the story happens?',
    explanation: 'Those details show the time and place.',
    evidenceReference: 'setting-clue',
    evidenceReferenceIds: [
      storyMapSentenceId('library-card', 1),
      storyMapSentenceId('library-card', 2),
    ],
    targetVocabulary: ['after school', 'rainy afternoon'],
    soundOutChunks: ['af', 'ter'],
    choices: [
      { id: 'a', text: 'after school' },
      { id: 'b', text: 'rainy afternoon' },
      { id: 'c', text: 'science fair' },
      { id: 'd', text: 'bright picture book' },
    ],
    correctChoiceIds: ['a', 'b'],
  }),
  createHotTextQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.libraryCard,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedB,
    activityIdentifier: 'activity-story-map-guided-b',
    questionIdentifier: storyMapQuestionId('guided-b', 'q4'),
    prompt: 'Which sentence shows how Jamal solves the problem?',
    explanation: 'The third sentence tells the fixing steps.',
    evidenceReference: 'resolution-clue',
    evidenceReferenceIds: [storyMapSentenceId('library-card', 3)],
    targetVocabulary: ['opened', 'sorted'],
    soundOutChunks: ['sort', 'ed'],
    selectableSegments: [
      {
        id: storyMapSentenceId('library-card', 1),
        text: 'After school on a rainy afternoon, Jamal helped at the library table.',
      },
      {
        id: storyMapSentenceId('library-card', 2),
        text: 'A card about the bird book slipped behind the display, and the shelf looked messy.',
      },
      {
        id: storyMapSentenceId('library-card', 3),
        text: "Jamal opened the drawer, sorted the cards, and wrote a new label with his teacher's kind help.",
      },
      {
        id: storyMapSentenceId('library-card', 4),
        text: 'Soon the display looked neat, and Jamal felt proud when the children stopped to read it.',
      },
      {
        id: storyMapSentenceId('library-card', 5),
        text: 'He placed the old card in front of the shelf so no one would miss the bright picture book again.',
      },
    ],
    correctSegmentIds: [storyMapSentenceId('library-card', 3)],
  }),
  createTableMatchQuestion({
    ...STORY_MAP_BASE,
    difficulty: 0,
    passageIdentifier: STORY_MAP_PASSAGE_IDS.libraryCard,
    lessonIdentifier: STORY_MAP_LESSON_IDS.guidedB,
    activityIdentifier: 'activity-story-map-guided-b',
    questionIdentifier: storyMapQuestionId('guided-b', 'q5'),
    prompt: 'Match each story part to the best detail.',
    explanation: 'The story parts help us follow the problem and the fix.',
    evidenceReference: 'story-structure',
    evidenceReferenceIds: [
      storyMapSentenceId('library-card', 1),
      storyMapSentenceId('library-card', 3),
      storyMapSentenceId('library-card', 4),
    ],
    targetVocabulary: ['display', 'label', 'proud'],
    soundOutChunks: ['dis', 'play'],
    rows: [
      {
        id: 'row-beginning',
        prompt: 'Beginning',
        correctChoiceId: 'choice-beginning',
        options: [
          { id: 'choice-beginning', text: 'Jamal helps at the library table after school.' },
          { id: 'choice-middle', text: 'Jamal opens the drawer and sorts the cards.' },
          { id: 'choice-end', text: 'The display looks neat and Jamal feels proud.' },
        ],
      },
      {
        id: 'row-problem',
        prompt: 'Problem',
        correctChoiceId: 'choice-problem',
        options: [
          { id: 'choice-problem', text: 'A card slips behind the display.' },
          { id: 'choice-helper', text: 'The teacher gives kind help.' },
          { id: 'choice-reader', text: 'Children stop to read the book.' },
        ],
      },
      {
        id: 'row-resolution',
        prompt: 'Resolution',
        correctChoiceId: 'choice-resolution',
        options: [
          { id: 'choice-neat', text: 'The shelf looks messy.' },
          { id: 'choice-resolution', text: 'Jamal writes a new label and fixes the display.' },
          { id: 'choice-card', text: 'The bird book slips again.' },
        ],
      },
    ],
  }),
]
