import {
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
  lessonChoice as choice,
} from './questionFactories'
import {
  centralIdeaCenterContentVersion,
  centralIdeaCenterFeatureIds,
  centralIdeaCenterLessonIds,
  centralIdeaCenterPassageIds,
  centralIdeaCenterQuestionIds,
  centralIdeaCenterSentenceIds,
} from './ids'
import { pollinatorPatchSentences, weatherStationSentences } from './passages'

const base = {
  benchmarkReference: 'ELA.2.R.2.2' as const,
  skillIdentifier: 'g2-information-detectives-reading' as const,
  reportingCategory: 'Reading Informational Text' as const,
  genre: 'informational' as const,
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2' as const,
  contentVersion: centralIdeaCenterContentVersion,
  reviewStatus: 'DRAFT' as const,
}

export const centralIdeaCenterGuidedQuestions = [
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.pollinatorPatchCounts.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.guidedAcrossSections,
    questionIdentifier: centralIdeaCenterQuestionIds.guidedAcrossSections[0],
    prompt: 'What is the topic of this passage?',
    explanation: 'The topic is a short phrase that names what the passage is about.',
    evidenceReference: centralIdeaCenterFeatureIds.pollinatorPatchCounts.title,
    evidenceReferenceIds: [centralIdeaCenterFeatureIds.pollinatorPatchCounts.title],
    targetVocabulary: ['topic'],
    soundOutChunks: ['top', 'ic'],
    tags: ['central-idea', 'topic-vs-central-idea'],
    choices: [
      choice('pollinator-topic', 'pollinator patch counts'),
      choice('weather-topic', 'weather tools'),
      choice('seed-topic', 'seed travel routes'),
      choice('compost-topic', 'compost piles'),
    ],
    correctChoiceIds: ['pollinator-topic'],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.pollinatorPatchCounts.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.guidedAcrossSections,
    questionIdentifier: centralIdeaCenterQuestionIds.guidedAcrossSections[1],
    prompt: 'Which sentence is the best central idea?',
    explanation: 'The central idea is a complete thought that brings the details together.',
    evidenceReference: centralIdeaCenterSentenceIds.pollinatorPatchCounts[7],
    evidenceReferenceIds: [centralIdeaCenterSentenceIds.pollinatorPatchCounts[7]],
    targetVocabulary: ['central idea', 'complete thought'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['central-idea', 'central-idea-complete-thought', 'inferred-central-idea'],
    choices: [
      choice('pollinator-detail-1', 'The sunny row had the tallest stems near the path.'),
      choice('pollinator-detail-2', 'The class counted three kinds of blooms in the sunny row.'),
      choice('pollinator-central', 'A pollinator garden gives insects places to find food and rest.'),
      choice('pollinator-detail-3', 'The shady row had fewer blooms but more leaves.'),
    ],
    correctChoiceIds: ['pollinator-central'],
  }),
  createMultiselectQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.pollinatorPatchCounts.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.guidedAcrossSections,
    questionIdentifier: centralIdeaCenterQuestionIds.guidedAcrossSections[2],
    prompt: 'Choose two details that are most relevant to the central idea.',
    explanation: 'The best details help readers see how the class compares the patch and notices insect visits.',
    evidenceReference: centralIdeaCenterFeatureIds.pollinatorPatchCounts.caption,
    evidenceReferenceIds: [
      centralIdeaCenterSentenceIds.pollinatorPatchCounts[1],
      centralIdeaCenterSentenceIds.pollinatorPatchCounts[2],
    ],
    targetVocabulary: ['relevant detail', 'compare', 'observe'],
    soundOutChunks: ['re', 'le', 'vant'],
    tags: ['relevant-details', 'relevant-detail-identification'],
    choices: [
      choice('pollinator-blue', 'The graph shows more blue flowers than red ones there.'),
      choice('pollinator-bees', 'Bees visited the sunny row most often on warm mornings.'),
      choice('pollinator-balance', 'The shady row had fewer blooms but more leaves.'),
      choice('pollinator-stems', 'The sunny row also had the tallest stems near the path.'),
    ],
    correctChoiceIds: ['pollinator-blue', 'pollinator-bees'],
  }),
  createHotTextQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.pollinatorPatchCounts.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.guidedAcrossSections,
    questionIdentifier: centralIdeaCenterQuestionIds.guidedAcrossSections[3],
    prompt: 'Tap the sentence that best helps readers understand the central idea.',
    explanation: 'This sentence puts the passage idea into a complete thought.',
    evidenceReference: centralIdeaCenterSentenceIds.pollinatorPatchCounts[7],
    evidenceReferenceIds: [centralIdeaCenterSentenceIds.pollinatorPatchCounts[7]],
    targetVocabulary: ['central idea'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['central-idea', 'stated-central-idea'],
    selectableSegments: [
      { id: centralIdeaCenterSentenceIds.pollinatorPatchCounts[0], text: pollinatorPatchSentences[0].text },
      { id: centralIdeaCenterSentenceIds.pollinatorPatchCounts[2], text: pollinatorPatchSentences[2].text },
      { id: centralIdeaCenterSentenceIds.pollinatorPatchCounts[6], text: pollinatorPatchSentences[6].text },
      { id: centralIdeaCenterSentenceIds.pollinatorPatchCounts[7], text: pollinatorPatchSentences[7].text },
    ],
    correctSegmentIds: [centralIdeaCenterSentenceIds.pollinatorPatchCounts[7]],
  }),
  createTableMatchQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.pollinatorPatchCounts.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.guidedAcrossSections,
    questionIdentifier: centralIdeaCenterQuestionIds.guidedAcrossSections[4],
    prompt: 'Match each statement to the best answer.',
    explanation: 'Each row matches a statement to the idea it names.',
    evidenceReference: centralIdeaCenterFeatureIds.pollinatorPatchCounts.glossary,
    evidenceReferenceIds: [
      centralIdeaCenterFeatureIds.pollinatorPatchCounts.title,
      centralIdeaCenterSentenceIds.pollinatorPatchCounts[7],
    ],
    targetVocabulary: ['topic', 'detail', 'central idea'],
    soundOutChunks: ['stat', 'e', 'ment'],
    tags: ['central-idea-and-evidence', 'most-relevant-details'],
    rows: [
      {
        id: 'pollinator-topic',
        prompt: 'What is the topic?',
        correctChoiceId: 'pollinator-topic-answer',
        options: [
          choice('pollinator-topic-answer', 'pollinator patch counts'),
          choice('pollinator-topic-detail', 'Bees visited the sunny row most often on warm mornings.'),
          choice('pollinator-topic-other', 'The shady row had fewer blooms but more leaves.'),
        ],
      },
      {
        id: 'pollinator-central',
        prompt: 'What is the central idea?',
        correctChoiceId: 'pollinator-central-answer',
        options: [
          choice('pollinator-central-answer', 'A pollinator garden gives insects places to find food and rest.'),
          choice('pollinator-central-other1', 'The graph shows more blue flowers than red ones there.'),
          choice('pollinator-central-other2', 'The sunny row also had the tallest stems near the path.'),
        ],
      },
      {
        id: 'pollinator-other',
        prompt: 'Which is another true detail?',
        correctChoiceId: 'pollinator-other-answer',
        options: [
          choice('pollinator-other-answer', 'The shady row had fewer blooms but more leaves.'),
          choice('pollinator-other-topic', 'pollinator patch counts'),
          choice('pollinator-other-central', 'A pollinator garden gives insects places to find food and rest.'),
        ],
      },
    ],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.weatherStationNotes.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.guidedPutImportantDetailsTogether,
    questionIdentifier: centralIdeaCenterQuestionIds.guidedPutImportantDetailsTogether[0],
    prompt: 'What is the topic of this passage?',
    explanation: 'The topic is a short phrase that names what the passage is about.',
    evidenceReference: centralIdeaCenterFeatureIds.weatherStationNotes.title,
    evidenceReferenceIds: [centralIdeaCenterFeatureIds.weatherStationNotes.title],
    targetVocabulary: ['topic'],
    soundOutChunks: ['top', 'ic'],
    tags: ['central-idea', 'topic-vs-central-idea'],
    choices: [
      choice('weather-topic', 'weather station notes'),
      choice('compost-topic', 'compost piles'),
      choice('seed-topic', 'seed travel routes'),
      choice('pollinator-topic', 'pollinator patch counts'),
    ],
    correctChoiceIds: ['weather-topic'],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.weatherStationNotes.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.guidedPutImportantDetailsTogether,
    questionIdentifier: centralIdeaCenterQuestionIds.guidedPutImportantDetailsTogether[1],
    prompt: 'Which sentence is the best central idea?',
    explanation: 'The central idea is the complete thought that the details point to.',
    evidenceReference: centralIdeaCenterSentenceIds.weatherStationNotes[7],
    evidenceReferenceIds: [centralIdeaCenterSentenceIds.weatherStationNotes[7]],
    targetVocabulary: ['central idea', 'observations'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['central-idea', 'central-idea-complete-thought', 'stated-central-idea'],
    choices: [
      choice('weather-detail-1', 'A wind sock points the direction the wind blows.'),
      choice('weather-central', 'With tools and careful observations, the class learns more about weather.'),
      choice('weather-detail-2', 'A thermometer tells the class if the air feels warmer or cooler.'),
      choice('weather-detail-3', 'A student circles cloudy days on the chart so the group can check them later.'),
    ],
    correctChoiceIds: ['weather-central'],
  }),
  createMultiselectQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.weatherStationNotes.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.guidedPutImportantDetailsTogether,
    questionIdentifier: centralIdeaCenterQuestionIds.guidedPutImportantDetailsTogether[2],
    prompt: 'Choose two details that are most relevant to the central idea.',
    explanation: 'These details show how the class uses tools and records to learn about weather.',
    evidenceReference: centralIdeaCenterFeatureIds.weatherStationNotes.caption,
    evidenceReferenceIds: [
      centralIdeaCenterSentenceIds.weatherStationNotes[0],
      centralIdeaCenterSentenceIds.weatherStationNotes[2],
    ],
    targetVocabulary: ['relevant detail', 'weather', 'chart'],
    soundOutChunks: ['re', 'le', 'vant'],
    tags: ['relevant-details', 'relevant-detail-identification'],
    choices: [
      choice('weather-thermometer', 'A thermometer tells the class if the air feels warmer or cooler.'),
      choice('weather-chart', 'The class records the numbers in a chart each afternoon.'),
      choice('weather-clouds', 'A student circles cloudy days on the chart so the group can check them later.'),
      choice('weather-wind', 'A wind sock points the direction the wind blows.'),
    ],
    correctChoiceIds: ['weather-thermometer', 'weather-chart'],
  }),
  createHotTextQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.weatherStationNotes.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.guidedPutImportantDetailsTogether,
    questionIdentifier: centralIdeaCenterQuestionIds.guidedPutImportantDetailsTogether[3],
    prompt: 'Tap the sentence that best helps readers understand the central idea.',
    explanation: 'This sentence brings the weather tools and notes together into one idea.',
    evidenceReference: centralIdeaCenterSentenceIds.weatherStationNotes[7],
    evidenceReferenceIds: [centralIdeaCenterSentenceIds.weatherStationNotes[7]],
    targetVocabulary: ['central idea'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['central-idea', 'stated-central-idea'],
    selectableSegments: [
      { id: centralIdeaCenterSentenceIds.weatherStationNotes[1], text: weatherStationSentences[1].text },
      { id: centralIdeaCenterSentenceIds.weatherStationNotes[4], text: weatherStationSentences[4].text },
      { id: centralIdeaCenterSentenceIds.weatherStationNotes[6], text: weatherStationSentences[6].text },
      { id: centralIdeaCenterSentenceIds.weatherStationNotes[7], text: weatherStationSentences[7].text },
    ],
    correctSegmentIds: [centralIdeaCenterSentenceIds.weatherStationNotes[7]],
  }),
  createTableMatchQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.weatherStationNotes.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.guidedPutImportantDetailsTogether,
    questionIdentifier: centralIdeaCenterQuestionIds.guidedPutImportantDetailsTogether[4],
    prompt: 'Match each statement to the best answer.',
    explanation: 'Each row matches a statement to the kind of information it gives.',
    evidenceReference: centralIdeaCenterFeatureIds.weatherStationNotes.glossary,
    evidenceReferenceIds: [
      centralIdeaCenterFeatureIds.weatherStationNotes.title,
      centralIdeaCenterSentenceIds.weatherStationNotes[7],
    ],
    targetVocabulary: ['topic', 'central idea', 'detail'],
    soundOutChunks: ['stat', 'e', 'ment'],
    tags: ['central-idea-and-evidence', 'most-relevant-details'],
    rows: [
      {
        id: 'weather-topic',
        prompt: 'What is the topic?',
        correctChoiceId: 'weather-topic-answer',
        options: [
          choice('weather-topic-answer', 'weather station notes'),
          choice('weather-topic-detail', 'A rain gauge shows how much rain fell overnight.'),
          choice('weather-topic-other', 'A student circles cloudy days on the chart.'),
        ],
      },
      {
        id: 'weather-central',
        prompt: 'What is the central idea?',
        correctChoiceId: 'weather-central-answer',
        options: [
          choice('weather-central-answer', 'With tools and careful observations, the class learns more about weather.'),
          choice('weather-central-other1', 'A thermometer tells the class if the air feels warmer or cooler.'),
          choice('weather-central-other2', 'The class records the numbers in a chart each afternoon.'),
        ],
      },
      {
        id: 'weather-other',
        prompt: 'Which is another true detail?',
        correctChoiceId: 'weather-other-answer',
        options: [
          choice('weather-other-answer', 'A wind sock points the direction the wind blows.'),
          choice('weather-other-topic', 'weather station notes'),
          choice('weather-other-central', 'With tools and careful observations, the class learns more about weather.'),
        ],
      },
    ],
  }),
] as const

