import {
  createEvidencePairQuestion,
  createHotTextQuestion,
  createMultipleChoiceQuestion,
  createMultiselectQuestion,
  createTableMatchQuestion,
  lessonChoice as choice,
} from './questionFactories'
import {
  centralIdeaCenterContentVersion,
  centralIdeaCenterFeatureIds,
  centralIdeaCenterLessonIds,
  centralIdeaCenterPassageIds,
  centralIdeaCenterQuestionIds,
  centralIdeaCenterSentenceIds,
} from './ids'
import { compostChangeSentences, seedTravelSentences, trailMarkerSentences } from './passages'

const base = {
  benchmarkReference: 'ELA.2.R.2.2' as const,
  skillIdentifier: 'g2-information-detectives-reading' as const,
  reportingCategory: 'Reading Informational Text' as const,
  genre: 'informational' as const,
  gradeBand: 2 as const,
  estimatedReadingLevel: 'Grade 2' as const,
  contentVersion: centralIdeaCenterContentVersion,
  reviewStatus: 'DRAFT' as const,
}

export const centralIdeaCenterCheckpointQuestions = [
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.seedTravelRoutes.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointA,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointA[0],
    prompt: 'What is the topic of this passage?',
    explanation: 'The topic is a short phrase that names what the passage is about.',
    evidenceReference: centralIdeaCenterFeatureIds.seedTravelRoutes.title,
    evidenceReferenceIds: [centralIdeaCenterFeatureIds.seedTravelRoutes.title],
    targetVocabulary: ['topic'],
    soundOutChunks: ['top', 'ic'],
    tags: ['central-idea', 'topic-vs-central-idea'],
    choices: [
      choice('seed-topic', 'seed travel routes'),
      choice('compost-topic', 'compost piles'),
      choice('trail-topic', 'trail markers'),
      choice('weather-topic', 'weather stations'),
    ],
    correctChoiceIds: ['seed-topic'],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.seedTravelRoutes.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointA,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointA[1],
    prompt: 'Which sentence is the best central idea?',
    explanation: 'The central idea is a complete thought about the topic.',
    evidenceReference: centralIdeaCenterFeatureIds.seedTravelRoutes.headingC,
    evidenceReferenceIds: [centralIdeaCenterFeatureIds.seedTravelRoutes.headingC],
    targetVocabulary: ['central idea', 'complete thought'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['central-idea', 'central-idea-complete-thought', 'inferred-central-idea'],
    choices: [
      choice('seed-detail-1', 'Some seeds are light and drift on the wind.'),
      choice('seed-central', 'Different seeds travel in different ways, and those trips help plants grow in new places.'),
      choice('seed-detail-2', 'A classroom map shows where the seeds traveled.'),
      choice('seed-detail-3', 'Birds may drop seeds after eating fruit.'),
    ],
    correctChoiceIds: ['seed-central'],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.seedTravelRoutes.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointA,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointA[2],
    prompt: 'Which detail is most relevant to the central idea?',
    explanation: 'This detail shows one way a seed can travel to a new place.',
    evidenceReference: centralIdeaCenterFeatureIds.seedTravelRoutes.caption,
    evidenceReferenceIds: [centralIdeaCenterSentenceIds.seedTravelRoutes[0]],
    targetVocabulary: ['relevant detail', 'travel'],
    soundOutChunks: ['re', 'le', 'vant'],
    tags: ['relevant-details', 'relevant-detail-identification'],
    choices: [
      choice('seed-water', 'Some float on water after a rain.'),
      choice('seed-room', 'That new spot can give the plant sun, soil, and room to grow.'),
      choice('seed-fur', 'Sticky seeds ride on fur or feathers.'),
      choice('seed-shoes', 'A few seeds even hitch a ride on shoes or socks.'),
    ],
    correctChoiceIds: ['seed-fur'],
  }),
  createMultiselectQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.seedTravelRoutes.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointA,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointA[3],
    prompt: 'Choose two details that are most relevant to the central idea.',
    explanation: 'These details show different ways seeds travel to new places.',
    evidenceReference: centralIdeaCenterFeatureIds.seedTravelRoutes.glossary,
    evidenceReferenceIds: [
      centralIdeaCenterSentenceIds.seedTravelRoutes[0],
      centralIdeaCenterSentenceIds.seedTravelRoutes[3],
    ],
    targetVocabulary: ['relevant detail', 'travel', 'new places'],
    soundOutChunks: ['re', 'le', 'vant'],
    tags: ['relevant-details', 'relevant-detail-identification'],
    choices: [
      choice('seed-wind', 'Some seeds are light and drift on the wind.'),
      choice('seed-water-detail', 'Some float on water after a rain.'),
      choice('seed-map', 'A classroom map shows where the seeds traveled.'),
      choice('seed-fur-detail', 'Sticky seeds ride on fur or feathers.'),
    ],
    correctChoiceIds: ['seed-wind', 'seed-fur-detail'],
  }),
  createHotTextQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.seedTravelRoutes.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointA,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointA[4],
    prompt: 'Tap the sentence that best helps readers understand the central idea.',
    explanation: 'This sentence puts the seed-travel details together into one idea.',
    evidenceReference: centralIdeaCenterSentenceIds.seedTravelRoutes[9],
    evidenceReferenceIds: [centralIdeaCenterSentenceIds.seedTravelRoutes[9]],
    targetVocabulary: ['central idea'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['central-idea', 'stated-central-idea'],
    selectableSegments: [
      { id: centralIdeaCenterSentenceIds.seedTravelRoutes[1], text: seedTravelSentences[1].text },
      { id: centralIdeaCenterSentenceIds.seedTravelRoutes[4], text: seedTravelSentences[4].text },
      { id: centralIdeaCenterSentenceIds.seedTravelRoutes[6], text: seedTravelSentences[6].text },
      { id: centralIdeaCenterSentenceIds.seedTravelRoutes[9], text: seedTravelSentences[9].text },
    ],
    correctSegmentIds: [centralIdeaCenterSentenceIds.seedTravelRoutes[9]],
  }),
  createTableMatchQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.seedTravelRoutes.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointA,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointA[5],
    prompt: 'Match each statement to the best answer.',
    explanation: 'Each row matches a statement to the idea it names.',
    evidenceReference: centralIdeaCenterFeatureIds.seedTravelRoutes.visual,
    evidenceReferenceIds: [
      centralIdeaCenterFeatureIds.seedTravelRoutes.caption,
      centralIdeaCenterFeatureIds.seedTravelRoutes.glossary,
    ],
    targetVocabulary: ['topic', 'central idea', 'detail'],
    soundOutChunks: ['stat', 'e', 'ment'],
    tags: ['central-idea-and-evidence', 'central-idea-from-details', 'most-relevant-details', 'relevant-details-across-sections'],
    rows: [
      {
        id: 'seed-topic',
        prompt: 'What is the topic?',
        correctChoiceId: 'seed-topic-answer',
        options: [
          choice('seed-topic-answer', 'seed travel routes'),
          choice('seed-topic-detail', 'A classroom map shows where the seeds traveled.'),
          choice('seed-topic-other', 'Birds may drop seeds after eating fruit.'),
        ],
      },
      {
        id: 'seed-central',
        prompt: 'What is the central idea?',
        correctChoiceId: 'seed-central-answer',
        options: [
          choice('seed-central-answer', 'Different seeds travel in different ways, and those trips help plants grow in new places.'),
          choice('seed-central-other1', 'Some float on water after a rain.'),
          choice('seed-central-other2', 'Sticky seeds ride on fur or feathers.'),
        ],
      },
      {
        id: 'seed-other',
        prompt: 'Which is another true detail?',
        correctChoiceId: 'seed-other-answer',
        options: [
          choice('seed-other-answer', 'A classroom map shows where the seeds traveled.'),
          choice('seed-other-topic', 'seed travel routes'),
          choice('seed-other-central', 'Different seeds travel in different ways, and those trips help plants grow in new places.'),
        ],
      },
    ],
  }),
  createEvidencePairQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.seedTravelRoutes.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointA,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointA[6],
    prompt: 'Choose the best answer for Part A and Part B.',
    explanation: 'The central idea names the main thought, and the detail shows one way seeds travel.',
    evidenceReference: centralIdeaCenterSentenceIds.seedTravelRoutes[9],
    evidenceReferenceIds: [
      centralIdeaCenterSentenceIds.seedTravelRoutes[0],
      centralIdeaCenterSentenceIds.seedTravelRoutes[3],
      centralIdeaCenterFeatureIds.seedTravelRoutes.visual,
    ],
    targetVocabulary: ['central idea', 'detail', 'evidence'],
    soundOutChunks: ['e', 'vi', 'dence'],
    tags: ['central-idea-and-evidence', 'central-idea-from-details', 'most-relevant-details', 'relevant-details-across-sections'],
    partAPrompt: 'What is the central idea of the text?',
    partAChoices: [
      choice('seed-part-a-1', 'Different seeds travel in different ways, and those trips help plants grow in new places.'),
      choice('seed-part-a-2', 'A classroom map shows where the seeds traveled.'),
      choice('seed-part-a-3', 'Some seeds are light and drift on the wind.'),
    ],
    partACorrectChoiceId: 'seed-part-a-1',
    partBPrompt: 'Which detail best supports that answer?',
    partBChoices: [
      choice('seed-part-b-1', 'Birds may drop seeds after eating fruit.'),
      choice('seed-part-b-2', 'Some seeds are light and drift on the wind.'),
      choice('seed-part-b-3', 'A classroom map shows where the seeds traveled.'),
    ],
    partBCorrectChoiceId: 'seed-part-b-2',
  }),

  createMultipleChoiceQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.compostChangeStory.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointB,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointB[0],
    prompt: 'What is the topic of this passage?',
    explanation: 'The topic is a short phrase that names what the passage is about.',
    evidenceReference: centralIdeaCenterFeatureIds.compostChangeStory.title,
    evidenceReferenceIds: [centralIdeaCenterFeatureIds.compostChangeStory.title],
    targetVocabulary: ['topic'],
    soundOutChunks: ['top', 'ic'],
    tags: ['central-idea', 'topic-vs-central-idea'],
    choices: [
      choice('compost-topic', 'compost piles'),
      choice('seed-topic', 'seed travel routes'),
      choice('weather-topic', 'weather station notes'),
      choice('trail-topic', 'trail markers'),
    ],
    correctChoiceIds: ['compost-topic'],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.compostChangeStory.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointB,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointB[1],
    prompt: 'Which sentence is the best central idea?',
    explanation: 'The central idea is the complete thought that the details point to.',
    evidenceReference: centralIdeaCenterSentenceIds.compostChangeStory[9],
    evidenceReferenceIds: [centralIdeaCenterSentenceIds.compostChangeStory[9]],
    targetVocabulary: ['central idea', 'complete thought'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['central-idea', 'central-idea-complete-thought', 'stated-central-idea'],
    choices: [
      choice('compost-detail-1', 'Tiny bugs and worms help break the pieces apart.'),
      choice('compost-detail-2', 'The class turns the pile so air can move through it.'),
      choice('compost-central', 'Composting changes scraps and leaves into material that helps soil.'),
      choice('compost-detail-3', 'The class watches the graph each week.'),
    ],
    correctChoiceIds: ['compost-central'],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.compostChangeStory.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointB,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointB[2],
    prompt: 'Which detail is most relevant to the central idea?',
    explanation: 'This detail shows how the compost pile changes over time.',
    evidenceReference: centralIdeaCenterFeatureIds.compostChangeStory.caption,
    evidenceReferenceIds: [centralIdeaCenterSentenceIds.compostChangeStory[7]],
    targetVocabulary: ['relevant detail', 'compost'],
    soundOutChunks: ['re', 'le', 'vant'],
    tags: ['relevant-details', 'relevant-detail-identification'],
    choices: [
      choice('compost-dark', 'The pile gets darker and crumbly over time.'),
      choice('compost-smell', 'When the pile changes, it smells less like food scraps and more like earth.'),
      choice('compost-scraps', 'Food scraps, leaves, and paper go into the pile.'),
      choice('compost-graph', 'A graph shows the pile warming up and then cooling down.'),
    ],
    correctChoiceIds: ['compost-scraps'],
  }),
  createMultiselectQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.compostChangeStory.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointB,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointB[3],
    prompt: 'Choose two details that are most relevant to the central idea.',
    explanation: 'These details show how scraps change into compost that helps soil.',
    evidenceReference: centralIdeaCenterFeatureIds.compostChangeStory.visual,
    evidenceReferenceIds: [
      centralIdeaCenterSentenceIds.compostChangeStory[1],
      centralIdeaCenterSentenceIds.compostChangeStory[7],
    ],
    targetVocabulary: ['relevant detail', 'soil', 'change'],
    soundOutChunks: ['re', 'le', 'vant'],
    tags: ['relevant-details', 'relevant-detail-identification'],
    choices: [
      choice('compost-bugs', 'Tiny bugs and worms help break the pieces apart.'),
      choice('compost-useful', 'The scraps become compost that helps plants grow.'),
      choice('compost-leaf', 'A teacher says the class can still see leaf bits in the pile.'),
      choice('compost-week', 'The class watches the graph each week.'),
    ],
    correctChoiceIds: ['compost-bugs', 'compost-useful'],
  }),
  createHotTextQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.compostChangeStory.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointB,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointB[4],
    prompt: 'Tap the sentence that best helps readers understand the central idea.',
    explanation: 'This sentence states the big idea about what happens in the pile.',
    evidenceReference: centralIdeaCenterSentenceIds.compostChangeStory[9],
    evidenceReferenceIds: [centralIdeaCenterSentenceIds.compostChangeStory[9]],
    targetVocabulary: ['central idea'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['central-idea', 'stated-central-idea'],
    selectableSegments: [
      { id: centralIdeaCenterSentenceIds.compostChangeStory[2], text: compostChangeSentences[2].text },
      { id: centralIdeaCenterSentenceIds.compostChangeStory[3], text: compostChangeSentences[3].text },
      { id: centralIdeaCenterSentenceIds.compostChangeStory[7], text: compostChangeSentences[7].text },
      { id: centralIdeaCenterSentenceIds.compostChangeStory[9], text: compostChangeSentences[9].text },
    ],
    correctSegmentIds: [centralIdeaCenterSentenceIds.compostChangeStory[9]],
  }),
  createTableMatchQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.compostChangeStory.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointB,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointB[5],
    prompt: 'Match each statement to the best answer.',
    explanation: 'Each row matches a statement to the idea it names.',
    evidenceReference: centralIdeaCenterFeatureIds.compostChangeStory.visual,
    evidenceReferenceIds: [
      centralIdeaCenterFeatureIds.compostChangeStory.caption,
      centralIdeaCenterFeatureIds.compostChangeStory.visual,
    ],
    targetVocabulary: ['topic', 'central idea', 'detail'],
    soundOutChunks: ['stat', 'e', 'ment'],
    tags: ['central-idea-and-evidence', 'central-idea-from-details', 'most-relevant-details', 'relevant-details-across-sections'],
    rows: [
      {
        id: 'compost-topic',
        prompt: 'What is the topic?',
        correctChoiceId: 'compost-topic-answer',
        options: [
          choice('compost-topic-answer', 'compost piles'),
          choice('compost-topic-detail', 'Tiny bugs and worms help break the pieces apart.'),
          choice('compost-topic-other', 'The class watches the graph each week.'),
        ],
      },
      {
        id: 'compost-central',
        prompt: 'What is the central idea?',
        correctChoiceId: 'compost-central-answer',
        options: [
          choice('compost-central-answer', 'Composting changes scraps and leaves into material that helps soil.'),
          choice('compost-central-other1', 'The pile gets darker and crumbly over time.'),
          choice('compost-central-other2', 'The class turns the pile so air can move through it.'),
        ],
      },
      {
        id: 'compost-other',
        prompt: 'Which is another true detail?',
        correctChoiceId: 'compost-other-answer',
        options: [
          choice('compost-other-answer', 'A teacher says the class can still see leaf bits in the pile.'),
          choice('compost-other-topic', 'compost piles'),
          choice('compost-other-central', 'Composting changes scraps and leaves into material that helps soil.'),
        ],
      },
    ],
  }),
  createEvidencePairQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.compostChangeStory.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointB,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointB[6],
    prompt: 'Choose the best answer for Part A and Part B.',
    explanation: 'The central idea names the main thought, and the detail shows the change in the pile.',
    evidenceReference: centralIdeaCenterSentenceIds.compostChangeStory[9],
    evidenceReferenceIds: [
      centralIdeaCenterSentenceIds.compostChangeStory[1],
      centralIdeaCenterSentenceIds.compostChangeStory[7],
      centralIdeaCenterFeatureIds.compostChangeStory.visual,
    ],
    targetVocabulary: ['central idea', 'detail', 'evidence'],
    soundOutChunks: ['e', 'vi', 'dence'],
    tags: ['central-idea-and-evidence', 'central-idea-from-details', 'most-relevant-details', 'relevant-details-across-sections'],
    partAPrompt: 'What is the central idea of the text?',
    partAChoices: [
      choice('compost-part-a-1', 'Composting changes scraps and leaves into material that helps soil.'),
      choice('compost-part-a-2', 'A graph shows the pile warming up and then cooling down.'),
      choice('compost-part-a-3', 'Tiny bugs and worms help break the pieces apart.'),
    ],
    partACorrectChoiceId: 'compost-part-a-1',
    partBPrompt: 'Which detail best supports that answer?',
    partBChoices: [
      choice('compost-part-b-1', 'The class turns the pile so air can move through it.'),
      choice('compost-part-b-2', 'Food scraps, leaves, and paper go into the pile.'),
      choice('compost-part-b-3', 'A teacher says the class can still see leaf bits in the pile.'),
    ],
    partBCorrectChoiceId: 'compost-part-b-2',
  }),

  createMultipleChoiceQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.trailMarkersGuideTheWay.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointC,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointC[0],
    prompt: 'What is the topic of this passage?',
    explanation: 'The topic is a short phrase that names what the passage is about.',
    evidenceReference: centralIdeaCenterFeatureIds.trailMarkersGuideTheWay.title,
    evidenceReferenceIds: [centralIdeaCenterFeatureIds.trailMarkersGuideTheWay.title],
    targetVocabulary: ['topic'],
    soundOutChunks: ['top', 'ic'],
    tags: ['central-idea', 'topic-vs-central-idea'],
    choices: [
      choice('trail-topic', 'trail markers'),
      choice('seed-topic', 'seed travel routes'),
      choice('weather-topic', 'weather station notes'),
      choice('compost-topic', 'compost piles'),
    ],
    correctChoiceIds: ['trail-topic'],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.trailMarkersGuideTheWay.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointC,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointC[1],
    prompt: 'Which sentence is the best central idea?',
    explanation: 'The central idea is the complete thought that the details point to.',
    evidenceReference: centralIdeaCenterSentenceIds.trailMarkersGuideTheWay[9],
    evidenceReferenceIds: [centralIdeaCenterSentenceIds.trailMarkersGuideTheWay[9]],
    targetVocabulary: ['central idea', 'complete thought'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['central-idea', 'central-idea-complete-thought', 'inferred-central-idea'],
    choices: [
      choice('trail-detail-1', 'Bright markers show which path to take.'),
      choice('trail-central', 'Trail markers help visitors stay on the right path and reach the end safely.'),
      choice('trail-detail-2', 'A few arrows point back toward the main loop.'),
      choice('trail-detail-3', 'The end sign shows where the path meets the parking area.'),
    ],
    correctChoiceIds: ['trail-central'],
  }),
  createMultipleChoiceQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.trailMarkersGuideTheWay.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointC,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointC[2],
    prompt: 'Which detail is most relevant to the central idea?',
    explanation: 'This detail shows how the markers help visitors know which way to go.',
    evidenceReference: centralIdeaCenterFeatureIds.trailMarkersGuideTheWay.caption,
    evidenceReferenceIds: [centralIdeaCenterSentenceIds.trailMarkersGuideTheWay[0]],
    targetVocabulary: ['relevant detail', 'trail'],
    soundOutChunks: ['re', 'le', 'vant'],
    tags: ['relevant-details', 'relevant-detail-identification'],
    choices: [
      choice('trail-map-detail', 'The map tells hikers where to turn and where the loop ends.'),
      choice('trail-safe-detail', 'The guide notices a fallen branch and marks the safe side path.'),
      choice('trail-marker-detail', 'Bright markers show which path to take.'),
      choice('trail-end-detail', 'The end sign shows where the path meets the parking area.'),
    ],
    correctChoiceIds: ['trail-marker-detail'],
  }),
  createMultiselectQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.trailMarkersGuideTheWay.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointC,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointC[3],
    prompt: 'Choose two details that are most relevant to the central idea.',
    explanation: 'These details show how the trail markers guide visitors safely.',
    evidenceReference: centralIdeaCenterFeatureIds.trailMarkersGuideTheWay.visual,
    evidenceReferenceIds: [
      centralIdeaCenterSentenceIds.trailMarkersGuideTheWay[1],
      centralIdeaCenterSentenceIds.trailMarkersGuideTheWay[7],
    ],
    targetVocabulary: ['relevant detail', 'safely', 'path'],
    soundOutChunks: ['re', 'le', 'vant'],
    tags: ['relevant-details', 'relevant-detail-identification'],
    choices: [
      choice('trail-turn', 'The map tells hikers where to turn and where the loop ends.'),
      choice('trail-safe', 'The guide notices a fallen branch and marks the safe side path.'),
      choice('trail-loop', 'Families can follow the same color marker all the way around.'),
      choice('trail-lost', 'Markers help walkers avoid getting lost.'),
    ],
    correctChoiceIds: ['trail-safe', 'trail-lost'],
  }),
  createHotTextQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.trailMarkersGuideTheWay.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointC,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointC[4],
    prompt: 'Tap the sentence that best helps readers understand the central idea.',
    explanation: 'This sentence puts the trail-marker details together into one idea.',
    evidenceReference: centralIdeaCenterSentenceIds.trailMarkersGuideTheWay[9],
    evidenceReferenceIds: [centralIdeaCenterSentenceIds.trailMarkersGuideTheWay[9]],
    targetVocabulary: ['central idea'],
    soundOutChunks: ['cen', 'tral', 'idea'],
    tags: ['central-idea', 'stated-central-idea'],
    selectableSegments: [
      { id: centralIdeaCenterSentenceIds.trailMarkersGuideTheWay[1], text: trailMarkerSentences[1].text },
      { id: centralIdeaCenterSentenceIds.trailMarkersGuideTheWay[4], text: trailMarkerSentences[4].text },
      { id: centralIdeaCenterSentenceIds.trailMarkersGuideTheWay[7], text: trailMarkerSentences[7].text },
      { id: centralIdeaCenterSentenceIds.trailMarkersGuideTheWay[9], text: trailMarkerSentences[9].text },
    ],
    correctSegmentIds: [centralIdeaCenterSentenceIds.trailMarkersGuideTheWay[9]],
  }),
  createTableMatchQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.trailMarkersGuideTheWay.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointC,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointC[5],
    prompt: 'Match each statement to the best answer.',
    explanation: 'Each row matches a statement to the idea it names.',
    evidenceReference: centralIdeaCenterFeatureIds.trailMarkersGuideTheWay.visual,
    evidenceReferenceIds: [
      centralIdeaCenterFeatureIds.trailMarkersGuideTheWay.caption,
      centralIdeaCenterFeatureIds.trailMarkersGuideTheWay.visual,
    ],
    targetVocabulary: ['topic', 'central idea', 'detail'],
    soundOutChunks: ['stat', 'e', 'ment'],
    tags: ['central-idea-and-evidence', 'central-idea-from-details', 'most-relevant-details', 'relevant-details-across-sections'],
    rows: [
      {
        id: 'trail-topic',
        prompt: 'What is the topic?',
        correctChoiceId: 'trail-topic-answer',
        options: [
          choice('trail-topic-answer', 'trail markers'),
          choice('trail-topic-detail', 'Bright markers show which path to take.'),
          choice('trail-topic-other', 'The end sign shows where the path meets the parking area.'),
        ],
      },
      {
        id: 'trail-central',
        prompt: 'What is the central idea?',
        correctChoiceId: 'trail-central-answer',
        options: [
          choice('trail-central-answer', 'Trail markers help visitors stay on the right path and reach the end safely.'),
          choice('trail-central-other1', 'The map tells hikers where to turn and where the loop ends.'),
          choice('trail-central-other2', 'Families can follow the same color marker all the way around.'),
        ],
      },
      {
        id: 'trail-other',
        prompt: 'Which is another true detail?',
        correctChoiceId: 'trail-other-answer',
        options: [
          choice('trail-other-answer', 'The end sign shows where the path meets the parking area.'),
          choice('trail-other-topic', 'trail markers'),
          choice('trail-other-central', 'Trail markers help visitors stay on the right path and reach the end safely.'),
        ],
      },
    ],
  }),
  createEvidencePairQuestion({
    ...base,
    difficulty: 2,
    passageIdentifier: centralIdeaCenterPassageIds.trailMarkersGuideTheWay.passageId,
    lessonIdentifier: centralIdeaCenterLessonIds.checkpointC,
    questionIdentifier: centralIdeaCenterQuestionIds.checkpointC[6],
    prompt: 'Choose the best answer for Part A and Part B.',
    explanation: 'The central idea names the main thought, and the detail shows how the markers guide walkers.',
    evidenceReference: centralIdeaCenterSentenceIds.trailMarkersGuideTheWay[9],
    evidenceReferenceIds: [
      centralIdeaCenterSentenceIds.trailMarkersGuideTheWay[1],
      centralIdeaCenterSentenceIds.trailMarkersGuideTheWay[7],
      centralIdeaCenterFeatureIds.trailMarkersGuideTheWay.visual,
    ],
    targetVocabulary: ['central idea', 'detail', 'evidence'],
    soundOutChunks: ['e', 'vi', 'dence'],
    tags: ['central-idea-and-evidence', 'central-idea-from-details'],
    partAPrompt: 'What is the central idea of the text?',
    partAChoices: [
      choice('trail-part-a-1', 'Trail markers help visitors stay on the right path and reach the end safely.'),
      choice('trail-part-a-2', 'The map tells hikers where to turn and where the loop ends.'),
      choice('trail-part-a-3', 'Bright markers show which path to take.'),
    ],
    partACorrectChoiceId: 'trail-part-a-1',
    partBPrompt: 'Which detail best supports that answer?',
    partBChoices: [
      choice('trail-part-b-1', 'The end sign shows where the path meets the parking area.'),
      choice('trail-part-b-2', 'Bright markers show which path to take.'),
      choice('trail-part-b-3', 'Families can follow the same color marker all the way around.'),
    ],
    partBCorrectChoiceId: 'trail-part-b-2',
  }),
] as const
