import type { ContentPack, ContentPackLesson } from '../../../contentPackTypes'
import {
  grade3AcademicVocabularyArtifacts,
  grade3AcademicVocabularyGuides,
  grade3AcademicWordWorkshopPassages,
} from './content'
import {
  grade3AcademicWordWorkshopContentVersion,
  grade3AcademicWordWorkshopLessonIds,
  grade3AcademicWordWorkshopPackId,
  grade3AcademicWordWorkshopPrimarySkillId,
  grade3AcademicWordWorkshopQuestionIds,
  grade3AcademicWordWorkshopUnitId,
  grade3AcademicWordWorkshopWorldId,
} from './ids'
import { grade3AcademicWordWorkshopQuestions } from './questions'

const lessonPlans = [
  {
    lessonId: grade3AcademicWordWorkshopLessonIds.wordsForSchoolThinking,
    activityId: 'activity-g3-cc-aww-words-for-school-thinking',
    difficulty: 0,
    passage: grade3AcademicVocabularyArtifacts.scienceInvestigation.passage,
    questionIds: grade3AcademicWordWorkshopQuestionIds.wordsForSchoolThinking,
    lessonTitle: 'Academic Word Workshop Power-Up: Words for School Thinking',
    lessonObjective: 'Recognize academic words that help students study information and explain a conclusion.',
    teachingBlock: {
      title: 'Academic words name thinking jobs',
      explanation: 'A precise academic word tells what school task is happening. Check the meaning, the sentence job, and the subject context before choosing.',
      examples: [
        'Analyze means study information closely for a pattern.',
        'Evidence is information that supports an idea.',
        'Conclude means decide what makes sense after checking information.',
      ],
      contrast: 'An interesting detail is not evidence unless it helps answer the question.',
      learnerCue: 'Ask: What thinking job is the student doing?',
    },
  },
  {
    lessonId: grade3AcademicWordWorkshopLessonIds.chooseThePreciseWord,
    activityId: 'activity-g3-cc-aww-choose-the-precise-word',
    difficulty: 0,
    passage: grade3AcademicVocabularyArtifacts.mathematicsModel.passage,
    questionIds: grade3AcademicWordWorkshopQuestionIds.chooseThePreciseWord,
    lessonTitle: 'Academic Word Workshop Power-Up: Choose the Precise Word',
    lessonObjective: 'Distinguish approximate, exact, model-based, and evidence-based mathematics words.',
    teachingBlock: {
      title: 'Nearby words do different jobs',
      explanation: 'Estimate, represent, determine, and justify can all appear in math, but each word names a different job.',
      examples: [
        'Estimate gives a reasonable approximate answer.',
        'Represent shows one thing in another form.',
        'Justify explains why an answer makes sense with reasons.',
      ],
      contrast: 'A word can be related to the topic and still be wrong for the sentence job.',
      learnerCue: 'Check both the meaning and the grammar of the whole sentence.',
    },
  },
  {
    lessonId: grade3AcademicWordWorkshopLessonIds.explainAndSupport,
    activityId: 'activity-g3-cc-aww-explain-and-support',
    difficulty: 1,
    passage: grade3AcademicVocabularyArtifacts.readingDiscussion.passage,
    questionIds: grade3AcademicWordWorkshopQuestionIds.explainAndSupport,
    lessonTitle: 'Academic Word Workshop Lab: Explain and Support',
    lessonObjective: 'Use precise academic words to discuss clues, meaning, important ideas, and evidence.',
    teachingBlock: {
      title: 'Move from clues to a supported explanation',
      explanation: 'Readers infer an unstated idea, interpret meaning, summarize important information, and support ideas with useful details.',
      examples: [
        'I infer ___ from the clue ___.',
        'I interpret the image to mean ___.',
        'This detail supports the idea that ___.',
      ],
      contrast: 'Copying a stated fact is not inferring, and listing every detail is not summarizing.',
      learnerCue: 'Name the exact reading or discussion job.',
    },
  },
  {
    lessonId: grade3AcademicWordWorkshopLessonIds.organizeAndRevise,
    activityId: 'activity-g3-cc-aww-organize-and-revise',
    difficulty: 1,
    passage: grade3AcademicVocabularyArtifacts.writingRevision.passage,
    questionIds: grade3AcademicWordWorkshopQuestionIds.organizeAndRevise,
    lessonTitle: 'Academic Word Workshop Lab: Organize and Revise',
    lessonObjective: 'Choose words that precisely describe improving, clarifying, and arranging school writing.',
    teachingBlock: {
      title: 'Choose the word for the writing change',
      explanation: 'Revise is the broad act of improving work. Clarify makes meaning easier to understand. Organize is an action, while structure names the arrangement.',
      examples: [
        'I revised the paragraph by adding evidence.',
        'The label clarifies the diagram.',
        'The report structure has three connected sections.',
      ],
      contrast: 'Reading an unchanged draft again is not revision.',
      learnerCue: 'Ask what changed and why it changed.',
    },
  },
] as const

const guidedLessons: ContentPackLesson[] = lessonPlans.map((plan) => ({
  lessonId: plan.lessonId,
  worldId: grade3AcademicWordWorkshopWorldId,
  unitId: grade3AcademicWordWorkshopUnitId,
  activityId: plan.activityId,
  difficulty: plan.difficulty,
  passageIdentifiers: [plan.passage.passageIdentifier],
  questionIdentifiers: [...plan.questionIds],
  lessonTitle: plan.lessonTitle,
  lessonObjective: plan.lessonObjective,
  lessonRole: 'GUIDED_PRACTICE',
  selectionStatus: 'active',
  teachingBlock: {
    ...plan.teachingBlock,
    examples: [...plan.teachingBlock.examples],
  },
  contentVersion: grade3AcademicWordWorkshopContentVersion,
  eligiblePurposes: ['remediation', 'review'],
}))

const checkpointLessons: ContentPackLesson[] = [
  {
    lessonId: grade3AcademicWordWorkshopLessonIds.scienceAndMathCheckpoint,
    worldId: grade3AcademicWordWorkshopWorldId,
    unitId: grade3AcademicWordWorkshopUnitId,
    activityId: 'activity-g3-cc-aww-science-and-math-checkpoint',
    difficulty: 1,
    passageIdentifiers: [grade3AcademicVocabularyArtifacts.engineeringInvestigation.passage.passageIdentifier],
    questionIdentifiers: [...grade3AcademicWordWorkshopQuestionIds.scienceAndMathCheckpoint],
    lessonTitle: 'Academic Word Workshop Checkpoint: Science and Math Words',
    lessonObjective: 'Select precise academic words for investigation, mathematics, speaking, and writing tasks.',
    lessonRole: 'CHECKPOINT',
    selectionStatus: 'active',
    contentVersion: grade3AcademicWordWorkshopContentVersion,
    eligiblePurposes: ['progression', 'verification', 'review'],
  },
  {
    lessonId: grade3AcademicWordWorkshopLessonIds.readingAndWritingCheckpoint,
    worldId: grade3AcademicWordWorkshopWorldId,
    unitId: grade3AcademicWordWorkshopUnitId,
    activityId: 'activity-g3-cc-aww-reading-and-writing-checkpoint',
    difficulty: 1,
    passageIdentifiers: [grade3AcademicVocabularyArtifacts.sourceDiscussion.passage.passageIdentifier],
    questionIdentifiers: [...grade3AcademicWordWorkshopQuestionIds.readingAndWritingCheckpoint],
    lessonTitle: 'Academic Word Workshop Checkpoint: Reading and Writing Words',
    lessonObjective: 'Select precise words for source discussion, reading responses, and academic writing.',
    lessonRole: 'CHECKPOINT',
    selectionStatus: 'active',
    contentVersion: grade3AcademicWordWorkshopContentVersion,
    eligiblePurposes: ['progression', 'verification', 'review'],
  },
  {
    lessonId: grade3AcademicWordWorkshopLessonIds.acrossSubjectsCheckpoint,
    worldId: grade3AcademicWordWorkshopWorldId,
    unitId: grade3AcademicWordWorkshopUnitId,
    activityId: 'activity-g3-cc-aww-across-subjects-checkpoint',
    difficulty: 1,
    passageIdentifiers: [grade3AcademicVocabularyArtifacts.projectPresentation.passage.passageIdentifier],
    questionIdentifiers: [...grade3AcademicWordWorkshopQuestionIds.acrossSubjectsCheckpoint],
    lessonTitle: 'Academic Word Workshop Checkpoint: Words Across Subjects',
    lessonObjective: 'Transfer precise academic vocabulary across project, science, mathematics, reading, and writing contexts.',
    lessonRole: 'CHECKPOINT',
    selectionStatus: 'active',
    contentVersion: grade3AcademicWordWorkshopContentVersion,
    eligiblePurposes: ['progression', 'verification', 'review'],
  },
]

export const grade3AcademicWordWorkshopLessons: ContentPackLesson[] = [...guidedLessons, ...checkpointLessons]

export const grade3ContextCavernAcademicWordWorkshopPack: ContentPack = {
  manifest: {
    packId: grade3AcademicWordWorkshopPackId,
    packTitle: 'Grade 3 Context Cavern: Academic Word Workshop',
    gradeBand: 3,
    worldId: grade3AcademicWordWorkshopWorldId,
    unitId: grade3AcademicWordWorkshopUnitId,
    primarySkillId: grade3AcademicWordWorkshopPrimarySkillId,
    benchmarkReferences: [],
    supportingBenchmarkReferences: ['ELA.3.V.1.1'],
    partialBenchmarkCoverage: 'Constrained Grade 3 practice recognizing and selecting appropriate academic vocabulary use across speaking and writing contexts in multiple school subjects, without unrestricted response scoring or a claim of productive vocabulary mastery.',
    difficultyRange: [0, 1],
    contentVersion: grade3AcademicWordWorkshopContentVersion,
    reviewStatus: 'DRAFT',
    coverageKind: 'supportive_practice',
    lessonIds: grade3AcademicWordWorkshopLessons.map((lesson) => lesson.lessonId),
    passageIds: grade3AcademicWordWorkshopPassages.map((passage) => passage.passageIdentifier),
    questionIds: grade3AcademicWordWorkshopQuestions.map((question) => question.questionIdentifier),
    coveredPatterns: [
      'grade-level-academic-vocabulary',
      'appropriate-use',
      'speaking-writing-support',
      'no-open-response-scoring',
    ],
  },
  passages: grade3AcademicWordWorkshopPassages,
  questions: grade3AcademicWordWorkshopQuestions,
  lessons: grade3AcademicWordWorkshopLessons,
  grade3AcademicVocabularyGuides,
}
