import { contentPacks } from './registry'
import { buildFluencyPracticeAudit, buildGrade3FluencyPracticeAudit } from './fluencyPracticeAudit'

export * from './contentPackTypes'
export * from './contentPackAudit'
export * from './rootDecodingGuideAudit'
export * from './derivationalSuffixGuideAudit'
export * from './multisyllableDecodingGuideAudit'
export * from './characterDevelopmentGuideAudit'
export * from './themeDevelopmentGuideAudit'
export * from './characterPerspectiveGuideAudit'
export * from './poemFormGuideAudit'
export * from './informationalStructureGuideAudit'
export * from './centralIdeaEngineGuideAudit'
export * from './purposeDevelopmentGuideAudit'
export * from './authorClaimGuideAudit'
export * from './figurativeLanguageGuideAudit'
export * from './grade3SummaryGuideAudit'
export * from './grade3AuthorComparisonGuideAudit'
export * from './grade3AcademicVocabularyGuideAudit'
export * from './rootMeaningGuideAudit'
export * from './fluencyPracticeAudit'
export * from './legacyDevelopmentPack'
export * from './grade2/wordForge/consonantLeIntegrated'
export * from './grade2/wordForge/silentLetterCombinations'
export * from './grade2/wordForge/fluencyPracticeFoundations'
export * from './grade2/storyScouts/plotStructureElements'
export * from './grade2/storyScouts/themeTrail'
export * from './grade2/storyScouts/perspectivePortal'
export * from './grade2/poetryPlanet/rhymeRoutes'
export * from './grade2/contextCavern/academicWordWorkshop'
export * from './grade2/contextCavern/morphologyMine'
export * from './grade2/contextCavern/meaningClueChamber'
export * from './grade2/compareCastle/wordplayWatchtower'
export * from './grade2/compareCastle/retellHall'
export * from './grade2/compareCastle/compareKeep'
export * from './grade3/wordForge/rootReactor'
export * from './grade3/wordForge/suffixShifter'
export * from './grade3/wordForge/multisyllableMountain'
export * from './grade3/wordForge/fluencyFlight'
export * from './grade3/storyScouts/characterArcCamp'
export * from './grade3/storyScouts/themeDevelopmentTrail'
export {
  characterPerspectiveGuides,
  perspectivePortalCoveragePatterns,
  perspectivePortalPack,
  perspectivePortalStories as grade3PerspectivePortalStories,
  perspectivePortalPassages as grade3PerspectivePortalPassages,
  perspectivePortalQuestions as grade3PerspectivePortalQuestions,
  perspectivePortalLessons as grade3PerspectivePortalLessons,
} from './grade3/storyScouts/perspectivePortal'
export * from './grade3/poetryPlanet/poemFormObservatory'
export * from './grade3/informationDetectives/structureStation'
export * from './grade3/informationDetectives/centralIdeaEngine'
export * from './grade3/informationDetectives/purposeDevelopmentPath'
export * from './grade3/informationDetectives/claimEvidenceCourt'
export * from './grade3/compareCastle/figurativeFortress'
export * from './grade3/compareCastle/summaryStronghold'
export * from './grade3/compareCastle/authorLensTower'
export * from './grade3/contextCavern/academicWordWorkshop'
export * from './grade3/contextCavern/rootMeaningVault'
export * from './registry'

export const fluencyPracticeAudit = buildFluencyPracticeAudit(contentPacks)
export const grade3FluencyPracticeAudit = buildGrade3FluencyPracticeAudit(contentPacks)
