import { sampleContent as legacyDevelopmentSampleContent } from '../sampleContent'
import type { ContentPack } from './contentPackTypes'

export const legacyDevelopmentPack: ContentPack = {
  manifest: {
    packId: 'legacy-word-forge-development-pack',
    packTitle: 'Legacy Word Forge Development Pack',
    gradeBand: 2,
    worldId: 'word-forge',
    unitId: 'wg-unit-1',
    primarySkillId: 'g2-word-forge-word-practice',
    benchmarkReferences: ['RR-G2-WF-01'],
    partialBenchmarkCoverage: 'legacy bridge practice',
    difficultyRange: [0, 1],
    contentVersion: 'r0.1.0',
    reviewStatus: 'DRAFT',
    coveredPatterns: ['legacy-bridge'],
    passageIds: legacyDevelopmentSampleContent.passages.map((passage) => passage.passageIdentifier),
    questionIds: legacyDevelopmentSampleContent.questions.map((question) => question.questionIdentifier),
    lessonIds: [
      'lesson-word-forge-vowel-voyage-a',
      'lesson-word-forge-vowel-voyage-b',
      'lesson-word-forge-vowel-voyage-c',
      'lesson-word-forge-building-block',
    ],
  },
  passages: legacyDevelopmentSampleContent.passages,
  questions: legacyDevelopmentSampleContent.questions,
  lessons: [
    {
      lessonId: 'lesson-word-forge-vowel-voyage-a',
      worldId: 'word-forge',
      unitId: 'wg-unit-1',
      activityId: 'activity-word-forge-trail-1-a',
      difficulty: 1,
      passageIdentifiers: ['passage-word-forge-bridge-a'],
      questionIdentifiers: [
        'q-word-forge-vowel-voyage-a-1',
        'q-word-forge-vowel-voyage-a-2',
        'q-word-forge-vowel-voyage-a-3',
        'q-word-forge-vowel-voyage-a-4',
      ],
      lessonTitle: 'Vowel Voyage: Kite Clues',
      lessonObjective: 'Collect clues from a short kite passage and prove each choice with text.',
      lessonRole: 'CHECKPOINT',
      selectionStatus: 'legacy',
      contentVersion: 'r0.1.0',
      eligiblePurposes: ['remediation', 'review'],
    },
    {
      lessonId: 'lesson-word-forge-vowel-voyage-b',
      worldId: 'word-forge',
      unitId: 'wg-unit-1',
      activityId: 'activity-word-forge-trail-1-b',
      difficulty: 1,
      passageIdentifiers: ['passage-word-forge-bridge-b'],
      questionIdentifiers: [
        'q-word-forge-vowel-voyage-b-2',
        'q-word-forge-vowel-voyage-b-4',
        'q-word-forge-vowel-voyage-b-5',
      ],
      lessonTitle: 'Vowel Voyage: Seed Clues',
      lessonObjective: 'Use details from a short seed passage to explain careful steps.',
      lessonRole: 'CHECKPOINT',
      selectionStatus: 'legacy',
      contentVersion: 'r0.1.0',
      eligiblePurposes: ['remediation', 'review'],
    },
    {
      lessonId: 'lesson-word-forge-vowel-voyage-c',
      worldId: 'word-forge',
      unitId: 'wg-unit-1',
      activityId: 'activity-word-forge-trail-1-c',
      difficulty: 1,
      passageIdentifiers: ['passage-word-forge-bridge-a'],
      questionIdentifiers: [
        'q-word-forge-vowel-voyage-a-5',
        'q-word-forge-vowel-voyage-a-6',
      ],
      lessonTitle: 'Vowel Voyage: Team Clues',
      lessonObjective: 'Find what happened and connect a team lesson to passage evidence.',
      lessonRole: 'CHECKPOINT',
      selectionStatus: 'legacy',
      contentVersion: 'r0.1.0',
      eligiblePurposes: ['remediation', 'review'],
    },
    {
      lessonId: 'lesson-word-forge-building-block',
      worldId: 'word-forge',
      unitId: 'wg-unit-1',
      activityId: 'activity-word-forge-trail-0-a',
      difficulty: 0,
      passageIdentifiers: ['passage-word-forge-bridge-b'],
      questionIdentifiers: ['q-word-forge-vowel-voyage-b-1'],
      lessonTitle: 'Building Block: Careful Clues',
      lessonObjective: 'Practice finding one clear detail before returning to the trail.',
      lessonRole: 'CHECKPOINT',
      selectionStatus: 'legacy',
      contentVersion: 'r0.1.0',
      eligiblePurposes: ['remediation', 'review'],
    },
  ],
}
